### ISSUE TITLE
[RFC 0001] MVP

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#1]
### Abstract

We would like to create a basic CLI for Supabase. At this stage we can assume that the user won't need to create orgs/projects from the CLI, but they will need to:

-  develop locally
- push database migrations to their Postgres database

[Rendered](https://github.com/supabase/cli/blob/main/rfcs/0001-mvp.md)

**Comment by steve-chavez** [comment]
Oh, for this workflow to work, the RFC needs to be a PR. That way we can comment on individual lines.

**Comment by kiwicopple** [comment]
Makes a lot more sense!
