### ISSUE TITLE
`supabase start` does not wait for responding to `allow incoming network connections` dialog in macOS

### ISSUE THREAD

**Issue by osaxma** [supabase/cli#100]
# Bug report

## Describe the bug
Whenever I call `supabase start`, the following system dialog flashes before I can respond to it:

<img width="273" alt="Screen Shot 2021-12-08 at 1 56 28 AM" src="https://user-images.githubusercontent.com/46427323/145225536-40b88f76-fe84-47be-b92b-81d93a900749.png">

## To Reproduce

Video that shows the behavior:

https://user-images.githubusercontent.com/46427323/145225123-dcef51c8-9dd0-4c3c-91f3-1c3e159d5ba1.mov

## Expected behavior

The cli should wait until the user respond to the dialog. 

## System information

- OS: macOS BigSur 11.6.1 (20G224)
- supabase cli version: `0.15.5%` <~~ the `%` was part of `supabase --version` output

**Comment by osaxma** [comment]
Yeah I installed via this command:

```
 brew install supabase/tap/supabase  
```

For reference, I was able to allow the incoming connections manually doing the following:

Go to Settings -> Security & Privacy -> Firewall -> Firewall Options -> then:
<img width="671" alt="Screen Shot 2021-12-09 at 7 11 29 PM" src="https://user-images.githubusercontent.com/46427323/145433756-fdf9c43c-7e9d-4fa2-aa22-ede8d5ca39b3.png">

Tho after I ran `brew upgrade supabase`, I had to do it again.

**Comment by osaxma** [comment]
Actually the dialog still flashes even after adding `supabase` command to the list in the screenshot above.

**Comment by soedirgo** [comment]
Ah, I think I got this. Something to do with the port checking code. Will push a fix tomorrow - thanks for reporting this!
