### ISSUE TITLE
Error creating function with leakproof attribute

### ISSUE THREAD

**Issue by sweatybridge** [supabase/cli#1011]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This attribute requires superuser https://www.postgresql.org/docs/current/sql-createfunction.html

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/orgs/supabase/discussions/9314#discussioncomment-5652328

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by soedirgo** [comment]
There's no plan to allow creating leakproof functions for the time being.

**Comment by psteinroe** [comment]
@soedirgo any reason to not allow it? security?

**Comment by soedirgo** [comment]
Yup, it currently requires superuser, though there's talk on making this available to non-superusers on the [Postgres mailing list](https://postgrespro.com/list/thread-id/2546682).

**Comment by microfauna** [comment]
It's been a few years since this thread had any activity, but commenting to say that leakproof functions could be a real performance boon for RLS!
