### ISSUE TITLE
v1.50.4 unusable due to edge functions timeout while caching deps

### ISSUE THREAD

**Issue by evelant** [supabase/cli#1012]
# Bug report

- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

edge-functions are unusable on latest versions of the CLI. They time out while caching deps then become totally unavailable until restarted at which point they will time out again.

See issue at edge-runtime for more detail https://github.com/supabase/edge-runtime/issues/44 Also filing it here because I'm not sure if the bug is in cli or the runtime.

## To Reproduce

1. `supabase start`
2. call any edge function with more than a handful of deps
3. observe timeout error while caching deps
4. observe that all further requests fail instantly

## Expected behavior

1. There should not be a timeout error while caching deps or there should be a mechanism to pre-cache them
2. If an error/timeout occurs the edge functions should not refuse all further requests

## System information

- OS: macos
- Browser (if applies) N/A
- Version of supabase 1.50.4
- Version of Node.js: 16.19.0

**Comment by evelant** [comment]
@sweatybridge @soedirgo Have you been able to reproduce this? It's blocking me (and others, see the linked issue https://github.com/supabase/edge-runtime/issues/44) from using versions of the supabase cli above 1.49.4. Specifically I was hoping to try out vault but it's not included in the images referenced by the older cli.

**Comment by evelant** [comment]
@sweatybridge @soedirgo the supabase cli is still unusable in v1.50.10 due to these bugs. As I detailed above, it appears that if an edge function times out or fails for any reason then the edge functions container becomes completely broken and instantly returns
 ```

hyper::Error(User(Service), operation was canceled: connection was not ready
 Caused by:
   connection was not ready)
```

**Comment by sweatybridge** [comment]
Apologies for the inconvenience caused. I've pinged the functions team to take a look at this once they have some bandwidth.

**Comment by laktek** [comment]
@evelant Do you still experience this with the latest CLI release? (1.61.X)

**Comment by evelant** [comment]
No, it seems to work correctly now, thanks!

**Comment by laktek** [comment]
Cool! closing this issue.
