### ISSUE TITLE
Deploy fails if function is importing from parent directory

### ISSUE THREAD

**Issue by israelidanny** [supabase/cli#1016]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a monorepo-like setup where multiple Deno packages are all sharing one `import_map.json` and some common types and utilities. I have a special 'common' import map entry defined that contains some of that stuff. I also tried just a simple parent relative path.

I put my supabase folder in that same repository, and it works fine, except when trying to reference those common types in a function.

Then it does something like:
```
Error: Error bundling function: exit status 1
file:///src/import_map.json
file:///src/index.ts
file:///types/identifiers.ts
error: Uncaught Error: NotFound: No such file or directory (os error 2)
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)
```

Where path to `types` is actually: 
```
import { ItemId } from "../../../types/identifiers.ts";
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Put `supabase` in a folder that also has some other Deno sources
2. Create a function
3. Import something from the parent folder

## Expected behavior

I would expect it to bundle code, just like it does with URLs

## System information

- OS:  macOS

**Comment by sweatybridge** [comment]
Hi @israelidanny , it's unlikely that we will support importing from parent directory as the CLI has to assume a top level directory where deno functions are defined. Currently this is hardcoded as `supabase/functions`.

One workaround I can think of is to move any common files to `supabase/functions` and have other deno sources import from there. For example. in your case that would be `supabase/functions/types/identifiers.ts` and other sources can import like this:

```typescript
import { ItemId } from "supabase/functions/types/identifiers.ts";
```
