### ISSUE TITLE
Supabase start: Error response from daemon: pull access denied for public.ecr.aws/supabase/postgres

### ISSUE THREAD

**Issue by sashchukalex** [supabase/cli#1025]
# Bug report

## Describe the bug

I try to run the Supabase project locally and it can not pull images from AWS ECR. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new project 
2. Generate new access token on https://app.supabase.com/account/tokens
3. Install the Supabase CLI on MacOs `brew install supabase/tap/supabase`
4. Run `supabase login` and provide generated access token
5. Run `supabase init`
6. Run `supabase start`

## Expected behavior
Supabase services are running, I will see output containing my local Supabase credentials. 

## Screenshots
![Screenshot 2023-04-19 at 13 07 37](https://user-images.githubusercontent.com/103134656/233043389-0e30512e-043c-4dde-a985-76cecd1fbced.png)
![Screenshot 2023-04-19 at 13 08 05](https://user-images.githubusercontent.com/103134656/233043401-49be2214-7054-4a87-8a22-fbd3610668c0.png)

With `--debug` flag 
![image](https://user-images.githubusercontent.com/103134656/233043723-13387caa-36ae-4606-b969-2e3699a92280.png)

## System information

- OS: Apple Macbook M2 Pro
- Version of supabase-js: 1.50.9
- Version of Node.js: v18.14.2

**Comment by sweatybridge** [comment]
Hi @sashchukalex, we will look into this issue. As a temporary workaround, you can specify an alternate registry:

```bash
SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start
```

**Comment by sashchukalex** [comment]
> Hi @sashchukalex, we will look into this issue. As a temporary workaround, you can specify an alternate registry:
> 
> ```shell
> SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start
> ```

Thanks a lot for this workaround! It works now.

**Comment by sweatybridge** [comment]
Could you share with me the docker auth configs to help debug?

```bash
$ cat ~/.docker/config.json
{
	"auths": {
		"ghcr.io": {},
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "desktop"
}
```

I suspect there are entries for AWS ECR that caused expired auth tokens to be injected when pulling images.

**Comment by sweatybridge** [comment]
Yup, I think your can run `docker logout public.ecr.aws` to fix this issue. Our images are public so they can be pulled anonymously.

**Comment by sashchukalex** [comment]
> Yup, I think your can run `docker logout public.ecr.aws` to fix this issue. Our images are public so they can be pulled anonymously.

Thank you! It works 👍
