### ISSUE TITLE
Can't import local code into edge functions development container

### ISSUE THREAD

**Issue by evelant** [supabase/cli#1040]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When developing edge functions the local docker container cannot access code imported from outside the `supabase/functions` folder. This makes it difficult to work with isomorphic library code shared between edge functions and the app.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add an import map entry referencing some local code
```json
{
    "imports": {
        "my-shared-package": "../../myapp-shared/my-shared-package"
    }
}
```
2. This can be deployed successfully because code gets bundled
3. This cannot be run in development because the deno-relay docker container cannot access the path

## Expected behavior

`supabase-cli` should read `import_map.json` for any local paths and mount those to the docker container relative to the function source. This would make local development work.

## Screenshots

N/A

## System information

- OS: MacOS
- Browser (if applies) N/A
- Version of supabase-cli: 1.49.4 (cannot use latest due to https://github.com/supabase/edge-runtime/issues/44)
- Version of Node.js: 16.19.0

## Additional context

The only workaround I could find for this problem isn't a very good one. To work around it I changed import map to import my shared code directly from github

```json
{
    "imports": {
        "my-shared-package": "https://raw.githubusercontent.com/myuser/myproject/mybranch/packages/my-shared-package"
    }
}
```
I also added DENO_AUTH_TOKENS to my `.env` so the private repo would be accessible.

This is not a great solution obviously because local changes to shared code aren't reflected until they're pushed to the referenced branch and the Deno cache is deleted/refreshed.

**Comment by laktek** [comment]
@evelant We are looking into few possible solutions to solve this issue. For now as a workaround, can you place the library code inside `supabase/functions` and symlink to them from outside to be used by the client code?

**Comment by evelant** [comment]
Thanks for the quick fix! I will try this out later. It wasn't really practical for me to move the large amount of existing shared code for a variety of reasons.
