### ISSUE TITLE
Cannot type in Access Token in cmd or powershell

### ISSUE THREAD

**Issue by markcouvaras** [supabase/cli#1054]
## Describe the bug

As of this morning I cannot type in my access token in the cmd line prompt when prompted. Nor can I paste it

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run npx supabase login
2. In the prompt that asks for access token. Try and type or right click paste access token
3. Nothing happens

## Expected behavior

I should be able to type or paste my access token in the command line

## System information

- OS: Windows 10 Enterprise
Version	22H2
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0
- Supabase CLI Version: 1.52.3
![Capture](https://user-images.githubusercontent.com/52830148/235880027-61ac527a-3094-4575-9dcc-f331ad3fd772.PNG)

**Comment by sweatybridge** [comment]
The access token is hidden from display by default as it is sensitive data. May I check if you are able to login after hitting enter?

**Comment by markcouvaras** [comment]
I have tried by trying to paste it and hitting enter and I get this
![image](https://user-images.githubusercontent.com/52830148/235884056-37e4db2a-e17d-4e6a-afa7-ac4fc7d9a8ef.png)

**Comment by soedirgo** [comment]
Are you using a `sbp_v0_` access token? The CLI doesn't accept that atm.

**Comment by markcouvaras** [comment]
Yes that is correct? How can I change this?

**Comment by markcouvaras** [comment]
The one I am trying to use starts like below:
sbp_e454aa....................

**Comment by markcouvaras** [comment]
The cmd pallette just doesn't want me to type anything at all.

**Comment by soedirgo** [comment]
Can you try it with `npx supabase login --debug`? (Making sure to mask the actual token)

**Comment by markcouvaras** [comment]
Same error message.The problem is in the cli input part. The token is fine and has worked perfectly until now. However due to the problems we had this morning due to the hotfix, it seems as though it affected the input.

**Comment by sweatybridge** [comment]
I'm unable to reproduce your error on my win10 vm. Could you check the windows credentials store to see if the project access token exists?
![Capture](https://user-images.githubusercontent.com/1639722/235980275-258a0bca-71bd-4d34-bdde-e666a33b2c31.PNG)

You may try removing the token and login again.

**Comment by markcouvaras** [comment]
I removed the token and I still cannot type or paste anything in the cmd where it asks for 'Enter your access token'. Could you please tell me how I can do a full removal and clean of the npm cache so that I can totally remove the supabase cli. After that I will try and reinstall it.

**Comment by sweatybridge** [comment]
Typically `npm uninstall supabase` should work. If not, you can also try deleting the `./node_modules` directory from your project folder.

**Comment by markcouvaras** [comment]
Thank you for trying to help me with this, but unfortunately nothing seems to work.

**Comment by sweatybridge** [comment]
Another workaround is to skip login completely by setting `SUPABASE_ACCESS_TOKEN` env var.

**Comment by markcouvaras** [comment]
Ok I could  try that. I am guessing I need to do this using GitHub Actions or is there a simpler way using VSCode?

**Comment by markcouvaras** [comment]
Awesome that did the trick. Thank you so much for your patience and help in resolving this case.

**Comment by AdamQuadmon** [comment]
I had a similar issue using the PowerShell in VsCode on Win11.
Using the default PowerShell worked as expected

**Comment by markcouvaras** [comment]
> I had a similar issue using the PowerShell in VsCode on Win11. Using the default PowerShell worked as expected

Interesting stuff. I will look into this as it never crossed my mind it could be that.

**Comment by justin-echternach** [comment]
for what it's worth ... I have the same issue on Windows 11 in vs code and in Power Shell and Command Prompt directly.  I resolved it by setting the environment variable as suggested above.

**Comment by carsonkrueger** [comment]
> I had a similar issue using the PowerShell in VsCode on Win11. Using the default PowerShell worked as expected

This worked for me, thanks

**Comment by lesourdingo** [comment]
> I had a similar issue using the PowerShell in VsCode on Win11. Using the default PowerShell worked as expected

Same problem for me, it works  with the default PowerShell too.

**Comment by tachibana-shin** [comment]
i had the same problem but it is on linux it seems that what is stopping me from entering the token is the password input the supabase cli is using.

i feel it's really useless because if the attacker wants to get it they have already captured the token from the token generating site and no one can remember this token so the password field here is meaningless

**Comment by hansanax** [comment]
I typed the access token manually in the terminal, and that worked for me. However, as I was typing, there was no indication that I was actually typing anything.

**Comment by NightGod-A** [comment]
i used the method to set env and sucessfully logined. but i can't input anything when i link to my database that i need to input my password.

**Comment by umershaikh123** [comment]
gitbash worked for me.

**Comment by fvckprth** [comment]
I'm on the mac and I'm having the same issue as well

**Comment by FerdiHr** [comment]
> Are you using a `sbp_v0_` access token? The CLI doesn't accept that atm.

I'm on MacOS, every token I can generate is with the format `spb_v0_` 
I can't deploy, any idea on when there will be handle ? 

Thanks for the amazing work with supabase

**Comment by royalrudra** [comment]
Encountering the same problem with Visual Studio Code on Windows, but utilizing the Windows Terminal resolves the issue.

**Comment by aethernable** [comment]
I had the same problem in my VS studio code was not working with bash or PowerShell I'm running Windows 10 and when I tried the command terminal it works
