### ISSUE TITLE
Regression: insufficient SUPABASE_SCANNER_BUFFER_SIZE for seed

### ISSUE THREAD

**Issue by brendanmc6** [supabase/cli#1058]
# Bug report

I believe this commit has introduced a regression in `npx supabase start`
https://github.com/supabase/cli/commit/067268495d26cfada284e3b4d1a0c6a17541b5c5

My seed data is only 7kb, and this error is thrown preventing me from `start`ing or `reset`ing my db locally.

```
Seeding data supabase/seed.sql...
Error: bufio.Scanner: token too long
After statement 0: 
Try setting SUPABASE_SCANNER_BUFFER_SIZE=5MB (default is 256KB)
```

I can set the buffer size as suggested in the output to fix the issue, however this does not seem like the intended default behavior described in the commit above.

Temporary solution:
```
SUPABASE_SCANNER_BUFFER_SIZE=5MB npx supabase start
```

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

- Create small seed file
- `npx supabase start`
- observe console error

## Expected behavior

Small seed files should start without specifying the buffer env var.

**Comment by sweatybridge** [comment]
Sorry about that. It was an unfortunate oversight on my part. It's now fixed in 1.54.1
