### ISSUE TITLE
Supabase Running Locally `realtime` schema's Tables Not Being Created By CLI After `supabase db reset` but are created after hard restart

### ISSUE THREAD

**Issue by nbarrow-inspire-labs** [supabase/cli#1073]
[Edit: I wasn't sure if this was better reported here or under the cli project, and am happy to move it if this is an issue with the cli and not with the base supabase instance itself)

I was having issues with realtime and running supabase locally that did not exist in my clone running in Supabase's cloud. I made sure that react's strict mode was disabled, that replication was enabled, that I was using the latest versions of both the CLI and the javascript client, etc.

I was able to narrow down the issue to this: 
1. running `supabase db reset` is clearing the tables in the `realtime` schema
2. however, running `supabase stop` and then immediately `supabase start` re-generates the tables in the `realtime` schema
3. but, even after running the `supabase stop` and `supabase start` (which applied my `seed.sql` and `migrations`, both attached), if I subsequently run `supabase db reset`, these tables are deleted again

It seems, from the CLI output, that running `supabase start` runs `supabase db reset`, so it's strange to me that only when I manually run `supabase db reset` do those tables get deleted (leading me to believe this is not an issue with my migrations or seed). 

[Edit: the reason why this is an issue for me is that the subscriptions to realtime are failing and are not registering (they report in the browser as successfully subscribed, but when I change data in the public schema, nothing happens on the frontend, but once the tables in the `realtime` schema do exists, such as after hard-restarting supabase, everything works perfectly); attempting to subscribe on the frontend/browser is not creating the tables in the `realtime` schema]

I'll put a GIF below of me re-creating this error, as well as all of my migrations and seed files. As seen in the video, I take the exact steps that I document above, where re-starting local supabase applies all of my migrations and `seed.sql`, while not disrupting the `realtime` schema, but once I manually run `supabase db reset`, the tables in `realtime` schema disappear.

![2023-05-03 23 54 24](https://user-images.githubusercontent.com/127700939/236110065-fe00564d-958d-4969-b7d2-ea9f9a903632.gif)

[migrations.zip](https://github.com/supabase/supabase/files/11392794/migrations.zip)
[seed.sql.zip](https://github.com/supabase/supabase/files/11392795/seed.sql.zip)

**Comment by sweatybridge** [comment]
Yup, I will also add realtime to the list of services to be restarted after reset. Thanks for reporting this issue.
