### ISSUE TITLE
cli hangs during startup

### ISSUE THREAD

**Issue by scopethis** [supabase/cli#108]
# Bug report

## Describe the bug

Running Supabase locally using ```supabase start``` on a previously initialised project does not finish. It hangs when starting the database.

## To Reproduce
This is was a fresh install (re-fetched all containers again) using the latest CLI and Postgres 14.
My config.json is shown below
```
{
  "projectId": "supabase-backend",
  "ports": {
    "api": 54321,
    "db": 54322,
    "pgMeta": 54323,
    "studio": 54324,
    "inbucket": 54325
  },
  "dbVersion": "140001",
  "excludeSchemas": [
    "extensions"
  ]
}
```

I've recently upgraded to the lastest cli, before this everything was working fine.
I upgraded using homebrew: ```brew upgrade supabase```
I have a small set of migrations that create a few tables with relationships, but nothing major.

I cleared out all existing docker containers and attempted a fresh ```supabase start```, but it is simply stuck when trying to start the database

## Expected behavior

The setup should complete and list the available urls for the API and the DB address

## Screenshots
![Screenshot 2021-12-12 at 13 52 21](https://user-images.githubusercontent.com/40038165/145715113-0d9a7344-c8e4-4297-bd7f-1d2b35b85f6a.png)

## System information

- OS: macOS. M1 Chip. 16GB ram
- Browser n/a
- Version of supabase-cli: 0.15.7
- version of supabase-cli before upgrade: 0.12.2

## Additional context

As mentioned above, everything was working very well. However this upgrade has stopped me in my tracks. The only thing I haven't tried yet is doing a complete setup again using the steps found here: https://github.com/supabase/cli/tree/main/examples/tour.

I will try a complete setup again using the steps above, but was hoping to avoid doing that if possible.

**Comment by scopethis** [comment]
So, on attempting to do a fresh start, new supabase folder etc, I have run into a different error, which may or may not be related. After running ```supabase init``` I attempted to run ```supabase db remote set``` with my details. However I got the error below:

```Error: Remote database Postgres version 130003 is incompatible with dbVersion 140001```

This is after removing all containers and accepting what the upgraded supabase cli gave when running ```supabase start```

Not quite sure what to do at this point.

**Comment by soedirgo** [comment]
Can you change `dbVersion` in `supabase/config.json` to `130003`? Not sure why it got stuck there, but you should be able to reuse the `migrations` directory on the newly setup project.

**Comment by scopethis** [comment]
Thank you. I've got passed ```supabase db remote set``` but now my migration is stalling. In fact erroring out:

```
ALTER TABLE
GRANT
GRANT
GRANT
Error: Error running SQL: PANIC:  stuck spinlock detected at LWLockWaitListLock, /build/postgresql-13-Wn5d1c/postgresql-13-13.3/build/../src/backend/storage/lmgr/lwlock.c:918
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
connection to server was lost
```

In some cases it stalls when applying a migration. This didn't happen before I upgraded.

**Comment by soedirgo** [comment]
Hmm, looking around based on the error message suggests it's a qemu-related issue. Can you try narrowing down the issue (e.g. commenting out all migrations but one, commenting out all but a few SQL in the migration) and posting it here, using dummy values? I'm also on M1 so I can try to replicate.

**Comment by scopethis** [comment]
What ever I do to change the migrations ends up with:
```supabase_migrations.schema_migrations table is not in sync with the contents of supabase/migrations.```

**Comment by soedirgo** [comment]
Can you test the migrations with just `supabase start` without doing `supabase db remote set`? To resolve that you'd need to do `DROP SCHEMA supabase_migrations CASCADE` on the remote database first - I'll improve the error message on this one.

**Comment by scopethis** [comment]
@soedirgo Are you using Docker Desktop? If so, what version are you running? Thanks.

**Comment by soedirgo** [comment]
I'm currently using the latest version:
```
❯ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:34:44 2021
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by scopethis** [comment]
I've upgraded Docker Desktop to the latest release, created a new supabase project and started a fresh project. So far all is well. However I haven't tried running a migration yet. I'm not entirely sure why it failed **yet** - i'll go back and have a look at some point to see where I went wrong. Thanks for your help @soedirgo!
