### ISSUE TITLE
supabase db diff outputs wrong branch name

### ISSUE THREAD

**Issue by cdimitroulas** [supabase/cli#1085]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This is a rather minor issue, but when running `supabase db diff --use-migra` I noticed that the output included a line which reads:
```
Finished supabase db diff on branch main.
```

The branch name was `main`, even though I was on a different branch when running this command. I think the correct behaviour would be to print the current branch name.

## To Reproduce

1. Check out a branch which is not `main` e.g. `git checkout -b test`
2. Run `supabase db diff`
3. See the output in the console which reads: "Finished supabase db diff on branch main."

## Expected behavior

It should say "Finished supabase db diff on branch `test`"

## Screenshots

![Screenshot 2023-05-10 at 19 42 20](https://github.com/supabase/cli/assets/20640274/13c8d434-716b-483d-9051-cc6994bb7bde)

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 1.57.4
- Version of Node.js: v16.15.1

**Comment by codesnik** [comment]
It looks like it is not about your local git branches, but about _supabase db_ branches. (`supabase db branch --help`). Which feature seems to be broken or not finished yet.

**Comment by cdimitroulas** [comment]
Ah, interesting. Perhaps you are right! Happy to close this issue if someone confirms this is the case, though I must say it's a little confusing to see output in the console from the CLI related to a WIP/experimental feature when using the most commonly used commands

**Comment by sweatybridge** [comment]
Thanks for your feedback. I will address this in the next release.
