### ISSUE TITLE
Local development requires internet connection

### ISSUE THREAD

**Issue by socramm9** [supabase/cli#1094]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am not sure if it is just not Supported anymore but local development is no longer possible if not connected to a network. 
In an older supabase version it was still possible, I worked several times traveling without a connection. 

## To Reproduce

https://github.com/supabase/cli/assets/52098754/8c9bce78-af38-44c3-a07e-905e3defecd2

## Expected behavior

Development should also be possible without internet connection 

## Screenshots

<img width="666" alt="Bildschirmfoto 2023-05-12 um 13 47 39" src="https://github.com/supabase/cli/assets/52098754/db1a424f-3989-48c0-8d9a-e9a1fa74c000">

## System information

I am on the latest supabase version `1.58.1`

**Comment by wmeligy-revamp** [comment]
Having the same issue here for Monacoeditor

**Comment by Jaspie88** [comment]
Also having this issue. I can't even visit the local dashboard at http://localhost:54323/ without an active internet connection.

**Comment by sweatybridge** [comment]
This should have been fixed in latest release. Feel free to reopen if you are still unable to load the dashboard offline.
