### ISSUE TITLE
Should be able to start from anywhere

### ISSUE THREAD

**Issue by awalias** [supabase/cli#11]
since we do a global install of the CLI you should be able to `supabase start` from any directory

I noticed that if you're in a dir where you didn't init you will get :

```
supabase@MacBook-Pro-4 supabase % supabase start
⠧ Starting local emulator.../usr/local/lib/node_modules/supabase/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: docker-compose -f .supabase/emulator/docker-compose.yml up -d
.FileNotFoundError: [Errno 2] No such file or directory: './.supabase/emulator/docker-compose.yml'

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker-compose -f .supabase/emulator/docker-compose.yml up -d',
  stdout: '',
  stderr: ".FileNotFoundError: [Errno 2] No such file or directory: './.supabase/emulator/docker-compose.yml'\n"
}

```
instead of `.supabase` we should probably install the folder in the users root `~/.supabase`

**Comment by awalias** [comment]
hmm although this does mean a global single instance, which also isn't desirable

**Comment by soedirgo** [comment]
I think this is fine, Firebase's local emulator is also installed into the user's $HOME. The question is whether we'll have project-specific stuff, and whether or not it can fit into, say, `supabase.json`.

**Comment by soedirgo** [comment]
On that note, I should really catch all those errors...

**Comment by soedirgo** [comment]
Also, as it is now, you can't use multiple local dev setup, since they all use the same Docker project name (`supabase`), though this is an easy fix (prompt user for project name on `init`).

**Comment by awalias** [comment]
I think enabling multiple envs and catching the error above is probably the best path forward then

"whoops! you need to supabase init inside this directory before you can supabase start"

**Comment by soedirgo** [comment]
The way it works now, it requires `supabase start` to be run inside a Git repo and to have the `supabase` directory in the current working directory.
