### ISSUE TITLE
Cannot create a new user on dev server

### ISSUE THREAD

**Issue by ozum** [supabase/cli#110]
# Bug report

## Describe the bug

I cannot create a user either with JS or via Studio.

### JS (1)

Example from https://supabase.com/docs/reference/javascript/auth-api-createuser seems wrong.

```ts
// error TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type 'UserAttributes'.
const { data: user, error } = await supabase.auth.api.createUser({ name: 'Yoda' });
```
![image](https://user-images.githubusercontent.com/1497060/146362822-3d018d3e-9edf-4712-b22f-20e525c788b8.png)

### JS (2)

Instead I use following:
```ts
// I got error: { message: 'Database error checking email', status: 500 }
const { data: user, error} = await supabase.auth.api.createUser({ email: "abc@xyz.com", data: {name: 'Yoda'} });
```

### Studio

I try to use `Authetication/Users/Invite`, but got error "Failed to invite user: Database error finding user"

![image](https://user-images.githubusercontent.com/1497060/146363347-e843f2b1-d3b5-4ecc-8e48-0a4b82f22c27.png)

supabase/supabase#4268 mentions disabling e-mail confirmation, but I can't find how to do it in the local dev studio.

## System information

macOS 11

**Comment by ozum** [comment]
Thanks, @kiwicopple. Could you please suggest a workaround until it is solved? I'm stuck and can't test Supabase, because I can't create a user.

Also, I kindly suggest you or your team consider this case:

* Updating docs on how to start a working barebone "Hello user" type CLI project from scratch. (without using example project)
* Enable/disable e-mail verification via CLI or Dev Server Studio.
* Fix wrong example for `supabase.auth.api.createUser` in https://supabase.com/docs/reference/javascript/auth-api-createuser. (Example and real TS definitions mismatch)

Best,

**Comment by soedirgo** [comment]
@ozum can you set your `config.json` according to [this](https://supabase.com/docs/reference/cli/config-reference#portsinbucket-optional)? I'm still working on exposing auth configs etc., in the meanwhile setting the `inbucket` port disables email confirmation.

**Comment by soedirgo** [comment]
Can you provide your CLI version? There was some issues with Auth and Storage on earlier versions of the CLI.

**Comment by ozum** [comment]
Yes, 0.15.8

I can create a user with a password (it isn't shown in the examples, I just blindly tried) `await supabase.auth.api.createUser({ email: "abc@xyz.com", password: "password", data: {name: 'Yoda'} })`. However, created user is still waiting for verification. So, still stuck.

**Comment by ozum** [comment]
I found a workaround. I'm sharing here if anyone needs it until a proper solution is developed.

To create a user in development server:

1. Update `supabase/config.json` file and add `ports.inbucket` ket with a port value. (i.e. 54324)
2. Restart supabase server.
3. Create a client, using the "Service Role Key".
4. Create a user with mail and password:

```ts
const supabase = createClient('http://localhost:54321', SERVICE_ROLE_KEY);
const { data: user, error} = await supabase.auth.api.createUser({
  email: "abc@xyz.com",
  password: "password",
  data: {name: 'Yoda'}
})`;
```

5. Open Supabase database using your favorite PostgreSQL client. (i.e. pgAdmin)
6. Open `auth.users` table and update the user by setting `email_confirmed_at` column to a date. (i.e. '2012-12-01 00:00:00')

Now, you have a verified user and can use `await supabase.auth.signIn({ email: "abc@xyz.com", password: "password" });`

**Comment by soedirgo** [comment]
You should be able to monitor & click the confirmation email on the `inbucket` port (`http://localhost:54324`):
<img width="1914" alt="Screen Shot 2021-12-17 at 5 53 13 PM" src="https://user-images.githubusercontent.com/31685197/146525608-9605c7b7-eb36-4841-9998-a30ac30efc9c.png">

**Comment by ozum** [comment]
@soedirgo, thank you. I didn't know that it is a connectable web-based app.

**Comment by ozum** [comment]
@soedirgo, shouldn't this issue be open until it is solved? Currently, there is only a workaround.

**Comment by soedirgo** [comment]
Hmm, which part is still problematic? I can create the user (with password) both with or without `inbucket`.

**Comment by ozum** [comment]
Yea, I tested with a password without inbucket. It's OK. You are right. Just need to update docs.

**Comment by soedirgo** [comment]
Thanks! I'll create an issue for updating the auth docs.
