### ISSUE TITLE
Error running deployed function when using `import_map.json`

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1101]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

There are runtime errors for edge functions using an import_map.json file from CLI version 1.59.0 up. Deployment of the edge function using the cli is successful. However, when the function is called from the deployed URL, we get the following message:

```
module not found: file:///src/import_map.json
```
It is possibly related to this commit: https://github.com/supabase/cli/commit/c86872624202718d3cade35f5cfd9f176652b158

Discussion on this issue here: https://discord.com/channels/839993398554656828/1107654159307645000

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use cli version >= 1.59.0
2. Create any function using an import-map.json file
3. Deploy the function using `supabase function deploy ...`
4. Call the deployed function (using curl, supabase client, any)

## Expected behavior

The function called runs successfully.

## Temporary Solution

- Use CLI version 1.58.1

## Additional context

- OS: macOs
- Browser (if applies) [e.g. chrome, safari]
- Version of Node.js: 16

**Comment by sweatybridge** [comment]
I've reverted the change in 1.60.1 to unblock deploys. Fixing the relative path import will require more upstream changes listed here https://github.com/supabase/cli/pull/1103
