### ISSUE TITLE
It should be possible to run npx supabase init without human interaction

### ISSUE THREAD

**Issue by dsebastien** [supabase/cli#1106]
Currently, when `npx supabase init` is executed, the program asks "Generate VS Code workspace settings?" and requires an answer (y/N). It should be possible to bypass that entirely so that the answer is automatically provided (e.g., npx supabase init --yes or npx supabase init -y) or so that the question is not asked in the first place.

**Comment by bombillazo** [comment]
Not sure if this specific to this cli or an `npx` thing, but we've had scripts fail for use due to this as well.
