### ISSUE TITLE
Can't run supabase start after it was forcefully closed

### ISSUE THREAD

**Issue by charlieamer** [supabase/cli#113]
# Bug report

## Describe the bug
I can't run `supabase start` after forcefully closing terminal (such as shutting down computer). The following error occurs:
```
Error: Error response from daemon: Conflict. The container name "/supabase_db_PROJECT_NAME" is already in use by container "xxx". You have to remove (or rename) that container to be able to reuse that name.
```
### Workaround
In order to work around the problem I have to remove a bunch of docker containers manually:
```
docker rm supabase_db_PROJECT_NAME
docker rm supabase_pgbouncer_PROJECT_NAME
docker rm supabase_kong_PROJECT_NAME
docker rm supabase_auth_PROJECT_NAME
docker rm supabase_realtime_PROJECT_NAME
docker rm supabase_rest_PROJECT_NAME
docker rm supabase_storage_PROJECT_NAME
docker rm supabase_differ_PROJECT_NAME
docker rm supabase_pg_meta_PROJECT_NAME
docker rm supabase_studio_PROJECT_NAME
```
## To Reproduce
1. Run `supabase start`
2. Wait for everything to run
3. Forcefully close the terminal (don't press `ctrl + c` to stop supabase)
4. Try to run `supabase start` again

## Expected behavior
In my opinion the easiest solution would be to check if there are containers that supabase is supposed to run and do `docker rm ...` for each of those (either automatically, or as an argument flag, or as a separate command).

## System information

- OS: Ubuntu
- Version of supabase cli: `0.15.9`

## Additional context
If I press `ctrl + c` I can `supabase start` later without any issue.

**Comment by soedirgo** [comment]
Related: https://github.com/supabase/cli/issues/97
