### ISSUE TITLE
supabase login: Invalid access token format. Must be like

### ISSUE THREAD

**Issue by AdamQuadmon** [supabase/cli#1130]
I can't login.
`supabase login` gives `Invalid access token format` Error

I'm using the tokens generated at https://app.supabase.com/account/tokens
When it ask for the token I can't see the input text, nether if I past the token or if I type it manually
If I hit enter after pasting the token I get this error message:

Error: Invalid access token format. Must be like `sbp_0102...1920`.

**Desktop:**
 - OS: Win11
 - Version of CLI 1.62.3
 - Version of Node.js v18.16.0

**Comment by wirapramuja** [comment]
hello have you solved yet? i have same issue

**Comment by MalzSmith** [comment]
After trying a bunch of times in vscode and getting this error, I've managed to log in using Windows Terminal (used powershell in both). No idea what was interfering with my attempts.

@wirapramuja

**Comment by f-okd** [comment]
Windows terminal worked for me also

**Comment by f-okd** [comment]
> After trying a bunch of times in vscode and getting this error, I've managed to log in using Windows Terminal (used powershell in both). No idea what was interfering with my attempts.
> 
> @wirapramuja

Windows terminal worked for me too

**Comment by ohanote** [comment]
powershell worked here

**Comment by bitnom** [comment]
You need to grab one of these https://supabase.com/dashboard/account/tokens and set env var `SUPABASE_ACCESS_TOKEN` to it.
