### ISSUE TITLE
Upstream request error - Generate types for TypeScript

### ISSUE THREAD

**Issue by paulwiesi** [supabase/cli#1131]
## Describe the bug

When trying to generate types for my project with the supabase cli, it suddenly won't work anymore. I update the types when mutliple changes to the database have been made, but since the last update I get the following error: 

**Error: failed to retrieve generated types: {"message":"upstream request timeout"}**

## To Reproduce

1. Install CLI
2. Connect the Supabase CLI to your Supabase account (access token)
3. Generate Types 
 In my case:` supabase gen types typescript --project-id <--project-id--> > lib/database.types.ts  `

## Expected behavior

Generate types for TypeScript inside the file database.types.ts

## Screenshots

<img width="577" alt="CleanShot 2023-05-20 at 22 00 38@2x" src="https://github.com/supabase/supabase/assets/72663552/1a2ebf8d-fce2-42a7-be76-f88f8239af29">

## System information

- OS: macOS
- Version of supabase-cli: 1.61.5

**Comment by coopernewby** [comment]
I am having the same issue on Supabase CLI 1.63.1

**Comment by mansueli** [comment]
Hi There,

Just to isolate this, are you able to get the types with the management API?
(you'll need to generate a personal supabase token) 

https://supabase.com/docs/reference/api/generate-typescript-types

**Comment by coopernewby** [comment]
No, got the same timeout going through the management api, Also keep getting cors errors and psotgres metadata 504s on the supabase dash when trying to look at the auth and database tabs

**Comment by sweatybridge** [comment]
To avoid the timeouts from our hosted server, you can generate types using the local docker container instead. This is done by passing in the `--db-url` flag. For eg.

```bash
supabase gen types typescript --db-url 'postgresql://postgres:<your-password>@db.<project-id>.supabase.co:5432/postgres'
```

The cors error you were experiencing was caused by our CloudFlare setup. It should have been resolved now.
