### ISSUE TITLE
supabase db reset wipes the db but doesn't run migrations

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#114]
# Bug report

## Describe the bug

If I run `supabase db reset` then I simply get an empty database without my migrations.

## To Reproduce

1. `supabase init`
2. `supabase start`
2. `supabase migration new init
3. create a migration
4. `supabase db reset`
5. Go to studio and verify that tables were not created

## Expected behavior

I'd expect my migrations to be applied

## System information

- OS: ubuntu
- Version of supabase cli: 0.15.8
- Version of Node.js: 16

**Comment by soedirgo** [comment]
Ack, this was an edge case - if you use a migration name other than `init` it should work. I'll do a workaround for this in a bit.
