### ISSUE TITLE
supabase projects delete command

### ISSUE THREAD

**Issue by tehnorm** [supabase/cli#1151]
It is useful to be able to perform the deletion of a project programmatically. Having to log in to a UI is very challenging from a CI/CD perspective. 

**Describe the solution you'd like**
Add a new command to delete a project. e.g.

`supabase projects delete --yes --project-ref <ref>`

**Describe alternatives you've considered**
Logging into the supabase UI, navigating to the project, and clicking on the "Delete Project" button to trigger the deletion flow.

**Comment by BlackdreamIO** [comment]
i dont know how to delete my current supabase project please help

**Comment by zeshhaan** [comment]
The command `supabase link` will list your projects. 

grab the project ref from the list and then run the command:

```bash
supabase projects delete <project-ref>
```
