### ISSUE TITLE
supabase projects reset --yes --project-ref <ref>

### ISSUE THREAD

**Issue by tehnorm** [supabase/cli#1152]
It is useful to perform the reset of a project programmatically. In the local supabase CLI, a project can be reset to stock values and data. This is helpful for testing and for our product teams to have a known set of data in their UAT environments.

### Describe the solution you'd like
Add a new command to delete a project. e.g.

`supabase projects reset --yes --project-ref <ref>`

### Describe alternatives you've considered
There is no solution for this currently. Without the ability to connect with a `superuser` the local commands to reset a project can not be replicated.

**Comment by sweatybridge** [comment]
Potentially a duplicate of #480
