### ISSUE TITLE
Type generation outputs to file instead of terminal

### ISSUE THREAD

**Issue by EliasTouil** [supabase/cli#1158]
**Describe the bug**

I tried running 
`npx supabase gen types typescript --linked > types/supabase.ts`
The command "froze" so I had a look at the output file and found a message there 😅

`Need to install the following packages:
  supabase@1.64.3
Ok to proceed? (y) `

```json
{
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "gen-types": "npx supabase gen types typescript --linked > types/supabase.ts"
  },
  "dependencies": {
    "@supabase/auth-helpers-nextjs": "0.7.0",
    "@supabase/supabase-js": "2.23.0",
    "@types/node": "20.2.5",
    "@types/react": "18.2.7",
    "@types/react-dom": "18.2.4",
    "encoding": "^0.1.13",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "next": "13.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "server-only": "^0.0.1",
    "swr": "2.1.5",
    "typescript": "5.0.4"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.24",
    "supabase": "^1.64.3", // I just added this to follow the prompt
    "tailwindcss": "^3.3.2"
  }
}
```

**To Reproduce**
In a project without Supabase installed as a devdependency run:
`npx supabase gen types typescript --linked > types/supabase.ts`

**Expected behavior**
Script outputs to the terminal

**Screenshots**
![Screenshot 2023-05-29 at 11 06 51 AM](https://github.com/supabase/cli/assets/4231667/b89e3fae-1e13-4a06-8b0e-0d5af1f108b2)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac os Ventura 13.2.1
 - Version of CLI - I installed the latest version and don't know what I had before :/
 - Version of supabase-js (if applicable) 2.23.0
 - Version of Node.js (if applicable) v20.2.0

**Additional context**

**Comment by soedirgo** [comment]
Thanks @EliasTouil! As per the [instructions](https://supabase.com/docs/guides/cli#installation), you'd need to run `npm install --save-dev supabase` first before running `npx supabase`.
