### ISSUE TITLE
Custom initial db name

### ISSUE THREAD

**Issue by HadySalhab** [supabase/cli#1164]
**Is your feature request related to a problem? Please describe.**
I am trying to run Supabase locally, I wasn't able to choose the db name. Currently it always default to postgres.

**Describe the solution you'd like**
Add additional config properties to override the default db name, user and password

**Comment by sweatybridge** [comment]
Hi @HadySalhab, to help us prioritise this enhancement, could you elaborate more on how customising the db name, user, and password would be useful for local development?

**Comment by HadySalhab** [comment]
Hi @sweatybridge , 
Thanks for your message. I had an expectation that the database name can be changed when running the project in the cloud (Supabase platform), and my concern was how can Supabase cli push the migration to my remote database with different name. 
I miss that the cli provide the ```--db-url``` flag. 
Sorry for the confusion, appreciate your support, will close this issue.
