### ISSUE TITLE
supabase CLI fails to mirror remote DB relations

### ISSUE THREAD

**Issue by aresnick** [supabase/cli#117]
# Bug report

## Describe the bug

In following the [CLI tour](https://github.com/supabase/cli/tree/main/examples/tour), when I try to run `supabase start`, as `supabase` applies the migrations generated by `db remote commit`, it encounters a missing relation and errors out, 

```text
⣷ Applying migration 20211224180148_remote_commit.sql...

BEGIN
Error: Error running SQL: ERROR:  relation "public.teams" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
…
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `supabase init`
2. `supabase db remote set $CONNECTION_STRING`
3. `supabase db start`
4. Await the migration to error out

## Expected behavior

The DB should start up successfully.

## Screenshots

asciinema recording available [here](https://asciinema.org/a/zGceHWLK1GOdPK78Ts4sU8FOj)

## System information

- OS: macOS Monterey 12.0.1 (M1, 2020)
- Supabase CLI: 0.15.10

**Comment by aresnick** [comment]
If it is useful, [db_backup.sql.zip](https://github.com/supabase/cli/files/7775009/db_backup.sql.zip) is the result of `pg_dumpall` of the Supabase DB, generated by `pg_dumpall --dbname="postgresql://postgres:.jzrxiiU%40Vt7jgYqLVsUfrYU*VGZkjwV@db.labhhhajyoiveqvcamyw.supabase.co:5432/postgres" --verbose --no-password --no-owner`

**Comment by soedirgo** [comment]
I think this is the same issue as https://github.com/supabase/cli/issues/65. The migration generated by `commit` isn't foolproof so you might need to modify it, especially if the diff is large.

I've added some warnings in the output of `db commit` and `db remote commit` in https://github.com/supabase/cli/commit/f4ece64daac6fcad8b63edf51c68424b032b4c4b to highlight this, so closing this for now. Feel free to reopen if there's a follow-up issue though!
