### ISSUE TITLE
supabase cli fails with "sh: supabase: not found" on alpine-based node Docker images

### ISSUE THREAD

**Issue by rmvh** [supabase/cli#1191]
The command `supabase` fails when executed in a node Docker image based on alpine.

With `npx`:
```
$ docker run -it node:alpine npx supabase
Unable to find image 'node:alpine' locally
alpine: Pulling from library/node
Digest: sha256:59ac6536ba03469adc3847f23a4f223b0418fba21c90168d703f61bd84125989
Status: Downloaded newer image for node:alpine
Need to install the following packages:
  supabase@1.64.8
Ok to proceed? (y) y
sh: supabase: not found
npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice
```

With `npm i --save-dev supabase`:
```
$ docker run -it node:alpine sh -c "mkdir /tmp/supabase; cd /tmp/supabase; npm i --save-dev supabase; supabase"

added 23 packages in 4s

4 packages are looking for funding
  run `npm fund` for details
npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice 
sh: supabase: not found
```

**Comment by sweatybridge** [comment]
You are missing `npx supabase` in your second example. Full command is:

```bash
docker run -it node:alpine sh -c "mkdir /tmp/supabase; cd /tmp/supabase; npm i --save-dev supabase; npx supabase"
```

**Comment by sweatybridge** [comment]
Thanks for reporting back. This seems to be an issue with supabase binary dynamically linking to glibc which isn't installed on alpine by default. You can work around it by installing `apk add libc6-compat` before starting supabase. Full command:

```bash
docker run -it node:alpine sh -c "cd /tmp; npm i --save-dev supabase; apk add libc6-compat; npx supabase"
```

Reference: https://stackoverflow.com/a/66974607

**Comment by sweatybridge** [comment]
Also note that many supabase commands require docker as a dependency. So if you are trying to supabase start inside a docker container, remember to volume mount the docker socket from your host machine as well. For example,

```bash
docker run -v "/var/run/docker.sock:/var/run/docker.sock:rw" -it node:alpine sh ...
```

**Comment by sweatybridge** [comment]
For d-in-d to work, not only the cli container but also the typegen container cli launches has to be in the same docker network as the db container. So yes, exposing your supabase container to the host machine is your best bet here.
