### ISSUE TITLE
How to write tests around policies that use auth.uid()

### ISSUE THREAD

**Issue by cazzer** [supabase/cli#1192]
**Link**
[https://supabase.com/docs/guides/database/testing](https://supabase.com/docs/guides/database/testing)

**Describe the problem**
I'm stoked to see that _something_ on testing is included in the docs, but it still leaves me with some questions. The area of greatest complexity for me, (and therefore the most valuable to test, in my opinion), is my policies. I use `auth.uid()` heavily throughout my policies and want to write tests to validate that particular users have access to query and mutate appropriate records in the database.

It is clear to me how to use pgTAP to create and run migrations. How can I use this framework to add tests for actions that invoke procedures or policies that include `auth.uid()` calls?

**Describe the improvement**
Add further examples for how to test more Supabase-specific areas of database design, such as policy and stored procedure testing.

**Additional context**
Add any other context or screenshots that help clarify your question.

**Comment by sweatybridge** [comment]
Thanks for the great suggestion. You may want to check out this community driven [helper functions](https://github.com/usebasejump/supabase-test-helpers/blob/main/supabase_test_helpers.sql) that lets you authenticate as any user in your pgTAP tests.

After setting up these helpers in `supabase/tests`, you will be able to call them in db tests like this [example](https://github.com/usebasejump/supabase-test-helpers/blob/main/tests/04-blog-example.sql). 

We are definitely looking into more documentations around RLS testing so stay tuned.

**Comment by cazzer** [comment]
Oh snap, thanks @sweatybridge! I hadn't come across that repo yet; it completely satisfies my needs so feel free to close this issue.
