### ISSUE TITLE
Selectively parse `config.toml` depending on command

### ISSUE THREAD

**Issue by mrchrishahn** [supabase/cli#1202]
**Is your feature request related to a problem? Please describe.**
When setting up auth providers locally using the `config.toml` you should ideally use environment variables to configure the secrets ([related PR](https://github.com/supabase/supabase/pull/14845)). 

However, if/when the `config.toml` gets committed to git (I haven't found any clear documentation on whether this is recommended or not) and you want to automate db migrations using e.g. [GitHub actions](https://supabase.com/docs/guides/cli/managing-environments#configure-github-actions), the current config parser errors if you don't specify the environment variables for the auth providers.
As far as I understand the different CLI commands, the fully parsed auth provider options are only used in the `start` command for configuring the GoTrue server. Thus, for most actions, like running `db push`, the config parser raises errors that are not needed. This makes the pipeline setup harder and can increase the risk of secrets being disclosed. 

**Describe the solution you'd like**
I'd suggest implementing private flags to the LoadConfig function to specify the config sections which should be validated, so that e.g. the `db push` command only loads the db related configs.

**Describe alternatives you've considered**
Another option would be to generally discourage users from committing their `config.toml` to git and clarifying that the `config.toml` is mostly meant for configuration of your local or self-managed system and doesn't get applied to the Supabase-managed project.

**Comment by sweatybridge** [comment]
I believe this has been addressed in latest CLI as we no longer load unnecessary configs for `db push`. Our recommendation is to commit `config.toml` so that other devs and CI can reproduce the same local environment.
