### ISSUE TITLE
not able to run tests from command line

### ISSUE THREAD

**Issue by CareTiger** [supabase/cli#1206]
getting the following error
```$ supabase test db --debug
Supabase CLI 1.64.8
2023/06/12 22:40:18 Sent Header: Host [docker]
2023/06/12 22:40:18 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/12 22:40:18 Sent Header: Content-Length [3072]
2023/06/12 22:40:18 Sent Header: Content-Type [text/plain]
2023/06/12 22:40:18 Send Done
2023/06/12 22:40:18 Recv First Byte
2023/06/12 22:40:18 Sent Header: Host [docker]
2023/06/12 22:40:18 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/12 22:40:18 Sent Header: Content-Length [1164]
2023/06/12 22:40:18 Sent Header: Content-Type [application/json]
2023/06/12 22:40:18 Send Done
2023/06/12 22:40:18 Recv First Byte
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
2023/06/12 22:40:18 Sent Header: Host [docker]
2023/06/12 22:40:18 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/12 22:40:18 Send Done
2023/06/12 22:40:18 Recv First Byte
Error: error executing command```

**To Reproduce**
Steps to reproduce the behavior:
run 
``` supabase test db --debug```

**Expected behavior**
```All tests successful.
Files=1, Tests=1,  1 wallclock secs ( 0.01 usr  0.00 sys +  0.04 cusr  0.02 csys =  0.07 CPU)
Result: PASS```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
```------------------------------
- Operating System: Windows_NT
- Node Version:     v19.8.1
- Nuxt Version:     0.0.0
- Nitro Version:    -
- Package Manager:  npm@9.7.1
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------```

**Comment by CareTiger** [comment]
@sweatybridge  when will the next version be released?  I think this new cadence is a little slow given the number of changes. I understand the stability tradeoffs but can we go to once a week release?

**Comment by sweatybridge** [comment]
I will make the stable release today after merging this fix. I'd like to keep the current cadence for the time being. We can always do a hotfix release anytime for urgent fixes.

**Comment by CareTiger** [comment]
still getting the error 
`$ supabase db test --debug
Supabase CLI 1.68.6
2023/06/13 03:56:00 Sent Header: Host [docker]
2023/06/13 03:56:00 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/13 03:56:00 Sent Header: Content-Length [3072]
2023/06/13 03:56:00 Sent Header: Content-Type [text/plain]
2023/06/13 03:56:00 Send Done
2023/06/13 03:56:00 Recv First Byte
2023/06/13 03:56:00 Sent Header: Host [docker]
2023/06/13 03:56:00 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/13 03:56:00 Sent Header: Content-Length [1225]
2023/06/13 03:56:00 Sent Header: Content-Type [application/json]
2023/06/13 03:56:00 Send Done
2023/06/13 03:56:00 Recv First Byte
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
2023/06/13 03:56:00 Sent Header: Host [docker]
2023/06/13 03:56:00 Sent Header: User-Agent [Go-http-client/1.1]
2023/06/13 03:56:00 Send Done
2023/06/13 03:56:00 Recv First Byte
Error: error executing command
`

**Comment by sweatybridge** [comment]
This error is due to the use of containerd. You need to disable from docker settings https://github.com/supabase/cli/issues/1178#issuecomment-1580118070
