### ISSUE TITLE
Error: service not healthy: [realtime-dev.supabase_realtime_xxx]

### ISSUE THREAD

**Issue by kapitanluffy** [supabase/cli#1211]
**Describe the bug**

**To Reproduce**
1. Run `npx supabase start`

**Expected behavior**
I cannot start local supabase. I can start with `--ignore-health-check` flag.

**Screenshots**
![image](https://github.com/supabase/cli/assets/485799/7f012f88-3e1e-4514-bbca-1a6a286e55a1)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version of CLI [e.g. v1.50.15]
 - Version of Node.js (if applicable) [e.g. v18.15.0]

**Additional context**

I attached the log below: [supabase.log](https://github.com/supabase/cli/files/11752851/supabase.log)

**Comment by sweatybridge** [comment]
Hi @kapitanluffy, as a sanity check, could you confirm if it's reproducible on the latest cli version?

```bash
npx supabase@latest start
```

**Comment by kapitanluffy** [comment]
> Hi @kapitanluffy, as a sanity check, could you confirm if it's reproducible on the latest cli version?
> 
> ```shell
> npx supabase@latest start
> ```

Yep. I downgraded and upgraded. I also cleared the docker containers, volumes etc.

**Comment by sweatybridge** [comment]
Based on the logs, it seems that the monotonic clock on your host machine has drifted into the past. This caused realtime to crash.

```bash
Monotonic time stepped backwards!
Previous time: 10661093675
Current time:  10661081882
Aborted (core dumped)
```

Have you tried syncing your system clock? Could you also tell me more about the OS an docker version you are using?

**Comment by kapitanluffy** [comment]
> Based on the logs, it seems that the monotonic clock on your host machine has drifted into the past. This caused realtime to crash.
> 
> ```bash
> Monotonic time stepped backwards!
> Previous time: 10661093675
> Current time:  10661081882
> Aborted (core dumped)
> ```
> 
> Have you tried syncing your system clock? Could you also tell me more about the OS an docker version you are using?

Sorry to bring this up again. I am experiencing this problem again. Any recommendations on what to do? What I did was just sync my time to a time server
