### ISSUE TITLE
Docker contexts not utilised and DOCKER_HOST can't handle ssh:// addresses

### ISSUE THREAD

**Issue by niktek** [supabase/cli#1223]
**Describe the bug**
When a user has multiple docker contexts and sets one to be active, the supabase CLI doesn't use that context info.  If you then try to work around this by overriding the default context with DOCKER_HOST=ssh://remotehost then checks like AssertDockerIsRunning fail as they don't use the connection helpers from Docker and treat it as a local http ping.

Some brief research shows that it looks like 
- https://github.com/docker/cli/blob/master/cli/connhelper/connhelper.go 
- https://github.com/docker/cli/blob/master/cli/context/store/store.go

Might be relevant to properly pickup the contexts and to also handle the extra ssh tunnelling/DIND setups that might be out there.

**Comment by sweatybridge** [comment]
Thanks for reporting this issue.

I've changed the docker client initialisation code to read from docker's default [context store](https://github.com/docker/cli/blob/085d5c281612298583d19806aa8ec637b572e4cc/cli/command/cli.go#L243). Could you help me test it out using the latest beta release? ie.

```bash
npx supabase@beta start
```

**Comment by niktek** [comment]
This seems to make it always use the default, instead of using the context that the user selected.

<img width="989" alt="image" src="https://github.com/supabase/cli/assets/52020637/139a6c60-e95a-4437-ad9f-61be7761d407">
- Starts with default context (as denoted by * next to name)
- list images to show it working
- change context to be liniks which uses an ssh://nik@liniks connection
- list images to show it is connected to a new remote docker daemon
- run supabase@beta - it ignores the selected context, but correctly sees the local containers
- shutdown the local docker daemon
- re-run supabase command and it tries to talk to local socket rather than ssh tunnelling to remote socket.

To be clear - I'm not entirely sure that Docker provides a means to do this all for you as I have seen other tools the use the docker cli (such as `act` a local replica for making GitHub Actions) also not take into account docker contexts as well.

**Comment by sweatybridge** [comment]
Thanks for following up with this detailed result. I managed to fix it with a different function provided by docker cli. Tested locally using your commands:

```bash
docker context use test-context
supabase start
```
