### ISSUE TITLE
Authorization failed while linking project

### ISSUE THREAD

**Issue by chetannn** [supabase/cli#1224]
I am unable to link my project through CLI.

I have checked from supabase API as well and my project ref id and password are correct as well. I tried connecting postgresql through psql command, it's working fine.

![Screenshot 2023-06-21 at 12 25 00](https://github.com/supabase/cli/assets/22125423/5982f310-0aac-433a-b5bb-1ece9103b29e)

![Screenshot 2023-06-21 at 12 15 44](https://github.com/supabase/cli/assets/22125423/9121c9eb-7583-481d-a9fe-2939e386640d)

**Desktop (please complete the following information):**
 - OS: [macos m1]
 - Version of CLI [v1.68.6]

**Comment by sweatybridge** [comment]
Hi @chetannn, could you try setting the `SUPABASE_ACCESS_TOKEN` environment variable to see if it works? For eg.

```bash
SUPABASE_ACCESS_TOKEN=<your token> npx supabase link --project-ref <your-ref>
```

**Comment by chetannn** [comment]
Tried it but no luck

![Screenshot 2023-06-21 at 12 53 15](https://github.com/supabase/cli/assets/22125423/1bae50f0-850c-457b-a088-ff6ff78d984d)

**Comment by sweatybridge** [comment]
The error message is different now which indicates progress. Could you try setting the password as env var as well?

```bash
SUPABASE_ACCESS_TOKEN=<token> SUPABASE_DB_PASSWORD=<password> npx supabase link --project-ref <your-ref>
```

If this works, it probably indicates a bug with our loading of project credentials.

**Comment by saidb-dev** [comment]
Could you please help ?

PS C:\Users\saidb\saidb-dev\basejump> supabase link --project-ref xxxxxxx
Authorization failed for the access token and project ref pair: {"message":"Forbidden resource"}


PS C:\Users\saidb\saidb-dev\basejump> SUPABASE_ACCESS_TOKEN=xxxxxxxxx SUPABASE_DB_PASSWORD=xxxxxx npx supabase link --project-ref xxxxxxx

SUPABASE_ACCESS_TOKEN=xxxxxxxx : The term 
'SUPABASE_ACCESS_TOKEN=xxxxxxxxx' is not recognized as the name of a cmdlet, function,    
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

**Comment by sweatybridge** [comment]
@saidb-dev the syntax for setting env var on powershell is as follows 

```
$Env:<variable-name> = "<new-value>"
```

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

**Comment by fzybb** [comment]
Same issue, it works for me as well. But can anyone explain what may cause this error?

**Comment by JakesMD** [comment]
For anyone with this error: `Authorization failed for the access token and project ref pair: {"message":"Failed to fetch project service details"}`

This means that your supabase project has been paused (probably automatically). You need to restore the project in the dashboard.

**Comment by 23000003** [comment]
> Same issue, it works for me as well. But can anyone explain what may cause this error?

I know its a bit late but this for anyone who had the issues same as mine when changing deployment projects, its because the environment variable is already set in the first project u have deployed.

Run ``$Env:<variable-name> = '<new-value>' `` as given above first before ``npx supa --- ``

**Comment by ekediala** [comment]
Have the same problem. None of the solutions above worked. I logged out of my personal supabase account and logged in with a client's when this started. I have created a new access token and added it to env, I have used supabase login, etc., and nothing worked.

OS Version: macOS Sequoia 15.3.2 
CLI version: npx supabase@latest

**Comment by ncuthbert** [comment]
There is a service issue right now. Seems to be wide spread.
https://status.supabase.com/incidents/3h1gjkvf7dmd

**Comment by d-stoll** [comment]
Same problem here, when trying to link a project i get the following error:

`Authorization failed for the access token and project ref pair: {"message":"Cannot GET /v1/projects/.../api-keys?reveal=false"}`

OS Version: Microsoft Windows Version 24H2
CLI Version: bunx supabase@2.19.7

**Comment by maxstralka** [comment]
Jep, same here

**Comment by kabirivan** [comment]
Same problem here, when trying to link a project i get the following error:

Authorization failed for the access token and project ref pair: {"message":"Cannot GET /v1/projects/.../api-keys?reveal=false"}
OS Version: macOS Sequoia 15.3.2
CLI version: npx supabase@latest
Crash report: fea1e7a81073422e90ca72e6798e1d3a

**Comment by d-stoll** [comment]
works again on my side
