### ISSUE TITLE
feat: improve management api commands (functions, projects....)

### ISSUE THREAD

**Issue by Ananya2001-an** [supabase/cli#1225]
**Is your feature request related to a problem? Please describe.**
Currently we don't have any commands to create, list or update a function from the cli. Also, we have already implemented the api-keys function for projects inside client.gen.go but we don't have a command to call it so that can be also added to the backlog (can be done alongside). 

So for now we can add these sub-commands:
`supabase functions list`
`supabase functions create`
`supabase functions update`
`supabase functions retrieve`
`supabase projects api-keys`

**Additional context**
I would like to work on this :) I plan to break this into "one command at a time" so that it could be easier for reviewing.

**Comment by sweatybridge** [comment]
Hi @Ananya2001-an, the cli commands and api endpoints may not be named the same way for usability. For example, we currently implement the following functions commands:

- `functions new` (similar to create)
- `functions deploy` (similar to update)
- `functions download` (similar to retrieve)

We are still missing `functions list` and `projects api-keys`. I would be happy to review your PRs if you want to work on it.

**Comment by Ananya2001-an** [comment]
Ahh yess u are right... cool I will work on the other 2 then :)

**Comment by Ananya2001-an** [comment]
Also there's another issue that I will create later. I noticed that for each command we don't have some sort of restriction as to which sub command exists for it; like even if I type something like `supabase db jdhj` it returns info about the db command but instead we should throw some error saying that it's an invalid command....

**Comment by Ananya2001-an** [comment]
Solved with PRs #1233 #1226
