### ISSUE TITLE
[Feature] Unset all secrets command

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1235]
**Is your feature request related to a problem? Please describe.**

Deleting secrets one by one can be tedious, especially if we autogenerate secrets or add multiple/change names of various secrets.

**Describe the solution you'd like**

Add a flag to the unset command to delete all secrets so we can re-source them all from our .env file

**Describe alternatives you've considered**

Creating a script that reads the list of existing secrets and loop through each to delete each one. (Not fun)

**Comment by CareTiger** [comment]
reopening as a much wanted feature request

**Comment by bombillazo** [comment]
Any update on this?

**Comment by sweatybridge** [comment]
This is now available in cli beta. Stable will be updated next Tuesday.

```
npx supabase@beta secrets unset
```
