### ISSUE TITLE
bug: database branch should delete when not able to make connection

### ISSUE THREAD

**Issue by Ananya2001-an** [supabase/cli#1238]
**Describe the bug**
On invoking the `db branch create <branch name>` command, we are creating a new exec process but for some reason the `ContainerExecAttach` process fails and we simply return an error saying branch was not created though we still have that exec process running because the next time when I try to create a branch with the same name, it returns an error saying database <branch name> already exists. 

**To Reproduce**
1. `supabase db branch create <name>`
2. if fails on connection, returns error
3. run the first command again
4. database "branch name" already exists

**Expected behavior**
When we fail to establish a connection with the exec process in the server, we should make a delete request to the docker api to do the cleanup.

Here: https://github.com/Ananya2001-an/cli/blob/29cac72e42e7589e50f8fbc38765815e7b6b68a1/internal/db/branch/create/create.go#L98

**Screenshots**
![Screenshot 2023-06-24 134633](https://github.com/supabase/cli/assets/55504616/a86fdd64-08ea-451f-9425-78cd72e8ea9b)

**Additional context**
I am not sure why the connection is failing in my case tho; would love some feedback on that as well. I am using WSL on Win11 and I am running the cli in development.

**Comment by sweatybridge** [comment]
We will be deprecating the `db branch` command soon in favour of remote branching. They are currently available as `supabase --experimental branches` flag.
