### ISSUE TITLE
Error: Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by CareTiger** [supabase/cli#1244]
**Describe the bug**
```
55f7c1dbc3b0: Pull complete
1af02b748d41: Pull complete
cbaf17ee761a: Pull complete
Digest: sha256:8e21c5f8431422a90afa370e65a1a2cad2f4cc0cd65fd17d5a84df76035a6f0f
                                                                               Status: Downloaded newer image for public.ecr.aws/supabase/pgadmin-schema-diff:cli-0.0.5
3.0.1621480950: Pulling from supabase/migra
540db60ca938: Pull complete
d037ddac5dde: Pull complete
629719f9106a: Pull complete
f9ef3a05a91e: Pull complete
a953f4282204: Pull complete
941692ce3501: Pull complete
e04b5858486e: Pull complete
Digest: sha256:7521d74e7cbc39417fbf1d775d99c6ba87548a8a63b9d6f0076ecc0371af9d3a
                                                                               Status: Downloaded newer image for public.ecr.aws/supabase/migra:3.0.1621480950
Error: Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
Try rerunning the command with --debug to troubleshoot the error.
```

**To Reproduce**
download latest images after deleting images/containers/volumes and running` supabase start`

**Expected behavior**
clean download of images and running supabase instances of all services.

**Comment by sweatybridge** [comment]
To help us reproduce docker related issues, please always remember to report your system info.
- CLI version
- OS version
- Docker version

Also, what's the contents of your docker config? ie. `cat /etc/docker/daemon.json`

**Comment by CareTiger** [comment]
$ supabase --version
1.68.6

windows 11

$ docker --version
Docker version 24.0.2, build cb74dfc

$ cat /etc/docker/daemon.json
cat: /etc/docker/daemon.json: No such file or directory

**Comment by sweatybridge** [comment]
Does it work if you use a different image registry?

```bash
SUPABASE_INTERNAL_IMAGE_REGISTRY=ghcr.io supabase start
```

**Comment by CareTiger** [comment]
@sweatybridge  where do i change that setting?

**Comment by sweatybridge** [comment]
```powershell
$env: SUPABASE_INTERNAL_IMAGE_REGISTRY = 'ghcr.io'
supabase start
```

You need to set that env var in powershell.

**Comment by CareTiger** [comment]
i reinstalled docker desktop and was able to download the images successfully. thanks for your help.
