### ISSUE TITLE
`db reset` fails on migrations depending on core schemas

### ISSUE THREAD

**Issue by yacinelakel** [supabase/cli#1255]
**Describe the bug**
After updating to version 1.69.1, migrations that depend on the schema `auth` fail on the columns removed in commit https://github.com/supabase/cli/commit/45093b70afaf78e8e6b9da42fba23c455403f4a4 (for example the `phone` column) with the following error.

`Error: ERROR: column "phone" does not exist (SQLSTATE 42703)`

This seems to be due to the containers running the `auth` migrations after our migrations.

**To Reproduce**
1. `npm install supabase@1.69.1`
2. `npx supabase init`
3. `npx supabase migration new auth_phone_view`
4.  Create a view of including the `auth.users` phone column
```sql
-- Create a view of the users table that includes the auth columns.

CREATE OR REPLACE VIEW public.users AS
SELECT
  id,
  email,
  phone
FROM auth.users;
```
5. `npx supabase db start`
6. `npx supabase db reset`

**Expected behavior**
The migrations are run on the local database successfully, as with 1.69.0. 

**Desktop:**
 - OS: Windows & macOS
 - Version of CLI: ^1.69.1

**Additional context**
Tested with multiple cli versions, up to 1.74.2

**Comment by vickkhera** [comment]
It also breaks applying a `seed.sql` file that populates user records with those columns.

**Comment by CareTiger** [comment]
@sweatybridge Hi!  latest patch still doesn't fix this issue.
$ supabase --version
1.74.2

**Comment by bombillazo** [comment]
For anyone hitting this, use CLI  `v1.69.0` in the meantime.

```sh
npx supabase@1.69.0
```

**Comment by CareTiger** [comment]
it works. thanks @sweatybridge

**Comment by yacinelakel** [comment]
Thanks for the quick fix @sweatybridge!

This fixes the issue as long as you have previously ran `supabase start`.

Our build scripts run `supabase db start` and then `supabase test db`. Currently,  our tests are failing due to the initial schemas not being applied and the same issue regarding missing columns occur.

The reproduction steps are the same.

**Comment by yacinelakel** [comment]
I guess we could use `supabase start -x [unused deps]`....

**Comment by sweatybridge** [comment]
Oh you are right. It still breaks db start. I will make a separate fix for that soon.

**Comment by bombillazo** [comment]
Thanks @sweatybridge !

**Comment by yacinelakel** [comment]
@sweatybridge Release 1.75.2 fixes all our issues now! Thanks and great job. 👍
