### ISSUE TITLE
Generate Typescript enums along with DB types

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1256]
**Is your feature request related to a problem? Please describe.**
It is common with TypeScript to use enums for value selections, validations, and general logic. Often, the DB schema literal types that map to custom datatypes are not enough to implement certain logic in Typescript since they only exist statically in the code.

It would be great if the DB schema generation script would also generate native TypeScript enums for use in the TS logic.

**Describe the solution you'd like**
When generating the DB schema, the command also produces TypeScript enums matching the Database column enums.

**Describe alternatives you've considered**
Manually creating the enums...

**Comment by soedirgo** [comment]
Do you have an example where the string union (e.g. `Database['public']['my_type']`) isn't sufficient?

**Comment by bombillazo** [comment]
When mapping DB values to existing data values from other sources, we end up having to create an enum or enum-like structure to "convert" between values since one cannot use types as values.

**Comment by bombillazo** [comment]
That is one example I can think of from the top of my head, I've had other cases where we've needed the enum values of our DB data-types.

**Comment by soedirgo** [comment]
Do you have a more concrete example? I still don't see where this is needed - e.g. if you need to pass a TypeScript `enum` as part of an `.insert()` query, you can do ``.insert({ column: `${myenum}` })``, and if you need to pass a query result to a TypeScript `enum`, you still need to to cast it to that enum's type.

Re: using values instead of types, I think this is out of scope right now, as the focus is on the static checking use case.

**Comment by hussam3h** [comment]
I am wondering about the same thing. If I've created the enum in the DB, and I can generate the type, how can I access that enum on the frontend of my app? Say I have a US States enum.. can I access that enum from the DB to use in a dropdown? or do I have to create a separate array of states to use?

**Comment by bombillazo** [comment]
The use cases for enums may be uncommon, but they exist. Ultimately, some devs might want enums for different reasons, even when type unions can be used.

But for us it's not a stopper; we've already implemented a code generator that creates our enums based on the Types generated by the Supabase client.

**Comment by soedirgo** [comment]
Got it 👍 I'll mark this as wontfix for now, but open for discussion if there are more requests for this.

**Comment by ldsk-trifork** [comment]
I would like this too.

**Comment by plgingras88** [comment]
As far as I know, we can convert enums to pure javascript arrays or objects, but the same isn't true for interfaces/types. For example, I want to populate a select menu with a list corresponding to all my enums values. For such thing, I actually have to duplicate/fix my auto gen types from Supabase to enums myself for my menus to stay up-to-date with the enums.

If there's a way around let me know, otherwise I believe this request is relevant.

**Comment by serhii-levchenko** [comment]
as alternative you can add your own script in package.json e.g. `"generate:enums": "node ./scripts/generate-enums.js"`

`./scripts/generate-enums.js` file:
```
const fs = require('fs');
const ts = require('typescript');

// Read the types.ts file
const fileContent = fs.readFileSync('./types.ts', 'utf8');

// Function to transform enum names to PascalCase and remove '_enum' suffix
function transformEnumName(name) {
    return name
        .replace(/_enum$/, '') // Remove '_enum' suffix
        .split('_')
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

// Function to parse and extract enums from Database['public']['Enums']
function extractEnums(content) {
    const sourceFile = ts.createSourceFile('types.ts', content, ts.ScriptTarget.Latest, true);
    const enums = {};

    function visit(node) {
        if (ts.isPropertySignature(node) &&
            node.name.escapedText === 'Enums' &&
            node.type &&
            ts.isTypeLiteralNode(node.type)) {

            node.type.members.forEach(member => {
                if (ts.isPropertySignature(member) &&
                    member.type &&
                    ts.isUnionTypeNode(member.type)) {

                    const enumName = transformEnumName(member.name.escapedText);
                    const enumValues = member.type.types.map(type => {
                        if (ts.isLiteralTypeNode(type) && type.literal && ts.isStringLiteral(type.literal)) {
                            return type.literal.text;
                        }
                        return null;
                    }).filter(Boolean);

                    enums[enumName] = enumValues;
                }
            });
        }

        ts.forEachChild(node, visit);
    }

    visit(sourceFile);

    return enums;
}

// Function to create enum strings
function createEnumStrings(enums) {
    return Object.entries(enums).map(([enumName, enumValues]) => {
        const enumMembers = enumValues.map(value => `${value} = "${value}"`).join(',\n  ');
        return `export enum ${enumName} {\n  ${enumMembers}\n}`;
    }).join('\n\n');
}

// Extract enums
const extractedEnums = extractEnums(fileContent);

// Create enum strings
const enumStrings = createEnumStrings(extractedEnums);

// Write enums to a new file
fs.writeFileSync('./enums.ts', enumStrings);
```

as an output you get `enums.ts` file with all your enums (PascalCase, without `enum` suffix`) - e.g.
```
export enum LogLevel {
  debug = "debug",
  info = "info",
  warning = "warning",
  error = "error"
}
```

**Comment by plgingras88** [comment]
Thanks for sharing @serhii-levchenko, this is a great way to start a new year. ;-) 

For sure this goes into my supabase toolbox !

**Comment by govi218** [comment]
@soedirgo I think there certainly is a common use case, which is to generate a radio button type input from an enum defined in the db. This need arises for a variety of applications, and a type union isn't good as I cannot iterate over them. Generating TS enums with something simple like @serhii-levchenko's script above seems like a healthy compromise.

**Comment by arpithindukuri** [comment]
@serhii-levchenko I had an enum with ~200 values (country currency codes, like USD, CAD, etc.), as well as others that could change in the future. This worked perfect. Thanks!

**Comment by mwolf1989** [comment]
Face the same problem at the moment. Happy to see this improved at one point.

**Comment by RemyNtshaykolo** [comment]
Thanks @serhii-levchenko, just one small note, it does not work when enum has only one value

**Comment by John0x** [comment]
@soedirgo there are some other important use cases as well.
One would be, if you need to iterate over the enum fields, which isn't possible with string unions. Another is input validation with Zod. If you would have the native enum, you could just use that. With the string unions, you have to maintain an extra array of the strings. This should be covered by the supabase cli in my opinion, since it's a pretty common usecase.

**Comment by tylerkatz** [comment]
If anyone cares for a Typescript utility using only in-memory operations, multiple schema support and stdout printing for easy redirection to a file (just like the Supabase scripts work) - I have the gist for you: https://gist.github.com/tylerkatz/d68be375635114b3e8041ae448888b43

```
import { Database } from '../src/database.types';
import ts from 'typescript';
import path from 'path';

function getSchemaEnums(schema: keyof Database) {
  const dbTypesPath = path.resolve(__dirname, '../src/database.types.ts');
  const options: ts.CompilerOptions = {
    target: ts.ScriptTarget.Latest,
    module: ts.ModuleKind.CommonJS,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
  };

  const sourceFile = ts.createSourceFile(
    'temp.ts',
    `import { Database } from '${dbTypesPath}'; type Enums = Database['${schema}']['Enums'];`,
    ts.ScriptTarget.Latest,
    true
  );

  const host = ts.createCompilerHost(options);
  const originalGetSourceFile = host.getSourceFile;
  host.getSourceFile = (fileName: string, ...args: any[]) => {
    if (fileName === 'temp.ts') return sourceFile;
    if (fileName === dbTypesPath) {
      return ts.createSourceFile(fileName, require('fs').readFileSync(dbTypesPath, 'utf-8'), ts.ScriptTarget.Latest);
    }
    return originalGetSourceFile.call(host, fileName, ...args);
  };

  const program = ts.createProgram(['temp.ts'], options, host);
  const checker = program.getTypeChecker();
  const enums: Record<string, string[]> = {};

  function visit(node: ts.Node) {
    if (ts.isTypeAliasDeclaration(node) && node.name.text === 'Enums') {
      const type = checker.getTypeAtLocation(node);
      for (const prop of type.getProperties()) {
        const propType = checker.getTypeOfSymbolAtLocation(prop, node);
        if (propType.isUnion()) {
          enums[prop.name] = propType.types
            .map(t => t.isLiteral() ? t.value as string : null)
            .filter((v): v is string => typeof v === 'string');
        }
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return enums;
}

const validSchemas = ['public', 'auth', 'graphql_public'] as const;
const schemas = process.argv.slice(2).length > 0 ? process.argv.slice(2) : ['public'];
const allEnums: Record<string, Record<string, string[]>> = {};

for (const schema of schemas) {
  if (validSchemas.includes(schema as any)) {
    allEnums[schema] = getSchemaEnums(schema as keyof Database);
  }
}

const output = Object.entries(allEnums)
  .map(([schema, schemaEnums]) =>
    Object.entries(schemaEnums)
      .map(([name, values]) => {
        const enumValues = values
          .map(value => `  ${value.replace(/[^a-zA-Z0-9_]/g, '_')} = "${value}"`)
          .join(',\n');
        return `export enum ${schema}_${name} {\n${enumValues}\n}`;
      })
      .join('\n\n')
  )
  .join('\n\n');

process.stdout.write(`// Generated file - Do not edit manually\n// Generated by packages/supabase/tools/generate-enums.ts\n\n${output}\n`);
```

**Comment by stefanatanasovmk** [comment]
Thanks @serhii-levchenko 

Here is my suggestion, the database types and the enums are generated from one script:
```
#!/bin/bash

# Load environment variables from .env
export $(grep -v '^#' .env | xargs)

# Run the Supabase CLI command
npx supabase gen types typescript --project-id "$PROJECT_REF" --schema public > database.types.ts

# Run the enum generator
node ./scripts/generate-enums.js
```

In `package.json` in scripts I added "generate": "bash ./scripts/run.sh"`.

Then I can run `yarn generate` / `npm generate` and I'll get my database types and enums from a single command, ready to be use throughout the code.

**Comment by LovaArutinovi** [comment]
if someone needs enums with camel case keys and wants to have Enum at the end of name instead of Type 💪🚀
`const fs = require('fs');
const ts = require('typescript');
const { toCamel } = require('ts-case-convert');

// Read the types.ts file
const fileContent = fs.readFileSync('./src/types/supabase.types.ts', 'utf8');

// Function to transform enum names to camelCase or PascalCase
function transformEnumName(name) {
  // Convert the name to PascalCase
  name = name
    .replace(/_enum$/, '') // Remove '_enum' suffix
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  // Remove 'Type' at the end, then add 'Enum' if not already present
  if (name.endsWith('Type')) {
    name = name.replace(/Type$/, '') + 'Enum';
  } else {
    name = name + 'Enum';
  }

  return name;
}

// Function to parse and extract enums from Database['public']['Enums']
function extractEnums(content) {
  const sourceFile = ts.createSourceFile('types.ts', content, ts.ScriptTarget.Latest, true);
  const enums = {};

  function visit(node) {
    if (ts.isPropertySignature(node) && node.name.escapedText === 'Enums' && node.type && ts.isTypeLiteralNode(node.type)) {
      node.type.members.forEach(member => {
        if (ts.isPropertySignature(member) && member.type && ts.isUnionTypeNode(member.type)) {
          const enumName = transformEnumName(member.name.escapedText);
          const enumValues = member.type.types
            .map(type => {
              if (ts.isLiteralTypeNode(type) && type.literal && ts.isStringLiteral(type.literal)) {
                return type.literal.text;
              }
              return null;
            })
            .filter(Boolean);

          enums[enumName] = enumValues;
        }
      });
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);

  return enums;
}

// Function to create enum strings, handling keys that start with numbers and converting to camelCase
function createEnumStrings(enums) {
  return Object.entries(enums)
    .map(([enumName, enumValues]) => {
      const enumMembers = enumValues
        .map(value => {
          // Fix: Wrap enum names starting with a number in quotes
          const enumKey = value.match(/^\d/) ? `"${toCamel(value.replace(/ /g, ''))}"` : toCamel(value.replace(/ /g, ''));
          return `${enumKey} = "${value}"`; // Remove spaces in enum values
        })
        .join(',\n  ');
      return `export enum ${enumName} {\n  ${enumMembers}\n}`;
    })
    .join('\n\n');
}

// Extract enums
const extractedEnums = extractEnums(fileContent);

// Create enum strings
const enumStrings = createEnumStrings(extractedEnums);

// Write enums to a new file
fs.writeFileSync('./src/types/supabase.enums.ts', enumStrings);
`
