### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Schmell** [supabase/cli#1269]
**Describe the bug**
When trying to login the CLI asks for a token, but you cannot paste or type at the prompt

**To Reproduce**
`npx supabase login`
then try to paste and nothing happens
pressing enter suggests that you have not entered in a token

**Expected behavior**
I would expect to log me in

**Screenshots**
not really

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI: 1.75.2
 - Version of supabase-js: 2.26.0
 - Version of Node.js: v18.15.0

**Additional context**

**Comment by sweatybridge** [comment]
Closing as duplicate. You may find the suggestions in these issues useful

- https://github.com/supabase/cli/issues/1000#issuecomment-1590711838
- https://github.com/supabase/cli/issues/1054#issuecomment-1536393966
