### ISSUE TITLE
Service Not Healthy : API not working

### ISSUE THREAD

**Issue by romain-sen** [supabase/cli#1275]
**Describe the bug**
Cannot run supabase locally correctly. 
When starting it with `supabase start`, get the following error  : `Error: service not healthy: [supabase_rest_student-review supabase_deno_relay_student-review]`.
When starting using the flag `--ignore-health-check`, as recommanded on #778, the service start but still gives the message `Error: service not healthy: [supabase_rest_student-review supabase_deno_relay_student-review]`.
Even if the service started, the api doesn't work : `http://localhost:54323/project/default/api` gives an error 500. Same error with I make a request like : `http://localhost:54321/rest/v1/profiles?select=*` that returns : (502) "An invalid response was received from the upstream server".

**To Reproduce**
run `supabase start --ignore-health-check`
go on  `http://localhost:54323/project/default/api`

**Expected behavior**
Expect the api to work. The doc should work and request to the api url should works.

**Screenshots**
![image](https://github.com/supabase/cli/assets/58177664/08b11dec-2910-4e75-a65d-f5895738fcdb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version of CLI : 1.64.8
 - Version of Node.js (if applicable) : v18.16.0

**Additional context**
Some additional logs : 
![image](https://github.com/supabase/cli/assets/58177664/8839931b-35f1-4135-93c3-b91da1ddd7fa)

```
➜  student-review git:(test-app) ✗ docker logs 5eedaa18b5f5
03/Jul/2023:14:44:22 +0000: Attempting to connect to the database...
03/Jul/2023:14:44:22 +0000: Connection successful
03/Jul/2023:14:44:22 +0000: Listening on port 3000
03/Jul/2023:14:44:22 +0000: Config reloaded
03/Jul/2023:14:44:22 +0000: Listening for notifications on the pgrst channel
03/Jul/2023:14:44:22 +0000: Schema cache loaded
03/Jul/2023:14:44:22 +0000: Attempting to connect to the database...
...
03/Jul/2023:14:44:24 +0000: Connection successful
03/Jul/2023:14:44:24 +0000: Config reloaded
03/Jul/2023:14:44:24 +0000: Schema cache loaded
FATAL:  terminating connection due to administrator command
03/Jul/2023:14:45:18 +0000: Retrying listening for notifications on the pgrst channel..
03/Jul/2023:14:45:18 +0000: Attempting to connect to the database...
Could not listen for notifications on the pgrst channel
03/Jul/2023:14:45:18 +0000: Retrying listening for notifications on the pgrst channel..
03/Jul/2023:14:45:18 +0000: {"code":"PGRST000","details":"connection to server at \"supabase_db_student-review\" (172.21.0.2), port 5432 failed: FATAL:  database \"postgres\" does not exist\nDETAIL:  It seems to have just been dropped or renamed.\n","hint":null,"message":"Database connection error. Retrying the connection."}
03/Jul/2023:14:45:18 +0000: Attempting to reconnect to the database in 0 seconds...
03/Jul/2023:14:45:19 +0000: Connection successful
...
03/Jul/2023:14:45:19 +0000: Config reloaded
03/Jul/2023:14:45:20 +0000: Schema cache loaded
03/Jul/2023:14:45:30 +0000: Retrying listening for notifications on the pgrst channel..
03/Jul/2023:14:45:30 +0000: Attempting to connect to the database...
Could not listen for notifications on the pgrst channel
03/Jul/2023:14:45:30 +0000: {"code":"PGRST000","details":"connection to server at \"supabase_db_student-review\" (172.21.0.2), port 5432 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n","hint":null,"message":"Database connection error. Retrying the connection."}
03/Jul/2023:14:45:30 +0000: Retrying listening for notifications on the pgrst channel..
03/Jul/2023:14:45:30 +0000: Attempting to reconnect to the database in 0 seconds...
03/Jul/2023:14:45:31 +0000: Connection successful
03/Jul/2023:14:45:31 +0000: Config reloaded
03/Jul/2023:14:45:31 +0000: Listening for notifications on the pgrst channel
03/Jul/2023:14:45:31 +0000: Schema cache loaded
...
03/Jul/2023:14:48:08 +0000: Connection successful
03/Jul/2023:14:48:08 +0000: Listening on port 3000
03/Jul/2023:14:48:08 +0000: Config reloaded
03/Jul/2023:14:48:08 +0000: Listening for notifications on the pgrst channel
03/Jul/2023:14:48:08 +0000: Schema cache loaded
```

**Comment by sweatybridge** [comment]
Does `supabase start` work for you on a new local project without any migrations?

If it works, you may try to further narrow down the problem by removing local migrations, starting from the latest one.

**Comment by romain-sen** [comment]
I started a new project named "supCliTest" and ran `supabase init`.
When running supabase start : 
```
service not healthy: [supabase_rest_supCliTest supabase_edge_runtime_supCliTest]
```

I also upgraded my supabase cli version:
```
➜ supCliTest  supabase --version
1.75.3
```

**Comment by xHergz** [comment]
@romain-sen any luck with this? I have the [same issue](https://github.com/supabase/cli/issues/778#issuecomment-1645816323) but with `supabase_studio`.

**Comment by rmukhia** [comment]
> > @romain-sen any luck with this? I have the [same issue](https://github.com/supabase/cli/issues/778#issuecomment-1645816323) but with `supabase_studio`.
> 
> I purged everything (docker container, images, cache...). When I came back after a week (little pause on this project), I reinstalled everything and it worked. I am sorry but except saying keep trying and one day it will work maybe, I have no better advice...

I was facing the same issue with `supabase_rest` and `supabase_edge_runtime` in Ubuntu 23.04.
I tried to purge all the images, containers and volumes and downgraded supabase-cli to 1.77.9 but still faced the same issue.

However on inspecting the docker container `supabase_kong*`, at  `Config.EntryPoint` , the upstream url was set to some random IP in my network.

Instinctively I concluded that the supabase docker network did not have other containers when kong is started and kong cannot resolve the other services. 

Then I cloned this repo, and then I moved this section which starts kong container 
https://github.com/supabase/cli/blob/20a54db3b63d6b00aff8778690d8554afc78411b/internal/start/start.go#L274

to the very end after all other containers are started. 
https://github.com/supabase/cli/blob/20a54db3b63d6b00aff8778690d8554afc78411b/internal/start/start.go#L691

After compiling and running, the entire supabase cli stack successfully ran without any problem.

Surprisingly enough, after stopping the containers(no backup), I went back to my original project and started the supabase stack with supabase@1.81.1 and it worked in my original project as well.

**Comment by rmukhia** [comment]
Update: The solution mentioned in the above comment does not work. I faced the same issue today as well.

After researching around, it seems like docker uses the the host systems `/etc/resolv.conf` for DNS server resolution. 

My internet provider redirects all unknown host to a predefined host to show a 404 page.

The kong container picks up the same settings.
```
$ docker exec -it supabase_kong_cli cat /etc/resolv.conf

search abc.com
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

And tries to resolve all internal docker hostname to ***.abc.com which in turn resolves to the DNS sink host which is the Ip address I see in upstream_url. 

Making changes in `/etc/resolv.conf`  is not permanent so the easy fix for me right now is to edit the `/etc/resolv.conf` in the host system and change to Google DNS server.
```
nameserver 8.8.8.8
options edns0
```
and then start supabase so that kong can resolve the docker container addresses.

```
$ docker exec -it supabase_kong_cli cat /etc/resolv.conf
nameserver 127.0.0.11
options edns0 ndots:0
```

In the next reboot of the host system the `/etc/resolv.conf` will be regenerated with the default settings.

**Comment by sweatybridge** [comment]
The random ip resolution should be fixed in latest release. We are now using 127.0.0.1 everywhere instead of trying to resolve localhost. Feel free to open a new issue if this still doesn't work.

**Comment by wiwa** [comment]
I believe this is an issue which continues to exist (as of version `1.178.2`), at least due when using Tailscale to ssh into my dev machine. I resolved it by starting supabase after deleting `/etc/resolv.conf` (and then adding it back after supabase started).
