### ISSUE TITLE
`storage` RLS policies missing from `supabase db diff`

### ISSUE THREAD

**Issue by nbarrow-inspire-labs** [supabase/cli#1276]
**Describe the bug**
Running the command `supabase db diff` does not recognize any RLS policies created in `storage.objects` or `storage.buckets`. 

**To Reproduce**
1. Create a new policy for `storage.buckets` via a script or via the [localhost web interface](http://localhost:54323/project/default/storage/policies).
2. run the `diff` command (`supabase db diff`) or save to a file (`supabase db diff -f diff`)
3. the following is output:
```
Diffing schemas: extensions,public
Finished supabase db diff on branch development/nick.

No schema changes found
```

**Expected behavior**
Obviously buckets and storage objects **should not/cannot** be included in `supabase db diff` (see https://github.com/supabase/cli/issues/859). I am not looking for the buckets themselves to be `diff`'d, but only the **policies** for the `storage` schema. Currently, I am having to manually copy and paste the output of my policies, created in the `Review` step when creating a new policy, into a migration file (`supabase migration new`). Such policies could/should(?) be included in `supabase db diff`. 

**Desktop (please complete the following information):**
 - OS: Mac OS 13.3 (22E252)
 - Version of CLI: 1.75.3

**Comment by sweatybridge** [comment]
We intentionally removed `storage` schema from the list of schemas diffed by default because it was prone to errors. You can diff the RLS policies manually with `supabase db diff --schema storage`.

**Comment by nbarrow-inspire-labs** [comment]
@sweatybridge gotcha, thanks! I totally forgot about the `schema` flag.

**Comment by Angus-Moore-Dev** [comment]
What would be the process to diff the actual storage buckets themselves (not just the RLS policies for them)?

**Comment by sweatybridge** [comment]
> What would be the process to diff the actual storage buckets themselves (not just the RLS policies for them)?

There isn't a command to download buckets at the moment. @Angus-Moore-Dev do you mind creating a separate issue? We can look into supporting it.

**Comment by nbarrow-inspire-labs** [comment]
@Angus-Moore-Dev I believe, for the most part, you can use the `schema` flag of the CLI to `diff` the RLS policies themselves, as @sweatybridge mentions above; in terms of the actual buckets, they are just rows under the `storage` schema, in the `buckets` table; you could use `pg_dump` to dump just that table (see [here](https://stackoverflow.com/a/3682944/14717625)), or you can use migrations files to CRUD specific rows in that table. We use the latter option and utilize migrations files to CRUD `storage.objects`.

Via Migrations Files:

- creating:
```sql
-- add additional columns here as necessary, such as `allowed_mime_types`
insert into storage.buckets (id, name, public)
  values
    ('my_bucket', 'my_bucket', 'TRUE');
```
- updating:
```sql
UPDATE storage.buckets
  SET
    allowed_mime_types = array['image/jpg','image/png','application/pdf','text/csv'],
    file_size_limit = 10485760
  WHERE
    storage.buckets.id = 'my_bucket';
```
- deleting: `delete from storage.buckets where buckets.id='my_bucket';`

**Comment by Angus-Moore-Dev** [comment]
@sweatybridge sorry for the late reply, yes absolutely I can create one!
