### ISSUE TITLE
Add a note to restart supabase after upgrading

### ISSUE THREAD

**Issue by shaunsaker** [supabase/cli#1281]
**Link**
https://supabase.com/docs/guides/cli#updates

**Describe the problem**
After upgrading from supabase cli v1.35.? to v1.75.3, I encountered an error `{"message":"name resolution failed"}` when serving my functions locally using `supabase functions serve`. The cause of this issue was that I had outdated supabase containers running. To resolve this, I had to stop and start supabase to fetch the latest containers.

**Describe the improvement**
Add a note to restart supabase after upgrading. E.g.

To ensure that you have the most recent versions of the supabase containers, remember to restart them by executing the following commands:

```
supabase stop
supabase start
```

**Additional context**
N/A

**Comment by sweatybridge** [comment]
Thanks for the suggestion.
