### ISSUE TITLE
Incomplete output from "supabase gen types typescript --local"

### ISSUE THREAD

**Issue by President** [supabase/cli#1295]
**Describe the bug**
I have quite large database schema. When I run "supabase gen types typescript --local" it generates output which is incomplete - it breaks in the middle of some structure definition:
...
   Update: {
          code?: string | null
          long_title?:
            | Database["public"]["CompositeTypes"]["multilang_text"]
            | null
          short_title?:
    --- END OF OUTPUT
The output size is about 2.1Mb and has 53821 lines.
How to fix this?

**To Reproduce**
Have large schema
1. supabase gen types typescript --local > typescript/apps/frontend-v3/src/supabase/database.types.ts
2. open generated file and scroll down
3. See that file is incomplete

**Expected behavior**
File should be complete

**Desktop (please complete the following information):**
 - OS X / Macbook Air on M2
 - Version of CLI: 1.75.3
 - Version of Node.js: v20.3.1

**Additional context**
First we had this issue on computers with Windows. But today (maybe schema grow a little bit over last few days) I constantly see this issue on OS X.

**Comment by sweatybridge** [comment]
Hello, could you clarify if the `supabase gen types typescript` command ran successfully with exit code 0? If not, could you share the error logs here?

**Comment by soedirgo** [comment]
Closing as non-reproducible
