### ISSUE TITLE
Supbase Stop Doesn't Stop Running Docker Containers

### ISSUE THREAD

**Issue by alteredorange** [supabase/cli#13]
# Bug report

## Describe the bug

`supabase stop` does not stop running docker containers.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. supabase init
2. supabase start
3. supabase stop
4. Notification of "Stopped local Supabase"
5. supabase docker group is still running.

## Expected behavior

'supabase stop' would stop all supabase related docker containers.

## Screenshots

![image](https://user-images.githubusercontent.com/2141012/113314339-755c5800-92c9-11eb-9819-81238a05cd0d.png)

## System information

- OS: Windows running ubuntu and docker desktop through WSL2
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-cli: 0.3.3
- Version of Node.js: 15.6.0

**Comment by soedirgo** [comment]
Hey @alteredorange, this should be fixed in #10, the latest release should have that fix (including the fix for the other issue). Can you see if that works?

**Comment by alteredorange** [comment]
Ah yes, indeed it does! Sorry about that, had already submitted the big before upgrading!
