### ISSUE TITLE
Edge functions are nearly impossible to write if project directory is a monorepo

### ISSUE THREAD

**Issue by evelant** [supabase/cli#1303]
**Describe the bug**

This may not be actionable by the Supabase team since it may be a bug in Deno but I at least wanted to bring it up here for visibility. Since Supabase by default puts the edge functions project in a sub-directory this breaks the ability to edit Deno code with Deno LSP if there is a root package.json. 

For more detail see the issue filed at vscode_deno: https://github.com/denoland/vscode_deno/issues/878

**To Reproduce**
1. Create a supabase project
2. Use a root package.json for a monorepo setup
3. Observe that editing edge function code doesn't work correctly due to Deno LSP conflicting with TSServer

**Expected behavior**
Default project structure should try to work around Deno's quirks. Or more ideally allow building edge functions with a less problematic runtime such as Bun.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser (if applicable) N/A
 - Version of CLI N/A
 - Version of supabase-js (if applicable) N/A
 - Version of Node.js (if applicable) N/A

**Additional context**

**Comment by laktek** [comment]
@evelant we will look into providing customization options for the project structure.

Also, would you be interested in jumping on a quick call with me to summarize your monorepo setup and how you use edge functions? It will help us to design a better solution to handle different use cases.

**Comment by evelant** [comment]
@laktek Sure I could chat tomorrow, just let me know when

**Comment by soedirgo** [comment]
@evelant are you still having this issue? This [setup](https://github.com/soedirgo/my-app) seems to be working as expected for me.

**Comment by ChuckJonas** [comment]
I have a mono repo with `supabase`, a `react-app` (typescript vite), and a `scripts` (typescript node) folder for some.  

In vscode I can open the root project and edit the `supabase/functions` app OR the `react-app`.  However, once I start editing the react-app, the deno files for some reason start getting picked up by the ts LSP instead of the deno LSP.

I think there's probably some way to configure vscode workspaces...

**Comment by sweatybridge** [comment]
CLI now has an option to setup vscode workspace for edge functions when running [supabase init](https://supabase.com/docs/reference/cli/supabase-init). Does it works for you?

**Comment by evelant** [comment]
@sweatybridge  Unfortunately not, I already tried the vscode workspace trick. It seems there are multiple bugs in vscode_deno which unfortunately don't seem to be getting any attention from the Deno team. They've seen no movement for at least the last 3 months. https://github.com/denoland/vscode_deno/issues/878 https://github.com/denoland/vscode_deno/issues/967 https://github.com/denoland/vscode_deno/issues/873 https://github.com/denoland/vscode_deno/issues/488

Has the Supabase team considered supporting something other than Deno for the edge runtime? I realize you're pretty invested in it given the use of Deno deploy and all of the custom tooling you've had to build to make it work, but Deno is just _so incredibly painful_ to work with. I've had to code edge functions without type checking, import maps break all the time and must be manually kept in sync with package.json versions used in shared code, I get random 502 errors on clients with no logs indicating a problem, packages imported from esm.sh only work sometimes, and so on.

Bun would be a fantastic alternative. It _just works_ with modern code and ecosystem and has batteries included tooling for seemingly a lot of the stuff you've had to hack into working Deno (like bundling local shared code).

**Comment by erickreutz** [comment]
I would also like to voice my frustrations in regard to using edge functions in a monorepo with any sort of complexity. I'd like to import code I have in `packages/*` but it's nearly impossible. Deno was a mistake. Forced to use Vercel instead.

**Comment by otang** [comment]
I really agree. Edge functions in Deno in my repo has been the single biggest pain with using Supabase. I really wish we could just have node edge functions, it would make the project so much simpler to maintain

**Comment by ardabeyazoglu** [comment]
> I would also like to voice my frustrations in regard to using edge functions in a monorepo with any sort of complexity. I'd like to import code I have in `packages/*` but it's nearly impossible. Deno was a mistake. Forced to use Vercel instead.

This is the only pain in my stomach as of now, otherwise vscode related issues are almost ok now. Any serious application must have a proper backend (like nest etc.) in addition to edge functions and monorepo is a reality nowadays. Currently, i am writing code inside supabase/functions and import them to nest modules when i need them but this is not optimal. If only supabase let importing/copying other packages from a parent folder, this could be solved as well.

**Comment by sweatybridge** [comment]
> If only supabase let importing/copying other packages from a parent folder, this could be solved as well.

We have addressed a few issues in the last week. I believe importing packages from parent folder is supported properly via import map now. Could you give the latest CLI version a try and let me know? For eg. 

1. Create `supabase/functions/import_map.json` with the following contents:

```json
{
  "imports": {
    "common": "../../common/"
  },
}
```

2. And import it inside `supabase/functions/hello/index.ts` as follows

```typescript
import { SomeType } from "common/types.ts";
```

3. For Deno LSP, add import map to `.vscode/settings.json`

```json
{
  "deno.enablePaths": ["supabase/functions"],
  "deno.importMap": "supabase/functions/import_map.json",
  "deno.lint": true
}
```

**Comment by ardabeyazoglu** [comment]
@sweatybridge it doesn't work for me. It doesn't deploy with latest deno and supabase versions. I am also on windows 11.

The import map has `"@mylib/shared/": "./_global/src/"` and my function has `import { ApplicationError } from "@mylib/shared/types/errors.ts";` . This way deno-lint and typescript see the code valid, but supabase deploy throws the following error:

`Error: failed to load 'file:///home/deno/_global/src/types/errors.ts': Module not found "file:///home/deno/_global/src/types/errors.ts"`

I don't know why it is trying to fetch it from "/home/deno". The same code works when i import using `import { ApplicationError } from "../_global/src/types/errors.ts";`

The directory structure is as follows:
```
supabase/functions/
   import_map.json
   myfunction/
       index.ts
   _global/
        src/
           types/
               errors.ts

**Comment by sweatybridge** [comment]
> It works when i add "functions" to the path like ""@mylib/shared/": "./functions/_global/src/". However, this time deno lint fails to detect the import in vscode.

Have you updated CLI to latest version v1.176.4? We specifically fixed [this issue](https://github.com/supabase/cli/issues/1338) with import map.

**Comment by ardabeyazoglu** [comment]
@sweatybridge Yes, it is 1.176.4.

**Comment by sweatybridge** [comment]
@ardabeyazoglu could you show me the contents of all the json files in `supabase/.temp/import_maps`?

**Comment by ardabeyazoglu** [comment]
@sweatybridge there is no such file. This is the contents of the directory.

-a---          12/06/2024    12:07              8 cli-latest
-a---          04/06/2024    09:15              8 gotrue-version
-a---          04/06/2024    09:15            109 pooler-url
-a---          04/06/2024    09:15              8 postgres-version
-a---          04/06/2024    09:15             20 project-ref
-a---          04/06/2024    09:15              7 rest-version
-a---          04/06/2024    09:15              6 storage-version

**Comment by sweatybridge** [comment]
Thanks for your help, I managed to reproduce the issue and release a fix. Could you try `npx supabase@beta functions serve / deploy`?

**Comment by ardabeyazoglu** [comment]
@sweatybridge I can confirm it works with supabase cli 1.176.10. Having import_map inside functions folder, and using relative path like "../../parent-lib/" works when deploying and running the function as well as linting in vscode.
Well done, thanks!

**Comment by erickreutz** [comment]
This issue is far from closed.

**Comment by haschu** [comment]
@sweatybridge For me it only works when the file I try to import is at least in the project root directory (using `npx supabase@beta functions serve`)

For for example:

```
/path/to
  some_other_file.ts
  my-project/
    some_file.ts
    supabase/
      functions/
        import_map.json
```

import_map.json
```
{
  "some_file": "../../some_file.ts" <---- works
  "some_other_file": "../../../some_other_filter.ts" <---- works not
}
```

I'm also able to import `some_file` via an absolute path while `some_other_file` doesn't seem to be work.

I would be happy about any advice  🙂

**Comment by ccarstens** [comment]
I started working on a code base using supabase and I'm quite surprised that I'm not able to execute code in edge functions from outside the `/supabase/functions` directory. There are some types and implementations I want to use both in front and back end and beyond that I don't want to couple my logic to supabase. 

It seems like the only option is to publish the shared logic to npm, which unnecessarily complex for the use case. 
Very possible that I'm not seeing an obvious solution here, so if anyone has found out how to reference code outside the `/supabase` folder, please let me know :) <3

**Comment by jhsu98** [comment]
I've been having trouble with this as well. I was able to do the initial setup for the [NextJS Subscription Payments starter](https://github.com/vercel/nextjs-subscription-payments) However, once I needed to add a Supabase Edge Function I'm running into several Deno-related issues in VS Code.

**Comment by pickwick9** [comment]
I have the same issue as @ccarstens. I get InvalidWorkerCreation: worker boot error failed to load whenever i try to import things from outside of the supabase/functions/ directory

**Comment by cohlar** [comment]
I have just given this a try on my project and came to the following results.

1. if `import_maps.json` refers to a file (e.g. `"errors": "../../utils/errors.ts"`) and that file has no imports, everything works fine

2. I start having a runtime `InvalidWorkerCreation` error when `errors.ts` imports other files without specifying the file type (must import from `*.ts` to make it work)

3. I am getting both a runtime `InvalidWorkerCreation` error and a compile error `Relative import path ... not in import map ...` if I try to import a full directly (e.g. `"utils": "../../utils/"`) and then try to import from a file within this directory (e.g. import from `utils/errors.ts`)

That's great progress compared to what it used to be!
Hope it gets even smoother 😎

**Comment by laktek** [comment]
We have an experimental update to CLI which changes how imports are handled (removes the Docker dependency, so we can access local files without restrictions). https://github.com/orgs/supabase/discussions/33613

This should simplify sharing dependencies outside of `supabase/` directory.

**Comment by armartinez** [comment]
Hi, I'm trying to do an import using 'deno.json' but I can't get it to work, is supposed to work the same as 'import_map.json' ?
