### ISSUE TITLE
Inconsistent collation between local/CLI projects and hosted platform

### ISSUE THREAD

**Issue by olirice** [supabase/cli#1309]
On the hosted platform 
```
show lc_collate
```
is `C.UTF-8` but on local/cli/docker projects its `en_US.utf-8`

TODO:
https://github.com/supabase/cli/commit/0e4f1b279abe7cfe86aff98457265292bd2180b4#diff-13b1b6dafbe0eaec74d05eba0c98b8eac2654a90be6c1981db154cb5beed807cR128

need to add lc-collate here in addition to ctype ^

**Comment by sweatybridge** [comment]
https://github.com/supabase/cli/pull/1308 fix has been released to latest stable channel.
