### ISSUE TITLE
[DX] show the currently active branch

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#131]
# Feature request

## Is your feature request related to a problem? Please describe.

Below these, it would be good to show the active branch:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/10214025/148121051-25b508d3-b2c0-48b5-a2f0-fe1b771e57b0.png">

## Describe the solution you'd like

```
You're currently on the `main` database branch.
Run 
  `supabase db branch create` to create a new branch
  `supabase db branch switch` to switch to an existing branch
  `supabase db branch list` to see all your branches
```

**Comment by sweatybridge** [comment]
With preview branching, the active branch name is the same as git branch.
