### ISSUE TITLE
Support for Windows ARM64

### ISSUE THREAD

**Issue by StrawMonkey** [supabase/cli#1315]
Loving Supabase so far, but we've gotten a bit stuck trying to use the supabase-cli on a Surface 9. I think ARM64 is not supported? Would be great if it was or if there was an option to force install the AMD64 version.

````
Downloading https://github.com/supabase/cli/releases/download/v1.77.9/supabase_windows_arm64.tar.gz
npm ERR! node:events:489
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR!``

**Comment by sweatybridge** [comment]
Yea, we haven't been compiling for windows arm64 as no one was requesting for it. Thanks for creating this issue and we will look into it.

**Comment by sweatybridge** [comment]
We've added windows arm64 build to our releases since 1.126.1. We don't have a Surface 9 to verify but feel free to reopen this issue if it doesn't work for you.
