### ISSUE TITLE
Storage buckets do not copy over to development

### ISSUE THREAD

**Issue by francistogram** [supabase/cli#1318]
**Describe the bug**
Storage buckets do not copy over to development

**To Reproduce**
1. On `supabase@1.77.9`
2. `npx supabase start`
3. Go to http://localhost:54323/project/default/storage/policies
4. You'll see that the policies have carried over but there are no buckets and unable to create one

**Expected behavior**
Storage buckets (not the files) would copy over with the policies so that uploading and downloading would work as expected

**Screenshots**
<img width="321" alt="image" src="https://github.com/supabase/cli/assets/3721449/a83f4e49-28b0-429f-983a-b95fc559bd68">

**Desktop (please complete the following information):**
 - OS: Mac 12.5.1
 - Browser: Brave
 - Version of CLI: `1.77.9`

**Additional context**
I was previously on `supabase@1.38.0` and that worked just fine and just recently upgraded to the latest

**Comment by sweatybridge** [comment]
Thanks for letting us know of this issue. You are right that the dumped buckets may not be compatible with future versions of our storage schema. I will check with the team to see if we can improve this.

Meanwhile, the workaround is to re-dump the buckets from your remote project:

```bash
supabase db dump --data-only --schema storage
```
