### ISSUE TITLE
Support for Azure AD Single-Tenant Authentication in Supabase CLI

### ISSUE THREAD

**Issue by Frame1910** [supabase/cli#1320]
**Describe the bug**
Azure AD auth provider doesn't take in a tenant url, and therefore cannot suport single-tenant applications.
In order to authenticate with a single tenant application in Azure, the auth provider must hit the tenant-specific URL:
"https://login.microsoftonline.com/<tenant_id>" rather than the /common endpoint (which is only for multi-tenant applications)

**To Reproduce**
1. Setup local development for supabase as per docs
2. Create app registration in Azure portal as per docs, except pick the single tenant option for supported account types:

![image](https://github.com/supabase/cli/assets/22231370/54c02045-d532-4741-b35d-a7bd27104f7d)

3. Add config options to config.toml as per docs:
```
[auth.external.azure]
enabled = true
client_id = "env(SUPABASE_AZURE_CLIENT_ID)"
secret = "env(SUPABASE_AZURE_CLIENT_SECRET)"
redirect_uri = "https://localhost:3000"
```
4. Try to login

**Expected behavior**
You should be authenticated with Azure AD and the normal login flow continues. When you want to login to an internal, company-only application, single tenant is necessary for security (ie. only people with a company email address can authenticate), which is actually one of the main reasons people use Azure AD in the first place, rather than other OAuth providers.

Supabase proper already implements the tenant url:
![image](https://github.com/supabase/cli/assets/22231370/d3e42487-7603-44b7-98a8-37958a7c6d81)
I've verified that when using the "live" credentials that it works as expected.

**Screenshots**
![image](https://github.com/supabase/cli/assets/22231370/6f5b9d86-8148-4a61-881c-dc1ab23974c3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (however this issue persists across browsers)
 - Version of CLI: 1.77.9
 - Version of supabase-js: 2.26.0
 - Version of Node.js: 20.2.0

**Additional context**
N/A

**Comment by sweatybridge** [comment]
This has been resolved by https://github.com/supabase/cli/pull/473

example usage: https://github.com/supabase/cli/blob/develop/internal/utils/templates/init_config.test.toml#L144

**Comment by rlirli** [comment]
The example usage link @sweatybridge posted is dead. See mentioned change in commit history [here](https://github.com/supabase/cli/commit/a7712ca6cb1d674871197baa60ea74c4fa7881cd#diff-315c0e4898fa48b5e5394e5a8d8d65437eac539e6b363a7660c157055a166fa9). 

The config.toml addition he highlights is the addition of the `url` parameter.

```diff
[auth.external.azure]
enabled = true
client_id = "env(SUPABASE_AZURE_CLIENT_ID)"
secret = "env(SUPABASE_AZURE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
+ url = "https://login.microsoftonline.com/<tenant-id>"
```
