### ISSUE TITLE
supabase db reset breaks openapi spec

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#133]
# Bug report

## Describe the bug

My OpenAPI spec at `http://localhost:54321/rest/v1/?apikey=your-anon-key` looks fine after running `supabase start`. But if I run `supabase db reset` then `definitions` in my types are wrong (and maybe more).

## Expected behavior

I'd expect the generated types to be the same if no changes were made to migrations.

## Screenshots

<img width="489" alt="Screenshot 2022-01-05 at 20 33 18" src="https://user-images.githubusercontent.com/16841792/148277943-d6b4c3e6-ea39-42c8-ba00-e79c92428329.png">

<img width="318" alt="Screenshot 2022-01-05 at 20 32 24" src="https://user-images.githubusercontent.com/16841792/148277961-bb42603c-294a-4aef-bb39-5cf3bb5a5f0b.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

This is pretty bad for DX - e.g. I have a reset pipeline that first resets the DB and then [regenerate types based on the openapi spec](https://supabase.com/docs/reference/javascript/generating-types#generate-database-types-from-openapi-specification).

**Comment by steinroe** [comment]
Same problem here! I have to manually restart the rest container for it to reload the schema. It seems like reloading the schema is possible. Would be great to add it to the CLI: https://postgrest.org/en/latest/schema_cache.html
