### ISSUE TITLE
supabase functions serve: Import maps fail to resolve inside of 'functions' directory

### ISSUE THREAD

**Issue by ChuckJonas** [supabase/cli#1338]
# Issue

It seems like import maps are failing in multiple ways:

1. When the mapped directory is INSIDE the function folder, the import map does not properly resolve in the docker instance
2. When the import is outside of the `supabase` folder, it seems like a private module is created? But this causes the `Duplicate mount point` issue
3. Behavior of import maps seems to be different if `--import-maps` flag vs using the defaults

Note: I haven't had a chance to test any of this with deploy, but I assume these issues will carry over in one way or another...

# Reproduction

(this was previously posted to #1093, but decided it deserves a new, open issue)

This is failing in my setup:

**Project Structure**
```
root
   - common
   - react-app
   - supabase
   - functions
      - _core
         - supabaseClient.ts
      - chat
         - index.ts
      - import_map.json
   - package.json
```

**supabase/functions/chat/index.ts**
```
import { corsHeaders } from "core/supabaseClient.ts";
import { fnSharedWithReact } from "common/template";
```

### In "supabase_edge_runtime" Docker container

**home/deno**

```
home/deno
  - fallback_import_map.json
  - main
  - functions
     - _core
        - supabaseClient.ts
     - chat
        - index.ts
     - import_map.json
  - modules
      - 4b0ed4fd36b0064d333d0ebb53b49ba5d84e9b130af0ab0c15f9924364d718c6
```

**fallback_import_map.json**
```json
{
    "imports": {
        "@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2",
        "common/": "/home/deno/modules/4b0ed4fd36b0064d333d0ebb53b49ba5d84e9b130af0ab0c15f9924364d718c6/",
        "core/": "./_core/"
    },
    "scopes": {}
}
```

The deno LSP (vscode) is happy with this configuration, but when I try to invoke the `functions/chat` function, I get this error:

```
Failed to load module: "file:///home/deno/_core/supabaseClient.ts" - No such file or directory (os error 2)
```

It seems like the`fallback_import_map.json` that gets setup in the "supabase_edge_runtime" container is referencing the wrong path:  

**`"core/": "./_core/"` should be `"core/": "./functions/_core/"`**

Also, when I try to run it with the `--import-map` flag, I get the `Duplicate mount point` error as above:

```
supabase functions serve --env-file .env --no-verify-jwt --import-map supabase/functions/import_map.json

-> Error response from daemon: Duplicate mount point: /home/deno/modules/4b0ed4fd36b0064d333d0ebb53b49ba5d84e9b130af0ab0c15f9924364d718c6
```

### Update

If I update my import map to: 
```
    "core/": "./functions/_core/",
```

Then it works (as suspected), but this breaks the imports in my local deno LSP... Also, it goes against what was said in #1093: 

> paths in import_map are relative to supabase/functions directory

So... I don't really understand what's going on.

My workaround was to move my import map OUTSIDE of `functions` (`./supabase/import-map.json`), and now vscode and supabase serve are at least consistent.  However, when I do this, it doesn't even attempt to generate the module for `common` anymore.

**Comment by idudinov** [comment]
Hi! Currently I abandoned using import maps (aka path aliases) within `functions` folder and moved all my client-server re-usable code outside `supabase` folder, and it works perfectly both in local and deployed versions.

However, since using relative paths is evil, I'm also looking for a solution for this issue to be able to use backend-only aliases for functions.

I suppose it could be resolved by keeping the same folders structure as in the project folder, I mean avoid moving `import_map.json` from `supabase/functions` to `supabase` level and mount `/supabase/functions` (instead of just `functions`) without any extra stuff like migrations etc., so in such case relative mappings in `import_map.json` shouldn't break I think. (or maybe re-map them by adding `./functions` prefix?)

**Comment by rasphlat** [comment]
In my case this issue occurs only on Windows, on MacOS is working fine

**Comment by Matx00** [comment]
@idudinov Hi, could you provide an example of how you structured the file? I tried what you said but still getting errors.
Thank you!

**Comment by idudinov** [comment]
@Matx00 no problem, here's my setup.

```javascript
// supabase/functions/import_map.json

{
    "imports": {
        // here listed all packages that are used in "common"
        "yup": "https://esm.sh/yup@1.2.0",

        // the "common" folder is in the root dir
        "common/": "../../src/common/"
    }
}
```

Now I can reference my models from `common` in Deno files:

```typescript
import { UserProfile } from 'common/types/models/index.ts';
```

However I still use relative paths for my shared code within `functions`:
```typescript
import '../_shared/utils/bigint.ts';
```

Hopefully this helps, but don't hesitate to ask any questions if any.

**Comment by ChuckJonas** [comment]
@laktek based on the comments here and additional research in my own project, I think the scope of this issue can be defined using the following reproduction steps.

### Reproduction Steps

1. Create a new supabase project
2. create a new file `supabase/functions/_shared/foo.ts` with the following:
```ts
export const foo = 'bar'
```
3. create a file `supabase/functions/import_map.json` with the following:
```json
    "shared/": "./_shared/"
```
4. create a new supabase function with the following:
```ts
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { foo } from 'shared/foo.ts'; 

console.log("Hello from Functions!")

serve(async (req) => {
  console.log(foo);
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  return new Response(
    JSON.stringify(data),
    { headers: { "Content-Type": "application/json" } },
  )
})
```
5. run the `function:serve` locally and curl the created function.  You should see an error similar to this one:

```
Failed to load module: "file:///home/deno/_shared/foo.ts" - No such file or directory (os error 2)
An error has occured
InvalidWorkerCreation: worker boot error
    at async Function.create (ext:sb_user_workers/user_workers.js:124:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:110:20)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerCreation"
}
```

### Expected Result

The module should be resolving to `file:///home/deno/functions/_shared/foo.ts` 

### Workaround

Move `supabase/functions/_shared` to `supabase/_shared` and update `import_map.json`.

### Other Notes

The fix might be to update the [bindImportMap function](https://github.com/supabase/cli/blob/main/internal/functions/serve/serve.go#L255C6-L255C19) to detect imports inside of the `functions` directory (`./`) and properly rewrite these paths to `./functions`.

**Comment by evelant** [comment]
@sweatybridge have you had a chance to look at this? It seems to boil down to the cli mounting the import map in the container at `/home/deno` when it should be in `/home/deno/functions` so that relative paths remain correct since the default placement of import_map.json is `supabase/functions` in a project.

**Comment by inorganik** [comment]
I was struggling with trying to get import_map.json to work, only to discover that since v1.30, Deno wants you to put import aliases in the imports object of deno.json. It worked for me.

Since version 1.30, the deno.json configuration file acts as an [import map](https://docs.deno.com/runtime/manual/basics/import_maps) for resolving bare specifiers.

See https://docs.deno.com/runtime/manual/getting_started/configuration_file#imports-and-scopes

**Comment by sweatybridge** [comment]
I finally managed to look into this more. I had to use absolute path when mounting import map inside the container.

Feel free to verify this fix with `npx supabase@beta functions serve`

**Comment by leoneparise** [comment]
The issue persists in beta. I found that the `import_map.json` only works correctly when the file is placed inside the `supabase` directory and not within the `functions` subdirectory. Here’s the content of my `import_map.json`:

```json
{
  "imports": {
    "chai/": "npm:/chai@5.1.0/",
    "drizzle-orm": "npm:drizzle-orm@0.30.7",
    "drizzle-orm/": "npm:/drizzle-orm@0.30.7/",      
    "postgres": "npm:postgres@3.4.3",
    "date-fns": "npm:date-fns@3.6.0",
    "date-fns-tz": "npm:date-fns-tz@3.1.3",
    "langchain": "npm:langchain@0.1.33",
    "supabase-js": "npm:@supabase/supabase-js@2.42.5",
    "delay": "https://deno.land/x/delay@v0.2.0/mod.ts",
    "std/": "https://deno.land/std@0.152.0/",
    "oak/": "https://deno.land/x/oak@v11.1.0/",    
    "validasaur/": "https://deno.land/x/validasaur@v0.15.0/",
    "@utils/": "./functions/_utils/",
    "@repositories/": "./functions/_repositories/",
    "@shared/": "./functions/_shared/",
    "@tests/": "./functions/tests/"
  }
}
```

**Comment by stefan-girlich** [comment]
Confirmed that this is also broken in the release v1.167.4
@sweatybridge Could you please re-open this issue?

**Comment by stefan-girlich** [comment]
# Observations using Supabase v1.168.8

### `import_map.json`
(removed `functions/` when placed in `functions/`)
{
  "imports": {
    "supabase-js": "https://esm.sh/@supabase/supabase-js@2.43.4",
    "supabase-types": "./functions/_shared/@types/supabase.ts"
  },
  "scopes": {}
}


### using `supabase/functions/import_map.json`
```
failed to load 'file:///home/deno/_shared/@types/supabase.ts': Module not found "file:///home/deno/_shared/@types/supabase.ts".
An error has occured
InvalidWorkerCreation: worker boot error failed to load 'file:///home/deno/_shared/@types/supabase.ts': Module not found "file:///home/deno/_shared/@types/supabase.ts".
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:155:15)
    at async Object.handler (file:///home/deno/main/index.ts:147:22)
    at async respond (ext:sb_core_main_js/js/http.js:162:14) {
  name: "InvalidWorkerCreation"
}
```

### using `supabase/import_map.json`
```
Relative import path "supabase" not prefixed with / or ./ or ../ and not in import map from "file:///home/deno/functions/on-user-create/index.ts"
An error has occured
InvalidWorkerCreation: worker boot error Relative import path "supabase" not prefixed with / or ./ or ../ and not in import map from "file:///home/deno/functions/on-user-create/index.ts"
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:155:15)
    at async Object.handler (file:///home/deno/main/index.ts:147:22)
    at async respond (ext:sb_core_main_js/js/http.js:162:14) {
  name: "InvalidWorkerCreation"
} 
```

**Comment by sweatybridge** [comment]
Sorry I just double checked everything and it is working as intended. Relative paths in `import_map.json` should be based on where your import map is located. For eg. to import a file `supabase/functions/_shared/types.ts`

If your import map is located at `supabase/functions/import_map.json`, then it should read

```json
{
  "imports": {
    "supabase-types": "./_shared/types.ts"
  },
}
```

Otherwise, if it is located at `supabase/import_map.json`, then it should read

```json
{
  "imports": {
    "supabase-types": "./functions/_shared/types.ts"
  },
}
```

**Comment by sweatybridge** [comment]
@stefan-girlich which OS are you using?

**Comment by AndryHTC** [comment]
I'm noting here that the Supabase functions appear to search for "import_map.json" within the "functions" directory. The newly recommended method of defining import maps in the "deno.json" file does not seem to be working.

**Comment by mattrigg9** [comment]
> I'm noting here that the Supabase functions appear to search for "import_map.json" within the "functions" directory. The newly recommended method of defining import maps in the "deno.json" file does not seem to be working.

I see the same behavior - renaming deno.json to import_map.json when in the functions directory appears to fix resolution issues.

**Comment by Ge6ben** [comment]
The issue happens when running:

`deno cache --reload index.ts`

This command causes the error.

To fix it, please reinstall Deno completely and install it again without running the cache command.
In other words, after reinstalling Deno, do not run:

`deno cache --reload index.ts`
