### ISSUE TITLE
New version of CLI fails to apply migrations with error: must be member of role "supabase_admin"

### ISSUE THREAD

**Issue by ozozozd** [supabase/cli#1349]
**Describe the bug**
Supabase won't start locally with new version of CLI and Docker images.

We've developed our app with the older CLI (1.29.3). Now a new teammate is blocked from setting up their local environment because the new CLI (1.82.2) and the accompanying images fail to apply our migrations and start the local dev setup.

We are able to reproduce the issue and confirm that 1.29.3 works fine and 1.82.2 fails by installing the CLI as a dev dependency.

**To Reproduce**
1. supabase start

**Expected behavior**
Applying the existing migrations and starting the local environment.

**Screenshots**
Attached.
![Screenshot 2023-08-01 at 5 49 35 PM](https://github.com/supabase/cli/assets/1986349/16f0537c-2a4b-4428-9347-3e4518ed1053)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Version of CLI: v1.82.2

As far as I can find, there are is no documentation for how to migrate old migrations to work with the new CLI.

**Comment by sweatybridge** [comment]
Hi @ozozozd, we made a [security patch](https://github.com/supabase/supabase/discussions/9314) to hosted projects so that all tables are owned by postgres role instead of supabase_admin. You `_remote_commit.sql` file doesn't seem to have the latest platform changes.

You can try to manually edit `_remote_commit.sql` file to change any alter table statements that use supabase_admin to `OWNER TO 'postgres'` instead.

If that fails, you may also drop `supabase_migrations.schema_migrations` table on your hosted project, remove all files in `supabase/migrations`, then run `supabase db remote commit` again. This will reset your migration history to the latest snapshot.

**Comment by ozozozd** [comment]
Thank you @sweatybridge. Is there any downside to dropping the `supabase_migrations.schema_migrations` and resetting the migration history?

**Comment by sweatybridge** [comment]
Feel free to reopen if you are still running into issues.

**Comment by jeremyisatrecharm** [comment]
> You can try to manually edit `_remote_commit.sql` file to change any alter table statements that use supabase_admin to `OWNER TO 'postgres'` instead. Or simply comment out those alter owner statements since the default owner is postgres.

This solved my issue, adding some text here to help with search since OP provided a screenshot:
```
ERROR: must be member of role "supabase_admin" (SQLSTATE 42501)
At statement 19: ALTER TABLE "public"."accounts" OWNER TO "supabase_admin"
```

**Comment by miguelespinoza** [comment]
had the same issue and decided to follow the following steps:
* drop supabase_migrations.schema_migrations table
* remove all files in supabase/migrations
* then run supabase db remote commit again

this borked my Golang services, luckily it's on staging, so I'm not freaking out. I suspect it changed the roles for my user against these tables. This is the error I get:

```
ERROR: relation "table" does not exist (SQLSTATE 42P01)
```

I've tried:
```
ALTER TABLE public.table OWNER TO "postgres";
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table TO "postgres";
```

but it intermittently fixes the issue, processes one table query, then eventually fails with the next. It's a big whac-a-mole game. Idk, if it has to do with a legacy configuration where previously my db had granted permissions to supabase_admin. I see that was discontinued.

@sweatybridge, any thoughts to remedy this issue?

**Comment by miguelespinoza** [comment]
If anyone encounters the issue I received. This did the trick:
1. execute `SELECT pg_catalog.set_config('search_path', 'public, extensions', true);`
2. restart your db, not ideal, but it was staging, so was fine having down time

must be some cached db connection that was causing the issue.

**Comment by nicetomytyuk** [comment]
Hi there, I have a self-hosted solution where I started to develop my database, I'm migrating the development on my local machien with supabase cli.

What I did is to run: `supabase db pull --db-url="my_connection_string"` but once I try to up the migration with: "supabase migration up" I get:

```Applying migration 20250311110528_remote_schema.sql...
ERROR: must be member of role "supabase_admin" (SQLSTATE 42501)
At statement 37:
ALTER TYPE "public"."payment_status" OWNER TO "supabase_admin"
Try rerunning the command with --debug to troubleshoot the error.```

**Comment by luishugoooo** [comment]
> Hi there, I have a self-hosted solution where I started to develop my database, I'm migrating the development on my local machien with supabase cli.
> 
> What I did is to run: `supabase db pull --db-url="my_connection_string"` but once I try to up the migration with: "supabase migration up" I get:
> 
> ```
> ERROR: must be member of role "supabase_admin" (SQLSTATE 42501)
> At statement 37:
> ALTER TYPE "public"."payment_status" OWNER TO "supabase_admin"
> Try rerunning the command with --debug to troubleshoot the error.```
> ```

Same issue
