### ISSUE TITLE
Run production project locally

### ISSUE THREAD

**Issue by reveurguy** [supabase/cli#1354]
I have a project on supabase that is production mode.
How can i ran that project locally through CLI ?

Because whenever i want to check something, I can't login to the website. In local development mode also it redirects to the deployed website as that is set in the project auth url.
I have added localhost as well in additional urls but still doesnt work

**Comment by sweatybridge** [comment]
After running `supabase start`, your local dashboard is available at http://localhost:54323

You may also refer to our [local dev guide](https://supabase.com/docs/guides/cli/local-development) for setting up your local development environment to mirror production.
