### ISSUE TITLE
API Port doesn't included in "Inbucket" email confirmation mails

### ISSUE THREAD

**Issue by TugayYaldiz** [supabase/cli#1355]
**Describe the bug**
When working with 

```
[auth.email]
enable_confirmations = true
```

on local confirmation mail sent to [Inbucket](http://localhost:54324/). In there the port is missing
<img width="1121" alt="image" src="https://github.com/supabase/cli/assets/22748758/6c8f9cee-92e8-4484-86b5-fa610fa6402d">

When we go there "The site can’t be reached" error appears.

When I add "port" manually, it works as intended

Wrong:  `http://localhost/auth/v1/verify?token=.....`
Correct:  `http://localhost`**`:54321`**`/auth/v1/verify?token=......`

I couldn't find anything to change this in `config.toml`

My [config.toml](https://github.com/supabase/cli/files/12270362/config.txt)

**To Reproduce**
1. Create a clean local Supabase instance from scratch
2. Try to confirm email
3. Check Inbucket

**Expected behavior**
Port must be added by default.

**Screenshots**
```TypeScript
  const supabase = createClientComponentClient<Database>();

  const handleSignUp = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (loading) {
      return;
    }

    await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${location.origin}/api/auth/callback`,
      },
    });

    setView('check-email');
  };
```

<img width="1332" alt="image" src="https://github.com/supabase/cli/assets/22748758/19160f8f-0955-4667-b74f-f12f1044370f">

**Desktop (please complete the following information):**
 - OS: [macOS Ventura Version 13.3.1 (a)]
 - Browser [chrome]
 - Version of CLI [v1.82.6]
 - Version of supabase-js [v2.31.0]
 - Version of @supabase/auth-helpers-nextjs [v0.7.4]
 - Version of Node.js [v18.17.0]

**Comment by silentworks** [comment]
This has been reported already and has been fixed. The next release of the CLI will include the fix. 

https://github.com/supabase/supabase/issues/16100#issuecomment-1663772108
