### ISSUE TITLE
Can't reset database locally

### ISSUE THREAD

**Issue by bpbastos** [supabase/cli#1363]
**Describe the bug**
I'm unable to reset the local database. I'm currently working on a project to migrate a legacy Yii2 system to Supabase. However, every time I attempt to execute 'npx supabase db reset' with the intention of running migrations and seeding the database, the command returns an error: 'database is not healthy.' As a result, neither the migrations nor the database seeding process is successful.

**To Reproduce**
1. Create a new migration/seed
2. Try to run npx supabase db reset

**Expected behavior**
Run the migrations and database seed

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version of CLI 1.83.7/1.84.0
 - Version of Node.js v18.16.1

**Comment by sweatybridge** [comment]
Could you try to restart the local development stack from a clean state? You can use the following commands

```bash
npx supabase stop --no-backup
npx supabase start
```

**Comment by bpbastos** [comment]
> ```shell
> npx supabase start
> ```
Doing as you suggested worked; the migrations and seeds were executed. I tried running 'npx supabase db reset' again to test, but it still returns 'database is not healthy'.

**Comment by bpbastos** [comment]
> Could you try to restart the local development stack from a clean state? You can use the following commands
> 
> ```shell
> npx supabase stop --no-backup
> npx supabase start
> ```
Doing as you suggested worked; the migrations and seeds were executed. I tried running 'npx supabase db reset' again to test, but it still returns 'database is not healthy'.

**Comment by sweatybridge** [comment]
I believe this is fixed in the latest beta release, ie. `npx supabase@beta db reset`. Feel free to reopen if you are still experiencing this issue.

**Comment by vicnaum** [comment]
Having similar issue on MacOS CLI. Was working fine for several days. Then db reset doesn't do anything - all stays the same. --no-backup didn't help either
