### ISSUE TITLE
Disable unused containers in config to save CPU

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#1366]
### Is your feature request related to a problem? Please describe.
Supabase containers are idling at 25% CPU in my system.

### Describe the solution you'd like
`config.toml` option to disable containers that aren't necessary. In my case I don't need functions, realtime and image proxy

### Describe alternatives you've considered
Manually stopping the unnecessary containers

### Additional context
`docker stats` recording:

https://github.com/supabase/cli/assets/11315492/b677d16f-98cc-40d3-be1d-0320d5a83c35

**Comment by soedirgo** [comment]
You can use the `-x` flag to exclude some containers from starting: https://supabase.com/docs/reference/cli/supabase-start

**Comment by probablykasper** [comment]
That's a great way for now, thanks for the tip!

Having an option in `config.toml` would be really nice
