### ISSUE TITLE
[BUG] Attempting to look at local Postgres logs causes Studio to crash

### ISSUE THREAD

**Issue by mrmikardo** [supabase/cli#1377]
**Describe the bug**
Attempting to view one of the Postgres log entries in the local Supabase Studio causes the client application to crash;

<img width="1512" alt="Screenshot_2023-08-14_at_09 43 43" src="https://github.com/supabase/cli/assets/10819829/7c33d0f4-ff4a-4b4a-a60e-81933b99dae8">

**To Reproduce**
1. Run the local Supabase instance.
2. Navigate to the Studio.
3. Click on the logs tab, then click Postgres.
4. Click on an individual log message.
5. See error.

**Expected behavior**
I'd expect to see a detail view of the log.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version of CLI: `1.83.7`

**Additional context**
Originally reported in Discord [here](https://discord.com/channels/839993398554656828/1140345066670538892/1140345066670538892).

**Comment by sweatybridge** [comment]
This has been fixed in updated studio.
