### ISSUE TITLE
2.9.2 introduced a bug

### ISSUE THREAD

**Issue by digitalbase** [supabase/cli#1384]
# Bug report

Regression caused by `required:"true"` 
https://github.com/supabase/gotrue/commit/4745451a931c2be5d36c07b37bd0eb3ab7780587#diff-4c28cb40881781a1067b3b3681c43f805dab629f31f3c7614b0f781ffa096505L80

Everyone trying supabase from scratch with SupaBase run into this error

Thread https://discord.com/channels/839993398554656828/1141398284351586394

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

All commands are complaining about `API_EXTERNAL_URL` missing

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
 
```
mkdir test
cd test
supabase login
supabase init
supabase link --project-ref XX
supabase start
supabase db reset
```

error

 ```
2023/08/16 17:46:25 Sent Header: Host [api.moby.localhost]
2023/08/16 17:46:25 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/08/16 17:46:25 Send Done
2023/08/16 17:46:25 Recv First Byte
{"level":"fatal","msg":"Failed to load configuration: required key API_EXTERNAL_URL missing value","time":"2023-08-16T15:46:25Z"}
2023/08/16 17:46:25 Sent Header: Host [api.moby.localhost]
2023/08/16 17:46:25 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/08/16 17:46:25 Send Done
2023/08/16 17:46:25 Recv First Byte
```

## System information

- OS: macOS,
- Version of supabase-cli  CLI 1.86.1

**Comment by silentworks** [comment]
I've transferred this as it's a CLI issue rather than a GoTrue issue. The issues is that the `db reset` isn't setting a required environment variable which wasn't required before. Here is where the `API_EXTERNAL_URL` env variable should be set again https://github.com/supabase/cli/blob/main/internal/db/reset/reset.go#L293-L299

**Comment by silentworks** [comment]
For anyone else hitting this error before we get a fix out, look for `supabase/.temp` directory and you should see a `gotrue-version` file. If your `supabase start` is already running you will need to run `supabase stop` first and then edit the `gotrue-version` file and set the version to `2.84.2` for now, then run `supabase start` again and all the other commands should be working again.

**Comment by digitalbase** [comment]
Confirmed as working. Tnx!

**Comment by currymich** [comment]
> For anyone else hitting this error before we get a fix out, look for `supabase/.temp` directory and you should see a `gotrue-version` file. If your `supabase start` is already running you will need to run `supabase stop` first and then edit the `gotrue-version` file and set the version to `2.84.2` for now, then run `supabase start` again and all the other commands should be working again.

This worked, but with v2.82.4 as mentioned in digitalbase's message. Thank you!
