### ISSUE TITLE
Downloading Storage Bucket Contents

### ISSUE THREAD

**Issue by Angus-Moore-Dev** [supabase/cli#1388]
**Is your feature request related to a problem? Please describe.**
I would love if Supabase had the functionality to be able to download contents from the storage buckets. I have a number of projects that require referencing to files in buckets. This works fine if I am storing the URL of the object (for public files), but this creates real problems when fetching relative files from buckets for existing data.

**Describe the solution you'd like**
The ability to download the contents from storage buckets into my local development environment. Maybe as a flag for the `db dump` command?

**Describe alternatives you've considered**
None, since this becomes really problematic when you have nested folders and files to deal with.

**Additional context**
N/A

If you guys are able to add this, that would be fantastic. Might be a problem for users who have sensitive information in their databases, but for those of us storing relative paths for files in the database (because of RLS), it'd be nice to be able to actually have those files locally for when we run our development environment. Thanks :D

**Comment by sweatybridge** [comment]
This is a great idea. We have an internal RFC to add the following commands to sync storage bucket contents between remote and local. The files are expected to be saved to `supabase/storage` directory while entries in `storage.buckets` and `storage.objects` table will probably be pulled as a new migration file in `supabase/migrations`.

- `supabase storage ls`

```bash
$ supabase storage ls my_bucket
test1.csv test2.txt

$ supabase storage ls *.csv
my_bucket/test1.csv
```

- `supabase storage cp`

```bash
$ supabase storage cp ss://my_bucket/test3.png .
Downloaded file: ./my_bucket/test3.png

$ supabase storage cp my_bucket ss://my_bucket
Uploaded file: my_bucket/test1.csv
Uploaded file: my_bucket/test2.txt
Overwritten file: my_bucket/test3.png

$ supabase storage cp my_bucket/test3.png ss://public/
Confirm uploading files from my_bucket to public? [y/N]
Uploaded file: public/test3.png
```

- `supabase storage rm`

```bash
$ supabase storage rm my_bucket/test3.png
Deleted file: my_bucket/test3.png

$ supabase storage rm -r my_bucket
Confirm deleting all files in my_bucket? [y/N]
Deleted file: my_bucket/test1.csv
Deleted file: my_bucket/test2.txt
```

These commands should feel familiar to bash users but we are also open to your feedback if there are use cases not covered here.

**Comment by gruckion** [comment]
Please implement this

**Comment by rdewolff** [comment]
Hey there! 👋 

First off, I wanted to express how much I appreciate the work you all have been doing on this project. It's truly transformative! 🚀

I recently came across this issue about downloading storage bucket contents, and I have to say, I think it's a game-changer. Being able to effectively copy, clone, or move bucket data would be immensely helpful for a number of reasons:

Flexibility: Sometimes, we need to switch between different environments, and having this feature would make the transitions seamless.
Data Recovery: Mistakes happen, and having a reliable way to restore or replicate our bucket data would be a lifesaver in case things go awry.
Testing & Development: For devs like me, being able to mock real-world scenarios in a local dev environment can be invaluable. This would make the development process a lot smoother and more efficient.
In essence, such a feature would offer both peace of mind and an enhancement in our workflow, and I truly believe it'd be a great addition to an already amazing project.

Keep up the fantastic work, and thank you for considering this! 🙌

**Comment by sweatybridge** [comment]
We have released this feature to beta channel. The commands should work for most projects unless you have many objects (max around 100k).

Let me know if you run into any issues.

**Comment by brianGammon** [comment]
Thanks for this @sweatybridge! What about buckets with > 100k objects? Would this be supported later?

I am looking to move an app from Firebase to Subabase. Currently I have a Firebase bucket with about 20GB and ~200k objects all from user uploads (lots of small files). They are organized and secured in folders named with an organization ID.

I'm having a moment of pause realizing that Supabase doesn't give me access to the underlying bucket in the same way Firebase does using GCP. What do folks running Supabase at scale in production do for backup and recovery of their storage?

**Comment by Akash187** [comment]
@brianGammon I think Supabase got you covered. Can you elaborate on some specific scenario that you think is not possible with Supabase?

**Comment by sweatybridge** [comment]
> What about buckets with > 100k objects? Would this be supported later?

I should have clarified earlier that 100k advisory limit only applies to the number of objects copied in 1 invocation of storage command. For larger buckets, you can always run storage cp multiple times to copy files in batches.

> They are organized and secured in folders named with an organization ID.

Since your objects are already grouped in folders by organization ID, you may consider copying org by org. For example, assuming you have downloaded all Firebase objects into a local directory structure named `/tmp/<org_id>`

```bash
# Download from s3 / gcs
gsutil -m cp -r gs://bucket /tmp
```

You can use the following script to upload to Supabase Storage:

```bash
# Upload to Supabase Storage
for path in /tmp/*; do
  org_id=$(basename -- "$path")
  supabase --experimental storage cp -r "$path" "ss:///bucket/$org_id"
done
```

> What do folks running Supabase at scale in production do for backup and recovery of their storage?

I think the long term answer for this is [BYO bucket](https://github.com/supabase/storage-api/issues/27) for replication. What you can do now is to schedule a periodic job to download from Storage using CLI and upload to s3 / gcs using awscli / gsutil. You can then run the script above to restore.

Let me know if you find this solution sufficient. I'm happy to include an extended example in our [backup docs](https://supabase.com/docs/guides/cli/github-action/backups).

**Comment by brianGammon** [comment]
Thank you for the thorough response @sweatybridge, that helps quite a bit. The docs have been excellent from a database standpoint, and this info helps fill the gap on what to do with storage.

**Comment by Robertleoj** [comment]
How do I put the files into the storage in the local supabase instance?

I see that I can copy the files to the local filesystem, but I want them to appear in the locally running supabase.

**Comment by sweatybridge** [comment]
> I see that I can copy the files to the local filesystem, but I want them to appear in the locally running supabase, so I can access them normally with the storage API.

This is not supported by CLI at the moment. You would need to write a script using the storage-js library.

Alternatively if you can file a new issue, I will be happy to look into it.

**Comment by yannickschuchmann** [comment]
> This is a great idea. We have an internal RFC to add the following commands to sync storage bucket contents between remote and local. The files are expected to be saved to `supabase/storage` directory while entries in `storage.buckets` and `storage.objects` table will probably be pulled as a new migration file in `supabase/migrations`.
> 
> * `supabase storage ls`
> 
> $ supabase storage ls my_bucket
> test1.csv test2.txt
> 
> $ supabase storage ls *.csv
> my_bucket/test1.csv
> * `supabase storage cp`
> 
> $ supabase storage cp ss://my_bucket/test3.png .
> Downloaded file: ./my_bucket/test3.png
> 
> $ supabase storage cp my_bucket ss://my_bucket
> Uploaded file: my_bucket/test1.csv
> Uploaded file: my_bucket/test2.txt
> Overwritten file: my_bucket/test3.png
> 
> $ supabase storage cp my_bucket/test3.png ss://public/
> Confirm uploading files from my_bucket to public? [y/N]
> Uploaded file: public/test3.png
> * `supabase storage rm`
> 
> $ supabase storage rm my_bucket/test3.png
> Deleted file: my_bucket/test3.png
> 
> $ supabase storage rm -r my_bucket
> Confirm deleting all files in my_bucket? [y/N]
> Deleted file: my_bucket/test1.csv
> Deleted file: my_bucket/test2.txt
> These commands should feel familiar to bash users but we are also open to your feedback if there are use cases not covered here.

That's cool. Is it possible to use these for branches? 
e.g. I have a persistent branch "staging" and I want to download all files.
