### ISSUE TITLE
Which checksum needs to be verified in postinstall script ?

### ISSUE THREAD

**Issue by code-withAshish** [supabase/cli#1391]
I was going throigh the repo of the cli and i saw this TODO comment, so i thought of contributing to the repo,
https://github.com/supabase/cli/blob/59b71ba3bc473d3f0e07a546cb2bb9e5a5acf1d0/scripts/postinstall.js#L106

but please correct me if i am wrong, diesnt the package manager checks for the integrity checksum automatically after install or is it something else we are trying to acheive?

If you could provide me an insight of the goal , I would love to contribur to the repo

**Comment by sweatybridge** [comment]
Thanks for offering to help!

The package managers will verify checksum of postinstall.js but not the cli binaries downloaded by postinstall script. So this TODO is about adding checksum verification to the actual binaries, which is published in our github releases page https://github.com/supabase/cli/releases/download/v1.86.2/supabase_1.86.2_checksums.txt.

**Comment by code-withAshish** [comment]
Ahh makes sense, I will file a PR for this ASAP.
Thanks for the clarification 😁

**Comment by code-withAshish** [comment]
Hey @sweatybridge,
 I have opened a PR , have a look if you get time #1393 
Thank you
