### ISSUE TITLE
Auth Actions Taking 10+ seconds on windows

### ISSUE THREAD

**Issue by alteredorange** [supabase/cli#14]
# Bug report

## Describe the bug
Sorry, one more issue :)
Not sure if this is local/dev/cli related, or tangentially related to this issue: https://github.com/supabase/supabase/issues/937 
but now that I can log in, the initial login takes 10 to 20 seconds. If I run the login immediately after, it usually goes down to around 15 milliseconds, but then will intermittently go back to 10 to 20 seconds to log in.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create user
2. log in with user 

## Expected behavior

Logins should be consistently under 1 second.

## Screenshots
You can see the times bounce around, between 20 seconds and 15 milliseconds for the initial login, but then calling the session is always fast (I'm assuming because supabase is already initialized?)
![image](https://user-images.githubusercontent.com/2141012/113319117-5b714400-92ce-11eb-896e-a127afbcdc1c.png)

## System information

- OS: Windows 10 running ubuntu and docker desktop with WSL2
- Version of supabase-js: 1.7.7, CLI: 0.3.4
- Version of Node.js: 15.4.0

## Additional context

Here's the node script I'm testing with:
```
import { createClient } from '@supabase/supabase-js'
const SUPABASE_URL = 'http://localhost:8000'
const SUPABASE_ANON_KEY = '---the-key---'
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
import { performance } from "perf_hooks"

const main = async () => {
  var t0 = performance.now()
  const { user, session, error } = await supabase.auth.signIn({
    email: 'hi@gmail.com',
    password: 'superpasswordtighty',
  })
  var t1 = performance.now()
  console.log("Login took " + (t1 - t0) + " milliseconds. (" + ((t1 - t0) / 1000) + "secconds)")

  var t0 = performance.now()
  const session2 = supabase.auth.session()
  var t1 = performance.now()
  console.log("Session took " + (t1 - t0) + " milliseconds. (" + ((t1 - t0) / 1000) + "secconds)")
}
main()
```

**Comment by alteredorange** [comment]
Also, after leaving everything untouched for 20 minutes, I ran the script 10 times, and didn't have any over 15 milliseconds. Then, stopping supabase, and starting it back up again, the first 5 scripts ran at 15 to 20 seconds, then 5 at 15 milliseconds, then 1 at 15 seconds, and then 40 at sub 1 second.  Not sure if the gotrue server or kong is "calibrating" or something when docker first starts up? Not sure where to look, are there logs somewhere to see what takes the 15 second requests so long?

**Comment by soedirgo** [comment]
That's odd, I couldn't reproduce this (M1 MBA, gotrue on qemu).

Perhaps you can check the logs from the containers? Either from the Docker Desktop app or `docker logs supabase-auth`.

**Comment by alteredorange** [comment]
can't see much from the logs, I'm not seeing any errors or anything being thrown.  I also just noticed that nothing is persisted to disk/docker isn't using any volumes to store data, so everything gets trashed on shutdown. Is that by design, or should I open up a bug report?  I would assume most people doing local dev would want to persist changes, but I could be wrong.

```
time="2021-04-01T17:29:36Z" level=info msg="request completed" component=api duration=207645700 method=POST path=/signup referer= remote_addr="172.26.0.2:38286" request_id=0b76bca4-c5cc-44e9-b6ca-70766117444d status=200

time="2021-04-01T17:29:36Z" level=info msg="request started" component=api method=POST path=/token referer= remote_addr="172.26.0.2:38294" request_id=666a0ae6-c971-409d-8e67-f9bd6b21f3cf

time="2021-04-01T17:29:36Z" level=info msg=Login action=login instance_id=00000000-0000-0000-0000-000000000000 login_method=password metering=true user_id=c43723f0-4f3e-49dc-ad35-f05e78fddbb4

time="2021-04-01T17:29:36Z" level=info msg="request completed" component=api duration=201652600 method=POST path=/token referer= remote_addr="172.26.0.2:38294" request_id=666a0ae6-c971-409d-8e67-f9bd6b21f3cf status=200

time="2021-04-01T17:30:54Z" level=info msg="request started" component=api method=POST path=/signup referer= remote_addr="172.26.0.2:38302" request_id=418c6dc2-b233-4df9-b2ee-775fc675afc1

time="2021-04-01T17:30:54Z" level=info msg="400: A user with this email address has already been registered" component=api error="400: A user with this email address has already been registered" method=POST path=/signup referer= remote_addr="172.26.0.2:38302" request_id=418c6dc2-b233-4df9-b2ee-775fc675afc1

time="2021-04-01T17:30:54Z" level=info msg="request completed" component=api duration=4907500 method=POST path=/signup referer= remote_addr="172.26.0.2:38302" request_id=418c6dc2-b233-4df9-b2ee-775fc675afc1 status=400

time="2021-04-01T17:30:54Z" level=info msg="request started" component=api method=POST path=/token referer= remote_addr="172.26.0.2:38310" request_id=4a5b9b5f-09f1-4555-abc5-6db430078661

time="2021-04-01T17:30:55Z" level=info msg=Login action=login instance_id=00000000-0000-0000-0000-000000000000 login_method=password metering=true user_id=c43723f0-4f3e-49dc-ad35-f05e78fddbb4

time="2021-04-01T17:30:55Z" level=info msg="request completed" component=api duration=99468000 method=POST path=/token referer= remote_addr="172.26.0.2:38310" request_id=4a5b9b5f-09f1-4555-abc5-6db430078661 status=200
```

**Comment by alteredorange** [comment]
Regarding the volumes, it does look like supabase does store the data, it's just that `supabase stop` actually deletes the docker containers, instead of just stopping them, hence the data gets deleted. So that probably would be a bug?

**Comment by kiwicopple** [comment]
> it's just that supabase stop actually deletes the docker containers

We have a bit more context on this one here: https://github.com/supabase/cli/pull/15


>  Not sure if the gotrue server or kong is "calibrating" or something when docker first starts up?

It shouldn't be. I also haven't been able to replicated this using a Mac. I wonder if it's related to WSL somehow? I know networking between the OS and WSL was always a bit funky when I used a Windows machine, although it was WSL1.

**Comment by alteredorange** [comment]
@ kiwicopple Could be! Since this is hard to reproduce, and only appears to happen at startup, I'll close the issue for now, thanks!

**Comment by easy-street** [comment]
@alteredorange @kiwicopple i'm seeing precisely the same behavior on windows 10 pro with both wsl2 and hyper-v docker installations. also unable to reproduce in any mac or native linux environment. steps to repro for me on a clean installation:
- `supabase init`
- `supabase start`
- `GET` to http://localhost:8000/auth/v1/settings with the anon `apikey` header

consistently around 20 seconds with more reasonable response times occasionally

**Comment by kiwicopple** [comment]
that's awesome debugging @easy-street - thanks for helping here. I'll reopen this

**Comment by soedirgo** [comment]
Thanks @easy-street! I added the config to the compose file. @alteredorange feel free to reopen if the issue persists.

**Comment by nopol10** [comment]
I was using the "clone supabase/supabase" option provided in the docs to start a self-hosted supabase and only just realized that the docker-compose.yml and the one in supabase/cli are different which was why I was encountering this issue even though it's resolved, I guess this should be used as the official way as it's the most updated?

**Comment by soedirgo** [comment]
@nopol10 you're right, unfortunately they're often out of sync, and the one here tends to be more up-to-date (not intended to be this way though, would appreciate a PR on supabase/supabase 🙏). But FYI we're currently reworking the CLI ([WIP](https://github.com/soedirgo/cli)) so that `eject` has some added convenience with an existing setup (e.g. reusing your config).

**Comment by nopol10** [comment]
Ah I see, nice to hear about the CLI updates. I'll see if I can help
