### ISSUE TITLE
Config option to disable `edge-runtime`

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#1414]
### Is your feature request related to a problem? Please describe.
Supabase is using a lot of CPU at idle. Using the `supabase start` `-x` option to exclude containers is easy to forget and has to be done manually by each team member.

### Describe the solution you'd like
`config.toml` option to disable `imgproxy` (while keeping `storage` enabled), `realtime` and `edge-runtime`

### Additional context
Related:
- https://github.com/supabase/cli/issues/1366

**Comment by sweatybridge** [comment]
Changing the title because disabling realtime is now supported.

**Comment by bnjmnt4n** [comment]
Any chance to update this for the other two services?
