### ISSUE TITLE
Get the description of the column on the generated types

### ISSUE THREAD

**Issue by juliomuhlbauer** [supabase/cli#1417]
**Is your feature request related to a problem? Please describe.**
No. But I want to grab the description automatically.

**Describe the solution you'd like**
Get the description of the column on the generated types. Maybe in js comments? Also would help on vscode hints.

**Describe alternatives you've considered**
Copy and paste manually.

**Additional context**
My use case is populating my db with formatted data with gpt and a description of the column helps a lot.

**Comment by soedirgo** [comment]
Thanks! Tracking this on https://github.com/supabase/cli/issues/412
