### ISSUE TITLE
Error: Error response from daemon: No such image: supabase/gotrue:v2.2.12

### ISSUE THREAD

**Issue by matt-paul** [supabase/cli#142]
# Bug report

## Describe the bug

Error when following the 'tour' in the repo in order to try out handling migrations with the CLI

## To Reproduce

Follow 'tour' instructions [here](https://github.com/supabase/cli/tree/main/examples/tour)

After applying step 'supabase db remote commit', eventually recieve error:

`Error: Error response from daemon: No such image: supabase/gotrue:v2.2.12`

## Expected behavior

Command succeeds.

## System information

- OS: macOS 12.1
- Browser (if applies) n/a
- Version of supabase-js: 0.15.16%    
- Version of Node.js: v14.18.1

**Comment by soedirgo** [comment]
Thanks Matt! Found out what the issue was - does updating the CLI version fix it for you?

**Comment by matt-paul** [comment]
Yes thats worked now, thanks

**Comment by fairpoolio** [comment]
In my case, the error was because Docker ran out of disk space.

Solution: increase the Docker disk space.
