### ISSUE TITLE
custom triggers get run when resetting local db with seeds, causing duplicate key issues

### ISSUE THREAD

**Issue by njbmartin** [supabase/cli#1420]
**Describe the bug**
I have created some custom triggers. One of these triggers creates a user in `public.users` which uses `auth.id` as a primary key (as described here: https://supabase.com/docs/guides/auth/managing-user-data#using-triggers).

When I reset the db using the seed data from production, it throws an error `ERROR: duplicate key value violates unique constraint "users_pkey" (SQLSTATE 23505)`.

I had to disable the triggers in a migration file so that these weren't being fired.

```SQL
ALTER TABLE "auth"."users" DISABLE TRIGGER "on_auth_user_created";
ALTER TABLE "public"."profiles" DISABLE TRIGGER "on_profile_created";
```

By disabling these triggers, I was able to successfully run `supabase start` and `supabase db reset`.

Is there an automated way to disable triggers until the seed data has been populated?

**To Reproduce**

As described above.

**Expected behavior**
Custom triggers are not fired when populating db with seed.

**Desktop (please complete the following information):**
 - OS: Windows (via VS Code Dev Container)
 - Version of CLI: 1.87.4 / 1.91.1 / 1.69.0
 - Version of Node.js: 18.16.0

**Additional context**

Only taken me 3 hours to work out why this was happening. `--debug` did not provide a hint that a trigger was being fired.

**Comment by sweatybridge** [comment]
One way is to add the following line to the start of `supabase/seed.sql`. Seeding as the replica role disables all triggers.

```sql
SET session_replication_role = replica;
```

**Comment by ahmadawais** [comment]
Here's a Node.js script to automate that. 

```js
const fs = require('fs');
const path = require('path');

// Define the path to the seed.sql file
const filePath = path.join(__dirname, '..', 'supabase', 'seed.sql');

// Read the content of the seed.sql file
fs.readFile(filePath, 'utf8', (err, data) => {
	if (err) {
		console.error('Error reading file:', err);
		return;
	}

	// Prepare the lines to be added
	const lineToAddAtStart = 'SET session_replication_role = replica;\n\n';
	const lineToAddAtEnd = '\n\nSET session_replication_role = DEFAULT;';

	// Modify the file content
	const modifiedContent = lineToAddAtStart + data + lineToAddAtEnd;

	// Write the modified content back to the seed.sql file
	fs.writeFile(filePath, modifiedContent, 'utf8', err => {
		if (err) {
			console.error('Error writing file:', err);
			return;
		}
		console.log('File has been modified successfully');
	});
});
```

**Comment by kevin-eberhardt** [comment]
Sorry to open the issue again but is it planned to integrate a parameter in the command line or similar for supabase so that this is automatically integrated into the seed.sql? Would help some with local development I think!
Looking forward to hearing from you

**Comment by kevin-eberhardt** [comment]
Sorry to open the issue again but is it planned to integrate a parameter in the command line or similar for supabase so that this is automatically integrated into the seed.sql? Would help some with local development I think!
Looking forward to hearing from you

**Comment by DhenPadilla** [comment]
@kevin-eberhardt I think in the latest `supabase-cli` version, it automatically adds this in the `seed.sql`.

They also recently added an `--exclude` parameter, which allows you to exclude certain tables that have triggers involved if you want to do it that way!

See the following:
https://github.com/supabase/cli/issues/1772
