### ISSUE TITLE
Import map not found 'file:///home/aibek/upfront/checkout/supabase/functions/import_map.json' (local directory)

### ISSUE THREAD

**Issue by ahoskins** [supabase/cli#1426]
**Describe the bug**
The deployed Supabase function is giving the error:

`import map not found 'file:///home/aibek/upfront/checkout/supabase/functions/import_map.json'`

This directory is a local directory of someone who deployed this edge function. The confusing thing is, we have never defined an `import_map` or have never manually deployed using the `--import_map` flag, so I'm not sure why it's looking for an import map.

**Expected behavior**
It's expected that the edge function would not be looking for an import map, since we never added this file.

**Screenshots**
<img width="1450" alt="image" src="https://github.com/supabase/cli/assets/1527504/bcf20a60-f038-4433-9cc2-beac5f88df54">

**Comment by ahoskins** [comment]
@sweatybridge is this fixed by the above PR that was merged? This has been a real source of pain for us breaking production edge functions just by someone else deploying them. If we all update the newest version of CLI, will this issue be resolved? Thanks.

**Comment by sweatybridge** [comment]
> is this fixed by the above PR that was merged?

No, I linked to this issue by mistake. I will take a closer look at this first thing tmr. Sorry for the inconvenience.

**Comment by ahoskins** [comment]
@sweatybridge Okay, good to hear. This caused a production outage and is seriously putting doubt into using edge functions at our company. This keeps happening every time a different person deploys the same functions.

**Comment by sweatybridge** [comment]
Could you send a support ticket through the dashboard? I tried deploying functions locally from separate directories and it works without the `import_map` error. I will would need more information to help debug further.

**Comment by ahoskins** [comment]
@sweatybridge I've created an issue through our dashboard, thanks for the support on this

**Comment by Mugumo** [comment]
Is there any progress on this issue?
When I deploy a function from my windows environment it works fine, but then when others deploy again from macOS or ubuntu, our supabase edge functions throw a similar error:

`Import map not found 'file:///C:/Users/ZacharyGakuo/Documents/fin_conn/midware/repos/supabase/supabase/functions/import_map.json'`

I am deploying using supabase CLI from a windows machine my colleagues are deploying from ubuntu and macOS:

`supabase functions deploy my-function --project-ref some_project_ref`

**Comment by sweatybridge** [comment]
@Mugumo could you check if you are using the latest CLI version on both windows and Mac? We found the original problem to caused by version mismatch so it would be good to check on your side too.

**Comment by Mugumo** [comment]
> @Mugumo could you check if you are using the latest CLI version on both windows and Mac? We found the original problem to caused by version mismatch so it would be good to check on your side too.

I think everyone is using different versions:

(myself) Windows: supabase 1.64.8,
Ubuntu: supabase 1.58.1,
macOS: 0.38.4,
etc.

Is the recommendation for all of us to update to latest?

**Comment by sweatybridge** [comment]
Yes, we make a stable every 2 weeks and it's recommended to update regularly for the latest patches.

If you are using nodejs, an alternative is to pin the cli to a specific version using `npm i supabase@1.64.8 --save-dev`. This at least ensures that everyone on your team is using the same version.
