### ISSUE TITLE
Supabase CLI ignores --workdir flag for init command

### ISSUE THREAD

**Issue by thesobercoder** [supabase/cli#1431]
**Describe the bug**

The `init` command should respect the `--workdir` flag and create the files in the current directory, i.e. `awesome-project`, but instead it creates a subdirectory called `supabase` which is specifically opposite of what the intention was.

**To Reproduce**

1. Make an empty directory
	```sh
	mkdir awesome-project
	```
2. Change to the newly created directory
	```sh
	cd awesome-project
	```

3. Initialize supabase
	```sh
	supabase init --workdir "."
	```

**Expected behavior**

The Supabase CLI should respect the `--workdir` flag and create the files in the current directory, i.e. `awesome-project`, but instead it creates a subdirectory called `supabase` which is specifically opposite of what the intention was.

**Desktop (please complete the following information):**

 - OS: Windows 10 22H2
 - Version of CLI: 1.88.0

**Comment by sweatybridge** [comment]
This is actually working as intended. The `supabase` subdirectory contains `config.toml` and migration files for setting up local dev environment. We cannot support arbitrary names for this path. The `workdir` flag refers to the [project directory](https://supabase.com/docs/reference/cli/global-flags) which is one level up from the config directory.

**Comment by thesobercoder** [comment]
@sweatybridge So the Supabase subdirectory is something unavoidable?

**Comment by sweatybridge** [comment]
AFAIK, yes because we need a predicable name to locate the config files.

**Comment by thesobercoder** [comment]
@sweatybridge Thanks for the clarification.
