### ISSUE TITLE
Add support for "check" constraints to the "gen types" command

### ISSUE THREAD

**Issue by wstrother** [supabase/cli#1433]
It would be really nice if when using the "gen types typescript" command, the CLI tool could infer where a type is actually a union of literals. Consider the following table:

```sql
create table
  public.state_variables (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    key character varying not null,
    value text null,
    user_id uuid not null,
    type text not null default 'string'::text,
    constraint state_variables_pkey primary key (id),
    constraint state_variables_user_id_fkey foreign key (user_id) references auth.users (id),
    constraint valid_type check (
      (
        type = any (
          array['string'::text, 'boolean'::text, 'number'::text]
        )
      )
    )
  ) tablespace pg_default;
  ```

The result of `supabase gen types typescript` is:

```typescript
// ...
state_variables: {
        Row: {
          // ...
          type: string
         // ...
        }
// ...
```

When `type: "string"|"boolean"|"number"` would be much more useful.

I'm aware this could potentially be opening up a can of worms, but at least in the specific case where the constraint is effectively `check (value in ("literal1", "literal2", ...))` it would be really nice, especially since every time I use the CLI to update type definitions again it will overwrite my manual changes.

**Comment by soedirgo** [comment]
@wstrother you can use [Postgres enums](https://www.postgresql.org/docs/current/datatype-enum.html) for this. Does that not work for your use case?

**Comment by wstrother** [comment]
> @wstrother you can use [Postgres enums](https://www.postgresql.org/docs/current/datatype-enum.html) for this. Does that not work for your use case?

Yes, this will work perfectly, thank you! Sorry I didn't see this response when you posted it. I really appreciate your help!
