### ISSUE TITLE
Unable to "supabase start" - /usr/local/lib/node_modules/pm2/node_modules/nssocket/.npmignore: invalid argument

### ISSUE THREAD

**Issue by louis030195** [supabase/cli#1439]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Receiving

```
/usr/local/lib/node_modules/pm2/node_modules/nssocket/.npmignore: invalid argument
```

Upon running `npx supabase start` in Gitpod.io

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start a gitpod.io instance with default Docker image
2. Run `npx supabase start`
3. See error

## Expected behavior

It runs

## System information

- OS: gitpod.io `gitpod/workspace-full:latest`

```bash
node -v
v16.19.0

docker -v
Docker version 20.10.17, build 100c701
```

**Comment by sweatybridge** [comment]
We should have resolved this issue since CLI 1.50.8

https://github.com/supabase/cli/issues/268#issuecomment-1511355569

Running `npx supabase start` in GitPod is fully supported.
