### ISSUE TITLE
db reset leaving the database unhealthy

### ISSUE THREAD

**Issue by TacoV** [supabase/cli#1447]
**Describe the bug**
The command `supabase db reset` destroys the local database.

**To Reproduce**
I have 1 migration, both in the production log and in the local folder, automatically generated by supabase CLI. If I now fully reset the data like below, I have a working database
```` bash
$ npx supabase stop
$ docker volume prune -af
$ npx supabase start
```` 

However, if I then make some changes and want to reset the database, it fails
```` bash
$ npx supabase db reset
Resetting local database...
Restarting containers...
database is not healthy
Try rerunning the command with --debug to troubleshoot the error.
```` 

Now, the database is not healthy, and the local schema no longer exists!

**Expected behavior**
Both commands should result in the same (working) local database. Resetting the db should not result in losing all tables.

**Desktop:**
 - Working from Github Codespace
 - Version of CLI: 1.88.0

**Additional context**
The initial data has been migrated by hand to production, local and production are often out of sync. Full resets like this are often needed. Not sure whether my schema is this exotic, I don't think so, or that CLI is this unstable.

**Comment by sweatybridge** [comment]
This is probably an issue of health check timeout. I've increased it to 30s for you to give a try

```bash
npx supabase@beta db reset
```

**Comment by TacoV** [comment]
So I am somewhat hesitant to choose Y here, as remote in my book would be the production database.

````console
$ npx supabase@beta db reset
Need to install the following packages:
  supabase@1.96.1
Ok to proceed? (y) 
Confirm resetting the remote database? [Y/n] 
````

**Comment by sweatybridge** [comment]
That's a bug introduced by a recent refactoring. I've made a patch here https://github.com/supabase/cli/pull/1464. Please give it another go after it's merged.

**Comment by TacoV** [comment]
Will do!

Just to check - would proceeding actually have wiped the remote prod db? Or is it just a incorrect confirmation?

**Comment by sweatybridge** [comment]
It's an incorrect confirmation. Confirming would not actually wipe the remote database because the `config.Host` is still set to `localhost`.

**Comment by TacoV** [comment]
Now it works like a charm:
````console
$ npx supabase@beta db reset
Need to install the following packages:
  supabase@1.96.2
Ok to proceed? (y) 
Resetting local database...
Restarting containers...
Applying migration 20230901091357_remote_schema.sql...
Seeding data supabase/seed.sql...
Finished supabase db reset on branch main.
````

Thanks!
