### ISSUE TITLE
Cannot reset linked database when citext extension in use

### ISSUE THREAD

**Issue by stlbucket** [supabase/cli#1470]
after first successfully deploying migrations to linked database, executing:
```
npx supabase db reset --linked
```

gives the following error:

```
╰─➤  sup db reset --linked
Confirm resetting the remote database? [y/N] y
Resetting remote database...
ERROR: cannot drop function citext_pattern_lt(citext,citext) because extension citext requires it (SQLSTATE 2BP01)
At statement 14: do $$ declare
  rec record;
begin
  -- functions
  for rec in
    select *
    from pg_proc p
    where p.pronamespace::regnamespace::name = 'public'
  loop
    -- supports aggregate, function, and procedure
    execute format('drop routine if exists %I.%I(%s) cascade', rec.pronamespace::regnamespace::name, rec.proname, pg_catalog.pg_get_function_identity_arguments(rec.oid));
  end loop;

  -- in order: tables (cascade to views), sequences
  for rec in
    select *
    from pg_class c
    where
      c.relnamespace::regnamespace::name = 'public'
      and c.relkind not in ('c', 'v', 'm')
    order by c.relkind desc
  loop
    -- supports all kinds of relations, except views and complex types
    execute format('drop table if exists %I.%I cascade', rec.relnamespace::regnamespace::name, rec.relname);
  end loop;

  -- types
  for rec in
    select *
    from pg_type t
    where t.typnamespace::regnamespace::name = 'public'
  loop
    execute format('drop type if exists %I.%I cascade', rec.typnamespace::regnamespace::name, rec.typname);
  end loop;
end $$;
```

supabase v 1.88.0

**Comment by sweatybridge** [comment]
Could you give try the latest beta release to see if it works? Feel free to post here if you run into other problems resetting.

**Comment by stlbucket** [comment]
Hi Han,

Are you asking me to try the latest beta version?   Would this be in the
CLI or does the fix happen on the platform itself?

I'm a little hesitant to switch up my supabase versions on any front at
this moment as I'm still building a few features before I'm really needing
to deploy online.  Past experience has me a little gun-shy of messing up my
local environment.

That being said, it will likely be tomorrow when I am ready to move
forward.  I will circle back and confirm soon.

Thanks,

Kevin

**Comment by sweatybridge** [comment]
Understand. The fix we made was to drop extensions before functions and other objects when performing a remote reset. I tested this locally with citext extension enabled from a migration file. There is no platform changes required for this fix. 

You can try it out without updating your local `package.json` by running `npx supabase@beta db reset --linked`. 

Of course, it is up to you when you want to try it out.

**Comment by stlbucket** [comment]
Han,

I tried it out with ***@***.*** db reset --linked and it worked

Thanks,

Kevin
