### ISSUE TITLE
Receiving no such file as node_modules/supabase/bin/supabase when deploying nodejs server [npm]

### ISSUE THREAD

**Issue by sspahic2** [supabase/cli#1474]
**Describe the bug**
When I deploy my NodeJS server after adding supabase to it, I receive the error that there is no such file or folder in node_modules/supabase/bin/supabase.

**Note**: I'm using Render hosting to deploy my NodeJS server.

**To Reproduce**
1. Add @supabase/supabase-js and supabase with npm
2. Deploy project to Render
3. Receive error

**Expected behavior**
Deployment was successful.

**Screenshots**
![image](https://github.com/supabase/cli/assets/12472045/19654e37-8ee6-4edd-963c-4702f8dcffee)

**Desktop (please complete the following information):**
Not applicable

**Additional context**
I've tried locally to reproduce the issue by deleting node_modules, but it installs correctly.

**Comment by sweatybridge** [comment]
Hi @sspahic2, can you try running `npm install --production` when deploying the project to Render? Typically the cli is not needed for deployment as it's only installed as a [dev dependency](https://github.com/supabase/cli#install-the-cli).

**Comment by sspahic2** [comment]
Hello @sweatybridge ,
thank you very much. That information struck gold and resolved the issue.
