### ISSUE TITLE
Cannot bypass password prompt for `supabase link`

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1480]
**Describe the bug**
I am trying to run `supabase link` in a CICD environment but the command always prompts for a password. 

We wish to skip this automatically but there is no CLI options to do so.

**To Reproduce**N/A

**Expected behavior**

Have a flag to skip passing a password when running `supabase link`

**Screenshots**
![image](https://github.com/supabase/cli/assets/44002321/5182f016-4b2b-40a2-854e-be0cfdf59b89)
![image](https://github.com/supabase/cli/assets/44002321/fd17e794-0a81-4708-bdaa-16d0116d2afd)

**Desktop (please complete the following information):**
 - Version of CLI 1.91.1

**Additional context**

**Comment by sweatybridge** [comment]
It's not intuitive but you can use input redirect to bypass password prompt. For eg.

```bash
supabase link --project-ref ******************** <<< ""
```

**Comment by bombillazo** [comment]
Ill mark as complete since there is a way around passing the empty string
