### ISSUE TITLE
Allow running supabase with SSL enabled (accessible via HTTPS)

### ISSUE THREAD

**Issue by jovobe** [supabase/cli#1491]
**Is your feature request related to a problem? Please describe.**
I'm currently implementing the [Login with Apple](https://supabase.com/docs/guides/auth/social-login/auth-apple) functionality. Sadly, I'm unable to test my implementation locally because Apple forces you to provide an HTTPS URL as a return URL. Because supabase runs locally without SSL, this callback URL looks like this: `http://localhost:54321/auth/v1/callback`.

**Describe the solution you'd like**
It would be very nice no either have a switch in the `config.toml` to enable SSL or just to serve the `/auth` endpoints via two separate ports, one with SSL enabled and one without. E.g. `https://localhost:54329/auth/v1/callback`

**Describe alternatives you've considered**
A workaround I'm going to implement now is to serve a reverse proxy (e.g. traefik) locally that just translates a local HTTPS endpoint to the given HTTP one.

**Additional context**
This is how the Apple config dialog looks like: 
![Screenshot 2023-09-14 at 3 59 16 PM](https://github.com/supabase/cli/assets/1265894/b2d2e95f-1dfe-4779-b732-83570f86c68c)

**Comment by grddavies** [comment]
I'd also appreciate this functionality for my use case:

**Is your feature request related to a problem? Please describe.**
I want to use supabase cli to test my web app locally, and with devices on my local network. My app needs to be served via https to enable access to the camera media stream. 

**Describe the solution you'd like**
Switch in config to enable SSL, or additionally enabling auth via https by default

**Describe alternatives you've considered**
This can be mitigated by enabling camera access over http in the browser of the device I am testing (eg via <chrome://flags/#unsafely-treat-insecure-origin-as-secure>)

**Comment by mlawlerau** [comment]
Trying to implement Apple OAuth locally too. Need HTTPS for local supabase.,

**Comment by andreasvirkus** [comment]
Same issue with developing Slack apps 😕 

![Screenshot 2024-07-01 at 23 55 31](https://github.com/supabase/cli/assets/9140811/4daae3a9-a9ee-4c8f-9f36-a373157b8305)

**Comment by TheCodeDestroyer** [comment]
@sweatybridge from what I can see this is now supported via:
```
[api.tls]
enabled=true
```
Is that correct?

**Comment by sweatybridge** [comment]
Yes, that's correct.

**Comment by nathangroblewski** [comment]
Incase anyone else finds themselves here using Nextjs with `--experimental-https` flag

Ensure you enable the `[api.tls]` flag in the `config.toml` as mentioned above

```json
    "scripts": {
        "dev": "NODE_TLS_REJECT_UNAUTHORIZED='0' next dev --experimental-https",
     }
```

Obviously, don't disable `NODE_TLS_REJECT_UNAUTHORIZED` in deployed environments
