### ISSUE TITLE
"supabase migration up" fails on local projects

### ISSUE THREAD

**Issue by ds300** [supabase/cli#1497]
**Describe the bug**

I'm using supabase for local dev and I don't have a linked project set up.

As of version `1.95.0`, when I run `supabase migration up` it fails with the following error:

    Cannot find project ref. Have you run supabase link?

I had a look and it seems like recently the way that the cli flags were parsed/defined was changed, and the relevant ones are here I think.

https://github.com/supabase/cli/blob/b7c58ad9dc937a01a40591a5a8b8a66746010637/cmd/migration.go#L127-L128

These flags' default values, on my machine at least, cause the cli to think it should run in linked mode, and it ends up going down this code path:

https://github.com/supabase/cli/blob/b7c58ad9dc937a01a40591a5a8b8a66746010637/internal/utils/flags/db_url.go#L63-L72

which causes the failure mentioned above.

**To Reproduce**
run `supabase migration up` in a non-linked context

**Expected behavior**
it applies the migrations, or tells me that my local db is up to date

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version of CLI: `1.99.1` but the bug was introduced in `1.95.0` as far as I can tell

**Additional context**
This doesn't seem to happen for other members of my team, so I may have some special messed up state on my machine. I tried nuking all the dotfiles in the `supabase` directory of my project, I tried resetting the db, I tried stopping and starting. Let me know if I can provide any other useful context.

**Comment by sweatybridge** [comment]
Thanks for raising this issue. I managed to reproduce and release a fix in the latest version.
