### ISSUE TITLE
Tutorial (ionic react) lacks db migration

### ISSUE THREAD

**Issue by EvgeniiaVak** [supabase/cli#1499]
**Link**
https://supabase.com/docs/guides/getting-started/tutorials/with-ionic-react#set-up-the-database-schema

**Describe the problem**
When going through the tutorial it asks to run User Management Starter which creates a new table however it does not create a migration, so later when trying to run the project locally with supabase cli, the table is not there.

**Describe the improvement**
Running starters could also create migrations. Alternatively, the documentation could guide you through creating a migration with the provided SQL instead.

**Comment by thorwebdev** [comment]
Good idea, thanks for flagging @EvgeniiaVak 💚
