### ISSUE TITLE
Local `pg-bouncer` container startup auth error

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1508]
**Describe the bug**

We are having trouble with the local pg-bouncer image when running on a linux machine.

**To Reproduce**
1. Run `supabase start`
2. Go to the `supabase_pooler_app` container logs to see error

**Expected behavior**

**Screenshots**

![image](https://github.com/supabase/cli/assets/44002321/690dc80e-c172-4f36-8147-ffa2fdd4d4da)

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 38)
 - Version of CLI: 1.97.1

**Additional context**

**Comment by sweatybridge** [comment]
Kinda crazy how this bug trickled down from upstream [bitnami/pgbouncer repo](https://github.com/bitnami/containers/issues/48959). I've updated our ECR mirror with their latest fixes for this tag. Could you run `docker pull public.ecr.aws/supabase/pgbouncer:1.20.1` and restart the local stack to see if it helps?

I've also made a PR to use their immutable tag to prevent such cases from happening in the future.

**Comment by bombillazo** [comment]
@sweatybridge we just confirmed it works, thanks!
