### ISSUE TITLE
use --env-file on localhost supabase start / stop / reset

### ISSUE THREAD

**Issue by jdgamble555** [supabase/cli#1518]
**Describe the bug**
I'm not sure if this is a bug or a needed feature, but I would like to be able to load a different `.env` file name besides just `.env`.  Apparently this is possible for local edge functions per [Managing Secrets and Environment Variables](https://supabase.com/docs/guides/functions/secrets), but not possible for the whole supabase? This doesn't make sense to me why it would only be available for local function testing and not the whole  `config.toml`, so perhaps I am missing something?

**To Reproduce**
Run localhost with `supabase start --env-file ./.env.development`

**Expected behavior**
It would load the `.env.development` (or whatever name), instead of throwing an error:
```
unknown flag: --env-file
```
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of CLI 1.99.5
 - Version of Node.js 18

Thanks,

J

**Comment by bombillazo** [comment]
That I know of, `supabase start` does not use a --env.file flag, but you can source the env file you want to use locally in your CLI and supabase start will see those variables.

**Comment by jdgamble555** [comment]
`source` is specific to unix and still a work around. I am using Windows (statistically most programmers do), and I don't want to declare all my projects env variables globally.

It is weird that it was implemented only for functions then. 

Should I close this and make a feature request?

J

**Comment by jdgamble555** [comment]
I should add that this works:
```
supabase functions serve --env-file ./path/to/.env-file
```
But we need this to work:
```
supabase start --env-file ./path/to/.env-file
supabase stop --env-file ./path/to/.env-file
supabase reset --env-file ./path/to/.env-file
...
```
So not just `supabase start`.

J

**Comment by msawangwan** [comment]
this would be much appreciated.

**Comment by Matsuuu** [comment]
I've also come to want this. Mainly because I want to be creating a dev setup, where I could have a simple setup steps for our dev team on varying machines (unix, windows, etc.) without having to have separate instructions on each machine. 

Running supabase from npx or a local installation is already quite cross-platform but if the project has *any* env variables, it becomes a burdain to make cross platform.

After reading through [Function.run](https://github.com/supabase/cli/blob/main/internal/functions/serve/serve.go#L36C7-L36C7) codes and [Start.run](https://github.com/supabase/cli/blob/main/internal/start/start.go#L128-L888) codebases, I don't think it's impossible to just [Boop some env variables on board](https://github.com/supabase/cli/blob/main/internal/start/start.go#L801-L815).


Actually implementing it to all of the cli api's though? That might require some monkey patching which I don't know is the best approach.

Could there be an approach where we create a loader for `--env-file` files and use it anywhere in the system? That would allow us to add this functionality to all of the cli endpoints, without having to trickle down the variable through all of the function calls.

Something along the lines of  (writing js as go isn't my strong suit)

```javascript
class LocalEnvManager {
  #instance;
  static getInstance() {
    if (!this.#instance) {
      this.#instance = new LocalEnvManager();
    }
    return this.#instance;
  }

  readSuppliedEnv(envFilePath) {
        // envFilePath is supplied by user via `--env-file`
	const userEnv = parseEnvFile(envFilePath, fsys) // This function is already in https://github.com/supabase/cli/blob/main/internal/functions/serve/serve.go#L180
  }
}
```

And then we could just call the singleton instance throughout our cli pathways to trickle them around the different `utils.DockerStart` calls. 

---

Would this singleton-ish approach make any sense? It would allow us to utilize the same flag across the cli API without having to completely butcher the function calls by adding more and more params to them and trickling the data down all of the pipes.

I'd be happy to take a stab at this if there's interest. Ping @sweatybridge or someone who's actively maintaining this project.

**Comment by goggle555** [comment]
Personally, I would be happy if `.env.local` is automatically used in the local development environment.
`.env.local` is often included in `.gitignore` and can safely handle environmental counts.

**Comment by sweatybridge** [comment]
> Personally, I would be happy if .env.local is automatically used in the local development environment.

I like this suggestion as well. We can probably follow the [convention](https://github.com/joho/godotenv) documented by godotenv. While it's not as explicit as --env-file flag, it does same quite a lot of keystrokes when starting and stopping. 

If anyone would like to contribute a PR, this would be the code to update: 
https://github.com/supabase/cli/blob/4f83327b92768dc691a849ff0b5c75570a218ff7/internal/utils/config.go#L485

**Comment by sweatybridge** [comment]
CLI now supports the following precedence order when loading `.env` files

<table>
  <thead>
    <tr>
      <th>Priority</th>
      <th colspan="3">Environment</th>
      <th><code>.gitignore</code>it?</th>
      <th>Notes</th>
    </tr>
    <tr>
      <th></th>
      <th>development</th>
      <th>test</th>
      <th>production</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tr>
    <td>highest</td>
    <td><code>.env.development.local</code></td>
    <td><code>.env.test.local</code></td>
    <td><code>.env.production.local</code></td>
    <td>Yes</td>
    <td>Environment-specific local overrides</td>
  </tr>
  <tr>
    <td>2nd</td>
    <td><code>.env.local</code></td>
    <td><strong>N/A</strong></td>
    <td><code>.env.local</code></td>
    <td>Yes</td>
    <td>Local overrides</td>
  </tr>
  <tr>
    <td>3rd</td>
    <td><code>.env.development</code></td>
    <td><code>.env.test</code></td>
    <td><code>.env.production</code></td>
    <td>No</td>
    <td>Shared environment-specific variables</td>
  </tr>
  <tr>
    <td>last</td>
    <td><code>.env</code></td>
    <td><code>.env</code></td>
    <td><code>.env</code></td>
    <td><a href="#should-i-commit-my-env-file">Maybe</a></td>
    <td>Shared for all environments</td>
  </tr>
</table>

Ref: https://github.com/bkeepers/dotenv?tab=readme-ov-file#customizing-rails

**Comment by gorango** [comment]
After upgrading to the latest version of Supabase, I am still unable to use environment variables in my local env, getting: `Error evaluating "env(VARIABLE)": environment variable VARIABLE is unset.`

I tried `source .env`, `supabase secrets set --env-file supabase/.env`, `supabase start --env-file supabase/.env`, and ofcourse `supabase start` after running `source` and `secrets`.

**Desktop environment**

- OS: Ubuntu 22.04.4 LTS x86
- CLI: v1.191.3 and v1.117.0
- Node: v20.12.0

**Comment by tommedema** [comment]
none of these .env files seem to work for me, including prefixing export. E.g. when I set AUTH_JWT_SECRET in an .env then restart supbase it still uses the default key:

JWT secret: super-secret-jwt-token-with-at-least-32-characters-long

**Comment by tommedema** [comment]
tried using the beta version, but same issue persists :(

**Comment by sweatybridge** [comment]
You want to use `SUPABASE_AUTH_JWT_SECRET` in .env file. I will create a separate issue to improve the docs on config.toml since that trips up users quite often.

**Comment by thebrrt** [comment]
Hi @sweatybridge thank you for all of your work! Where can I find documentation on what the .env file key names should be? Specifically for the anon and service key definitions

**Comment by thebrrt** [comment]
Never mind I found something!! If anyone else finds this via a Google search, I was able to find it at this repo's README:
https://github.com/supabase/fly-preview

**Comment by manizm** [comment]
Is this supposed to substitute values in config.toml as well when starting? i.e. `project-id = "env(PROJECT_ID)"` is not getting substituted by values present in .env file. It didn't work by adding values through dotenv-cli either. 

My project structure is:
```
package.json
.env
supabase
|-- config.toml
|-- other files
```

**Comment by joelpramos** [comment]
@sweatybridge this didn't work for me for functions with the `supabase start` with any combination of `SUPABASE_ENV=local supabase start` or sourcing before as suggested above `source supabase/functions/.env.local && supabase start`... etc. Tried the files at different levels (repo root, supabase/, supabase/functions).

only the variables under `.env` on `supabase/functions` are pulled into the Edge functions runtime.

any thoughts here?

**Comment by jdgamble555** [comment]
For me, I use `.env` for local testing, and if I need to test prod locally, it won't be a local supabase (you can only run one at a time anyway), it will connect directly to my hosted prod database. If I had a staging, it would probably be a hosted free tier for testing only.

So not really needed when you think about it.

J
