### ISSUE TITLE
migration-up doesn't connect to remote projects

### ISSUE THREAD

**Issue by Pictor13** [supabase/cli#1519]
**Describe the bug**
Migration-up functionality works only on local-development.
Nor `supabase migration up --db-url "$REMOTE_DB_URL"` or `supabase migration up --linked` seem to interact with the remote db; migration-up always connects to local-dev.

**To Reproduce**
```
$ REMOTE_DB_URL="postgresql://postgres:${REMOTE_DB_PASSWORD}@db.${SUPABASE_PROD_PROJECT_ID}.supabase.co:5432/postgres"
$ supabase migration up --db-url "$REMOTE_DB_URL"
Applying migration 20230922120547_add-mytable-new_column.sql...
ERROR: column "new_column" of relation "mytable" already exists (SQLSTATE 42701)
At statement 0: -- we test a 'new_column' migration with
alter table "public"."mytable" add column "new_column" boolean not null default true
Try rerunning the command with --debug to troubleshoot the error.

$ supabase stop
Postgres database saved to volume: supabase_db_spydefi-be
Postgres config saved to volume: supabase_config_spydefi-be
Storage directory saved to volume: supabase_storage_spydefi-be
Inbucket emails saved to volume: supabase_inbucket_spydefi-be
Stopped supabase local development setup.

$ supabase migration up --db-url "$REMOTE_DB_URL"
failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)
Try rerunning the command with --debug to troubleshoot the error.
$ supabase link --project-ref $REMOTE_PROJECT_ID --password "$REMOTE_DB_PASSWORD"    
$ supabase migration up --linked 
failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)
Try rerunning the command with --debug to troubleshoot the error.
```

**Expected behavior**
`--linked` or specific `--db-url` should run the migrations on the remote Supabase database, rather  than on the local-dev environment.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version of CLI [e.g. v1.99.5]

**Additional context**
I restored a database from a dump onto the remote project's database; I need to run a migration that I created on local-development, but the issue is a blocker for managing remote migrations.

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. It might have been a mistake to expose `--db-url` and `--linked` flags to `migration up` command as it's traditionally used for local database only.

As a workaround, could you run `supabase db push --db-url "$REMOTE_DB_URL"` instead?

**Comment by Pictor13** [comment]
Oh ok I understand, I'm also victim of copy/paste at times 😁

Is `db push` a workaround or is the functionality the same?

**Comment by sweatybridge** [comment]
`db push` was created before `migration up` so it will more likely stay. Its functionality is to apply your local migrations to the remote db.

**Comment by sweatybridge** [comment]
This has been fixed in latest release https://github.com/supabase/cli/releases/tag/v1.110.1
