### ISSUE TITLE
Cannot copy and paste `SUPABASE_ACESSS_TOKEN` on the CLI `login` page.

### ISSUE THREAD

**Issue by bwprado** [supabase/cli#1521]
**Describe the bug**
When using the Supabase CLI, trying to the command `npx supabase login`, it does not allow me to write anything on the prompt: **Enter your access token:**, neither does it allow me to copy and paste the access token to login to the CLI.

**To Reproduce**
1. `npx supabase login`
2. Try to write anything on the prompt.
3. Try to copy and paste the access token

**Expected behavior**
CLI should allow user input of any form there.

**Screenshots**
![image](https://github.com/supabase/cli/assets/77552420/d706e448-f237-49c4-a780-5dab24c51929)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Terminal 1: Git Bash
 - Terminal 2: Windows Powershell
 - Version of supabase: `^1.99.5`,

**Comment by sweatybridge** [comment]
Closing this as a duplicate of https://github.com/supabase/cli/issues/1054

We hide the token input by design to avoid accidentally storing it in your shell history. If you press `enter` after `ctrl+v`, the pasted token should still be accepted by the CLI.

As a future improvement, we may consider showing an indicator that something has been typed, like `sbp_****`.

**Comment by bwprado** [comment]
I'm sorry @sweatybridge, but I cannot, for the love of god, paste anything in there. Tried many computers and terminals.

https://github.com/supabase/cli/assets/77552420/824356e3-9251-40aa-bdfe-bb957df5b6d7

**Comment by sweatybridge** [comment]
Not sure what's the root cause but you can work around it by setting the environment variable `export SUPABASE_ACCESS_TOKEN=spb_**`. That allows you to skip the login command entirely.

**Comment by andreapiso** [comment]
This is a real bug and should not be closed, I also am not able to paste/type anything in the terminal to log in, I am on Mac and it does not work either with zsh or bash.
