### ISSUE TITLE
CLI any command timeout

### ISSUE THREAD

**Issue by kno-raziel** [supabase/cli#1524]
**Describe the bug**

After a failed try of  `npx supabase db reset --linked`,  any command from the CLI just fail with a timeout.

**Expected behavior**
Success command execution in terminal.

**Screenshots**
<img width="1160" alt="image" src="https://github.com/supabase/cli/assets/8211946/21a283e9-a7be-40a1-b66f-580d0d82baf1">

<img width="1139" alt="image" src="https://github.com/supabase/cli/assets/8211946/e639a89d-a983-45df-8dd0-0e47f69dd272">

**Desktop (please complete the following information):**
 - OS: macOS  v13.5.2
 - Version of CLI: v1.99.5 
 - Version of Node.js : v16.19.0

**Additional context**
The issue started to happen after a failed reset in remote.

**Comment by sweatybridge** [comment]
Could you check if connecting via `psql 'postgresql://postgres:<password>@db.qoazdmrkgfabrsxuqgqo.supabase.co:5432/postgres'` works for you?

**Comment by kno-raziel** [comment]
> Could you check if connecting via `psql 'postgresql://postgres:<password>@db.qoazdmrkgfabrsxuqgqo.supabase.co:5432/postgres'` works for you?

I have tried to connect with pgAdmin using this [guide](https://supabase.com/docs/guides/database/connecting-to-postgres#how-connection-pooling-works) and is also timeout 😩
 
![image](https://github.com/supabase/cli/assets/8211946/d34ddaf3-d5aa-47c3-b9cb-895ec6500c5a)

The weird thing is I'm able to connect in my sveltekit project using the @supabase/auth-helpers-sveltekit 🤔

**Comment by sweatybridge** [comment]
It looks like an issue with your hosted project. Feel free to send a support ticket if this is still happening.
