### ISSUE TITLE
Deno v1.37 runtime

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1525]
**Describe the bug**
Hello, I have no way of confirming, but I believe the edge runtime deno version is lower than 1.37.

Deno 1.37 introduced many new features, including Resource Management and the `using`keyword. 

It would be great for the Deno edge-runtime containers and remote edge functions to support Deno 1.37.

**To Reproduce**
N/A

**Expected behavior**
Support for Deno 1.37

**Desktop (please complete the following information):**
 - Version of CLI 1.99.9

**Comment by laktek** [comment]
@bombillazo We will add support for 1.37 within the next 2 weeks. Usually, we allow some time after release to land security updates, fixes etc before upgrading.

**Comment by laktek** [comment]
@bombillazo The latest release of Supabase CLI ([v1.108.4](https://github.com/supabase/cli/releases/tag/v1.108.4)) should have support for Deno 1.37.1
