### ISSUE TITLE
Postinstall script is not running while using Bun

### ISSUE THREAD

**Issue by SHA-2ws** [supabase/cli#1527]
**Describe the bug**
After running the "bun add supabase -d" command, when attempting to use "bunx supabase login," an error occurs with the message "supabase command not found." 

**To Reproduce**
1. Run the command: `bun add supabase -d`
2. Attempt to use "bunx supabase login"

**Expected behavior**
After installing the CLI, the postinstall script should run successfully.

**Desktop:**
- OS: Windows 10 with WSL (Arch)
- Version of CLI: v1.99.5
- Version of Bun: v1.0.3

**Additional context**
I resolved the issue by replacing "node" with "bun" in the package.json's postinstall script and running it with "bun postinstall." This change allowed the CLI to function as expected.

**Comment by akoenig** [comment]
@SHA-2ws This is intended and not really related to supabase. `bun install` doesn't execute lifecycle scripts. You have to add `supabase` as a `trustedDependency` in your `package.json`:

```json
  "trustedDependencies": [
    "supabase"
  ],
```

You can read more about [here](https://bun.sh/docs/cli/install#trusted-dependencies). After adding it to your `package.json`, make sure to remove `~/.bun`, `node_modules` and the `bun.lockb` file and execute `bun install`.

**Comment by kamilogorek** [comment]
@akoenig I'd not recommend removing `~/.bun` as it's default location for the `bun` binary itself if you follow official "install guide" 😅
It's better to use `bun pm cache rm` instead, which will always choose correct cache directory.

**Comment by akoenig** [comment]
@kamilogorek ah true, you're right. Thanks for the heads up.

I'm using [devbox](https://www.jetpack.io/devbox) which utilizes `nix` under the hood and therefore the bun binary lives in the nix store so it was "safe" to delete `~/.bun`.

**Comment by sweatybridge** [comment]
Closing this as we have documented the installation steps using trusted dependency as part of [readme](https://github.com/supabase/cli#install-the-cli).
