### ISSUE TITLE
Postgrest image not found

### ISSUE THREAD

**Issue by gergely-xyz** [supabase/cli#1532]
**Describe the bug**
When I try to start supabase for local development with the cli the command fails as it can't find the given version of the postgrest image.

The following error is shown:
```
Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v10.2.0 not found: manifest unknown: Requested image not found
```
Looking at the [image repo](https://gallery.ecr.aws/supabase/postgrest) there is indeed no 10.2.0 tag available.

**To Reproduce**
1. Install supabase cli version 1.99.5 with yarn
2. run ```yarn supabase start``` in an initialized project

**Expected behavior**
The cli pulls an image that exists.

**Desktop:**
 - OS: Arch Linux and Windows 10
 - Version of CLI 1.99.5

**Comment by sweatybridge** [comment]
I've triggered a mirror job to sync the v10.2.0 tag https://github.com/supabase/cli/actions/runs/6337320512

It should be available now.
