### ISSUE TITLE
supabase db diff doesn't output storage buckets information.

### ISSUE THREAD

**Issue by HoussemBousmaha** [supabase/cli#1537]
**Is your feature request related to a problem? Please describe.**
The goal of course is to do supabase local development with all its features and then simply get all my database schemas and storage buckets so that i can migrate them to my remote supabase project. maybe there is a way to do this and i am just dumb but the solution i figured out was to use `supabase db diff` to get the database schema and go to the remote database -> sql editor and paste it all there and run it.

i don't know exactly how it's properly done. maybe you can help.

**Comment by sweatybridge** [comment]
We have a storage bucket section in local dev guide https://supabase.com/docs/guides/cli/local-development#sync-storage-buckets

Let me know if this is sufficient for your use case.

**Comment by sweatybridge** [comment]
To sync from local to remote, you can run `supabase db diff --schema storage`.

**Comment by HoussemBousmaha** [comment]
thank you sir!
