### ISSUE TITLE
Support tsrange in generated typescript types

### ISSUE THREAD

**Issue by pingiun** [supabase/cli#1549]
**Is your feature request related to a problem? Please describe.**

Right now the cli generates a type of `unknown` for tsrange fields. It would be nice to get some information for rows that include a `tsrange`

**Describe the solution you'd like**

Some javascript type that nicely represents a range

**Describe alternatives you've considered**

Parsing the data manually, but this is error prone and annoying

**Additional context**

-

**Comment by soedirgo** [comment]
Closing as duplicate of https://github.com/supabase/cli/issues/531
