### ISSUE TITLE
ERROR: schema "supabase_functions" does not exist

### ISSUE THREAD

**Issue by kirkstrobeck** [supabase/cli#1552]
**Describe the bug**

I run `supabase db push` locally and get this error

```
ERROR: schema "supabase_functions" does not exist (SQLSTATE 3F000)
```

**To Reproduce**

1. Create a migration with `supabase_functions` in the contents
2. `supabase db push`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 14.0 (23A344)
 - Version of CLI: 1.100.1
 - Version of Node.js: v18.12.1

**Additional context**

I’m also experiencing this on GitHub actions and [this solution](https://github.com/supabase/cli/issues/925#issuecomment-1554959917) doesn’t work

**Comment by kirkstrobeck** [comment]
Solved by going to the supabase instance and enabling webhooks

**Comment by Serlych** [comment]
@kirkstrobeck Thanks, it solved it for me too. Posting in case anyone is looking for the answer.
Following [Supabase docs](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#restore-to-your-new-project). 😄

**Comment by sid-gandhi** [comment]
Bro solved it @Serlych 👏🏿

**Comment by felixmpaulus** [comment]
This is not a solution for remote branches... How can I enable webhook automatically on branch creation?
