### ISSUE TITLE
Migration squash only targets some schemas

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1562]
**Describe the bug**

It may be necessary to change schemas other than public and custom schemas. For example, adding triggers to the auth schema or storage schemas.

The `squash` command does not add the changes present in these schemas to the squashed schema file, so when one creates a new migration just after squashing, one gets a new migration with the missing changes for the rest of the schemas.

**To Reproduce**
1. Make changes to the auth schema (add a trigger to the users table for example)
1. Run `supabase migration squash --local`
2. Run `supabase db diff --local -f test -s -s public,auth`

**Expected behavior**

Squashing detects and includes the changes to other schemas.

Another option if the desired default behavior is not to add those schemas, is to have a flag like the `db diff` command to pass the list of schemas to include in the squash.

**Comment by sweatybridge** [comment]
Seems to be a duplicate of https://github.com/supabase/cli/issues/1493
