### ISSUE TITLE
Add commands for "get encryption key" and "set encryption key"

### ISSUE THREAD

**Issue by olirice** [supabase/cli#1569]
**Is your feature request related to a problem? Please describe.**
On first postgres start, a script runs to get an encryption key that is used by pgsodium. That key is unique to the instance and used for TCE, Vault, and pgsodium.

That value is intentionally not included in things like pg_dumps so dumped data is encrypted. However, we still need to provide a mechanism for customers to get their encryption key so they can 
- migrate data among projects
- dump a project's data and run it locally

It produces 2+ support issue a week

**Describe the solution you'd like**
I'd like to add a subcommand similar to `supabase encryption key get` and `supabase encryption key set`. The names aren't important so feel free to make the actual commands more consistent with the existing commands.

The routes [already exist](https://supabase.com/docs/reference/api/gets-projects-pgsodium-config) but currently we're asking customers to curl for it which is not very ergonomic. 

**Describe alternatives you've considered**
- Not allow migration of encrypted data
- Ask customers contact support when migrating encrypted projects
- cURL the Postgres-meta endpoint 

cc @michelp

**Comment by sweatybridge** [comment]
We actually just released this to beta channel https://github.com/supabase/cli/releases/tag/v1.101.0

The command is `vault get-root-key` though

**Comment by michelp** [comment]
> The command is vault get-root-key though

The Vault is just one specific case of the general column encryption pattern, all of which use the root key, so naming the parent command "vault" is likely too specific, "tce" or "column-encryption" would be closer to the correct conceptual idea.

**Comment by olirice** [comment]
> just released this to beta channel https://github.com/supabase/cli/releases/tag/v1.101.0

oh nice!


if its still in beta do we have the ability to change that name as Michel suggested ^? maybe even `encryption get-root-key`

**Comment by michelp** [comment]
> maybe even encryption get-root-key

Yeah that's even better, since lots of the symmetric encryption functions in pgsodium unrelated to column encryption also use the root key.

**Comment by sweatybridge** [comment]
> if its still in beta do we have the ability to change that name as Michel suggested ^? maybe even encryption get-root-key

Yup, we haven't documented it anywhere yet so it should be ok to change. I will do that before the next stable release.
