### ISSUE TITLE
No emails sent to inbucket when using signUp

### ISSUE THREAD

**Issue by NixBiks** [supabase/cli#1570]
**Describe the bug**

I'd expect `supabase.auth.signUp` to send emails to inbucket but I see none.

**To Reproduce**

```
npx create-next-app -e with-supabase
```

Add supabase cli and set environment variables to point to the local supabase. Try to sign up and check inbucket afterwards

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS
 - Browser (if applicable) [e.g. chrome, safari]: chrome
 - Version of CLI [e.g. v1.60.0]: 1.100.1
 - Version of supabase-js (if applicable) [e.g. v2.22.0]: 2.38.0
 - Version of Node.js (if applicable) [e.g. v16.20.0]: v16.15.1

**Comment by BCYCAData** [comment]
Any movement on this?

**Comment by sweatybridge** [comment]
This is most likely because inbucket's smtp port is commented out in your `config.toml`. I can receive signup emails using the following config.

```
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
smtp_port = 54325
# pop3_port = 54326
```
