### ISSUE TITLE
Project aliases and flags

### ISSUE THREAD

**Issue by hamishjohnson** [supabase/cli#1573]
**Is your feature request related to a problem? Please describe.**
I would like to easily be able to choose which project a command is being executed for

**Describe the solution you'd like**
In firebase-tools, you can create project aliases and use project flags. https://firebase.google.com/docs/cli#project_aliases

So you could create an alias "dev" and "prod" and then easily execute commands for each project: i.e. `firebase deploy --only functions -P prod`

**Additional context**
I like to leave dev as the default for security, and then explicitly say when I want to use prod

So a normal call to `firebase deploy --only functions` will use dev alias by default, and then I would have to explicitly do `-P prod` to deploy to production

**Comment by sweatybridge** [comment]
There are currently 3 ways that cli supports for specifying an arbitrary project.

1. Pass in `--project-ref` flag
2. Set `SUPABASE_PROJECT_ID` env var (or using .env file)
3. Link a project with `supabase link`

If you don't specify any of the above, cli will prompt you with a list of projects to choose to. You can then filter them down by name, org, or ref.

I believe these methods can sufficiently fulfil the needs of project alias.
