### ISSUE TITLE
go install creates ~/go/bin/cli instead of ~/go/bin/supabase

### ISSUE THREAD

**Issue by opsaaaaa** [supabase/cli#1580]
Its as the title says.
The issue and replication:
```sh
$ go install github.com/supabase/cli@latest                   
$ ls ~/go/bin                   
air  **cli**  cobra-cli  goeval  gomacro  pup
$ cli help
Supabase CLI

Usage:
  supabase [command]
...
Use "supabase [command] --help" for more information about a command.
```
See? Took me a minute to realize what happened. Funny problem though.

workaround:
```sh
$ mv ~/go/bin/cli ~/go/bin/supabase
```

version:
```sh
$ go version  
go version go1.21.0 linux/amd64
```

**Comment by kamilogorek** [comment]
There's a note about running `ln -s "$(go env GOPATH)/cli" /usr/bin/supabase` as there's currently no way to change the behavior of `go install` and it will always use package name as the binary name as well.
Do you think there's anything that requires rewording in docs?

**Comment by sweatybridge** [comment]
Yup, agree that it's something inherent with go install. Closing with a link to our docs with the symlink suggestion https://github.com/supabase/cli/blob/main/README.md?plain=1#L120
