### ISSUE TITLE
Trying to link to a project on expo react-native

### ISSUE THREAD

**Issue by FaysalBsata** [supabase/cli#1588]
**Describe the bug**
I am doing npx supabase link --project-ref <project-ref> --password  <pass>
and I'm getting Error status 404: {"message":"Route GET:/version not found","error":"Not Found","statusCode":404}
**To Reproduce**
npx supabase link --project-ref <project-ref> --password  <pass>

**Expected behavior**
I expected to finish the command without throwing errors

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Version of Node.js v16.20.0

**Comment by nkriege** [comment]
Seems to have been introduced in v1.103.0. Downgrading to v1.102.3 fixes this.

**Comment by FaysalBsata** [comment]
@nkriege how can I do that?

**Comment by FaysalBsata** [comment]
Error status 404: {"message":"Route GET:/version not found","error":"Not Found","statusCode":404}
Finished supabase link.
@sweatybridge

**Comment by sweatybridge** [comment]
> Finished supabase link.

This looks good. It's probably because your hosted project is still on storage v2 while we are migrating to v3. 

There's nothing to worry about at the moment as it will be fixed eventually when we finish migrating every hosted project.

**Comment by sweatybridge** [comment]
This has been addressed in the latest beta release.

**Comment by yystock** [comment]
> This has been addressed in the latest beta release.
tried beta release,` supabase link `did succeed, but `supabase db pull` fails with the error:
Supabase CLI 1.108.3
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:52                             
  in github.com/supabase/cli/internal/db/pull.Run:33

**Comment by landsman** [comment]
I got the same error, latest macOS.

1. `supabase init`
2. `supabase link --project-ref xxx`
3. When I ran `supabase projects list` I saw that the project is successfully linked
4. but when I ran `supabase migration up` it tried to run it to localhost database:

```
failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)
```

What did I miss? In `./supabase/config.toml` is no info about linked project / remote db.

**Comment by sweatybridge** [comment]
Do you want to push migrations to the linked project? Currently that command is `supabase db push`.

`supabase migration up` is currently used for local database only. It's pending another refactor [here](https://github.com/supabase/cli/pull/1505).

**Comment by stephencweiss** [comment]
Thanks @nkriege -- this solved it for me:

```shell
npx supabase@1.102.3 link --project-ref <ref>
Need to install the following packages:
  supabase@1.102.3
Ok to proceed? (y) y
Enter your database password (or leave blank to skip): 
Finished supabase link.
```

**Comment by landsman** [comment]
> Do you want to push migrations to the linked project? Currently that command is `supabase db push`.

yes, after a few minutes, I figured it out. It works.

I thought that `database` was only for manipulation with dumps, schema, or something like that, so command named `migration` caught my eye more.

Thanks.
