### ISSUE TITLE
"public" schema in studio does not represent postgres "public" schema correctly

### ISSUE THREAD

**Issue by simpros** [supabase/cli#1590]
**Describe the bug**
In studio version 20230921-d657f29 internal table policies are shown.

**To Reproduce**
1. Update to latest supabase cli
2. `supabase stop` & `supabase start` to fetch latest docker-images
3. Open the studio on `localhost:54323`
4. Open Authentication > Policies

**Expected behavior**
Internal Tables should not be shown under this tab as it is on the hosted version

**Screenshots**
<img width="1260" alt="image" src="https://github.com/supabase/cli/assets/38320875/0a1e1ceb-fa4a-47e9-997d-927a28768441">

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser: Arc
 - Version of CLI: 1.106.1

**Comment by chriscasper** [comment]
Having this same issue. Its also affecting the schema display and the tables list under the database for me on local `supabase start`

Supabase: v1.100.1
Postgres v15.1.0.122 

Note: This is from a database migration from a  V14 project i had. Wondering if this is the cause or if Supabase is broken locally?

**Comment by simpros** [comment]
@chriscasper yes you are right, its also in the database view in the public schema.

But the problem is not postgres as in pgadmin the "public" schema seems correct

![image](https://github.com/supabase/cli/assets/38320875/a06a636e-bff6-453d-964f-b6614268b79f)

**Comment by sweatybridge** [comment]
This sounds like an issue with search_path as those extra schemas are from the extensions schema. I will take a closer look next week.

**Comment by simpros** [comment]
Another thing that just came up with this bug, is that my update calls on the local machine take at least 6 seconds. On the hosted version there is no Problem at all. Could that be related @sweatybridge ?
