### ISSUE TITLE
`db reset` to specific migration

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1594]
**Is your feature request related to a problem? Please describe.**

Currently, `db reset` will run all migrations in the migrations folder. Sometimes, we want to run to a specific migration and not run the whole list as we develop.

**Describe the solution you'd like**

Add a new flag (perhaps `--target-migration`) to specify which migration to reset the database.

**Describe alternatives you've considered**

We have to move the files we do not want to run during db reset, then move them back after we reset the database.

**Comment by sweatybridge** [comment]
I believe this is already available via `db reset --version` flag.

**Comment by bombillazo** [comment]
Ahh I thought that meant the database postgres version, not the migration, thanks!
