### ISSUE TITLE
supabase link returns 404 on route /version

### ISSUE THREAD

**Issue by josuablejeru** [supabase/cli#1599]
**Describe the bug**
After running `supabase init`, I needed to link the local project with the one hosted by supabase in the cloud (eu-central-1). Running `supabase link  --project-ref <project-id>`  is returning this error:

```
Error status 404: {"message":"Route GET:/version not found","error":"Not Found","statusCode":404}
```

**Expected behavior**
Should be successfully link the project locally 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version of CLI: 1.106.1
 - Version of Node.js: v16.14.2

**Comment by kamilogorek** [comment]
Ref: https://github.com/supabase/cli/pull/1558

**Comment by danhollick** [comment]
Getting this same issue

**Comment by sweatybridge** [comment]
related comment https://github.com/supabase/cli/issues/1588#issuecomment-1772036691
