### ISSUE TITLE
Improve debuggability of database tests (show more test output)

### ISSUE THREAD

**Issue by grschafer** [supabase/cli#1607]
**Is your feature request related to a problem? Please describe.**

When testing non-trivial database functions (with pgtap via `supabase test db`), it's quite difficult to debug or introspect variables. This is largely because the tooling in plpgsql is limited (e.g. no debugger), but perhaps the supabase CLI can help out.

**Describe the solution you'd like**

I have two concrete suggestions:
1. Show `pg_prove` output from the `supabase test db` command by default (rather than requiring the `--debug` flag to see it, mixed in with a bunch of "Sent Header"/"Send Done"/"Recv First Byte" log lines)
2. Let users optionally enable the `--verbose` flag of `pg_prove`, which prints query output to stdout

As a hypothetical example, I have a function called `select_foo` which is an RPC endpoint called by users to toggle a "selected" flag and perform some other work (kick off a background job or send a notification or whatever). I want to use pgtap to test that this function works correctly. Make the following files:

```sql
-- seed.sql
drop table if exists foo;
create table foo (
  label text primary key,
  selected boolean default false
);
insert into foo (label) values ('hello'), ('world');

create or replace function select_foo(label text)
returns void
language plpgsql
as $$
begin
  update foo set selected = true where select_foo.label = foo.label;
  -- Function might update or notify something else here
end;
$$;
```

```sql
-- test.sql
create extension if not exists pgtap with schema extensions;

begin;
select plan(1);

-- Intentional typo in following line (helIo instead of hello)
select 'helIo' as target_label \gset

select select_foo(:'target_label');
select results_eq(
  format($$ select selected from foo where label = %L $$, :'target_label'),
  array[true]
);

select * from finish();
rollback;
```

Seed a database and run the tests with the below commands (I'm using pg_prove directly instead of the supabase CLI so it's easy to show what pg_prove's verbose flag does):

```bash
docker network create pg-test-example
# In one shell
docker run --rm --network=pg-test-example --name=pg-test-example-postgres \
    -v $(pwd)/seed.sql:/docker-entrypoint-initdb.d/seed.sql \
    -e POSTGRES_PASSWORD=password supabase/postgres:15.1.0.129

# In another shell
docker run --rm --network=pg-test-example --name=pg-test-example-pgprove \
    -v $(pwd)/test.sql:/test.sql -e PGPASSWORD=password \
    itheory/pg_prove:3.35 --user=postgres --host=pg-test-example-postgres /test.sql
```

The last command will display output like:

```
psql:/test.sql:1: NOTICE:  extension "pgtap" already exists, skipping
/test.sql .. 
# Failed test 1
#     Results differ beginning at row 1:
#         have: NULL
#         want: (t)
# Looks like you failed 1 test of 1
Failed 1/1 subtests 

Test Summary Report
-------------------
/test.sql (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: FAIL
```

Assuming you don't immediately see the typo, how do you go about debugging this? This is a simple example, but in more complex scenarios, something like this can be time-consuming and difficult to debug and you can't figure it out via visual inspection.

A debugger would be ideal, but it seems like [the ones that exist require custom libraries or extensions](https://stackoverflow.com/questions/20190406/how-to-debug-postgresql-stored-procedures). It's not my focus in this issue, but making a debugger easy and available in supabase might be nice!

The next option is debugging via printing/logging, but this is also challenging. It takes time and research to figure out things like:
- Printing with `raise notice` doesn't appear anywhere unless you add the `--debug` flag to the `supabase test db` command
- You can get log statements to appear in the server log by using `raise log` instead of `raise notice` (though `raise notice` is more frequently used in code snippets around the internet, I think)
    - Perhaps this is improved (I'm on an old version of the supabase CLI currently), but the postgres logs disconnect frequently, e.g. every time I run `supabase db reset`. I currently view the postgres logs with `docker logs -f supabase_db_<folder_name>`. I think you can see these in the local studio web frontend nowadays?
- The `raise` statement only works in plpgsql -- there's nothing similar that you can use in plain sql

Some of the above might be mistaken or only true in certain circumstances or on certain versions, in which case, please correct me on them! But regardless, I think that misunderstandings and caveats in the above just underscores the difficulty of figuring these things out.

One approach that I have stumbled upon for debugging the above is described here (https://stackoverflow.com/questions/23729752/raise-notice-to-print-a-tables-data). Essentially, you jam whatever data you want into a json string/array and log that.

```sql
-- Add this line to the select_foo function in seed.sql
raise log '%', ((select array_to_json(array_agg(foo)) from foo))

-- Or, add these lines to test.sql
do $$
begin
  raise log '%', ((select array_to_json(array_agg(foo)) from foo));
end$$;
```

Now, the output of `supabase test db` will still be the same, but the postgres server logs will contain lines like:

```
<date> postgres@postgres LOG:  [{"label":"hello","selected":false},{"label":"world","selected":false}]
<date> postgres@postgres CONTEXT:  PL/pgSQL function select_foo(text) line 3 at RAISE
<date> postgres@postgres STATEMENT:  select select_foo('helIo');
```

From here, you might find the typo or need to add more queries or maybe a plpgsql loop or maybe you add a `foo.label = select_foo.label` column to that json/array log expression. Or you give up and load your test seed data into your database outside the testing environment and play around with it interactively in psql, running queries and functions line-by-line til you figure it out. Either way, it's not a quick and easy thing.

I think my two suggestions above (repeated below) could help.
1. Show `pg_prove` output from the `supabase test db` command by default (rather than requiring the `--debug` flag)
    - This means that `raise notice` lines will appear directly in the command output, which is easier than finding `raise log` statements in the postgres container logs.
2. Let users optionally enable the `--verbose` flag of `pg_prove`, which prints query output to stdout
    - This means you can put lines like `select *, :'target_label' as target_label, label = :'target_label' as label_matches from foo;` in test.sql (along with psql formatting commands like `\t off` and `\pset format aligned`) to get more helpful output like the below, which should make it faster/easier to track down bugs.
        ```
        psql:/test.sql:1: NOTICE:  extension "pgtap" already exists, skipping
        /test.sql ..
        1..1
         label | selected | target_label | label_matches
        -------+----------+--------------+---------------
         hello | f        | helIo        | f
         world | f        | helIo        | f
        (2 rows)
        not ok 1
        # Failed test 1
        #     Results differ beginning at row 1:
        #         have: NULL
        #         want: (t)
        # Looks like you failed 1 test of 1
        Failed 1/1 subtests

        Test Summary Report
        -------------------
        /test.sql (Wstat: 0 Tests: 1 Failed: 1)
          Failed test:  1
        Files=1, Tests=1,  0 wallclock secs ( 0.01 usr +  0.01 sys =  0.02 CPU)
        Result: FAIL
        ```

**Describe alternatives you've considered**

- Running tests without the supabase CLI, i.e. with `pg_prove` directly
- Just using the `select array_to_json(array_agg(...` approach

**Additional context**

I'm open to other ideas and corrections to any of the above! Perhaps there should be a debugging tips and tricks github discussion or section of the supabase docs.

I'm currently on Supabase CLI 1.49.4 (released 2023 Apr 6), but it doesn't look like [the pg_prove invocation or output](https://github.com/supabase/cli/blob/main/internal/db/test/templates/test.sh#L32) has changed significantly since then.

**Comment by sweatybridge** [comment]
Hello @grschafer, thanks for the detailed suggestions. We have implemented the following improvements to the latest cli release.

1. show pg_prove output by default, ie. notice messages now show up on stderr
2. when `--debug` flag is enabled, we pass `--verbose` flag to pg_prove

Let me know if these improvements are sufficient for your debugging or if you have other suggestions to improve debuggability of pgtap tests.

**Comment by grschafer** [comment]
Awesome -- thanks for looking into this! I won't get a chance to test the new version for a few days at least, but I think the changes you made take care of the concerns I had when opening this issue, so I'll close it!
