### ISSUE TITLE
gotrue docker image stuck on v2.74.2

### ISSUE THREAD

**Issue by chatch** [supabase/cli#1609]
**Describe the bug**
Using this cli to start supabase locally the gotrue docker container is running from image v2.72.2 which was released back in June.

As far as i can see it should be using v2.99.0 (main and latest release): https://github.com/supabase/cli/blob/v1.106.1/internal/utils/misc.go

And the hosted version is on 2.104.2 so the local one is lagging behind quite a bit.

**To Reproduce**
1. `supabase start`
2. `docker ps | grep true`

**Expected behavior**
Ideally the latest version used in the cloud environment (as I'm seeing some differences and am testing to rule out an issue is because of different versions of the software).

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser (if applicable)": N/A
 - Version of CLI: 1.106.1 (latest at time of writing)
 - Version of supabase-js (if applicable): N/A
 - Version of Node.js (if applicable): N/A (installed cli with brew not npm)

**Additional context**

**Comment by sweatybridge** [comment]
Could you try deleting `supabase/.temp/gotrue-version` file? It should reset the local gotrue version to the default v2.99.0.

If you want to match local gotrue version to that of your remote project, you can also use relink your project with `supabase link --project-ref <ref>`. That will save your remote project's gotrue version to `supabase/.temp/gotrue-version`.

**Comment by chatch** [comment]
ah! nice one @sweatybridge . that's got it :+1: 

good to know about the (re)link-ing too. i will give that try soon also.
