### ISSUE TITLE
supabase db pull is not applied on storage schema

### ISSUE THREAD

**Issue by bhy** [supabase/cli#1623]
**Describe the bug**
The doc in `supabase db pull` says:

> -s, --schema strings    Comma separated list of schema to include. (default all)

However the "all" here seems not including `storage`.

**To Reproduce**
1. Have a database that contain storage security policies.
2. run `supabase db pull` to pull the remote migrations. 
3. the result migration scripts does not contain storage  security policies.
4. manually run `db pull --schema storage` can pull these security policies.

**Expected behavior**
`supabase db pull` should include all schemas as the doc specified.

**Comment by ivanmaxlogiudice** [comment]
not including auth too

**Comment by sweatybridge** [comment]
I've updated db pull to suggest diffing storage schema separately. This is inline with our documentation https://supabase.com/docs/guides/cli/local-development#sync-storage-buckets
