### ISSUE TITLE
PostgREST labeled "service not healthy" when OpenAPI disabled or anon lacks privileges

### ISSUE THREAD

**Issue by grschafer** [supabase/cli#1637]
**Describe the bug**

Even though the PostgREST service comes up successfully, `supabase start` can exit with a `service not healthy: [supabase_rest_project]"` error when the request to `/rest/v1/` returns a non-200 response. This endpoint can return a non-200 response in different ways, for example:
- if the [postgrest config is `openapi-mode=disabled`](https://postgrest.org/en/stable/references/configuration.html#openapi-mode) which returns a 404 response
- if [postgrest is configured with a db-pre-request function](https://postgrest.org/en/stable/references/configuration.html#db-pre-request) that the anon role has insufficient privileges to run, returning a 401 response

**To Reproduce**
Run the following to set up a new supabase project

```bash
git init supabase-rest-healthcheck-failure
cd supabase-rest-healthcheck-failure/
supabase init
supabase migration new disable_openapi
```

Replace the content of the `disable_openapi` migration with the following:

```sql
alter role authenticator set pgrst.openapi_mode to 'disabled';
notify pgrst, 'reload config';
```

Start the project, which will look like the following:

```bash
$ supabase start
Starting database...
Setting up initial schema...
Applying migration 20231106193529_disable_openapi.sql...
Seeding data supabase/seed.sql...
Starting containers...
Setting up Edge Functions runtime...
Waiting for health checks...
supabase_rest_supabase-rest-healthcheck-failure container logs:
06/Nov/2023:19:50:25 +0000: Starting PostgREST 11.2.0...
06/Nov/2023:19:50:25 +0000: Attempting to connect to the database...
06/Nov/2023:19:50:25 +0000: Connection successful
06/Nov/2023:19:50:25 +0000: Listening on port 3000
06/Nov/2023:19:50:25 +0000: Config reloaded
06/Nov/2023:19:50:25 +0000: Listening for notifications on the pgrst channel
06/Nov/2023:19:50:25 +0000: Schema cache loaded
06/Nov/2023:19:50:25 +0000: Starting PostgREST 11.2.0...
06/Nov/2023:19:50:25 +0000: Attempting to connect to the database...
06/Nov/2023:19:50:25 +0000: Connection successful
06/Nov/2023:19:50:25 +0000: Config reloaded
06/Nov/2023:19:50:25 +0000: Schema cache loaded
06/Nov/2023:19:50:25 +0000: Starting PostgREST 11.2.0...
06/Nov/2023:19:50:25 +0000: Attempting to connect to the database...
06/Nov/2023:19:50:25 +0000: Connection successful
06/Nov/2023:19:50:25 +0000: Config reloaded
06/Nov/2023:19:50:25 +0000: Schema cache loaded
service not healthy: [supabase_rest_supabase-rest-healthcheck-failure]
Try rerunning the command with --debug to troubleshoot the error.
```

The logs for the `supabase_rest_*` container will look like:

```
172.24.0.1 - - [06/Nov/2023:19:47:42 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:43 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:44 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:45 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:46 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:47 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:48 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
172.24.0.1 - - [06/Nov/2023:19:47:49 +0000] "HEAD /rest/v1/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1"
...
```

**Expected behavior**

The health-check for the PostgREST service shouldn't rely on the user's postgrest config or the structure of their database privileges.

**Suggested solution**

Instead of making a request to `/rest/v1/` and [expecting a 200 response](https://github.com/supabase/cli/blob/c355dc131d5edc189b23a23c84444b33a5e30809/internal/status/status.go#L120), the supabase CLI should make a request to [PostgREST's health-check endpoint](https://postgrest.org/en/stable/references/admin.html#health-check), which has been available [since postgrest 10](https://github.com/PostgREST/postgrest/releases/tag/v10.0.0).

This also means that [the admin-server-port](https://postgrest.org/en/stable/references/configuration.html#admin-server-port) will need to be configured and exposed by the docker container.

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.03 LTS
- Version of CLI: 1.110.1
- Postgres docker image: public.ecr.aws/supabase/postgres:15.1.0.117
- PostgREST docker image: public.ecr.aws/supabase/postgrest:v11.2.0

**Additional context**

I originally discovered this issue because I use a `db-pre-request` function that declares a plpgsql variable with a custom type in a schema that `anon` didn't have a usage grant for (and I would prefer not to grant anon usage on that schema).

**Comment by sweatybridge** [comment]
Thanks for the detailed report and suggestion. I've updated the health check for postgrest to use admin endpoint.
