### ISSUE TITLE
Ability to expose additional schemas on the API server

### ISSUE THREAD

**Issue by osaxma** [supabase/cli#164]
# Feature request

## Is your feature request related to a problem? Please describe.

I can't expose schemas on the API server using the dashboard (and I'm not aware of other means). 

## Describe the solution you'd like

The same solution as the the hosted version where one can expose additional schemas on the API server using the dashboard as described here:

> By default the API server points to the `public` schema. You can enable other database schemas within the Dashboard. Go to `Settings > API > Schema` and add the schema which you want to expose to the API.
> source: https://supabase.com/docs/reference/javascript/initializing#api-schemas

## Describe alternatives you've considered

I tried following the PostgREST docs to update the schemas but it looks like there aren't any `pgrst` configs as part of the database.

**Comment by steinroe** [comment]
Did you find any workaround other than using public schema?

**Comment by soedirgo** [comment]
I've made an update on the config in https://github.com/supabase/cli/pull/172 that exposes this setting. PR still needs some sanity checks, but the `api.schemas` setting should work.
