### ISSUE TITLE
supabase destroy

### ISSUE THREAD

**Issue by landsman** [supabase/cli#1641]
I'm facing some kind of bug when the database won't start after I reinstall the project on localhost (removed dir, new git clone). 

The fastest thing for me would be to type something like: `supabase destroy` which will remove all local data related to the studio. So basically reinstall. Or the terminal can just print me a tutorial on how to do it manually. No need to search in doc, github etc. 

I'm aware of db reset command, but it do not help when containers not running.
```
supabase db reset
supabase start is not running.
```

**Comment by sweatybridge** [comment]
Have you tried `supabase stop --no-backup`? We can consider adding a log message if that solves your problem

**Comment by landsman** [comment]
> Have you tried `supabase stop --no-backup`? We can consider adding a log message if that solves your problem

Does it work when there are no containers running? I basically just want to know docker volume paths and remove them.

**Comment by sweatybridge** [comment]
Yes the command tries to remove volumes and containers even if they are not started.

**Comment by landsman** [comment]
nice, thanks!
