### ISSUE TITLE
Supabase Start Error Requested image not found

### ISSUE THREAD

**Issue by sjmiddlebrook** [supabase/cli#1644]
**Describe the bug**
I tried to run npx supabase start after running npx supabase init and npx supabase link --project-ref <project-id> 
I get the following error from the CLI: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.20 not found: manifest unknown: Requested image not found

**To Reproduce**
npx supabase init
npx supabase link --project-ref <project-id>
npx supabase start
error message: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.20 not found: manifest unknown: Requested image not found

**Expected behavior**
Supabase starts locally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - macbook m1
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI [e.g. v1.60.0] - 1.110.1
 - Version of supabase-js (if applicable) [e.g. v2.22.0]
 - Version of Node.js (if applicable) [e.g. v16.20.0] - v18.18.0
 - Docker version - 24.0.6

**Additional context**
I checked another issue that mentioned possibly a version issue between 14 and 15. When I run SELECT VERSION() in supabase SQL editor I see 'PostgreSQL 15.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit' and the major_version in my config.toml is 15.

**Comment by sweatybridge** [comment]
Seems like there are a few versions of pg15 that we don't support as well. You can work around this by removing the file `supabase/.temp/postgres-version` which is created by supabase link.

**Comment by sjmiddlebrook** [comment]
That worked. Thanks for the help!
