### ISSUE TITLE
Migration with serial data type fails

### ISSUE THREAD

**Issue by teemu-kemppainen** [supabase/cli#165]
# Bug report

## Describe the bug

Supabase CLI created migration fails if table uses `serial` data type.

## To Reproduce

1. Open the SQL editor and run:

```
create table if not exists public.my_table (
  id serial primary key,
  creator uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamp with time zone not null default now(),
  content text not null
);
```
2. Run `supabase db commit test_serial`
3. Run `supabase db reset`
4. Get the error

```
Error: Error resetting database: ERROR:  relation "my_table_id_seq" does not exist
LINE 8:     id integer NOT NULL DEFAULT nextval('my_table_id_seq'::r...
```

The resulting migration is as follows:
```
CREATE TABLE IF NOT EXISTS public.my_table
(
    id integer NOT NULL DEFAULT nextval('my_table_id_seq'::regclass),
    creator uuid DEFAULT auth.uid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    content text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT my_table_pkey PRIMARY KEY (id),
    CONSTRAINT my_table_creator_fkey FOREIGN KEY (creator)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.my_table
    OWNER to postgres;

GRANT ALL ON TABLE public.my_table TO anon;

GRANT ALL ON TABLE public.my_table TO authenticated;

GRANT ALL ON TABLE public.my_table TO postgres;

GRANT ALL ON TABLE public.my_table TO service_role;
```

## Expected behavior

The migration would work.

## System information

- supabase --version: 0.16.1
- Ubuntu 21.10

## Additional context

Manually modifying the migration to

```
CREATE SEQUENCE my_table_id_seq AS integer; -- ADD THIS
CREATE TABLE IF NOT EXISTS public.my_table
(
    id integer NOT NULL DEFAULT nextval('my_table_id_seq'::regclass),
    creator uuid DEFAULT auth.uid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    content text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT my_table_pkey PRIMARY KEY (id),
    CONSTRAINT my_table_creator_fkey FOREIGN KEY (creator)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

ALTER SEQUENCE my_table_id_seq OWNED BY my_table.id; -- ADD THIS

ALTER TABLE IF EXISTS public.my_table
    OWNER to postgres;

GRANT ALL ON TABLE public.my_table TO anon;

GRANT ALL ON TABLE public.my_table TO authenticated;

GRANT ALL ON TABLE public.my_table TO postgres;

GRANT ALL ON TABLE public.my_table TO service_role;
```
makes it work.

This modification is based on Postgres [documentation](https://www.postgresql.org/docs/current/datatype-numeric.html):
>The data types smallserial, serial and bigserial are not true types, but merely a notational convenience for creating unique identifier columns (similar to the AUTO_INCREMENT property supported by some other databases). In the current implementation, specifying:
>```
>CREATE TABLE tablename (
>    colname SERIAL
>);
>```
>is equivalent to specifying:
>```
>CREATE SEQUENCE tablename_colname_seq AS integer;
>CREATE TABLE tablename (
>    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
>);
>ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
>```

I also see there's a difference in the migration create table as it uses 
```
...
id integer NOT NULL DEFAULT nextval('my_table_id_seq'::regclass),
...
```
whereas Postgres documentation uses 
```
...
colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
...
```
but I am not very skilled at Postgres.

**Comment by soedirgo** [comment]
Thanks @teemu-kemppainen - this is a limitation of the schema diff tool, we can't fix it on the CLI side. Unfortunately the only way to handle this is to manually review each autogenerated diff.

For this specific issue though, you might want to consider using [identity columns](https://stackoverflow.com/questions/55300370/postgresql-serial-vs-identity) instead, which should work without error.
