### ISSUE TITLE
`supabase start` Error: Failed to connect to Docker daemon. Is Docker running?

### ISSUE THREAD

**Issue by nvme0** [supabase/cli#167]
# Bug report

## Describe the bug

Recently updated to supabase 0.17.0, and when running `supabase start` I get the following error message:

```bash
Error: Failed to connect to Docker daemon. Is Docker running?
```

Using the npm package (0.5.0) I have no issues running `supabase start`. 

edit: It starts fine when running as a super user

## System information

- OS: Linux
- Version of Node.js: v14.17.1

**Comment by t-eckert** [comment]
If it starts fine when running as a super user, you almost certainly have the Docker daemon running. Two things you can consider

- Update your Docker engine to a version >19 which is able to run rootless.
- Add your user with root privileges to the Docker group: `sudo usermod -aG docker $USER`.

[Reference](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo)

[Docker Engine Release Notes](https://docs.docker.com/engine/release-notes/)

**Comment by nvme0** [comment]
Hey @t-eckert, thanks for the suggestion.

I have already added my user with root privileges to the Docker group, as you can see I can run docker commands but not supabase commands.

![Screenshot_2022-02-09_21-01-15](https://user-images.githubusercontent.com/53546898/153185315-8d38b3d9-d5a1-4d07-b8dd-92908f8ec7dd.png)

Seems to be an issue with my setup, as it runs fine in the ci

**Comment by nvme0** [comment]
@osaxma Thanks for the suggestion, I am running on Linux

**Comment by soedirgo** [comment]
What are the permissions for your `docker` binary? In my Linux box it's `-r-xr-xr-x root root`, which might explain why it runs w/ the old Node CLI (it just runs the `docker` binary) but requires superuser for the Go CLI.

**Comment by haydn** [comment]
I'm hitting this error trying to run the CLI in [a Vercel build step](https://vercel.com/docs/concepts/deployments/build-step).

This is the "Install Command" I'm running: 

```
amazon-linux-extras install -y docker && systemctl enable docker && yum install -y https://github.com/supabase/cli/releases/download/v0.24.5/supabase_0.24.5_linux_amd64.rpm && yarn install
```

That command runs fine, but when I try to commit the database migrations:

```
supabase db remote set $POSTGRES_URL && supabase db remote commit
```

I get Docker daemon error message:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I can replicate this on my local (macOS) machine using [the same build image Vercel uses](https://vercel.com/docs/concepts/deployments/build-step#build-image):

```
$ docker run --rm -it amazonlinux:2.0.20191217.0 sh
sh-4.2# amazon-linux-extras install -y docker && systemctl enable docker && yum install -y https://github.com/supabase/cli/releases/download/v0.24.5/supabase_0.24.5_linux_amd64.rpm
sh-4.2# supabase init
sh-4.2# supabase start
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:26
  in github.com/supabase/cli/internal/start.Run:35
```

Unhelpfully, the AWS documentation [mentions you might need to reboot an EC2 instance to fix Docker permission issues](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html) after installing:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/27211/163762439-99cf11b7-b210-4b03-b1ac-ff6d0c6f8a07.png">

Is there something really obvious I've missed here or any thoughts on how to work around this? I'm trying to keep the whole setup as simple as possible, but it's looking like I might need to get some other infrastructure involved to run the migrations (maybe GitHub Actions?).

**Comment by soedirgo** [comment]
@haydn not familiar with Vercel, but are you able to run Docker containers in a Vercel build step? Same thing for the local repro.

**Comment by soedirgo** [comment]
Just tested the local repro myself, I worked when I did `docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock amazonlinux:2.0.20191217.0 sh`.

**Comment by haydn** [comment]
@soedirgo Thanks for the quick reply!

> are you able to run Docker containers in a Vercel build step?

Nope, Vercel runs the Docker containers. All that is configurable are some commands to run within them:

![image](https://user-images.githubusercontent.com/27211/163767156-b6ac2218-d8a3-4585-a243-f101f0b1d47d.png)

**Comment by soedirgo** [comment]
Can you check if you can run e.g. `docker run hello-world` in the build step?

**Comment by haydn** [comment]
Sorry, I probably should've included that in my first comment.

Just running `docker info` yields the same error:

```
sh-4.2# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by antonigiske** [comment]
I have the same issue. ´docker ps´ and all other commands. Docker Desktop is running also. I've tried to restart both computer and docker multiple times to no avail. Any tips are welcome.

### System information
OS: Mac 12.6
Version of Node.js: v16.13.0
Supabase CLI: 1.11.0
Docker: 20.10.20, build 9fdeb9c

**Comment by antonigiske** [comment]
This was using latest Docker Desktop. After reading the release notes I noticed this on 4.13.0:

`By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead.`

https://github.com/docker/for-mac/issues/6529

It worked for me after downgrading.

**Comment by cravelight** [comment]
I just went ahead and created the symbolic link and it worked for me. I'm upgrading to a new machine next week anyway, so this one will be wiped. :)

`ln -s /users/me/.docker/run/docker.sock /var/run/docker.sock`

I had to sudo it.

**Comment by soedirgo** [comment]
You can also use the `DOCKER_HOST` env for now (in `~/.bashrc`, etc.) until this is fixed upstream:

```sh
DOCKER_HOST=unix:///Users/me/.docker/run/docker.sock supabase start
```

**Comment by sweatybridge** [comment]
Closing this as won't fix because docker is a prerequisite for using the CLI.

**Comment by amireldor** [comment]
This is a future reference to myself. On Linux, I did something like this (I use Docker Desktop):

```
export DOCKER_HOST=unix:///home/amir/.docker/desktop/docker.sock
```

**Comment by techandmedia** [comment]
> Closing this as won't fix because docker is a prerequisite for using the CLI.

There's no mention in the doc that docker is prerequisite; can you add it there as I lost hours trying to generate types and the doc just mention to run the command. I thought my connection is bad

**Comment by sweatybridge** [comment]
@techandmedia could you post your error logs here? Generating types for a hosted project does not require docker https://supabase.com/docs/guides/api/generating-types.

This issue is related to [local development](https://supabase.com/docs/guides/resources/supabase-cli/local-development) which we have documented that docker is a prerequisite.

**Comment by techandmedia** [comment]
@sweatybridge
This is how I run gen type
```bash
$ npx supabase login
$ npx supabase gen types typescript --db-url postgresql://postgres:mypassword@db.myconnection.supabase.co:5432/ppostgres
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Connecting to postgresql://postgres:mypassword@db.myconnection.supabase.co:5432/postgres
Error: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdockker_engine/v1.24/images/public.ecr.aws/supabase/postgres-meta:v0.58.0/json": open //./pipe/docker_engine: The system cannot fnind the file specified.
Try rerunning the command with --debug to troubleshoot the error.
error Command failed with exit code 1.
```

**Comment by sweatybridge** [comment]
The `--db-url` flag is mostly used for self-hosted setup. For platform projects, we suggest using `--project-id` flag as documented.

```bash
npx supabase login
npx supabase gen types typescript --project-id myconnection --schema public > types/supabase.ts
```

I will update the cli reference docs to make this distinction clearer.

**Comment by techandmedia** [comment]
Hi @sweatybridge thank you for your reply, but I still got error, though it's different

```bash
$ npx supabase gen types typescript --project-id connection --schema public > types/supabase.ts
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Error: failed to retrieve generated types: {"message":"Forbidden resource"}
Try rerunning the command with --debug to troubleshoot the error.
error Command failed with exit code 1.
```

**Comment by sweatybridge** [comment]
Have you replaced `connection` with your actual `project-id`?

**Comment by techandmedia** [comment]
Hi @sweatybridge 
Like this right? I am the only one who has access to this project and create the project
```bash
npx supabase gen types typescript --project-id postgresql://postgres:passwprd@db.connection.supabase.co:5432/postgres --schema public > types/supabase.ts
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Error: failed to retrieve generated types: {"message":"Forbidden resource"}
Try rerunning the command with --debug to troubleshoot the error.
error Command failed with exit code 1.
```
Where can I see this in the dashboard?
`has read permission to your project`

Also if you are free, can you have a look of this discussion raised by me as well? Thanks
https://github.com/supabase/supabase/discussions/11784

**Comment by sweatybridge** [comment]
Your project id is part of the url you use to access supabase.com: https://app.supabase.com/project/<project-id>

Alternatively use `supabase projects list` to find it. Please open a separate issue if the error still exists. As explained before, this thread is meant for self-hosted only.

**Comment by techandmedia** [comment]
Ah ok got, it works now, thanks @sweatybridge

**Comment by selbyk** [comment]
> export DOCKER_HOST=unix:///home/amir/.docker/desktop/docker.sock

Took me longer than I care to admit to realize I needed 3 `/`'s

**Comment by abuuzayr** [comment]
if you are using [colima](https://github.com/abiosoft/colima) do this instead

`DOCKER_HOST=unix:///$HOME/.colima/docker.sock supabase start`

or of course add it to your `.bashrc` / `.zshrc`

**Comment by mlynch** [comment]
> Closing this as won't fix because docker is a prerequisite for using the CLI.

@sweatybridge is Docker a prerequisite for following the [Managing Environments](https://supabase.com/docs/guides/cli/managing-environments) guide? Because I'm also getting this issue and I don't see Docker mentioned on that page. That page is linked to in a few places and skips the Local Development guide so it's understandable that Docker might not be installed if you've previously only been using the supabase.com dashboard. Going to install it and hope it fixes it though.

**Comment by sweatybridge** [comment]
Hi @mlynch, thanks for spotting this inconsistency in our guides. Yes, docker is indeed a prerequisite for managing environments. I've opened a PR to update the docs.

**Comment by raveesh-me** [comment]
https://eshlox.net/2023/02/26/supabase-cli-cannot-connect-to-the-docker-daemon/

**Comment by jojule** [comment]
On MacOS, this fixes the situation for me:
`export DOCKER_HOST=unix:///$HOME/.docker/run/docker.sock`

**Comment by yaronguez** [comment]
Curious, why is this issue resolved? Isn't this a bug with supabase? At the very least, I'd assume that supabase should update [the docs](https://supabase.com/docs/guides/getting-started/local-development) on local development to save everyone from having to search for a fix on this thread.

**Comment by sweatybridge** [comment]
We closed this issue because it is specific to user's docker installation. Since [Docker Desktop 4.14.0](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-enhancements-11), the socket file `/var/run/docker.sock` has been added back to default installation options. If you installed docker without letting it [create symlinks](https://github.com/supabase/cli/issues/167#issuecomment-1537351179) to finish the default setup, not only supabase but other programs that docker-py would also not work.

Hence, I don't consider this a bug specific to the CLI. But I go ahead and document the `DOCKER_HOST` workaround in our troubleshooting guide.

**Comment by PhE** [comment]
> I just went ahead and created the symbolic link and it worked for me. I'm upgrading to a new machine next week anyway, so this one will be wiped. :)
> 
> `ln -s /users/me/.docker/run/docker.sock /var/run/docker.sock`
> 
> I had to sudo it.

`sudo ln -s ~/.docker/desktop/docker.sock  /var/run/docker.sock`

**Comment by yaronguez** [comment]
> We closed this issue because it is specific to user's docker installation. Since [Docker Desktop 4.14.0](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-enhancements-11), the socket file `/var/run/docker.sock` has been added back to default installation options. If you installed docker without letting it [create symlinks](https://github.com/supabase/cli/issues/167#issuecomment-1537351179) to finish the default setup, not only supabase but other programs like docker-py would also not work.
> 
> Hence, I don't consider this a bug specific to the CLI. But I will go ahead and document the `DOCKER_HOST` workaround in our troubleshooting guide.

Thanks! I encountered this problem after installing Docker Desktop for macOS version 4.20.0 and I did not do anything special during the installation or deny it any requested access.

**Comment by bertvh** [comment]
FYI: I just installed 4.20.1 for Mac and had to check a box in settings after installation to enable this.

![Screenshot 2023-06-26 at 09 59 01 Medium](https://github.com/supabase/cli/assets/941577/b9145d69-934e-42a7-9f16-b68c81c81822)

**Comment by dbustosp** [comment]
> You can also use the `DOCKER_HOST` env for now (in `~/.bashrc`, etc.) until this is fixed upstream:
> 
> ```shell
> DOCKER_HOST=unix:///Users/me/.docker/run/docker.sock supabase start
> ```

Thank you! This worked for me!

**Comment by chrisciszak** [comment]
> FYI: I just installed 4.20.1 for Mac and had to check a box in settings after installation to enable this.
> 
> ![Screenshot 2023-06-26 at 09 59 01 Medium](https://user-images.githubusercontent.com/941577/248726781-b9145d69-934e-42a7-9f16-b68c81c81822.jpeg)

This fixed it on my MacOS

**Comment by davidshq** [comment]
> We closed this issue because it is specific to user's docker installation. Since [Docker Desktop 4.14.0](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-enhancements-11), the socket file `/var/run/docker.sock` has been added back to default installation options. If you installed docker without letting it [create symlinks](https://github.com/supabase/cli/issues/167#issuecomment-1537351179) to finish the default setup, not only supabase but other programs like docker-py would also not work.
> 
> Hence, I don't consider this a bug specific to the CLI. But I will go ahead and document the `DOCKER_HOST` workaround in our troubleshooting guide.

I'm running 4.44.3 on Ubuntu and seeing this problem.
