### ISSUE TITLE
supabase db dump does not include entries from supabase_migrations

### ISSUE THREAD

**Issue by eythorhel19** [supabase/cli#1671]
**Describe the bug**
When I am storing a backup using `supabase db dump --db-url <db_url> -f "./data.sql" --use-copy --data-only` then it does not include the entries from supabase_migrations.supabase_migrations table. It is like it completely skips that schema. This is an issue since when I restore the database and the next time I am going to push an added migration to the database it starts from the first migration and fails. I tried using the -s parameter and inserted supabase_migrations and then I get the correct data, but it is not ideal to have to specify all schemas (if you would for example add one) and also as it says in the help for that command that the default is to include all schemas.

**To Reproduce**
1. Run `supabase db dump --db-url <db_url> -f "./data.sql" --use-copy --data-only`
2. Restore the database using `psql --single-transaction --variable "ON_ERROR_STOP=1" --file roles.sql --file schema.sql --command "SET session_replication_role = 'replica';" --file data.sql --dbname <db_url>`
3. Try pushing new migration and painfully realize that the migration history is none existant.

**Expected behavior**
supabase db dump includes the supabase_migrations schema when the -s parameter is not set.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS Ventura 13.2]
 - Version of CLI [e.g. v1.112.0]
 - Version of supabase-js (if applicable) [e.g. v2.4.1]

**Comment by d9k** [comment]
Yes, I have to run migrations dump separately too:

```
supabase db dump --data-only --schema supabase_migrations > ./supabase/dump-migrations.sql
```
