### ISSUE TITLE
Latest stable release (1.112.0) adds a test_tenant table which breaks schema check tests

### ISSUE THREAD

**Issue by KirioXX** [supabase/cli#1677]
**Describe the bug**
The latest version (1.112.0) is creating a test_tenant table, I'm not sure if that is intended or not.
With this table it breaks our schema tests.

**To Reproduce**
1. start up a local env
2. check the tables in the public schema
3. Observe the tet_tenant table

**Expected behavior**
No table on start up

**Screenshots**
<img width="839" alt="Screenshot 2023-11-20 at 16 14 12" src="https://github.com/supabase/cli/assets/11646702/63e9405a-0ade-4c56-95a1-9dffc130172e">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI: 1.112.0

**Additional context**

**Comment by sweatybridge** [comment]
This should be fixed in latest stable release.
