### ISSUE TITLE
`supabase db remote commit` fails with error `Error: ERROR: prepared statement "lrupsc_1_0" already exists (SQLSTATE 42P05)`

### ISSUE THREAD

**Issue by t-eckert** [supabase/cli#168]
# Bug report

## Describe the bug

When creating a local copy of my Supabase project, I get an error about a prepared statement already existing and the clone fails.

## To Reproduce

I am trying to "clone" my Supabase project locally for [this app](https://github.com/t-eckert/gradienthub). In the `frontend` directory, run `supabase init`. The process completes with the message `Finished supabase init`.

I then run `supabase db remote set 'postgresql://postgres:<your_password>@db.<your_project_ref>.supabase.co:5432/postgres'` with my details added. This successfully completes with the message `Finished supabase db remote set`.

I then run `supabase db remote commit`. The loading indicator runs for a moment, then I get the error response `Error: ERROR: prepared statement "lrupsc_1_0" already exists (SQLSTATE 42P05)`.

## Expected behavior

When running `supabase db remote commit`, I should get a local representation of my remote Supabase project.

## System information

- OS: Windows, but running WSL2 using Ubuntu 20.04.3
- Version of supabase CLI: 0.17.0 (Installed using brew)

## Additional context

I was able to find [this similar issue](https://github.com/jackc/pgx/issues/602) but I wasn't able to find anything actionable on my end.

**Comment by soedirgo** [comment]
Just to confirm, are you using direct connection (`postgresql://...:5432/postgres`) instead of PgBouncer (`postgresql://...:6543/postgres`)?

**Comment by t-eckert** [comment]
Oh shoot. I bet that's it. I was using `6543`/PgBouncer. I made the mistake of not copying that correctly when I was recreating what I typed in the terminal (so that I didn't enter my DB password). Using `5432` worked as intended.

Thank you so much for knowing exactly what the problem was.

**Comment by t-eckert** [comment]
As a follow up, if I were to open a PR to allow a user to set the remote by passing in the database ref and password separately, would you be open to that? I'm thinking `supabase db remote set --host <your_project_ref> --pass <your_password>` which would be interpolated into the correct connection string?

**Comment by soedirgo** [comment]
Sure! Nit: maybe `--password` instead of `--pass`.

**Comment by pencilcheck** [comment]
I tried the ":5432" but it keeps saying dial error connection refused but I can do it when I change it back to 6543
