### ISSUE TITLE
Unable to Perform Write Operations in Supabase Studio

### ISSUE THREAD

**Issue by fernandosmither** [supabase/cli#1682]
**Describe the bug**
I'm unable to Perform Write Operations in Supabase Studio. Eg. Create a new Table, create a column inside a table.

**To Reproduce**
1. Create a new project `supabase init && supabase start`
2. Go to the studio on your web browser (tested multiple with/without extensions) usually on [http://localhost:54323/project/default/editor](http://localhost:54323/project/default/editor)
3. Try to create a table
4. Get a bugged attempt at rendering html inside an alert

**Expected behavior**
The tables to be created, or at least not a bugged dialog

**Screenshots**
![image](https://github.com/supabase/cli/assets/66154723/cc157189-2758-4cc4-8754-8754def72e2c)
![image](https://github.com/supabase/cli/assets/66154723/f7b129da-31d2-49f7-a922-6912283ced31)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS (based on Ubuntu)
 - Browser: Firefox, Chromium without extensions
 - Version of CLI: 1.115.2

**Additional context**
Running on Docker desktop. Containers show no problem at all.

![image](https://github.com/supabase/cli/assets/66154723/2e6435b6-f70b-4bd1-bc99-8c89b79fa193)

At first tried to add a column on an already existing db. Created a project from scratch to replicate thinking it could be a db issue, but the problem persists after a clean install.

**Comment by danielfoxp2** [comment]
I'm facing the same problem, but in version 1.113.2. on windows 11, browsers brave and edge.
Here: https://github.com/supabase/supabase/issues/19117 is another issue reporting the same problem.
