### ISSUE TITLE
Getting error on creating tables on supabase local

### ISSUE THREAD

**Issue by jibin2706** [supabase/cli#1683]
**Describe the bug**
Getting error on create tables / creating policy on supabase local

**To Reproduce**
1. Create a new supabase local project 
2. Open Supabase Studio
3. Create New Table / Add Policy

**Expected behavior**
Queries 

**Screenshots**
<img width="452" alt="Screenshot 2023-11-24 at 00 26 17" src="https://github.com/supabase/cli/assets/28289448/bce70764-da7e-4f9e-9de7-e201965715c1">
<img width="811" alt="Screenshot 2023-11-24 at 00 26 35" src="https://github.com/supabase/cli/assets/28289448/71d5c59b-506d-4cf4-90a2-3eaac868f3ac">

**Desktop (please complete the following information):**
 - Browser (if applicable) Chrome
 - Version of CLI - 1.115.2

**Additional context**
Running the latest beta version

**Comment by leerobert** [comment]
Yeah you gotta downgrade CLI to at least `1.110.3` in my testing. Latest version is breaking in a lot of areas

**Comment by angelxtrme** [comment]
https://github.com/supabase/supabase/issues/19117#issuecomment-1825123611

**Comment by mthuggett** [comment]
I'm on 1.113.2 and have been experiencing similar results when trying edit table column or add columns.  Will downgrade as recommended as I noticed on a separate machine running 1.110.1 all worked fine.
