### ISSUE TITLE
Unable to turn on Realtime for any table

### ISSUE THREAD

**Issue by Angus-Moore-Dev** [supabase/cli#1684]
**Describe the bug**
I am unable to turn on Supabase Realtime for any table. No method of turning on Realtime for any table works.

**To Reproduce**
First method:
1. Go to your local Supabase development window (http://localhost:54321)
2. Click on Tables
3. Select any table you like
4. Click on the button that says 'Realtime off' in the table editor menu bar
5. Select 'Enable Realtime'
6. Now wait forever

Second method:
1. Same as steps 1-3 in the first method
2. Select 'Edit Table'
3. Click 'Enable Realtime' and then save changes
4. You will have a huge error toast appear that is full of HTML

**Expected behavior**
To be told that Realtime has been enabled and things are working as expected.

**Screenshots**
<img width="800" alt="image" src="https://github.com/supabase/cli/assets/99398403/20b1896f-b1fa-4263-a700-1360e6d5adef">
<img width="800" alt="image" src="https://github.com/supabase/cli/assets/99398403/8ddc585b-92a8-465f-b5b8-5a35926dd141">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser: Brave (Chromium)
 - Version of CLI: v1.113.2
 - Version of supabase-js: 2.36.0
 - Version of Node.js (if applicable): v20.5.0

**Additional context**
N/A

**Comment by angelxtrme** [comment]
Downgrade supabase cli to **1.110.3**

**Comment by jason1610** [comment]
@angelxtrme I've been having the exact same html dump as an error for **_every single_** change I try to make in my db. Roll back to 1.110.3 fixed it  thanks
