### ISSUE TITLE
How to signout from CLI

### ISSUE THREAD

**Issue by iammohan01** [supabase/cli#1688]
How can i signout supabse account from cli ?

**Comment by kamilogorek** [comment]
Remove access token from the default keyring of your operating system.
For OSX it's Keychain, for Windows it's "Accessing Credential Manager" and most linux distros have their own "Passwords and Keys" apps. See https://pkg.go.dev/github.com/zalando/go-keyring@v0.2.3#section-readme for implementation details.

If not supported, it fallbacks to `$HOME/.supabase/access-token` file.

**Comment by iammohan01** [comment]
Thanks man, fixed. but why don't we have command like `supabase logout` ?

**Comment by kamilogorek** [comment]
That sounds like a good addition. PRs welcome :)

**Comment by iammohan01** [comment]
@kamilogorek Are we storing anything other tha access token in this diretory `~/.supabase/access-token` ?

**Comment by iammohan01** [comment]
@kamilogorek is there anything contains other than access token in this file `~/.supabase/access-token` ?

Is it safe to delete this file while logout ?

**Comment by kamilogorek** [comment]
Good catch, thanks! Fixed in #1700 

> @kamilogorek is there anything contains other than access token in this file ~/.supabase/access-token ?
> Is it safe to delete this file while logout ?

No, just a token. And in keyring its scoped to a predefined key, so you don't need to do any existence checks if someone calls logout multiple times (other than standard go errors for removing missing file).
