### ISSUE TITLE
start command won't recover from interrupted initialization

### ISSUE THREAD

**Issue by cbzehner** [supabase/cli#17]
# Bug report

## Describe the bug

When `supabase init` is interrupted or otherwise unavailable, the `supabase start` command isn't able to recover and provides a misleading error message.

## To Reproduce
I'm on a 2019 MBP running Big Sur...

1. Turn off Docker globally (you may also need to clear any local Docker images used in Supabase's compose file)
2. Run `supabase init` taking the defaults and you'll end up with "Error running docker-compose."
```bash
❯ supabase init
✔ Port for Supabase URL: · 8000
✔ Port for PostgreSQL database: · 5432
✖ Error running docker-compose.
```
3. Start the Docker daemon again...
4. Try running `supabase init` (again). No-op.
```bash
❯ supabase init
Project already initialized. Remove .supabase to reinitialize.
```
5. Run `supabase start` and see the same error from the `init` command.
```
❯ supabase start
✖ Error running docker-compose.
```

This was solved by `rm -rf .supabase` and re-running `supabase init` but it isn't clear the underlying cause.

## Expected behavior

Ideally `supabase start` would detect initialization had failed and prompt me to re-initialize or `supabase init` should detect a badly configured `.supabase/` directory.

## System information

- OS: macOS
- Version of supabase-cli: 0.3.6
- Version of Node.js: v15.11.0

**Comment by soedirgo** [comment]
Thanks for the report! I'll add proper cleanup for aborted init soon.
