### ISSUE TITLE
Support custom pg-meta, studio, pooler, and realtime images

### ISSUE THREAD

**Issue by S96EA** [supabase/cli#1702]
**Is your feature request related to a problem? Please describe.**
I built a custom [postgres-meta](https://github.com/supabase/postgres-meta) image, and I want to start it using cli command, like `supabase start`, but now the image is written in [code](https://github.com/supabase/cli/blob/main/internal/utils/misc.go).

**Describe the solution you'd like**
Cloud we put the image written in code to config file, like [db image](https://github.com/supabase/cli/blob/c600ca82b7d7219a7da4964ae737394d8d3cee02/internal/start/start.go#L666).

**Comment by S96EA** [comment]
It looks like we can't reach online pgmeta api, when I called `https://my-project-xxx.supabase.co/pg/`, the API returned `no Route matched`, but when I called a local api endpoint `http://127.0.0.1:54321/pg/`, it returned the right output: `{"status":200,"name":"@supabase/postgres-meta","version":"0.0.0-automated","documentation":"https://github.com/supabase/postgres-meta"}`.

**Comment by sweatybridge** [comment]
> It looks like we can't reach online pgmeta api

You are right. It's not open to public directly but some of our platform api routes proxy to pgmeta, like [typegen](https://api.supabase.com/api/v1#/projects/getTypescriptTypes). It will be useful to figure out a way for contributors to test pgmeta.

Could you elaborate on the changes you plan to make to pgmeta? Perhaps there's an alternative way to test it.

**Comment by S96EA** [comment]
I noticed that there is an API in pgmeta that provides the version, I'm wondering if it's possible to read the pgmeta through this API, like we do with [GoTrue](https://github.com/supabase/cli/blob/18198ddf2f4740f9d0d6cf939d80b5157500e449/internal/utils/tenant/gotrue.go#L19). Then  we can save the version of pgmeta in a temporary file.

**Comment by sweatybridge** [comment]
These images are now configurable in cli beta release.

```
echo "v0.81.1" > supabase/.temp/pgmeta-version
npx supabase@beta start
```

**Comment by zoultrex** [comment]
> These images are now configurable in cli beta release.
> 
> ```
> echo "v0.81.1" > supabase/.temp/pgmeta-version
> npx supabase@beta start
> ```

I don't have a live project to link so I could get all the versions, but I do have a colleague that I can look into the docker and get his versions, how do I know the names for each of those? I would never have guessed that postgres-meta has to be referenced as pgmeta


public.ecr.aws/supabase/studio
public.ecr.aws/supabase/postgrest
public.ecr.aws/supabase/storage-api
public.ecr.aws/supabase/gotrue
public.ecr.aws/supabase/realtime
public.ecr.aws/supabase/postgres-meta
public.ecr.aws/supabase/postgres
public.ecr.aws/supabase/edge-runtime
public.ecr.aws/supabase/logflare
public.ecr.aws/supabase/mailpit
public.ecr.aws/supabase/vector
public.ecr.aws/supabase/kong
