### ISSUE TITLE
Notify/auto-sync local service versions with linked project

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1704]
**Is your feature request related to a problem? Please describe.**

Now that one can see the service versions between local and linked projects, it would be great to be notified (or automatically update the local version) when the remote service versions change.

**Describe the solution you'd like**

One can get a CLI prompt notification about a version diff between local and remote, and automatically bump to the new version.

**Describe alternatives you've considered**

Manually having to check the versions and change the config values in the `.temp` folder.

**Comment by sweatybridge** [comment]
I've added the version check to supabase start command in beta release https://github.com/supabase/cli/pull/1843

It will suggest to rerun supabase link if local and remote versions mismatch.
