### ISSUE TITLE
Add column descriptions to generated typescript types docstring

### ISSUE THREAD

**Issue by d9k** [supabase/cli#1713]
There must be fields descriptions (comments)

1) in dumps in form of

```sql
COMMENT ON COLUMN public.authors.birth_town IS 'town of birth (test description)';
```

2) in generated typescript types as docstrings before corresponding field names.

![Selection_2023-12-05_14-34-25](https://github.com/supabase/cli/assets/7331988/0f6a0065-2981-4a77-a822-6b85b155d471)

![Selection_2023-12-05_14-33-29](https://github.com/supabase/cli/assets/7331988/15bed1e0-8d4a-4714-9e75-14f5d0642f7a)

### SQL to get descriptions manually

```
select
    c.table_schema,
    c.table_name,
    c.column_name,
    pgd.description
from pg_catalog.pg_statio_all_tables as st
inner join pg_catalog.pg_description pgd on (
    pgd.objoid = st.relid
)
inner join information_schema.columns c on (
    pgd.objsubid   = c.ordinal_position and
    c.table_schema = st.schemaname and
    c.table_name   = st.relname
);
```

(thanks to https://stackoverflow.com/a/4946306/1760643)

**Comment by d9k** [comment]
Adding description in Supabase admin UI:
![Selection_2023-12-05_14-39-39](https://github.com/supabase/cli/assets/7331988/dc59a83d-74ca-4539-bb12-02c0cb228f48)

**Comment by d9k** [comment]
I was able to write [script](https://github.com/d9k/citations-supabase-demo/blob/main/node-script/db-gen-descriptions.ts) which grabs description info using SQL query via PostgreSQL connection to Supabase.

Supabase as single source of truth for fields descriptions can be very useful to construct form fields, for example.

**Comment by sweatybridge** [comment]
We will support dumping of comments in this PR https://github.com/supabase/cli/pull/1981

Typegen comments are tracked in this issue https://github.com/supabase/cli/issues/412
