### ISSUE TITLE
Unable to start local after update of Postgres

### ISSUE THREAD

**Issue by teddarling** [supabase/cli#1718]
**Describe the bug**
The problem is that running supabase start on a local machine fails. The indication is that the Docker image is not available. This is after updating Postgres to 15.1.0.137 from the Supabase infrastructure panel.

**To Reproduce**
1. Open WSL command Prompt
2. type "supabase start --ignore-health-check --debug"
3. Hit Enter

**Expected behavior**
I expect that the local Supabase docker image will run. Instead it appears that the docker image is not available.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 11 with WSL 2
 - Browser (if applicable): N/A
 - Version of CLI - 1.115.5
 - Version of supabase-js (if applicable): 2.39.0
 - Version of Node.js (if applicable): v21.2.0

**Additional context**
Debug Result:
Supabase CLI 1.115.5
2023/12/06 13:16:25 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:25 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:25 Send Done
2023/12/06 13:16:25 Recv First Byte
2023/12/06 13:16:25 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:25 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:25 Send Done
2023/12/06 13:16:25 Recv First Byte
2023/12/06 13:16:25 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:25 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:25 Send Done
2023/12/06 13:16:25 Recv First Byte
2023/12/06 13:16:25 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:25 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:25 Send Done
2023/12/06 13:16:25 Recv First Byte
2023/12/06 13:16:25 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:25 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:25 Sent Header: Content-Length [0]
2023/12/06 13:16:25 Sent Header: Content-Type [text/plain]
2023/12/06 13:16:25 Sent Header: X-Registry-Auth [e30=]
2023/12/06 13:16:25 Send Done
2023/12/06 13:16:26 Recv First Byte
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.137 not found: manifest unknown: Requested image not found
Retrying after 4s: public.ecr.aws/supabase/postgres:15.1.0.137
2023/12/06 13:16:30 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:30 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:30 Sent Header: Content-Length [0]
2023/12/06 13:16:30 Sent Header: Content-Type [text/plain]
2023/12/06 13:16:30 Sent Header: X-Registry-Auth [e30=]
2023/12/06 13:16:30 Send Done
2023/12/06 13:16:31 Recv First Byte
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.137 not found: manifest unknown: Requested image not found
Retrying after 8s: public.ecr.aws/supabase/postgres:15.1.0.137
2023/12/06 13:16:39 Sent Header: Host [api.moby.localhost]
2023/12/06 13:16:39 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/06 13:16:39 Sent Header: Content-Length [0]
2023/12/06 13:16:39 Sent Header: Content-Type [text/plain]
2023/12/06 13:16:39 Sent Header: X-Registry-Auth [e30=]
2023/12/06 13:16:39 Send Done
2023/12/06 13:16:40 Recv First Byte
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.137 not found: manifest unknown: Requested image not found

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. It is due to a failed job to publish docker image for 15.1.0.137. I've triggered a rerun of the [publish job](https://github.com/supabase/postgres/actions/runs/7086053358). It should be fixed in an hour or so.
