### ISSUE TITLE
Supabase studio container keeps restarting

### ISSUE THREAD

**Issue by Lion7de** [supabase/cli#1724]
**Describe the bug**
I created a new Supabase project. Last time i used Supabase was 1.5 years ago but i cleaned all the old images and CLI (0.5.0) from my Mac to start new again. 
Now when running npx supabase start, the Supabase Studio container keeps restarting and thus health checks fail. Unfortunately there is no Error report since the container logs only show the NextJS startup logs, so i cant really find out out whats happening there.

**To Reproduce**
1. Setup a new Supabase project
2. Run npx supabase start

**Expected behavior**
Studio container should startup and keep running.

**Screenshots**
![Bildschirmfoto 2023-12-08 um 12 39 12](https://github.com/supabase/cli/assets/27055694/1e464130-7e09-4cf0-8aa1-dba106fc8c34)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version of CLI 1.115.3-5 & beta

**Additional context**
Available docker resources: 8 CPU Cores, 10 GB RAM (Usage doesnt come close to it after startup)

I already cleaned all volumes and images from docker to make sure the images are freshly downloaded. I also tried different CLI versions with different studio container versions. All the other containers are starting properly.

**Comment by LuisHCK** [comment]
I'm having the exact same problem
Is my first time running Supabase

- CLI version: `1.115.5`
- OS MacOS Sonoma, Intel

![Screenshot 2023-12-08 at 11 44 43 AM](https://github.com/supabase/cli/assets/5175137/4cbae25b-986c-4e43-a85f-94dd84f7602c)

**Comment by sweatybridge** [comment]
Since you are using Intel Mac, the following docker settings might work for you https://github.com/supabase/cli/issues/1083#issuecomment-1691431279

**Comment by Lion7de** [comment]
Works! Perfect, thank you!
