### ISSUE TITLE
Cannot start local supabase postgres instance with 15.1 (no permission to create extension)

### ISSUE THREAD

**Issue by leerobert** [supabase/cli#1755]
**Describe the bug**
Have an existing repo from 15.0 postgres. Have existing migrations, some with lines like:

```sql
create extension if not exists "http" with schema "extensions";
```

Upon `supabase start`, migrations fail with:

```sh
git:(develop) supabase start
Applying migration 20230119033102_initial_migration_user_org.sql...
Applying migration 20230201052512_org-policies.sql...
Applying migration 20230201053030_add_project.sql...
Applying migration 20230202060208_working_rls_for_creating_org.sql...
Applying migration 20230207160023_project_changes.sql...
Applying migration 20230208185700_files_qaps_and_more.sql...
ERROR: permission denied to create extension "http" (SQLSTATE 42501)          
At statement 0: create extension if not exists "http" with schema "extensions"
```

**Expected behavior**
Supabase local instance to spin up

**Screenshots**

**Desktop (please complete the following information):**

supabase services

  
        SERVICE IMAGE      │        LOCAL         │   LINKED
    supabase/postgres      │ 15.1.0.37            │ 15.1.0.137
    supabase/gotrue        │ v2.126.1             │ v2.125.1
    postgrest/postgrest    │ v10.2.0              │ v11.2.2
    supabase/realtime      │ v2.25.35             │ -
    supabase/storage-api   │ v0.43.11             │ v0.43.11
    supabase/edge-runtime  │ v1.29.1              │ -
    supabase/studio        │ 20231123-64a766a     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Additional context**

**Comment by sweatybridge** [comment]
Hello @leerobert, it appears that your local postgres version (15.1.0.37) is out of date. Could you try updating it by running `supabase link`?

Alternatively you can reset your local versions to the default by removing `rm -rf supabase/.temp` directory.

**Comment by leerobert** [comment]
Thanks @sweatybridge this was the issue. Once I removed my `supabase/.temp` files and re-ran `supabase start`, I was able to run my migrations without issues locally.
