### ISSUE TITLE
Allow modification of JWT expiry value

### ISSUE THREAD

**Issue by yowzadave** [supabase/cli#176]
It appears that when using the CLI, the JWT is hard-coded to expire in 3600 seconds—it'd be great if there were a way to increase this to make testing locally more convenient.

**Comment by soedirgo** [comment]
You should be able to configure this in the latest version, see https://github.com/supabase/cli/blob/main/internal/init/templates/init_config.toml

**Comment by soedirgo** [comment]
Will close this for now, but feel free to reopen if there are further issues.

**Comment by yowzadave** [comment]
Thanks, @soedirgo! The documentation re: config here seems to be outdated: https://supabase.com/docs/reference/cli/config-reference . Installing the latest CLI, I now get an error if I put a `config.toml` at the root of my supabase directory:

```
Error: Error starting database: ERROR:  syntax error at or near "#"
LINE 1: # Local config
```

**Comment by soedirgo** [comment]
Yes, the docs is yet to be updated.

Re: the error, that doesn't look right - Can you provide your CLI version?

**Comment by yowzadave** [comment]
@soedirgo —sorry, my mistake; I had the config in the wrong spot.
