### ISSUE TITLE
Postgrest v12.0.1 does not exist on AWS when starting containers

### ISSUE THREAD

**Issue by azharc** [supabase/cli#1767]
**Describe the bug**
Latest Postgrest image (12.0.1) does not exist

**To Reproduce**
1. Create a new project in Supabase that uses Postgrest v12.0.1
2. Link the project locally
3. Try `supabase start`
4. `Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v12.0.1 not found: manifest unknown: Requested image not found`

**Expected behavior**
Docker containers to start. Issue can be resolved by changing `supabase/.temp/rest-version` to "v11.2.2" and running `supabase stop` then `supabase start` again. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Version of CLI: 1.123.4
 - Version of Node.js: v18.15.0

**Additional context**
I tried this on two different machines so it doesn't seem to be a network issue (I hope).

**Comment by therealpurplemana** [comment]
i am also seeing this after upgrading postgres to 15.1.1.54:

failed to pull docker image: Error response from daemon: toomanyrequests: Rate exceeded
Retrying after 4s: public.ecr.aws/supabase/postgrest:v12.1
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v12.1 not found: manifest unknown: Requested image not found
Retrying after 8s: public.ecr.aws/supabase/postgrest:v12.1

**Comment by sweatybridge** [comment]
It's a known issue with a workaround https://github.com/supabase/cli/issues/2321#issuecomment-2134460201

I will update the link once it's resolved.
