### ISSUE TITLE
CLI: Supabase Authentication. error: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Ksrzg01** [supabase/cli#1770]
**Describe the bug**
When installing the latest CLI and performing simple inserts, the code errors out as the normal 'postgres' dev password is no longer working. When I revert to version 1.112.0, everything works just fine. 

**To Reproduce**
Install the latest CLI 
Run a normal seed process which uses the supabase libary to insert data

**Expected behavior**
Installation of CLI as well as successful seeding process. 

**Screenshots**
<img width="1092" alt="image" src="https://github.com/supabase/cli/assets/109107901/e4d6f58e-c150-4ccf-b4bd-be3221327b6a">

Function where authentication fails 
<img width="499" alt="image" src="https://github.com/supabase/cli/assets/109107901/12cbc7b5-bc53-4f8e-a25c-74074dd0ea53">

**Desktop (please complete the following information):**
 - Version of CLI 1.123.4
 - Version of supabase-js (if applicable) 2.39.0
 - Version of Node.js (if applicable) v18.13.0

**Additional context**
I wish I could better explain the issue, but ultimately I have a GH action that rebuilds and tests out my website using the latest supabase cli version, in this case 1.123.4. I've been pushing changes without issue until last week when this started to manifest. After changing the version of the supabase CLI from 1.123.4 to 1.112.0, I was able to get a successful run. The part that is failing is when I try to clear the tables.

**Comment by sweatybridge** [comment]
Are you able to narrow down the version range further? It sounds similar this issue https://github.com/supabase/cli/issues/1737

**Comment by Ksrzg01** [comment]
Hey @sweatybridge  I've confirmed the failure occurs in the same versions as issue #1737. The break seems to occur in 1.120.0 and up.

**Comment by sweatybridge** [comment]
Thanks, I will close this as a duplicate then.
