### ISSUE TITLE
Edge function deployment fails on Bitbucket

### ISSUE THREAD

**Issue by asciiwhite** [supabase/cli#1774]
**Describe the bug**
We use a BitBucket pipeline to deploy our edge functions. With the changes done in supabase cli v1.120.0the deployment fails with the log message **Error: Permission denied (os error 13)**

**To Reproduce**
1. Run a bitbucket cloud pipeline including the following step
```
- step: 
    script:
      - cd supabase
      - npm ci
      - npx supabase link --project-ref $SUPABASE_PROJECT_ID
      - npx supabase functions deploy
    services:
      - docker
```
2. Error at end of bundle step
```
Supabase CLI 1.120.0
Bundling ai-sales-script
...
v1.29.1: Pulling from supabase/edge-runtime
...
DEBUG Snapshot already up to date. Skipping pending resolution.
DEBUG Opening cache /root/.cache/deno/dep_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/dep_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
Error: Permission denied (os error 13)
2023/12/21 09:19:38 Sent Header: Host [localhost:2375]
2023/12/21 09:19:38 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/12/21 09:19:38 Send Done
2023/12/21 09:19:38 Recv First Byte
error running container: exit 1
```

**Expected behavior**
No error should occur and the edge function deployment should finish successfully.

**System information**
 - Version of CLI: v1.120.0 and higher

**Additional information**
- we are using a monorepo including the supabase directory
- the import map of our functions only contains remote entries to cdn's

**Comment by sweatybridge** [comment]
I would need more system info to diagnose. Could you try `npx supabase@beta functions deploy --create-ticket` on your CI and report the crash ID here?

**Comment by asciiwhite** [comment]
> I would need more system info to diagnose. Could you try `npx supabase@beta functions deploy --create-ticket` on your CI and report the crash ID here?

The crash id: f57b447f764d488cb2dc62b400170204

**Comment by sweatybridge** [comment]
@laktek looks like the permission denied error is coming from edge runtime. Is there any debug flag that we can set to return the file path that edge runtime is trying to access?

**Comment by sweatybridge** [comment]
I've addressed this issue in beta release and tested with my own bitbucket repository. Could you try the following command in your pipeline?

```bash
npx supabase@beta functions deploy
```

**Comment by asciiwhite** [comment]
> ```shell
> npx supabase@beta functions deploy
> ```

The beta version does not show the issue. :)
