### ISSUE TITLE
Failed to save database password: failed to unlock correct collection （not wsl）

### ISSUE THREAD

**Issue by sunt89** [supabase/cli#1779]
**Describe the bug**
when i execute supabase link --project-ref xxxxxx
Failed to save database password: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'
Finished supabase link.

**Additional context**
Supabase cli version: 1.123.4
OS:  Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by sweatybridge** [comment]
This is just a warning when native credentials store isn't available. It's safe to ignore.
