### ISSUE TITLE
Use git branch name by default when creating a db branch

### ISSUE THREAD

**Issue by iAmWillShepherd** [supabase/cli#179]
# Feature request

Use the current git branch name as the default name – when no branch name is given – for the db branch when running `supabase db branch create`.

## Describe the solution you'd like

The current implementation requires that I pass the `<branch name>` as an argument, but it would be nicer if the argument were optional and the CLI used my currently checked out branch in git for the branch name when no branch name is given. 

###### Result in a db branch being created named _feb23-livestream_, after the git branch name
```sh
╭─iamwill@zues ~/code/OneSignalDevelopers/ngosi ‹feb23-livestream●›
╰─$ supabase db branch create
```

###### If a name is given, use that instead
```sh
╭─iamwill@zues ~/code/OneSignalDevelopers/ngosi ‹feb23-livestream●›
╰─$ supabase db branch create some-other-branch-name
```

**Comment by sweatybridge** [comment]
This is now the default behaviour for preview branching https://github.com/supabase/cli/pull/1313
