### ISSUE TITLE
Seeding data fails when supabase db dump inserts \n into first line of seed.sql

### ISSUE THREAD

**Issue by Daniel-Ash** [supabase/cli#1793]
**Describe the bug**
Seeding data fails when supabase db dump inserts \n into first line of seed.sql

**To Reproduce**
1. Run a seed data dump, e.g. 
`supabase db dump --data-only -f supabase/data/seed.sql `
2. First line of seed.sql will contain a newline:  
`SET session_replication_role = replica;\n`
3. Run seed script against db (I use psql)
`an error occurred while executing the script: exit status 3
psql:supabase/data/seed.sql:1: error: invalid command \n`

**Expected behavior**
`\n` should not appear in seed.sql

**System Info:**
- OS: Windows
- Version of CLI: supabase: 1.127.3 (latest version as of 30 December 2023)

**Additional context**
If you manually remove \n the script runs as expected.

**Comment by sweatybridge** [comment]
I believe this is fixed in the beta release channel. Could you try `npx supabase@beta db dump --data-only` to see if it works as expected?

**Comment by Daniel-Ash** [comment]
I use scoop for the CLI - can it access the beta release channel?

**Comment by sweatybridge** [comment]
Yes, the command is `scoop install supabase-beta`

**Comment by Daniel-Ash** [comment]
Looks like you're correct @sweatybridge. All sorted!

**Comment by sweatybridge** [comment]
https://github.com/supabase/cli/pull/1783
