### ISSUE TITLE
Auth actions throwing 502 Bad gateway error while developing locally 

### ISSUE THREAD

**Issue by KarelSchwab** [supabase/cli#18]
# Bug report

## Describe the bug

A 502 Bad gateway error gets thrown in the development console when trying to sign up or sign in a user after calling `createClient` in a frontend Vue application using Vitejs. Everything works fine when using the supabaseUrl and supabaseKey from the dashboard but not that of the CLI after initialising it.

## To Reproduce

Follow the guide as is in the CLI docs
1. Run `npm install -g supabase`
2. Run `supabase init`
3. Create the client using the `createClient` method from the @supabase/supabase-js package
4. Run `supabase start`
5. Run `npm run dev`
6. Call the `signin` or `signUp` method

## Expected behavior

That a user will be signed in or a new user record be created

## Screenshots
![image](https://user-images.githubusercontent.com/35557567/113487256-5de2c200-94b7-11eb-90c9-fc1f59894c0a.png)

## System information

- OS: Pop!_OS 20.10
- Browser: Brave
- Version of supabase-js: 1.7.7
- Version of Node.js: 12.18.2

## Additional context

Docker version: 20.10.5, build 55c4c88
Docker Compose version: 1.28.6, build 5db8d86f

Output when running `docker ps`
![image](https://user-images.githubusercontent.com/35557567/113487319-ba45e180-94b7-11eb-8d93-de5564127e64.png)

**Comment by kiwicopple** [comment]
Hey @KarelSchwab, it could be related to this: https://github.com/supabase/cli/issues/9 (fixed in v0.3.4: https://github.com/supabase/cli/pull/12)

Can I please check:

- what version of the CLI are you running?
- do you have Postgres installed locally and running on Port 5432? This could be conflicting with the docker database

**Comment by KarelSchwab** [comment]
Hi @kiwicopple, I'm using CLI version 0.3.6. No, I do not have it installed. I will read through #9 and #12 and keep investigating.

**Comment by KarelSchwab** [comment]
Hi @kiwicopple. I got it working. Seems like it was just a spotty network connection that dropped a few times while running `supabase init`. After removing the containers, images, and the volumes it works.
