### ISSUE TITLE
Unable to install supabase via pnpm

### ISSUE THREAD

**Issue by ianzone** [supabase/cli#1809]
**Describe the bug**
```
$ pnpm add -g supabase
Packages: +26
++++++++++++++++++++++++++
Progress: resolved 43, reused 17, downloaded 26, added 26, done
 WARN  Failed to create bin at /home/ian/.local/share/pnpm/global/5/.pnpm/supabase@1.127.4/node_modules/supabase/node_modules/.bin/supabase. ENOENT: no such file or directory, open '/home/ian/.local/share/pnpm/global/5/.pnpm/supabase@1.127.4/node_modules/supabase/bin/supabase'
.pnpm/supabase@1.127.4/node_modules/supabase: Running postinstall script, failed in 201ms
.../node_modules/supabase postinstall$ node scripts/postinstall.js
│ node:internal/process/esm_loader:40
│       internalBinding('errors').triggerUncaughtException(
│                                 ^
│ Installing Supabase CLI as a global module is not supported.
│ Please use one of the supported package managers: https://github.com/supabase/cli#install-the-cli
│ (Use `node --trace-uncaught ...` to show where the exception was thrown)
│ Node.js v20.10.0
└─ Failed in 201ms at /home/ian/.local/share/pnpm/global/5/.pnpm/supabase@1.127.4/node_modules/supabase
 ELIFECYCLE  Command failed with exit code 1.
```

**Expected behavior**
package installed

**Desktop (please complete the following information):**
 - OS: Windows and Ubuntu
 - Version of Node.js v20.10.0

**Comment by sweatybridge** [comment]
As explained in the error message, installing with `-g` flag is not supported. Please use one of the alternatives in readme.

**Comment by abbott** [comment]
Install Supabase CLI binary globally without homebrew using this gist: [install-supabase-cli-macos.sh](https://gist.github.com/abbott/9b0a3a10274a05517d30ec39f1ee34a0). 

It works perfectly on my M1 MacBook Pro.

cc: @ianzone

**Comment by ivandax** [comment]
The `-g` flag is not supported. I needed it in Windows but the docs recommended installing locally as a dev dependency. 

I used yarn: 

`NODE_OPTIONS=--no-experimental-fetch yarn add supabase --dev`

See here:
https://supabase.com/docs/guides/local-development?queryGroups=package-manager&package-manager=yarn#quickstart
