### ISSUE TITLE
DB Lint Should have the Option to Exit with a Non-Zero Status Code if There are Lint Errors 

### ISSUE THREAD

**Issue by davidtucker** [supabase/cli#1812]
**Is your feature request related to a problem? Please describe.**
Currently the Supabase documentation includes the lint functionality in the sample Github workflows. Since lint always returns a zero exit code, this does nothing more than add the lint notes to the build logs. While I don't think you always want a lint command to fail when there are warnings or errors, this should be a configuration option so that it can be included in a testing pipeline without parsing the output.

**Describe the solution you'd like**
The current behavior can be preserved by forcing a flag to enable this behavior. The `--fail-on` flag could be configured for `error`, `warning`, or `none` (default value).

**Comment by avallete** [comment]
I can work on this one.

**Comment by avallete** [comment]
Thank's for reporting !

This has been added in: https://github.com/supabase/cli/pull/2664
