### ISSUE TITLE
CLI Fails to get proper images on Raspberry PI 4

### ISSUE THREAD

**Issue by Matsuuu** [supabase/cli#1818]
**Describe the bug**
Running the supabase CLI, build/installed from source via `go install`, I try to start up a supabase project with `supabase start` adn get the following error

```
15.1.0.147: Pulling from supabase/postgres
failed to display json stream: no matching manifest for linux/arm/v7 in the manifest list entries
Retrying after 4s: public.ecr.aws/supabase/postgres:15.1.0.147

```

**To Reproduce**
1. Have a Raspberry Pi 4
2. Setup a supabase project
3. Run Supabase start

**Expected behavior**
Supabase starts and setup up the right docker containers

**Desktop (please complete the following information):**
 - OS: uname: Linux raspberrypi 6.5.0-1005-raspi #7-Ubuntu SMP PREEMPT Sun Oct  8 09:09:29 UTC 2023 armv7l armv7l armv7l GNU/Linux
 Raspberry Pi 4
 - Version of CLI: Current master

**Additional context**
It seems like the whole project has some hiccups working on raspberry pi's :D The only way to get the cli working was to get the source code and build it with go, now this, etc.

**Comment by nyannyacha** [comment]
If you look at [supabase/postgres](https://hub.docker.com/r/supabase/postgres/tags) on dockerhub, it's not supported to run in ARM 32-bit mode, so yes it's expected that it won't run on that OS. You will need to reinstall an OS on your Pi that supports 64-bit mode.

Please refer link below for more information 😁
https://raspberrypi.stackexchange.com/questions/111011/aarch64-or-armv8-with-arch-on-a-raspberry-pi-4

**Comment by Matsuuu** [comment]
Boy do I feel dumb right now 😄 

Accidentally had installed a 32-bit linux on the machine.

**Comment by digisomni** [comment]
> If you look at [supabase/postgres](https://hub.docker.com/r/supabase/postgres/tags) on dockerhub, it's not supported to run in ARM 32-bit mode, so yes it's expected that it won't run on that OS. You will need to reinstall an OS that supports 64-bit mode on your Pi.
> 
> Please refer link below for more information 😁 https://raspberrypi.stackexchange.com/questions/111011/aarch64-or-armv8-with-arch-on-a-raspberry-pi-4

The problem with this is that Supabase Vector is not supported on 64-bit ARM, particularly, where a page size > 4KB is present. So this is a bit of a Catch 22.
