### ISSUE TITLE
Unable to access logs on local dev environment - An error has occurred: fetch failed

### ISSUE THREAD

**Issue by alexandrubau** [supabase/cli#1820]
**Describe the bug**
After setting up local development environment, I'm unable to access any logs from the studio console. No matter which service I access, I get the following error.

**To Reproduce**
1. Install `supabase/cli` using homebrew according to official docs
2. Run `supabase init` followed by `supabase start`
3. Access studio console at http://127.0.0.1:54323
4. Navigate to Logs section and click on any service provider
6. See the error

**Expected behavior**
Logs should be displayed for each provider.

**Screenshots**
<img width="1100" alt="Screenshot 2024-01-06 at 15 00 40" src="https://github.com/supabase/cli/assets/1225661/2a92bfd2-0f23-4a8b-940d-c84bb1d12629">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of CLI: 1.127.4

**Additional context**
No tables or schemas were added. Just the local development setup according to official docs.
No errors were thrown during setup. No errors can be found on any running docker containers.

**Comment by sweatybridge** [comment]
Could you check if the `[analytics]` section in your `supabase/config.toml` is set to enabled? If this is the first time you init, logs explorer is disabled by default.

**Comment by alexandrubau** [comment]
You are right, it was disabled. Shouldn't it be enabled by default?

**Comment by divmgl** [comment]
@sweatybridge probably low priority, but you may want to add a quick blurb for this error message on the dashboard to avoid future users from being confused about this (as I just was).

**Comment by argotechnica** [comment]
+1 to "quick blurb for this error message on the dashboard"

it'd be great to not have to find a gh issue to know I have to do this!

**Comment by Jonny1987** [comment]
> +1 to "quick blurb for this error message on the dashboard"
> 
> it'd be great to not have to find a gh issue to know I have to do this!

I agree

**Comment by AlexBThomsen** [comment]
Agree!
