### ISSUE TITLE
Realtime websockets begin to fail after running supabase db reset

### ISSUE THREAD

**Issue by azharc** [supabase/cli#1829]
**Describe the bug**
Realtime begins to fail after `supabase db reset`

**To Reproduce**
1. Open a project that uses realtime and open the developer console on the front end
2. Run `supabase start`
3. Websocket connections will establish successfully
4. Run `supabase db reset`
5. Websocket connection will begin to fail 

**Expected behavior**
Websockets remain connected even after `supabase db reset`

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.1
 - Browser (if applicable): Chrome
 - Version of CLI: 1.131.3

**Additional context**
The issue resolves itself if one runs `supabase stop` then `supabase start` again. 

Here is the relevant code in the migration that may play a role in this issue:
```
-- REALTIME
-- remove the supabase_realtime publication
DROP publication if exists supabase_realtime;
-- re-create the supabase_realtime publication with no tables
CREATE publication supabase_realtime;
COMMIT;
-- (update this to match your tables)
ALTER publication supabase_realtime add table public.freezes;
ALTER publication supabase_realtime add table public.actions;
ALTER publication supabase_realtime add table public.games;
ALTER publication supabase_realtime add table public.progress;
```

**Comment by sweatybridge** [comment]
If you refresh the browser, does websocket successfully reconnect?

The db reset command performs a hard reset where the whole database container is recreated. For many reasons, we cannot change this behaviour. Therefore, I believe it's not possible for realtime service to reuse any existing websockets after reset.
