### ISSUE TITLE
Windows 2022 Server supabase start failed.

### ISSUE THREAD

**Issue by zhushuihua** [supabase/cli#183]
c:\server\supabase start
Error: Error response from daemon: No such image: supabase/postgres:14.1.0

**Comment by soedirgo** [comment]
You might need Docker on WSL to run it on Windows since we don't have `windows/amd64` images.

**Comment by zhushuihua** [comment]
I have installed ubuntu to wsl, and now the error becomes
sudo /home/linuxbrew/.linuxbrew/bin/supabase start
Error: Error response from daemon: network supabase_network_my_server not found

**Comment by zhushuihua** [comment]
sudo docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS    PORTS     NAMES
6cbc64b74325   hello-world                "/hello"                 2 minutes ago    Created             loving_cohen
f7fded7dd603   hello-world                "/hello"                 5 minutes ago    Created             fervent_ellis
4c88cd01b8b8   supabase/postgres:14.1.0   "docker-entrypoint.s…"   10 minutes ago   Created             supabase_db_my_server
6e5a5b2d2443   hello-world                "/hello"                 34 minutes ago   Created             nifty_stonebraker
5653339efe15   hello-world                "/hello"                 36 minutes ago   Created             frosty_babbage
007261dbe981   hello-world                "/hello"                 37 minutes ago   Created             objective_driscoll

**Comment by zhushuihua** [comment]
sudo docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
8fd78ac1ec08   bridge    bridge    local
ef0e6fcc4c42   host      host      local
1bbfde478f65   none      null      local

**Comment by sweatybridge** [comment]
Closing this issue as stale. Feel free to open again if this is still happening in the latest version.
