### ISSUE TITLE
Database tests cannot be executed on BitBucket Pipeline

### ISSUE THREAD

**Issue by asciiwhite** [supabase/cli#1830]
**Describe the bug**
Running our database test in an Bitbucket pipeline fails due to some docker related settings. 

```
npx supabase db test
Connecting to local database...
3.36: Pulling from supabase/pg_prove
...
Status: Downloaded newer image for public.ecr.aws/supabase/pg_prove:3.36
failed to create docker container: Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
```

**To Reproduce**
Run **npx supabase db test** inside a BitBucket Cloud Pipeline.

**Expected behavior**
The database tests should be executed with issues.

**Desktop (please complete the following information):**
 - Version of CLI v1.131.0

**Comment by asciiwhite** [comment]
Support ticket id: 61fb85130f7644aaa3d4c79e78ab44eb

**Comment by sweatybridge** [comment]
Apologies for this regression. I've released a new version that fixes this problem on bitbucket pipeline.

**Comment by asciiwhite** [comment]
Thanks a lot for the quick fix. :)

**Comment by swamidass** [comment]
Having this same problem with version of the cli 1.172.2
