### ISSUE TITLE
Error trying to activate vanity subdomain using CLI

### ISSUE THREAD

**Issue by xpertana** [supabase/cli#1832]
**Describe the bug**
Getting the following error while trying to activate a vanity subdomain:
```
failed to create vanity subdomain config: {"message":"Internal Server Error","errorEventId":"10cf2a4a109940259df6d1c4fef235cc"}
Sent crash report: b8cf1cb37e714c2aac31f56acd9a0371
```
 -  I am on a Pro Plan
 -   CLI version is : Supabase CLI 1.127.4
 
**To Reproduce**
Issue the following CLI command:
```
supabase vanity-subdomains activate --project-ref <myprojectid> --desired-subdomain xxxxxx --debug --experimental
```

- When I check the status via the 'get' CLI command it shows active anyway:
```
 Status: active
Vanity subdomain: xxxxxx.supabase.co
```

- I can delete the subdomain using the CLI without error
- But in actuality it is never really fully active:
-  does not show up on the Supabase dashboard
-  does not work in Supabase connection args using `createClient`

**Desktop (please complete the following information):**
 - OS: Mac OS 14.1 (23B2073)
 - Version of CLI : Supabase CLI 1.127.4

**Comment by sweatybridge** [comment]
Hello @xpertana, there appears to be an error setting cname record for your hosted project. I don't think this is a cli error but I would suggest creating a [support ticket](https://supabase.com/dashboard/support/new) through the dashboard. Our support team will respond promptly to help you check the vanity subdomain setup.
