### ISSUE TITLE
Manifest unknown

### ISSUE THREAD

**Issue by zhihengGet** [supabase/cli#1839]
**Describe the bug**
have been getting  following err

failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.46 not found: manifest unknown: Requested image not found
                                                                                                                                                                       Retrying after 4s: public.ecr.aws/supabase/postgres:14.1.0.46
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.46 not found: manifest unknown: Requested image not found   
                                                                                                                                                                       Retrying after 8s: public.ecr.aws/supabase/postgres:14.1.0.46
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.46 not found: manifest unknown: Requested image not found
Try rerunning the command with --debug to troubleshoot the error.

@1.133.1

**Comment by sweatybridge** [comment]
Could you double check the `major_version` field in `supabase/config.toml`? It should say `major_version = 14` since you are using a PG14 project.

**Comment by zhihengGet** [comment]
> Could you double check the `major_version` field in `supabase/config.toml`? It should say `major_version = 14` since you are using a PG14 project.

hello, i have version 15, i actually  regeneretaed a new one using supabase cli but no luck

major_version = 15

**Comment by sweatybridge** [comment]
You need to set it to 14 to match your remote project.
