### ISSUE TITLE
Error: duplicate key value violates unique constraint "schema_migrations_pkey"

### ISSUE THREAD

**Issue by wirhabenzeit** [supabase/cli#1844]
**Describe the bug**
I am trying to mirror the remote database schema and contents to my local development database. 

**To Reproduce**

```
npx supabase db pull  
npx supabase db dump -f supabase/seed.sql --data-only
npx supabase db reset --debug                          
```

**Error**

```
2024/01/16 00:04:24 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"23505","Message":"duplicate key value violates unique constraint \"schema_migrations_pkey\"","Detail":"Key (version)=(20240115215654) already exists.","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"supabase_migrations","TableName":"schema_migrations","ColumnName":"","DataTypeName":"","ConstraintName":"schema_migrations_pkey","File":"nbtinsert.c","Line":664,"Routine":"_bt_check_unique","UnknownFields":null}
2024/01/16 00:04:24 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
failed to send batch: ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" (SQLSTATE 23505)
```

**Expected behavior**
I am expecting the remote database to be mirror to my local one. Without `db dump` the db reset works without error (but the resulting database is empty)

**Desktop (please complete the following information):**
 - Version of CLI [e.g. v1.131.4]

**Comment by sweatybridge** [comment]
Could you give `npx supabase@beta db reset` a try? We made a fix recently for this issue.

**Comment by galaxyblur** [comment]
@sweatybridge that worked for me!

**Comment by wirhabenzeit** [comment]
@sweatybridge I am getting the same error with the beta version:

```
% npx supabase@beta db reset        
Resetting local database...
Recreating database...
Setting up initial schema...
Applying migration 20240115215654_remote_schema.sql...
Seeding data supabase/seed.sql...
failed to send batch: ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" (SQLSTATE 23505)
Try rerunning the command with --debug to troubleshoot the error.
```

With `--debug` the error is 

```
2024/01/16 07:14:35 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"23505","Message":"duplicate key value violates unique constraint \"schema_migrations_pkey\"","Detail":"Key (version)=(20240115215654) already exists.","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"supabase_migrations","TableName":"schema_migrations","ColumnName":"","DataTypeName":"","ConstraintName":"schema_migrations_pkey","File":"nbtinsert.c","Line":664,"Routine":"_bt_check_unique","UnknownFields":null}
```

**Comment by wirhabenzeit** [comment]
Update: Commenting out 

```
INSERT INTO "supabase_migrations"."schema_migrations" ("version", "statements", "name") VALUES
....
```

in `seed.sql` makes `npx supabase db reset` run successfully.

**Comment by lab-bone-Max** [comment]
I'm seeing the same issue and still get 'ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" (SQLSTATE 23505)' with `npx supabase@beta db reset` even when the seed.sql was also created with beta CLI with `npx supabase@beta db dump -f supabase/seed.sql --data-only`

I note the "statements" and "name" columns are both NULL in the generated seed.sql whereas they are correctly populated with the migrations data with identical "schema_migrations"."version" in the local DB just before this failure. I temporarily resolved this by adding ` ON CONFLICT("version") DO NOTHING` to the end of the INSERT statement.

The CLI version that was downloaded with `npx supabase@beta -v` was supabase@1.134.0

**Comment by sweatybridge** [comment]
Thanks for adding more details. I believe it's safe to delete insert statements to `supabase_migrations.schema_migrations` completely to avoid double seeding. I've made a PR to change the default behaviour of `db dump --data-only` so they won't be included in seed.sql going forward.

**Comment by DhenPadilla** [comment]
@sweatybridge 

>Thanks for adding more details. I believe it's safe to delete insert statements to supabase_migrations.schema_migrations completely to avoid double seeding. I've made a PR to change the default behaviour of db dump --data-only so they won't be included in seed.sql going forward.

I've been thinking about this as previously, we run into duplicate-seed issues.

My ideal is that the the `db dump --data-only` also had a flag called `--exclude` which takes a list of strings for tables that you'd like to exclude from the seed during the `db dump`.

This would help both supabase and it's supabase-cli users as any breakages such as this issue can just be circumvented easier by users

**Comment by sweatybridge** [comment]
Sound good to me. We have a separate issue here for tracking exclude flag https://github.com/supabase/cli/issues/1772

**Comment by bashirmindee** [comment]
I couldn't launch supabase so I couldn't reset it.
I pruned the volumes: `docker volume prune --all`
