### ISSUE TITLE
column "refreshed_at" of relation "sessions" does not exist

### ISSUE THREAD

**Issue by lab-bone-Max** [supabase/cli#1845]
**Describe the bug**
When restoring a copy of production DB for local development I get the error:
```
Seeding data supabase/seed.sql...
failed to send batch: ERROR: column "refreshed_at" of relation "sessions" does not exist (SQLSTATE 42703)
```

**To Reproduce**
1. Dump the DB with `supabase db dump -f supabase/seed.sql --data-only`
2. Initialise local DB with `supabase db reset` 

**Expected behavior**
I can see that our production DB has some extra columns (refreshed_at, user_agent, ip, tag) in the auth.sessions table that are not present in a current empty default DB. I can also see the same is true of the column auth.identities.provider_id and we don't have these columns in any of our migrations.

We are a long time Supabase customer and have been using the cli since the beginning. Admittedly we have a number of hacks in the migrations accumulated from old Schema Diff issues such as sequence names not renamed after renaming tables in the Supervisor UI.

We only manage the public schema in our migrations and it seems other schemas of our production DB have got out of sync with the Supabase default DB. is it safe to delete these columns?

**Desktop (please complete the following information):**
 - MacOS
 - CLI v1.127.4
 
**Additional context**
Sent crash report: d55c4ed4457c4a42aa0119b0c379c3db

**Comment by sweatybridge** [comment]
It's strange that I couldn't find your crash ID in our sentry. Could you try running `db reset --create-ticket` again?

> our production DB has some extra columns (refreshed_at, user_agent, ip, tag) in the auth.sessions table that are not present in a current empty default DB

There is a short term solution to rectify this:

1. Check that your local service versions match remote by running `supabase services` command. If they don't match, you want to run `supabase link` to update your local versions.
2. You want to pull the custom changes you've made to the remote auth schema by running `supabase db pull --schema auth`.

After these steps, db reset should work locally.

The long term solution is to remove any custom changes you've made to `auth` schema. The `auth` schema is managed by Supabase and we can't guarantee that future upgrades work if you have custom modifications. For custom fields like user_agent, ip, tag, etc. our suggestion is to create your own table in public schema that syncs with auth schema via triggers.

But to be safe, please file a [support ticket](https://supabase.com/dashboard/support/new) so our auth team can take a closer look at what needs to be done.

**Comment by lab-bone-Max** [comment]
Thanks for the hints, `supabase services` yielded:
```
        SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼───────────
    supabase/postgres      │ 15.1.0.117           │ 15.1.1.2
    supabase/gotrue        │ v2.104.2             │ v2.132.3
    postgrest/postgrest    │ v11.2.0              │ v12.0.2
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.43.11             │ v0.43.11
    supabase/edge-runtime  │ v1.29.1              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

Run supabase link to sync your local image versions with the linked project.
```
So I ran `supabase link` to get:
```
Selected project ref: xxxxx
Enter your database password (or leave blank to skip): 
Finished supabase link.
Local config differs from linked project. Try updating supabase/config.toml
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "oms"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

["db.pooler"]
enabled = false
port = 54329
pool_mode = "session"
default_pool_size = 15
max_client_conn = 100
```
Other than the pool_mode and the schemas this is the same as my config.toml. What is confusing is that we don't have a schema called 'oms' but adding the lines to the config.yaml and running `supabase link` yields:
```
Selected project ref: xxx
Enter your database password (or leave blank to skip): 
Finished supabase link.
```
and `supabase services` now gives
```
        SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼───────────
    supabase/postgres      │ 15.1.1.2             │ 15.1.1.2
    supabase/gotrue        │ v2.132.3             │ v2.132.3
    postgrest/postgrest    │ v12.0.2              │ v12.0.2
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.43.11             │ v0.43.11
    supabase/edge-runtime  │ v1.29.1              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

I'm not sure I needed the `supabase db pull --schema auth` but after a couple of supabase stop/supabase start/Supabase reset tries the expected sequence of `supabase db dump --data-only >"supabase/seed.sql"` and `supabase db reset` now works. I can see you seem to have also fixed the issue with the 'supabase_migrations.schema_migrations' key conflict so thanks for that.

I'm still concerned about where these extra columns in the auth schema came from and why the CLI thinks there is a phantom 'oms' schema. Our DB is very old and comes from the early days of SB when documentation was rarely canonical. I think this is peculiar to us so will raise a ticket to get our DB looked out.

**Comment by sweatybridge** [comment]
> CLI thinks there is a phantom 'oms' schema

This 'oms' schema is most likely coming from your dashboard api configuration: https://supabase.com/dashboard/project/_/settings/api

It should be safe to remove from the `Extra schemas` field if it no longer exists.
