### ISSUE TITLE
`refreshSession` returns `null`

### ISSUE THREAD

**Issue by naripok** [supabase/cli#185]
# Bug report

Calling `supabase.auth.refreshSession` on local dev env breaks session.
I've added a runnable minimal example [here](https://github.com/naripok/supabase-js-refreshSession-bug). It runs on node but the exact same happens on the browser.

## Describe the bug

After signing in with `supabase.auth.signIn` the `supabase.auth.token` obj is set in the `localStorage` as expected.
My use-case manipulates the `user_metadata` in the backend and I need to refresh it in the front-end after the calls succeed.
Calling `getUser(session.access_token)` returns the same obj as present in the `supabase.auth.token.currentSession.user`, without the updates.
The only way I found for getting the updated user obj is to call `supabase.auth.refreshSession`. This works on the deployed version of the app. However, on local (`supabase start`), calling `refreshSession` issues `TOKEN_REFRESHED` event containing the `session` param as an empty obj `{}`. The strange thing is that the `supabase.auth.token` remains in the `localStorage` untouched.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start a development supabase server with `supabase start`
2. Sign in with `supabase.auth.signIn`
3. Verify that `supabase.auth.token` obj is set in the `localStorage`
4. Call `supabase.auth.refreshSession`
5. Verify that the session is broken by watching it with `supabase.auth.onAuthChange`
6. Verify that subsequent calls to `supabase.auth.session` returns `{}`

## Expected behavior

Should update the session/user with the most up-to-date server data?

## System information

- OS: Ubuntu Linux 5.11.0-46-generic 51~20.04.1-Ubuntu
- Version of supabase-js: 1.30.6
- Version of Node.js: v16.13.2

## Additional context

- [runnable minimal example](https://github.com/naripok/supabase-js-refreshSession-bug)

**Comment by thorwebdev** [comment]
@naripok can you print the output of `docker logs supabase_auth_<project_id in supabase/config.toml>`?
