### ISSUE TITLE
Broken flag --env-file

### ISSUE THREAD

**Issue by luisfcofv** [supabase/cli#1863]
**Describe the bug**
The `﻿--env-file` flag is failing to read any `﻿.env` files.

**To Reproduce**
1. Open a terminal
2. Run `supabase functions serve --env-file ./supabase/.env.local`
3. See error `Failed to read env file: stat ./supabase/.env.local: no such file or directory`

**Expected behavior**
It should read the `.env` file

**Screenshots**
<img width="753" alt="Screenshot 2024-01-19 at 10 11 31" src="https://github.com/supabase/cli/assets/1128284/b8347bfd-8c08-42e1-85fe-bf0fb8d7d3ac">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version of CLI: 1.131.5

**Additional context**
I tried different paths and different .env file names. The outcome remained the same.

**Comment by muratmirgun** [comment]
Guys I can take this issue

**Comment by sweatybridge** [comment]
I suspect this happens because the project folder is named `supabase`. It confuses our chdir logic because there is a supabase directory nested under supabase.

As a temporary workaround, you can try renaming the project folder to something else.

**Comment by luisfcofv** [comment]
Thanks for checking this out @sweatybridge. Here is the output of `pwd`
`/Users/luis/Development/juliens/apps/supabase`

I also added the output of `ls -al` in case that helps.
The Firebase CLI is not picking up any of my .env files.

![Screenshot 2024-01-22 at 09 28 28](https://github.com/supabase/cli/assets/1128284/e3ad6d08-44f2-4f03-8699-1a3f14e9188f)

**Comment by luisfcofv** [comment]
I renamed the folder, and it is now working as expected. I also reinstalled the Docker images and containers, so I'm not sure which action fixed the issue. Thanks! I'm closing the issue now.
