### ISSUE TITLE
`supabase db diff` granting privileges to `anon` and other roles (in a way it never has)

### ISSUE THREAD

**Issue by nbarrow-inspire-labs** [supabase/cli#1864]
**Describe the bug**
When I create a new table ([demo](https://drive.google.com/file/d/1w7Z1uhoQETJO-F6OOJr3RZ5QgJGx004T/view?usp=sharing)) and then run `supabase db diff` (the precise command I use for my tailored setup is `supabase db diff --schema storage,extensions,public,pg_catalog,auth -f diff` I usually get a schema diff for just the created table. However, now I am getting a whole host of `grant` commands to roles (including `anon`) which should not be the case.

I double checked, and none of my previous migrations (after creating tables, et cetera) have these in them:

```sql
-- ...

grant delete on table "public"."dispatch_boards" to "anon";

grant insert on table "public"."dispatch_boards" to "anon";

grant references on table "public"."dispatch_boards" to "anon";

grant select on table "public"."dispatch_boards" to "anon";

grant trigger on table "public"."dispatch_boards" to "anon";

grant truncate on table "public"."dispatch_boards" to "anon";

grant update on table "public"."dispatch_boards" to "anon";

grant delete on table "public"."dispatch_boards" to "authenticated";

grant insert on table "public"."dispatch_boards" to "authenticated";

grant references on table "public"."dispatch_boards" to "authenticated";

grant select on table "public"."dispatch_boards" to "authenticated";

grant trigger on table "public"."dispatch_boards" to "authenticated";

grant truncate on table "public"."dispatch_boards" to "authenticated";

grant update on table "public"."dispatch_boards" to "authenticated";

grant delete on table "public"."dispatch_boards" to "service_role";

grant insert on table "public"."dispatch_boards" to "service_role";

grant references on table "public"."dispatch_boards" to "service_role";

grant select on table "public"."dispatch_boards" to "service_role";

grant trigger on table "public"."dispatch_boards" to "service_role";

grant truncate on table "public"."dispatch_boards" to "service_role";

grant update on table "public"."dispatch_boards" to "service_role";
```

**To Reproduce**
See this video: https://drive.google.com/file/d/1w7Z1uhoQETJO-F6OOJr3RZ5QgJGx004T/view?usp=sharing

**Expected behavior**
None of these statements.

**Screenshots**
See the [video](https://drive.google.com/file/d/1w7Z1uhoQETJO-F6OOJr3RZ5QgJGx004T/view?usp=sharing) above.

**Desktop (please complete the following information):**
 - OS: macOS 13.3 (22E252)
 - Browser: Version 120.0.6099.216 (Official Build) (arm64)
 - Version of CLI: 1.131.5
 - Version of supabase-js: n/a
 - Version of Node.js: n/a

**Comment by nbarrow-inspire-labs** [comment]
I'm only bringing this up because it appears to me to be a major security issue to be granting these privledges to roles like `anon` (and for the fact that none of my other 30 some-odd tables have ever experience this before the new 1.131.x version of the cli).

**Comment by sweatybridge** [comment]
This is probably due to an [intentional change](https://github.com/supabase/cli/pull/1728) to always diff the grant statements. It suggests that your remote database has these grants which are not present in your local migrations.

You can verify this by running the query below

```
SELECT grantee, privilege_type 
FROM information_schema.role_table_grants 
WHERE table_name='dispatch_boards'
```

If this is not intended, I think it's best for you to manually revoke these grants through the remote dashboard.

**Comment by nbarrow-inspire-labs** [comment]
@sweatybridge thanks for your reply. I don't have a remote database connected, I'm diff-ing against the local clone. Basically, I'm using the default functionality (which I believe is the same as using the `--local` flag). Although, based on the PR you linked, it seems like this isn't a security issue? If it isn't, and this is fine, we can probably close thise (I wanted to be check to be safe).

**Comment by sweatybridge** [comment]
Oh I see. The local database's default privileges should have setup these grants to `anon` role for every new table created in public schema. It's weird that these grants appear in the diff without any manual changes. Perhaps you can try `supabase stop --no-backup` to clean up local state before diffing?

The grants on `anon` are safe as long as you enable RLS policies on those tables. Without these grants, supabase-js won't be able to access the table using anon key.

**Comment by danielo515** [comment]
I am also worried about this.
Most of my tables, should only be accessible to the admin user, and no one else. This means that I only enable row level security, and don't add any policy. This seems to be enough to prevent anon to insert or read rows from those tables, but I think it is redundant and unnecessary. Why add those grants? It is confusing and noisy.

**Comment by stefan-girlich** [comment]
+1 for the security concerns.
@sweatybridge Would it make sense / is it possible to add a comment to the corresponding lines in the generated migration file? Even though this should be safe, it could be worth encouraging users to remove at least the permissions that they know they definitely won't need (e.g. any write access for `anon`)

**Comment by Shabinder** [comment]
+1, this behaviour isnt mentioned anywhere, and seeing these grants, without knowning this, just makes alarms go off... and hence the search for same landed me here.

mentioning it in documentation or adding a comment in the generated migration would be helpful.

**Comment by Cikmo** [comment]
I really want to bump this issue. This seems like a major security concern.

If I understand correctly, the way around this is to have a migration for the table creation separately from the policy creations?

**Comment by nettum** [comment]
Agree with the above concerns and ended up here because of it. I did follow [this guide](https://supabase.com/docs/guides/local-development/declarative-database-schemas) to set up schema and migrations correctly from the start and got a bit puzzled when all the grant statements was added to the migration file. A mention in the documentation would be nice.

**Comment by galacticgibbon** [comment]
I was able to fix this by adding the roles to the schema... 

```
create table "profiles" (
  "id" text primary key,
);

REVOKE ALL ON TABLE public.profiles FROM anon, authenticated;
GRANT ALL ON TABLE public.profiles TO service_role;

```

This generates a migration that only includes the grant on service_role. Or you could revoke all of them if you prefer.

**Comment by Mehdi-Verfaillie** [comment]
This is an awful behaviour that lead to grant "haunting". Here what's happen if you create custom grants, let's take the rbac exemple:

1 - You create your tables
2 - You generate a migration
3 - Now you got 40+ lines of auto generated grants under your table definition

```
grant truncate on table "public"."role_permissions" to "authenticated";
grant update on table "public"."role_permissions" to "authenticated";
grant delete on table "public"."user_roles" to "anon";
-- ...40+ more lines
```

4 - For the rbac exemple, you need to add custom grants so you do:

```
GRANT ALL ON TABLE public.user_roles TO supabase_auth_admin;
GRANT ALL ON TABLE public.role_permissions TO supabase_auth_admin;
REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;
REVOKE ALL ON TABLE public.role_permissions FROM authenticated, anon, public;
```

5 - Now, guess what, you want to move on the next migration, let's say you want to add a new enum so you expect:

`create type "public"."locale" as enum ('en', 'fr', 'bg');` to be generated.

but you got your diff tool trying to override your custom grants.

```
create type "public"."locale" as enum ('en', 'fr', 'bg');

revoke delete on table "public"."role_permissions" from "supabase_auth_admin";
revoke insert on table "public"."role_permissions" from "supabase_auth_admin";
revoke references on table "public"."role_permissions" from "supabase_auth_admin";
grant truncate on table "public"."role_permissions" to "authenticated";
grant update on table "public"."role_permissions" to "authenticated";
grant delete on table "public"."user_roles" to "anon";
-- ...40+ more lines
```

**and for every single migration you will do in the futur**, you keep having your diff tool trying to override your custom grants, getting mixed with other grants when you end up creating new tables. Now every single migration is a pain to manually fix.

**Comment by Almopt** [comment]
> This is an awful behaviour that lead to grant "haunting". Here what's happen if you create custom grants, let's take the rbac exemple:
> 
> 1 - You create your tables 2 - You generate a migration 3 - Now you got 40+ lines of auto generated grants under your table definition
> 
> ```
> grant truncate on table "public"."role_permissions" to "authenticated";
> grant update on table "public"."role_permissions" to "authenticated";
> grant delete on table "public"."user_roles" to "anon";
> -- ...40+ more lines
> ```
> 
> 4 - For the rbac exemple, you need to add custom grants so you do:
> 
> ```
> GRANT ALL ON TABLE public.user_roles TO supabase_auth_admin;
> GRANT ALL ON TABLE public.role_permissions TO supabase_auth_admin;
> REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;
> REVOKE ALL ON TABLE public.role_permissions FROM authenticated, anon, public;
> ```
> 
> 5 - Now, guess what, you want to move on the next migration, let's say you want to add a new enum so you expect:
> 
> `create type "public"."locale" as enum ('en', 'fr', 'bg');` to be generated.
> 
> but you got your diff tool trying to override your custom grants.
> 
> ```
> create type "public"."locale" as enum ('en', 'fr', 'bg');
> 
> revoke delete on table "public"."role_permissions" from "supabase_auth_admin";
> revoke insert on table "public"."role_permissions" from "supabase_auth_admin";
> revoke references on table "public"."role_permissions" from "supabase_auth_admin";
> grant truncate on table "public"."role_permissions" to "authenticated";
> grant update on table "public"."role_permissions" to "authenticated";
> grant delete on table "public"."user_roles" to "anon";
> -- ...40+ more lines
> ```
> 
> **and for every single migration you will do in the futur**, you keep having your diff tool trying to override your custom grants, getting mixed with other grants when you end up creating new tables. Now every single migration is a pain to manually fix.

So what's the workaround or the solution for this issue?

**Comment by Magnuti** [comment]
No fix yet? Seeing 20 lines of these statements for every new table is very confusing.

```
grant delete on table "public"."example" to "anon";

grant insert on table "public"."example" to "anon";

grant references on table "public"."example" to "anon";

...
```

How do we change default privileges (and should we)? As noted in https://github.com/supabase/supabase/pull/33722

I just started a new project with the Data API disabled and created a new table locally and then used the diff tool.

With the Data API disabled it does not make sense that the diff tool gives grants to all the different roles/users.

**Comment by nettum** [comment]
I regularly get back to this issue as I still find these grants confusing. 

Is the following true?

1) If you create a table and then create a migration, you might end up with the following in your migration file (same grants for `authenticated` and `service_role`) :
```
grant delete on table "public"."your_table" to "anon";
grant insert on table "public"."your_table" to "anon";
grant references on table "public"."your_table" to "anon";
grant select on table "public"."your_table" to "anon";
grant trigger on table "public"."your_table" to "anon";
grant truncate on table "public"."your_table" to "anon";
grant update on table "public"."your_table" to "anon";
```
2) As long as the same migration have `alter table "public"."your_table" enable row level security;` and you **do not** create any RLS policies you are safe - only the service role will be able to do all grants above?

3) `anon`, `authenticated` or any other role except `service_role` will not have access to data or are able to harm `public.your_table`?

After doing some tests with at least `anon_key` and `service_role_key` from the js sdk and the REST API this seems to be the case.

For me, this is still not clear from the docs.

Edit: I follow the [Declarative database schemas](https://supabase.com/docs/guides/local-development/declarative-database-schemas) when creating new tables or doing schema changes as I want all my changes and migrations to be documented and predictable with git history and deployment / migrations with github actions. This way all changes should be easy to  follow between developers. NO manual setup in the dashboard UI or deployments/migrations against remote databases from local machines.
