### ISSUE TITLE
Supabase failing to build in Github Actions CI process

### ISSUE THREAD

**Issue by AM-colee** [supabase/cli#1872]
**Describe the bug**
There seems to be an issue requiring the local environment to either be logged in or the SUPABASE_ACCESS_TOKEN to be set locally. This specifically affects the tests ran on PRs using the "CI" github workflow as per the official configuration (link included in reproduction steps).

Having re-ran this against various versions it seems to work against 1.133.3 however fails on 1.134.0
Changes made between releases:
https://github.com/supabase/cli/compare/v1.133.3...v1.134.0

**To Reproduce**
When using the github actions defined in the follow configuration:
https://supabase.com/docs/guides/cli/managing-environments?environment=ci#configure-github-actions

Create a PR to the your CI process enabled repo and your github action will fail with the following error:
`Access token not provided. Supply an access token by running supabase login or setting the SUPABASE_ACCESS_TOKEN environment variable.`

**Expected behavior**
You should not need to have logged into supabase cli or provided an access token for running tests locally in the CI environment.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A - uses a github action runner specs:

> steps:
>   \- uses: actions/checkout@v3
>   \- uses: supabase/setup-cli@v1
>     with:
>       version: latest

**Additional context**
Workaround for those experiencing this issue is to update the jobs section of your .github/workflows/ci.yml file to start with:
> steps:
>   \- uses: actions/checkout@v3
>   \- uses: supabase/setup-cli@v1
>     with:
>       version: 1.133.3

**Comment by sweatybridge** [comment]
Do you have the `SUPABASE_PROJECT_ID` set as env var or have run `supabase link` before start?

Based on the linked commits, the failure could be due to cli picking up stale project id.

Let me know if removing the env var works for you, so at least we can confirm the problem before I push a fix.

**Comment by AM-colee** [comment]
Sorry, I'm not sure what you mean. From my understanding the Github CI action is setting up a machine to locally run supabase and the tests. As far as I know it should not be reaching to any other environment so would have no need for a project id or linking.

The step it fails on is:
>\- name: Start Supabase local development setup
>run: supabase start

I have confirmed there is no environment set as part of the script so it should not get any environment configurations from github and there is no supabase link command ran as part of the CI.yml file. Not sure what the changes were between 1.33.3 and 1.134 but if it was an issue with an environment variable would it not fail on 1.133.3 as well or was there a change in how environments are handled?

The github action defines it's system as follows in case it is of any use:

>runs-on: ubuntu-latest
>
>steps:
>\- uses: actions/checkout@v3

**Comment by sweatybridge** [comment]
Sorry if it wasn't clear. The new behaviour is to call our api to check the project's service versions only when a project id is provided. If you haven't linked a project, it should not be making this api call at all.

That's why I believe your CI workflow must be picking up the project id from somewhere unintentionally. Perhaps a stale file in `supabase/.temp/project-ref` or the env var.

That said, the cli should be handling such stale files more gracefully. So regardless of the root cause, I will make patch cli to not throw an error here.
