### ISSUE TITLE
The default answer for `supabase db reset --linked` should not be `Y`

### ISSUE THREAD

**Issue by DanEEStar** [supabase/cli#1875]
**Is your feature request related to a problem? Please describe.**
I used the command `supabase db reset --linked` for the first time. I was suprised that the default answer is "Yes". In my opinion it should be "No" to at least prevent the `reset` when I accidently run the command and just pressed "enter".

**Describe the solution you'd like**
The line 54 in reset.go
```
if shouldReset := utils.PromptYesNo("Confirm resetting the remote database?", true, os.Stdin); !shouldReset {
```
sould become 
```
if shouldReset := utils.PromptYesNo("Confirm resetting the remote database?", false, os.Stdin); !shouldReset {
```

**Describe alternatives you've considered**
No alternative

**Comment by Ninjeneer** [comment]
I totally agree with this one, destructive actions should never be authorized by default

**Comment by tobiastornros** [comment]
Any plans to add `--force` or `--yes` to this command @sweatybridge? Trying to use it in github action to reset staging every night.

**Comment by sweatybridge** [comment]
You can pipe yes / no to cli via stdin. For eg.

```bash
yes | supabase db reset --linked
```

**Comment by tmountain** [comment]
We're piping yes now, but it does seem like a command-line arg is the right way.

**Comment by sweatybridge** [comment]
> Is there a better way to roll out breaking changes to core tools?

Perhaps the CLI can print the suggested replacement command on such breaking changes in the future. So at least it's more straightforward to fix any broken builds.

In this case, we had to fix it sooner than later to prevent more users from accidentally deleting prod data.

**Comment by hnykda** [comment]
I made it into a new feature request: https://github.com/supabase/cli/issues/2341
