### ISSUE TITLE
Migrations are difficult to maintain with a team

### ISSUE THREAD

**Issue by otang** [supabase/cli#1882]
**Is your feature request related to a problem? Please describe.**
Supabase seems to crash unless all new migration files have a newer timestamp than *any previously run migration*. This makes it difficult when working with a team of multiple devs, all creating independent migrations on feature branches throughout the week.

**Describe the solution you'd like**
Other migration frameworks, like Knex, can handle consolidating any migrations that haven't been run yet, even if they may be dated older than a previously committed migration.

**Describe alternatives you've considered**
I am considering switching to knex or another tool to manage the migrations.

**Comment by sweatybridge** [comment]
If you are talking about db push command, there's a flag `--include-all` to apply out of order migrations to your remote database.

When developing locally, the same flag exists for migration up command.

But I do agree managing timestamp is tedious. We have internal RFC for moving towards a declarative schema.sql with generated migration files. Hopefully it will be less burdensome after adopting declarative schema.

**Comment by otang** [comment]
@sweatybridge the flag seems promising! `supabase/setup-cli@v1 version: 1.28.3` doesn't seem to recognize it though.

![image](https://github.com/supabase/cli/assets/800081/403336ea-b445-45ae-9914-173967d5fa3f)
![image](https://github.com/supabase/cli/assets/800081/0b09d539-dac7-4dca-8a9c-30925ce5823f)
![image](https://github.com/supabase/cli/assets/800081/28906d13-2fa2-487b-8507-dc09a23f6676)

**Comment by sweatybridge** [comment]
You can customise the version installed by setup-cli. For eg.

```yaml
with:
  version: latest
```

It's been a while since we updated the default version though. So I will make a separate release for that.

**Comment by otang** [comment]
@sweatybridge it worked! This solutions is perfect for us. Thank you. You can close this issue if you'd like
