### ISSUE TITLE
supabase/postgres image fails to start after updating to 15.1.0.147

### ISSUE THREAD

**Issue by jakobskytte** [supabase/cli#1892]
**Describe the bug**
After I updated the CLI to the latest version and run `supabase start`, it just gets stuck at `Starting database from backup`.

When I check the logs from the docker container I see the following error:

![image](https://github.com/supabase/cli/assets/25202811/e036e29e-8a4c-4580-8621-9e5a2123cc62)

![image](https://github.com/supabase/cli/assets/25202811/f2cbac3a-1425-461a-8723-8dd5dbf0065d)

I noticed that this doesn't happen if I go back to a version of the CLI that uses an older image than 15.1.0.147 for postgres.

Any idea what might be causing this?

**Desktop (please complete the following information):**
 - OS: Windows (Running on WSL 2.0 with Ubuntu 20.04.6 LTS)
 - Version of CLI: 1.136.3

**Comment by sweatybridge** [comment]
I suspect this is caused by reusing the same postgres config docker volume between postgres versions. You should be able to remove the config volume by running `supabase stop --no-backup`. After that, `supabase start` should work.

Note that this will delete any data in the local database as well. So if you have any WIP changes, you want to dump them to either a migration or a seed file first before stopping.

**Comment by jakobskytte** [comment]
Here's what I have tried so far without success 
1. `supabase stop --no-backup` then `supabase start`
2. Deleted the volume completely from docker
3. Deleted the config.toml and doing `supabase init` again

Still getting the same error from Docker as mentioned in the inital post.

**Comment by jakobskytte** [comment]
Running these 3 commands in Docker made it work again.

`docker system prune `

`docker system prune`

`docker volume rm $(docker volume ls -qf dangling=true`

**Comment by sweatybridge** [comment]
Thanks for the diagnosis. For future reference, we recently changed the way supabase stop creates and deletes volumes. So if the dangling volume was created by an old version of cli, newer version of cli may not be able to delete them.
