### ISSUE TITLE
Local UI does not work in Windows Subsystem For Linux (WSL2)

### ISSUE THREAD

**Issue by ezynda3** [supabase/cli#19]
# Bug report

## Describe the bug
After running `supabase init` and `supabase start` and then going to the specified `Supabase URL`, instead of displaying the UI, I receive a JSON repsponse:

```
{
"message": "no Route matched with those values"
}
```

## To Reproduce
With WSL2 properly setup and Docker Desktop with `Use the WSL 2 based engine` enabled in settings, run `supabase init` and `supabase start` in a WSL2 terminal. Finally navigate to the `Supabase URL` shown in the terminal after `supabase init`.

## Expected behavior

I should see the Supabase UI

## System information

- OS: Windows 10 (with WSL2)
- Browser chrome
- Version of supabase-cli: 3.0.6
- Version of Node.js: v14.15.3

**Comment by ezynda3** [comment]
Actually just after reading the docs again, it looks like there is no UI associated with local dev? 😅 If that's the case, I'll go ahead and close this issue.

**Comment by kiwicopple** [comment]
No local dashboard yet sorry @ezynda3 ! (a bit more context [here](https://github.com/supabase/supabase/discussions/1001#discussioncomment-558696))

I'll update the docs today to make this clearer.

**Comment by ezynda3** [comment]
Awesome. Thanks for all the hard working and shipping all of this stuff so quickly!
