### ISSUE TITLE
supabase link doesn't work

### ISSUE THREAD

**Issue by oungo** [supabase/cli#1902]
**Describe the bug**
```supabase link --project-ref <project-id>``` doesn't work.
I'm running supabase locally using docker.
```supabase start``` working successfully.
If I do something in local dashboard, and ```supabase db reset``` ok.
But when I tried to link my project, it failed with error.

**To Reproduce**
1. Type ```supabase link --project-ref <project-id>```

**Expected behavior**
supabase link project

**Screenshots**
This is the error when I called ```supabase link --project-ref <project-id> --debug```

```2024/02/01 08:45:55 Connect Start: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543
2024/02/01 08:45:55 Connect Error: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543 dial tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543: connect: no route to host
2024/02/01 08:45:55 Connect Start: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543
2024/02/01 08:45:55 Connect Error: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543 dial tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:6543: connect: no route to host
Retrying... db.uisrpvsazlvutgmbqhuy.supabase.co 5432
2024/02/01 08:45:55 Connect Start: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432
2024/02/01 08:45:55 Connect Error: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432 dial tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432: connect: no route to host
2024/02/01 08:45:55 Connect Start: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432
2024/02/01 08:45:55 Connect Error: tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432 dial tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432: connect: no route to host
failed to connect to `host=db.uisrpvsazlvutgmbqhuy.supabase.co user=postgres database=postgres`: dial error (dial tcp [2406:da12:b78:de03:4fe3:351e:99dd:6a75]:5432: connect: no route to host)
```

**Desktop (please complete the following information):**
 - OS: mac OS
 - Version of CLI: 1.110.1
 - Version of Node.js: v18,16.0

**Comment by sweatybridge** [comment]
Are you able to upgrade cli to latest 1.136.3 and try again?

Alternatively you need to setup your local network to be IPv6 addressable since We migrated all projects to ipv6 recently.

**Comment by oungo** [comment]
@sweatybridge it works well! thank you
