### ISSUE TITLE
relation "public.otherfacilities_id_seq" does not exist using Kotlin

### ISSUE THREAD

**Issue by arbyruns** [supabase/cli#1929]
**Describe the bug**
I've updated from supabase `1.4.7` to the latest `2.1.3` and now when posting data I get the following error `: relation "public.otherfacilities_id_seq" does not exist`

**To Reproduce**
configure code to `insert` data like so
```kotlin
val city = City(name = "The Shire", countryId = 554)
supabase.from("otherFacilities").insert(city)
```

My code being used:
```kotlin
        return try {
            supabase.from(Constants().supaBaseOtherFacility)
                .insert(otherFacilityDto)
            true
        } catch (e: java.lang.Exception) {
            Log.e("postOtherFacilityPost", "error $e")
            return false
        }
```

**Expected behavior**
Be able to insert data

**System information**
Returns the following error:
`io.github.jan.supabase.exceptions.NotFoundRestException: relation "public.otherfacilities_id_seq" does not exist`

**Additional context**
If applicable, add any other context about the problem here.
 - Kotlin SDK
 - Version of supabase-js [e.g. v2.1.3]
- Running the same SDK version on iOS and I don't have any issues

**Comment by arbyruns** [comment]
I was able to get this solved over in discord, but the issue was because I'm always passing in an ID, but had `Automatically assign a sequential unique number to the column` checked. I removed the check

What it's interesting is that I don't have any issues with the Swift library

**Comment by sweatybridge** [comment]
Thanks for reporting. Are the clients connecting to the same database / project? Another possibility is their schemas are different. Otherwise this seems like an inconsistency with different client libraries.

**Comment by arbyruns** [comment]
Same tables and same database with public schemas. I have three tables and the issue was occurring with each one.
