### ISSUE TITLE
`supabase deploy` inconsistent state error

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1934]
**Describe the bug** 

Since v1.136.2 at least, running `supabase functions deploy` has been giving issues where the function seems to be deployed successfully but we always get a 500 response when we call the edge function. This deployment is happening from our GH actions workflow using the [setup-cli](https://github.com/supabase/setup-cli) action with the necessary permissions and project ID, which worked for previous CLI versions.

I'm not sure what the `supabase/setup-cli` is doing internally, it seems like it is running a docker container rather than the deploy command on the workflow runner host. When we call the edge function, we get 500 errors, with no logs generated in the dashboard, only the invocation error (see screenshot)

The current solution to this is that we have to manually deploy from our main branch locally into supabase with the same cli command.

**To Reproduce**

1. Setup GH actions with supabase/setup-cli to run `supabase function deploy`
2. Deploy a function with the `supabase functions deploy`
3. Call the function endpoint.

**Expected behavior**

Independent of the environment, the deploy function successfully deploys and is available for use.

**Screenshots**

<img width="700" alt="image" src="https://github.com/supabase/cli/assets/44002321/a26cb76b-09fe-4582-b180-b5370ab8cbf4">

**System information**
 - Version of CLI: 1.142.2

**Additional context**
 - Version of supabase/setup-cli: v1.3.0

**Comment by sweatybridge** [comment]
Can't seem to reproduce. The next time it happens, could you file a support ticket attaching the erroneous eszip bundle downloaded from v1 api?

```bash
curl -H 'authorization: Bearer <access_token>' \
https://api.supabase.com/v1/projects/<ref>/functions/<slug>/body -o bin.eszip
```

Appreciate your help.
