### ISSUE TITLE
failed to pull docker image

### ISSUE THREAD

**Issue by jdgamble555** [supabase/cli#1938]
**Describe the bug**
When I run `supabase start` I get this error:
```
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.139.2-rc.7
not found: manifest unknown: Requested image not found
```

**To Reproduce**
Install the latest version of supabase:
```
"supabase": "^1.142.2",
```

**Expected behavior**
No errors

**System information**
Rerun the failing command with `--create-ticket` flag (preferred).
 - Ticket ID: cf89590c829d4353bb8226495c762c88
 - OS: Windows 11
 - Version of CLI: 1.142.2
 - Versions of services: 
 ```
        SERVICE IMAGE      │        LOCAL         │    LINKED
  ─────────────────────────┼──────────────────────┼───────────────
    supabase/postgres      │ 15.1.0.137           │ 15.1.0.137
    supabase/gotrue        │ 2.139.2-rc.7         │ 2.139.2-rc.7
    postgrest/postgrest    │ v11.2.2              │ v11.2.2
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.46.5              │ v0.46.5
    supabase/edge-runtime  │ v1.33.5              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

J

**Comment by jdgamble555** [comment]
So I temporarily fixed it by removing the version in `supabase/.temp/gotrue-version`, however, it still wants to link to a non-existent version:

```
You are running outdated service versions locally:
supabase/gotrue:v2.132.3 => 2.139.2-rc.7
Run supabase link to update them.
```

Should the cloud version be using a version that is not downloadable?

J

**Comment by sweatybridge** [comment]
It looks like we don't have version 2.139.2-rc.7 published on [docker hub](https://hub.docker.com/r/supabase/gotrue/tags?page=1&name=2.139.2). I will ping our auth team to take a look. Sorry for the inconvenience.

**Comment by pidanou** [comment]
I have somewgat the same issue with gotrue:2.142.0

`docker pull public.ecr.aws/supabase/gotrue:2.142.0` works fine 
but when i run `supabase start` i have:

```
failed to pull docker image: invalid reference format
Retrying after 8s: public.ecr.aws/supabase/gotrue:2.142.0

failed to pull docker image: invalid reference format
```

**Comment by Mikodin** [comment]
We're in the same boat over here
https://github.com/supabase/supabase/issues/21300



> So I temporarily fixed it by removing the version in `supabase/.temp/gotrue-version`, however, it still wants to link to a non-existent version:
> 
> ```
> You are running outdated service versions locally:
> supabase/gotrue:v2.132.3 => 2.139.2-rc.7
> Run supabase link to update them.
> ```
> 
> Should the cloud version be using a version that is not downloadable? This breaks the link.
> 
> J

This worked, all I had to do was add a `v` in the front

**Comment by stefan-girlich** [comment]
@Mikodin  Changing to `v2.142.0` causes a new error for me; please let me know if you experienced something similar.

```
➜  supabase db pull
Connecting to remote database...
Setting up initial schema....
failed to pull docker image: invalid reference format
Retrying after 4s: public.ecr.aws/supabase/gotrue:v2.142.0
```

**Comment by sweatybridge** [comment]
Can you try deleting any new line characters in the version file? I will also update the code to handle this better

**Comment by stefan-girlich** [comment]
@sweatybridge Sorry - I accidentally deleted my previous content; restoring it below:

I am getting a new error after hotfixng `supabase/.temp/gotrue-version` to include the "v" character:

´´´
➜  supabase db pull
Connecting to remote database...
Setting up initial schema....
failed to pull docker image: invalid reference format
Retrying after 4s: public.ecr.aws/supabase/gotrue:v2.142.0
```

@sweatybridge It seems there are no newline characters in the file. I will check if vim left any kind of control characters.

**Comment by gillesmag** [comment]
I just ran into the same issue, pulling the image without the `v` tag prefix and tagging the image with the expected image name worked for me.

```
docker pull public.ecr.aws/supabase/gotrue:v2.142.0
docker tag public.ecr.aws/supabase/gotrue:v2.142.0 public.ecr.aws/supabase/gotrue:2.142.0
```

**Comment by jdgamble555** [comment]
@sweatybridge - I'm still getting the error:
```
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.139.2-rc.7 
not found: manifest unknown: Requested image not found
```
When running `npx supabase start`. Your team has not added it yet.

J

**Comment by jdgamble555** [comment]
Yes, I'm using `1.142.2`.

**Comment by jdgamble555** [comment]
No because then it will ask me to relink. That is not the version installed on the cloud.

**Comment by gillesmag** [comment]
<img width="826" alt="Screenshot 2024-02-16 at 13 54 58" src="https://github.com/supabase/cli/assets/664445/9460e691-ec60-4077-8f59-6523092badcc">

It is for my project. I reran `supabase link` (which did nothing since my versions are all synced) and `supabase start` works fine for me now. I created the project on supabase a couple of hours ago so that might be why I don't have the gotrue version issue that you're mentioning.

**Comment by jdgamble555** [comment]
Yes, I can upgrade my project, but that doesn't fix the underlying problem.

**Comment by jdgamble555** [comment]
@sweatybridge - There is definitely a bug here.  I **upgraded** my supabase project by going to settings, infrastructure. I am now using the latest version.

The problem is a bug with `supabase link`.  It does not seem to add the `v` to `v2.142.0`.
```
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.142.0 
not found: manifest unknown: Requested image not found
```
I can add the `v` to it so that it is `v2.142.0`, but then I get this `error` when running `supabase start`:
```
You are running outdated service versions locally:
supabase/gotrue:v2.142.0 => 2.142.0
```
Obviously they are the same version, but `supabase start` does not realize this because the code does not take the `v` into account. This is a problem and a bug with `supabase link` AND `supabase start`.

J

**Comment by sweatybridge** [comment]
Turns out the `v` prefix was accidentally dropped from gotrue's `/health` endpoint response but the docker tag was still `v2.142.0`. There's an [upstream PR](https://github.com/supabase/gotrue/pull/1434) to fix it. Once it's rolled out, running link and start should work again.

**Comment by stefkudla** [comment]
I could not get any of the older versions or fixed mentioned above to work unfortunately, as this issue just started happening for me today. Deleting the `supabase/.temp/gotrue-version` file worked for me
