### ISSUE TITLE
Supabase self hosting: error in realtime on IPv4 devices.

### ISSUE THREAD

**Issue by Yogesh7920** [supabase/cli#1940]
**Describe the bug**
My device has IPv6 disabled so I changed the "ip_version" to "IPv4" but still it's not working. 
I am getting the following error
![image](https://github.com/supabase/cli/assets/55453812/fbd34f20-b372-43f6-950f-acfcd07e1950)

My config.toml
![image](https://github.com/supabase/cli/assets/55453812/6a696ed4-b80b-466c-ba9f-3ce78a1c9241)

Commands tried:
1. supabase start
2. npx supabase@beta start

**To Reproduce**
1. Try to self host in a machine with IPv6 disabled.

**Expected behavior**
You will find the following error in realtime
![image](https://github.com/supabase/cli/assets/55453812/2e7375b7-10f5-45b7-a395-9772d5082036)

**Comment by sweatybridge** [comment]
Looks like this env var was recently deprecated without maintaining backwards compatibility https://github.com/supabase/realtime/pull/779

I will ping the realtime team to take a closer look. Apologies for the inconvenience.

**Comment by sweatybridge** [comment]
Closing as resolved by upstream
