### ISSUE TITLE
`supabase start` and `supabase stop` not working as expected

### ISSUE THREAD

**Issue by BoscoDomingo** [supabase/cli#1942]
**Describe the bug**
Anytime you try to operate on the local database after a PC restart, you get the `supabase start is not running.` error, even though the containers are up.

If you do run `supabase start` as expected you get an error.
If you run `supabase stop [--no-backup]` it gives no errors, but doesn't do anything.
If you run `supabase start` again you get `failed to start docker container: Error response from daemon: driver failed programming external connectivity on endpoint supabase_db_[PROJECT_ID] (...): Bind for 0.0.0.0:54322 failed: port is already allocated`

The only way to solve this is to manually stop the containers yourself

**To Reproduce**
1. Have supabase running locally, restart PC (could be restarting docker suffices) and start docker
2. Run any supabase command -> Error
3. `supabase stop`
4. `supabase start`

**Expected behavior**
For containers to be correctly recognised as running automatically, as well as to stop when using `supabase stop`

**Screenshots**
![image](https://github.com/supabase/cli/assets/46006784/52970f5d-3f38-461f-a95c-94905b85294e)

**System information**
Rerun the failing command with `--create-ticket` flag (preferred).
 - Ticket ID: ecbca492c1f04e599e05d9b88ac0bf56

**Comment by sweatybridge** [comment]
Have you tried the suggested command with --project-id flag?

**Comment by BoscoDomingo** [comment]
@sweatybridge We recently changed the local project name due to #1922, which could've caused this. I just manually reset the containers, but I'll test stopping the db with the `--project-id` flag next time around
