### ISSUE TITLE
db dump fails with "Network is unreachable" error message

### ISSUE THREAD

**Issue by hypercomputer** [supabase/cli#1944]
**Describe the bug**
I have been attempting to use the `supabase db dump` command to records some changes to my schema that I made within the Supabase web UI, but every time I run it I get the following error message (I altered the IPv6 address in the output):

```
pg_dump: error: connection to server at "db.MY_PROJECT_REFERENCE_ID.supabase.co" (2600:1f18:2e13:9d02:9512:fb9:1234:abcd), port 5432 failed: Network is unreachable
        Is the server running on that host and accepting TCP/IP connections?
```

It seems that I am not the only one encountering a similar issues as I found the [following recent complaint](https://www.reddit.com/r/Supabase/comments/1aiu28s/db_dump_network_unreachable/) via the Supabase subreddit.

**To Reproduce**
1. From a terminal run `sudo supabase db dump --schema public -f path/to/output.sql`
2. Provide the correct admin and DB password at the prompts
3. Observe the error message:
```
pg_dump: error: connection to server at "db.MY_PROJECT_REFERENCE_ID.supabase.co" (2600:1f18:2e13:9d02:9512:fb9:1234:abcd), port 5432 failed: Network is unreachable
        Is the server running on that host and accepting TCP/IP connections?
```

**Expected behavior**
The DB schema is written to the specified file.

**System information**
Rerun the failing command with `--create-ticket` flag (preferred).
 - Ticket ID: ce9a7284cf6548a1a36423a23f31858b
 - OS: Ubuntu
 - Version of CLI: v1.142.2
 - Versions of services:
 ```
         SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼───────────
    supabase/postgres      │ 15.1.0.147           │ 15.1.1.9
    supabase/gotrue        │ v2.132.3             │ v2.132.3
    postgrest/postgrest    │ v12.0.1              │ v12.0.2
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.46.4              │ v0.48.1
    supabase/edge-runtime  │ v1.33.5              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```
**Additional context**
This is the first time I have encountered issues running this command. It worked for me previously without issues many times.  In order to attempt to resolve the issue I updated my CLI version from 1.91.3 to 1.142.2, but the error was present across versions. Is the issue possibly related to the IPv6 migration?

**Comment by sweatybridge** [comment]
Hello, have you tried relinking your project before db dump? CLI fetches the pooler url after linking successfully so that subsequent commands can connect via IPv4.

**Comment by hypercomputer** [comment]
Ah, thank you! I just tried that and now I am able to use the CLI properly again. Thanks for the help.
