### ISSUE TITLE
Request for opening `postgREST` server to a local machine port

### ISSUE THREAD

**Issue by DhenPadilla** [supabase/cli#1958]
**Is your feature request related to a problem? Please describe.**

Not a _problem_ per se. But I was looking to try a query on the `postgrest` api server and I couldn't find any way to do this via the config currently.
What I'm attempting to do is quite involved; but for context: we have a JSONB column in our DB that holds a `text[]` value.

Namely; I want to run a `WHERE col_name->'array_key' ?| ['input_array',...]` query filter but from my understanding, this isn't available in the supabase `postgrest-js` package. (I also opened a separate request in that repo.).

**Describe the solution you'd like**

It would be nice if the `supabase_rest_app` could be opened to the local machine somehow so I can run a query directly against the supabase `postgREST` server.

Currently it's opened within the docker-image as `3000/tcp` but hoping to get something like: `localhost:11111->3000/tcp` so  I can then query with:
`localhost:11111?=queryhere`

Not sure if there is a solution for this already, but would be good to do this without having to mess with any docker compose anywhere

**Comment by sweatybridge** [comment]
The `PostgREST` server is accessible from http://localhost:54321/rest/v1/

It doesn't have a dedicated port mapping because we use kong as a proxy https://github.com/supabase/cli/blob/main/internal/start/templates/kong.yml#L45
