### ISSUE TITLE
Error "server error (FATAL: Address not in tenant allow_list:" 

### ISSUE THREAD

**Issue by easwar-sevanun** [supabase/cli#1966]
Bug
While trying db push or db link i am getting Error "server error (FATAL: Address not in tenant allow_list:". Even after removing network restrictions, still getting the error message

Steps
Tried connecting the db through Supabase link CLI command. after selecting server and entering password. i am getting the above error message. i removed all network restrictions too. still getting same issue.

Crash ID: d3bf6c60bb39444d9a957811037d75f9

**Comment by sweatybridge** [comment]
Have you tried `Allow all access` from the network restrictions section on the dashboard? https://supabase.com/dashboard/project/_/settings/database

I don't think CLI supports resetting the network restrictions once you've updated it.

**Comment by easwar-sevanun** [comment]
I am not resetting the network restrictions in CLI. I am only running the migration commands, its not allowing me to connect due to network restrictions.

I update the network restrictions through https://supabase.com/dashboard/project/_/settings/database. Even after that my CLI is not allowing me to connect.

I hope you understand the problem. Please check the crash ID, should be get some information.


Thanks and Regards
Easwar
+91 99944 03421
[cid:2e6d5ff5-244f-46e2-a06b-9e5eadf440a7]
[cid:56a312a7-db6c-45fb-bc72-67f357742ead]<https://dunsregistered.dnb.com/DunsRegisteredProfileAnywhere.aspx?Key1=3175797&PaArea=Email>
________________________________

**Comment by sweatybridge** [comment]
I do see network restrictions still applied to your project

```
{"config":{"dbAllowedCidrs":["0.0.0.0/0"],"dbAllowedCidrsV6":["::/0"]},"status":"applied","entitlement":"allowed"}
```

Could you share a screenshot of your dashboard page? It should look exactly like the screenshot below
![Screenshot 2024-02-20 at 7 21 21 PM](https://github.com/supabase/cli/assets/1639722/033e1277-a222-4ad7-a036-03cf1720f7b2)

Otherwise, please double check your network settings to `Allow all access`.

Also, you might want to run `projects list` locally to make sure you are linked to the right project.

**Comment by easwar-sevanun** [comment]
Thanks for reverting back. Here is the screenshot.

[cid:990ad671-cf86-4ce2-a215-b3e1d1be0e5b]

Also i checked the projects lists, its linked to the correct project.


Thanks and Regards
Easwar
+91 99944 03421
[cid:f0004bec-d7d1-4210-9219-af6e23122127]
[cid:ee8355bd-3d78-4789-980d-a7b6ab67c1d7]<https://dunsregistered.dnb.com/DunsRegisteredProfileAnywhere.aspx?Key1=3175797&PaArea=Email>
________________________________

**Comment by sweatybridge** [comment]
Your screenshot might not be uploaded successfully.

Are you able to connect via `psql <connection-string>`?

If this problem persists, it's probably best to file a [support ticket](https://supabase.com/dashboard/support/new) because I can successfully connect from my side.

**Comment by easwar-sevanun** [comment]
Thank you for follow-up. But this seems an intermittent issue at Supabase. It’s resolved now.
    Regards Easwar
  

 From: Han Qiao ***@***.***>Sent: Tuesday, February 20, 2024 9:45 PMTo: supabase/cli ***@***.***>Cc: Easwaramoorthy Damodaran ***@***.***>; Author ***@***.***>Subject: Re: [supabase/cli] Error "server error (FATAL: Address not in tenant allow_list:" (Issue #1966) 
Your screenshot might not be uploaded successfully.
Are you able to connect via psql <connection-string>?
If this problem persists, it's probably best to file a support ticket because I can successfully connect from my side.
