### ISSUE TITLE
Ability to lock the seed file to a migration version

### ISSUE THREAD

**Issue by lauri865** [supabase/cli#1973]
**Is your feature request related to a problem? Please describe.**
I don't know how others manage this, but I'm often encountering a chicken and egg problem working with migrations and seed file locally, especially if we're manipulating existing structures which may sometimes involve transforming existing data, casting types, etc.

Let's say we need to rename a column:
1. Add a migration that renames a column
2. Apply a migration – works, great
3. Push the migration
4. Reset the DB to make sure everything works on a clean run, and that the migration didn't only run because we manually edited some data or forgot some other changes.
5. Crap, reset doesn't work, because seed file with untransformed data structure. Now we need to manually remove relevant migration files, reset the database, and apply the migrations again. Or generate a new seed file after each migration, but that makes things a lot more brittle and create a state discrepancy between local vs. prod, whereby migrations may fail in production.

There are other use cases as well, where you want to change your approach, and have to manually move around things and lose a lot of time in the process. The whole process makes you avoid making any mistakes, and discourages any real experimentation and breaking things (which should be highly encouraged to not end up breaking things in prod).

The overarching problem is that it's difficult to develop and test migrations that need to manipulate existing structures and data.

**Describe the solution you'd like**
Would love to lock the seed file to a migration version. Say locking seed file to a migration version e.g. `1322837510`. So, when I run `supabase db reset`, first migrations are run until version `1322837510`, then seed file is loaded, and then the rest of the migrations will be added (or have to be invoked with manually with `supabase migration up` – the former would be more foolproof, but this would still be an improvement). 

**Describe alternatives you've considered**
Having a working directory for "development" migrations that won't be loaded automatically by `supabase db reset`. E.g. postgraphile's migration tool has a `current.sql` file.

But would love to hear how other people are working with this.

**Comment by lauri865** [comment]
Could be even locked to the migration version of the linked project by default. Or have a CLI command to fetch the current version.

**Comment by sweatybridge** [comment]
> when I run supabase db reset, first migrations are run until version 1322837510, then seed file is loaded

We thought about `<timestamp>_seed.sql` files before but decided against it because it's incompatible with the eventual goal of supporting declarative schema. Some prior arts in this area include
- https://github.com/stripe/pg-schema-diff
- https://github.com/ariga/atlas

Instead, I would recommend keeping `seed.sql` up to date with latest schema using the following approach.

1. Resets local database to the last version compatible with seed.sql
2. Migrate the seeded database locally
3. Regenerate the seed file from local dump

```bash
supabase db reset --version 1322837510
supabase migration up
supabase db dump --data-only --local > supabase/seed.sql
```

Does it solve your use case?

**Comment by lauri865** [comment]
Aha, didn't know that there's a version flag for the reset command already. It does help indeed - thanks! Can implement our own lockfile with that.

Declarative schema sounds great in theory. But yet to see an approach I would trust with anything more than dead simple migration paths.

**Comment by lauri865** [comment]
If anyon else is looking for a solution, a super simple locking mechanism that's very helpful in dev – a reset command in package.json:
```
supabase db reset --version=$(cat seed.sql.lock) && pnpm migrate
```

Want to enable locking? Just add e.g. `1709728009` (or whatever version of a migration you want to lock to) into lock file, and it will first reset to this version and then add the migrations. If migrations should fail, you can always continue fixing the errors, and trying to re-apply with `supabase migration up`

Want to disable lock? Just empty the file.
