### ISSUE TITLE
`supabase stop --no-backup` unexpectedly creates backup

### ISSUE THREAD

**Issue by daniel-j-h** [supabase/cli#1982]
When stopping the supabase services through the `supabase stop` cli there is a flag to have it delete all volumes

> --no-backup           Deletes all data volumes after stopping.

It looks like the flag does not work right now or at least does not work as expected: I expected e.g. the database volume to be deleted and not to be kept around.

Here is an example where I
1. make sure there are no volumes around
2. start the supabase services
3. stop the supabase services with the `--no-backup` flag
4. unexpectedly get volumes backed up

```bash
djh@rf ~/r/portal> docker volume ls --filter label=com.supabase.cli.project=portal
DRIVER    VOLUME NAME

djh@rf ~/r/portal> supabase start
You are running outdated service versions locally:
supabase/gotrue:v2.132.3 => v2.143.0
Run supabase link to update them.
Skipping migration .gitkeep... (file name must match pattern "<timestamp>_name.sql")
Seeding data supabase/seed.sql...
Started supabase local development setup.

         API URL: http://127.0.0.1:54321
         ...
         ...

djh@rf ~/r/portal> supabase stop --no-backup
Stopped supabase local development setup.
Local data are backed up to docker volume. Use docker to show them: docker volume ls --filter label=com.supabase.cli.project=portal

djh@rf ~/r/portal> docker volume ls --filter label=com.supabase.cli.project=portal
DRIVER    VOLUME NAME
local     supabase_config_portal
local     supabase_db_portal
local     supabase_edge_runtime_portal
local     supabase_storage_portal
```

See how there are volumes created where I expected all volumes to be deleted so that next time I'm starting from a clean state.

To highlight the unexpected part:

```bash
djh@rf ~/r/portal> supabase stop --no-backup
Stopped supabase local development setup.
Local data are backed up to docker volume. Use docker to show them: docker volume ls --filter label=com.supabase.cli.project=portal
```

**System information**
- OS: Linux
- Version of CLI: 1.145.4 (latest)

**Comment by sweatybridge** [comment]
Could you share the debug output from running `supabase stop --no-backup --debug`? I can't seem to reproduce this on macOS.

**Comment by riccardolardi** [comment]
We have the same issue on latest MacOS Sonoma 14.2.1 (23C71) using Colima 0.8.6 and Docker 25.0.3. The --no-backup flag has no effect.

**Comment by sweatybridge** [comment]
Thanks for providing more details. I managed to reproduce this on Docker 25.0.3. I will look into why this broke.

The last known working version is [Docker Engine v20.10.24](https://docs.docker.com/engine/release-notes/20.10/#201024)

**Comment by aloisklink** [comment]
v1.131.1 seems to works for me, while v1.132.0 doesn't work for me:

```console
$ npx supabase@~1.132.0 stop --no-backup
Need to install the following packages:
supabase@1.132.1
Ok to proceed? (y) y
Stopped supabase local development setup.
Local data are backed up to docker volume. Use docker to show them: docker volume ls --filter label=com.supabase.cli.project=xxxxxxxx
```

```console
$ npx supabase@~1.131.0 stop --no-backup
Need to install the following packages:
supabase@1.131.5
Ok to proceed? (y) y
Stopped supabase local development setup.
```

Maybe https://github.com/supabase/cli/commit/155a0b568271d2a85d5463dc968a10a0c2d216d2 changed something, it's the main difference I can see in 1.132.x?

**Comment by sweatybridge** [comment]
Yes, we started using volume prune instead of volume rm. But docker changed the default behaviour of volume prune to only include anonymous volumes.

This should be fixed in `npx supabase@beta stop --no-backup`
