### ISSUE TITLE
`supabase status` writes to stderr even without `--debug` flag

### ISSUE THREAD

**Issue by daniel-j-h** [supabase/cli#1987]
When using the `supabase status` sub-command to produce output we can use to programmatically pass variables along, by default it looks like we are still outputting to `stderr` even without the `--debug` flag.

    --debug                             output debug logs to stderr

See this example

```bash
djh@rf ~/r/portal> supabase status -o json
Stopped services: [supabase_inbucket_portal realtime-dev.supabase_realtime_portal storage_imgproxy_portal supabase_pg_meta_portal supabase_studio_portal supabase_analytics_portal]
{
  [redacted]
}
```

I didn't expect the first line there about the stopped services; the workaround is to ignore `stderr` like

```bash
djh@rf ~/r/portal> supabase status -o json 2> /dev/null
{
  [redacted]
}
```

so that we can parse the json values and pass them on accordingly as in

```bash
readonly ANON_KEY="$(supabase status -o json 2> /dev/null | jq '.ANON_KEY')"
```

**System information**
- OS: Linux
- Version of CLI: 1.145.4 (latest)

**Comment by sweatybridge** [comment]
I think only stdout is passed through bash pipes by default? So you would see the line about stopped services but it wouldn't be passed on to jq.

**Comment by daniel-j-h** [comment]
Yeah you are right :+1: To clarify: it's not breaking the parsing it's just annoying seeing the same log messages multiple times just from parsing and using env vars in a bash script.

**Comment by sweatybridge** [comment]
Thanks for clarifying. Ideally we want to support this by configuring LOG_LEVEL https://github.com/supabase/cli/issues/1915
