### ISSUE TITLE
`npx supabase init --debug` fails when generating VS Code Settings for Deno

### ISSUE THREAD

**Issue by pgibler** [supabase/cli#2000]
The init command finishes successfully when I select the no option when asked to generate the Deno VS Code settings, but not when I select the yes option. When I ask it to generate them, it fails with following error: `failed to parse settings: invalid character '}' looking for beginning of object key string`

system: Ubuntu 20.04
cli version: 1.145.4

![image](https://github.com/supabase/cli/assets/119892/7831bd93-d4a3-484f-801e-48b684e14268)

**Comment by sweatybridge** [comment]
This seems to be a duplicate https://github.com/supabase/cli/issues/1825#issuecomment-1882228969

**Comment by sweatybridge** [comment]
So the fix would be to check if your existing `.vscode/settings.json` file is malformed. Or remove it so that cli can initialise from clean state.
