### ISSUE TITLE
`supabase start`: Edge Runtime container fails with "Segmentation fault"

### ISSUE THREAD

**Issue by gstsdev** [supabase/cli#2013]
**Describe the bug**
When I run the `supabase start` command, the `supabase_edge_runtime` container fails with a simple "Segmentation fault" message.

When I run with the `--debug` flag, I see that it happens after this:

```
...
Download https://deno.land/x/jose@v4.13.1/runtime/subtle_rsaes.ts
DEBUG Snapshot already up to date. Skipping pending resolution.
DEBUG Opening cache /root/.cache/deno/dep_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/dep_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
Segmentation fault
```

**To Reproduce**
1. Run `supabase start` (or `supabase start -x ...`, leaving just the Edge Runtime)
2. Wait for health checks
3. See error

**Expected behavior**
I expected the CLI to start the Edge Runtime container successfully, so I could test Supabase Functions locally.

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag (preferred).
 - Ticket ID: 92d95afc064648a192484dd5784122f9
 - OS: macOS
 - Version of CLI: 1.142.1
 - Versions of services:
```
        SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.153           │ 15.1.0.153
    supabase/gotrue        │ v2.143.0             │ v2.143.0
    postgrest/postgrest    │ v12.0.1              │ v12.0.1
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.48.2              │ v0.48.2
    supabase/edge-runtime  │ v1.33.5              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

**Comment by nyannyacha** [comment]
@sweatybridge Could you please transfer this issue to the edge-runtime repository?

**Comment by sweatybridge** [comment]
This might have something to do with docker. Could you report the docker version and check that docker virtualisation settings match the screenshot below?

![Screenshot 2024-03-06 at 12 36 56 PM](https://github.com/supabase/cli/assets/1639722/aa47be86-e040-4421-b0db-7392e32c2597)

**Comment by gstsdev** [comment]
> This might have something to do with docker. Could you report the docker version you are using and check that docker virtualisation settings match the screenshot below?
> 
> ![Screenshot 2024-03-06 at 12 36 56 PM](https://private-user-images.githubusercontent.com/1639722/310362477-aa47be86-e040-4421-b0db-7392e32c2597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzUzMzQsIm5iZiI6MTcwOTczNTAzNCwicGF0aCI6Ii8xNjM5NzIyLzMxMDM2MjQ3Ny1hYTQ3YmU4Ni1lMDQwLTQ0MjEtYjBkYi03MzkyZTMyYzI1OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTQyMzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJhODA4M2Q3OTg3YWQ4NTFmN2FhYjViOTcyYTY5N2VhZjkwOTgxNzdmYzVjOTAyMjVmMzMwNzgyNDhlNmZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L_NY3DzEQ50W_iQXAf8pEQZVQQTr_o1arvDCvmqxC28)

My current version of Docker is `25.0.2`, and Docker Desktop is `4.27.1`.

After changing the settings to what you suggested, it worked! Thank you!
