### ISSUE TITLE
Cannot alter owner of view to `authenticated`

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/cli#2020]
**Describe the bug**
When using `supabase db reset` with a migration containing `alter view X owner to authenticated`, I get the following error: `ERROR: permission denied for schema public (SQLSTATE 42501)`

**Expected behavior**
I should be able to alter the owner of a table/view to `authenticated` to restrict views from being accessed by `anon`.

**System information**
 - OS: macOS 14
 - Version of CLI: v1.148.6
 - Versions of services:

```
        SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼────────────
    supabase/postgres      │ 15.1.0.68            │ 15.1.0.68
    supabase/gotrue        │ v2.143.0             │ v2.143.0
    postgrest/postgrest    │ v10.2.0              │ v10.2.0
    supabase/realtime      │ v2.25.66             │ -
    supabase/storage-api   │ v0.48.2              │ v0.48.2
    supabase/edge-runtime  │ v1.38.0              │ -
    supabase/studio        │ 20240301-0942bfe     │ -
    supabase/postgres-meta │ v0.79.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

**Comment by sweatybridge** [comment]
If I understand correctly, you want to revoke anon access to view X. The following statement should work without changing view owner.

```sql
REVOKE ALL PRIVILEGES ON X FROM anon;
```

**Comment by bnjmnt4n** [comment]
Thanks for the tip. I was wondering why there was some inconsistency between the CLI and one of our projects on supabase.com. The hosted version was created before https://github.com/orgs/supabase/discussions/9314, and we were able to alter the table/view owner using the Supabase query editor in the past, and even today.

However, on a newly created project the command to alter the owner also fails on both the CLI and the hosted project via the query editor. I guess this can be closed since this isn't really an issue with the CLI.

Not sure if it's important to fix the inconsistent permissions for older projects.
