### ISSUE TITLE
Database not healthy on `npx supabase db diff --linked -f <migration__filename>`

### ISSUE THREAD

**Issue by gorayaa66** [supabase/cli#2037]
**Describe the bug**
Everything was working fine and then all of a sudden it stopped working.

**To Reproduce**
These are the deps i'm using and i linked it to the remote supabase project.
"dependencies": {
    "@supabase/supabase-js": "^1.35.7",
    "dotenv": "^16.3.1",
    "supabase": "^1.144.2"
  }

**Expected behavior**
It should download the database diff in the file specified.

**System information**
 - Crash Ticket ID:  474f1630f33543328f794767c4a7cc5a
 - Version of OS: Mac OS
 - Version of CLI: 1.144.2
 - Version of Docker: Docker version 20.10.6, build 370c289
 - Versions of services: 
 -       SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼────────────
    supabase/postgres      │ 15.1.0.37            │ 15.1.0.37
    supabase/gotrue        │ v2.132.3             │ v2.143.0
    postgrest/postgrest    │ v10.2.0              │ v10.2.0
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.48.1              │ v0.48.2
    supabase/edge-runtime  │ v1.34.1              │ -
    supabase/studio        │ 20240205-b145c86     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Comment by sweatybridge** [comment]
```
supabase/postgres │ 15.1.0.37 │ 15.1.0.37
```

Your postgres image version appears to be quite outdated. For any versions below 15.1.0.55, you will likely run into some edge cases not handled by CLI upgrade. Could you try upgrading your project via the dashboard? https://supabase.com/dashboard/project/_/settings/infrastructure

After that, relink your project and reset your local database.

```bash
supabase link
supabase stop --no-backup
supabase start
```

**Comment by gorayaa66** [comment]
@sweatybridge yes it worked. Thanks
