### ISSUE TITLE
Generating TypeScript types fails in Bitbucket pipeline

### ISSUE THREAD

**Issue by hammerlscs** [supabase/cli#2046]
**Describe the bug**
We are using

```
npx supabase gen types typescript --local
```

to generate the TypeScript types in our pipeline. Since upgrading from 1.131.5 to 1.148.6, generating types fails with the following error:

```
v0.79.0: Pulling from supabase/postgres-meta
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.79.0
failed to create docker container: Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
```

**To Reproduce**
Use `npx supabase gen types typescript --local` in the Bitbucket pipeline.

**System information**
 - Ticket ID: eb96d7a5b9de43a0bbfe5fca68213cf4

**Additional context**
Possibly related to https://github.com/supabase/cli/issues/1830

**Comment by etzelc** [comment]
Seeing this error in our BitBucket Pipeline (including current pre-release version 1.144.4) when executing `npx supabase start`
```
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.79.5
failed to create docker container: Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by swamidass** [comment]
Having this same problem with version of the cli 1.172.2. Is there a fix in the works? Hopefully some regression testing too, because this seems to be a recurring bug.

**Comment by maximilian-hammerl** [comment]
We are also using CLI version 1.172.2 and we are not having this problem. Everything works fine on our end.
