### ISSUE TITLE
Error while running supabase db pull

### ISSUE THREAD

**Issue by jay-trivedi** [supabase/cli#2050]
I am getting an error while running `npx supabase db pull` - 

Connecting to remote database...
failed to open dump file: open supabase/migrations/20240314130741_remote_schema.sql: no such file or directory
Try rerunning the command with --debug to troubleshoot the error

**System information**
 - Ticket ID: 20f59ba2330e4539947f473eb6eb3001
 - Version of OS: macOS 14.1.1 (23B81)
 - Version of CLI: 1.148.6
 - Version of Docker: v25.0.3
 - Versions of services:
 
|      SERVICE           |        IMAGE         |    LOCAL           |  LINKED   |
|------------------------|----------------------|--------------------|-----------|
| supabase/postgres      | 15.1.0.147           | 15.1.1.24         |           |
| supabase/gotrue        | v2.144.0             | v2.144.0          |           |
| postgrest/postgrest    | v12.0.2              | v12.0.2           |           |
| supabase/realtime      | v2.25.66             | -                 |           |
| supabase/storage-api   | v0.46.4              | v0.48.2           |           |
| supabase/edge-runtime  | v1.38.0              | -                 |           |
| supabase/studio        | 20240301-0942bfe     | -                 |           |
| supabase/postgres-meta | v0.79.0              | -                 |           |
| supabase/logflare      | 1.4.0                | -                 |           |
| bitnami/pgbouncer      | 1.20.1-debian-11-r39 | -                 |           |
| darthsim/imgproxy      | v3.8.0               | -                 |           |

**Comment by sweatybridge** [comment]
This has been addressed in beta release: `npx supabase@beta db pull`

Stable release will go out next Tuesday.

**Comment by jay-trivedi** [comment]
`npx supabase@beta db pull` works! Thanks for the quick revert. Looking forward to the stable release next Tuesday.

**Comment by jingsam** [comment]
> This has been addressed in beta release: `npx supabase@beta db pull`
> 
> Stable release will go out next Tuesday.

I wander when release the new stable supabase that i can recreate all local dev envirment.
