### ISSUE TITLE
Unexpected Access to Restricted Materialized View

### ISSUE THREAD

**Issue by SamuraiT** [supabase/cli#2066]
## Describe the bug
After setting up a materialized view `sensitive_data_view` with restricted access, and granting `SELECT` permission exclusively to the `service_role`, users without the `service_role` can unexpectedly access the materialized view. This behavior is unexpected as the intention was to limit access to this sensitive data.

## To Reproduce
1. Create a materialized view with the command:  
   ```sql
   CREATE MATERIALIZED VIEW sensitive_data_view AS SELECT * FROM sensitive_data_table;
   ```
2. Reset permissions to limit public access with:  
   ```sql
   REVOKE ALL ON sensitive_data_view FROM PUBLIC;
   ```
3. Grant `SELECT` permission only to `service_role` with:  
   ```sql
   GRANT SELECT ON sensitive_data_view TO service_role;
   ```
4. Log in as a user without `service_role` and attempt to access `sensitive_data_view`.

## Expected behavior
The expectation was that only users with the `service_role` would be able to access the `sensitive_data_view`. Other users, especially those without explicit permissions, should not have access to the materialized view, ensuring the security of sensitive data.

## System information*
- PostgreSQL version: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
- Your database's hosting environment: local

**Comment by sweatybridge** [comment]
The default privileges in `public` schema is setup by Supabase to always grant all access to `anon`, `authenticated`, and `service_role` when new views are created. This means you need to revoke additional permissions in step 2.

```sql
postgres=> REVOKE ALL ON sensitive_data_view FROM PUBLIC, anon, authenticated, service_role;
REVOKE
postgres=> \dpp sensitive_data_view
                                              Access privileges
 Schema |        Name         |       Type        |     Access privileges     | Column privileges | Policies
--------+---------------------+-------------------+---------------------------+-------------------+----------
 public | sensitive_data_view | materialized view | postgres=arwdDxt/postgres |                   |
(1 row)
```

After that, if you proceed with step 3, other users won't be able to access the view anymore.

**Comment by SamuraiT** [comment]
understood ! thank you so much
