### ISSUE TITLE
Diff command fails because pg_jsonschema is not enabled on shadow db

### ISSUE THREAD

**Issue by Davidtozz** [supabase/cli#2088]
**Describe the bug**
Using the diff command with extensions not enabled by default results in error. In my case, i enabled (other than the default extensions) the `pg_jsonschema` extensions, to validate a column holding JSONB data. It seems that the shadow db, created during the execution of the diff command, doesn't take into account possible extensions enabled on the main supabase instance, and therefore apply them before comparing changes. 

**To Reproduce**
1. From the Supabase Dashboard, search and enable `pg_jsonschema`
2. Apply some changes to the database, including at least 1 JSONB field with a check having a function from pg_jsonschema (ex. jsonb_matches_schema() ) 
3. Run `supabase db diff` 

**Expected behavior**
No errors are thrown, shadow db  and the command outputs the expected result

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: a3ab023086174add99c5dcb28fe95b0d
 - Version of OS: Windows 11
 - Version of CLI: 1.148.6
 - Version of Docker: 25.0.3, build 4debf41

- Versions of services:   
-- supabase/postgres          15.1.0.147           
-- supabase/gotrue              v2.143.0             
-- postgrest/postgrest          v12.0.1              
-- supabase/realtime             v2.25.66            
-- supabase/storage-api        v0.46.4             
-- supabase/edge-runtime    v1.38.0              
-- supabase/studio                 20240301-0942bfe     
-- supabase/postgres-meta    v0.79.0              
-- supabase/logflare               1.4.0                
-- bitnami/pgbouncer            1.20.1-debian-11-r39 
-- darthsim/imgproxy             v3.8.0               

**Additional context**
If applicable, add any other context about the problem here.
 - Browser: Brave
 - Version of supabase-js:  v2.39.8
 - Version of Node.js  v20.9.0

**Comment by sweatybridge** [comment]
Do you have `create extension if not exists pg_jsonschema` in any of your migration files?

**Comment by Davidtozz** [comment]
Nope, I solved the issue by including that line in my first migration file. Can't believe the issue was that simple, thanks a lot!
