### ISSUE TITLE
how to run `supabase start` with nerdctl

### ISSUE THREAD

**Issue by mmohammadi9812** [supabase/cli#2105]
**Link**
https://supabase.com/docs/reference/cli/supabase-start#supabase-start

**Describe the problem**
I have installed Supabase with brew. I'm using Lima on Mac and Nerdctl as docker. Running `supabase start` gives an error about docker not running and I couldn't find any issue or discussion about how to run this command with nerdctl

If docker is hardcoded, any explanation on how to run necessary containers would be great

Thanks

**Comment by sweatybridge** [comment]
The CLI doesn't use any hardcoded docker commands as it works directly with any docker-compatible container runtime. So nerdctl is irrelevant here but you do need either Colima or podman installed.

**Comment by mmohammadi9812** [comment]
Ok, I will try it with them then. Thank you
