### ISSUE TITLE
Supbase local migration not being updated in remote

### ISSUE THREAD

**Issue by emmyduruc** [supabase/cli#2136]
# Bug report
i am using the CLI migration locally is up-to-date and i can see new tables in studioURL but when i run $ "supabase db push"
Connecting to remote database...
Remote database is up to date.
and when i check my remote db the changes are not up-to-date 

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
the Remote db is not getting updated
i am using the CLI migration locally is up-to-date and i can see new tables in studioURL but when i run $ "supabase db push"
Connecting to remote database...
Remote database is up to date.
## To Reproduce
supabase create new migration

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior
That the local changes should be in the remote when i run supabase db push 

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by sweatybridge** [comment]
Could you run `supabase migration list` and share the output?

**Comment by emmyduruc** [comment]
> Could you run `supabase migration list` and share the output?
here is the output from "supabase migration list"
![image](https://github.com/supabase/cli/assets/82957750/93148316-ce60-4a61-b2ab-10f619e7e340)

**Comment by sweatybridge** [comment]
It does seem like all your local migrations are already pushed to remote. Do you know which migration file and which statement is missing on remote?

**Comment by emmyduruc** [comment]
They are pushed to remote but i do not see the new tables the local and remote tables looks totally different though the migrations are in sync

**Comment by sweatybridge** [comment]
Can you run `supabase projects list` to check that you are linked to the right project?

**Comment by sweatybridge** [comment]
One more question to check: have you saved all your local migrations to disk? This can be done with `supabase db diff` which should report no changes found.

**Comment by emmyduruc** [comment]
> One more question to check: have you saved all your local migrations to disk? This can be done with `supabase db diff` which should report no changes found.

Unfortunately did not help

**Comment by sweatybridge** [comment]
As a last resort, you can also reset your remote database: `supabase db reset --linked`

**Comment by sweatybridge** [comment]
Any updates on this one? There's another way to sync up your schema

1. Start a local database
```bash
supabase db start
```

2. Backup your migrations directory
```bash
mv supabase/migrations supabase/backup
```

3. Dump your remote schema
```bash
mkdir supabase/migrations
supabase db dump -f supabase/migrations/0_schema.sql
```

4. Save local diff as a migration file
```bash
supabase db diff -f schema_drift
```

5. Restore your migrations and push
```
mv supabase/backup supabase/migrations
supabase db push
```

I think these steps will be simpler with [declarative schema](https://github.com/supabase/cli/pull/2099). But for now, you will have to fix the schema drift using those steps above.

**Comment by ericdjavid** [comment]
Thanks for that @sweatybridge, helped me a lot! 👍

**Comment by viniciusdeliz** [comment]
@sweatybridge can the `supabase db dump` create individual migration files maybe?

The one command you instructed works for me: `supabase db dump -f supabase/migrations/0_schema.sql`
However that makes me lose the migrations history that I already have in the remote (44 records in remote). Isn't there a way to just create migration files based on what we have in the remote records?

A developer in the team haven't committed the changes to git history. I'm trying to make the db healthy and synch-able.

**Comment by sweatybridge** [comment]
@viniciusdeliz if you already have records in remote history, you can run `supabase migration fetch` to pull them into local migration directory.

https://supabase.com/docs/reference/cli/supabase-migration-fetch

**Comment by longhairedsi** [comment]
Hey, I've got a similar issue, a migration has run on the database(is second to newest in migration history) but non of the changes have been applied to my db. The images show a small example of what should have been applied vs when the table is showing. Now I can't deploy new migrations as they rely on these changes. Can I safely just manually run the sql from this migration on my prod db to bring it up to date? any unintended side effects of that?

![Image](https://github.com/user-attachments/assets/d248b539-dffd-438a-bf94-ca877f2ac10b)

![Image](https://github.com/user-attachments/assets/1a6163ab-c7fd-40a3-81c1-99297c145568)

**Comment by longhairedsi** [comment]
Anyone else gets here , I manually re-ran the sql in individual statements wrapped in transactions,  I got this error each time a ran it on one of the ALTER TABLE statments that added more than one column. (almost instantly)

`Error: upstream connect error or disconnect/reset before headers. reset reason: connection timeout`

My suspicion is that originally this happened and the migration failed silenty for some reason. I broke the it into individual ADD COLUMN statements and it worked

**Comment by antochan** [comment]
@sweatybridge thanks for ur help with fixing migration drift. I'm now running into an issue when running supabase start im getting

`ERROR: must be member of role "supabase_admin" (SQLSTATE 42501)` 

any ideas?

**Comment by sweatybridge** [comment]
@antochan could you show me the statement which throws this error?

Generally we want to comment out any statement that changes owner to supabase_admin. But I just want to double check why we missed this case.

**Comment by antochan** [comment]
> [@antochan](https://github.com/antochan) could you show me the statement which throws this error?
> 
> Generally we want to comment out any statement that changes owner to supabase_admin. But I just want to double check why we missed this case.

This line: commenting it out seems to work!
ALTER PUBLICATION "supabase_realtime_messages_publication" OWNER TO "supabase_admin";
