### ISSUE TITLE
pgtle and supabase-dbdev extension cannot be enabled after db pull

### ISSUE THREAD

**Issue by officialankan** [supabase/cli#2163]
**Describe the bug**
When running `supabase migration up` when getting started with local development, I get this error message:

```
ERROR: schema "pgtle" does not exist (SQLSTATE 3F000)
At statement 12: CREATE EXTENSION IF NOT EXISTS "pg_tle" WITH SCHEMA "pgtle"
```

**To Reproduce**
1. `supabase link --project-ref <project-id>`
2. `supabase db pull`
3. `supabase migration up`
4. This is where the error pop up...

**Expected behavior**
I would expect the my migration, generated by `supabase db pull` to be applied succesfully.

**Screenshots**
![bild](https://github.com/supabase/cli/assets/13569761/2c3cf408-c844-4beb-8861-b8ba799634c0)

This could probably be resolved by a postgres genius, however I am not one. Hoping this can be resolved and documented.

Thanks!

**Comment by sweatybridge** [comment]
Could you run `supabase services` and report the versions? It would help us reproduce

**Comment by sweatybridge** [comment]
Thanks, in this case, you can edit line 12 of your migration file to drop the `WITH SCHEMA "pgtle"` part. So it reads

```sql
CREATE EXTENSION IF NOT EXISTS "pg_tle";
```

**Comment by officialankan** [comment]
> Thanks, in this case, you can edit line 12 of your migration file to drop the `WITH SCHEMA "pgtle"` part. So it reads
> 
> ```sql
> CREATE EXTENSION IF NOT EXISTS "pg_tle";
> ```

I did this, but now the error is the same but with the next statement regarding `supabase-dbdev`. When I drop the `WITH SCHEMA "supabase-dbdev"`, the migration still doesn't work :(

![bild](https://github.com/supabase/cli/assets/13569761/d60c19d1-3e4e-453f-9aa1-18de8587f037)

**Comment by sweatybridge** [comment]
Oh, there's a special syntax to enable `supabase@dbdev` extension that is not captured properly by db pull.

```sql
create extension if not exists http with schema extensions;
create extension if not exists pg_tle;
select
    pgtle.install_extension(
        'supabase@dbdev',
        resp.contents ->> 'version',
        'PostgreSQL package manager',
        resp.contents ->> 'sql'
    )
from extensions.http(
    (
        'GET',
        'https://api.database.dev/rest/v1/'
        || 'package_versions?select=sql,version'
        || '&package_name=eq.supabase-dbdev'
        || '&order=version.desc'
        || '&limit=1',
        array[
            (
                'apiKey',
                'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJp'
                || 'c3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdXB0cHBsZnZpaWZyY'
                || 'ndtbXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODAxMDczNzI'
                || 'sImV4cCI6MTk5NTY4MzM3Mn0.z2CN0mvO2No8wSi46Gw59DFGCTJ'
                || 'rzM0AQKsu_5k134s'
            )::extensions.http_header
        ],
        null,
        null
    )
) x,
lateral (
    select
        ((row_to_json(x) -> 'content') #>> '{}')::json -> 0
) resp(contents);
create extension "supabase@dbdev";
```

can you try replace line 13 with the block above?

**Comment by officialankan** [comment]
> Oh, there's a special syntax to enable `supabase@dbdev` extension that is not captured properly by db pull.
> 
> ```sql
> create extension if not exists http with schema extensions;
> create extension if not exists pg_tle;
> select
>     pgtle.install_extension(
>         'supabase@dbdev',
>         resp.contents ->> 'version',
>         'PostgreSQL package manager',
>         resp.contents ->> 'sql'
>     )
> from extensions.http(
>     (
>         'GET',
>         'https://api.database.dev/rest/v1/'
>         || 'package_versions?select=sql,version'
>         || '&package_name=eq.supabase-dbdev'
>         || '&order=version.desc'
>         || '&limit=1',
>         array[
>             (
>                 'apiKey',
>                 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJp'
>                 || 'c3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdXB0cHBsZnZpaWZyY'
>                 || 'ndtbXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODAxMDczNzI'
>                 || 'sImV4cCI6MTk5NTY4MzM3Mn0.z2CN0mvO2No8wSi46Gw59DFGCTJ'
>                 || 'rzM0AQKsu_5k134s'
>             )::extensions.http_header
>         ],
>         null,
>         null
>     )
> ) x,
> lateral (
>     select
>         ((row_to_json(x) -> 'content') #>> '{}')::json -> 0
> ) resp(contents);
> create extension "supabase@dbdev" with schema extensions;
> ```
> 
> can you try replace line 13 with the block above?

This is getting a bit weird because now it fails 50% of the time with 

```
ERROR: Resolving timed out after 1000 milliseconds (SQLSTATE XX000)
At statement 16: create extension "supabase@dbdev" with schema extensions
```

but the other 50% with

```` 
ERROR: extension "olirice-index_advisor" is not available (SQLSTATE 0A000)
At statement 20: CREATE EXTENSION IF NOT EXISTS "olirice-index_advisor"
```` 

Did I do too much work on the hosted platform before looking at local development? :)

**Comment by sweatybridge** [comment]
It's probably just the newly released `index_advisor` that hasn't been fully tested with local development setup.

Do you use other packages from `dbdev`? If not, you can comment out statements that create those extensions for the time being.

```sql
-- CREATE EXTENSION IF NOT EXISTS "pg_tle"
-- CREATE EXTENSION IF NOT EXISTS "supabase-dbdev"
-- CREATE EXTENSION IF NOT EXISTS "olirice-index_advisor"
```

**Comment by officialankan** [comment]
For now, I commented out the extensions as per your first alternative. Now works great!

Thanks for the quick response!
