### ISSUE TITLE
Local development environment issue after updating to latest docker images

### ISSUE THREAD

**Issue by anton-kirschhock** [supabase/cli#2177]
**Describe the bug**
Supabase CLI just installed the latest version of the Realtime image (v2.28.23) and when I want to start my local env I get:
{:error, "ERROR 42703 (undefined_column) column t0.jwt_jwks does not exist\n\n    query: SELECT t0.\"id\", t0.\"name\", t0.\"external_id\", t0.\"jwt_secret\", t0.\"jwt_jwks\", t0.\"postgres_cdc_default\", t0.\"max_concurrent_users\", t0.\"max_events_per_second\", t0.\"max_bytes_per_second\", t0.\"max_channels_per_client\", t0.\"max_joins_per_second\", t0.\"suspend\", t0.\"inserted_at\", t0.\"updated_at\" FROM \"tenants\" AS t0 WHERE (t0.\"external_id\" = $1)"}} to 500 response

**To Reproduce**

**Expected behavior**
No issues when starting the supabase stack

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 5d8b60e340a5409b826ed0de92761bf8
 - Version of OS: Windows 11
 - Version of CLI: [e.g. v1.60.0]
 - Version of Docker: 1.161.0
 - Versions of services: 
   - supabase/postgres = 15.1.1.16
   - supabase/gotrue = v2.143.0 
   - postgrest/postgrest = v12.0.2
   - supabase/realtime = v2.28.23 
   - supabase/storage-api = v0.48.2  
   - supabase/edge-runtime = v1.43.2  
   - supabase/studio = 20240408-6bf3b81 
   - supabase/postgres-meta = v0.80.0  
   - supabase/logflare = 1.4.0
   - bitnami/pgbouncer = 1.20.1-debian-11-r39 
   - darthsim/imgproxy = v3.8.0

**Additional context**
If applicable, add any other context about the problem here.
 - Version of supabase-js [e.g. v2.22.0]
 - Version of Node.js [e.g. v16.20.0]

**Comment by sweatybridge** [comment]
This is because we changed the order which realtime migrations are run. It affects users who are starting supabase from a local backup.

You can fix it by running `supabase stop --no-backup` before supabase start. Note this will delete any uncommitted changes you have locally.
