### ISSUE TITLE
Supabase CLI 1.163.2: Docker Image Pull Failure Due to Timeout on 'supabase start' Command

### ISSUE THREAD

**Issue by flocosnier** [supabase/cli#2210]
**Describe the bug**
I've upgraded supabase-cli to 1.163.2 and I can no longer use supabase start.

Running supabase start --debug now ends with :

`failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`
or
`failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": context deadline exceeded
`

**To Reproduce**
1. Update to Supabase CLI 1.163.2
2. Run "supabase start"
3. See error

**Expected behavior**

**System information**
 - Ticket ID: 6612aed1cba94883ad785d6526de3b9e
 - Version of OS: Windows 11 (23H2)
 - Version of CLI: v1.163.2
 - Version of Docker: v25.0.3
 - Versions of services: 
    supabase/postgres      │ 15.1.1.41            │ 15.1.1.41
    supabase/gotrue        │ v2.148.0             │ v2.148.0
    postgrest/postgrest    │ v12.0.2              │ v12.0.2
    supabase/realtime      │ v2.28.23             │ -
    supabase/storage-api   │ v1.0.10              │ v1.0.10
    supabase/edge-runtime  │ v1.45.2              │ -
    supabase/studio        │ 20240422-5cf8f30     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Comment by sweatybridge** [comment]
Could you try `SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start`?

It might be a temporary issue with aws.

**Comment by rusakovic** [comment]
```DEBUG FileFetcher::fetch_remote() - specifier: https://deno.land/x/jose@v4.13.1/runtime/subtle_rsaes.ts
DEBUG FileFetcher::fetch_cached - specifier: https://deno.land/x/jose@v4.13.1/runtime/subtle_rsaes.ts
DEBUG Snapshot already up to date. Skipping pending resolution.
DEBUG Opening cache /root/.cache/deno/node_analysis_cache_v1...
DEBUG edge-runtime is listening on 0.0.0.0:8081
Functions config: {}
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.45.2 (compatible with Deno v1.40.3)
Pruned containers: [45...6]
Pruned network: [supabase_network_project-supabase]
service not healthy: [supabase_rest_project-supabase supabase_edge_runtime_project-supabase]
```

but works without any issues - all containers are healthy - with `supabase --debug start --ignore-health-check`

The logs I still see
```
Using supabase-edge-runtime-1.45.2 (compatible with Deno v1.40.3)
service not healthy: [supabase_rest_project-supabase supabase_edge_runtime_project-supabase]
```

but in Docker Desktop all containers are running.

**Comment by sweatybridge** [comment]
@rusakovic sorry are you asking why the rest and edge_runtime containers are reported as unhealthy locally? If so, could you open a separate issue because that's unrelated to this ticket.
