### ISSUE TITLE
Supabase diff omit semicolon from migration statement?

### ISSUE THREAD

**Issue by higheruceo** [supabase/cli#2213]
**Describe the bug**
supabase diff when specifying --db-url does not include semicolon 

**To Reproduce**
supabase db diff --db-url postgres://url  -f migration_name

**Expected behavior**
semicolon should be included at the end of each statement so that a supabase start or db reset would complete without error.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 469084417d594511b4593c1a8156f238
 - Version of OS: MacOs
 - Version of CLI: 1.163.6

**Comment by sweatybridge** [comment]
Sorry I can't seem to reproduce

```bash
$ supabase db diff --db-url 'postgres://postgres:postgres@localhost:54322/postgres' -f what
onnecting to remote database...
Creating shadow database...

$ cat supabase/migrations/20240429062258_what.sql
create extension if not exists "hypopg" with schema "extensions";

create extension if not exists "index_advisor" with schema "extensions";
```

Could you report versions from the `supabase services` as well as the problematic schema and actual output?

**Comment by sweatybridge** [comment]
closing as not reproducible
