### ISSUE TITLE
supabase_realtime clears out after db reset

### ISSUE THREAD

**Issue by kevduong1** [supabase/cli#2214]
After running supabase db reset

users have to re-enable the listeners for each table everytime, it'd be nice if db diff included some sort of way to track real time listeners enabled for tables, or possibly opt into saving it with an argument or something.

<img width="1009" alt="image" src="https://github.com/supabase/cli/assets/65885347/e9623a7f-a7f9-4551-87d0-e9e16c779a56">

**Comment by sweatybridge** [comment]
Hello, this is currently a known limitation of db diff. The workaround is to add those tables to realtime publications manually in a migration file. For eg

```
alter publication "supabase_realtime" add table only "public"."my_table";
```

**Comment by kevduong1** [comment]
Hi Sweaty, thanks that works
