### ISSUE TITLE
update storage-api to latest

### ISSUE THREAD

**Issue by psteinroe** [supabase/cli#2220]
**Is your feature request related to a problem? Please describe.**
especially now after launch week, it would be great to get the s3 compatible storage api into the cli 

**Describe the solution you'd like**
update storage-api to latest

**Comment by sweatybridge** [comment]
S3 support in storage-api was added to CLI during last LW. Running `supabase status` should show the S3 credentials for connecting locally.

**Comment by psteinroe** [comment]
for some reason the cli version was not up to date despite the `beta` tag... sorry for bothering.
