### ISSUE TITLE
Supabase CLI as NPM dev-dependency not working the same as run by npx?!

### ISSUE THREAD

**Issue by Fefke** [supabase/cli#2222]
**Describe the bug**
I tried to fetch the Typescript-scheme of my PostgresDB from a different scheme than "public"
and for some reason while running `npm run supabase gen types typescript --project-id xyz -s "MyCustomSchemeAsNamedInPostgres"` I am only allowed to receive the default scheme
and only by running it via npx: `npx supabase gen types typescript --project-id xyz -s "MyCustomSchemeAsNamedInPostgres"`,
I receive the correct types for my specific scheme.

I dont know how the same tools can produce a different outcome on this.
Possibly this is a bug of npm itself.

**To Reproduce**
Pretty much both commands from above.

Both CLI-Versions being the same on v1.164.1.

**Expected behavior**
I expect my custom scheme to be generated as typescript-types in both cases.

**Screenshots**
At first by running it with `npm run` I have to select the project-id anyway - although it's already declared:
![image](https://github.com/supabase/cli/assets/33942165/44fe869f-5938-4e68-aa83-da3848baa871)

The actual type-Generation looks like this:
![image](https://github.com/supabase/cli/assets/33942165/83af21da-ad62-43ea-8526-b46dfb8c9231)
 not being/containing the requested scheme.

If I run the same supabase-cli command via npx, it works as I intended it to:
![image](https://github.com/supabase/cli/assets/33942165/f63c8708-2e16-4092-87e2-5483a5d8b30a)

It's notable, that every other supabase-cli-command I used so far is working as intended,
only the type-generation has this weird behaviour.

Thank you for your time and this great project!

**System information**
 - Version of OS: Ubuntu 22.04 LTS (WSL2)
 - Version of CLI: 1.164.1
 - Version of Docker: Docker version 25.0.3, build 4debf41

**Additional context**

**Comment by sweatybridge** [comment]
As a sanity check, could you run both `npm run supabase --version` and `npx supabase --version` to check that they match?
