### ISSUE TITLE
--no-backup flag no longer deletes docker volumes

### ISSUE THREAD

**Issue by barbinbrad** [supabase/cli#2230]
**Describe the bug**
On the newest version of the CLI the `--no-backup` flag does not remove the volumes

**To Reproduce**
```
npx --yes supabase stop --no-backup
```

**Expected behavior**
The volumes are removed when `--no-backup` is passed

**System information**
 - Version of CLI: [e.g. v1.164.1]

**Comment by sweatybridge** [comment]
Hello, which cli version did you upgrade from? Which docker version are you running?

**Comment by barbinbrad** [comment]
> Hello, which cli version did you upgrade from? Which docker version are you running?

Upgrade from 1.145.4
Docker version 26.0.0, build 2ae903e
MacOS Sonoma 14.3

**Comment by barbinbrad** [comment]
After running `supabase stop --no-backup` and then running `supabase start` the CLI outputs "Starting database from backup..." and it does not run the migrations.

**Comment by sweatybridge** [comment]
Our documentation recommends running `supabase stop --no-backup` before upgrading. https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli

If you didn't do that, an alternative is to delete all docker volumes manually with `docker volume prune -a` or one by one with `docker volume rm`

**Comment by barbinbrad** [comment]
I've been deleting the docker volumes manually each time I run `supabase stop --no-backup`  -- but is there any good way to get back to a state where this isn't required?

**Comment by sweatybridge** [comment]
I can't reproduce this locally though. Could you report the output from `docker volume ls` before and after? ie. it should be empty

```
$ docker volume ls
DRIVER    VOLUME NAME
$ supabase start
$ supabase stop --no-backup
$ docker volume ls
DRIVER    VOLUME NAME
```
