### ISSUE TITLE
Can't link to project when database SSL is on

### ISSUE THREAD

**Issue by perostlin** [supabase/cli#2233]
**Describe the bug**
I'm currently in the works of securing our database.
So one thing I want to do is to turn on SSL for direct connections towards our database, but when I do so I get the following error when I try to do the ```supabase link```:

```
server error (FATAL: SSL connection is required (SQLSTATE XX000))
```

What I can see is that I'm not able to set an option anywhere to tell the link command to use SSL or a given certificate?
Any help is appreciated.

**To Reproduce**
1. Create a new database.
2. Turn "Enforce SSL on incoming connections" under Project Settings > Database.
3. Run ```supabase link```, select your newly created project

**Expected behavior**
Either get an extra option telling me that I need to specify a SSL certificate to be able to use ```supabase link```or something like it.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: c7ff82933ac74f8b92d1b86c566510ba
 - Version of OS: macOS Sonoma 14.4.1
 - Version of CLI: 1.164.1
 - Version of Docker: 24.0.6, build ed223bc
 - Versions of services:
<img width="429" alt="Screenshot 2024-05-02 at 14 22 05" src="https://github.com/supabase/cli/assets/20464832/b8583ae4-fe5c-44d9-bf75-a38bf5b9dc30">

**Additional context**
Very flaky experience, probably because this options is in beta, sometimes I'm able to link with it turned on and sometimes not.
When mixing it with "Network Restrictions" I'm not able to link if I have restrict all access, but if I add my IP I'm able to link.

**Comment by sweatybridge** [comment]
Could you try link again after deleting `supabase/.temp` ?

CLI uses sslmode=prefer so it should work with ssl enforcement. It also takes a few minutes for ssl changes to propagate based on my testing. 

If that still doesn't work, you can also try setting the env var `PGSSLMODE=require supabase link`

Hope it helps.

**Comment by perostlin** [comment]
Deleting the .temp did the trick, thank you @sweatybridge!
