### ISSUE TITLE
Cannot run `npx supabase db reset` in newly initialized project

### ISSUE THREAD

**Issue by Silur** [supabase/cli#2250]
Environment: Arch linux x64, supabase-cli `1.165.0`

```bash
docker system prune -a # to reset all volumes and download latest images
mkdir /tmp/newproject
cd $_
npm install supabase
npx supabase init
npx supabase start
# services run successfully, realtime service healthcheck positive
npx supabase db reset --debug
```

Running an empty db reset as above results with the following:
```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 4.3) :ets.lookup(:cachex_overseer_table, Realtime.Tenants.Cache)
    (cachex 3.4.0) lib/cachex/services/overseer.ex:89: Cachex.Services.Overseer.retrieve/1
    (cachex 3.4.0) lib/cachex.ex:676: Cachex.fetch/4
    (realtime 2.28.32) lib/realtime/context_cache.ex:12: Realtime.ContextCache.apply_fun/3
    (realtime 2.28.32) lib/realtime/tenants.ex:59: Realtime.Tenants.health_check/1
    nofile:1: (file)
error running container: exit 1

```

**Comment by Silur** [comment]
issue still present in version 1.172.2

**Comment by sweatybridge** [comment]
What's the output from `supabase services`?

**Comment by timobehrens** [comment]
I have a similar issue: I cannot clear my hosted DB using `npx supabase db reset --linked`. The databases are not deleted at all.

**Comment by sweatybridge** [comment]
> I cannot clear my hosted DB using npx supabase db reset --linked

@timobehrens this sounds like a separate issue with hosted project. Could you file a support ticket so we can take a closer look?

**Comment by sweatybridge** [comment]
closing as not reproducible.

**Comment by Silur** [comment]
sent a crash report in case you need more verbose logs `cf18f4347b35489d956e2714b7e5091e`

**Comment by Silur** [comment]
> closing as not reproducible.

the root cause seems to be `ipv6.disable=1` in the kernel flags. give it a try in docker with `sysctl`
