### ISSUE TITLE
Functions deploy does not work on Windows

### ISSUE THREAD

**Issue by Curetix** [supabase/cli#226]
# Bug report

## Describe the bug

When trying to deploy a function on Windows, it throws the following error message:

```powershell
PS C:\Users\panam\Development\supabase-test> supabase functions deploy hello-world
Error: exec: "C:\\Users\\panam/.supabase/deno": file does not exist
```

I checked the directory and the file does actually exist, so it might be an issue with the slashes in the path?

## To Reproduce

1. Follow the Getting Started guide in the docs for Edge functions.
2. Run `supabase functions deploy hello-world`.
3. The process fails.

## Expected behavior

The function should be deployed.

## System information

- OS: Windows 11
- Shell: PowerShell
- Version of cli: 0.23.6

**Comment by GaryAustin1** [comment]
I've been stuck on this awhile today...
They issued 0.23.7 which got past the deploy ... 
but then I hit this:
 mkdir ~/.supabase: The system cannot find the path specified
But looks like they reverted 0.23.7 back to the old code and now 0.23.8

**Comment by awalias** [comment]
good catch @soedirgo is working on a patch now 👍

**Comment by GaryAustin1** [comment]
I guess I'll just wait as it was reverted... I think.  0.23.7 got further, but seemed still broke.

**Comment by GaryAustin1** [comment]
Waiting for scoop to get it the new version...  
Do you have to update that too?
Never used scoop before but the guide showed using that to get the cli...

**Comment by GaryAustin1** [comment]
Error: exec: "C:\\Users\\gabbo\\.supabase\\deno": file does not exist
 No Go.

**Comment by Curetix** [comment]
> Error: exec:` "C:\\Users\\gabbo\\.supabase\\deno": file does not exist` No Go. edited to have the `\\` come thru. 0.23.9

Same for me.

**Comment by GaryAustin1** [comment]
Better have it working by hackathon tomorrow or you are going to have to handicap the Linux guys somehow... ;)

**Comment by soedirgo** [comment]
😅 I don't have a Windows machine, so this will be tricky... can you try v0.23.10 once it's out?

**Comment by GaryAustin1** [comment]
The hackathon can proceed!
![image](https://user-images.githubusercontent.com/54564956/161165228-61ffa84b-94ad-453e-bc40-8ec5d60b0929.png)

**Comment by Curetix** [comment]
Yep, it's working with v0.23.10. Thanks for the quick fix @soedirgo
