### ISSUE TITLE
Realtime websocket fails to connect when running locally

### ISSUE THREAD

**Issue by samtgarson** [supabase/cli#23]
# Bug report

## Describe the bug

I use a realtime WS connection to subscribe to various updates, which works great in production. However, this seems to fail to connect when using supabase locally, with the following errors:

Server:
```
supabase-kong      | 2021/04/17 21:28:06 [error] 22#0: *10872 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: kong, request: "GET /realtime/v1/websocket?apikey=REDACTED&vsn=1.0.0 HTTP/1.1", upstream: "http://172.23.0.4:4000/socket/websocket?vsn=1.0.0", host: "localhost:8000"
```

Client:
```
browser.js?7e3c:21 
WebSocket connection to 'ws://localhost:8000/realtime/v1/websocket?apikey=REDACTED&vsn=1.0.0' failed: 
```

## To Reproduce

Just subscribing to events according to the docs, as mentioned it works perfectly in prod. The relevant file is [here](https://github.com/samtgarson/dobble/blob/main/src/services/data-client.ts#L260-L306), and a screenshot below; I'll try to make a recreation in the meantime you might be able to confirm this as an easy case of user error 😅 

```
supabase-kong      | 2021/04/17 21:28:06 [error] 22#0: *10872 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: kong, request: "GET /realtime/v1/websocket?apikey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoiYW5vbiJ9.36fUebxgx1mcBo4s19v0SzqmzunP--hm_hep0uLX0ew&vsn=1.0.0 HTTP/1.1", upstream: "http://172.23.0.4:4000/socket/websocket?vsn=1.0.0", host: "localhost:8000"
```

## Expected behavior

The websocket connection should proceed and receive incoming messages from the server.

## Screenshots

![image](https://user-images.githubusercontent.com/6242344/115127077-90b6ab00-9fcb-11eb-9b08-1926efea45e1.png)

## System information

- OS: Mac OS (M1, Big Sur 11.0.1)
- Browser (if applies) Chrome
- Version of supabase-js: 
  ```
  "@supabase/supabase-js": "^1.7.1"
  "supabase": "^0.3.8"
  ```

- Version of Node.js: 15.8.0

**Comment by samtgarson** [comment]
A little more investigation—the `realtime` container is crashing on start with the following error:
![image](https://user-images.githubusercontent.com/6242344/115149894-053a2a00-a05e-11eb-98cb-6655545af5ee.png)

I'll continue when I have time but this feels like it could be an architecture issue—I wonder if anyone on the team has had success running this locally on an M1 machine, or if this issue has come up before?

Without supporting multiple redirects on the hosted auth server, this seems to be the easiest way to do local development without spinning up an entire new Supabase project and migrating everything across.

**Comment by kiwicopple** [comment]
It looks like Realtime isn't starting at all. So my initial thoughts are:

1. An M1/architecture issue, as you point out. Unfortunately nobody in the team has an M1 machine yet.
2. Unable to attach to the database, so failing to start

1 is the most likely candidate. The team is quite stretched at the moment so we'll dig into this asap. If you want to help contribute to this one the `release` workflow would be the best place to start: https://github.com/supabase/realtime/blob/master/.github/workflows/release.yml. As you mention, it looks like we aren't pushing the aarch releases to docker

**Comment by samtgarson** [comment]
Building a docker image for realtime locally solved the issue 👍  PR submitted to add ARM to the docker build pipeline.

**Comment by kiwicopple** [comment]
Amazing work @samtgarson - great contribution ⚡

**Comment by kiwicopple** [comment]
Reopening this because the GitHub Action didn't seem to pick up the new architecture

**Comment by w3b6x9** [comment]
> Reopening this because the GitHub Action didn't seem to pick up the new architecture

@soedirgo got it working with https://github.com/supabase/realtime/commit/eed8a4dbec310069f3eaad68319d70f0b8e3dcd6.

**Comment by soedirgo** [comment]
@samtgarson I had this issue before on M1 with a different amd64 image and increasing Docker's memory to 8GB (I think the default was 2GB?) fixed it. Can you check if that works for you? (Or you can simply use the arm64 version for now.)

**Comment by samtgarson** [comment]
Thanks for the quick work!

@soedirgo just tried, could be missing something but it didn't seem to make a difference 🤔
