### ISSUE TITLE
Locally debug supabase functions through debugger

### ISSUE THREAD

**Issue by dev-personalx** [supabase/cli#2311]
**Is your feature request related to a problem? Please describe.**
I would love to spin up supabase functions through 
`supabase functions serve` and attach to a debugger.

**Describe the solution you'd like**
Since supabase edge runtime already allows for attaching a debugger. [PR](https://github.com/supabase/edge-runtime/pull/245)
We should have the option of passing in --debug option from `supabase functions serve` to supabase edge runtime,

**Describe alternatives you've considered**
The alternative is to add sufficient logging

**Comment by laktek** [comment]
You can now use Chrome DevTools to debug Edge Functions https://supabase.com/docs/guides/functions/debugging-tools (also check the video tutorial on how to use it https://www.youtube.com/watch?v=sOrtcoKg5zQ)
