### ISSUE TITLE
CLI fails to pull postgrest v12.1

### ISSUE THREAD

**Issue by ImPrankster** [supabase/cli#2321]
**Describe the bug**
When running `supabase start` the CLI errors with "failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v12.1 not found: manifest unknown: Requested image not found"

**To Reproduce**
Run `supabase start` with an empty project

**Expected behavior**
Does not error

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Version of OS: 14.5 (23F79)
 - Version of CLI: 1.167.4
 - Version of Docker: Docker version 25.0.5, build 5dc9bcc
 - Versions of services: [output from `supabase services` command]
  
[38;5;252m[0m[38;5;252m[0m  [38;5;252m      SERVICE IMAGE      │        LOCAL         │  LINKED[0m
[0m[38;5;252m[0m  [38;5;252m─────────────────────────┼──────────────────────┼────────────[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/postgres      │ 15.1.1.54            │ 15.1.1.54[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/gotrue        │ v2.151.0             │ v2.151.0[0m
[0m[38;5;252m[0m  [38;5;252m  postgrest/postgrest    │ v12.1              │ v12.1[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/realtime      │ v2.28.32             │ -[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/storage-api   │ v1.2.1               │ v1.2.1[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/edge-runtime  │ v1.49.0              │ -[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/studio        │ 20240506-2976cd6     │ -[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/postgres-meta │ v0.80.0              │ -[0m
[0m[38;5;252m[0m  [38;5;252m  supabase/logflare      │ 1.4.0                │ -[0m
[0m[38;5;252m[0m  [38;5;252m  bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -[0m
[0m[38;5;252m[0m  [38;5;252m  darthsim/imgproxy      │ v3.8.0               │ -[0m
[0m

**Comment by sweatybridge** [comment]
Could you delete `supabase/.temp` directory and try again?

I believe this is an issue with PostgREST not released properly on the hosted platform. It affects some linked projects. I've reached out to internal teams to take a closer look.

**Comment by AaronSmothers** [comment]
Having the same issue here, will try the .temp delete.

**Comment by AaronSmothers** [comment]
> Having the same issue here, will try the .temp delete.

Looks like whatever updates were made has resolved this issue for me. Thanks for the weekend vigilance ya'll.

**Comment by ImPrankster** [comment]
> > Having the same issue here, will try the .temp delete.
> 
> Looks like whatever updates were made has resolved this issue for me. Thanks for the weekend vigilance ya'll.

I still have the issue, what did u try besides deleting .temp

**Comment by eifr** [comment]
> Could you delete `supabase/.temp` directory and try again?
> 
> I believe this is an issue with PostgREST not released properly on the hosted platform. It affects some linked projects. I've reached out to internal teams to take a closer look.

deleted `supabase/.temp` fixed it for me :)

**Comment by sweatybridge** [comment]
We have added PostgREST 12.1 to our ECR and GHCR image registries. This should be fixed now.

**Comment by williamoverton** [comment]
To fix it for me I had to run `supabase link` **and then** delete `supabase/.temp`
