### ISSUE TITLE
Supabase start giving "failed to display json stream" error

### ISSUE THREAD

**Issue by SeonaidhMorrison** [supabase/cli#2328]
**Describe the bug**
When I try to run supabase start using supabase cli locally, I am met with this error: failed to display json stream: failed to extract layer sha256:{shakey}: failed to get reader from content store: blob sha256:{shakey} expected at /var/lib/desktop-containerd/daemon/io.containerd.content.v1.content/blobs/sha256/{shakey}: blob not found: not found

**To Reproduce**
1. Run supabase init successfully
2. Set up docker on device
3. Try to run supabase start as admin

**Expected behavior**
Supabase start works as expected

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [611f3a9cf1584f5c9fc3bcb2b7df0664]
 - Version of OS: [Windows 11]
 - Version of CLI: [v1.169.6]
 - Version of Docker: [4.30.0]
 - Version of Services
        SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼────────────
    supabase/postgres      │ 15.1.1.25            │ 15.1.1.25
    supabase/gotrue        │ v2.151.0             │ v2.151.0
    postgrest/postgrest    │ v12.0.2              │ v12.0.2
    supabase/realtime      │ v2.28.32             │ -
    supabase/storage-api   │ v1.2.1               │ v1.2.1
    supabase/edge-runtime  │ v1.53.3              │ -
    supabase/studio        │ 20240514-6f5cabd     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Comment by sweatybridge** [comment]
Could you check that `Use containerd ...` option is unset in docker settings?

<img width="900" alt="Screenshot 2024-05-28 at 5 57 06 PM" src="https://github.com/supabase/cli/assets/1639722/5ba4c2b6-ab3a-4528-906d-3c1c1db6cfbb">

This might be caused by api differences between docker engine and containerd.

**Comment by SeonaidhMorrison** [comment]
> Could you check that `Use containerd ...` option is unset in docker settings?
> 
> <img alt="Screenshot 2024-05-28 at 5 57 06 PM" width="900" src="https://private-user-images.githubusercontent.com/1639722/334651323-5ba4c2b6-ab3a-4528-906d-3c1c1db6cfbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTk2NjEsIm5iZiI6MTcxODU1OTM2MSwicGF0aCI6Ii8xNjM5NzIyLzMzNDY1MTMyMy01YmE0YzJiNi1hYjNhLTQ1MjgtOTA2ZC0zYzFjMWRiNmNmYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTZUMTczNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYxNDRlNTRmY2UwZmZhM2FlMjNkZGRiNjFiMThiZmJjYTZiMTBhYzEyN2FiYTYxNzBmZjBiY2ZmNmQ4ODk4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AQ7ZXpG4zsRKGbaJDgzyp8K-1BqL6FwIkD7n7wg77qs">
> This might be caused by api differences between docker engine and containerd.

This worked! Thanks for your help
