### ISSUE TITLE
Enable Graphql in Kong

### ISSUE THREAD

**Issue by Marviel** [supabase/cli#233]
[Graphql routes are missing from Kong Config](https://github.com/supabase/cli/blob/160e898f83aaf58e826bf726fe5742f39561621e/internal/start/templates/kong_config#L46)

# Feature request
Graphql should be enabled in Kong just like it is in [the master supabase repo self-hosted example](https://github.com/supabase/supabase/blob/21f9e79799bdc37278951c1e0cf600422d38cf25/docker/volumes/api/kong.yml#L98)

## Is your feature request related to a problem? Please describe.

Yes, currently we cannot query graphql in the version of supabase produced by the CLI, though #232 fixes the database-level concern there.

## Describe the solution you'd like
I *think* all that needs to happen is the addition of the new route to Kong... but we may also have to update the postgrest container version. Not sure yet.

**Comment by soedirgo** [comment]
Made a small attempt here https://github.com/supabase/cli/pull/238, but I'm not familiar with pg_graphql. Are able to verify if that works?
