### ISSUE TITLE
`ERROR: extension "pg_cron" must be installed in schema "pg_catalog"` After `1.169.8` Upgrade

### ISSUE THREAD

**Issue by barrownicholas** [supabase/cli#2342]
**Describe the bug**
After upgrading the CLI to `1.169.8`, I am now getting the following error when trying to run the following command:

### Command
```plpgsql
create extension if not exists "pg_cron" with schema "extensions";
```

### Error
```text
ERROR: extension "pg_cron" must be installed in schema "pg_catalog" (SQLSTATE 0A000)
At statement 0: create extension if not exists "pg_cron" with schema "extensions"  
```

**To Reproduce**
1. Upgrade CLI to latest (`1.169.8`)
2. Try to enable `pg_cron`

**Expected behavior**
`pg_cron` was previously working fine (I'm getting this error in a schema diff from 12/13/2023). 

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: `bb7f78fa80d54d5a90bd0016c251d4fe`
 - Version of OS: macOS `13.3 (22E252)`
 - Version of CLI: `1.169.8`
 - Version of Docker: `Docker version 26.1.1, build 4cf5afa`
 - Versions of services:

```
        SERVICE IMAGE      │        LOCAL         │ LINKED
  ─────────────────────────┼──────────────────────┼─────────
    supabase/postgres      │ 15.1.1.41            │ -
    supabase/gotrue        │ v2.151.0             │ -
    postgrest/postgrest    │ v12.0.1              │ -
    supabase/realtime      │ v2.28.32             │ -
    supabase/storage-api   │ v1.0.6               │ -
    supabase/edge-runtime  │ v1.53.3              │ -
    supabase/studio        │ 20240514-6f5cabd     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

**Comment by barrownicholas** [comment]
Update 1: is this behavior intentional? I am now seeing the following in the dashboard:

<img width="1624" alt="Screenshot 2024-05-29 at 12 34 59 PM" src="https://github.com/supabase/cli/assets/75350582/86173aaa-ee82-4d7e-8b03-2f1b23f60803">

**Comment by barrownicholas** [comment]
Update 2 (for visibility):

- manually modifying my schema diff file seems to fix this:
~~`create extension if not exists "pg_cron" with schema "extensions";`~~
`create extension if not exists "pg_cron" with schema "pg_catalog";
`

**Comment by sweatybridge** [comment]
Yup, that is a good fix.

The new Postgres image ships with version 1.6.2 of pg_cron which requires it to be installed in `pg_catalog` schema.
