### ISSUE TITLE
Publications are not included in `supabase db changes`

### ISSUE THREAD

**Issue by Marviel** [supabase/cli#235]
# Bug report

## Describe the bug

When running `supabase db changes`, publication configurations are not included in the output.

For example, to configure the realtime server to listen to everything (for simplicity) we do this right now: 

```sql
begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication, enable for all tables.
  CREATE PUBLICATION supabase_realtime FOR ALL TABLES;
commit;
```

However, if this command is run, the `supabase db changes` will show that nothing has happened on the local database.

## To Reproduce

Make publication changes, run `supabase db changes`

## Expected behavior

Publication configurations should be included in `supabase db changes`. I am not skilled enough in postgres toolsets to know if this is a concern with not targeting the right namespaces, or if it's a limitation of pgAdmin 4's Schema Diff utility... however given the fact that a simple SQL command (`select * from pg_catalog.pg_publication;`) can be run to show all publications, I would have to assume this could be fixed at some level without too much issue.

**Comment by soedirgo** [comment]
Thanks for reporting this. As you said, this is a limitation of the schema diff - not much the CLI can do about it. The autogenerated diff doesn't capture everything, so for cases like this you'd need to review & modify the diff manually.
