### ISSUE TITLE
Supabase cli cannot load migrations

### ISSUE THREAD

**Issue by mohit2530** [supabase/cli#2357]
**Describe the bug**
Trying to reset the local db with `npx supabase db reset` fails with error - 
```
ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" (SQLSTATE 23505)                 
At statement 19: INSERT INTO supabase_migrations.schema_migrations(version, name, statements) VALUES($1, $2, $3)
```

**To Reproduce**
1. Open terminal on selected project.
2. Run command `npx supabase db reset`
3. Reset is successful but when after setting up initial schema, error message is seen.

**Expected behavior**
This should not happen ( I believe ). When we are resetting the database locally, I think the migrations should either be applied or removed.

**Screenshots**
![image](https://github.com/supabase/cli/assets/44540219/5722b1ce-ae74-4100-b0cf-6125b776ec7b)

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: d5ab641e1e1941469be3d99f64d635cb
 - Version of OS: Windows 11, running on WSL
 - Version of CLI: 1.72.2
 - Version of Docker: **Docker version 26.1.2, build 211e74b**
 - Versions of services: 
![image](https://github.com/supabase/cli/assets/44540219/b10ddd8c-4f37-4a63-978a-f9c8ce711101)

**Additional context**

**Node version -** 
![image](https://github.com/supabase/cli/assets/44540219/e4a996c7-0d09-4635-a2a6-2b5c9a91d31b)

**Comment by sweatybridge** [comment]
How did you generate `_load_user_profile` migration file? It should not contain any inserts to `supabase_migrations.schema_migrations` table.

You can fix this error by removing line 19.
