### ISSUE TITLE
Missing GoTrue environment variables in config.toml

### ISSUE THREAD

**Issue by hypervisor** [supabase/cli#2397]
**Is your feature request related to a problem? Please describe.**
`config.toml` seems to be missing options for OTP expiration (seconds) and length (digits). This makes it harder to work with OTPs locally if you change the length specifically (expiration doesn't really matter).

**Describe the solution you'd like**
I'd like an option added like `auth.email.otp_length` to `config.toml`

**Describe alternatives you've considered**
None applicable.

**Additional context**
Possibly related discussion: https://github.com/orgs/supabase/discussions/26330

This is already adjustable in the managed studio: 

![Skjermbilde 2024-06-09 kl  00 30 28](https://github.com/supabase/cli/assets/35572104/035947cc-68de-4663-abd5-fec72591fc9f)

But remote and local needs to match here.

**Comment by makhil006** [comment]
+1

**Comment by sweatybridge** [comment]
This has been addressed by new configs added in https://github.com/supabase/cli/pull/2810
