### ISSUE TITLE
service role key provided by cli is not working as expected

### ISSUE THREAD

**Issue by ff6347** [supabase/cli#24]
# Bug report

The service role key provided by the cli seems not to be the right one. When I try to run this command in the shell:

```
curl -X POST 'http://localhost:8888/auth/v1/signup' \
-H "apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "123456"
}'
```

I get this response

```
{
  "message":"Invalid authentication credentials"
}
```

The JWT_SECRET (`super-secret-jwt-token-with-at-least-32-characters-long`) is indeed the one that was used to sign this key, but something seems to be missing?

## To Reproduce

clone the repo https://github.com/ff6347/supabase-cli-gives-non-functional-service-role-key
run `npx supabase start`
run `node index.mjs` or the command above
## Expected behavior

>A clear and concise description of what you expected to happen.

I expect the key to work.

## System information

- OS: macOS 11.2.3
- Version of supabase-js:

```
  "dependencies": {
    "@supabase/supabase-js": "1.11.7",
    "supabase": "0.3.8"
  }
```

- Version of Node.js: 14.16.0

**Comment by kiwicopple** [comment]
Hey @ff6347 - the anon key actually acts as the apikey, and you can use the SERVICE_KEY as an Auth Bearer token like this:

```
curl -X POST 'http://localhost:8888/auth/v1/signup' \
-H "apikey: ANON_KEY" \
-H "Authorization: Bearer SERVICE_KEY" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "123456"
}'
```

This is also how "logged in users" work too:

```
curl -X POST 'http://localhost:8888/auth/v1/signup' \
-H "apikey: ANON_KEY" \
-H "Authorization: Bearer USER_JWT" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "123456"
}'
```

I'll close this, and if I have misunderstood the issue or you have any other questions, feel free to reopen 👍

**Comment by ff6347** [comment]
Hi @kiwicopple thanks for the swift reply. That worked. I was so sure I tried that. :/

What about doing that same thing with the js library? I tried the following:

```ts
// output from the cli on creation
// Supabase URL: http://localhost:8888
// Supabase Key (anon, public): eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoiYW5vbiJ9.36fUebxgx1mcBo4s19v0SzqmzunP--hm_hep0uLX0ew
// Supabase Key (service_role, private): eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI
// Database URL: postgres://postgres:postgres@localhost:5432/postgres

// Run supabase start to start local Supabase.

// Create a single supabase client for interacting with your database
import { createClient } from "@supabase/supabase-js";


const supabase = createClient(
  "http://localhost:8888",
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI",
  {
    headers: {
      apikey:
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoiYW5vbiJ9.36fUebxgx1mcBo4s19v0SzqmzunP--hm_hep0uLX0ew",
    },
  }
);

async function main() {
  const { user, session, error } = await supabase.auth.signUp({
    email: "example@email.com",
    password: "example-password",
  });
  console.log(user, session, error);
}

main().catch(console.error);

```

```bash
node index.mjs
```

I get this response.

```bash
null null { message: 'Invalid authentication credentials', status: 401 }
```

To put this in more context. We are developing a project that uses supabase from the  React frontend and that has also a Fastify backend. The backend is called from the frontend and does some computation and inserts data on the users behalf.

That works pretty well. I can log in an user, make a request with his token to our backend, insert some data etc. My backend supabase client gets initialized with the service role key only. 

On your cloud platform everything works fine.

Now I'm trying to write integration tests and want to:

- spin up a local supabase version, (✓)
- signup a user (get his token), (✓)
- make a request to my backend with his token, (✓)
- make the computation and insert data on his behalf (✘)

The last point is where I'm stuck. Somehow my backend seems not to be able to make a request to the local supabase instance when I initialize the client with that service role key.

I ran the node script above against the remote supabase instance and I can signup a user. But on the local version it fails. That is why I think something must be off with the service role key.

**Comment by ff6347** [comment]
BTW. I can't reopen the issue.

**Comment by kiwicopple** [comment]
Actually you're completely right - the Service Role key should be also an API key here:

https://github.com/supabase/cli/blob/111303e339e396e66726c5ac21f08685035c786f/src/templates/init/docker/kong/kong.yml#L42

If you add this to your `.supabase/docker/kong/kong.yml` then you can use it as an API key. Then when you set up the client you should use:

```js
const supabase = createClient(
  "http://localhost:8888",
  SERVICE_ROLE_KEY
);
```

This is a bit of an oversight on our side. very sorry about the @ff6347 - really appreciate you bringing this to our attention

**Comment by ff6347** [comment]
Yay! It works. Thank you. 

![](https://media0.giphy.com/media/cklPOHnHepdwBLRnQp/giphy.gif)

Keep up the good work with supabase. We are totally looking forward to migrations and functions.

**Comment by kiwicopple** [comment]
Nice! I'm going to reopen this because we need to add this to the generated file for everyone else

> We are totally looking forward to migrations and functions

Working hard on them!

**Comment by sroussey** [comment]
> Actually you're completely right - the Service Role key should be also an API key here:
> If you add this to your `.supabase/docker/kong/kong.yml` then you can use it as an API key. 

If you add what??

**Comment by ff6347** [comment]
> If you add what??

You beat me to it and I think your change is right. That is what I would have done. 🚀

**Comment by kiwicopple** [comment]
Thank you team, really appreciate the help here 💚 

the team is quite busy so this is a big help

**Comment by kiwicopple** [comment]
fixed by https://github.com/supabase/cli/pull/25
