### ISSUE TITLE
Error with import_map.json. - import_map.json includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by luisfcofv** [supabase/cli#2409]
**Describe the bug**
Error with the latest Supabase CLI version when running `functions serve --env-file .env` or running `supabase start`.

I get this error:
```
Setting up Edge Functions runtime...
failed to create volume: Error response from daemon: create supabase/functions/import_map.json: "supabase/functions/import_map.json" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
Try rerunning the command with --debug to troubleshoot the error.
```

It works if I downgrade the Supabase CLI. 
Right now I'm using v1.174.4, but I'm not sure if there are more recent versions that work.

**To Reproduce**
1. `supabase start`
2. See the error

**Expected behavior**
It should work

**System information**
 - Version of OS: MacOS 
 - Version of CLI: v1.176.2

**Comment by sweatybridge** [comment]
Could you provide more details to help me reproduce? `ls -la supabase/functions`

**Comment by joeldomke** [comment]
I have the same issue. Here are the logs when I run `supabase start`:

```
Applying migration [...]
Seeding data supabase/seed.sql...
Stopping containers...
failed to create volume: Error response from daemon: create supabase/functions/import_map.json: "supabase/functions/import_map.json" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

I'm also v1.176.2

**Comment by sweatybridge** [comment]
Thanks for helping to identify the bug. I will release a fix soon.
