### ISSUE TITLE
Cannot resolve (maybe corrupted) local database

### ISSUE THREAD

**Issue by oddanderson** [supabase/cli#2414]
Long story short, I created tables in the project editor before thinking about migrations, etc.

I'm not trying to move to a more sustainable deployment path where I do all changes locally, generate migrations, etc.

No matter what I do to reset / start over, I end up with the error code `error running container: exit 1`

Here's what I've tried
```
npx supabase db reset --linked  
~~ delete migration in migrations folder
npx supabase stop --no-backup
npx supabase start
```

I get the following error from --debug
```
** (ArgumentError) could not call Module.put_attribute/3 because the module Realtime.Repo.Migrations.CreateTenants is already compiled
(elixir 1.14.3) lib/module.ex:2504: Module.assert_not_readonly!/2
(elixir 1.14.3) lib/module.ex:2201: Module.__put_attribute__/5 /app/lib/realtime-2.28.32/priv/repo/migrations/20220329161857_add_extensions_table.exs:2: (module)
nofile:1: (file)
2024/06/11 16:20:45 Sent Header: Host [api.moby.localhost]
2024/06/11 16:20:45 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
```

I'm ok completely wiping my DB, I just don't want to start a new project

**Comment by sweatybridge** [comment]
Could you provide more info about your local system?

Cli version
supabase services
Docker version
OS version

**Comment by filipecabaco** [comment]
From the error it seems that the Realtime container got recompiled which is something I would not expect to see since they have already been compiled 🤔 

Do all containers fail to start when the error happens?

**Comment by filipecabaco** [comment]
Could you remove the Realtime time containers and images and then try to boot up again?
```
docker container rm $(docker container ls -a | grep realtime | awk '{print $1}')
docker rmi $(docker images | grep realtime | awk '{print $3}')         
```

**Comment by filipecabaco** [comment]
I will keep investigating what could have been as this is very unexpected as the compilation shouldn't be happening after the image as been built so I need to understand what could be triggering the recompilation of Realtime🤔

**Comment by filipecabaco** [comment]
Thank you for the hints and sorry for the incovenience 🙏
