### ISSUE TITLE
Updating to v1.176.4 breaks `db pull`

### ISSUE THREAD

**Issue by Ronyo** [supabase/cli#2417]
**Describe the bug**
After upgrading from v1.172.2 running `supabase db pull` results in an error.
It seems that the command is spinning up a `nextjs-subscription-payments` container complains that it is running and taking the port it needs.
This prevents me from generating TS types and deploying without shipping TS issues.

**To Reproduce**
1. Follow instructions from the [nextjs stater](https://github.com/vercel/nextjs-subscription-payments)
2. Create new database table
3. Run `supabase db pull`

**Expected behavior**
No errors when pulling db schema.

**Screenshots**

**System information**
n/a

**Additional context**
Node - v20.11.0

**Comment by sweatybridge** [comment]
This is likely unrelated to version upgrade. What's the output from `docker ps -a`?

You can stop the container that's taking the port following the suggestion from cli.

**Comment by Ronyo** [comment]
Downgrading the package to `1.172.2` resolved all of the issues without doing anything else.
Stopping the container didn't help because the command was starting it again before complaining about it.

I'm not sure about `docker ps -a` because I moved to other things after resolving the problem.
