### ISSUE TITLE
Reset breaks my database

### ISSUE THREAD

**Issue by mikestopcontinues** [supabase/cli#2449]
**Describe the bug**
I tried to reset my cloud database (staging instance, fwiw), and my environment broke. It seems a transaction failed and didn't clean-up, so now I can't connect and the reset isn't finished.

**To Reproduce**
1. Run `supabase db reset --linked`
2. See error

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: ac30891d94e943778d1044ebfbe57dbb
 - Version of OS: OSX 14.5
 - Version of CLI: 1.178.2
 - Version of Docker: 4.31.0
 - Versions of services: 

```
        SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.1.0.153       │ 15.1.0.153
    supabase/gotrue        │ v2.152.1         │ v2.152.1
    postgrest/postgrest    │ v12.0.1          │ v12.0.1
    supabase/realtime      │ v2.28.32         │ -
    supabase/storage-api   │ v1.5.1           │ v1.5.1
    supabase/edge-runtime  │ v1.54.6          │ -
    supabase/studio        │ 20240422-5cf8f30 │ -
    supabase/postgres-meta │ v0.80.0          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
    darthsim/imgproxy      │ v3.8.0           │ -
```

**Comment by sweatybridge** [comment]
Do you have the postgres logs from the hosted project to help me investigate?
