### ISSUE TITLE
error "graphql_public" does not exists with cli supabase start

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/cli#246]
# Bug report

A customer using the CLI with a new install is getting this:

"I'm trying to execute. supabase start but i got this error  Error: Error starting database: ERROR:  schema "graphql_public" does not exist"

No info yet, but putting this out here in case the code added here for pg_graphql is already being installed by the CLI and there might be an issue with the pg_graphql extension.   Would not have expected customer to run into it yet.

@olirice I noticed the push 4 days ago, so flagging in case an early issue has been found.

**Comment by madsbuch** [comment]
@olirice Let me see if I can find time to make reproduction over the weekend.

The problem occurred after attempting to issue a `supabase start` subsequently to a `supabase db remote commit`. Ie. the migration created by `supabase db remote commit` included the error.

Note: the GraphQl extension was not activated on the project while the migration still included `CREATE OR REPLACE FUNCTION graphql_public.graphql ...`

**Comment by soedirgo** [comment]
pg_graphql should work on the CLI as of v0.24.6. Sorry for the wait!

**Comment by princemaple** [comment]
Hi, how can I get myself out of this stuck state?

```
Error: Error starting shadow database: NOTICE:  event trigger "api_restart" does not exist, skipping
NOTICE:  function extensions.notify_api_restart() does not exist, skipping
NOTICE:  event trigger "api_restart" does not exist, skipping
NOTICE:  function extensions.notify_api_restart() does not exist, skipping
NOTICE:  extension "pg_graphql" does not exist, skipping
```

The migration was generated with an older version of cli. I cannot manually remove the migration row in the schema migrations table. If I delete the migration file, it tells me this:

```
Error: The remote database's migration history is not in sync with the contents of supabase/migrations. Resolve this by:
- Updating the project from version control to get the latest supabase/migrations,
- Pushing unapplied migrations with supabase db push,
- Or failing that, manually inserting/deleting rows from the supabase_migrations.schema_migrations table on the remote database.
```

**Comment by princemaple** [comment]
I think we are making progress. Now the main issue is just `moddatetime`. It doesn't complain about `pg_graphql` anymore.

```
Error: Error starting shadow database: ERROR:  function extensions.moddatetime() does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
.....
```

**Comment by princemaple** [comment]
Is there any way for me to re-generate the initial migration?

**Comment by soedirgo** [comment]
Does your hosted Supabase project have the `moddatetime` extension enabled? If so you can create `supabase/extensions.sql` with contents `CREATE EXTENSION moddatetime SCHEMA extensions`.

**Comment by princemaple** [comment]
After adding `extensions.sql` and re-arranging the migration a little, it's working now :) Thanks a lot for the help!

**Comment by sweatybridge** [comment]
For future reference, we no longer support `supabase/extensions.sql` since CLI v1. We have fixed postgres permissions such that `create extension` statements should work in migration scripts.
