### ISSUE TITLE
Cannot exclude `vector` from `supabase start`

### ISSUE THREAD

**Issue by boozedog** [supabase/cli#2475]
**Describe the bug**
I'm not using pgvector in my application and I'd like to exclude it. But supabase-cli refuses to start if it's excluded

**To Reproduce**
`supabase start --exclude "vector"`

**Expected behavior**
Supabase local starts without vector

**Screenshots**
```
❯ supabase start --exclude "vector"

failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused
Try rerunning the command with --debug to troubleshoot the error.
```

**System information**
```
❯ cat /etc/lsb-release 
DISTRIB_CODENAME=vicuna
DISTRIB_DESCRIPTION="NixOS 24.11 (Vicuna)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="24.11"
LSB_VERSION="24.11 (Vicuna)"

❯ node --version
v20.11.1

❯ supabase --version
1.178.2

❯ docker --version
Docker version 24.0.9, build v24.0.9
```

**Comment by sweatybridge** [comment]
The [vector service](https://github.com/vectordotdev/vector) refers to log ingestion for analytics, not pgvector. You can disable analytics in config.toml if you don't want to use it.

**Comment by boozedog** [comment]
Ah, thanks for the clarification. I thought it was [Supabase Vector](https://supabase.com/vector) :wink:
