### ISSUE TITLE
When developing locally Studio configuration assumes API is running on port configured in API section

### ISSUE THREAD

**Issue by Paul-HeathCo** [supabase/cli#2491]
When running in dev container (code spaces) endpoints get forwarded. So API endopoint of http://127.0.0.1:54321 becomes https://codespace123-54321.app.github.dev (running on port 443). There is no way to configure this in .toml file because studio setup code [here](
https://github.com/supabase/cli/blob/5e8237478d00a06d54ead1b050d12ea88d8eaf2d/internal/start/start.go#L913C71-L913C97) assumes API endpoint is running  at port 54321 (as configured in API section).

Proposed fix is to allow to specify port explicitly like sample below:

```
[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "https://codespace123-54321.app.github.dev:443" 
```

**Comment by sweatybridge** [comment]
Could you show me a screenshot of studio or network tabs that is broken due to this misconfig?
