### ISSUE TITLE
could not access file \"$libdir/wrappers-0.1.19\": No such file or directory

### ISSUE THREAD

**Issue by magick93** [supabase/cli#2492]
**Describe the bug**
Running `supabase start` fails and results in `could not access file \"$libdir/wrappers-0.1.19\": No such file or directory` from the pg container. 

**To Reproduce**
1. Run `supabase start`

**Expected behavior**
Should start local sb environment

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 5d5126eea8ee405688263931da427e08
 - Version of OS: Ubuntu 22.04
 - Version of CLI: 1.178.2
 - Version of Docker: Docker version 27.0.3, build 7d4bcd8
 - Versions of services: [output from `supabase services` command]

        SERVICE IMAGE      │      LOCAL       │  LINKED
  ─────────────────────────┼──────────────────┼────────────
    supabase/postgres      │ 15.1.1.64        │ 15.1.1.64
    supabase/gotrue        │ v2.153.0         │ v2.153.0
    postgrest/postgrest    │ v12.1            │ v12.1
    supabase/realtime      │ v2.28.32         │ -
    supabase/storage-api   │ v1.5.1           │ v1.6.4
    supabase/edge-runtime  │ v1.54.6          │ -
    supabase/studio        │ 20240422-5cf8f30 │ -
    supabase/postgres-meta │ v0.80.0          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
    darthsim/imgproxy      │ v3.8.0           │ -

**Comment by sweatybridge** [comment]
I'm not sure how your local db ends up in this state, but it could be due to a corrupt docker volume for your local db. You can try restarting from scratch. For eg.

```bash
supabase stop --no-backup
supabase start
```

**Comment by magick93** [comment]
Thanks. 
I managed to fix it by deleting the docker volumes, which I think is similar to your suggestion.
