### ISSUE TITLE
Enabling analytics cause supabase functions deploy to fail

### ISSUE THREAD

**Issue by ardabeyazoglu** [supabase/cli#2503]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Deploying supabase functions fail with following error, when [analytics] section in config.toml enabled. 

`failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused
`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add the following lines to config.toml and try to deploy a function.
```
[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"
```

2. Then set enabled to false, and try again. This time it should work.

## Expected behavior

It must work with analytics enabled, because **we need analytics in local supabase runtime for logging to work**.

## System information

- OS: Windows 11
- Version of supabase-cli: 1.178.2
- Version of Node.js: v20.15.0

**Comment by sweatybridge** [comment]
Could you try the latest cli release 1.183.5? We changed logging driver in from syslog to native docker logs to avoid this issue.

**Comment by ardabeyazoglu** [comment]
For some reason, scoop does not update since 1.178.2, as you can see in the attachment.

![image](https://github.com/supabase/cli/assets/1159836/747caa86-57a6-41ea-8ade-cac08523ad01)

**Comment by sweatybridge** [comment]
Thanks for confirming!
