### ISSUE TITLE
Invalid config for auth.email.magic_link.content_path

### ISSUE THREAD

**Issue by zhihengGet** [supabase/cli#2510]
**Describe the bug**

when starting supabsae i got 'Invalid config for auth.email.magic_link.content_path' 

i do have a template/confirm or template/magiclink in the same dir as config.toml, it works working in 183 

```

subject = "Please Cofirm Your email"
content_path ="./supabase/template/confirm.html"

[auth.email.template.magic_link]
subject = "magic_link"
content_path ="./supabase/template/magiclink.html"
```

**Expected behavior**

**Screenshots**

**System information**

windows 11 WSL with docker

**Additional context**
v1.185 and 1.86.1 failed ,

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. It was due to an refactoring oversight. It will be fixed in the next release 1.186.2.
