### ISSUE TITLE
How to add email auth through commands

### ISSUE THREAD

**Issue by 5279314** [supabase/cli#2516]
How to add the following parameters, can they be added to `config.toml `?
```
## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender
ENABLE_ANONYMOUS_USERS=false
```

**Comment by sweatybridge** [comment]
You can configure most of them in `[auth.email]` stanza. See this example: https://github.com/supabase/cli/blob/develop/pkg/config/templates/config.toml#L103

**Comment by 5279314** [comment]
Thank you for your answer. 
Another question is, how to customize the email confirmation information connection domain name?
I don't want an IP address of `127.0.0.1`
![image](https://github.com/user-attachments/assets/7c5bc066-ff94-4532-9477-7a7a15e0963a)
