### ISSUE TITLE
Error running stack locally: `supabase/postgrest:v12.2.2 not found`

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#2526]
**Describe the bug**
We get this error when running `supabase start`

> failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v12.2.2 not found: manifest unknown: Requested image not found

**To Reproduce**
1. Run supabase start

**Expected behavior**
Stack works

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 60a2f753224f4ef38eb9849ba2ba4bca
 - Version of CLI: 1.183.5
 - Versions of services:
    supabase/postgres      │ 15.1.1.78        │ 15.1.1.78
    supabase/gotrue        │ v2.155.3         │ v2.155.3
    postgrest/postgrest    │ v12.2.2          │ v12.2.2
    supabase/realtime      │ v2.29.15         │ -
    supabase/storage-api   │ v1.6.8           │ v1.6.8
    supabase/edge-runtime  │ v1.54.10         │ -
    supabase/studio        │ 20240701-05dfbec │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
    darthsim/imgproxy      │ v3.8.0           │ -

**Comment by bombillazo** [comment]
@sweatybridge I think there is a missing image in docker hub

**Comment by bombillazo** [comment]
<img width="763" alt="image" src="https://github.com/user-attachments/assets/5f496262-6d00-4627-a752-37ad3422e978">

**Comment by bombillazo** [comment]
@sweatybridge @kiwicopple  There is a missing docker image

**Comment by bombillazo** [comment]
Image was uploaded, thanks

**Comment by sweatybridge** [comment]
Yup, I've just mirrored it. Thank you for spotting it https://github.com/supabase/cli/actions/runs/9961311607/job/27522532276
