### ISSUE TITLE
Resources may not be torn down when an error is encountered

### ISSUE THREAD

**Issue by parrotmac** [supabase/cli#253]
# Bug report

## Describe the bug

When starting a local environment that has an error, most of the stack is left running. This requires a user to either tear down the stack and start it again.

## To Reproduce

Output from a local shell session (lines starting with `$` are lines I executed):
```bash
$ supabase start # This works!
$ supabase stop # Also OK!

# Do something that would result in an error
$ echo "SELECT 1 FROM table_that_does_not_exist;" >> supabase/extensions.sql

$ supabase start # Try starting DB...
Error: Error starting database: ERROR:  relation "table_that_does_not_exist" does not exist
LINE 4: SELECT 1 FROM table_that_does_not_exist;

# Fix issue that was causing grief
$ sed -i '' 's/SELECT 1 FROM table_that_does_not_exist;//g' supabase/extensions.sql

$ supabase start # Try staring again...
Error: supabase start is already running. Try running supabase stop first.
```

## Expected behavior

When an error is encountered during setup, the stack should shutdown instead of leaving the project in an inconsistent state.

## Screenshots

See annotated excerpt above

## System information

- OS: `{macOS, Linux}`
- Browser: n/a
- Version of supabase-js: n/a
- Version of Node.js: n/a

## Additional context

Also see discussion in https://github.com/supabase/cli/issues/234

**Comment by soedirgo** [comment]
Should be fixed on v0.24.10. Thanks again for the report!
