### ISSUE TITLE
Build failure with Nix

### ISSUE THREAD

**Issue by jaredramirez** [supabase/cli#254]
# Bug report

## Describe the bug

When trying to build this package with Nix with the following configuration:
```nix
(buildGoModule rec {
  pname = "supabase-cli";
  version = "0.24.5";
  src = fetchFromGitHub {
    owner = "supabase";
    repo = "cli";
    rev = "v${version}";
    sha256 = "sha256-kkMx+XDpFbU9xRmxJieO59FNGPo9NXlE5s4/ytUWw/M=";
  };
  vendorSha256 = "sha256-TGsreflIjTX8PB3MpZ82onQA/9JLh+0EZFlWLqlLAtA=";
  runVend = true;
})
```
it fails with:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8z841h152kdh967rkagygzsv1xrsx41x-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building subPackage .
internal/db/branch/create/create.go:13:2: //go:build comment without // +build comment
```

## To Reproduce

Copy the above build expression into `build.nix`, then run `nix build`. (Or `shell.nix` and run `nix shell`)

## Expected behavior

The package to be built

## System information

- OS: MacOS
- Nix Version: `nix (Nix) 2.6.0pre20211217_6e6e998`

## Additional context

I don't know much about go, so it's totally possible that my problem is that I'm forgetting some configuration when building the package!

If this can be resolved, it'd also be great to have a `flake.nix` in this repository for super easy installs!

**Comment by soedirgo** [comment]
I'm not familiar with Nix Flakes, but maybe you could try building with Go 1.18+?

**Comment by jaredramirez** [comment]
That was it, I needed to use `buildGo118Module` rather than `buildGoModule`. Here's what it looked like in the end:

```nix
(buildGo118Module rec {
  pname = "supabase-cli";
  version = "...";
  src = fetchFromGitHub { ... } ;
  vendorSha256 = "...";
})
```
