### ISSUE TITLE
'supabase stop' to use a cached version of config.toml used to start

### ISSUE THREAD

**Issue by AndreVicencio** [supabase/cli#2553]
**Is your feature request related to a problem? Please describe.**
When you use 
`supabase stop`
it references the current version of config.toml

This is an issue when supabase is alreeady running, then you make some changes to config.toml
in particular you add new environment values

Then when you call 'supabase stop' you get an error:
"Error evaluating "env(YOUR_VARIABLE)": environment variable YOUR_VARIABLE is unset."
Because these variables were not present when you executed 'supabase start'

effectively not allowing you to run 'supabase stop'

You have to remove/comment out your changes to the config.toml

**Describe the solution you'd like**
Maybe cache the version of config.toml that 'supabase start' used and use that whenever 'supabase stop' is executed.

**Comment by sweatybridge** [comment]
I don't see any clear benefits of caching over commenting out the missing envs. The complexity of implementing it is also significant because you can stop any project by its id, not just the one in current directory.
