### ISSUE TITLE
ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" 

### ISSUE THREAD

**Issue by johnconnorquigley** [supabase/cli#2564]
**Bug**
Bug was encountered while onboarding a new employee. He cloned our code repository which contained our supabase folder.
The supabase folder has the following structure:

- supabase
    - migrations -> where all of our migrations are defined in .sql files
    - config.toml
    - seed.sql

Then he ran the commands in the following order after cloning the repository and clean installing supabase:
1. `supabase start` to start the local dev stack
2. `supabase db reset` to reset the database, apply migrations, and seed the database

Note that we don't use `supabase db link` for local development, we manage all our migrations to the remote db with separate actions triggered by PRs.

He encountered the following error when `supabase db reset` tried to make the first migration:
```
ERROR: duplicate key value violates unique constraint "schema_migrations_pkey" (SQLSTATE 23505)
At statement 16: INSERT INTO supabase_migrations.schema_migrations(version, name, statements) VALUES($1, $2, $3)
```
Note: statement 16 is the last statement in our first migration file, so it appears that the issue comes not from the actual migration but when the migration is being recorded into the migrations table

We removed the migrations and seed data from his supabase folder, and have him run `supabase db reset` again and noticed that no schema_migrations schema was created (should appear below schema_functions):
![image (4)](https://github.com/user-attachments/assets/993c3465-bb14-4718-aae2-204651829226)

**Expected behavior**
For the rest of our team, this process runs without a hitch, properly applying migrations and seed data. Leading me to believe it may have something to do with the install, but we've tried a clean install to no avail. 

**Reason to suspect issue**
Have seen that there are other issues related to insertions into the schema_migrations table, although these seem to occur after linking and pulling. The issue we are experiencing however, appears to just occur during local development.

**Comment by sweatybridge** [comment]
Which version of cli are you running? Could you try `npx supabase@beta start` just to be sure?

**Comment by johnconnorquigley** [comment]
turned out something was wrong with the employee's postgres install, closing

**Comment by ThatXliner** [comment]
For those who are coming to this issue in the future, I had this issue on my local development because my migration timestamps were the same. To fix it, just recreate one of the migrations with a later timestamp

<img width="909" alt="image" src="https://github.com/user-attachments/assets/4a8f14a1-39ab-4455-b15a-04453cfba8be">

**Comment by kevin-brotcke** [comment]
For me I found a trigger was causing the data to populate before seeding, see https://github.com/supabase/cli/issues/1420.
