### ISSUE TITLE
docs: Add guidance for mounting Docker socket in Supabase CLI

### ISSUE THREAD

**Issue by tharakadesilva** [supabase/cli#2575]
**Link**

https://supabase.com/docs/guides/cli/local-development#local-logging

**Describe the problem**

When running `supabase start`, I am getting the following warning:

```
WARNING: analytics requires mounting default docker socket: /var/run/docker.sock
```

The current documentation lacks information on how to address this warning and properly mount the Docker socket when using Supabase CLI.

**Describe the improvement**

- Add a new section in the Supabase CLI documentation explaining the significance of this warning. Alternatively, if the user cannot take any action on this, remove it.
- Provide step-by-step instructions on how to mount the Docker socket.
- Explain the impact on analytics functionality if the socket is not mounted

**Additional context**

This issue was encountered when running Supabase CLI version 1.187.3.

When I try to access logs, I am seeing: 
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/7adda593-45c0-4556-83a5-9d6120952ef1">

**Comment by sweatybridge** [comment]
We have just published some docs a few days ago https://supabase.com/docs/guides/cli/getting-started

Could you let me know if it works for you?

**Comment by sweatybridge** [comment]
Thanks for confirming that the settings worked in resolving the analytics issue.

I think printing a warning isn't really a big deal given the amount of logs we already show. Perhaps we will clean up the cli logs altogether when we have the free time.

**Comment by sweatybridge** [comment]
I might have posted on the wrong issue. Anyway the step by step guide for analytics settings on windows is here 

https://github.com/supabase/cli/issues/2538#issuecomment-2246855270
