### ISSUE TITLE
supabase_vector_project container is not ready: unhealthy

### ISSUE THREAD

**Issue by noga-dev** [supabase/cli#2588]
**Describe the bug**
I tried running ```supabase start``` using 1.183.5, 1.187.10, 1.187.14, I basically kept downgrading until I go to 1.172.2 which finally worked.

**To Reproduce**
1. Install any version in the last month.
2. Run 'supabase start'
3. Observe error "supabase_vector_project container is not ready: unhealthy"

**Expected behavior**
It's supposed to run normally like version 1.172.2

**Screenshots**
[N/A]

**System information**
 - Ticket ID: 4f84685928bb4d429fa68bcf4803e93d
 - Version of OS: Windows 11 x64
 - Version of CLI: at least 1.183.5 and above (maybe lower I just started skipping more versions at once)
 - Version of Docker: Docker Desktop 4.33.1 (161083)
 - Versions of services: 
 ```
    supabase/postgres      │ 15.1.1.78        │ -
    supabase/gotrue        │ v2.151.0         │ -
    postgrest/postgrest    │ v12.2.0          │ -
    supabase/realtime      │ v2.29.15         │ -
    supabase/storage-api   │ v1.0.6           │ -
    supabase/edge-runtime  │ v1.55.0          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Additional context**
[N/A]

**Comment by sweatybridge** [comment]
Have you configured docker for windows according to our docs https://supabase.com/docs/guides/cli/getting-started?

**Comment by sweatybridge** [comment]
We print a warning text in yellow. But it's probably drowned in the other logs.

If you don't want to turn on tcp daemon, you can turn off analytics as an alternative. Just set `enabled = false` in config.toml.

**Comment by thisisone** [comment]
This article was helpful.
thank you

**Comment by TallManCycles** [comment]
Helpful. Thanks

**Comment by douglas-yokomizo** [comment]
Thanks!! I was loosing my mind over this

**Comment by timrutter** [comment]
so i have this problem described above.  I have tried enabling the daemon on the port, i have tried disabling the analytics but it still fails with 503 and then terminates everything.  I'm using docker for windows.

**Comment by sweatybridge** [comment]
@timrutter changing the port should be fine. Could you try the suggestion here https://github.com/supabase/cli/issues/2753#issuecomment-2410246004

**Comment by islycodes** [comment]
Thanks! was very helpful.

**Comment by Hermes-fire** [comment]
> > Have you configured docker for windows according to our docs https://supabase.com/docs/guides/cli/getting-started?
> 
> Hmm, I see now, that the SS on that page shows that "Expose daemon on tcp://localhost:2375 without TLS" is supposed to be toggled on. And after doing so, I'm able to run Supabase on latest. But I don't want it turned on. Any way around this?
> 
> Also, shouldn't the error from the CLI be more useful than 'container is not ready: unhealthy?"

Expose daemon on tcp://localhost:2375 without TLS works for me

**Comment by Hermes-fire** [comment]
> > Have you configured docker for windows according to our docs https://supabase.com/docs/guides/cli/getting-started?
> 
> Hmm, I see now, that the SS on that page shows that "Expose daemon on tcp://localhost:2375 without TLS" is supposed to be toggled on. And after doing so, I'm able to run Supabase on latest. But I don't want it turned on. Any way around this?
> 
> Also, shouldn't the error from the CLI be more useful than 'container is not ready: unhealthy?"

Well seen, thanks, "Expose daemon on tcp://localhost:2375 without TLS" allowed me to start supabase_vector container.

**Comment by Rednas83** [comment]
I had the same thing, but I forgot to set the correct boxes under `Docker>Settings>General`. It is also mentioned in the docs but it is very easily overlooked

![Image](https://github.com/user-attachments/assets/f998fb57-8e53-4e1c-9bbc-ad654accb984)

**Comment by kevinkip** [comment]
After trying all the suggestions provided, I realized that I had other public ecr repo login credentials.

After running `docker logout public.ecr.aws`, I was able to start supabase.

**Comment by Jonny1987** [comment]
This option is no longer available in docker desktop so how can Expose daemon on tcp://localhost:2375?

**Comment by abrahamgtech** [comment]
> This option is not available in docker desktop for linux so how can Expose daemon on tcp://localhost:2375? It's pretty essential to have logs locally whille developing so database changes can be debugged

Please, can this be looked into. I am on an ubuntu environment @sweatybridge

**Comment by sweatybridge** [comment]
@abrahamgtech all our CI runs on linux and there's no problem reading logs from unix domain socket. Could you open a new issue with more details about your local environment, service versions, etc. Basically follow the new issue template

**Comment by abrahamgtech** [comment]
> We print a warning text in yellow. But it's probably drowned in the other logs.
> 
> If you don't want to turn on tcp daemon, you can turn off analytics as an alternative. Just set `enabled = false` in config.toml.

Thank you for your response, I had to disable analytics in the config.toml

**Comment by Jonny1987** [comment]
> [@abrahamgtech](https://github.com/abrahamgtech) all our CI runs on linux and there's no problem reading logs from unix domain socket. Could you open a new issue with more details about your local environment, service versions, etc. Basically follow the new issue template

But don't we need to turn on the "expose daemon" setting in docker desktop? My docker desktop doesn't have this option (latest version, apparently this is a windows only feature now: [https://docs.docker.com/desktop/settings-and-maintenance/settings/](https://docs.docker.com/desktop/settings-and-maintenance/settings/))

**Comment by sweatybridge** [comment]
> But don't we need to turn on the "expose daemon" setting in docker desktop?

No need. The expose daemon is only a workaround on windows due to the lack of domain socket. This should not be necessary on Linux and macOS.

**Comment by Jonny1987** [comment]
The only way I managed to get this working on ubuntu is:

1) Running this first to create a proxy socket:
```
   sudo socat UNIX-LISTEN:/var/run/docker.sock,fork,user=$USER,group=docker,mode=660 UNIX-CONNECT:$HOME/.docker/desktop/docker.sock
```

2) Starting supabase using:

```
DOCKER_HOST=unix:///var/run/docker.sock supabase start
```


I tried setting DOCKER_HOST AND DOCKER_SOCKET_LOCATION to unix://$HOME/.docker/desktop/docker.sock but it didn't work

**Comment by vuquocan1987** [comment]
I am having same problem with Ubuntu, It only works if I disable analytic.

**Comment by iansummerlin** [comment]
> The only way I managed to get this working on ubuntu is:
> 
> 1. Running this first to create a proxy socket:
> 
> ```
>    sudo socat UNIX-LISTEN:/var/run/docker.sock,fork,user=$USER,group=docker,mode=660 UNIX-CONNECT:$HOME/.docker/desktop/docker.sock
> ```
> 
> 2. Starting supabase using:
> 
> ```
> DOCKER_HOST=unix:///var/run/docker.sock supabase start
> ```
> 
> I tried setting DOCKER_HOST AND DOCKER_SOCKET_LOCATION to unix://$HOME/.docker/desktop/docker.sock but it didn't work

I needed to do this to get it working on ubuntu too

**Comment by Jonny1987** [comment]
> The only way I managed to get this working on ubuntu is:
> 
> 1. Running this first to create a proxy socket:
> 
> ```
>    sudo socat UNIX-LISTEN:/var/run/docker.sock,fork,user=$USER,group=docker,mode=660 UNIX-CONNECT:$HOME/.docker/desktop/docker.sock
> ```
> 
> 2. Starting supabase using:
> 
> ```
> DOCKER_HOST=unix:///var/run/docker.sock supabase start
> ```
> 
> I tried setting DOCKER_HOST AND DOCKER_SOCKET_LOCATION to unix://$HOME/.docker/desktop/docker.sock but it didn't work

This workaround has stopped working for me now. I created a new issue (linked juts before this comment)
