### ISSUE TITLE
Supabase CLI: Logout Does Not Restrict Access to Previously Linked Projects

### ISSUE THREAD

**Issue by mmooccii** [supabase/cli#2594]
**Describe the bug**

After logging out from a Supabase CLI account and logging in with a different account, it is still possible to affect the projects linked by the previous account.

**To Reproduce**
1. Run `supabase login` with Account A.
2. Use `supabase link` to link a project.
3. Execute `supabase logout` to log out.
4. Run `supabase login` with Account B.
5. Try to perform operations on the project linked by Account A.
6. See the issue where operations on the project linked by Account A are still possible.

**Expected behavior**
When logging in with Account B after logging out from Account A, operations on projects linked by Account A should be restricted.

**System information**
- Version of OS: macOS Sonoma 14.5
- Version of CLI: 1.187.10
- Version of Node.js: v18.19.1
- Chip: Apple M2
- Model: MacBook Pro (Model Identifier: Mac14,7)
- Docker: 
  - Version: 4.30.0 (149282)
  - Engine: 26.1.1
  - Compose: v2.27.0-desktop.2
  - Credential Helper: v0.8.1
  - Kubernetes: v1.29.2

**Additional context**
If applicable, add any other context about the problem here.
- Browser: N/A
- Version of supabase-js: N/A

**Comment by avallete** [comment]
I will work on this.
