### ISSUE TITLE
Error evaluating "env(AUTH_GITHUB_CLIENT_ID)": environment variable AUTH_GITHUB_CLIENT_ID is unset.

### ISSUE THREAD

**Issue by AndaHendriksen** [supabase/cli#2599]
**Describe the bug**
When I run "npx supabase start" I get the error message:
`Error evaluating "env(AUTH_GITHUB_CLIENT_ID)": environment variable AUTH_GITHUB_CLIENT_ID is unset.`
`Try rerunning the command with --debug to troubleshoot the error.`

When I run "npx supabase start --debug" I get the same error:
`Error evaluating "env(AUTH_GITHUB_CLIENT_ID)": environment variable AUTH_GITHUB_CLIENT_ID is unset.`

I've followed [this doc](https://supabase.com/docs/guides/functions/secrets) to add the variables and when I run "npx supabase secrets list" as the doc suggests, I can see that AUTH_GITHUB_CLIENT_ID is there. And I have a local ".env" and ".env.local" file with the variable set.

What am I missing?

**Expected behavior**
I want to be able to run supabase in docker

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: c7835273637144bf897af2f1e3a21ba2
 - Version of OS: Windows 10
 - Version of CLI: v1.187.10
 - Version of Docker: v4.33.1
 - Versions of services:
         SERVICE IMAGE      │      LOCAL       │ LINKED
  ─────────────────────────┼──────────────────┼─────────
    supabase/postgres      │ 15.1.1.78        │ -
    supabase/gotrue        │ v2.151.0         │ -
    postgrest/postgrest    │ v12.2.0          │ -
    supabase/realtime      │ v2.29.15         │ -
    supabase/storage-api   │ v1.0.6           │ -
    supabase/edge-runtime  │ v1.55.0          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Comment by sweatybridge** [comment]
It's most likely due to wrong config.toml. Can you reinitialise with `supabase init --force`?

**Comment by HuriHuchi** [comment]
I am experiencing the same issue. Above solution isn't working either.

> It's most likely due to wrong config.toml. Can you reinitialise with `supabase init --force`?

**Comment by pedroaquinoo** [comment]
I tried moving around the env file, renaming, and the only thing that was working was `GO_TRUE_ENV=blablabla supabase start` on start, status, stop and everything.

However, that gets annoying pretty quickly. The correct solution and what I was doing wrong is my env file wasn't in the right place. 

The correct should be:

folder
— ./supabase
— env.local

**Comment by sweatybridge** [comment]
@pedroaquinoo could you give beta release a try? it could be related to a recent bug fix https://github.com/supabase/cli/issues/2772

```
npx supabase@beta start
```

Your local files look correct
```
.
├── supabase/config.toml
└── .env.local
```

Within `.env.local` you can set `AUTH_GITHUB_CLIENT_ID` or any other env declared in config.toml.

**Comment by BertVanHecke** [comment]
i have the same issue at the moment, and i understand that the files should be in a specific place. However i dont want the supabase folder at the root of my project. Please provide an option to specify the .env location.
