### ISSUE TITLE
Generate const array of possible enum values

### ISSUE THREAD

**Issue by gwax** [supabase/cli#2601]
**Is your feature request related to a problem? Please describe.**

I would like to have values matching possible enum values that are synchronized to the database schema for looping or use with zod and similar tools.

**Describe the solution you'd like**

for a schema:
```typescript
export type Database = {
  public: {
    Enums: {
      mytype: "value" | "other"
    }
  }
}
```

I would like to have generated values:
```typescript
export const DatabaseValues = {
  public: {
    Enums: {
      mytype: ["value", "other"],
    },
  },
} as const;
```

this would allow defining zod types to match like:

```typescript
const mySchema = z.object({
  mytype: z.enum(DatabaseValues.public.Enums.mytype),
});
```

**Describe alternatives you've considered**

- manually keeping values in sync with the database and hoping they don't fall out of sync
- writing custom type checkers to ensure that values match the schema

**Additional context**

**Comment by sweatybridge** [comment]
Sorry for the late reply on this. I believe we are currently generating typescript enums. Is it not sufficient to zod schema?
