### ISSUE TITLE
Failed to start supabase

### ISSUE THREAD

**Issue by caiquecastro** [supabase/cli#2617]
**Describe the bug**
Failed to start supabase local environment

**To Reproduce**
Run `npx supabase start`

**Expected behavior**
Should start the local environment with docker containers

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: c0d484e8f29b4af5933362d4ba55d27d
 - Version of OS: macOS Sonoma 14.5 (23F79)
 - Version of CLI: 1.190.0
 - Version of Docker: Docker version 27.1.1-rd, build cdc3063
 - Versions of services:
         SERVICE IMAGE      │      LOCAL       │ LINKED
  ─────────────────────────┼──────────────────┼─────────
    supabase/postgres      │ 15.1.0.122       │ -
    supabase/gotrue        │ v2.148.0         │ -
    postgrest/postgrest    │ v11.2.0          │ -
    supabase/realtime      │ v2.30.23         │ -
    supabase/storage-api   │ v1.0.10          │ -
    supabase/edge-runtime  │ v1.56.0          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

+ exec /app/bin/realtime eval '{:ok, _} = Application.ensure_all_started(:realtime)
{:ok, _} = Realtime.Tenants.health_check("realtime-dev")'
** (MatchError) no match of right hand side value: {:error, {:badrpc, {:error, {:erpc, :timeout}}}}
    (realtime 2.30.23) lib/realtime/tenants.ex:85: Realtime.Tenants.health_check/1
    nofile:2: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.2.3) erl_eval.erl:494: :erl_eval.expr/6
    (elixir 1.16.2) lib/code.ex:572: Code.validated_eval_string/3
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

**Comment by akhudek** [comment]
I am also experiencing this exact error. Even if I remove all the migrations and seed sql I get this error. I've tried stopping with `--no-backup` and that also doesn't help.

**Comment by erik-rt** [comment]
I'm running Sonoma 14.4.1 and was also erroring out when trying to run `supabase start`. I was seeing the following error:

```bash
The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "_supavisor" does not exist
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:756: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:564: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:433: Ecto.Migrator.run/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
```

In my case I was able to run `supabase stop --no-backup` followed by `supabase start` and now it seems to be working again.

**Comment by redtomato0129** [comment]
Hi
