### ISSUE TITLE
unable to see edge functions in local development studio + when doing supabase login it only goes to supabase url and not to self hosted version

### ISSUE THREAD

**Issue by SerjoA** [supabase/cli#2635]
i dont know if both of the above are bugs or issues but i cant find anything in the docs.
how do i login to my self hosted version?
how to see edge functions in local superbase studio or in self hosted studio ?

**Comment by TBG-FR** [comment]
Did you find a way to see them ?

**Comment by Abhishekpatel123** [comment]
Same any update on this
