### ISSUE TITLE
 An error occurs in the "user_metadata" column of the "objects" table while running `npx supabase db reset` command.

### ISSUE THREAD

**Issue by gopte100** [supabase/cli#2637]
**Describe the bug**
An error occurs in the "user_metadata" column of the "objects" table while running the npx supabase db reset --debug command.

**Screenshots**
![image](https://github.com/user-attachments/assets/84aa5b64-ab7d-47f3-81aa-af5890171f3e)

**System information**
 - Ticket ID: 0540a80ea6ba44faa7f10aa3c61b7af3
 - Version of OS: macOS 14.5(23F79)
 - Version of CLI: 1.190.0
 - Version of Docker: 4.14.0 (91374)
 - Versions of services:
         SERVICE IMAGE      │      LOCAL       │   LINKED
    supabase/postgres      │ 15.1.0.153       │ 15.1.0.153
    supabase/gotrue        │ v2.148.0         │ v2.158.1
    postgrest/postgrest    │ v12.0.1          │ v12.0.1
    supabase/realtime      │ v2.30.23         │ -
    supabase/storage-api   │ v0.48.4          │ v1.10.3
    supabase/edge-runtime  │ v1.56.0          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Comment by sweatybridge** [comment]
closing as there are suggested workarounds.
