### ISSUE TITLE
Deploying Supabase on a Domain using HTTPS

### ISSUE THREAD

**Issue by TannerGabriel** [supabase/cli#264]
# Feature request

## Is your feature request related to a problem? Please describe.

In some cases, it might be useful to deploy your Supabase instance on a custom domain using HTTPS instead of exposing it on a given port.

## Describe the solution you'd like

One solution I can think of right now would be to set environment variables for the Nginx proxy e.g. `VIRTUAL_HOST=$DOMAIN` and `LETSENCRYPT_HOST=$DOMAIN`. This will probably only affect the `supabase/studio` container.

### Steps to implement

1. Add environment variables support in [Go code](https://github.com/supabase/cli/blob/main/internal/start/start.go#L827)
2. Let the user configure the Docker network the containers are in (It needs to be the same network as the Nginx proxy container).

Any other solutions are also welcome.

**Comment by soedirgo** [comment]
I may be misunderstanding the feature request, but this is prob out of the scope of the CLI, which only supports local development workflows. For hosting/deploying your own Supabase instance, you can try the [self-hosting](https://supabase.com/docs/guides/hosting/overview) guide instead.

**Comment by TannerGabriel** [comment]
@soedirgo, I missed that the CLI is only meant for local development. I thought it was meant as a more automated alternative for the self-hosting guide.

Do you think that an HTTPS implementation is still useful? If not, feel free to close the issue.

**Comment by soedirgo** [comment]
Sorry about that, I'll keep that in mind and make it more prominent.

I haven't found a use-case for HTTPS for local dev, but if there is we can reopen this issue.

**Comment by Schniz** [comment]
@soedirgo the Slack OAuth requires a server listening in https, which is problematic for local development with Supabase.

**Comment by mlawlerau** [comment]
I think Apple OAuth requires a https url too.

**Comment by jchaselubitz** [comment]
Hello. Safari browsers also require this, so without being able to the local supabase server to https, it's not possible to use Ngrok to test the site locally on a phone or tablet

**Comment by Stokestack** [comment]
I'm surprised and disappointed to find that there's no way to use HTTPS and our own certificates for local dev. This is essential when you're writing a back end for a mobile application. I can't hit my Supabase project from my iPhone, because iOS (Apple) requires HTTPS.

I also read the self-hosting docs, and so far I haven't found any mention of where to put certificates there either.

**Comment by sweatybridge** [comment]
For future reference, you can enable TLS in config.toml and set callback URL to https://localhost:54321

https://github.com/supabase/cli/issues/1491#issuecomment-2278362547

**Comment by Stokestack** [comment]
Thanks. I have that option set in config.toml, but I'm not using a callback URL. Just doing regular queries under iOS using the Swift library.
