### ISSUE TITLE
Functions debugging broken

### ISSUE THREAD

**Issue by daniel-sc** [supabase/cli#2646]
**Describe the bug**
Using v1.191.3 the debugging of functions fails on Windows. See error below.
This is/was working with v1.191.0.

**To Reproduce**
1. run `npx supabase@latest functions serve --inspect-mode brk`
2. make a curl request
3. See error "thread '<unnamed>' panicked ..."

**Expected behavior**
It should not fail and debugging should be possible.

**Screenshots**
```bash
user@machine:/mnt/c/dev/projekte/auto-l10n$ RUST_BACKTRACE=1 npx supabase@latest functions serve --inspect-mode brk
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.56.1 (compatible with Deno v1.43.0)       
serving the request with /mnt/c/dev/projekte/auto-l10n/supabase/functions/translate-xlf2
Debugger listening on ws://0.0.0.0:8083/ws/ff2ed703-91a5-4e1c-85fc-4fe8bf6ecf96
Visit chrome://inspect to connect to the debugger.
Worker is waiting for debugger to connect.
thread '<unnamed>' panicked at /usr/local/cargo/git/checkouts/deno_core-1aa117f39acc86a9/6323369/core/inspector.rs:367:16:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to send request to user worker: request has been cancelled by supervisor
error in user worker connection: error writing a body to connection
user worker failed to respond: request has been cancelled by supervisor
WorkerRequestCancelled: request has been cancelled by supervisor
    at async Promise.allSettled (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:73:61)
    at async Object.handler (file:///root/index.ts:163:14)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "WorkerRequestCancelled"
```

**System information**
Rerun the failing command with `--create-ticket` flag.
=> This does give the same output as without the `--create-ticket` flag!

 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: Win10 (WSL) + Win11
 - Version of CLI: v1.191.3
 - Version of Docker: 27.0.3
 - Versions of services: 
         SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.113       │ 15.6.1.113
    supabase/gotrue        │ v2.158.1         │ v2.158.1
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.23         │ -
    supabase/storage-api   │ v1.10.3          │ v1.10.3
    supabase/edge-runtime  │ v1.56.1          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Additional context**
If applicable, add any other context about the problem here.
 - Browser n/a
 - Version of supabase-js n/a
 - Version of Node.js v18.20.4

**Comment by sweatybridge** [comment]
cc @nyannyacha as it seems related to the edge runtime upgrade to 1.56.1 https://github.com/supabase/cli/releases/tag/v1.191.1

**Comment by nyannyacha** [comment]
I'll take a look

**Comment by nyannyacha** [comment]
It doesn't look like the inspector is causing panic for all user scripts.

Hello @daniel-sc 😁
Can you provide some reproducible code?

**Comment by daniel-sc** [comment]
@nyannyacha the following function reproduces this:

```ts
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { XmlDocument } from "npm:xmldoc@~1.3.0";

Deno.serve(async (req) => {
  console.log("Request received");

  const doc = new XmlDocument("requestBody");

  return new Response("done");
});
```
