### ISSUE TITLE
Document .env file for config.toml

### ISSUE THREAD

**Issue by sweatybridge** [supabase/cli#2662]
**Link**
Add a link to the page which needs improvement (if relevant)

**Describe the problem**
Is the documentation missing? Or is it confusing? Why is it confusing?

**Describe the improvement**
A clear and concise description of the improvement.

**Additional context**
Add any other context or screenshots that help clarify your question.

**Comment by Xavier-IV** [comment]
I can agree this, although I don't think it's even implemented, except for supabase function (which is a separate topic).

https://supabase.com/docs/guides/cli/managing-config

This document causes more confusion. Following it I assume Supabase does detect .env, but its not. Have to export/set manually the env from terminal, and only then can run supabase start.

```bash
$ export MY_ENV=value
$ supabase start
```

I'm prone to update the docs as to not confuse others, but appreciate if others can share their thoughts on this.

**Comment by Xavier-IV** [comment]
> I can agree this, although I don't think it's even implemented, except for supabase function (which is a separate topic).
> 
> https://supabase.com/docs/guides/cli/managing-config
> 
> This document causes more confusion. Following it I assume Supabase does detect .env, but its not. Have to export/set manually the env from terminal, and only then can run supabase start.
> 
> ```shell
> $ export MY_ENV=value
> $ supabase start
> ```
> 
> I'm prone to update the docs as to not confuse others, but appreciate if others can share their thoughts on this.

Update, this does work, but proper placement of the .env matters.

Create a PR to update the docs:
https://github.com/supabase/supabase/pull/29225
