### ISSUE TITLE
`db test` fails on Bitbucket CI with cli release v1.200.3

### ISSUE THREAD

**Issue by etzelc** [supabase/cli#2703]
**Describe the bug**
PR https://github.com/supabase/cli/pull/2683 added `security-opt` flag to the run of pg_prove container. `security-opt` is not allowed on Bitbucket Cloud CI (see https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/#Full-list-of-restricted-commands). 

One idea to fix this issue: Special treatment for Bitbucket CI like here https://github.com/supabase/cli/blob/570158335c9dfdcaef5f455f5dc428ccd8fc779f/internal/utils/docker.go#L287

**To Reproduce**
1. Run pipeline with `supabase db tests` on Bitbucket Cloud

**Expected behavior**
Tests are executed.

**Error Log**
```
3.36: Pulling from supabase/pg_prove
...
failed to create docker container: Error response from daemon: authorization denied by plugin pipelines: --security-opt is not allowed
```

**Additional context**
 - Version of supabase-cli v1.200.3

**Comment by avallete** [comment]
Thank's for reporting, a fix in on it's way ! 👍

**Comment by etzelc** [comment]
Thanks for the super fast fix. The preview release [v1.201.1](https://github.com/supabase/cli/releases/tag/v1.201.1) is working as expected. 😃
