### ISSUE TITLE
Support logs locally

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#271]
# Feature request

It is currently very difficult to debug issues related to trigger functions. Adding logging locally could significally help with that. I've originally posted about it [here](https://github.com/supabase/supabase/discussions/7061).

**Comment by sweatybridge** [comment]
Hi @mr-bjerre , we are actively looking into exposing the logs explorer in studio. This will be solved together with [this feature request](https://github.com/supabase/supabase/issues/6674) for self-hosted supabase.

Meanwhile, if you want to tail the logs manually, they can be found inside the postgres container, timestamped by the hour.
```bash
$ docker exec -it supabase_db_supabase-dev ls -la /var/log/postgresql
total 228
drwxrwxr-t 1 root     postgres   4096 Sep  2 05:54 .
drwxr-xr-x 1 root     root       4096 Jan 27  2022 ..
-rw-r----- 1 postgres postgres 216553 Sep  2 05:55 server_0500_UTC.csv
-rw-r----- 1 postgres postgres    406 Sep  2 05:54 server_0500_UTC.log
```

**Comment by sweatybridge** [comment]
I will merge this issue with https://github.com/supabase/cli/issues/52. Feel free to reopen it if you think there's something lacking from the suggestion there.

**Comment by johannesjo** [comment]
My postgres log folder is always empty (also there is no logging configured in the postgres config when the container is freshly started).

**Comment by sweatybridge** [comment]
For future reference, postgres container logs can be viewed with `docker logs -f supabase_db_<project>` command or via docker desktop app.

![Screenshot 2023-08-02 at 6 44 41 PM](https://github.com/supabase/cli/assets/1639722/e1f2b8de-7204-43ef-bdc2-7f4421a3bee0)

**Comment by johannesjo** [comment]
@sweatybridge you sir are my personal hero for the day! Spent hours on this. This should definitely be mentioned in the [documentation](https://supabase.com/docs/guides/cli/local-development#enabling-local-logging)!

**Comment by RafaelCENG** [comment]
Hello, I'm using the docker desktop app and I'm inside the supabase_db_backend container. I have a trigger that I want to use to raise logs but I can't see any logs. I have an error that I'm trying to debug but cant log anything (developing locally)

**Comment by rngadam** [comment]
> Hello, I'm using the docker desktop app and I'm inside the supabase_db_backend container. I have a trigger that I want to use to raise logs but I can't see any logs. I have an error that I'm trying to debug but cant log anything (developing locally)

For future reference, this works:

a log line in the trigger:

```
    raise log 'log - check_debits_credits_balance called'; 
```

tracking the logs (swap bethune for your own project name):

```
$ docker logs -f supabase_db_bethune-prototype
```

outputs:

```
172.25.0.11 2024-04-25 15:12:46.993 UTC [2052] postgres@postgres LOG:  log - check_debits_credits_balance called
172.25.0.11 2024-04-25 15:12:46.993 UTC [2052] postgres@postgres CONTEXT:  PL/pgSQL function check_debits_credits_balance() line 5 at RAISE
172.25.0.11 2024-04-25 15:12:46.993 UTC [2052] postgres@postgres STATEMENT:  
	-- source: dashboard
	-- user: self host
	-- date: 2024-04-25T15:12:46.925Z
	
	insert into transactions(date, amount, journal_entry, account_id) values(
	  '2022-03-01',
	  100,
	  10,
	  (select id from accounts where name = 'Cash')
	);
```

**Comment by waynesbrain** [comment]
The easiest way I found was to use [portainer](https://www.portainer.io) to recreate the Supabase analytics container to add a mount to `/var/run/docker.sock`.

- Install/run portainer, open it, navigate to containers in local environment.
- Find the `supabase_analytics` container and click it.
- Click "Duplicate/Edit" in the top toolbar.
- Near the bottom of the next page find Volumes.
  - Add a new volume.
  - Switch the container input from `Volume` to `Bind` mount.
  - Enter `/var/run/docker.sock` for both `container` and `host`.
  - Click "Deploy the container" and say yes to replace the existing one.
