### ISSUE TITLE
`supabase migration fetch`: failed to scan targets

### ISSUE THREAD

**Issue by tvogel** [supabase/cli#2725]
**Description**
When running `supabase migration fetch`, I receive

```
> npx supabase --create-ticket migration fetch 
Do you want to overwrite existing files in supabase/migrations directory? [Y/n] 
Connecting to remote database...
failed to scan targets: can't scan into dest[2]: cannot scan null into *string
Try rerunning the command with --debug to troubleshoot the error.
Sent crash report: a27a49210b894a6bbd9753984d8bf8c6
```

**To Reproduce**
I am actually not sure - might depend on the specific project.

**Expected behavior**
The migration data should be downloaded from the linked project.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: a27a49210b894a6bbd9753984d8bf8c6
 - Version of OS: opensuse:tumbleweed:20240927
 - Version of CLI: 1.200.3
 - Version of Docker: 26.1.5-ce, build 411e817ddf71
 - Versions of services: 
        SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.127       │ 15.6.1.127
    supabase/gotrue        │ v2.162.1         │ v2.162.1
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.7          │ v1.11.7
    supabase/edge-runtime  │ v1.58.3          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Comment by sweatybridge** [comment]
Thanks for reporting this bug. It's actually caused by a null value in your migration history table. I will push a fix to handle this client side. Meanwhile, you can also repair the history table by reverting the bad entry

```
supabase migration repair 20230501231133 --status reverted
```

**Comment by tvogel** [comment]
Thank you for the explanation and the fix! 🪡
