### ISSUE TITLE
Release 1.202.4 and later break seed on reset - Windows

### ISSUE THREAD

**Issue by DuncanLHS** [supabase/cli#2734]
**Describe the bug**
Since Release 1.202.4, db reset no longer recognises my seed.sql file even though it exists in the expected location, supabase/seed.sql

**To Reproduce**
1. Update to supabase cli v1.202.4 or later

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/0043d2e5-6ebe-4e92-b109-31e7b784907b)

![image](https://github.com/user-attachments/assets/545a5303-ad5f-4468-a429-c89cae963d30)

**System information**
 - Version of OS: Windows 11
 - Version of CLI: v1.202.4 or later
 - Version of Docker: Docker Desktop v4.34.2
 - Versions of services:
 ```
         SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.127       │ 15.6.1.127
    supabase/gotrue        │ v2.162.1         │ v2.162.1
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.7          │ v1.11.7
    supabase/edge-runtime  │ v1.58.11         │ -
    supabase/studio        │ 20240923-2e3e90c │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Comment by sweatybridge** [comment]
This is due to a bug in path separator handling. Could you try the beta release?

```
npx supabase@beta db reset
```

**Comment by DuncanLHS** [comment]
@sweatybridge That's fixed it. Thanks.
```
$ npx supabase@beta db reset
Need to install the following packages:
supabase@1.204.3
Ok to proceed? (y) y

Resetting local database...
Recreating database...
Setting up initial schema...
Seeding globals from roles.sql...
Applying migration ....
Seeding data from supabase/seed.sql...
Restarting containers...
```

**Comment by DuncanLHS** [comment]
Still seeing this issue on db pull and push:
```bash
npx supabase db pull --local
No seed files matched pattern: supabase/seed.sql
No seed files matched pattern: supabase/seed.sql
```

Not sure why as I don't believe the seed is used in these commands.

**Comment by DuncanLHS** [comment]
@sweatybridge See the original bug at the top here. `db reset` was fixed i.e. the `No seed file matched pattern` warning no longer shows with the `db reset` command. It was an issue with reading the file system correctly on windows I believe. However, I'm still seeing the warning when using `db push` and `db pull`
