### ISSUE TITLE
Remove "Body exceeded 1mb limit" error

### ISSUE THREAD

**Issue by vbylen** [supabase/cli#274]
Hi there,

I'm trying to seed my local database with 1000 users and 1000 posts.

However I'm greeted with the following error:

`"Body exceeded 1mb limit"`

So postgres is complaining that the `seed.sql` file is too big.

I've tested inserting a smaller number of rows and it works fine.

Any ideas how I could get around this?

Thanks!

**Comment by eeston** [comment]
Hello,

I've currently toying around with a seed file that's around 3mb which is full of mostly JSON plus a few functions for inserting the data.

I'm running 1.8.2 and I'm getting the following error while trying to seed... `Error: bufio.Scanner: token too long`
I also tried to seed in the dashboard (local) but the limit there is 1mb. 

Would importing from a csv be the prefered method here?

**Comment by eeston** [comment]
Hello @sweatybridge,

I've currently toying around with a seed file that's around 3mb which is full of mostly JSON plus a few functions for inserting.

I'm running 1.8.2 and I'm getting the following error while trying to seed...
Error: bufio.Scanner: token too long.

I also tried to seed in the dashboard (local) but the limit there is still 1mb (Body exceeded 1mb limit).

Is there another way to seed large amounts of data?

**Comment by sweatybridge** [comment]
Hi @eeston , we have made the scanner buffer size configurable. You might need to play around with buffer sizes to fit your seed file. Perhaps 5mb could be a good start

```bash
SUPABASE_SCANNER_BUFFER_SIZE=5mb supabase db reset
```

> I'll need to do the same in my cloud instance of supabase too. I assume the 1mb will still be an issue on that dashboard?

Yes, the hosted dashboard has the same body size limit. We will look into extending the CLI to push your seed data to cloud instance using `supabase db push`. The related ticket is https://github.com/supabase/cli/issues/160

**Comment by eeston** [comment]
Fantastic...I'll test this at the weekend. Thanks for your help @sweatybridge

**Comment by eeston** [comment]
Hi @sweatybridge,

Just had a play around with this and unfortunately it still fails with the same error. Not a big deal locally but for the hosted dashboaed I think I'll end up splitting the data into multiple chunks. I assume the csv upload option is also limited to 1mb?

**Comment by sweatybridge** [comment]
> I assume the csv upload option is also limited to 1mb?

I just checked with our support team. The csv upload option does not impose such size limits. You should be able to upload 3mb of seed data using it.

**Comment by kiwicopple** [comment]
> Is there another way to seed large amounts of data?

The best way to seed a lot of data is through the COPY command:
https://www.postgresql.org/docs/current/sql-copy.html

It looks like you've go mostly JSON data - I have a small tutorial which could help with that:
https://paul.copplest.one/knowledge/tech/postgres-data.html

**Comment by eeston** [comment]
Thanks for the info @kiwicopple.

I ended up inserting the data in 5000row chunks...wasn't too much trouble. Good to know for next time though! 👍

**Comment by ricardosikic** [comment]
hi guys, i'm facing the same error i have installed version 1.42.7 (with brew today).

**Comment by sweatybridge** [comment]
@ricardosikic have you tried setting `SUPABASE_SCANNER_BUFFER_SIZE=5MB` or larger value before supabase start?

**Comment by ricardosikic** [comment]
Hi no, I just ran `supabase db remote commit` and then dumped it with `--data-only`. Where is that line located?

**Comment by sweatybridge** [comment]
It's a env var so you can do it like this

```
SUPABASE_SCANNER_BUFFER_SIZE=5MB supabase start
```

**Comment by ricardosikic** [comment]
Hi ✋, didn't work. I was thinking of trying to connect to my localhost instance with pgadmin and seed the tables with an csv file.

**Comment by sweatybridge** [comment]
What's the size of your seed.sql file? Could you also post the cli logs here?

**Comment by ricardosikic** [comment]
hi, 4kb. But the format is like

```
--
-- Data for Name: objects; Type: TABLE DATA; Schema: storage; Owner: supabase_storage_admin
--

COPY storage.objects (id, bucket_id, name, owner, created_at, updated_at, last_accessed_at, metadata) FROM stdin;
d2-86ba-5ec4dfe1891d	avatars	0.4968305670106038.jpg	ed385cb4-b74e-4587-9cf7-468aed9c10e8	2023-02-12 01:02:38.420795+00	2023-02-12 01:02:38.892079+00	2023-02-12 01:02:38.420795+00	{"eTag": "\\"700f2fc6bb91124e58b5ad51cff51449\\"", "size": 268015, "mimetype": "image/jpeg", "cacheControl": "max-age=3600", "lastModified": "2023-02-12T01:02:39.000Z", "contentLength": 268015, "httpStatusCode": 200}
4-48cf-9635-e934e5083988	logo-image	logo/.emptyFolderPlaceholder	\N	2023-02-25 19:34:24.734096+00	2023-02-25 19:34:24.82976+00	2023-02-25 19:34:24.734096+00	{"eTag": "\\"d41d8cd98f00b204e9800998ecf8427e\\"", "size": 0, "mimetype": "application/octet-stream", "cacheControl": "max-age=3600", "lastModified": "2023-02-25T19:34:25.000Z", "contentLength": 0, "httpStatusCode": 200}
```

**Comment by sweatybridge** [comment]
@ricardosikic I see, yup the error message is different from what's posted previously in this thread.

Also, is this from `db dump --data-only` or regular pg_dump? We are using [column inserts](https://github.com/supabase/cli/blob/main/internal/db/dump/templates/dump_data.sh#L10) so I'm surprised to see copy statements here.

**Comment by ricardosikic** [comment]
Hi, yes the with the command and your las advice my error `Error: bufio.Scanner: token too long.` disappeared. It was related with Bufio error. Thanks

**Comment by jadghadry** [comment]
Hi all, I feel like I'm missing something.

Any time I run `scoop install supabase` I only get v1.50.4 of the CLI (apparently the latest version, updated at 4/12/2023 4:39:38 PM). Also, I can't just run `SUPABASE_SCANNER_BUFFER_SIZE=5MB supabase start` on Windows PowerShell.

Can anyone give a bit more context please?

**Comment by sweatybridge** [comment]
Hi @jadghadry, you can set env vars on powershell like this

```powershell
$Env:SUPABASE_SCANNER_BUFFER_SIZE = '5mb'
supabase start
```

**Comment by brendanmc6** [comment]
Related new issue that has emerged -> https://github.com/supabase/cli/issues/1058

referencing here for anyone on Google who is now seeing this `SUPABASE_SCANNER_BUFFER_SIZE` error upon database start or reset :)

**Comment by myagizmaktav** [comment]
@sweatybridge Hello,  I use supabase, docker host which docker container should take this env?

**Comment by sweatybridge** [comment]
> which docker container should take this env?

This env is set on your host machine where supabase cli in installed. You don't need to set it inside any container.
