### ISSUE TITLE
No seed files matched pattern supabase\seed.sql

### ISSUE THREAD

**Issue by red2678** [supabase/cli#2747]
**Describe the bug**
After updating to 1.203.0 I can no longer seed my db with my seed file. 

**To Reproduce**
1. Update the cli to 1.203.0
2. Run one of the supabase commands that will seed the local db (db reset, start, stop, etc)
3. See the error in the terminal "No seed files matched pattern: supabase\seed.sql"

**Expected behavior**
It should use my seed file to seed the db.

**Screenshots**
![image](https://github.com/user-attachments/assets/751384e7-c79e-43b5-8607-f16bef1c48df) 
sss of the err

![image](https://github.com/user-attachments/assets/54e4011d-dbf7-40e2-b49e-e2e7384e1b95) 
but it's there!

**System information**
Rerun the failing command with `--create-ticket` flag. <-- this does nothing?
 - Ticket ID: NA
 - Version of OS: Windows 11 Home - 23H2
 - Version of CLI: 1.203.0
 - Version of Docker: Docker Desktop 4.34.2
 - Versions of services: 
 ```
 No seed files matched pattern: supabase\seed.sql

  
        SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.115       │ 15.6.1.115
    supabase/gotrue        │ v2.162.1         │ v2.162.1
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.7          │ v1.11.7
    supabase/edge-runtime  │ v1.58.11         │ -
    supabase/studio        │ 20240930-16f2b8e │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Additional context**
I tried setting in my config.toml too, but still no dice. 

```
[db.seed]
enabled = true
sql_paths = ['./seed.sql'] 
```

**Comment by avallete** [comment]
Hi @red2678,

Could you try using the latest beta release channel with the following command and let me know if it resolves your issue?

```bash
npx supabase@beta db restart
```

We've included a potential fix in the [v1.204.1 release](https://github.com/supabase/cli/releases/tag/v1.204.1).

**Comment by red2678** [comment]
Yes sir, that did work! To note, I'm sure you meant `reset`.

**Comment by red2678** [comment]
Closing as this has been resolved in v1.204.1

**Comment by brishan3** [comment]
I am currently experiencing the same issue as mentioned by @red2678 above .

I have had no issues seeding Locally up until today, and now I am continually getting the message: 

`No seed files matched pattern: supabase\seed.sql`

Despite having a `seed.sql` file within my projects `/supabase` directory that was generate via the CLI using my usual go to:

`supabase db dump -f supabase/seed.sql --data-only`

**What I have tried:**
- Updating Supabase CLI to latest using Scoop (I am now running v1.203.0), the issue persists
- Setting explicit seed paths in the config.toml, the issue persists
- And now after finding this thread I have tried using `npx supabase@beta db reset`, and the same issue persists

**System information**
I also tried creating a ticket using `--create-ticket` flag. To no avail.

    Ticket ID: NA
    Version of OS: Windows 10 Home - 22H2
    Version of CLI: 1.203.0
    Version of Docker: Docker Desktop 4.34.3

**Comment by avallete** [comment]
> I am currently experiencing the same issue as mentioned by @red2678 above .
> 
> I have had no issues seeding Locally up until today, and now I am continually getting the message: 
> 
> `No seed files matched pattern: supabase\seed.sql`
> 
> Despite having a `seed.sql` file within my projects `/supabase` directory that was generate via the CLI using my usual go to:
> 
> `supabase db dump -f supabase/seed.sql --data-only`
> 
> **What I have tried:**
> - Updating Supabase CLI to latest using Scoop (I am now running v1.203.0), the issue persists
> - Setting explicit seed path, e.g. `sql_paths = ['./seed.sql']` in the config.toml, the issue persists.
> - And now after finding this thread I have tried using `npx supabase@beta db reset`, and the same issue persists
> 
> **System information**
> I also tried creating a ticket using `--create-ticket` flag. To no avail.
> 
>     Ticket ID: NA
>     Version of OS: Windows 10 Home - 22H2
>     Version of CLI: 1.203.0
>     Version of Docker: Docker Desktop 4.34.3

Hey @brishan3,

We’ve just released CLI version 1.204.3, and I recommend upgrading to see if that resolves the issue.

If the problem continues, it would be really helpful to get more information about your project’s file structure. For example, are you working in a monorepo with multiple Supabase projects, or is there anything unique about your setup?

This will help us better understand and reproduce the issue on our end. Let us know how it goes!

**Comment by brishan3** [comment]
Thanks for your response, @avallete!

Moments ago I resolved my issue by updating the Supabase CLI.

I noticed that after I ran `npx supabase@beta db reset`, the message "A new version of Supabase CLI is available: v1.204.3 (currently installed v1.203.0)" was printed out.

My issue was resolved after running `npm update supabase -g`

**Comment by bcorman** [comment]
Quick note regarding the release: it's been about 6 hours since the release went out, so I see the "new release available" message in the CLI, but when I try to update with scoop it still thinks the newest version is 1.203.0:
![Screenshot 2024-10-09 102422](https://github.com/user-attachments/assets/a6c4b8ff-6e4e-4ff6-aa00-6988a6f83348)
![Screenshot 2024-10-09 102429](https://github.com/user-attachments/assets/a5e72ea0-beee-4b36-a721-05815b227c20)

Just flagging in case this delay isn't normal. Let me know if I should file a separate issue.

**Comment by bcorman** [comment]
To answer my own question, it looks like I just have to sit around and wait for Scoop's update bot to get around to it: https://github.com/ScoopInstaller/Main/commits?author=github-actions%5Bbot%5D
