### ISSUE TITLE
Cannot create new migrations after upgrading to `v.1.203.0`

### ISSUE THREAD

**Issue by jennyckaplan** [supabase/cli#2749]
**Describe the bug**
I use `npx supabase` when running the CLI to stay up to date with `latest`. Yesterday, after upgrading to `v.1.203.0`, I was no longer able to create a new migration (using `npx supabase db diff --use-migra -f <migration_name>`). After investigation and clearing out all my Docker containers, volumes, and images, I also tried resetting the database to the local migration files, and that command (`npx supabase db reset --local`) gave me the same error.

This morning, I upgraded to the newest version of the CLI (`v.1.204.3`) and the error went away.

Error (when running with the `--debug` flag):
```
2024/10/09 09:31:23 Recv First Byte
/app/dist/storage/backend/file.js:64
      throw new Error("FILE_STORAGE_BACKEND_PATH env variable not set");
      ^

Error: FILE_STORAGE_BACKEND_PATH env variable not set
    at new FileBackend (/app/dist/storage/backend/file.js:64:13)
    at createStorageBackend (/app/dist/storage/backend/index.js:35:22)
    at Object.<anonymous> (/app/dist/storage/events/base-event.js:36:64)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/dist/storage/events/webhook.js:34:25)

Node.js v20.18.0
2024/10/09 09:31:23 Sent Header: Host [api.moby.localhost]
```

**To Reproduce**
1. Use latest (`v.1.203.0`). 
2. Try to create a new migration based on changes to the local studio.
3. See error

**Expected behavior**
I am not self-hosting, so I do not expect to need to set this env variable.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: baf8ddbb82f44cd09073df541605a78d
 - Version of OS: macOS Sonoma Version 14.1.2 (Darwin 23.1.0)
 - Version of CLI: 1.230.0
 - Version of Docker: v.27.2.0
 - Versions of services:
```
        SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.1.0.153       │ 15.1.0.153
    supabase/gotrue        │ v2.162.1         │ v2.162.1
    postgrest/postgrest    │ v12.0.1          │ v12.0.1
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.13         │ v1.11.13
    supabase/edge-runtime  │ v1.58.11         │ -
    supabase/studio        │ 20240930-16f2b8e │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Additional context**
If applicable, add any other context about the problem here.
 - Browser N/A
 - Version of supabase-js v.2.39.2
 - Version of Node.js v20.18.0

**Comment by sweatybridge** [comment]
We have released a potential fix for this issue in the beta channel. Could you give it a try?

```
npx supabase@beta db diff
```

See also https://github.com/supabase/cli/issues/2738

**Comment by jennyckaplan** [comment]
> We have released a potential fix for this issue in the beta channel. Could you give it a try?
> 
> ```
> npx supabase@beta db diff
> ```
> 
> See also #2738

oh amazing, missed that ticket - all fixed in the newest version as mentioned, just wanted to make sure you were aware!
