### ISSUE TITLE
Bug: `supabase db remote commit` stuck if database contains additional schema

### ISSUE THREAD

**Issue by kaleabmelkie** [supabase/cli#276]
# Bug report

## Describe the bug

`supabase db remote commit` stuck at 0% progress if a new schema is added to the database.

## To Reproduce

1. Create a new project on app.supabase.io
2. Run the following SQL:
  ```sql
  CREATE SCHEMA my_schema
  ```
3. Create a new local project with `supabase init`
4. Run `supabase db remote set <REMOTE_URL>` -- grab the remote URL from your app.supabase.io dashboard
5. Run `supabase db remote commit`

Step 5 won't finish. It's stuck at 0% progress (and the label "Committing changes on remote database as a new migration..." is above it).

I've tried it numerous times with the same outcome.

And, if I remove the schema (or never created it in a fresh setup) it will complete the operation in a few minutes.

## Expected behavior

`supabase db remote commit` should finish generating the migrations.

## Screenshots

<img width="704" alt="Screen Shot 2022-06-07 at 4 34 02 PM" src="https://user-images.githubusercontent.com/29814842/172393451-cf1d4fdd-0a22-4534-b80d-ad0ba6770257.png">

## System information

- OS: macOS 12.4 (M1 Pro)
- Version of supabase-cli: 0.26.1
- Version of Node.js: 16.15.1

**Comment by sweatybridge** [comment]
Hi @kaleabmelkie , appreciate your patience in waiting for us to get this issue sorted. With cli v1, we added better support for doing the initial dump with `db remote commit`. More information here https://supabase.com/docs/guides/cli/cicd-workflow#setting-up-a-project

Please give it a try and see if it works. Feel free to reopen this ticket if your issue persists.

**Comment by chitalian** [comment]
@sweatybridge I am running into the same issue - are there any logs that I can provide here?

I have the exact same setup except my supabase cli version is 1.4.1

**Comment by malerba118** [comment]
my processes are also stuck at the same point when i run `supabase db remote changes` and `supabase db remote commit`

**Comment by sweatybridge** [comment]
Hi, we have added migra support in the latest version for diffing linked project. It seems less prone to hanging than the default diff tool. You may use the following command in place of remote changes:

```
db diff --use-migra --linked --schema public,private
```

Any newly created schemas need to be declared explicitly via the `--schema` flag.

**Comment by abhay187** [comment]
> db diff --use-migra --linked --schema public,private



> Hi, we have added migra support in the latest version for diffing linked project. It seems less prone to hanging than the default diff tool. You may use the following command in place of remote changes:
> 
> ```
> db diff --use-migra --linked --schema public,private
> ```
> 
> Any newly created schemas need to be declared explicitly via the `--schema` flag.

@sweatybridge can you elaborate more. If I have table in my remote project supabase db remote commit fails

**Comment by sweatybridge** [comment]
> If I have table in my remote project supabase db remote commit fails

May I know what's the error message when it fails? It may be fixable by clearing the migration history table on your hosted project.

![Screenshot 2022-10-27 at 5 22 19 PM](https://user-images.githubusercontent.com/1639722/198246289-0f25a5b2-db32-47b4-a986-0d19d2cb59a8.png)
