### ISSUE TITLE
Supabase start is not pulling in variables from env.local after update

### ISSUE THREAD

**Issue by dexsnake** [supabase/cli#2772]
**Describe the bug**
In my .env.local file I have two variables that overwrite the default values:

SUPABASE_AUTH_JWT_SECRET
SUPABASE_DB_ROOT_KEY

After a recent cli update, the variables are no longer being loaded in after a supabase start. 

When it finishes, I get the default:
JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
in the terminal.

And when I check the pgsodium_root.key file in docker, the value does not match. I'm using a custom one that matches my production project so I can access vault secrets locally.

**To Reproduce**
1. Add SUPABASE_AUTH_JWT_SECRET=<Some Value> to .env.local
2. run supabase start (from fresh)
3. When finished, the terminal will output JWT secret: super-secret-jwt-token-with-at-least-32-characters-long instead of the provided value in the .env.local file

**Expected behavior**
When a value is set for SUPABASE_AUTH_JWT_SECRET in .env.local, it should use that value as the jwt secret instead of the default.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Version of OS: MacOS 14.4.1
 - Version of CLI: 1.204.3
 - Version of Docker: 25.0.3

**Comment by avallete** [comment]
Hi @dexsnake and thank's for reporting.

Do you by any chance have the version of the cli in which it was working as intended ? This will help us track down when the issue was introduced.

**Comment by dexsnake** [comment]
> Hi @dexsnake and thank's for reporting.
> 
> Do you by any chance have the version of the cli in which it was working as intended ? This will help us track down when the issue was introduced.

I don't recall unfortunately. I do update the cli pretty regularly, so it wouldnt have been that far back. I wanna say maybe 198.x.x
