### ISSUE TITLE
Allow login method be use in CI/CD

### ISSUE THREAD

**Issue by riderx** [supabase/cli#279]
I have added in my CI the upload of my edge function and for that, I need to login and set the project-ref.
I cannot use the login method to login, so I had to send the token directly into the file `~/.supabase/access-token`

## Describe the solution you'd like

Can we have `supabase login -t XXX` to set directly the token?
instead of user input after the command, for now, the user input prevents us to easily login in CI

## Describe alternatives you've considered

Continue to send the token in the file

**Comment by soedirgo** [comment]
Hey there, sorry for the late response. You don't need to run `supabase login` in CI - you can simply set a `SUPABASE_ACCESS_TOKEN` env var when running `supabase` commands.

If that doesn't work, feel free to reopen!

**Comment by riderx** [comment]
Thanks a lot! i was close, i used `SUPABASE_TOKEN` ^^.
For the project i still need to init or same, i can set an env for `projectRef` ?

**Comment by soedirgo** [comment]
You can probably set `SOME_ENV` and then do `--project-ref $SOME_ENV`, but I might consider supporting that env var in  the future.
