### ISSUE TITLE
Feature Request: Don't name containers in docker-compose.yml or assign them random names prefixed with supabase

### ISSUE THREAD

**Issue by ff6347** [supabase/cli#28]
# Feature request

## the problem

Naming containers in docker-compose makes it impossible to have two supabase projects side by side

While exploring supabase locally I had the problem that I needed to spin up another supabase setup to verify if I messed up my current setup. Due to the setting the `container_name` in `docker-compose.yml` it is not possible to spin up another instance without getting an error that this name is already in use.

It is nice to have a defined container name, but I don't see any benefit except for easier identification when running `docker ps` or `docker container ls`.

## the solution

Maybe the cli can create a random name and prefix it with `supabase-`.

## the alternative

The only alternative here is ejecting the project or editing the files in `.supabase/` manually

**Comment by kiwicopple** [comment]
> Maybe the cli can create a random name and prefix it with supabase

I like this solution 👍 great idea @ff6347

**Comment by soedirgo** [comment]
The containers are now named `supabase_<component>_<projectId>`, where `projectId` can be customized in the config.

**Comment by andrybicio** [comment]
Is it still a thing in self hosting tho? And how to add the project id? Is it the `name` key in the docker-compose? I tried changing it but the container names are still named supabase-$service.
Will the internal DNS among services solve correctly?

**Comment by andrybicio** [comment]
As I expected, if I spawn two different self hosted docker compose, they do not work side by side for the container_name is equal.
However, in `volumes/logs/vector.yml` things are referenced by container name
