### ISSUE TITLE
Update the NPM module documentation to avoid install conflicts

### ISSUE THREAD

**Issue by darren-toha** [supabase/cli#281]
# Improve documentation

## Link 

[NPM Subabase CLI](https://www.npmjs.com/package/supabase)

## Describe the problem

We're using the Supabase cli in our project and have had the following issue:

The npm package has been installed globally as per the current instructions on the npm module page at the link above.

Later, the instructions at the [Supabase Github Repo](https://github.com/supabase/cli) have been followed to install the cli.

This results in two versions of the cli being present on a user's system. In this particular case a Windows OS.

When running `supabase start` the npm version (0.5.0) is run, and not the most recent version (0.26.1 as of this request), causing issues.

## Describe the improvement

Would it be possible to mark the npm package as deprecated, remove the `npm install supabase -g` install text, and point the user directly to Github to follow the correct install procedure there? Thanks

**Comment by sweatybridge** [comment]
related #127

**Comment by soedirgo** [comment]
We've updated the npm package to install the Go version, so both installation instructions should result in the same CLI being installed.

**Comment by sweatybridge** [comment]
Hi @darren-toha , I just realised we haven't updated the documentation for how to install from npm. So in case you want to try it out early, our recommendation is to install supabase **locally** to avoid path conflicts with system package managers. For example:

```bash
npm install supabase
npx supabase -h
```

This also helps keep Supabase CLI versioned in your project's `package.json`.
