### ISSUE TITLE
Supabase Destroy Needed

### ISSUE THREAD

**Issue by Crisfole** [supabase/cli#2822]
**Describe the bug**

My coworker just bumped into an issue with his local supabase volumes getting corrupted somehow. In order to solve this we had to stop supabase, manually tear down the docker volumes, and restart to get things working again.

There was no easy way to `supabase stop --rm` (like a `docker compose down --rm`). A destructive option for `supabase stop` would be valuable in these instances.

**To Reproduce**

1. Deliberately screw up your docker volumes (Exercise left for the reader)
2. supabase start (get error).
3. manually destroy the supabase volumes.

**Expected behavior**

3. Should be able to `supabase stop --rm` or similar.

**Screenshots**

N/A

**System information**

Irrelevant

**Additional context**

N/A

**Comment by avallete** [comment]
Hi,

It seems like what you're looking for is the `--no-backup` option detailed here:

https://supabase.com/docs/reference/cli/supabase-start

**Comment by Crisfole** [comment]
Thank you, you're right!
