### ISSUE TITLE
TypeScript type generation for custom schema

### ISSUE THREAD

**Issue by dbhathena** [supabase/cli#2823]
**Describe the bug**
When using a custom schema that I have successfully exposed to the data API, the `gen types typescript` script generates a file that still defaults to "public" for the `Tables<'row'>` shorthand.

**To Reproduce**
1. Create custom schema and expose it to the data API following instructions [here](https://supabase.com/docs/guides/api/using-custom-schemas)
2. In JS client, run `npx --yes supabase gen types typescript --project-id "<ID>" --schema custom_schema > ./path/to/db/index.ts`
3. Observe the line `type PublicSchema = Database[Extract<keyof Database, 'public'>];`

**Expected behavior**
Line `type PublicSchema = Database[Extract<keyof Database, 'public'>];` should be `type PublicSchema = Database[Extract<keyof Database, 'custom_schema'>];`

**Screenshots**
N/A

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Version of CLI: 1.207.9
 - Versions of services: 
![Screenshot 2024-11-01 at 11 42 09 AM](https://github.com/user-attachments/assets/7527045b-b5cd-455c-b684-b0fa44eb985d)

**Additional context**
If applicable, add any other context about the problem here.
N/A

**Comment by sweatybridge** [comment]
The shorthand will always default to `public` schema. You will have to pass in the schema name to the generic type to use the custom schema.

**Comment by dbhathena** [comment]
What is the reasoning for this? It makes sense to default to the `public` schema, but if the `custom_schema` argument is specified, shouldn't the generated file be consistent with that?

I'm satisfied with the answer, I can just make my own shorthand file, but this decision makes the shorthand completely useless, since the generated file won't have the `public` schema, in it, but the shorthand refers to it anyways.
