### ISSUE TITLE
V 1.215 local storage buckets 

### ISSUE THREAD

**Issue by ganjiefong** [supabase/cli#2841]
Newest supabase cli Version 1.215 have a bug on storage buckets that make it unusable.

Error:
API error happened while trying to communicate with the server.

Solution for now:
I reset my entire window 11, which doesn't work. All u need to do is downgrade the supabase cli Version.

**Comment by Wizzel1** [comment]
Same happens for me

**Comment by sweatybridge** [comment]
This should be fixed in the latest release.
