### ISSUE TITLE
Cannot recover from forcibly stopping supabase's containers

### ISSUE THREAD

**Issue by chaseWilliams** [supabase/cli#2842]
**Describe the bug**
supabase thinks its running but it is not

**To Reproduce**
Start supabase, then forcibly `docker rm -f < container name >` all of the containers.

**Expected behavior**
`supabase start` will restart the containers, and `supabase status` reports all services as down.

**Screenshots**
My supabase status:
```
Stopped services: [supabase_kong_supabase supabase_auth_supabase supabase_inbucket_supabase supabase_realtime_supabase supabase_rest_supabase supabase_storage_supabase supabase_imgproxy_supabase supabase_pg_meta_supabase supabase_studio_supabase supabase_edge_runtime_supabase supabase_analytics_supabase supabase_vector_supabase supabase_pooler_supabase]
supabase local development setup is running.

          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
```
supabase start:
```
supabase start is already running.
Run supabase status to show status of local Supabase containers.
```
supabase stop:
```
Stopped supabase local development setup.
```

No process is listening on the port supabase is reporting that the db is live at.

**System information**
 - Version of OS: macos 14.6.1
 - Version of CLI: v1.215.0
 - Version of Docker: 4.26.1
supabase services:
```
       SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.127       │ 15.6.1.127
    supabase/gotrue        │ v2.163.2         │ v2.163.2
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.14         │ v1.11.14
    supabase/edge-runtime  │ v1.60.1          │ -
    supabase/studio        │ 20241029-46e1e40 │ -
    supabase/postgres-meta │ v0.84.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Comment by chaseWilliams** [comment]
I've also removed the volumes, so both `docker ps` and `docker volume ls` no longer show any supabase stuff

**Comment by avallete** [comment]
That's probably because `docker-compose` has his own context, with restart policy and so on.

If you want to stop all your containers and volume using `npx supabase stop --all --no-backup` should cleanup everything running under "supabase" context.

**Comment by chaseWilliams** [comment]
@avallete just tried that and its still stuck. Obviously this isn't how I would typically shut down supabase, but after a computer restart the stack was unhealthy and nothing other than a `docker -f` was stopping the containers

**Comment by chaseWilliams** [comment]
Ok looks like my db container is somehow zombified as far as I can tell. `docker stats` shows 
```
CONTAINER ID   NAME                   CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
afc63d6cf6e3   supabase_db_supabase   0.00%     0B / 0B             0.00%     0B / 0B   0B / 0B     0
```
and `docker top` shows
```
Error response from daemon: container afc63d6cf6e384aa68418cce700df0aa1ce6e15c335cce97479b5528e6141a12 is in Running state but has no containerd Task set
```
I was looking in the souce code, and maybe its worth having `AssertSupabaseDbIsRunning` trying connecting to the db or something? I was having other errors as well, so I ended up just changing the project id which is working fine

**Comment by sweatybridge** [comment]
Can you check your docker settings if you are using docker engine instead of containerd?

There seems to be a known problem with zombie process using containerd https://github.com/docker/for-linux/issues/779#issuecomment-1876696587

Glad that you found a workaround though.
