### ISSUE TITLE
Error connecting to API Error: API error happened while trying to communicate with the server.

### ISSUE THREAD

**Issue by atilladeniz** [supabase/cli#2844]
**Describe the bug**
After supabase start when I go to API Docs it shows Building Docs.. and then Error connecting to API
Error: API error happened while trying to communicate with the server.

**Screenshots**
![Google Chrome 2024-11-06 22 49 21](https://github.com/user-attachments/assets/ba31caf5-78c1-42e1-9add-68539292b12d)

**System information**
 - Version of OS: MacOs
 - Version of CLI: 1.215.0
 - Version of Docker: Orbstack

**Comment by sweatybridge** [comment]
This has been fixed in latest CLI release.

**Comment by nqhuy-2x** [comment]
After supabase start when I go to API Docs it shows Building Docs.. and then Error connecting to API
Error: API error happened while trying to communicate with the server.

OS: Amalinux9 
Docker version 27.5.0
Docker compose: 
Docker Compose version v2.32.3

![Image](https://github.com/user-attachments/assets/24caf4b6-b8d0-484d-b202-5b2e033595fb)

**Comment by 2u841r** [comment]
its happening for me, when I trying enable Google auth provider in **Supabase helf hosted on Coolify**. or try to Disable Phone Login. 

mydomain.tld/project/default/auth/providers

**Comment by niallam22** [comment]
I have just created a supabase db with coolify and I am getting the error when creating a new table.

**Comment by Fauzdar1** [comment]
It happens whenever I make any changes in the self-deployed Supabase's panel, be it a column name change, add column, edit table etc.

**Comment by eddylackmann** [comment]
Any Solution? I have the same problem

**Comment by Fauzdar1** [comment]
> Any Solution? I have the same problem

What worked for me was a fresh reinstall of Supabase. Redoing everything isn't a solution, though.

**Comment by aenikata** [comment]
I had a similar issue and managed to resolve the issue. The first problem was setting the public URLs, and the second was having changed the JWT then using the form on the self-hosting page to generate updated keys to have in the env file.  Either being wrong means it's either pointing to the wrong place to handle auth or it's using an invalid key. If you follow (and understand) the self-hosting instructions FULLY, then it should work.
