### ISSUE TITLE
PLV8 breaks with some recent postgres versions

### ISSUE THREAD

**Issue by lauri865** [supabase/cli#2884]
**Describe the bug**
Updated project link: postgres updated to `15.6.1.127` locally

Getting errors on every plv8 function:
```
PostgresError: could not access file "$libdir/plv8-3.1.5": No such file or directory
```

Downgraded to: 15.6.1.120

Everything works again.

Any idea what we could do to solve this?
We also tried v[15.6.1.139](https://github.com/supabase/postgres/releases/tag/15.6.1.139), but it didn't work either.

**Comment by sweatybridge** [comment]
Hi @lauri865, there is indeed a version bump for plv8 on the platform side since 15.6.1.120. You can update your local setup by running `supabase stop --no-backup` before `supabase start`. Hope it helps.

**Comment by sweatybridge** [comment]
Yup agree that checking the versions into git would be nice going forward https://github.com/supabase/cli/issues/2435

We will probably add a flag other commands to specify different remotes. That would reduce the reliance on repeatedly running supabase link to activate different projects.

**Comment by lauri865** [comment]
Great!

Seems like Supabase cloud prevents upgrade when plv8 version changes, which is great. But it only says to disable plv8 in order to upgrade the postgres version, without offering any other instructions or why this needs to be done – confusing.

It can make for a very difficult upgrade path, if there's a deep dependency tree on plv8. Do we need to recreate the whole database was my first instinct?! In that case, we're gonna be stuck on this version for a while, because that's a pain to do manually.

I still think minor version upgrades of plv8 could be handled better, as they don't ship any breaking updates, but tearing down and rebuilding the database is a lot of work.

Luckily, I found  a simpler workaround for the time being
1. Replace all plv8 functions with temporary plpsql functions, e.g.:
```sql
CREATE OR REPLACE FUNCTION has_access()
RETURNS BOOLEAN
IMMUTABLE
AS $$
BEGIN
    RAISE EXCEPTION 'database maintenance in progress';
    RETURN false;
END
$$ LANGUAGE plpgsql;
```
2. Then you can run `DROP EXTENSION plv8;`, without having any cascading effects
3. Upgrade infra
4. `CREATE EXTENSION plv8;`
5. Replace temporary plpgsql functions back to original plv8 functions, and you're all set.

No need to mess with tearing down the whole database in our case – a few minutes work instead of hours of pain that we'd rather not take on. In our case, we only have 2 plv8 functions, but every RLS rule depends on them, and some views. So, cascading effects are very real.

**Comment by lauri865** [comment]
@pcnc – does the below PR fix the above issue in the future?
https://github.com/supabase/postgres/pull/1259

If so, I think there's more documentation / information needed to share with developer, as many of your customers may be stuck on older versions because of the cumbersome upgrade path.
