### ISSUE TITLE
"supabase projects create" no longer returns new project's id

### ISSUE THREAD

**Issue by salmoro** [supabase/cli#2886]
**Describe the bug**
Up until version  1.191.3, when creating a new project via `supabase projects create` the stdout would be a string that includes in it the new project id. Recent versions of the CLI do not return anything when creating a new project.
This is a blocker for us to upgrade our Supabse cli version in CI as we create new preview Supabase projects and need to know the project ids of those new projects.

**To Reproduce**
`supabase projects create`

**Expected behavior**
Return a string which includes the specific project-id of the new project

**System information**
 - Version of OS: Ubuntu 24.04, macOS 15.1
 - Version of CLI: 1.219.2

**Comment by sweatybridge** [comment]
Since 1.191.3, we've introduced structured output formats to make parsing easier for other tools that integrate with supabase cli. For example, to print the new project id as json

```
supabase projects create my_preview --output json
```
