### ISSUE TITLE
Local Supabase db reset fails with ERROR: database "_supabase" is used by an active logical replication slot (SQLSTATE 55006)

### ISSUE THREAD

**Issue by hjaarnio** [supabase/cli#2903]
**Describe the bug**
After running `supabase start` to bring a project online from migrations, running `supabase db reset` doesn't work because there is an active logical replication slot, which apparently prevents the database from being destroyed.
```
ERROR: database "_supabase" is used by an active logical replication slot (SQLSTATE 55006)
At statement 2: DROP DATABASE IF EXISTS _supabase WITH (FORCE) 
```
This happens on a blank project without migrations etc.
This seems to happen only when postgres major version is set to 14, not when it's set to 15

**To Reproduce**
1. supabase start
3. supabase db reset

**Expected behavior**

**Screenshots**
N/A

**System information**
 - Ticket ID: 909d7d251ecf440298fed44466079659
 - Version of OS: macOS Sonoma 14.1.2 (23B92)
 - Version of CLI: 1.223.10
 - Version of Docker: Docker version 24.0.6, build ed223bc

**Comment by avallete** [comment]
Thank's for reporting !

I've been able to reproduce on my end and I'm working on a fix for this 👍
