### ISSUE TITLE
Github checks never stop and migrations are not applied

### ISSUE THREAD

**Issue by muezz** [supabase/cli#2920]
**Describe the bug**
Unlike before, when I push changes in the `./supabase` folder, migrations are not being detected and applied to the preview branch in Supabase. In fact, in Github, the checks have been running non-stop for the past 40 mins. There are no logs in those checks so I have no way of knowing what is wrong.

**To Reproduce**
1. Run the diff command to create a migration file locally.
2. Push changes to github
3. Wait
4. Keep waiting

**Expected behavior**
This was working just fine yesterday. Changes get pushed, Supabase<->Github integration detects it and applies them to the preview branch.

**Screenshots**
<img width="600" alt="image" src="https://github.com/user-attachments/assets/6d029ab2-773d-4d25-80ca-d5b12ccd41bb">

**System information**
There is no command to run so I cannot run `--create-ticket`.
 - Version of OS: macOS 15.1.1 (24B91)
 - Version of CLI: v1.223.10
 - Version of Docker: v26.1.4, build 5650f9b
 - Versions of services: 
      SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.1.0.103       │ 15.1.0.103
    supabase/gotrue        │ v2.158.1         │ v2.163.2
    postgrest/postgrest    │ v11.1.0          │ v11.1.0
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.0          │ v1.13.0
    supabase/edge-runtime  │ v1.62.2          │ -
    supabase/studio        │ 20241106-f29003e │ -
    supabase/postgres-meta │ v0.84.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Comment by sweatybridge** [comment]
Are there any logs on supabase dashboard for your branch? https://supabase.green/dashboard/project/_/branches

**Comment by muezz** [comment]
@sweatybridge There is no indication of a push in the Supabase dashboard. The last log is from yesterday's push. I think the GitHub check needs to pass for Supabase to trigger the application of the migrations.

**Comment by sweatybridge** [comment]
Have you opened a support ticket yet? there could be an issue with your project / github connection.

**Comment by muezz** [comment]
@sweatybridge i have not opened a ticket yet. I will do that now.

**Comment by amirnksb** [comment]
Hey Having same issue, were you able to fix it

**Comment by muezz** [comment]
@amirnksb Unfortunately it has been too long and I do not remember what I did exactly to get it fixed. My suspicion is that I had to define the project ref ID in the `config.toml` file.
