### ISSUE TITLE
I cant get Supababase CLI to run on my mac mac

### ISSUE THREAD

**Issue by TheLegendAli** [supabase/cli#2935]
when I run

`supabase start`

I get the following error:

`failed to connect to postgres: failed to connect to `host=127.0.0.1 user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)`

here is the full trace:

`supabase start
WARN: no seed files matched pattern: supabase/seed.sql
Stopping containers...
failed to connect to postgres: failed to connect to `host=127.0.0.1 user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)
Try rerunning the command with --debug to troubleshoot the error.`

**Comment by avallete** [comment]
Hi there !

It look like the database cannot be reached for some reason. Did you try stoping all other possibly running containers with `supabase stop --all --no-backup` ?

Could you provide the debugs logs so we can see where the connexion is failing exactly ?

**Comment by avallete** [comment]
Hi there! Since we haven’t received any updates, we’ll go ahead and close this issue for now. Please feel free to reopen it anytime if you have more details to share. Thanks for understanding!
