### ISSUE TITLE
Are env variables loaded for all config.toml configurations?

### ISSUE THREAD

**Issue by xGerTowelie** [supabase/cli#2957]
**Describe the bug**
I have problems using the `env()` manipulation for the `site_url` in the `[auth]` section of the `config.toml`. For other configurations like the `[auth.external.keycloak]` `secret` its working.

**To Reproduce**
1. set site_url hardcoded:
```toml
[auth]
enabled = true
site_url = "http://whatever:3000"
```
2. Login with keycloak
3. After login I get redirected to `http://whatever:3000`
4. Restart supabase
5. set site_url to load from `.env` to any other env variable. (which is used in keycloak config already)
```toml
[auth]
enabled = true
site_url = "env(SUPABASE_AUTH_CALLBACK_ENDPOINT)"
```
6. Login again with keycloak
7. After login I get redirected to `http://localhost:3000` (and not to the env which was  `SUPABASE_AUTH_CALLBACK_ENDPOINT="http://spaddevmarcel:54321/auth/v1/callback"`)

**Expected behavior**
I expected the env to load, but it seems that it uses the default value instead.

**System information**
 - Ticket ID: none
 - Version of OS: [e.g. Ubuntu 22.04]
 - Version of CLI: [e.g. v2.0.0]
 - Version of Docker: [e.g. v27.3.1]
 - Versions of services: (docker images, `npx supabase services` doesn't work locally)
 ```
 CONTAINER ID   IMAGE                                             COMMAND                   CREATED          STATUS                    PORTS                                                                                                                                         NAMES
96b98af09b59   public.ecr.aws/supabase/studio:20241202-71e5240   "docker-entrypoint.s…"    27 minutes ago   Up 27 minutes (healthy)   0.0.0.0:54323->3000/tcp, [::]:54323->3000/tcp                                                                                                 supabase_studio_spesen
508f7604bae8   public.ecr.aws/supabase/postgres-meta:v0.84.2     "docker-entrypoint.s…"    27 minutes ago   Up 27 minutes (healthy)   8080/tcp                                                                                                                                      supabase_pg_meta_spesen
25740c2df9dc   public.ecr.aws/supabase/edge-runtime:v1.65.3      "sh -c 'cat <<'EOF' …"    27 minutes ago   Up 27 minutes             8081/tcp                                                                                                                                      supabase_edge_runtime_spesen
44c6aef24f0c   public.ecr.aws/supabase/imgproxy:v3.8.0           "imgproxy"                27 minutes ago   Up 27 minutes (healthy)   8080/tcp                                                                                                                                      supabase_imgproxy_spesen
21793f4699bc   public.ecr.aws/supabase/storage-api:v1.11.13      "docker-entrypoint.s…"    27 minutes ago   Up 27 minutes (healthy)   5000/tcp                                                                                                                                      supabase_storage_spesen
eb3bbafd305b   public.ecr.aws/supabase/postgrest:v12.2.0         "/bin/postgrest"          27 minutes ago   Up 27 minutes             3000/tcp                                                                                                                                      supabase_rest_spesen
76cae484bb67   public.ecr.aws/supabase/inbucket:3.0.3            "/start-inbucket.sh …"    27 minutes ago   Up 27 minutes (healthy)   0.0.0.0:54326->1100/tcp, [::]:54326->1100/tcp, 0.0.0.0:54325->2500/tcp, [::]:54325->2500/tcp, 0.0.0.0:54324->9000/tcp, [::]:54324->9000/tcp   supabase_inbucket_spesen
4ec90d4184cb   public.ecr.aws/supabase/gotrue:v2.164.0           "auth"                    27 minutes ago   Up 27 minutes (healthy)   9999/tcp                                                                                                                                      supabase_auth_spesen
6b1f64581be0   public.ecr.aws/supabase/kong:2.8.1                "sh -c 'cat <<'EOF' …"    27 minutes ago   Up 27 minutes (healthy)   8001/tcp, 8088/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp, [::]:54321->8000/tcp                                                              supabase_kong_spesen
9d2059a30e21   public.ecr.aws/supabase/postgres:15.6.1.139       "sh -c '\ncat <<'EOF'…"   28 minutes ago   Up 28 minutes (healthy)   0.0.0.0:54322->5432/tcp, [::]:54322->5432/tcp                                                                                                 supabase_db_spesen
```

**Additional Infos**
1. I'm using supabase locally
2. This is my first issue here. I hope my problem is clear and appropriate.

Kind Regards,
Towelie

**Comment by xGerTowelie** [comment]
### GOT IT WORKING! (It wasn't a Supabase issue at all)

I wanted to share what happened in case it helps others encountering a similar problem.

---

#### What went wrong:  

I mistakenly appended an "s" to the hostname in my `.env` file:  

```
SUPABASE_AUTH_SITE_URL="http://spaddevmarcels:3000"
```

This was referenced in my `config.toml` as follows:  

```toml
site_url = "env(SUPABASE_AUTH_SITE_URL)"
```

As a result, the `docker gotrue` container displayed:  

```
GOTRUE_SITE_URL: http://spaddevmarcels:3000
```

With this configuration, I got forwarded to an incorrect URL:  

```
http://spaddevmarcels:3000/....  
```

When I corrected the hostname by removing the extra "s":  

```
SUPABASE_AUTH_SITE_URL="http://spaddevmarcel:3000"
```

I was then forwarded to:  

```
http://localhost:3000/....  
```

---

#### The real issue:  

The problem wasn't Supabase—it was my app's authentication flow. Specifically, the issue was in this `Next.js` line:  

```typescript
return NextResponse.redirect(
    getStatusRedirect(
        `${requestUrl.origin}/`,
        'Success!',
        'You are now signed in.'
    )
);
```

When running the app with `next dev`, this code caused `localhost` to appear in the redirect.  

Additionally, the mismatch in the `.env` URL was causing the authentication flow to stop midway during the code exchange process because the incorrect URL didn't respond.  

---

### Key takeaway:  

- Supabase (and Gotrue) were working correctly.  
- The issue was the `Next.js` redirect handling during development (`next dev`), combined with my typo in the `.env` file.  

I hope this explanation helps anyone else who encounters similar issues!  

Thanks to everyone who helped clarify this for me.  

Kind regards,  
Towelie

**Comment by avallete** [comment]
Thank's for reporting back ! Happy you found a solution.
