### ISSUE TITLE
GitHub integration branch functionality broken when using `remotes` with default `auth.email.template.*.content_path` values

### ISSUE THREAD

**Issue by icopp** [supabase/cli#2963]
**Describe the bug**
When attempting to use a persistent branch with `remotes` values for `auth.email.template.*.content_path` in `config.toml`, the GitHub integration breaks on PRs with a `Invalid config for (name): open (path): no such file or directory` error.

**To Reproduce**
- Create a monorepo with a Supabase `config.toml` in one package
- In the `config.toml`, set values for `auth.email.template.*.content_path`. For example:
  ```
  [auth.email.template.confirmation]
  subject = "Confirm Your Signup"
  content_path = "./supabase/templates/confirmation.html"
  ```
- Set up a persistent branch via CLI
- In the `config.toml`, add a `remotes` entry. For example:
  ```
  [remotes.staging]
  project_id = "some-project-id-here"
  ```
- Create a GitHub PR using the persistent branch
- GitHub Supabase integration fails with an error around the `auth.email.template.*.content_path` setting

**Expected behavior**
- GitHub Supabase integration should work as expected, either by using the given file (which exists) or ignoring it

**Screenshots**

**System information**
- Rerun the failing command with `--create-ticket` flag: n/a
- Versions of services:
  ```
          SERVICE IMAGE      │      LOCAL       │  LINKED
  ─────────────────────────┼──────────────────┼────────────
    supabase/postgres      │ 15.1.1.78        │ 15.1.1.78
    supabase/gotrue        │ v2.164.0         │ v2.164.0
    postgrest/postgrest    │ v12.2.2          │ v12.2.2
    supabase/realtime      │ v2.33.58         │ -
    supabase/storage-api   │ v1.14.4          │ v1.14.4
    supabase/edge-runtime  │ v1.65.3          │ -
    supabase/studio        │ 20241202-71e5240 │ -
    supabase/postgres-meta │ v0.84.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
  ```

**Additional context**
n/a

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. It's apparently working only if supabase directory is at top level of your repo. I will push a fix for monorepo setups where supabase directory is nested somewhere.
