### ISSUE TITLE
Upgrade guide for version 2.0.0

### ISSUE THREAD

**Issue by Sicria** [supabase/cli#2971]
**Describe the problem**
Is there any documentation on upgrading from ~1.200.0 > 2.0.0? The bump is major makes it feels like there may be breaking changes, but I can't seem to find any mentions of any, or a guide on changes etc. 

**Describe the improvement**
Even if there are no breaking changes, it might be good to have a message about it for others just in case. For example I'm cautious about going from `1.223.10` > `2.0.0` just incase it breaks something and I don't immediately notice it.

**Comment by Sicria** [comment]
Just found this mentioned in a blog post. https://supabase.com/blog/cli-v2-config-as-code#breaking-changes so it's probably fine to upgrade, but I wonder if you could make this clearer in the repo or docs. Only a suggestion, feel free to close if you don't want to.

**Comment by avallete** [comment]
Thank's for the suggestion.

I added extra details and a link to the blogpost in the changelog release page: https://github.com/supabase/cli/releases/v2.0.0

So it's more discoverable from the github repo.
