### ISSUE TITLE
Failed to pull docker image - supabase/postgres:15.8.1.018

### ISSUE THREAD

**Issue by jamesfeeder** [supabase/cli#2977]
**Describe the bug**
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.8.1.018 not found: manifest unknown: Requested image not found

**System information**
 - Ticket ID: 8af4e9f503d8424faed3b7f20168d3fa
 - Version of OS: Fedora Linux 41 (Workstation Edition)
 - Version of CLI: 2.0.0
 - Version of Docker: 27.4.0
 - Versions of services:
![Screenshot From 2024-12-17 08-22-20](https://github.com/user-attachments/assets/e56f89ad-43cb-467c-9f02-9d9efcd1dbbe)

**Comment by sweatybridge** [comment]
Hi @jamesfeeder, our postgres team will work out the issue with Postgres image on ECR.

Meanwhile the workaround is to delete the local version file. 

```
rm supabase/.temp/postgres-version
```

**Comment by jamesfeeder** [comment]
Thank you 🙏 

While I'm using this workaround, Is it able to 'db push' to remote?

Just my curiosity, I don't have any plan to do it right now.

**Comment by eluce2** [comment]
I'm also having this issue, but deleting that temp file doesn't work for me, it just creates it again with the same version: `15.8.1.018`

**Comment by Nciso** [comment]
I have the same issue, there is no tag in the registry https://gallery.ecr.aws/supabase/postgres

**Comment by eluce2** [comment]
Ok, I guess my script was calling `supabase link` which was re-creating the version file. If I delete the file and then run the `db pull --linked` command, it works for me

**Comment by Nextc1** [comment]
same issues with different version

failed to pull docker image: Error response from daemon: failed to resolve reference "public.ecr.aws/supabase/postgres:15.8.1.020": public.ecr.aws/supabase/postgres:15.8.1.020: not found

**Comment by gaharrington** [comment]
> Hi @jamesfeeder, our postgres team will work out the issue with Postgres image on ECR.
> 
> Meanwhile the workaround is to delete the local version file.
> 
> ```
> rm supabase/.temp/postgres-version
> ```



> Hi @jamesfeeder, our postgres team will work out the issue with Postgres image on ECR.
> 
> Meanwhile the workaround is to delete the local version file.
> 
> ```
> rm supabase/.temp/postgres-version
> ```

After I do this, supabase start fails to start:
"supabase/postgres:15.6.1.143 => 15.8.1.020"

Using the --ignore-health-check produces the same error.

**Comment by sweatybridge** [comment]
> After I do this, supabase start fails to start

I forgot to mention that you also need to delete any backup volumes before restarting, ie. `supabase stop --no-backup`

**Comment by sweatybridge** [comment]
This problem with upstream postgres image has been fixed. https://github.com/supabase/postgres/pull/1372

**Comment by Ge6ben** [comment]
I get the same issue! when I run `subbase start` 
It was working fine after stopping it and resetting the db I can not start it again!
Error when I run `supabase start`

```
failed to pull docker image: Error response from daemon: failed to resolve reference "public.ecr.aws/supabase/postgres:15.8.1.044": failed to do request: Head "https://public.ecr.aws/v2/supabase/postgres/manifests/15.8.1.044": dialing public.ecr.aws:443 container via direct connection because  has no HTTPS proxy: connecting to public.ecr.aws:443: dial tcp: lookup public.ecr.aws: no such host
```
