### ISSUE TITLE
`supabase start` command fails after upgrading to `0.29.2`

### ISSUE THREAD

**Issue by KirioXX** [supabase/cli#300]
# Bug report

## Describe the bug

After updating to supabase CLI version 0.29.2, when running `supabase start` I get this error
```sh
Error: Error starting database: WARNING:  you need to manually restart any running background workers after this command
```
I already tried to remove all containers and images with the same result.

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Upgrade to subase cli version 0.29.2
2. Remove all containers and images with for example `docker container prune && docker image prune -a`
3. Run `supabase start`

## Expected behaviour

The service starts without errors.

## System information

- OS: macOS Monterey (12.4)
- Version of supabase-cli: 0.29.2

**Comment by soedirgo** [comment]
Should be fixed now - can you try upgrading to 0.29.3?

**Comment by djhi** [comment]
Confirmed on my side :+1:

**Comment by KirioXX** [comment]
Yes works for me too. Thanks, @soedirgo 🙌
