### ISSUE TITLE
Studio can't connect to default project

### ISSUE THREAD

**Issue by sdaoud** [supabase/cli#305]
# Bug report

## Describe the bug

After running `supabase init` followed by `supabase start`, I visit the studio URL http://localhost:54323 but the studio is unable to connect to the Default project. It stays on "connecting to project" indefinitely. I also see a 404 in the console for http://localhost:54323/api/projects/default/subscription

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run `supabase init`
2. run `supabase start`
3. Open the Studio URL link in browser
4. Navigate to Default project
5. Studio stuck in "connecting to project" state

## Expected behavior

The Default project should open successfully

## System information

- OS: macOS
- Browser: chrome
- Version of Supabase CLI: 0.30.0
- Version of Node.js: 13.14.0

**Comment by christrain91** [comment]
Same issue for me on `0.30.0`

**Comment by quangtd95** [comment]
same issue for me

**Comment by EALNick** [comment]
I had the same issue. I'm not sure if it helps but in my case I noticed that Supabase studio was not able to connect to REST endpoint because it was using localhost address (http://localhost:54321/rest/v1/) rather than network address of server. https://github.com/supabase/cli/issues/270

**Comment by pessimo** [comment]
I can self host supabase for local development as long as i don't change the JWT_SECRET in .env file which is by default 
JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long

if i change it to any other  generated jwt_secret, my studio stuck at connecting to project

**Comment by soedirgo** [comment]
Can you do `docker pull supabase/studio && supabase stop && supabase start` and try again?

**Comment by sdaoud** [comment]
@soedirgo That's done the trick 🎉

**Comment by jeramiahgcoffey** [comment]
I am having the same issue as of today. Studio can't reach `http://localhost:54323/api/projects/default/api/rest`

**Comment by andrebrantom** [comment]
I'm having the same issue, some APIs working OK at `http://localhost:54323` endpoint, but failing on the `api/projects/default/api/rest` API call.
![image](https://user-images.githubusercontent.com/112206/223099185-e0a8f2ef-f363-4ebc-9fbb-eac3e4ad3c6f.png)

**Comment by andrebrantom** [comment]
Ah, this was related to the issue raised on discord here: https://discord.com/channels/839993398554656828/1080939169980883025/1080939169980883025
Upgrading `supabase cli` to 1.42.0 has resolved it for me.
