### ISSUE TITLE
Polices editor crashes in local development

### ISSUE THREAD

**Issue by OskarArce** [supabase/cli#315]
# Bug report

## Describe the bug

Polices editor crashes just creating new table (local development)

## To Reproduce

Steps to reproduce the crash:

1. Initialize new project `$ mkdir your-project && cd $_`
2. Initialize Supabase `supabase init`
3. Start Supabase `supabase start`
4. Open [Supabase Studio](http://localhost:54323/project/default) & create new simple table (from SQL Editor or Table editor). E.g. suggested one on local development guide: ```create table employees (
    id integer primary key generated always as identity,
    name text
);```
5. Navigate to [Polices Editor](http://localhost:54323/project/default/auth/policies).
6. It has been crashed

## Expected behavior

Not to crash

## Screenshots

![imagen](https://user-images.githubusercontent.com/20611288/180743420-52b462cf-08ed-4787-a133-49a720e04c17.png)

## System information

- OS: Linux (Fedora 36)
- Browser: Firefox
- Version of supabase cli: 0.31.2

## Additional context

[Issue](https://github.com/supabase/supabase/issues/7863) moved from supabase

**Comment by soedirgo** [comment]
Hey @OskarArce, can you try doing `docker pull supabase/studio` and trying again?

**Comment by OskarArce** [comment]
@soedirgo  Fixed up!
Thank you!

**Comment by OskarArce** [comment]
@soedirgo but... now the `Invite` buttont has disappeared
![imagen](https://user-images.githubusercontent.com/20611288/180844379-5975c7ad-80e7-4cc2-82d8-885fd5d25594.png)
Docker images:
![imagen](https://user-images.githubusercontent.com/20611288/180844578-6843b19e-5f53-4a4f-bb27-e9b7af9c425b.png)

**Comment by sweatybridge** [comment]
closing this for now as it's superseded by #365
