### ISSUE TITLE
Postgrest docker image doesn't work on Apple M1

### ISSUE THREAD

**Issue by goldcoders** [supabase/cli#33]
# Postgrest Keeps Restarting 

## Describe the bug

Container of Postgres keeps restarting....
I tried several times, if somethings wrong...
if im running out of ram or not...
So Thats What I did I try to Bump the Ram and Swap

## Default Docker Set Up

4 CPU
Memory 2GB
Swap 1 GB

- This Result on Postgrest Keeps Restarting

## Working Docker Set UP

4 CPU
Memory 4GB
Swap 4 GB

- then enables Experimental Features

- [x] Use new Virtualization Framework

- This Resolves the ISSUE 

## System information

- Laptop: Macbook Air M1 with 8GB Ram
- OS: MacOs M1 Big Sur
- Version of supabase-js: [0.3.9]
- Version of Node.js: [14.16.0]

## To Reproduce

Docker Default Set Up
- 4 CPU
- Memory 2GB
- Swap 1 GB

- [x] Fresh Install Docker 
- [x] supabase init
- [x] supabase start

## Expected behavior

> Default Docker Set Up Will Keep the Postgrest container restarting...

## Screenshots

<img width="1680" alt="Screen Shot 2021-05-16 at 3 53 04 PM" src="https://user-images.githubusercontent.com/55337687/118390675-e5008980-b662-11eb-8a1b-0d17cd98a984.png">

**Comment by steve-chavez** [comment]
> Laptop: Macbook Air M1 

Not related to RAM. The upstream docker container for PostgREST doesn't work for ARM(M1 architecture) on MacOS yet.

There's a workaround here though: https://github.com/PostgREST/postgrest/issues/1785#issuecomment-832884561. It uses an Ubuntu build for ARM as the docker image.

**Comment by soedirgo** [comment]
@steve-chavez it actually works on M1 (over qemu), though as @goldcoders said I had to increase Docker's RAM to 4GB for it to work. Not sure if we should document this *here* though, as it's tangential to the CLI...

**Comment by cdedreuille** [comment]
Just as a reference, I'm experiencing the same issue locally on Apple M1 (discussed [here](https://github.com/supabase/supabase/discussions/1778#discussioncomment-806625)). I tried to push Docker's RAM to 4GB but it still keeps restarting.

**Comment by cdedreuille** [comment]
Ah it did work when I pushed the Swap to 4GB instead of 1.

**Comment by soedirgo** [comment]
For the record, keeping this issue open until PostgREST has a stable arm64 image - hopefully Docker's 2GB default is enough by then.

**Comment by steve-chavez** [comment]
There's now a PostgREST ARM Docker image for [v9.0.0](https://hub.docker.com/layers/postgrest/postgrest/v9.0.0/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02) and [latest](https://hub.docker.com/layers/postgrest/postgrest/latest/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02?context=explore).

**Comment by steve-chavez** [comment]
@soedirgo Can we close this one? (Not sure if the CLI needs updating or it will just pick up the `latest` docker image)

**Comment by soedirgo** [comment]
Yeah will close this once I update the image version in the CLI 👍

**Comment by soedirgo** [comment]
PostgREST 9 is now available in v0.15.6 👍
