### ISSUE TITLE
Add volumes

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#35]
# Chore

Since some people will be trying to deploy this to production, we should probably add a volume to the postgres image (even if it's just commented out

```
volumes:
      - <location>/postgres:/var/lib/postgresql/data
```

## Additional context

We could ask if they want to store the data?

**Comment by soedirgo** [comment]
We now use volumes for some containers, though they're all ephemeral because of the local dev use case. The self host setup however uses persisted volumes.
