### ISSUE TITLE
Missing command using the latest version

### ISSUE THREAD

**Issue by piotrkulpinski** [supabase/cli#353]
# Bug report

## Describe the bug

I just installed the CLI tool to test it now and I'm following the official Docs. Looks like the CLI is missing some of the commands listed. 

## To Reproduce

If I run `supabase db` it should display those commands (according to the docs): 

```bash
supabase db branch list
supabase db branch create
supabase db branch delete
supabase db switch
supabase db changes
supabase db commit
supabase db reset
supabase db remote set
supabase db remote commit
supabase db push
```
But my list is actually much shorter:

```bash
Available Commands:
  branch      Manage branches. Each branch is associated with a separate database.
  diff        Diffs the local database for schema changes
  push        Push new migrations to the remote database
  remote      Manage remote database connections
  reset       Resets the local database to current migrations
```

I'm running the latest version:
```bash
supabase -v
0.38.4
```

## Expected behavior

I wanted to use `supabase db commit` to create migrations automatically and `supabase db remote set` to create remote connection but those commands are missing along many others.

## System information

- OS: macOS
- Version of cli: 0.38.4

**Comment by sweatybridge** [comment]
Hi @piotrkulpinski , thanks for providing us with feedback. We are in the process of stabilising CLI commands for v1 release and unfortunately that meant some breaking changes. Specifically,

- `db commit` and `db changes` are superseded by `db diff`
- `db remote set` is replaced by `supabase link --project-ref`

The old behaviour is still available via `supabase db diff -f my_name` which creates a migration file automatically. In addition, you will be asked to enter your database password when doing `db remote push`.

We will be updating our guide to reflect these changes these few days. Once v1 is released, we will plan more carefully around deprecation. Appreciate your kind understanding.

**Comment by sweatybridge** [comment]
Hi @troels , we fixed the issue with `db remote changes` here https://github.com/supabase/cli/releases/tag/v0.38.7. Could you try upgrading to the latest version 0.39.3?

**Comment by troels** [comment]
Hi @sweatybridge 

Yes, it's working now.

**Comment by sweatybridge** [comment]
Our new docs site for v1 is now live:

- Local development guide: https://supabase.com/docs/guides/cli/local-development
- CI / CD guide: https://supabase.com/docs/guides/cli/cicd-workflow

The commands listed in [CLI reference](https://supabase.com/docs/reference/cli) are expected to have no breaking changes for this major version.

Hope it helps!
