### ISSUE TITLE
Add storage-api to docker-compose

### ISSUE THREAD

**Issue by awalias** [supabase/cli#36]
It should be a matter of adding the docker image `supabase/storage-api:latest` in here [https://github.com/supabase/cli/blob/main/src/templates/init/docker/docker-compose.yml](https://github.com/supabase/cli/blob/main/src/templates/init/docker/docker-compose.yml)

and also the storage schema from [here](https://github.com/supabase/storage-api/tree/master/migrations) to [here](https://github.com/supabase/cli/tree/main/src/templates/init/docker/postgres)

**Comment by inian** [comment]
Hmm I [added support](https://github.com/supabase/supabase/pull/1007) in the main repo, but not here. Main issue is that this setup is not completely local (assumes you have access to a s3 bucket)

**Comment by soedirgo** [comment]
This is now supported in the Go CLI.
