### ISSUE TITLE
Invite users

### ISSUE THREAD

**Issue by OskarArce** [supabase/cli#365]
# Bug report

## Describe the bug

It is not possible to invite new users (local development)

## To Reproduce

Steps to reproduce the crash:

1. Initialize new project `$ mkdir your-project && cd $_`
2. Initialize Supabase `supabase init`
3. Start Supabase `supabase start`
4. Open [Supabase Studio](http://localhost:54323/project/default)
5. Navigate to [Users](http://localhost:54323/project/default/auth/users).
6. `Invite` button has disappeared

Also I have try to invite with `inviteUserByEmail` function in a js script, It worked for a while but right now it throws an 500 error

## Expected behavor

I expect to can invite new users

## Screenshots

![imagen](https://user-images.githubusercontent.com/20611288/180844379-5975c7ad-80e7-4cc2-82d8-885fd5d25594.png)
Docker images:
![Captura de pantalla de 2022-08-15 11-24-38](https://user-images.githubusercontent.com/20611288/184611077-1a30c0b3-cb3d-49c3-b625-6405fee4bbbf.png)

## System information

- OS: Linux (Fedora 36)
- Browser: Firefox
- Version of supabase cli: 1.0.0

## Additional context

[Issue](https://github.com/supabase/cli/issues/315)

**Comment by sweatybridge** [comment]
Hi @OskarArce , thanks for reporting. I can reproduce this locally and we are working on a fix. I will ping you again once the fix is released.

**Comment by sweatybridge** [comment]
We have fixed this issue in the latest version of `studio`. You may need to clear your local image cache and restart supabase to fetch the latest version.

```bash
supabase stop
docker image rm supabase/studio public.ecr.aws/t3w2s2c9/studio
supabase start
```

**Comment by sweatybridge** [comment]
Feel free to open this ticket again if you are still having issues with new version.
