### ISSUE TITLE
Docker images are wrong architecture

### ISSUE THREAD

**Issue by Curetix** [supabase/cli#368]
# Bug report

## Describe the bug 
When pulling from the ECR repository (#364), some of the images are the wrong architecture (arm64 instead of x86/amd64). This results in noticeably reduced performance of local requests (due to emulation I guess). Images affected: Deno Relay, Studio, Kong, PG Meta.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use latest version of the CLI
2. Run `supabase start` in any project

## Expected behavior

The images should be for the correct architecture, like they were before.

## Screenshots

![Docker_Desktop_V5oGyR4HQV](https://user-images.githubusercontent.com/15160542/184711286-5f110e5d-a8a1-4313-aeea-efc8088c0ddb.png)

## System information

- OS: Windows 11
- Docker on WSL 2.0
- Version of CLI: 1.0.1

**Comment by sweatybridge** [comment]
Hi @Curetix , I can reproduce this issue locally. We will mirror the x86 images shortly and let you know once it's done. Meanwhile, if this is blocking, you may switch to docker registry using:

```bash
supabase stop
SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start
```

**Comment by sweatybridge** [comment]
We have pushed out x86 images. You can reset your local image cache and restart supabase local:

```bash
supabase stop
docker image prune --all
supabase start
```

**Comment by Curetix** [comment]
> We have pushed out x86 images. You can reset your local image cache and restart supabase local:
> 
> ```shell
> supabase stop
> docker image prune --all
> supabase start
> ```

Thank you!
