### ISSUE TITLE
Local Development fails to move beyond "Connecting to Default Project"

### ISSUE THREAD

**Issue by jchekanoff** [supabase/cli#371]
# Bug report

## Describe the bug

After installing Supabase CLI v1.0.1, I am unable to successfully access the project via the localhost GUI.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install Supabase CLI v1.0.1
2. Run `supabase start`
3. Visit studio url 

## Expected behavior

Supabase local project loads as expected

## Screenshots

![image](https://user-images.githubusercontent.com/28504852/184950999-351773a4-2932-429b-a337-516680ac1e21.png)

![image](https://user-images.githubusercontent.com/28504852/184951088-6e371e23-e362-48af-8fd6-c98405f15fd4.png)

## System information

- OS: macOS (latest)
- Browser (if applies): Chrome, Safari

## Additional context

Downgrading to v0.39.1 restores expected behavior.

**Comment by sweatybridge** [comment]
Hi @jchekanoff , in v1.0.1 we switched default image registry from docker hub to ECR. I suspect your error is due to outdated local image cache. Could you run the following commands to see if it works. 

```bash
brew upgrade supabase
supabase stop
docker image prune --all
supabase start
```

**Comment by lukebussey** [comment]
@sweatybridge That didn't work for me. The reason is that `supabase_rest_backend` keeps crashing every 5-6 seconds. the image being used is `public.ecr.aws/t3w2s2c9/postgrest:v9.0.1.20220802`

**Comment by rphlmr** [comment]
Same issue here with message `configuration file provided: not found`

**Comment by sweatybridge** [comment]
Just to be sure it's an issue with the image, could you try the following
```
SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start
```

It should switch images back to those hosted on docker hub.

**Comment by lukebussey** [comment]
@sweatybridge I receive this error now:
```
Error: Error response from daemon: No such image: docker.io/supabase/postgres:14.1.0.34
```

**Comment by sweatybridge** [comment]
Sorry I broke image pull in v1.0.4. Just released v1.0.5 to fix that.

**Comment by HegarGarcia** [comment]
Cannot start the local environment even with v1.0.5. `public.ecr.aws/t3w2s2c9/postgrest:v9.0.1.20220802` keeps restarting

**Comment by sweatybridge** [comment]
Ok I'm quite certain it's due to missing arm64 postgREST image on ECR. So if you are using m1 mac, please upgrade to latest and run with `SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start`.

I will try to get the postgREST image mirrored from docker hub tmr https://hub.docker.com/r/postgrest/postgrest/tags

**Comment by lukebussey** [comment]
@sweatybridge v1.0.5 worked for me - thanks!

**Comment by HegarGarcia** [comment]
> Ok I'm quite certain it's due to missing arm64 postgREST image on ECR. So if you are using m1 mac, please upgrade to latest and run with `SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io supabase start`.
> 
> I will try to get the postgREST image mirrored from docker hub tmr https://hub.docker.com/r/postgrest/postgrest/tags

Completely right, ran that command and works! Thanks a lot!

**Comment by sweatybridge** [comment]
I've mirrored postgrest arm64 image to ECR. Let me know if it works :)

**Comment by jchekanoff** [comment]
Thanks, @sweatybridge! Works for me on latest (v1.0.8).
