### ISSUE TITLE
generating typescript type fails when there is certain special chars in password

### ISSUE THREAD

**Issue by pixtron** [supabase/cli#372]
# Bug report

## Describe the bug

I tried to run this command:

```bash
supabase gen types typescript --db-url 'postgres://postgres:[YOUR_PASSWORD]@db.[YOUR_REF].supabase.co:6543/postgres' > types.ts
```

The password contained the special chars `$`, `#` and `%`. The command failed with

```bash
Error: node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Did some further tests:
- `$`, `%` in password work
- `#`, `?`  in password does not work

## To Reproduce

See above.

## Expected behavior

Should work with any special char.

## System information

- OS: macOS
- Version of supabase-cli: 1.0.1

## Additional context

The error is probably thrown in this `async` method and never caught. 
https://github.com/supabase/postgres-meta/blob/32da58fb3e18d21bd15ab423bb04a0267275d8ea/src/server/app.ts#L62-L65

**Comment by sweatybridge** [comment]
Hi @pixtron , we are now escaping passwords in v1.0.3. Feel free to open this ticket again if it doesn't solve your issue.

**Comment by pixtron** [comment]
@sweatybridge successfully tested with `#`, `:`, `.`, `/`, `@` in the password. Great job!

But with `v1.0.3` i get an new error when running typegen command with `--dbUrl`: "Error: Error response from daemon: network supabase_network_supabase-test not found"

I can fix that by running `supabase start` first. With `v1.0.1` i think i did not need to start a local instance to connect to a remote instance - possibly the network was still dangling around when i tried with `v1.0.1`. Feels a bit odd to have to spin up a local instance for this task.

**Comment by sweatybridge** [comment]
Yup, good catch. Changing it back to not require `start` in v1.0.4.
