### ISSUE TITLE
Updating Postgres

### ISSUE THREAD

**Issue by Flambe** [supabase/cli#382]
I'm using pg_graphql which is getting frequent updates, but these updates don't seem to be making it through to the CLI that often. I saw that someone [made a PR](https://github.com/supabase/cli/pull/299) to use the latest postgres image last month, but this got reverted.

Are there any plans to update the postgres image more frequently?

**Comment by sweatybridge** [comment]
Thanks @Flambe for the feedback. I will check on this next week and give you an update.

**Comment by NiklasPor** [comment]
I also just encountered a GQL issue which is only occurring on the CLI. Just linking for reference: https://github.com/supabase/pg_graphql/issues/206

**Comment by Flambe** [comment]
Did you manage to check this @sweatybridge?

**Comment by sweatybridge** [comment]
Hi @Flambe , thanks for reminding. We have manually updated postgres image to 14.1.0.66. Could you help verify if there's any missing graphql features in CLI v1.4.7?

Syncing the schema automatically is taking a bit longer because it needs to touch migration scripts in 3 different repos. But good news is our teams have agreed to work on it after next week.

**Comment by Flambe** [comment]
Hi @sweatybridge, thanks for the quick update!

I've updated my CLI and restarted my supabase locally & checking `select * from pg_extension;` does show pg_graphql to have a version of `v0.4.0` which is what I'm looking for. But the actual functionality I'm looking to use (`in` queries) does not seem to be present and I appear to be getting an old error (due to a spelling issue which is no longer in the pg_graphql code): `Invalid comaprison operator`

I'm not sure if the issue here is on the CLI or pg_graphql end?

> Syncing the schema automatically is taking a bit longer because it needs to touch migration scripts in 3 different repos. But good news is our teams have agreed to work on it after next week.

That's really good to hear!

**Comment by olirice** [comment]
@Flambe I wasn't able to reproduce the issue with the latest version of the CLI (1.4.7)

could you please triple check you're on 1.4.7 and try the following test case?


Table setup
```sql
create table account(
	id int primary key,
	name text
);

insert into account(id, name) values (1, 'a'), (2, 'b'), (3, 'c');
```

Query
```graphql
{
  accountCollection(filter: {id: {in: [2, 3]}}) 
  {
    edges {
      node {
        id
      }
    }
  }
}
```

Expected result
```sql
{
  "data": {
    "accountCollection": {
      "edges": [
        {
          "node": {
            "id": 2
          }
        },
        {
          "node": {
            "id": 3
          }
        }
      ]
    }
  }
}
```

---
@NiklasPor I left a similar note on your issue https://github.com/supabase/pg_graphql/issues/206 when you get a sec. thanks!

**Comment by Flambe** [comment]
@olirice You're correct it is working fine on 1.4.7.

My issue was that I did a small hack in the my migrations to implement `like` filters in GQL, but this replaced the `graphql.text_to_comparison_op` function with an older one which caused this issue. Updating this gives the expected result for `in` queries.

Sorry for the confusion, I should have double checked my existing code first!
