### ISSUE TITLE
Error while running db migrations

### ISSUE THREAD

**Issue by risonsimon** [supabase/cli#383]
# Bug report

## Describe the bug

I'm running into the following error when I'm running `supabase db remote commit` or `supabase start` after running the first migration by running `supabase db remote commit`.

```
Error: Error starting shadow database: ERROR:  relation "pgsodium.key_key_id_seq" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

## To Reproduce

1. Create a new Supabase project
2. Install CLI, and link to the project
3. Inside Supabase dashboard, go to SQL editor and run _Stripe subscription starter_ template to create the tables.
4. Run `supabase db remote commit` in the terminal
5. Run `supabase start` or run `supabase db remote commit` again.

## Expected behavior

Run the db migrations without errors

## System information

- OS: macOS
- Version of CLI: 1.0.7

**Comment by sweatybridge** [comment]
Hello @risonsimon , this is likely due to a new schema that is released to supabase platform. We will work on a fix soon.

**Comment by ZetiMente** [comment]
> Hello @risonsimon , this is likely due to a new schema that is released to supabase platform. We will work on a fix soon.
> 
> related [supabase/postgres#274](https://github.com/supabase/postgres/issues/274)

Hi @sweatybridge It's been two weeks now, is there a fix? There was a solution in the link you sent but I didn't understand the instructions there.

**Comment by sweatybridge** [comment]
Thanks @ZetiMente for following up on this. It took some effort to update the schema dump. Let me know if it works for you in v1.4.2 :)

**Comment by ZetiMente** [comment]
> Thanks @ZetiMente for following up on this. It took some effort to update the schema dump. Let me know if it works for you in v1.4.2 :)

Hi @sweatybridge I am still having issues with the CLI though. 

<img width="902" alt="Screen Shot 2022-10-07 at 4 17 01 PM" src="https://user-images.githubusercontent.com/76985631/194653687-6d8e1b86-2558-4881-b64b-c3031dacf467.png">
