### ISSUE TITLE
typegen error on function overloading

### ISSUE THREAD

**Issue by enyo** [supabase/cli#388]
When I run `supabase gen types typescript` the types file that is generated is invalid. There are plenty of duplicate fields:

`Error: Duplicate identifier 'exception_unknown_field'.`
`Error: Duplicate identifier 'comment'. `
etc...

<img width="503" alt="image" src="https://user-images.githubusercontent.com/133277/185501281-9a68763c-2e59-486f-b4c1-1229b7b5c14a.png">

**Comment by maxkostow** [comment]
I'm seeing this on the `Functions` property which does not seem to account for overloading
