### ISSUE TITLE
Add more detailed error output

### ISSUE THREAD

**Issue by panmau** [supabase/cli#39]
# Feature request

## Is your feature request related to a problem? Please describe.

When starting Supabase with the default config the error output is very generic when docker-compose fails for example because of a service already using a specified port.
```
$ supabase start
✖ Error running docker-compose.
```

## Describe the solution you'd like

The error output of supabase start should output more info about why docker-compose failed.

## Describe alternatives you've considered

Alternatively or additionally the full error could be logged to a file.

**Comment by nicholaschiang** [comment]
@panmau my current workaround is to just run the `docker-compose` command myself:
```commandline
$ docker-compose --file .supabase/docker/docker-compose.yml --project-name supabase up --detach
```
That :point_up: is the exact same command that [the Supabase CLI is running](https://github.com/supabase/cli/blob/main/src/commands/start.ts#L32) anyways.

**Comment by soedirgo** [comment]
With the new Go CLI the error output should now be more informative, e.g. Docker daemon not started, need to run `supabase init` in the project, etc.
