### ISSUE TITLE
auth: unencrypted connection

### ISSUE THREAD

**Issue by Aleksion** [supabase/cli#401]
# Bug report
The latest version of the supabase/cli (1.1.1) seems to have a few bugs related to the auth images:

## Describe the bug
- `supabase db start` adds an `ip_address` to the `audit_log_entries` column but the  `supabase db reset` command removes it again. That will result in any auth actions failing
- any `inbucket` related commands in local development will result in this error:

```
"auth_event":{"action":"user_invited","actor_id":"00000000-0000-0000-0000-000000000000","actor_username":"service_role","log_type":"team","traits":{"user_email":"member@example.com","user_id":"010b0e5c-f562-4f4d-b617-dfbd1ada2537"}},"component":"api","error":"Error sending invite email: unencrypted connection","level":"error","method":"POST","msg":"500: Error inviting user","path":"/invite","referer":"","remote_addr":"172.25.0.3:38572","timestamp":"2022-08-22T16:40:08Z"}
```

## To Reproduce
- Make sure you've installed the latest version of the cli (1.1.1)
- Create a new folder
- run `supabase init`
- run `supabase start` and check if you have the `ip_address` column in the auth database
- run `supabae db reset` and check if it's still there
- try sending a password recovery email (or create a new user) through the supabase dashboard

- OS: macOS
- Version of supabase-cli: [1.1.1]

## Extra context
We were coming from supabase cli 0.26.1 which worked. Downgrading to it again (which isn't simple because we're installing through Brew), resolves the issue

**Comment by soedirgo** [comment]
Sorry about this - should be fixed in 1.1.5 🙏
