### ISSUE TITLE
Migration statements not running in order?

### ISSUE THREAD

**Issue by maxkostow** [supabase/cli#404]
# Bug report

## Describe the bug

Getting `42P01` (table does not exist)  when running migrations with `insert` statements

## To Reproduce

1. Use supabase CLI 1.1.1 (#396 seems related)
2. Create the migration file
```sql
CREATE TABLE IF NOT EXISTS public.example
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT example_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.example
    OWNER to postgres;
GRANT ALL ON TABLE public.example TO anon;
GRANT ALL ON TABLE public.example TO authenticated;
GRANT ALL ON TABLE public.example TO postgres;
GRANT ALL ON TABLE public.example TO service_role;

INSERT INTO public.example VALUES (1, 'a');
```
3. Run
```sh
supabase stop
supabase start
supabase db reset --debug
```
5. See error
```
PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42P01","Message":"relation \"public.example\" does not exist","Detail":"","Hint":"","Position":13,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"parse_relation.c","Line":1360,"Routine":"parserOpenTable","UnknownFields":null}
``` 

## Expected behavior

The migration should run without issue as it did in `v0.38.4`

## Additional Information

If you move the `insert` to a separate file, the `db reset` completes successfully, however this will cause issues with our remote database as the migrations are already live.

**Comment by sweatybridge** [comment]
Hi @maxkostow , thanks for the detailed report. We are able to narrow down the problem to pgx statement cache and implement a workaround.

Feel free to open this issue again if you still face the same problem in `v1.1.3`.
