### ISSUE TITLE
Race condition in migration files

### ISSUE THREAD

**Issue by vbylen** [supabase/cli#405]
# Bug report

## Describe the bug

After updating supabase-cli to [v1.0.10](https://github.com/supabase/cli/releases/tag/v1.0.10) an error appears on one of my migration files when performing the `supabase db reset` command:  `cannot insert multiple commands into a prepared statement (SQLSTATE 42601)`.

Interestingly when just running the `supabase stop` and `supabase start` the db reset works smoothly as before.

## System information

- OS: macOS
- Version of supabase-cli: [1.0.10]
- Version of Node.js: [e.g. 18.7.0]

**Comment by vbylen** [comment]
I see this could be related to #404, my apologies for creating a new issue.

**Comment by sweatybridge** [comment]
Hi @vbylen this should due to a byte slice bug that's fixed in v1.1.2 https://github.com/supabase/cli/releases/tag/v1.1.2  

Feel free to open this issue again if upgrading doesn't work.
