### ISSUE TITLE
Error Sending Magic Link

### ISSUE THREAD

**Issue by mclean25** [supabase/cli#406]
# Bug report

## Describe the bug

When running Supabase locally via the CLI, I'm getting the following error when trying to sign in:

```
POST http://localhost:54321/auth/v1/otp

{email: "xxxx@hey.com", create_user: true, gotrue_meta_security: {}}

code: 500
error_id: "79e6a0d2-0398-401d-80cb-6abba937a327"
msg: "Error sending magic link"
```

The user is being correctly created in the `auth.users` table, but nothing is showing up in Inbucket as the error would suggest. 

I'm only getting this error running locally, hence why I posted this issue in this repository.

I know this is hard to decipher with this limited amount of information. Is there some logs hiding somewhere I can look into deeper?

## System information

- OS: macOS
- CLI version: 1.1.2
- Version of supabase-js: 1.35.6
- Version of Node.js: 16.15.0

## Context

I'm signing up like so:

```
await supabaseClient.auth.signIn({
      email: data.email,
    });
```

**Comment by mclean25** [comment]
For the record, I've now run `docker system prune -a` a few times and re-started the CLI but still get the same issue.

**Comment by esteban-url** [comment]
maybe related:

I've been unable to invite users from the local supabase studio.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/14810250/186070434-01767211-3edc-4fdc-a0d3-468765d83632.png">

I get a similar error when trying it from my API:

```ts
import { createClient } from '@supabase/supabase-js'
...
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
)
...
export const inviteUserByEmail = async (email: string) => {
  try {
    const { data, error } = await supabase.auth.api.inviteUserByEmail(email)

    if (error) {
      console.error(error)
      throw new RedwoodGraphQLError(error.message)
    }
    return data
  } catch (error) {
    console.error(error)
    throw new RedwoodGraphQLError(error.message)
  }
}
```

it logs this error:

```js
{ message: 'Error inviting user', status: 500 }
```

## System information 

* OS: macOS
* CLI version: 1.1.2
* Version of supabase-js: 1.35.4
* Version of Node.js: v16.17.0

**Comment by soedirgo** [comment]
Can you try this again in 1.1.5? Both the magic link and invite user error should be fixed now.

**Comment by esteban-url** [comment]
confirmed. it works! thanks @soedirgo

**Comment by mclean25** [comment]
Confirming as well, thanks!

**Comment by songololo** [comment]
I am encountering a similar issue: no email response with signup links or OTP codes arrive in my inbox...

Is there something I have to do to enable the dummy SMTP server to work?

I can see that the login requests is received by the `supabase_auth_interface` but then nothing happens in terms of receiving email.

Using `supabase` installed via `brew` - version `1.4.6`.

**Comment by soedirgo** [comment]
Hey @songololo, are you checking the inbox from the [email testing web interface](https://supabase.com/docs/reference/cli/config#local)?

**Comment by songololo** [comment]
@soedirgo thanks, I missed that.
