### ISSUE TITLE
add aarch64 support

### ISSUE THREAD

**Issue by bmedicke** [supabase/cli#41]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to run supabase on a Raspberry Pi 4 with a 64bit OS. Currently some of the used images don't seem to support that architecture (see log at the bottom) resulting in `exec user process caused: exec format error` for:

* supabase-mail
* supabase-db
* supabase-rest
* supabase-auth

## Describe the solution you'd like

Add support for aarch64.

## Additional context

`docker-compose up` output on a RPi4 a 64bit Rasbian:
https://gist.github.com/bmedicke/4ee23a9914717c3fd92f7800cd457cff

**Comment by julienR2** [comment]
I'm also facing this issue, on a Raspberrypi 4 running an Ubuntu Server x64.

I've dug a bit further and from what I see, each of Supabase services actually have a arm64 build too, available as a tar ball in the releases of each repo. For example [storage-api releases](https://github.com/supabase/storage-api/releases) list aa aarch64 build in each release, while on [docker hub](https://hub.docker.com/r/supabase/storage-api/tags?page=1&ordering=last_updated) only the arm64 is available.

I've tried manually downloading those images and import them into docker, with the hope that docker-compose would then picked the loaded images, but it seems I was a bit naive and might be missing something in my understanding 😅 

Any guidance to go through with using those build to `docker-compose up` the full stack with only aarch64 images would be awesome ! (And of course ideally, submitting those already build aarch64 images to docker-hub, would probably ease the process too)

**Comment by soedirgo** [comment]
The Node.js CLI is being EOL'd in favor of the Go rewrite, so I don't think this will land for the old CLI. But we still need this for the self-hosted Compose setup, so I'll create an issue there. Shouldn't be difficult as we already use aarch64 for the hosted platform, I'll see if I can get around to this the next few weeks.

**Comment by soedirgo** [comment]
Closing this in favor of the linked issue. The `supabase/postgres` image is the only one left missing a linux/arm64 build - the GitHub-hosted runner isn't enough to build these. Once we start having the linux/arm64 build (with self-hosted runners) it should be available with no change on the CLI side.

**Comment by soedirgo** [comment]
Resolved as per https://github.com/supabase/cli/issues/429#issuecomment-1263228324!
