### ISSUE TITLE
Generated types are incorrect for enum arrays

### ISSUE THREAD

**Issue by mrmattrc** [supabase/cli#413]
# Bug report

## Describe the bug

When running `supabase gen types typescript`, enum array type definitions are incorrect. Rather than wrapping the possible values in an array and declaring that it is an array of those types, it puts the array on the last item in the type.

## To Reproduce

1. Create a table with a column specifying an enum array.
2. Run `supabase gen types typescript`.
3. Look at the type output.

## Expected behavior

Enum arrays are correctly typed when running `supabase gen types typescript`.

### Supabase enum array definition

<img width="674" alt="Supabase enum array" src="https://user-images.githubusercontent.com/19395720/186550446-cb9a2b55-52e6-4569-b169-41090d3b836a.png">

### Generated types (code removed for example)

<img width="484" alt="Generated types" src="https://user-images.githubusercontent.com/19395720/186550910-3679d597-4b50-4fd3-86a5-896276f57974.png">

### Expected type output (code removed for example)
<img width="358" alt="Expected type output" src="https://user-images.githubusercontent.com/19395720/186551154-ece58662-67e0-493d-8f47-8680218c0ee8.png">

## System information

- OS: macOS 12.3.1
- Version of supabase-js: 2.0.0-rc.4
- Version of supabase cli: 1.1.5
- Version of Node.js: 16.16.0

**Comment by mrmattrc** [comment]
@soedirgo, thanks for the quick fix! Just out of curiosity, how does `supabase/postgres-meta` affect `supabase/cli`? In other words, is there a rough ETA for when I can update the CLI to include this fix?

**Comment by soedirgo** [comment]
We use postgres-meta to do the actual typegen - it's running in Docker through the CLI.

> is there a rough ETA

I'd say a few days - there are some changes I'd like to do at the same time. If it's urgent for you we can just do it now though, it's a pretty quick task.

**Comment by mrmattrc** [comment]
Thanks for the explanation. It's not an urgent issue. Thanks for being willing to prioritize it though! I look forward to getting the new update soon.

**Comment by mrmattrc** [comment]
@soedirgo, I updated the CLI to v1.3.0 and reran the typegen command, but I am experiencing the same behavior as before.
### Generated types (code removed for example)
![Supabase Typegen v1.3.0 Output](https://user-images.githubusercontent.com/19395720/187464151-77392bd4-1614-42e8-8d48-371ed9cd645f.png)

**Comment by soedirgo** [comment]
Was this run with `--local`? You might need to `supabase stop && supabase start` for the change to take effect

**Comment by mrmattrc** [comment]
@soedirgo, that worked! I was running locally, so I stopped and restarted supabase, reran the command, and it output it correctly. Thank you for the help!
