### ISSUE TITLE
Error when installing on windows via pnpm

### ISSUE THREAD

**Issue by universse** [supabase/cli#416]
# Bug report

## Describe the bug

preinstall script failed to run. Looks like `opts.url` is wrong. Should be [https://github.com/supabase/cli/releases/download/v1.1.6/supabase_1.1.6_windows_amd64.tar.gz](https://github.com/supabase/cli/releases/download/v1.1.6/supabase_1.1.6_windows_amd64.tar.gz) instead of [https://github.com/supabase/cli/releases/download/v1.1.6/supabase.exe_1.1.6_windows_amd64.tar.gz](https://github.com/supabase/cli/releases/download/v1.1.6/supabase.exe_1.1.6_windows_amd64.tar.gz) (no ".exe").

## Screenshots

![image](https://user-images.githubusercontent.com/15166715/186933481-22db41e9-f3e5-4b1c-a53d-fed00d1b511e.png)

## System information

- OS: Windows
- Version of supabase cli: 1.1.6
- Version of Node.js: 16.13.0

**Comment by sweatybridge** [comment]
Thanks for reporting. I've released a new version to fix the download path.
