### ISSUE TITLE
Database Diff not picking up FK "ON DELETE" status change

### ISSUE THREAD

**Issue by HankG** [supabase/cli#420]
# Bug report

## Describe the bug

Through DataGrip I changed the "ON DELETE" configuration on a foreign key to go from "NO ACTION" to "CASCADE". When I run the `supabase db diff` command the default option it doesn't pick up that change. If I use the migra though it does.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go into a table with a foreign key constraint that has ON DELETE NO ACTION
2. Change the constraint to ON DELETE CASCADE
3. Run the diff tool without migra

## Expected behavior

I expected to see something like what migra produced which picks up the change. In the case of migra it generated a "drop constraint" with the key name and then an "add constraint" with the key name with all the updated settings.

**Comment by sweatybridge** [comment]
Hi @HankG , thank you for reporting this issue. In the long run, we think it's more maintainable to focus on a single schema diff tool and make it good. Currently we are leaning towards migra because of its speed. Hence, I just want to give you a heads up that we might not fix such issues with pgadmin any time soon.

That said, we have not reached a final decision and I would greatly appreciate to hear your experience using both tools. Is there any situation where you think pgadmin has generated a better schema diff than migra?

**Comment by HankG** [comment]
Totally understand the desire to go down to one tool. The one thing I'm not thrilled with with Migra, and maybe it is a setting, is that it uses lower case for the SQL keywords and wraps table/field/etc name in a double quotes tag even if it doesn't need it. So some notional output of the two side-by-side,:

```sql
CREATE TABLE IF NOT EXISTS public.item_type_1
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    other_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    value double precision NOT NULL DEFAULT '0'::double precision,
    date1 timestamp with time zone NOT NULL,
    date2 timestamp with time zone NOT NULL,
)


create table "public"."item_type_2" (
    "id" uuid not null default uuid_generate_v4(),
    "other_id" uuid not null,
    "value" double precision not null default '0'::double precision,
    "start" timestamp with time zone not null,
    "stop" timestamp with time zone not null
);
```

It's a minor enough thing that if it isn't configurable then it doesn't matter to me either way. I've been using migra because I don't want to hand code the transitions that the default tool in the current version misses. I guess Migra also missed the "IF NOT EXISTS" but maybe there is a reason for that too...TBD.
