### ISSUE TITLE
Generate types for enums

### ISSUE THREAD

**Issue by mrmattrc** [supabase/cli#422]
# Feature request
Currently, the typegen command inlines enum types for columns. It would be more helpful to generate "top-level" types for the enums. This would allow us to use the enum types elsewhere in our code. Additionally, the enum types could be used for the column definitions rather than repeating the same type multiple times (for Row, Insert, and Update on tables).

## Is your feature request related to a problem? Please describe.
I have to manually create types for the enums which can get out of sync with the Postgres enums.

A clear and concise description of what you want and what your use case is.
The typegen command creates top level types for enums, uses the enums for the table column definitions, and exports the enum types.

**Comment by soedirgo** [comment]
Does this kind of format work for you? Each enum belongs to a schema so they need to be namespaced.
```ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: number;
          name: string | null;
          status: Database["public"]["Enums"]["user_status"] | null;
        };
        ...
      };
    };
    Views: { ... };
    Functions: { ... };
    Enums: {
      user_status: "ACTIVE" | "INACTIVE";
    };
  };
}
```
