### ISSUE TITLE
Arm64 images not used for 4 of the services on Mac OS M1 

### ISSUE THREAD

**Issue by jcoble** [supabase/cli#429]
# Feature request
I'm on a MacBook Pro M1 and using cli version 1.3.  When I run supabase start it pulls the images, starts them, but 4 are still amd64.

supabase_storage
supabase_db
supabase_auth
supabase_realtime

Those are the amd versions still.  I'm noticing it pulls specific images and doesn't allow it to choose the correct architecture.  What can I do to get the correct arm64 images, because I even see them in the docker hub registry.  

Please note that I am very green when it comes to docker and compose files etc.  But, if I'm right it doesn't even use a compose file, but the cli and go to pull the images on the start command.  I know just enough Go to be dangerous, but if something needs changed in the cli I could probably do it.  

Thanks for any help!!

**Comment by sweatybridge** [comment]
Hi @jcoble , thanks for offering to help! This is mostly a backend issue with mirroring docker images to ECR which took us some time to get right. Barring `supabase_realtime`, the rest of images have been upgraded to use arm64 version in CLI v1.4.2.

I will keep you posted once realtime is mirrored too.

**Comment by jcoble** [comment]
I upgraded the cli through brew, then started the containers.  It pulled all them from the registry ok, and 2 of the images are now arm64, then you mentioned supabase_realtime is not yet finished.  But the postgres_db image is still the amd version for some reason.
![image](https://user-images.githubusercontent.com/17329655/188631682-08716eb8-53bd-4c48-bceb-805eb9857113.png)

Here's the log:

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
 2022-09-06 11:59:53.541 UTC [1] LOG:  pgaudit extension initialized
 2022-09-06 11:59:53.706 UTC [1] LOG:  redirecting log output to logging collector process
 2022-09-06 11:59:53.706 UTC [1] HINT:  Future log output will appear in directory "/var/log/postgresql".

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start.... 2022-09-06 11:59:51.524 UTC [247] LOG:  pgaudit extension initialized
 2022-09-06 11:59:51.731 UTC [247] LOG:  redirecting log output to logging collector process
 2022-09-06 11:59:51.731 UTC [247] HINT:  Future log output will appear in directory "/var/log/postgresql".
 done
server started

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-schema.sql
CREATE ROLE
REVOKE
CREATE SCHEMA
CREATE FUNCTION
REVOKE
GRANT


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01-extension.sql
CREATE SCHEMA
CREATE EXTENSION


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02-sodium-extension.sql
CREATE SCHEMA
CREATE EXTENSION
GRANT ROLE
GRANT ROLE
GRANT ROLE


waiting for server to shut down.... done
server stopped

PostgreSQL init process complete; ready for start up.

Just let me know if you need anymore info and I'd be glad to grab it.  Thanks for doing this.

One other thing, is the studio going to have all the same functionality as the hosted in the future?  It's missing some key things that make it much easier to work with like seeing your functions and triggers,  postgres logs, and the sql editor saving the query, or at least have it maintain it's state when navigating away and coming back.  I wanted to get down a good workflow like you have in the docs, working locally and then sending the migrations through github's ci/cd pipeline.  But I noticed I had to go to another sql editor to do some things, which is ok, but working directly in the studio app was really nice using your hosted service.  Thanks again.

**Comment by sweatybridge** [comment]
Happy to share that we have now released all arm64 images, including realtime and postgres! You should be able to get those images after upgrading to v1.5.2.

> like seeing your functions and triggers, postgres logs, and the sql editor saving the query, or at least have it maintain it's state when navigating away and coming back.

I agree having these features in local studio would really improve the local dev experience. We have created tickets for each of them, with logs probably being the most requested. Our end goal to achieve as much feature parity as possible with the hosted studio.

Feel free to reopen if you encounter other problems with the arm images.

**Comment by soedirgo** [comment]
Note: you might need to run `docker image rm public.ecr.aws/t3w2s2c9/postgres:14.1.0.71 public.ecr.aws/t3w2s2c9/realtime:v0.22.7` if you've used a previous version of the CLI for the linux/arm64 image to be used.
