### ISSUE TITLE
supabass cli error in wsl2

### ISSUE THREAD

**Issue by zhihengGet** [supabase/cli#430]
# Bug report

## Describe the bug

running supabsae cli in wsl2  gave error when getting typescripts from schema

Error: error running container
triggerUncaughtException(err, true /* fromPromise */);
            ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'

### another error when i tried it with podman onwindows 
`Error: Error response from daemon: failed to obtain logs for Container '45f62aa4fb8926896c0490d0833f6b9797748dae1def510af5e7ac675c7f8b43': using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
`
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. installed brew, docker on wsl2
2.  install supabase with brew 
3.  go to project on windows /mnt/user/....
4.  run init then  supabase gen type typescript --db-url  

## System information

- OS: [e.g. macOS, Windows]  window 11 wsl2 ubuntu 
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]   latest  2.0.0
- Version of Node.js: [e.g. 10.10.0]  v16

**Comment by sweatybridge** [comment]
Hello, we have added support for generating types without docker. You might want to try the following commands to see if it works for you:

```bash
supabase init
supabase login
supabase link --project-ref
supabase gen types typescript --linked
```
