### ISSUE TITLE
Type Generator Generates wrong Enum Array Types

### ISSUE THREAD

**Issue by madebyfabian** [supabase/cli#433]
# Bug report

## Describe the bug

I have a schema that uses an ENUM array. The typescript type generator returns the wrong type for it. 

### Wrongly generated type:
```ts
export interface Database {
  // ...
  table: {
    Row: {
      my_col: "ENUM_VALUE_1" | "OTHER_ENUM_VALUE" | "THIRD_ENUM_VALUE"[] | null
    }
  }
}
```
As you can see it applies the array only on the last enum value.

## To Reproduce

Create a Posgres ENUM
Setup an example table, with a col that has a ENUM defined as array.
Setup CLI and generate Types.

## Expected behavior

I assume that the type generation for this would look like:

```ts
export interface Database {
  // ...
  table: {
    Row: {
      my_col: ("ENUM_VALUE_1" | "OTHER_ENUM_VALUE" | "THIRD_ENUM_VALUE")[] | null
    }
  }
}
```

## Screenshots

![Bildschirmfoto 2022-09-02 um 10 13 31](https://user-images.githubusercontent.com/32813692/188095454-25c08479-f6db-40a2-ab71-942a9d83248d.jpg)

![Bildschirmfoto 2022-09-02 um 10 13 55](https://user-images.githubusercontent.com/32813692/188095509-a26c3ed3-1d46-4aa6-aaf7-904964d8cbe3.jpg)

## System information

- OS: macOS
- Version of supabase-cli: 1.0.3
- Version of Node.js: 16.16.0

**Comment by soedirgo** [comment]
This seems like https://github.com/supabase/cli/issues/413. Can you update the CLI, restart the local dev server, and try it again?
