### ISSUE TITLE
supabase cb remote commit fails with pg_dump error

### ISSUE THREAD

**Issue by eidermaen** [supabase/cli#437]
# Bug report

## Bug description

I have a supabase project that is running in production. Now I want to setup supabase for local development so that I don't develop against the production data. Therefore I run:

```
supabase init

supabase link --project-ref <id>

supabase db remote commit  // Fails with pg_dump error
```

Error:
```
Error: Error running pg_dump on remote database: pg_dump: error: query failed: ERROR:  permission denied for table _type

pg_dump: error: query was: LOCK TABLE "graphql"."_type" IN ACCESS SHARE MODE
```

## System information

- OS: macOS 12.14 (intel)
- supabase cli version: 1.4.0

**Comment by soedirgo** [comment]
Can you try recreating the pg_graphql extension via https://app.supabase.com/project/_/database/extensions?

**Comment by eidermaen** [comment]
Seems to be working now as expected. Thank you!

Issue can be closed.

**Comment by barrelltech** [comment]
I had the same issue. Got the error when passing in `--debug` however the normal error I received was:

```
Error: Error running pg_dump on remote database: error running container
```

I tried turning off and on the graphql extension via your link. I still received the same error. I turned off the graphql extension, ran it again, and it worked. I turned the extension on afterwards.

1. Is there another way to 'recreate' the extension that I'm missing (besides turning it off and on)?
2. Will this cause any issues if the dump is created without the graphql extension?
3. Do I need the graphql extension if I'm just using the supabase-js select/upsert functions?

**Comment by sweatybridge** [comment]
Hi @barrelltech , to answer your questions:

> 3. Do I need the graphql extension if I'm just using the supabase-js select/upsert functions?

You don't need to enable graphql extension for select/upsert functions as the default json output should be fine.

> 2. Will this cause any issues if the dump is created without the graphql extension?

If you don't use graphql, it would be fine to omit graphql extension from the dump.

> 1. Is there another way to 'recreate' the extension that I'm missing (besides turning it off and on)?

We have an alternative solution that you may want to try https://github.com/supabase/cli/issues/506#issuecomment-1274925661. If the problem still persists, please feel free to contact support@supabase.io and we will investigate further.
