### ISSUE TITLE
CLI should be able to generate types from linked project

### ISSUE THREAD

**Issue by Soviut** [supabase/cli#438]
# Feature request

## Is your feature request related to a problem? Please describe.

In the new CLI (`1.0.8`) when using `supabase gen types typescript` there are two options for generating types from the database; `--local` and `--db-url`. Using the latter to get remote types requires providing the database URL which includes the database password. This makes it unsafe to put into a script in `package.json`.

## Describe the solution you'd like

The `supabase gen types typescript` should have a flag to use the currently linked project (eg: `--linked`. It would probably also make sense if this was the default if you omit any explicit flag.

This would remove the need for access to sensitive keys/passwords, making automation simpler.

## Describe alternatives you've considered

I currently document the process in my README but have to explain where to get the database password from.

Another possibility might be to use environment variables, but they'd have to be system environment variables, which are tricky to juggle with .env files.

**Comment by sweatybridge** [comment]
We have added support for `--linked` flag in the latest release https://github.com/supabase/cli/pull/518. Thank you for providing feedback on this feature request.

**Comment by gkatsanos** [comment]
> We have added support for `--linked` flag in the latest release #518. Thank you for providing feedback on this feature request.

please mention this somehow in https://supabase.com/docs/reference/javascript/typescript-support .. I spent some hours trying to figure out why the types arent properly generated till I realized I need to change that flag.
