### ISSUE TITLE
CLI via NPM doesn't work

### ISSUE THREAD

**Issue by LB22** [supabase/cli#441]
https://github.com/supabase/cli/issues/127#issuecomment-1226884931
@sweatybridge I'm thinking this might interest you

Let the powershell terminal speak for itself
```
> npm i supabase
changed 1 package, and audited 526 packages in 3s
found 0 vulnerabilities

> npx supabase -h
'supabase' is not recognized as an internal or external command,
operable program or batch file.
```

I have tried doing it using the global flag too. I have my PATH environment variables set up correctly too, so that's not the issue.
```
> npm i supabase -g     

added 14 packages, and audited 15 packages in 4s
found 0 vulnerabilities

> npm list -g --depth 0
C:\Users\Username\AppData\Roaming\npm
└── supabase@1.4.2

> supabase login
supabase : The term 'supabase' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ supabase login
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (supabase:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

NPM version: 8.3.1
Node version: 17.4.0
Docker version: 20.10.17, build 100c701
OS: Windows 10 Pro (21H2 19044.1949) 64bit

**Comment by sweatybridge** [comment]
Hi @LB22 , this is an issue with https://github.com/supabase/cli/blob/main/package.json#L18 bin path not handling windows directory separator so the supabase binary isn't copied properly. I haven't found satisfactory solution to it yet but just want to let you know it is on our radar.

For now, the workaround is to invoke the command with `node_modules/supabase/bin/supabase -h` instead of npx.

**Comment by sweatybridge** [comment]
Let's leave this open. I just looked into it a bit more and found a fix. :)

**Comment by twofingerrightclick** [comment]
I am having the same issue with 1.14.0... its hard to be a windows (and PowerShell 7) dev with node :)
The workaround of running supabase.exe from the install path is getting me by. (`./node_modules/supabase/bin/supabase`)

**Comment by sweatybridge** [comment]
Hi @twofingerrightclick, did you run into this issue with a fresh install, ie. `npm i supabase --save-dev`, or with package.json that already contains supabase as dev dependency? The latter would be a new issue that's also present on mac and linux.

**Comment by twofingerrightclick** [comment]
@sweatybridge ... it was a `npm i supabase --save-dev`. I'll watch that issue. Thanks!

**Comment by cohlar** [comment]
Hi, I'm having the same issue with version `1.15.0`. I installed supabase running `yarn add -D supabase`.

**Comment by dwozniak8** [comment]
Same here

`PS C:\apps\x> yarn add -D supabase
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > apollo-server-express@3.11.1" has unmet peer dependency "express@^4.17.1".
warning " > ts-loader@9.4.1" has unmet peer dependency "webpack@^5.0.0".
Downloading https://github.com/supabase/cli/releases/download/v1.26.5/supabase_1.26.5_windows_amd64.tar.gz
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: EPERM: operation not permitted, symlink '..\supabase\bin\supabase' -> 'C:\apps\x\node_modules\.bin\supabase'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',

`

**Comment by cohlar** [comment]
> Hi, I'm having the same issue with version `1.15.0`. I installed supabase running `yarn add -D supabase`.

I just upgraded to `1.27.10` and everything now works like a charm. I no longer need to use `node_modules/supabase/bin/supabase`.

**Comment by hoangvu12** [comment]
> 1.27.10

I'm still facing the same problem in `1.13.0` version.

**Comment by rokbenko** [comment]
@sweatybridge Hi! I have issues that I suspect are similar to what was discussed above.

I was getting the following error after running `pnpm supabase:start`:

```
> @ supabase:start C:\Users\xxxxx\xxxxx
> npx supabase start

'supabase' is not recognized as an internal or external command,
operable program or batch file.
ELIFECYCLE  Command failed with exit code 1.
```

Therefore, I ran the following command:

```
pnpm install supabase@latest --save-dev
```

This installed Supabase version `2.2.1`.

Then I tried to run `pnpm supabase:start` again, but I'm still getting the same error:

```
> @ supabase:start C:\Users\xxxxx\xxxxx
> npx supabase start

'supabase' is not recognized as an internal or external command,
operable program or batch file.
ELIFECYCLE  Command failed with exit code 1.
```

However, there was a warning when I ran `pnpm install supabase@latest --save-dev` which I think is the cause of the issue:

```
WARN  Failed to create bin at C:\Users\xxxxx\xxxxx\node_modules\.pnpm\supabase@2.2.1\node_modules\supabase\node_modules\.bin\supabase. ENOENT: no such file or directory, stat 'C:\Users\xxxxx\xxxxx\node_modules\.pnpm\supabase@2.2.1\node_modules\supabase\bin\supabase.EXE'
WARN  Failed to create bin at C:\Users\xxxxx\xxxxx\node_modules\.pnpm\supabase@2.2.1\node_modules\supabase\node_modules\.bin\supabase. ENOENT: no such file or directory, stat 'C:\Users\xxxxx\xxxxx\node_modules\.pnpm\supabase@2.2.1\node_modules\supabase\bin\supabase.EXE'
pabase. ENOENT: no such file or directory, stat 'C:\Users\xxxxx\xxxxx\node_modules\.pnpm\supabase@2.2.1\node_modules\supabase\bin\supabase.EXE'
```

How can I solve the issue?
