### ISSUE TITLE
Containers not restarted after Docker update

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#446]
# Bug report

## Describe the bug

Docker Desktop update seems to have caused supabase to bug out a bit. Running `supabase stop && supabase start` fixed it

## To Reproduce

iirc I ran `supabase stop` before updating Docker Desktop.

Afterwards I ran `supabase start`, and it said it was already running. I then ran `supabase status` and tried opening the URLs, and none of them worked (ERR_CONNECTION_REFUSED)

## Expected behavior

Should continue working as if nothing changed, possible restart or redownload docker images if necessary

## System information

- OS: macOS 10.15
- Browser: Brave
- Version of supabase-js: N/A
- Version of Node.js: v16.15.0

**Comment by sweatybridge** [comment]
Do you have [live restore](https://docs.docker.com/config/containers/live-restore/) enabled in your docker daemon config? It should help with minor and patch upgrades of docker desktop.

I will close this issue as won't fix because the CLI should not affect system wide docker config.

**Comment by probablykasper** [comment]
If I'm not mistaken, the live restore setting sounds like something that's just for when the upgrade is actually happening. I don't expect Supabase to be working while the actual upgrade is happening, if that's what it seemed like I was getting at

**Comment by sweatybridge** [comment]
You are right. It seems to be a problem with using `unless-stopped` as the default restart policy https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
