### ISSUE TITLE
How to use Supabase CLI with GitHub Actions?

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/cli#45]
# Bug report

## Describe the bug

As far as I know, there's no way to use the Supabase CLI in a continuous integration environment like GitHub Actions without checking the automatically generated `.supabase/` directory into version control.

Running `supabase init` in a CI environment just results in nothing (because your CI can't answer its prompts):

```
Run yarn supabase init
25l25l? Port for Supabase URL: ‣ 800025h25h
```

And then, because `supabase init` did nothing and thus didn't create the `.supabase/` directory, running `supabase start` fails:

```
Run yarn start:sb
.FileNotFoundError: [Errno 2] No such file or directory: './.supabase/docker/docker-compose.yml'
Error: Process completed with exit code 1.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new GitHub action.
2. Run `supabase init`
3. Run `supabase start`
4. See error.

## Expected behavior

There should be documentation and CLI options for running in continuous integration environments like GitHub Actions.

## Screenshots

![image](https://user-images.githubusercontent.com/20798889/127790865-1e0fa963-98c1-4d3a-97a7-ad9aec36a36f.png)

## System information

- OS: Ubuntu 20.04 LTS on GitHub Actions
- Version of supabase-js: 1.21.0
- Version of Node.js: 12.22.3

## Additional context

I'm trying to get the checks working for this PR: tutorbookapp/tutorbook#228

And then this is one of the failed runs: https://github.com/tutorbookapp/tutorbook/runs/3216189922?check_suite_focus=true

**Comment by soedirgo** [comment]
@nicholaschiang I had a brief test and couldn't make the prompts work in scripts (it was meant to be more of a local dev tool).

FYI we're currently [replacing the CLI](https://github.com/supabase/cli/tree/new) which will use commands and flags instead of prompts to make it CI-friendly. We'll also work on a GitHub Action and make the server work in CI for testing purposes (like `firebase emulators:exec`). This is all WIP though - sorry about this 🙏

**Comment by nicholaschiang** [comment]
@soedirgo no problem! I'm sure Supabase will have an amazing testing + CI experience once it's been built. :grin: 

My current workaround is to simply create a new hosted Supabase project called "Test" and then use it during CI. Eventually though, once you guys finish work on [this](https://github.com/supabase/cli/tree/new) I'll want to be running the PostgreSQL database locally (e.g. so that I can have multiple tests running in parallel without one test affecting the state of another).

**Comment by n-sviridenko** [comment]
Any updates on this?

**Comment by sweatybridge** [comment]
We now have a [GitHub Action app](https://github.com/supabase/setup-cli) for setting up the Supabase CLI on your action runners. There are a few examples on how to perform basic validations, such as applying all committed `supabase/migrations` to a local database instance on CI.

Feel free to try it out and open new issues if you run into problems.

**Comment by n-sviridenko** [comment]
@sweatybridge thanks for providing these examples.

However, we use CircleCI, and I believe, that the people upvoting this thread are not mandatorily looking for the Github Actions specific solution. Is there an isolated solution we can leverage to stay CI-agnostic?

**Comment by sweatybridge** [comment]
Hi @n-sviridenko , thank you for the kind feedback. 

I'm not 100% familiar with CircleCI so I hope you can help clarify a few questions. Does CircleCI runner come with the following tools installed?

- Git
- Docker 
- Curl or homebrew 

We are essentially following the same setup steps for GitHub action runner as documented in our [local development](https://supabase.com/docs/guides/local-development) guide. As long as there's an easy way to install these dependencies, our CI/CD steps are agnostic to the platform running the build. 

If setting up these dependencies is too complicated, what would be your preferred way to install them on CircleCI? I can think of a few alternatives like distributing an installer script, or a docker image with CLI pre installed. But I hope you can help me understand what's the ideal approach for CircleCI here.
