### ISSUE TITLE
Allow file creation on type generation.

### ISSUE THREAD

**Issue by wh1337** [supabase/cli#450]
# Feature request

## Describe the solution you'd like
I would like to have an additional flag that will create the file of the types that were generated.

e.g. `supabase gen types ts  --db-url $DATABASE_URL --create-file src/types`

This would then create the `supabase.d.ts` in the `src/types` directory.

**Comment by soedirgo** [comment]
Any benefit of this over `supabase gen types typescript --db-url $DB_URL > src/types/supabase.d.ts`?
