### ISSUE TITLE
Supabase login redirects to wrong url on ctrl clicking the link.

### ISSUE THREAD

**Issue by isaif** [supabase/cli#457]
# Bug report

## Describe the bug
Running `supabase login` commands gives the following message
`You can generate an access token from https://app.supabase.com/account/tokens.`
When I control click the link I am redirected to "https://app.supabase.com/account/tokens." instead of "https://app.supabase.com/account/tokens". Notice the dot / period at the end of the first link. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install the supabase cli from either npm or linux package manager like yay.
2. Run `supabase login`
3. Control click the link provided

## Expected behavior
When I control click the link I should be redirected to "https://app.supabase.com/account/tokens" instead of "https://app.supabase.com/account/tokens."

## Screenshots

![supabase-login](https://user-images.githubusercontent.com/11773308/190130695-83ad5ef1-8073-457f-9917-72455d4cdcd1.png)

## System information

- OS: manjaro
- Browser: chrome
- Version of supabase-js: v1.4.6
- Version of Node.js: v16.0.0

## Additional context

I think it is because of terminal I am using i.e. konsole which is causing this problem. I haven't tried other terminal application which allows control clicking the links. But I can help if the dot / period at the end can have a space before it.

**Comment by soedirgo** [comment]
Yeah, I think we just need to remove the dot at the end. Would you like to create a PR for it?

**Comment by isaif** [comment]
> Yeah, I think we just need to remove the dot at the end. Would you like to create a PR for it?

Yes sure. I checked the file which should be modified even before opening the issue.

I hope it is this one https://github.com/supabase/cli/blob/a493acde43512cb02d260fada2ae10e308f9493f/internal/login/login.go#L17
