### ISSUE TITLE
Support serving multiple functions at once

### ISSUE THREAD

**Issue by soedirgo** [supabase/cli#459]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now it's not possible to serve multiple functions at once.

## Describe the solution you'd like

Support `supabase functions serve` (with no function name arg) which serves all functions in `supabase/functions`.

## Describe alternatives you've considered

None

## Additional context

Asked in https://github.com/supabase/cli/issues/456#issuecomment-1248002166

**Comment by vbylen** [comment]
Looking forward to this! It's a cumbersome ordeal to serve the right function at the right time in local dev once you have several of them scattered throughout your app.

**Comment by sweatybridge** [comment]
This is now supported in latest CLI by `supabase functions serve`
