### ISSUE TITLE
PostgreSQL version is different than hosted Supabase

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/cli#46]
# Bug report

## Describe the bug

The PostgreSQL version run locally via `docker-compose` in this CLI is different than the version hosted by Supabase for new projects (which I'm pretty sure is v13). This prevents me from using something like the [pgAdmin Schema Diff](https://www.pgadmin.org/docs/pgadmin4/development/schema_diff.html) tool to generate migration scripts for my production Supabase project based on changes I've made to my local development PostgreSQL database.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Supabase project.
2. Start the local Supabase: `supabase start`
3. Connect pgAdmin to both.
4. Try to schema diff.
5. See error saying that both servers have to be running the same version of PostgreSQL.

## Expected behavior

The CLI and the hosted version of Supabase should both be running the same version of PostgreSQL.

## System information

- OS: Ubuntu 20.04 LTS (Pop_OS! 20.04 LTS)
- Version of supabase: 0.5.0
- Version of Node.js: 12.18.3

## Additional context

I'm trying to migrate my database schema using diffs instead of migration scripts as [recommended](https://supabase.io/new/blog/2021/03/31/supabase-cli#migrations).

**Comment by soedirgo** [comment]
The `supabase/postgres` image version is hardcoded (0.13.0) in the Compose file, so the DB version is locked on 12.7. With the new CLI you'll have a `dbVersion` in your config so we can select the appropriate image version to use. (Migrating between major versions will have to be done manually however)

**Comment by nicholaschiang** [comment]
Gotcha @soedirgo so I'm essentially just waiting on the new CLI for all these issues? :grin:

**Comment by soedirgo** [comment]
Pretty much 😅 though as a workaround you may be able to change the version in the Compose file to `13.3.0` or `latest` which would be Postgres 13.

**Comment by soedirgo** [comment]
With the new CLI you're now able to set `dbVersion` (automatically populated when you run `supabase link`).

**Comment by ftfdfrancoeur65** [comment]
Hi @soedirgo, 
is this merged? I'm not seeing any reference to `link` in `cmd/` directory.

**Comment by soedirgo** [comment]
The `supabase link` command was changed to `supabase db remote` subcommands in [0.13.0](https://github.com/supabase/cli/releases/tag/v0.13.0). Still need to put up docs, but you can see the example usage in examples/tour.
