### ISSUE TITLE
extension "pg_graphql" does not exist

### ISSUE THREAD

**Issue by bruceharrison1984** [supabase/cli#460]
# Bug report

## Describe the bug

Trying to run `supabase start` after `supabase db remote commit` fails with the following:
```sh
$ supabase start
Error: Error starting database: ERROR:  extension "pg_graphql" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Have existing Supabase project deployed
2. `supabase db remote commit`
3. Check that migrations were created
4. `supabase start` 
5. View error message

## Expected behavior

I would expect the supabase containers to start

## System information

- Windows 10
- Supabase CLI: 1.4.6
- Postgres 13

**Comment by soedirgo** [comment]
Our Postgres 13 Docker image is horribly outdated, the latest one was from July 2021. There hasn't been much work on releasing an updated Postgres 13 image sadly

**Comment by bruceharrison1984** [comment]
Would I be better served just manually migrating to a new pg14 Supabase project rather than waiting for pg13 fixes? That was actually my end goal when I downloaded the CLI.

**Comment by daver182** [comment]
Sorry for reopening, but I'm having the same problem. Does anyone know how to migrate to PG14?
Can I use an older version of the cli to fix this? I'm using pg13 in production, and I don't want to migrate.

Thanks

**Comment by soedirgo** [comment]
You can find the migration instruction here: https://supabase.com/docs/guides/database#migrating-between-projects

Older CLI versions would use the same if not older versions of the image, so that probably wouldn't help. I just discovered though that this error pops up even if you don't do `supabase db remote commit` - that can be fixed, so reopening this issue.
