### ISSUE TITLE
Wrong type generated for timestamptz postgres type

### ISSUE THREAD

**Issue by binjamil** [supabase/cli#467]
# Bug report

## Describe the bug
I have a column updatedAt of type timestamptz in a Postgres table. When I generate type definitions for it using `supabase gen types typescript --local` command, the typescript type that gets generated is `string | null` when it should be `Date | null`. In short, I expect Supabase CLI to generate Date type for all Date/Time postgres types in the database.

## To Reproduce

1. Go to https://supabase.com/docs/guides/with-nextjs and follow along the tutorial
2. Set up your project for local development by following along https://supabase.com/docs/guides/cli/local-development guide
3. Once your local development supabase services are running, run `supabase gen types typescript --local > supabase/types.ts` command
4. Open the generated file and look at the type of updatedAt column for profiles table. It will be of type `string | null`

P.S. If you're using NextJS with TypeScript, you will see the type error in Account.tsx component file as shown in screenshots below.

## Expected behavior
The type generated for updatedAt column should be `Date | null`

## Screenshots

Database schema:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/90112974/191056719-fbac77a4-c060-4fe4-a6c2-2f3564055a0e.png">

Generated types:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/90112974/191056824-dda9e218-e086-4ee4-9656-19a91b52098b.png">

TypeScript error:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/90112974/191056990-99b9e73d-d188-4353-825b-759c8f30bf7c.png">

## System information

- OS: macOS 12.4 21F79 arm64
- Version of Supabase CLI: 1.4.6
- Version of supabase-js: 2.0.0-rc.10
- Version of Node.js: 16.16.0

**Comment by soedirgo** [comment]
This is expected - timestamptz etc. are returned as `string` from the REST server. There's some discussion why we keep it that way here: https://github.com/supabase/postgrest-js/issues/201

**Comment by sweatybridge** [comment]
Have we thought about automatic de/serialisation of Date types in supabase-js? It would be nice to handle this conversion in client library since Date fields are so common.

**Comment by soedirgo** [comment]
You can comment on the linked thread. I don't think we'll be doing this unless there's a proposal on how to deal with the issues mentioned there.

**Comment by soedirgo** [comment]
Just an update, we're considering automatic conversion to `Date` for supabase-js v3, though there's no timeline for this yet.
