### ISSUE TITLE
Make JWT signing secret readily available

### ISSUE THREAD

**Issue by bruceharrison1984** [supabase/cli#468]
# Feature request

Within a NextJS app, I have some API endpoints where I manually validate the JWT to avoid a round-trip. This breaks when using `supabase start` because I don't know what the signing token is.

## Describe the solution you'd like

Make the signing token static or available within the UI (or ideally, both). You could also make it configurable via the `toml` file as well I suppose.

## Current JWT signing token within a deployed Supabase project
![image](https://user-images.githubusercontent.com/17836372/191104768-ae9979e5-4b40-4227-90c4-4f62f058c2d9.png)

**Comment by bruceharrison1984** [comment]
I found the signing token within the docker image `GOTRUE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long`.

I still think it'd be nice if this was surfaced somewhere more accessible than within an ENV_VAR inside of the auth docker container.

**Comment by soedirgo** [comment]
Is it sufficient to output this when running the `supabase start` command?

**Comment by bruceharrison1984** [comment]
> Is it sufficient to output this when running the `supabase start` command?

Yeah, I think that could work as well.
