### ISSUE TITLE
Service 'kong' failed to build : Build failed

### ISSUE THREAD

**Issue by carlomigueldy** [supabase/cli#47]
# Bug report

## Describe the bug

Failed to get credentials for Kong when `supabase init` is executed

```bash
carlomigueldy@DESKTOP-Q42TFOP:~/projects/saas-starter$ supabase init
✔ Port for Supabase URL: · 8000
✔ Port for PostgreSQL database: · 5432
✔ Port for email testing interface: · 9000
✖ Error running docker-compose: realtime uses an image, skipping
rest uses an image, skipping
storage uses an image, skipping
mail uses an image, skipping
auth uses an image, skipping
Building kong
#1 [internal] load build definition from Dockerfile
#1 sha256:a2bf235f4fa01db7fb26200e6ef362fd57ada372b4bc7e1de5c56b470cd90bd0
#1 transferring dockerfile: 253B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:aaa0ae78db691dfb8ecc2380ae3694a081ce542f81261cf88448f8c3034be22a
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/kong:2.1
#3 sha256:1bdd87e2d2dd9065233e3ef11ba879dfcb300117837b2620acfd719f1953d56c
<3>init: (2483) ERROR: UtilConnectToInteropServer:300: connect failed 2
#3 ERROR: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
------
 > [internal] load metadata for docker.io/library/kong:2.1:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
Service 'kong' failed to build : Build failed
```

## To Reproduce

A fresh project then just run `supabase init`

## Expected behavior

Should install a local emulator with all of Supabase dependencies.

## Screenshots

![image](https://user-images.githubusercontent.com/45052332/128720078-6c005df6-8da5-4d8d-9af1-8dec5d4a19be.png)

## System information

- OS: Windows
- Version of supabase-js: 0.5.0
- Version of Node.js: v14.17.1

**Comment by soedirgo** [comment]
Thanks for the report @carlomigueldy!

I couldn't reproduce this locally. Looking around, it seems like something to do with buildx:
- https://github.com/docker/buildx/issues/415
- https://github.com/docker/for-win/issues/11261

If the CLI isn't critical to your app right now, I'd suggest holding off on using atm as we're phasing it out for the WIP [Go CLI](https://github.com/supabase/cli/tree/new).

**Comment by carlomigueldy** [comment]
Thanks for the response! @soedirgo 

Actually last night it wasn't working... Then I slept and woke up and gave it another shot and it was working.

**Comment by soedirgo** [comment]
Heisenbugs - the ~best~ worst kind of bugs 🤡
