### ISSUE TITLE
gen types typescript changes table ordering on unrelated changes

### ISSUE THREAD

**Issue by chrisb2244** [supabase/cli#474]
# Feature request
I'd like the output of `supabase gen types typescript --db-url blah > my_database_types.ts` to produce a file that doesn't have lots of changes due to reordering of the tables. 

## Is your feature request related to a problem? Please describe.
I made some changes via the web GUI/dashboard, and then wanted to regenerate my types.
However, the changes (as shown by, e.g. `git diff`) are many, most of which are due to the tables being reordered.

## Describe the solution you'd like
Provide the same output for each call of `supabase gen types typescript`, regardless of `--local` or `--db-url`, so long as the database being referenced is the same.

## Describe alternatives you've considered
Manually reordering the generated types file. Undesireable, especially if repeatedly required.

## Additional context
Example changes:

![image](https://user-images.githubusercontent.com/7201433/192199278-05b6ffd3-94f4-4e6c-804a-58beb7b29a11.png)
and
![image](https://user-images.githubusercontent.com/7201433/192199244-0efba30c-09cd-41a2-81ae-3581bed58225.png)
 
caused by removing some nullable types on a different table.

Given that these are only used for typing with TypeScript (and not directly for database migrations, etc) I'd be fine with any static ordering, e.g. alphabetical by table/function name etc.

**Comment by soedirgo** [comment]
P.S. the fix isn't out on the latest CLI version yet, but will be soon once we update the typegen's Docker image version.
