### ISSUE TITLE
Getting error "relation "pgsodium.key_key_id_seq" does not exist (SQLSTATE 42P01)" when using "db remote commit"

### ISSUE THREAD

**Issue by xsmithdev** [supabase/cli#477]
# Bug report

## Describe the bug

When using the latest CLI to init, start, link, and remote commit; supabase errors with a missing relation.

```bash
relation "pgsodium.key_key_id_seq" does not exist (SQLSTATE 42P01)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `supabase init`
2. `supabase start`
3. `supabase link --project ...`
4. `supabase db remote commit`
5. `supabase db reset`

```bash
PS C:\Users\silen\Documents\GitHub\buildr-monorepo> supabase db reset        
Resetting database...
Initialising schema...
Applying migration 20220824061131_remote_commit.sql...
Error: ERROR: relation "pgsodium.key_key_id_seq" does not exist (SQLSTATE 42P01)
```

## Expected behavior

The database should now reflect the migration.

## System information

- OS: Windows 11
- Version of supabase-cli: 1.1.5
- Version of Node.js: 16.13.2

**Comment by sweatybridge** [comment]
Hello @ARMATAV , `supabase/extensions.sql` is a file that we no longer support in CLI v1 and I suspect it was working for you by accident...

Could you and @ZetiMente help me check that your remote projects have pgsodium enabled under the `pgsodium` schema?
![Screenshot 2022-09-27 at 12 31 34 AM](https://user-images.githubusercontent.com/1639722/192331827-97292fdd-639f-49c9-a3de-029eb38f2b0d.png)

The second issue with off sync timestamp between remote and local migration files was [fixed recently](https://github.com/supabase/cli/commit/0690a5177d390cc94c20a8f518f9e29976607eb0) in v1.4.5.

**Comment by ZetiMente** [comment]
Hi @sweatybridge I do have PGSODIUM enabled now, thanks to your help on the other issue ! I no longer get that error. I now get this: 
<img width="902" alt="Screen Shot 2022-10-07 at 4 17 01 PM" src="https://user-images.githubusercontent.com/76985631/194655297-87f42b5b-7916-40a2-88d4-8a2fad3a6b03.png">

**Comment by sweatybridge** [comment]
Hi, could you try running with `supabase db reset --debug` flag to check the detailed error log?

**Comment by sweatybridge** [comment]
We updated the way shadow database is created in the latest version. Feel free to open this issue again if the problem still persists.

**Comment by fbinz** [comment]
I'm not sure if it's the same problem, but I'm still having trouble creating a local development setup with the steps described in the OP. 
If I understand correctly, `supabase db remote commit` (step 4) on a new project should basically create all necessary tables.
While an SQL migration file is indeed successfully created, it references two views which are not present in the local postgres instance.

For reference, here are the views that are available on the hosted supabase.co database:
![image](https://user-images.githubusercontent.com/1530332/210810053-1a64ed23-eb9b-40c6-b9eb-9a94979bd780.png)

And here are the views in the locally created database:
![image](https://user-images.githubusercontent.com/1530332/210810199-d28a4ab5-31c1-4894-8aac-ee5e707e1b87.png)

The script generated by `supabase db remote commit` includes GRANT statements for those two missing views (decrypted_key, mask_columns). When applying the migrations using `supabase db reset`, these GRANT lead to errors, of course.

Commenting out these GRANT statements seems to work for now, but I guess it might lead to problems later.

**Comment by sweatybridge** [comment]
Hey, thanks for reporting. Did you try this on the latest version of CLI? This issue is different and it's mostly due to a pre-release of vault that was reverted. Updating CLI should fix it.

**Comment by jonathanperret** [comment]
I'm hitting the same issue as @fbinz on a fresh project after `supabase db remote commit`. The hosted database seems to use `pgsodium` version `3.1.5` whereas the CLI sets up version `3.0.4` (according to `pg_catalog.pg_extension`).

**Comment by fbinz** [comment]
Thanks for responding so quickly. I was using the latest version of the CLI.

**Comment by sweatybridge** [comment]
> The hosted database seems to use pgsodium version 3.1.5 whereas the CLI (version 1.29.1) sets up version 3.0.4 (according to pg_catalog.pg_extension).

The root cause is the same as https://github.com/supabase/cli/issues/766. I've updated the postgres image used by cli to match that of hosted platform.

**Comment by vikiival** [comment]
Hello @sweatybridge,

I am experiencing the same issue.  CLI (version 1.29.6)

1. make dump from remote db - `supabase db dump -f 1673369341_name.sql`
2. mv 1673369341_name.sql supabase/migrations
3. `supabase start`


```
Error: ERROR: relation "pgsodium.decrypted_key" does not exist (SQLSTATE 42P01)
At statement 106: --
-- Name: TABLE "decrypted_key"; Type: ACL; Schema: pgsodium; Owner: supabase_admin
--

GRANT ALL ON TABLE "pgsodium"."decrypted_key" TO "pgsodium_keyholder"
```

**Comment by d-e-h-i-o** [comment]
Hi @sweatybridge,

experiencing the same bug. Used CLI with version 1.33.0 to generate a remote commit. Now when the [Github CI script from the documentation](https://supabase.com/docs/guides/cli/managing-environments) is being run the following error is thrown:

```Applying migration 20230217111149_remote_commit.sql...
Error: ERROR: relation "pgsodium.decrypted_key" does not exist (SQLSTATE 42P01)
At statement 958: --                                                                                
-- Name: TABLE "decrypted_key"; Type: ACL; Schema: pgsodium; Owner: supabase_admin
--                                                                                
                                                                                  
GRANT ALL ON TABLE "pgsodium"."decrypted_key" TO "pgsodium_keyholder"             
Try rerunning the command with --debug to troubleshoot the error.
```

Script:
```
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
 ```

**Comment by devonkcopeland-serial** [comment]
Hi @sweatybridge,

I'm experiencing the same issue as @d-e-h-i-o. 

`Error: ERROR: relation "pgsodium.decrypted_key" does not exist (SQLSTATE 42P01)
At statement 568: --                                                                          
-- Name: TABLE "decrypted_key"; Type: ACL; Schema: pgsodium; Owner: postgres
--                                                                          
                                                                            
GRANT ALL ON TABLE "pgsodium"."decrypted_key" TO "pgsodium_keyholder"
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.`

**Comment by sweatybridge** [comment]
For future reference, this issue was addressed in v1.35.0 https://github.com/supabase/cli/pull/818. Feel free to reopen if updating CLI to latest doesn't help.

**Comment by wyozi** [comment]
Had this error locally when undergoing a major postgres upgrade (14 -> 15) and trying to run supabase reset.

Stopping and restarting supabase helped to force supabase cli to upgrade the used docker images

**Comment by pedromassango** [comment]
This is F# weird, I am running a "clean" docker container, why am I even having this issue in my local env? (not linked to a remote projectect)
