### ISSUE TITLE
ERROR:  permission denied for table users

### ISSUE THREAD

**Issue by JamesGarbaczewski** [supabase/cli#478]
# Bug report

Currently unable to use pg_dump as getting permission denied for table users.  
`pg_dump: error: query failed: ERROR:  permission denied for table users`
The last time pg_dump successfully ran was the morning of 7/21.

## Expected behavior

I believe pg_dump should be able to dump the database including the users table as it was previously.

I came across this, https://github.com/supabase/supabase/discussions/2495 Is this the recommended fix?

If so, is there anywhere this change would have been communicated?  Thank you

**Comment by soedirgo** [comment]
Permission issues on auth tables on pg_dump should be fixed now.
