### ISSUE TITLE
Support db-url flag for db reset

### ISSUE THREAD

**Issue by ryanalta** [supabase/cli#480]
# Bug report

## Describe the bug

The database connection string for the command `supabase db reset` appears to include a hardcoded 'localhost' for the hostname, and I am not finding anywhere I can override this. 

I'm not really great at go or familiar with the project but searching the codebase for 'localhost' seems to reveal hardcoded connection strings with no environment variable option in a couple spots.

https://github.com/supabase/cli/blob/aa6a5121cbc52201a31d6308d987cebd34e46aad/internal/db/reset/reset.go#L54

## To Reproduce

Using a VSCode dev container, I install the supabase cli, init and start a database (no problems), and then run `supabase db reset`

## Expected behavior

Able to set a postgres connection string or minimally, host so that `supabase db reset` runs.

## Current result:

```bash
# supabase db reset
Resetting database...
Initialising schema...
Error: failed to connect to `host=localhost user=postgres database=main`: dial error (dial tcp [::1]:54322: connect: cannot assign requested address)
```

## System information

- OS: linux, docker container
- Version of supabase-cli: 1.5.0

**Comment by sweatybridge** [comment]
Hi @ryanalta, could you share with us your `devcontainer.json` file to reproduce the error? I tried the following which works

```json
{
  "name": "Node.js & TypeScript",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:16-bullseye",
  "features": {
    "ghcr.io/devcontainers/features/docker-in-docker:1": {}
  },
  "postCreateCommand": "npm install -g supabase"
}
```

Here's the output from `supabase db reset` running inside dev container

```bash
node ➜ /workspaces/supabase-action-example (update-ci ✗) $ supabase db reset
Resetting database...
Initialising schema...
Applying migration 20220810154537_new_employee.sql...
Finished supabase db reset on branch main.
```

**Comment by ryanalta** [comment]
It doesn't seem like there's a way to specify the hostname in 1.12.2 either-- I'm using a devcontainer that extends an existing docker-compose with a custom Dockerfile for the main container that the devcontainer runs in (can't share), but I can force localhost for the container to resolve to my host IP with `extra_hosts`. I've added this to my docker-compose file and seems to work well enough: 

```
    extra_hosts:
      - "localhost:host-gateway" 
```

It would still be nice to be able to set the DB connection hostname via something in config.yml though, I'm not seeing if that exists but I do see a port.

**Comment by sweatybridge** [comment]
Possibly related to https://github.com/supabase/cli/issues/270. Would be helpful to remove the hardcoded hostnames for other services too.

**Comment by getglad** [comment]
+1 that the `extra_hosts` addition works for me as well.

I have historically had a `host.docker.internal:host-gateway` in the `extra_hosts` for other reasons, but had not seen an impact on supabase until recently.

**Comment by mrmikardo** [comment]
I'd also like the option of passing in a DB connection string so that I could use the `reset` command on hosted Supabase instances, too.

**Comment by tehnorm** [comment]
> e option of passing in a DB connection string so that I could use the `reset` command on hosted Supabase instances, too.

I would agree as well. It's very frustrating not being able to reset hosted Supabase instances - a use case is having a clean instance to apply seeds to for UAT for our product team.

**Comment by sweatybridge** [comment]
This is now supported on latest version of CLI. For eg. 

```bash
supabase db reset --linked
```
