### ISSUE TITLE
Adding plv8 extension via supabase UI causes error to throw when CLI stops/restarts

### ISSUE THREAD

**Issue by yowzadave** [supabase/cli#482]
# Bug report

I added the plv8 extension via the user interface at `localhost:54323`, and then added a migration that uses a plv8 function. When I stop and then re-start the database (thus running all of the migrations), an error is thrown:

```
Error: Error starting database: ERROR:  language "plv8" does not exist
HINT:  Use CREATE EXTENSION to load the language into the database.
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

Shouldn't enabling an extension persist even when stopping/starting CLI container?

Is it possible to configure so that plv8 will be enabled on start?

**Comment by soedirgo** [comment]
I believe you need to either do a `supabase db diff` to generate a new migration that includes creating the new extension, or include the `CREATE EXTENSION` manually in your migration. An extension is just part of your schema in this case.

**Comment by sweatybridge** [comment]
In addition, the hosted supabase project installs plv8 in `pg_catalog` schema so I'd suggest doing the same locally as well. The full command to include at the start of your migration file is:

```sql
CREATE EXTENSION IF NOT EXISTS "plv8" WITH SCHEMA "pg_catalog";
```

Feel free to reopen if you are still running into this issue.
