### ISSUE TITLE
Configurable storage FILE_SIZE_LIMIT

### ISSUE THREAD

**Issue by grschafer** [supabase/cli#489]
# Feature request

## Is your feature request related to a problem? Please describe.

I have customized the `FILE_SIZE_LIMIT` on my production supabase app, and it would be helpful to use the same `FILE_SIZE_LIMIT` value in my local development environment so that local testing matches the behavior of production.

## Describe the solution you'd like

I'd like the `config.toml` to include a new `storage` table with a `file_size_limit` key, as shown:

```
[storage]
# The maximum file size allowed, in bytes.
file_size_limit = 52428800
```

I haven't dug into config deserialization, but hopefully it would be possible to make the `storage` table optional for backwards-compatibility.

The config value for `file_size_limit` would then be passed to the environment of the storage-api container when it is started, similar to how other config values are used.

## Describe alternatives you've considered

None come to mind, other than modifying my local supabase CLI to do the above or to hardcode a different file size limit.

## Additional context

If this is an acceptable suggestion, I can likely submit a PR.

**Comment by soedirgo** [comment]
Yes, this is very much welcome, thanks! Maybe with `file_size_limit_bytes` instead of `file_size_limit`.
