### ISSUE TITLE
Cannot run edge function due to outdated deno runtime

### ISSUE THREAD

**Issue by point-source** [supabase/cli#490]
# Bug report

## Describe the bug
I wrote a supabase edge function a few weeks ago and successfully deployed it. Yesterday I went to edit it and realized I could not run it locally as I used to.

It appears that as deno continues to update their std library, functions will automatically use newer and newer versions of this library. In this case, my function's dependencies are now using std 0.153.0 which is incompatible with deno 1.20.3 (which is what supabase uses).

In order to get my application to work, I either need to find a way to force the std library down to 0.152.0 or get supabase to run something newer than 1.20.0. Since I don't import std myself but rather my dependencies do, I don't see a way to control which version of std I get.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new supabase function: `supabase functions new hello`
2. Edit the function and add a dependency such as `import "https://esm.sh/plaid@11.0.0";`
3. Run the function with supabase `supabase functions serve hello --debug` and observe [the error output](https://gist.github.com/point-source/a1831e9b109878df6c11aac718e62dd1)
4. Run the function with deno cli 1.20.3 and observe the same error: `deno run supabase/functions/hello/index.ts`
5. Run the function with deno cli 1.26.0 and observe that it works because 1.26.0 is compatible with std 0.153.0 while deno 1.20.3 is not

In case it helps, in my testing I used [asdf](https://asdf-vm.com/) as a version manager to be able to switch between deno versions.

## Expected behavior

I expect there to be a way to force either the deno version or library version or both when running locally as well as remote. Otherwise, a deterministic runtime environment is not possible and this reduces the viability of the edge functions feature.

## System information

- OS: macOS 12.6 (M1)
- Version of supabase-js: 1.35.6
- Version of Deno: 1.20.3 and 1.26.0
- Version of supabase-cli: 1.5.0

**Comment by soedirgo** [comment]
Thanks for reporting this @point-source, we pinned the Deno version a while ago because of an issue with [`deno bundle`](https://github.com/supabase/supabase/issues/7878). But since this is starting to be a blocker for some, we'll see if the latest version resolves this issue.

**Comment by point-source** [comment]
Of course! That said, many other cloud function providers allow the dev to either specify the runtime version or provide a list of acceptable versions. I feel like this would probably be important to ensure that deployed functions do not suddenly break if the supabase backend is updated. Or is a deployed function always run with the same deno version it was deployed with?

**Comment by soedirgo** [comment]
It's always run with the latest stable Deno version - this is the behavior of [Deno Deploy](https://deno.com/deploy), which we use under the hood.

**Comment by WithMyTeam** [comment]
Hello @soedirgo 

This version of deno works with Stripe in local dev?
because when I try to import Stripe 
`import Stripe from "https://esm.sh/stripe?target=deno&no-check";`

and serve It's fail

logs:
```
error: TS2345 [ERROR]: Argument of type '"CAA"' is not assignable to parameter of type 'RecordType'.
        this.#query(name, "CAA").then(({ ret }) => {
                          ~~~~~
    at https://deno.land/std@0.153.0/node/internal_binding/cares_wrap.ts:266:27

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'CAARecord'.
          (ret as Deno.CAARecord[]).forEach(({ critical, tag, value }) =>
                       ~~~~~~~~~
    at https://deno.land/std@0.153.0/node/internal_binding/cares_wrap.ts:267:24

TS2322 [ERROR]: Type '"CAA"' is not assignable to type 'RecordType'.
              type: "CAA",


... etc
```

**Comment by soedirgo** [comment]
You might need to use an earlier version of `stripe` - the latest version might be using a `std` version that's incompatible with the pinned Deno version used by the CLI.

**Comment by WithMyTeam** [comment]
I think it should have the possibility to choose his version of the deno runtime on supabase in a config file, is this envisaged?

**Comment by WithMyTeam** [comment]
I done tests.
effectively with the deno runtime version 1.21.1,  it's fails

but with the last version 1.26.0 it's works

it's possible to upgrade the version of deno to 1.26.0? or/and to add the possibility to add the runtime version of deno?

**Comment by soedirgo** [comment]
We don't plan to support setting the Deno version as that adds a point of failure. Maybe the solution right now is to use the latest Deno version and disable checks - I'll check this with the team.

**Comment by point-source** [comment]
Is the a workaround I can employ today to get my app working again until the team can review this?

**Comment by soedirgo** [comment]
Can you try this?

```ts
import { serve } from "https://deno.land/std@0.132.0/http/server.ts";
// append `&deno-std=0.132.0` on all esm.sh imports
import Plaid from "https://esm.sh/plaid@11.0.0?target=deno&deno-std=0.132.0";

serve(async (req) => {
  return new Response();
});
```

**Comment by WithMyTeam** [comment]
Hello @soedirgo 

When I try with &deno-std=0.132.0 for each libraries I import, it's works for me.

This is good progress 👍

**Comment by point-source** [comment]
@soedirgo your suggestion worked for my plaid lib import from esm.sh but did not work for my deno.land import of [Opine 2.3.3](https://deno.land/x/opine@2.3.3). This is expected behavior and would normally mean that Opine needs an update but that project has been moved to maintenance mode in favor of using express via deno 1.25's npm compatibility mode.

So now I have plaid working but Opine failing with the same error. My options are either ditch opine and lose an express-like syntax for my code wait until Supabase updates to at least deno runtime 1.25 so I can use express itself. Any other workaround ideas?

Just restating to posterity, it really seems like Supabase should just always match the current deno runtime version so that it behaves exactly the same as deno deploy. That way, all issues are deno issues instead of Supabase issues.

**Comment by soedirgo** [comment]
I was able to import Opine with `import Opine from "https://deno.land/x/opine@2.2.0/mod.ts"` - that seems like the closest version that works.

**Comment by point-source** [comment]
Good call! That does appear to work as far as running it. Now I'm hitting a function size limit when I try to deploy it to supabase. That's out of scope for this ticket though.

**Comment by soedirgo** [comment]
Good news - we've removed the Deno version pin in https://github.com/supabase/cli/pull/601! Can you check if your function can be deployed now? (You might need to update the CLI)

Here's the snippet I used to test this:

```ts
import { serve } from "https://deno.land/std@0.165.0/http/server.ts";
import Plaid from "https://esm.sh/plaid@12.0.0?target=deno&no-check";
import Stripe from "https://esm.sh/stripe@11.0.0?target=deno&no-check";
import Opine from "https://deno.land/x/opine@2.3.3/mod.ts";

console.log(Plaid, Stripe, Opine);

serve(async (req) => {
  try {
    return new Response();
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
    });
  }
});
```

**Comment by point-source** [comment]
Sure enough, that fixed it! Thanks @soedirgo :D
