### ISSUE TITLE
Add possibility to specify the minor version of PostgreSQL in /supabase/config.toml

### ISSUE THREAD

**Issue by Dizotoff** [supabase/cli#491]
# Feature request

Add possibility to specify the minor version of PostgreSQL

## Is your feature request related to a problem? Please describe.

My remote PostgreSQL version is 14.1, while the local is 14.3. Some of the ddl files I successfully apply locally don't work in remote.

## A clear and concise description of what you want and what your use case is.

I want to be able to set any version of my local so that it can match the remote. There is a setting for the major version number in `/supabase/config.toml` but no setting for the minor. 

## Describe the solution you'd like

Add `minor_version = N` setting to `/supabase/config.toml`  

## Additional context

![Screenshot 2022-09-29 at 15 07 20](https://user-images.githubusercontent.com/9533646/193239571-37376b8a-8937-4de7-b59f-71fca7aada46.png)

**Comment by soedirgo** [comment]
Hmm this might be difficult - we were able to get by with major versions because there's only 2 supported right now (13 & 14), but adding minor versions to the matrix makes this untenable. We also don't necessarily have an image for each minor version.

**Comment by sweatybridge** [comment]
While making the minor version configurable is difficult, it should be possible for us to sync up local Postgres version exactly with your hosted Postgres version. Would this sufficiently solve your use case?

**Comment by Dizotoff** [comment]
> While making the minor version configurable is difficult, it should be possible for us to sync up local Postgres version exactly with your hosted Postgres version. Would this sufficiently solve your use case?

This looks like a much lighter solution to my problem than I proposed. If it's possible to do, it would be fantastic.

**Comment by sweatybridge** [comment]
Here's the related issue for syncing postgres version https://github.com/supabase/cli/issues/389. I will close this ticket for now to focus on that one.
