### ISSUE TITLE
Missing `seed.sql` in new local project

### ISSUE THREAD

**Issue by BarakChamo** [supabase/cli#497]
# Bug report

## Describe the bug

After running `supabase init` and `supabase start`, I get the following error:
`Error: Error starting database: psql: error: /tmp/seed.sql: No such file or directory`

A `seed.sql` file is never created inside the `supabase` folder.

This happens after all containers are fetched and run and when the CLI is trying to run apply `seed.sql`.

## To Reproduce
Run `supabase init` and `supabase start` in a new project folder.

## Expected behavior

supabase should correctly initialize development environment.

## System information

- OS: macOS 12.4 running on M2 Mac 
- Version of Node.js: `v16.16.0`
- Version of Yarn: `1.22.19`

**Comment by BarakChamo** [comment]
Adding that the fix mentioned [here](https://github.com/supabase/cli/issues/277), creating a `seed.sql` file inside the `supabase` folder does not work.

**Comment by eeston** [comment]
To add to this, I seem to be getting the same error out of the blue after using the same `seed.sql` for a few weeks with no problems. It's kinda large (~3300 lines) but it's not caused any issues in the past.

macOS: 12.6
supabase: 1.6.0 (also 1.5.0 before I updated)
