### ISSUE TITLE
Gen types for schema other then `public`

### ISSUE THREAD

**Issue by jaredramirez** [supabase/cli#508]
# Feature request

## Is your feature request related to a problem? Please describe.

We use schemas heavily to organized our database. Currently it seems the `gen` command only generates types for the `public` schema. It would be great to be able to generate types for other schemas too.

## Describe the solution you'd like

Ability to generate types for other schemas.

**Comment by soedirgo** [comment]
This should be out now - let me know if it works!
```
supabase gen types typescript --local # uses `api.schemas` in `supabase/config.toml`
supabase gen types typescript --project-id abc-def-123 --schema public --schema private
```
