### ISSUE TITLE
"Applying migration" output corrupted

### ISSUE THREAD

**Issue by profiluefter** [supabase/cli#514]
# Bug report

## Describe the bug

The `supabase start` output is messed up.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new supabase project with a few migrations
2. Execute `supabase start`
3. See corrupted console output

## Expected behavior

Normal output where each migration overwrites the name of the previous migration in the console output.

## Screenshots

![grafik](https://user-images.githubusercontent.com/18028031/195377390-168def75-4488-4206-81b0-20c084cfa630.png)

## System information

- OS: Windows
- Browser (if applies) N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

I just tested that this bug was introduced in version 1.7.3. 1.7.2 works as expected.

**Comment by sweatybridge** [comment]
Hello, I will look into making the logs prettier tmr. A temporary workaround is redirect stderr to NUL or $null on PS.

```powershell
supabase start 2> $null
```
