### ISSUE TITLE
Generating types with postgis extension lead to file with lint errors.

### ISSUE THREAD

**Issue by pcardosolei** [supabase/cli#529]
# Bug report

## Describe the bug

When generating the Database Model via supabase cli if there is an postgis extension activate in its file the functions provided generate errors on the linter.

<img width="801" alt="Screenshot 2022-10-15 at 18 03 27" src="https://user-images.githubusercontent.com/10116142/196000066-8ad7926f-3876-445c-909e-f968a9599357.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- activate postgis extension on supabase.
- run supabase gen types typescript

## Expected behavior

functions that are more clear on the types.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. May I check if you installed postgis in `extensions` schema or created its own `postgis` schema?

**Comment by pcardosolei** [comment]
@sweatybridge hey. 

Just did this code on tableplus directly.

```
CREATE EXTENSION postgis;

SELECT AddGeometryColumn ('public','advertisements','geom',4326,'POINT',2);

```

**Comment by soedirgo** [comment]
Hey there, we just fixed this on our side - can you try regenerating your types?

**Comment by pcardosolei** [comment]
it is fixed with the latest update.

Will take a look at the comment. Thanks!
