### ISSUE TITLE
Injecting TS definitions is not working; responses are typed as any.

### ISSUE THREAD

**Issue by ivanbtrujillo** [supabase/cli#541]
# Bug report

## Describe the bug

Hi,

I'm trying to provide TS types to supabase but it is not working. Responses are typed as any. Seems that something between .from and .select is missing.

After generating the types of my remote database and passing it to createClient, Supabase always returns "any" as the type of the responses after querying. I followed this doc:

https://supabase.com/docs/reference/javascript/typescript-support

Thank you so much in advance for the support 🙏

## To Reproduce

1. Get types from my remote database:
```
supabase gen types typescript --project-id [my-id-was-here] > types/supabase.types.ts
```

Result:
```
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[]

export interface Database {
  public: {
    Tables: {
      appointments: {
        Row: {
          id: number
          professionalId: string
          customerId: string
          date: string
          status: string
          createdAt: string | null
          time: number
        }
        Insert: {
          id?: number
          professionalId: string
          customerId: string
          date: string
          status?: string
          createdAt?: string | null
          time: number
        }
        Update: {
          id?: number
          professionalId?: string
          customerId?: string
          date?: string
          status?: string
          createdAt?: string | null
          time?: number
        }
      }
      customers: {
        Row: {
          id: string
          createdAt: string | null
          phone: string | null
          credits: number
          taxId: string | null
          address: string | null
        }
        Insert: {
          id: string
          createdAt?: string | null
          phone?: string | null
          credits?: number
          taxId?: string | null
          address?: string | null
        }
        Update: {
          id?: string
          createdAt?: string | null
          phone?: string | null
          credits?: number
          taxId?: string | null
          address?: string | null
        }
      }
      products: {
        Row: {
          id: string
          credits: number | null
          description: string | null
          name: string
          price: number | null
          featured: boolean | null
          features: string[] | null
        }
        Insert: {
          id: string
          credits?: number | null
          description?: string | null
          name?: string
          price?: number | null
          featured?: boolean | null
          features?: string[] | null
        }
        Update: {
          id?: string
          credits?: number | null
          description?: string | null
          name?: string
          price?: number | null
          featured?: boolean | null
          features?: string[] | null
        }
      }
      professionals: {
        Row: {
          id: string
          licenseNumber: string
          meetLink: string
          shortDescription: string
          description: string
          taxId: string
          phone: string
          address: string
          tags: string[]
          createdAt: string | null
        }
        Insert: {
          id: string
          licenseNumber: string
          meetLink: string
          shortDescription: string
          description: string
          taxId: string
          phone: string
          address: string
          tags: string[]
          createdAt?: string | null
        }
        Update: {
          id?: string
          licenseNumber?: string
          meetLink?: string
          shortDescription?: string
          description?: string
          taxId?: string
          phone?: string
          address?: string
          tags?: string[]
          createdAt?: string | null
        }
      }
      profiles: {
        Row: {
          id: string
          firstName: string | null
          lastName: string | null
          referralSource: string | null
          role: string
          stripeCustomerId: string | null
        }
        Insert: {
          id: string
          firstName?: string | null
          lastName?: string | null
          referralSource?: string | null
          role?: string
          stripeCustomerId?: string | null
        }
        Update: {
          id?: string
          firstName?: string | null
          lastName?: string | null
          referralSource?: string | null
          role?: string
          stripeCustomerId?: string | null
        }
      }
      working_hours: {
        Row: {
          id: number
          professionalId: string
          day: string
          from: number
          to: number
          createdAt: string | null
        }
        Insert: {
          id?: number
          professionalId: string
          day: string
          from: number
          to: number
          createdAt?: string | null
        }
        Update: {
          id?: number
          professionalId?: string
          day?: string
          from?: number
          to?: number
          createdAt?: string | null
        }
      }
      working_hours_exceptions: {
        Row: {
          id: number
          professionalId: string
          date: string
          from: number
          to: number
          created_at: string | null
        }
        Insert: {
          id?: number
          professionalId: string
          date: string
          from: number
          to: number
          created_at?: string | null
        }
        Update: {
          id?: number
          professionalId?: string
          date?: string
          from?: number
          to?: number
          created_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
```

2. Create client and inject type definitions:
```
import { Database } from '@/types/supabase.types.ts'

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY = process.env.NEXT_PUBLIC_SUPABASE_KEY;
  
const supabase = createClient<Database>(URL!, KEY!);
```

3. When querying, the response type is "any":
<img width="607" alt="image" src="https://user-images.githubusercontent.com/6088653/196450935-de8ba924-41fc-4a61-ac9b-a25846eeccc5.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6088653/196450422-e0318b1c-3eba-4f2c-bb60-4fbd83784068.png">

I noticed it is typed when using ".from":
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/6088653/196451072-93475908-d992-4f72-b55d-67ebdb67813d.png">

But it is "any" when using ".select":
<img width="598" alt="image" src="https://user-images.githubusercontent.com/6088653/196451128-2574248d-84e8-4f84-91be-21df9415512f.png">

## Expected behavior

I would expect to have responses typed as expected, not as any.

## System information

- OS: macOS
- Version of supabase-js: ^2.0.0
- Version of Node.js: v16-14.0

**Comment by soedirgo** [comment]
Hey @ivanbtrujillo, can you upgrade `@supabase/supabase-js`? I think this is the same issue as https://github.com/supabase/supabase-js/issues/602

**Comment by grieblius** [comment]
Hello,

I can confirm I have the same issue with latest `"@supabase/supabase-js": "^2.0.4"`.

When using generated types it returns `any[]` and even do not validate that `anytable` does not exist in types:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/29752427/197328819-d6696daa-7636-4806-a2f7-24e462dd5e91.png">

When adding my custom types it returns `unknown[]`:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/29752427/197328917-c4212920-3270-45b3-ac25-f01d71fd4be1.png">

**Comment by grieblius** [comment]
FYI, I was generating types from local environment.
I've checked generated types and compared with other examples. There was no `Views` property.
In my case, manually adding `Views` property, fixes `any` issue:
```
    Views: {
      [_ in never]: never;
    };
```

<img width="542" alt="image" src="https://user-images.githubusercontent.com/29752427/197471004-f1a78188-d4e3-4ed8-a5a5-a082e36c51a0.png">

Also, now I understand that when migrating types from v1 to v2 I need to add custom types in the same structure as types are defined in generated types:
```
type AnyTable = {
  Row: {
    id: string;
    title: string;
  };
};
```

**Comment by soedirgo** [comment]
@grieblius can you try updating the CLI and restarting the local dev? IIRC the lack of `Views` was in an earlier version where the features weren't stable yet.

FYI passing type parameters in `.from()` is not supported - this may break at any time. The only supported type params are `Database` and `SchemaName` in `createClient()`/`SupabaseClient`/`PostgrestClient` and `Result` in `.returns()`.

**Comment by grieblius** [comment]
Oh, thank you, forgot to update `supabase` as it was installed as a global package..
That fixes the problem.

And thank you for information regarding `.from()` type parameters.

**Comment by soedirgo** [comment]
Closing this issue - feel free to comment if upgrading the client lib doesn't fix it, and we can reopen this.

**Comment by Frame1910** [comment]
I've got the exact same issue, however I'm running all the latest packages and I'm using it in an Angular project with a local DB container:

<img width="722" alt="Screenshot 2023-03-28 at 10 02 13 am" src="https://user-images.githubusercontent.com/22231370/228107758-4e142518-e60d-4fa0-bcee-92d697371dcf.png">

I've noticed the various PostgrestBuilder objects aren't noticing the typings, however the supabase client object is:

<img width="1009" alt="Screenshot 2023-03-28 at 10 03 32 am" src="https://user-images.githubusercontent.com/22231370/228107937-c9ba6e9f-5921-45dc-97de-3c4a276b58f5.png">

Any insight would be greatly appreciated.
