### ISSUE TITLE
Support `REDIRECT_URI` in external OAuth

### ISSUE THREAD

**Issue by mclean25** [supabase/cli#543]
# Bug report

I'm trying to get the Github Auth provider to work with my Supabase instance running locally on my machine. It seems like the `redirect_uri` isn't being allowed/set based on the error I'm getting from Github(?). I'm continually end up redirected to the following URL: http://localhost:3000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.

I'm using ngrok to port the Github Auth to my local server. The actual custom domain for ngrok has been modified for privacy.

My supabase/config.toml:
```
additional_redirect_urls = ["https://localhost:3000", "http://localhost:54321/auth/v1/callback", "https://my-domain.ngrok.io"]
# ...
[auth.external.github]
enabled=true
client_id="my-client-id"
secret="my-secret"
redirect_uri="https://my-domain.ngrok.io/auth/v1/callback"
```

In my Github OAuth bot, I have the "Authorization Callback URL" set to https://my-domain.ngrok.io/auth/v1/callback.

The reason I'm using the `redirect_uri` is from examining the [gotrue docs](https://github.com/supabase/gotrue#external-authentication-providers). Is this actually supported?

## System information
- Supabase CLI version 1.8.4

**Comment by soedirgo** [comment]
Hmm I don't think we expose `auth.external.github.redirect_uri` on the CLI config yet.
