### ISSUE TITLE
clean up completion command

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#55]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10214025/138456026-95abbaea-d9bc-4885-8deb-f4dd6e00955a.png">

**Comment by soedirgo** [comment]
The completions are now set up on install:

https://user-images.githubusercontent.com/31685197/140875371-2f9ed130-3e3b-4f0c-bc4d-b893d224572d.mov

Probably no harm done leaving it be, as e.g. GitHub does: https://cli.github.com/manual/gh_completion
