### ISSUE TITLE
Option to change Supabase URL for Supabase Studio

### ISSUE THREAD

**Issue by ccssmnn** [supabase/cli#551]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to setup an ephemeral development environment with Gitpod to speed up our workflow. With Gitpod, everything runs in a cloud instance with Docker access. Ports are made available through subdomains: `localhost:54321`➡️`https://54321-WORKSPACE.gitpod.io`. Accessing Supabase Studio gets stuck after selecting the Default Project because it is configured to search on `localhost`. The browser console shows failed requests to http://localhost:54321/rest/v1/.

## Describe the solution you'd like

I would love to configure the Supabase URL for my local Supabase Studio. An option for the `supabase start` command would be great. Maybe `supabase start --supabase-url=https://custom-domain.com

## Describe alternatives you've considered

You can make this work when using Gitpods VS-Code extension. This way, all the ports are forwarded through localhost and the assumptions of the CLI still stand. This adds some friction to the process, especially when using Gitpod for reviewing PRs or onboarding people.

**Comment by sweatybridge** [comment]
I believe this is the same issue as https://github.com/supabase/cli/issues/270. Will close this as dupe.
