### ISSUE TITLE
Local & Hosted Postgrest db-config Parity

### ISSUE THREAD

**Issue by Garett-MacGowan** [supabase/cli#553]
# Feature request

## Is your feature request related to a problem? Please describe.

When trying to programatically set up my project schemas & configuration, I expect the default local development settings to be the same as the hosted settings.

Currently, it seems that [db-config](https://postgrest.org/en/stable/configuration.html#db-config) is disabled in local development, meaning I cannot programmatically add & test changing the schemas exposed to the API. Instead, I am forced to test this functionality in my staging environment 👎.

I don't want to rely on the studio for changing configurations, hence the need for programmatically changing it.

## Describe the solution you'd like

Ideally, [db-config](https://postgrest.org/en/stable/configuration.html#db-config) (and all other settings) default to the same values as the hosted version of Supabase.

## Describe alternatives you've considered

Alternatively, maybe additionally, expose [db-config](https://postgrest.org/en/stable/configuration.html#db-config) as an option to `config.toml`.

## Additional context

**Simplified Example**
The below fails to work on local, assuming `private_rpc` is not set in the `schemas` list under [API] in `config.toml`

`check_postgrest_db_schemas()` would be uncallable in API due to schema not being exposed.

Response would be: `The schema must be one of the following: public, storage, graphql_public`
```
-- Create schema for holding private RPC.
CREATE SCHEMA private_rpc;

ALTER ROLE authenticator SET pgrst.db_schemas = "public, storage, private_rpc";
NOTIFY pgrst, 'reload config';
NOTIFY pgrst, 'reload schema';

CREATE OR REPLACE FUNCTION private_rpc.check_postgrest_db_schemas()
RETURNS TEXT AS $_$
    BEGIN
        RETURN response FROM (
            SELECT unnest(r.rolconfig) AS response
            FROM pg_catalog.pg_roles r
            WHERE r.rolname = 'authenticator'
        ) AS response
        WHERE response.response LIKE '%pgrst.db_schemas%';
    END $_$ 
volatile security definer language plpgsql;

-- Grant permissions on private_rpc schema to service_role so that auto generated API can work with it, given a service key.
GRANT USAGE ON SCHEMA private_rpc TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA private_rpc TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres, supabase_admin IN SCHEMA private_rpc GRANT ALL ON
ROUTINES TO service_role;
```

Perhaps I'm missing something or my dev process is wrong. I don't know why this wouldn't have come up yet.

**Comment by Garett-MacGowan** [comment]
Upon [further inspection](https://postgrest.org/en/stable/configuration.html#list-of-parameters) the default value is set to `True`, so maybe there is something else going on on my end?

I dug through the code and found the exact spot that may or may not need updating. If we add `PGRST_DB_CONFIG` [here](https://github.com/supabase/cli/blob/676e50bb967e9316febb3efce4dfb982d21c91f5/internal/start/start.go#L484), it may work?

It'd be awesome if someone else is able to reproduce my troubles, or if it is just me messing up somewhere.

**Comment by Garett-MacGowan** [comment]
There is a note [here](https://postgrest.org/en/stable/configuration.html#in-database-configuration) that says "When using both the configuration file and the in-database configuration, the latter takes precedence". There is no note that I can see regarding the precedence of environment variable configurations.

This makes me think that environment variables might take precedence above all, causing my problems. Based on the fact that `PGRST_DB_SCHEMAS` is always defined [here](https://github.com/supabase/cli/blob/676e50bb967e9316febb3efce4dfb982d21c91f5/internal/start/start.go#L484), it would explain why I can't get anything to work except by specifying the schemas inside `config.toml`.

**Comment by sweatybridge** [comment]
Hi @Garett-MacGowan, thanks for the detailed description. This is a good enhancement to have. There are a few things that we need to match between local and hosted, including the service config you mentioned and the [postgres version](https://github.com/supabase/cli/issues/389) here.

**Comment by Garett-MacGowan** [comment]
> Hi @Garett-MacGowan, thanks for the detailed description. This is a good enhancement to have. There are a few things that we need to match between local and hosted, including the service config you mentioned and the [postgres version](https://github.com/supabase/cli/issues/389) here.

Awesome, thanks for the fix.
