### ISSUE TITLE
Wrong typings for single column rpc

### ISSUE THREAD

**Issue by jsbrain** [supabase/cli#558]
# Bug report

## Describe the bug

Typings for rpc functions with single column table are incorrect.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create function:

```sql
create
or replace function public.user_tenants () returns table (tenant_id uuid) as $$
begin
  return query
  select
    tu.tenant_id
  from
    tenant_users tu
    inner join auth.users u on u.id = tu.user_id
    inner join tenants t on t.id = tu.tenant_id
  where
    tu.user_id = auth.uid();
end
$$ language plpgsql stable security definer
set
  search_path = public,
  pg_temp;
```

Generating types results in:

```ts
interface Database {
  // ...
  Functions: {
    user_tenants: {
      Args: Record<PropertyKey, never>;
      Returns: string;
    };
  };
}
```

While rpc result data is:

```ts
[
  {
    tenant_id: 'id1',
  },
  {
    tenant_id: 'id2',
  },
];
```

## Expected behavior

```ts
interface Database {
  // ...
  Functions: {
    user_tenants: {
      Args: Record<PropertyKey, never>;
      Returns: Record<string, unknown>[];
    };
  };
}
```

## System information

- OS: macOS 11.6.3
- Browser: Chrome
- Version of supabase-js: 2.0.4
- Version of Node.js: 16.17.1

**Comment by jsbrain** [comment]
I'm also curious if there is a way to actually infer the actual property keys while generating the types so the typings would look like the result object, e.g.:

```ts
interface Database {
  // ...
  Functions: {
    user_tenants: {
      Args: Record<PropertyKey, never>;
      Returns: { tenant_id: string }[];
    };
  };
}
```

**Comment by soedirgo** [comment]
Sorry for the super late response! This was fixed in https://github.com/supabase/postgres-meta/pull/423 which have been deployed.
