### ISSUE TITLE
Hide the database folder (for now)

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#56]
# Chore

## Describe the chore

The database folder/diff will be useful once it's fully documented, but for now it's a bit confusing if it does anything. Let's hide it until we have the `migrations` flow working

**Comment by soedirgo** [comment]
Just to be clear, is this about hiding `supabase/database` declarative dump?

**Comment by kiwicopple** [comment]
yeah I think for this version it's too confusing - I though it would be useful, but I think until we have a way of pushing local changes to the database it's a bit hard to understand the direction where the folders are going. We should keep the code, just comment it out for now
