### ISSUE TITLE
Unknown or unexpected option: project-id when using the cli to generate types

### ISSUE THREAD

**Issue by isaacfink** [supabase/cli#566]
# Bug report

When running the cli to generate types I get this error
`Unknown or unexpected option: project-id`

## Describe the bug

Can't generate types from the cli

## To Reproduce

run the following in a project
`npx supabase gen types typescript --project-id "project-link" --schema public > ./src/lib/types/generated.ts`

## Expected behavior

types should be generated

**Comment by sweatybridge** [comment]
Hi @isaacfink, could you check the version of cli you are running?

The flag should be available after updating via npm.

**Comment by isaacfink** [comment]
@sweatybridge that was it I feel stupid now, closing this issue
