### ISSUE TITLE
PGCRYPTO functions don't exist when seeding local database

### ISSUE THREAD

**Issue by corasan** [supabase/cli#568]
# Bug report

## Describe the bug

I just upgraded to the latest version of the CLI (v1.11.3) and my previous seed file stopped working (coming from v1.6.x) because it's not recognizing the pgcrypto functions even though the extension is added successfully. To be more specific, I am trying to insert new users and I'm using `crypt('testing123', gen_salt('bf'))` in the password field but I get this error: `ERROR: function gen_salt(unknown) does not exist (SQLSTATE 42883)`.

## To Reproduce

1. In the seed file add:
```
insert into auth.users (instance_id, id,aud,"role",email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,is_super_admin,created_at,updated_at,phone,phone_confirmed_at,confirmation_token,email_change,email_change_token_new,recovery_token) values
	('00000000-0000-0000-0000-000000000000'::uuid,'f76629c5-a070-4bbc-9918-64beaea48848'::uuid,'authenticated','authenticated','test@testmail.com',crypt('testing123', gen_salt('bf')),now(),'{"provider": "email", "providers": ["email"]}','{"name": "Test"}',FALSE,'2022-02-11 21:02:04.542','2022-02-11 21:02:04.542',NULL,NULL,'','','','')
on conflict (id) do nothing;
```
3. Run `supabase start` or `supabase db reset`

## Expected behavior

I expect the database to be seeded after running `supabase start` or `supabase db reset`

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-cli: 1.11.3
- Version of Node.js: v16.17.1

## Additional context

I downgraded to v1.7.2 and the seed works fine. It seems like v1.7.3 is the one breaking it.

**Comment by sweatybridge** [comment]
Hi @corasan, I'm unable to reproduce this issue on a new project. What I did was

```bash
supabase init
# update supabase/seed.sql with your script
supabase start
```

Could you provide more details to help debug further:
1. Are you using pg13 or pg14?
2. Is pgcrypto installed to `extensions` schema?
3. Do you have any migration file that changes the `search_path`?

**Comment by corasan** [comment]
1. I am using pg14
2. pgcrypto is installed in the extensions schema. If I query `select * from pg_extension;` I see it listed and if I check the enabled extensions in studio I see it listed there too.
3. I looked up `search_path` in the entire project but I only see `search_path` mentioned in the migration file generated by running `supabase db remote commit`(`SELECT pg_catalog.set_config('search_path', '', false);`) and config.toml.

I could try to create a new project from scratch and move things over if this is some weird edge case, but it is weird that the seed stops working after version v1.7.3.

**Comment by corasan** [comment]
### Update

@sweatybridge after trying to move things over to the newly created project I discovered that my original migration file from remote DB (...xxx_remote_commit.sql) was the cause of the issue. The only difference I noticed is at the end of the file there's a `RESET ALL;` line added.

**Comment by sweatybridge** [comment]
I see. Thank you for clarifying.

The problem you ran into had the same root cause as #507. We added a fix in v1.7.4 but unfortunately didn't handle the edge case with existing `_remote_commit.sql` generated by older clients.

Essentially we have to be careful with session configs now that we are running all migrations over the same pg connection. We should use `set local ...` instead of `set ...` statements so that the configs are scoped to a single transaction only.

For future reference, the workaround is to add `RESET ALL;` to the end of the initial migration file like what you've done.

**Comment by corasan** [comment]
Another thing I forgot to mention before is that I only noticed the `RESET ALL;` at the end of the migration file because I ran `supabase db remote commit` again to see what was different.

**Comment by jaocfilho** [comment]
How did you solved it?

I'm facing the same problem, I'm using supabase 1.75.3 and suddenly my seeding stop working.
`ERROR: function gen_random_bytes(integer) does not exist (SQLSTATE 42883)`

I have a custom function called `generate_random_hex` thats uses `gen_random_bytes`

```
CREATE OR REPLACE FUNCTION public.generate_random_hex()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  random_bytes BYTEA;
BEGIN
  -- Generate random bytes
  random_bytes := gen_random_bytes(32);

  -- Convert bytes to hex string
  RETURN encode(random_bytes, 'hex');
END;
$function$
;
```

**Comment by sweatybridge** [comment]
Hi @jaocfilho could you try `npx supabase@beta start`? It might be related to a recent fix we released.

**Comment by jaocfilho** [comment]
@sweatybridge The error persists.
