### ISSUE TITLE
bug in gen types in Supabase CLI 

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/cli#570]
# Bug report

I have encountered a problem generating types with the CLI
`supabase gen types typescript --db-url postgresql://postgres[PASSWORD]@db.[DB-ID].supabase.co:5432/postgres`

First this fails with 
`Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
Why would Docker need to be running to generate types from a remote db? Fair enough if it does.. but this requirement is not in the docs:
<img width="927" alt="CleanShot 2022-10-31 at 13 02 40@2x" src="https://user-images.githubusercontent.com/11864025/198934848-ae0b5dea-e5d8-47e0-b1e7-daef68fe81a8.png">

And these docs are in any case incorrect. There are no `--project-id` or `schema` flags..

If I start Docker and Supabase and run `supabase gen types typescript --db-url postgresql://postgres[PASSWORD]@db.[DB-ID].supabase.co:5432/postgres`
then the error is: `Error: error running container`

## System information

- OS: macOS13
- Version of supabase-cli: 1.6.0
- Version of Node.js: 18.12.0

## Additional context

Overall the Supabase Docs are letting the product down badly. They are inconsistent on don't exist at all. I urge you to please hire someone to maintain the docs full-time. It's no good building a fantastic product if we can't quickly figure out how to use it.

**Comment by sweatybridge** [comment]
Hello @fergusmeiklejohn, could you try updating the CLI to the latest version? I will also update the docs to include the min supported CLI version as a prerequisite.

closed as duplicate #566

**Comment by fergusmeiklejohn** [comment]
Right thanks very much! So the first problem is with Homebrew! I installed the supabase cli with brew, and there is some very weird bug in homebrew where it's requiring me to install a version of XCode which hasn't been released. See screengrab. 
<img width="887" alt="CleanShot 2022-11-01 at 09 20 29@2x" src="https://user-images.githubusercontent.com/11864025/199138999-1b8600f1-c95b-451f-9ada-f439521495c8.png">

Maybe we should remove reference to HomeBrew in the docs and replace with `npx` ? https://supabase.com/docs/guides/cli
I'm a fan of npx, we get the latest version and we don't need to bother with global installs

**Comment by fergusmeiklejohn** [comment]
I'm getting there with this but it's still in error.
First if I try to use the --db-url flag I get an error: `Error: URL is not a valid Supabase connection string.` but the docs don't indicate what a valid connection string should look like.
But then I realised that I can use --project-id anyway which is much better than --db-url, but there I'm getting a long way along the path but still getting an error: 
```bash
Error: failed to retrieve generated types: {"message":"Failed to generate TypeScript types: permission denied for schema graphql","errorEventId":"4e76f0e66de8413683f1ea42c4d5b2ff"}
```

**Comment by soedirgo** [comment]
> Maybe we should remove reference to HomeBrew in the docs and replace with npx ?

Yeah, I think we can add `npm`/`npx` as one of the installation options in that page.

> but still getting an error

Hmm this looks like a bug in our Management API - I'll take a look at this and loop back here.

**Comment by fergusmeiklejohn** [comment]
Local works:
`npx supabase gen types typescript --local > DatabaseTypes.ts`
🥳

Interesting that I'm using fig in the terminal which gives me autocomplete and `--project-id` is not offered isn't only
```bash
--db-url
--debug
--help
--local
```
npx supabase is installing Supabase CLI 1.11.3

**Comment by soedirgo** [comment]
Hey @fergusmeiklejohn! Sorry to follow up on an old issue - we've since updated the docs to default to using `npm`/`npx` as the installation method.

Regarding the `permission denied for schema graphql` error, this looks like an issue with that specific project - feel free to file a support ticket if you're still hitting into that and we'll get right on it.
