### ISSUE TITLE
TS: Inferred types are incorrect

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/cli#574]
# Bug report

## Describe the bug
 See the below screenshot. The left-hand column is the code, the right-hand column shows what Supabase is returning.
In the code you can see that `presentation.title` is a TS error because `presentation` is inferred to be an array. The inferred types are in the comment below the function.
In the right-hand column, you can see that Supabase returns `presentation` as an object, which is correct because the join is on primary keys so `presentation` is only ever going to be one row:

Gist of the exported [types](https://gist.github.com/fergusmeiklejohn/1f0f65a4e45fde71188557f8cf727c3f)

<img width="1684" alt="CleanShot 2022-11-02 at 12 18 30@2x" src="https://user-images.githubusercontent.com/11864025/199395339-6696d2cc-f337-4118-b957-7811ffbe6652.png">

## System information

- Supabase CLI: 1.11.3
- @supabase/supabase-js: 2.0.5

**Comment by fergusmeiklejohn** [comment]
I'm finding various interesting type inference bugs. The type inferences are forcing me to write *better* query strings, which is good. I mean that various string possibilities will return the data but often the type system wants me to use one of them.
I keep finding strange bugs though, like for example the type system will insist that a property doesn't exist on a type when it does exist and the type system seems to show it existing. 
`Property 'organisations' does not exist on type '{ organisations: ({ id: string; } & { name: string; })...`

**Comment by fergusmeiklejohn** [comment]
Another seeming TS inference bug: how can `id` be undefined? It's a required field in every row. It cannot ever be undefined.  If there is no error (I'm throwing if there is an error fetching from Supabase) then id must be defined.
<img width="373" alt="CleanShot 2022-11-16 at 09 37 01@2x" src="https://user-images.githubusercontent.com/11864025/202062135-5a57f2c4-cf2b-4885-856f-97bd8955be9b.png">

**Comment by soedirgo** [comment]
This should be resolved by https://github.com/supabase/cli/pull/1148
