### ISSUE TITLE
Supabase auto-generated types appear to be incorrect for timestampz

### ISSUE THREAD

**Issue by CharlesFJWilliamson** [supabase/cli#576]
# Bug report

## Describe the bug

When working with a field that is of type timestampz, the auto-generated types return string as the type for the field, whereas the database/API will only accept date objects that match the expected format.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new table
2. Create a property called date, with type timestampz
3.  Auto-generate the types, and confirm that it returns type string for that property
4. Try to submit a string via the API, and get an error back stating that the type submitted is unexpected

## Expected behavior

The auto-generated types and the types accepted by the API to align.

## System information

MacOS. I'm using Supabase >=1.8.1 as per the documentation, and running the auto-generated types using npx Supabase gen types .......

**Comment by soedirgo** [comment]
Hey @CharlesFJWilliamson, there isn't an easy way to assert the string matches the required timestamp format - it is [*possible*](https://spin.atomicobject.com/2017/06/19/strongly-typed-date-string-typescript/), but it's difficult to use and maintain.

In general, it isn't feasible to ensure that all data format requirements are caught at build time - e.g. if you have a `text` column with a `check` that it must be alphanumeric.
