### ISSUE TITLE
`numeric` type in Postgres is generated as `number` - Precision is lost

### ISSUE THREAD

**Issue by johanneskares** [supabase/cli#582]
# Bug report

## Describe the bug

The `numeric` type in Postgres is generated as Typescript `number,` making it very hard to set numbers beyond the javascript numbers precision (Number MAX_SAFE_INTEGER) which is very common in Blockchain applications.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with a numeric type
2. Generate types with supabase CLI 1.11.4 & `supabase gen types typescript`
3. Update or insert a row with 
```
await supabase.from("test").insert({
    test: 900719925474099228394847584,
})
```
## Expected behavior

Number in Database should have full precision. Inspect Dashboard, the number doesn't have the full precision

## System information

- CLI Version 1.11.4

## Possible solution

Generate the `numeric` Postgres Type as `string` in Typescript. Then I can do:

```
await supabase.from("test").insert({
    test: "900719925474099228394847584",
})
```

## Current Workaround
```
await supabase.from("test").insert({
    test: "900719925474099228394847584" as unknown as number,
})
```

**Comment by johanneskares** [comment]
Related issue: https://github.com/PostgREST/postgrest/issues/2586

**Comment by soedirgo** [comment]
Closing this as we're simply following what's returned by PostgREST
