### ISSUE TITLE
supabase db reset error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by MaxAst** [supabase/cli#583]
# Bug report

## Describe the bug

After running `supabase db remote commit`, I ran `supabase db reset` as was suggested by the CLI. This led to the following error:
```
Resetting database...
Initialising schema...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10129f500]

goroutine 1 [running]:
github.com/supabase/cli/internal/db/reset.WaitForHealthyDatabase({0x101aa4db8, 0x140001a0008}, 0x140001a0008?)
        /home/runner/work/cli/cli/internal/db/reset/reset.go:165 +0x150
github.com/supabase/cli/internal/db/reset.RestartDatabase({0x101aa4db8, 0x140001a0008})
        /home/runner/work/cli/cli/internal/db/reset/reset.go:148 +0xd0
github.com/supabase/cli/internal/db/reset.Run({0x101aa5058, 0x140003822c0}, {0x101aa7048, 0x102134098}, {0x0, 0x0, 0x0})
        /home/runner/work/cli/cli/internal/db/reset/reset.go:44 +0x2e0
github.com/supabase/cli/cmd.glob..func9(0x1020df140?, {0x101680b39?, 0x0?, 0x0?})
        /home/runner/work/cli/cli/cmd/db.go:148 +0xac
github.com/spf13/cobra.(*Command).execute(0x1020df140, {0x102134098, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x1020dcec0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/supabase/cli/cmd.Execute()
        /home/runner/work/cli/cli/cmd/root.go:50 +0x2c
main.main()
        /home/runner/work/cli/cli/main.go:8 +0x20
```

When adding the `--debug` flag, I can see that it is caused by the pg_graphql extension:
```
2022/11/06 15:02:02 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42883","Message":"function graphql.get_built_schema_version() does not exist","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"parse_func.c","Line":2444,"Routine":"LookupFuncWithArgs","UnknownFields":null}
```

## To Reproduce

I have the following extensions installed (Thought this info may be useful, given that a previous [issue](https://github.com/supabase/cli/issues/437) I ran into was solved by toggling off the pg_graphql extension):
<img width="1193" alt="Screenshot 2022-11-06 at 14 55 58" src="https://user-images.githubusercontent.com/13224092/200174859-1fa22d48-ec68-496a-bd89-c138968dea2f.png">

## Expected behavior

That the `supabase db reset` runs successfully.

## Screenshots

<img width="911" alt="Screenshot 2022-11-06 at 14 53 07" src="https://user-images.githubusercontent.com/13224092/200174729-f54fb96b-5149-4a30-b255-5110669f443f.png">

## System information

- OS: macOS
- Version of supabase-cli: 1.11.7

## Additional context

I tried it again after toggling the pg_graphql extension back on again, but ran into the same error

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. This problem is due to postgres image version mismatch between hosted and local. It should be fixed in latest version.
