### ISSUE TITLE
Supabase CLI fails to create a local copy of remote database

### ISSUE THREAD

**Issue by Evaldas-B** [supabase/cli#588]
# Bug report

## Describe the bug
Running `supabase db remote commit` creates a migration that later fails when running `supabase start` with provided error:

    Applying migration 20221109095547_remote_commit.sql...
    Error: ERROR: function graphql.get_schema_version() does not exist (SQLSTATE 42883)
    At statement 89:
    
    
    --
    -- Name: FUNCTION "get_schema_version"(); Type: ACL; Schema: graphql; Owner: supabase_admin
    --
    
    GRANT ALL ON FUNCTION "graphql"."get_schema_version"() TO "postgres";

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new supabase project from supabase dashboard
2. Add a simple table with couple rows
3. Create new directory and run `supabase init`
4. Link local config to remote project `supabase link --project-ref $PROJECT_ID --password $PASSWORD`
5. Create a migration that represents the remote state `supabase db remote commit --password $PASSWORD`
6. Run supabase locally `supabase start`

## Expected behavior

Local environment should start with the same schema and data as the remote

## Screenshots
![image](https://user-images.githubusercontent.com/53705834/200808923-afca04d9-48fc-4377-a791-38b43c68f06a.png)

## System information

- OS: [e.g. macOS, Windows]
- Version of  Docker: 4.13.1
- Version of supabase-cli: 1.11.7
- Version of Node.js: v18.12.1

## Additional context

Tried disabling and enabling `PG_GRAPHQL` extension

**Comment by sweatybridge** [comment]
Thanks for the detailed bug report. This problem is due to postgres image version mismatch between hosted and local. It should be fixed in latest version.
