### ISSUE TITLE
Expose pgadmin

### ISSUE THREAD

**Issue by kiwicopple** [supabase/cli#59]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd love to view the running database cluster with pgadmin. As I was jumping between branches I found that I wanted to look at all the database in the cluster. 

## Describe the solution you'd like

We're already using pgadmin for diff'ing - https://github.com/supabase/cli/blob/fb935d1e4e6f25004e8cae2825ec317494474fcb/internal/utils/utils.go#L50

Does this fork include the UI? If so, can we please expose it on a new port?

## Additional context

It would be awesome if it was pre-populated with the connection data so that they can login and see the cluster. Also I think pgadmin requires an admin username / password - could also be postgres/postgres

**Comment by sweatybridge** [comment]
I'm inclined to follow unix philosophy of making one tool do one thing well. So not really in favour of exposing pgadmin even if we can.

If there's demand for a more advanced admin interface, we should also consider lightweight alternatives like adminer. Currently it seems that studio's UI and sql editor satisfy most common use cases.

Feel free to open a new discussion for alternate admin ui.
