### ISSUE TITLE
relation "public.employees" does not exist

### ISSUE THREAD

**Issue by izayl** [supabase/cli#599]
# Bug report

## Describe the bug

use the example of [document](https://supabase.com/docs/guides/cli/local-development), cannot successfully start .

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a empty fold
2. run `supabase init`
3. add the following code to `seed.sql`
4. run `supabase start`

```sql
create table employees (
  id integer primary key generated always as identity,
  name text
);
insert into public.employees (name)
values ('Erlich Backman'),
  ('Richard Hendricks'),
  ('Monica Hall');
```

## Expected behavior

the local server start successfully.

## Screenshots

```sh
$ supabase start
Seeding data supabase/seed.sql...
Error: ERROR: relation "public.employees" does not exist (SQLSTATE 42P01)
Try rerunning the command with --debug to troubleshoot the error.
```

## System information

- OS: macOS
- Version of supabase-cli: 1.12.2
- Version of Node.js: 16.13.0

**Comment by sweatybridge** [comment]
Hi @izayl, have you tried creating the employees table in a new migration file? I believe this is working as [documented](https://supabase.com/docs/guides/cli/local-development#make-database-changes) because `seed.sql` is designed to contain only data inserts/updates/deletes. DDL statements like `create table` should be added via new migration.

**Comment by izayl** [comment]
@sweatybridge yes, I've tried to use a new migration to `insert`, but still, it not work.

**Comment by izayl** [comment]
and it works if there only `create table` and without `insert`

**Comment by sweatybridge** [comment]
Just to be clear, our documentation suggests creating 2 separate files

- `supabase/20220730063745_add_employees.sql`
```
create table employees (
  id integer primary key generated always as identity,
  name text
);
```

- `supabase/seed.sql`
```
insert into public.employees (name)
values ('Erlich Backman'),
  ('Richard Hendricks'),
  ('Monica Hall');
```

After that `supabase start` works for me.

**Comment by izayl** [comment]
@sweatybridge you're right, thanks for your help!
