### ISSUE TITLE
supabase gen types different order on my machine vs github actions

### ISSUE THREAD

**Issue by WesleyYue** [supabase/cli#602]
# Bug report

## Describe the bug

Trying to implement CI in Github Actions for verifying types have been generated and committed in git by following [this](https://supabase.com/docs/guides/cli/managing-environments#deploy-a-migration).

I am running into a weird issue where the order of the fields get generated slightly differently between my machine and github actions and it's not clear why. I can use a custom script to deep diff the two but this breaks the documented git diff method. I have verified that both cli versions are 1.12.2

## To Reproduce

On local machine:
    1. supabase link --project-ref $PROD_PROJECT_ID
    2. supabase db remote commit
    3. supabase db reset
    4. supabase gen types typescript --local > ../src/types/supabase/index.ts

On github actions:
```name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.12.2

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > ../src/types/supabase/index.ts
          cd ../src/types/supabase

          if [ "$(git diff --ignore-space-at-eol index.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
```

## Expected behavior

Expect the index.ts type file to be identical in both.

**Comment by TedAce** [comment]
The same issue here, tried many different things but with no luck. On the local machine, I'm using a prettier but the type file is ignored, also tried with no prettier on local env at all, using a prettier on remote - still the same.

Can't figure out a solution.

Run supabase gen types typescript --local > DatabaseDefinitions.ts
Detected uncommitted changes after build. See status below:
diff --git a/DatabaseDefinitions.ts b/DatabaseDefinitions.ts
index e4aa507..a[9](https://github.com/User/project/actions/runs/3468842892/jobs/5795122551#step:5:10)dadd0 [10](https://github.com/User/project/actions/runs/3468842892/jobs/5795122551#step:5:11)0644
--- a/DatabaseDefinitions.ts
+++ b/DatabaseDefinitions.ts
@@ -217,41 +217,44 @@ export interface Database {
       }
       orders: {
         Row: {
-          id: string
           user_id: string
           total: number
+          created_at: string
+          id: string
           payment_method: string
           total_items: number
           cart_id: string
           product_number: number
           total_tickets: number
-          created_at: string
         }
         Insert: {
-          id?: string
           user_id: string
           total: number
+          created_at?: string
+          id?: string
           payment_method: string
           total_items: number
           cart_id: string
           product_number: number
           total_tickets: number
-          created_at?: string
         }
         Update: {
-          id?: string
           user_id?: string
           total?: number
+          created_at?: string
+          id?: string
           payment_method?: string
           total_items?: number
           cart_id?: string
           product_number?: number
           total_tickets?: number
-          created_at?: string
         }
       }
       tickets: {
         Row: {
+          user_id: string
+          product_number: number
+          created_at: string
           id: string
           order_id: string
           tag1: number
@@ -259,[11](https://github.com/User/project/actions/runs/3468842892/jobs/5795122551#step:5:12) +262,11 @@ export interface Database {
           tag3: number
           tag4: number
           tag5: number
-          user_id: string
-          product_number: number
-          created_at: string
         }
         Insert: {
+          user_id: string
+          product_number: number
+          created_at?: string
           id?: string
           order_id: string
           tag1: number
@@ -[27](https://github.com/User/project/actions/runs/3468842892/jobs/5795122551#step:5:28)1,11 +274,11 @@ export interface Database {
           tag3: number
           tag4: number
           tag5: number
-          user_id: string
-          product_number: number
-          created_at?: string
         }
         Update: {
+          user_id?: string
+          product_number?: number
+          created_at?: string
           id?: string
           order_id?: string
           tag1?: number
@@ -[28](https://github.com/User/project/actions/runs/3468842892/jobs/5795122551#step:5:29)3,9 +286,6 @@ export interface Database {
           tag3?: number
           tag4?: number
           tag5?: number
-          user_id?: string
-          product_number?: number
-          created_at?: string
         }
       }
     }
Error: Process completed with exit code 1.

**Comment by soedirgo** [comment]
Hmm, I thought that was fixed by https://github.com/supabase/postgres-meta/pull/380, but I guess that doesn't cover columns.

**Comment by loiclouvet** [comment]
Having the same issue after doing a migration altering a column type.
```
ALTER TABLE addresses
    ALTER COLUMN zip_code TYPE varchar(5);
```
Diff result btw local / ci :
```
           country: string
-          zip_code: string
           created_by: string
           provider_id: number | null
+          zip_code: string
```

**Comment by soedirgo** [comment]
There's a PR to fix this, but there's one caveat: columns will be sorted alphabetically, which may or may not be desirable. E.g. instead of:

```ts
{
  id: string
  user_id: string
  total: number
  created_at: string
  payment_method: string
  total_items: number
  cart_id: string
  product_number: number
  total_tickets: number
}
```

You'd get:

```ts
{
  cart_id: string
  created_at: string
  id: string
  payment_method: string
  product_number: number
  total: number
  total_items: number
  total_tickets: number
  user_id: string
}
```

Is this desirable?

Worth noting that Postgres stores the column ordering so it's possible to have consistent column order *within* a database, though it may need more work to make it consistent *across* databases (e.g. local vs. staging vs. prod). So maybe the easy solution here is to use alphabetic ordering for now, and if enough folks want to preserve the column order, we can do that in the next major version of the CLI. Wdyt?

**Comment by loiclouvet** [comment]
> Worth noting that Postgres stores the column ordering so it's possible to have consistent column order within a database, though it may need more work to make it consistent across databases (e.g. local vs. staging vs. prod). So maybe the easy solution here is to use alphabetic ordering for now, and if enough folks want to preserve the column order, we can do that in the next major version of the CLI. Wdyt?

Sounds good to me !

**Comment by WesleyYue** [comment]
> Worth noting that Postgres stores the column ordering so it's possible to have consistent column order within a database, though it may need more work to make it consistent across databases (e.g. local vs. staging vs. prod). So maybe the easy solution here is to use alphabetic ordering for now, and if enough folks want to preserve the column order, we can do that in the next major version of the CLI. Wdyt?

Alphabetic sounds good. I would also go as far as to say none of the use cases for the comments on this issue need the order to be the same as the postgres column order. We only need a consistent ordering scheme across DBs to not break diffs.

**Comment by sweatybridge** [comment]
Thanks to @kbsali's contribution to pg-meta, the table columns are now sorted alphabetically.
