### ISSUE TITLE
Generated types for Views with a JOIN is missing the update types

### ISSUE THREAD

**Issue by WesleyYue** [supabase/cli#604]
# Bug report

## Describe the bug

With a view created with a join, `supabase gen types` does not generate the `Update: {...}` types for that view and I have to manually inject it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a View with a JOIN
2. Generate types with `supabase gen types`
3. Check that the view type does not contain types for Update

## Expected behavior

Should contain types for Update just like the non-JOIN views.

**Comment by soedirgo** [comment]
I don't think views with a JOIN are [automatically updatable](https://www.postgresql.org/docs/current/sql-createview.html#id-1.9.3.97.7.11.2). You could of course create a trigger as per the docs, but then you can't infer the types from that since you can do pretty much anything in the trigger.

**Comment by WesleyYue** [comment]
> but then you can't infer the types from that since you can do pretty much anything in the trigger

Gotcha, makes sense. Thanks.
