### ISSUE TITLE
ERROR: schema graphql is not a member of extension "pg_graphql"

### ISSUE THREAD

**Issue by MaxAst** [supabase/cli#615]
# Bug report

## Describe the bug

I'm trying to generate typescript types for my project. I installed the latest supabase cli, logged in, linked the project and ran `supabase db remote commit`. After that I ran `supabase db reset` as was recommended by the cli. This caused the following error:

```
Error: ERROR: schema graphql is not a member of extension "pg_graphql" (SQLSTATE 55000)
```

## To Reproduce

See above

## Expected behavior

The initial migration works as expected, so that I can generate typescript types.

## System information

- OS: macOS
- Version of supabase-cli: [e.g. 1.14.0]

## Additional context

I toggled the pg_graphql extension off and on again in the dashboard, but the issue still wasn't resolved.

**Comment by MaxAst** [comment]
I ran the SQL statements mentioned in [this issue](https://github.com/supabase/cli/issues/506), deleted the previous migration, and re-tried it. `supabase db remote commit` worked fine again and `supabase db reset` returned a different error now:
```
❯ supabase db reset
Resetting database...
Initialising schema...
Applying migration 20221116202309_remote_commit.sql...
Error: ERROR: relation "graphql._field" does not exist (SQLSTATE 42P01)
At statement 87:                                                                           
                                                                          
                                                                          
--                                                                        
-- Name: TABLE "_field"; Type: ACL; Schema: graphql; Owner: supabase_admin
--                                                                        
                                                                          
REVOKE SELECT ON TABLE "graphql"."_field" FROM "postgres";                
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by MaxAst** [comment]
FWIW toggling off the pg_graphql extension fixed the issue. This is fine for us, given that we don't make use of the extension. Nonetheless I'll keep the issue open, so this can be investigated for those who want to keep it toggled on

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. It is similar to #600 and #612. Our pg_dump script should ignore all schema changes generated by extensions. Unfortunately we haven't found a way to reliably exclude grants and revokes from pg_dump.

Our suggestion atm is to manually comment out lines containing ACL changes to graphql schema.

**Comment by sweatybridge** [comment]
We have updated the pg_dump script to auto comment out all ACL changes related to extensions.
