### ISSUE TITLE
Only apply migrations with .sql extension

### ISSUE THREAD

**Issue by mxmzb** [supabase/cli#625]
# Bug report

```
❯ npx supabase db push --debug
Enter your database password:
2022/11/21 01:21:41 Connect Start: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Start: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Done: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Done: udp 8.8.8.8:53
[...]
2022/11/21 01:21:41 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2022/11/21 01:21:41 PG Send: {"Type":"Query","String":"SELECT version FROM supabase_migrations.schema_migrations ORDER BY version"}
2022/11/21 01:21:41 PG Recv: {"Type":"RowDescription","Fields":[{"Name":"version","TableOID":17112,"TableAttributeNumber":1,"DataTypeOID":25,"DataTypeSize":-1,"TypeModifier":-1,"Format":0}]}
2022/11/21 01:21:41 PG Recv: {"Type":"CommandComplete","CommandTag":"SELECT 0"}
2022/11/21 01:21:41 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
Applying unapplied migrations...
Error: Can't process file in supabase/migrations: .DS_Store
```

## Describe the bug

When i run `supabase db push --debug` it will fail due to `.DS_Store` file, which by the way **does not exist** inside `./supabase/migrations/` !!

## To Reproduce

Run `supabase db push --debug` on a mac with an existing sql migration file.

## Expected behavior

It will sync up my migrations to the remote db.

## System information

- OS: macOS 13.0
- Version of supabase: 1.14.3
- Version of Node.js: v16.16.0

**Comment by sweatybridge** [comment]
I suspect there's a hidden file named `./supabase/migrations/.DS_Store`. You can check with the following command:

```bash
ls -la ./supabase/migrations
```

We will likely require all migrations to use `.sql` extension. But since it is a breaking change, I will do that in CLI v2.
