### ISSUE TITLE
How to install the cli on Ubuntu?

### ISSUE THREAD

**Issue by jvbianchi** [supabase/cli#63]
# Feature request

## Is your feature request related to a problem? 

I would like a way to install the cli on linux (Ubuntu)

**Comment by n-d-r-d-g** [comment]
You can also run:

1. `systemctl start docker` to start Docker.
2. `npx supabase start` or `sudo npx supabase start`. This might take a few minutes the first time you run it.

I have noticed that the above commands seem to be the easiest way to get supabase to work on Ubuntu-based systems.
