### ISSUE TITLE
Cannot  make `supabase start`

### ISSUE THREAD

**Issue by vikiival** [supabase/cli#632]
# Bug report

## Describe the bug

When I try to do `supabase start` it fails on `unknown image`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download latest Supabase CLI
2. Type `supabase start`
3. See error

## Expected behavior

Supabase CLI should start normaly

## Screenshots

```
$ supabase start
Error: Error: No such image: public.ecr.aws/t3w2s2c9/postgres:14.1.0.89
```

## System information

- OS: MacOS 12.5.1
- Version of supabase-js: ???
- Version of Node.js: 16.18.1

**Comment by vikiival** [comment]
Got even 100% 🙃 

<img width="307" alt="Screenshot 2022-11-24 at 10 16 32" src="https://user-images.githubusercontent.com/22471030/203758652-db55ae91-9081-451c-8f1e-8ab80bc7fe76.png">

**Comment by sweatybridge** [comment]
Hi @vikiival, is it stuck at 100% or did it finish downloading the image? I suspect it's an ephemeral issue with ECR. 

You may also try the alternative docker registry:

```bash
SUPABASE_INTERNAL_IMAGE_REGISTRY= docker.io supabase start
```

**Comment by vikiival** [comment]
> Hi @vikiival, is it stuck at 100% or did it finish downloading the image?

Hi @sweatybridge after 100% an error appears. 

```
Error: Error: No such image: public.ecr.aws/t3w2s2c9/postgres:14.1.0.89
```

I'll try different image registry

**Comment by sweatybridge** [comment]
Might also be worth checking if regular docker pull / run works

```bash
docker pull public.ecr.aws/t3w2s2c9/postgres:14.1.0.89
docker run -it public.ecr.aws/t3w2s2c9/postgres:14.1.0.89
```

**Comment by vikiival** [comment]
So the problem was mainly that I did not enough space for docker images.
Looks like `supabase start` passed correctly.

> ```shell
> docker pull public.ecr.aws/t3w2s2c9/postgres:14.1.0.89
> ```

This helped me to debug it :)
