### ISSUE TITLE
Storage API fails to copy file

### ISSUE THREAD

**Issue by haydn** [supabase/cli#633]
# Bug report

## Describe the bug

In development, using the storage API to copy a file like this:

```js
await supabase.storage
  .from("private")
  .copy(
    "master-documents/051b8395-502a-4a0c-9b4c-5fef4db3bf7d/1/contract-1.pdf",
    "documents/bd68140a-f34a-431f-9b36-7440b8817fee/1/contract-1.pdf"
  );
```

Results in this error:

> ENOENT: no such file or directory, copyfile '/var/lib/storage/stub/stub/private/master-documents/051b8395-502a-4a0c-9b4c-5fef4db3bf7d/1/contract-1.pdf' -> '/var/lib/storage/stub/stub/private/documents/bd68140a-f34a-431f-9b36-7440b8817fee/1/contract-1.pdf'

## To Reproduce

1. Create a new project: `supabase init && supabase start`
2. Create a bucket: `supabase.storage.createBucket("example-bucket")`
3. Add a file to the bucket: `supabase.storage.from("example-bucket").upload("example-file", file)`
4. Attempt to copy the file: `supabase.storage.from("example-bucket").copy("example-file", "example-copy")`

## Expected Behavior

It should copy the file like it does in a production environment.

## Screenshots

N/A

## System information

- OS: macOS
- Version of CLI : 1.15.0
- Version of supabase-js: 2.1.1
- Version of Node.js: 16.17

## Additional context

N/A

**Comment by haydn** [comment]
It looks like the way this failures has changed in recent versions. The copy operation will not raise an error and will create a new object, but trying to retrieve that object will return an `Internal Server Error`. You can hit this just trying to download or generate a URL for the object in Supabase Studio:

![image](https://github.com/supabase/cli/assets/27211/85db38f8-dc81-4d69-bfde-cd8c29329be8)

@sweatybridge Should this be moved to https://github.com/supabase/storage-api? I'm not sure where the problem lies, but I've only ever seen it in my development environment.

**Comment by sweatybridge** [comment]
Thanks @haydn, I've pinged the storage team internally to help take a look.
