### ISSUE TITLE
Create type and database wrong order in migrations

### ISSUE THREAD

**Issue by marozzocom** [supabase/cli#65]
# Bug report

## Describe the bug

When creating a migration file after creating a type and then using it in a newly created table, the type creation is placed after table creation in migration file.

## To Reproduce

Create type:

`create type custom_type as enum ('option1', 'option2');`

Create table

```
create table custom_table(
  id uuid not null primary key,
  type custom_type
);
```

Create migration

`supabase db dump --name create_custom_table`

Deploy migration (optional step to observe error)

`supabase deploy`

## Expected behavior

I suppose that in the generated migration file the type should be created before the table.

## Observed behavior

In the generated migration file the table is created first, and the type after it. This causes an error during deployment:

`Error: ERROR: type "custom_type" does not exist (SQLSTATE 42704)`

## System information

- OS: Windows
- Supabase CLI: 0.10.5
- Version of Node.js: 16.13.0
- Postgres Client where SQL was run: DataGrip

## Additional context

I understand this feature is probably not complete, I hope it is okay to file a bug report anyway. The steps above are similar to what I tried locally, but the names of the type, columns and table have been changed for this report.

In addition I noticed the migration has `DROP TYPE IF EXISTS public.custom_type;` commented out, just above creating the type. Not sure if this is intentional.

**Comment by soedirgo** [comment]
Thanks for filing this @marozzocom! Yeah the schema diff output isn't foolproof - I think we can communicate this better though. I'll update the docs & help output before I close this.

The `DROP TYPE` thing can be left commented out.

Just in case, once you reorder the migration and run `supabase db restore`, does it work? (This is a safer way to check for errors as it doesn't touch the deploy database.)

**Comment by marozzocom** [comment]
Hi!

Running `supabase db restore` seems to work after reordering the migration -- at least I did not notice any errors and there were no errors in console output.

**Comment by soedirgo** [comment]
Updated the error messages in https://github.com/supabase/cli/commit/f4ece64daac6fcad8b63edf51c68424b032b4c4b - that should provide a feedforward on what to do when this happens.
