### ISSUE TITLE
 Migration update for datatype and column migrations

### ISSUE THREAD

**Issue by AvidDabbler** [supabase/cli#669]
# Bug report

## Describe the bug

I have a supabase migration setup to push updated from my local to my test databases. Right now I am moving some columns that I want to archive with `_old` and create new columns in their place. I have a column that I am creating that is a uuid and was a json field.

When I do this I get the message that json cannot be changed to uuid (see below)

Sample updated migration script

```
alter table "public"."notes" add column "user_id_old" json;

alter table "public"."notes" add column "user_name" text;

alter table "public"."notes" alter column "user_id" drop not null;

alter table "public"."notes" alter column "user_id" set data type uuid using "user_id"::uuid;

alter table "public"."notes" add constraint "notes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) not valid;

alter table "public"."notes" validate constraint "notes_user_id_fkey";
```

Error Message

```
Error: ERROR: cannot cast type json to uuid (SQLSTATE 42846)
At statement 20: alter table "public"."notes" alter column "user_id" set data type uuid using "user_id"::uuid
```

The other issue that I am noticed is that I have done some data migrations manually moving data from one column to another this does not show up in the generated migration (example below)

```
-- update user_id
update notes 
  set 
    user_name = user_id_old->>'name',
    user_id = CAST(CAST(user_id_old->>'id' as char(36)) as uuid)
    
-- update stop
update notes 
  set 
    stop_id = stop_old[1]->>'value',
    stop_name = stop_old[1]->>'label'
  where stop_old[1] is not null
  ```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create some columns that are JSON
2. add some json to the fields
3. Rename the column
4. Create a new column with a type of string
5. Update the new colmuns with the old json
6. run the diff migration - `npx supabase db diff --debug --use-migra -f husky`
7. The generated migration should fail upstream

## Expected behavior

I would expect that the sql would run without error and create and transfer my data

## System information

- OS: osx 13 m1
- Browser: firefox

**Comment by AvidDabbler** [comment]
Looking back at this is am running the migration with husky locally on commit. Is this best practice or is it better to resolve all changes and let GA take care of the diff workflow?

**Comment by sweatybridge** [comment]
Hello, you can replace the generated `supabase/migrations/<timestamp>_husky.sql` with your own statements to fix any error. For example, the offending statement `alter column "user_id" set data type uuid` may be replaced:

```sql
alter table "public"."notes" add column "user_id_old" json;

alter table "public"."notes" add column "user_name" text;

alter table "public"."notes" alter column "user_id" drop not null;

-- alter table "public"."notes" alter column "user_id" set data type uuid using "user_id"::uuid;

-- replace user_id column, assuming no more constraints
update notes set user_id_old = user_id;
alter table notes drop column user_id;
alter table notes add column user_id uuid;

-- update user_id
update notes 
  set 
    user_name = user_id_old->>'name',
    user_id = CAST(CAST(user_id_old->>'id' as char(36)) as uuid)

alter table "public"."notes" add constraint "notes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) not valid;

alter table "public"."notes" validate constraint "notes_user_id_fkey";
```

Once `db reset` works locally, you can run `db push` to apply the migration on your linked remote project.

If you have multiple developers on the same project, it's usually better to let GA take care of `db push` on every merge to main branch. This makes sure that only one user (ie. the action runner) is updating the remote project. Otherwise you might have two devs pushing conflicting schema changes.

**Comment by AvidDabbler** [comment]
awesome thanks for the clarification. Sounds like I need to turn off husky and update my database locally in the interim. then i can start manually updating migrations with custom scripts.

One last question. Is there a way to manually create a migration if no changes have been detected? Like if i need to move some data around.

Maybe I performed a push with db push and i forgot the update. Can i manually create an empty migration file to be set to triggered if no changes were detected in the schema with the `diff` command?

**Comment by AvidDabbler** [comment]
thanks for the help. i think that we are back on track!

**Comment by sweatybridge** [comment]
Good to know! Feel free to reach out again if you run into other issues.
