### ISSUE TITLE
npm install fails to download binary

### ISSUE THREAD

**Issue by erodriguezh** [supabase/cli#679]
# Bug report

## Describe the bug

When running `npm install supabase@latest  --save-dev` the install script tries to download a binary from  the following url `https://github.com/supabase/cli/releases/download/v1.21.0/[object Object]_1.21.0_darwin_amd64.tar.gz`. Please notice the name of the file `[object Object]_1.21.0_darwin_amd64.tar.gz`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `npm install supabase@latest  --save-dev`

## Expected behavior

Supabase installs as a dependency package

## Screenshots

<img width="996" alt="Screen Shot 2022-12-08 at 20 58 32" src="https://user-images.githubusercontent.com/710174/206556709-970e6022-901c-468f-98f6-f3e058de1c07.png">

## System information

- OS: macOS Big Sur 11.7.1
- Version of supabase: 1.21.0
- Node version: 14.19.1
- Npm version: 6.14.16

**Comment by sweatybridge** [comment]
Could you check the contents of `cat /Users/erodr/Developer/playground/supaship/node_modules/supabase/package.json`?

I suspect it's a similar issue with corrupted local node module.

**Comment by erodriguezh** [comment]
The file does not exists. 
I also checked manually in the `node_modules` folder to see if there is any supabase folder at all, no luck either.

![Screen Shot 2022-12-09 at 09 06 56](https://user-images.githubusercontent.com/710174/206655120-92b3d376-7d88-46a0-9bad-9c6fc884a646.png)

![Screen Shot 2022-12-09 at 09 08 48](https://user-images.githubusercontent.com/710174/206655126-79bc68d5-932b-4ee2-b1eb-1c9b7e7be5e7.png)

**Comment by sweatybridge** [comment]
Can you try updating your npm version? I can't reproduce on 8.19.2
```
npm update -g npm
```

**Comment by erodriguezh** [comment]
It works with npm 8. Thanks for the help 🙂
