### ISSUE TITLE
Error: unexpected end of JSON input

### ISSUE THREAD

**Issue by titogarrido** [supabase/cli#68]
# Bug report

## Describe the bug

I am trying to create a new supabase instance using CLI on a ubuntu 20.04 (arm) and I am receiving:

Error: unexpected end of JSON input

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. install supabase cli 0.10.5
2. Create an empty directory supabase-local
```
ubuntu@ubuntu:~/supabase-local$ git init
Initialized empty Git repository in /home/ubuntu/supabase-local/.git/
ubuntu@ubuntu:~/supabase-local$ supabase init
Error: unexpected end of JSON input
```

## Expected behavior

I guess it should create a `supabase` directory.

## System information

- OS: Linux Ubuntu 20.04 - arm
- Version of supabase-cli 0.10.5

**Comment by soedirgo** [comment]
Hey @titogarrido, this is related to #41 - the containers won't run properly on aarch64 Linux. I'll close this issue in favor of that one.
