### ISSUE TITLE
Unable to start local database after upgrade to 1.24.0

### ISSUE THREAD

**Issue by miguelespinoza** [supabase/cli#687]
# Bug report

## Describe the bug

I was originally on cli version `1.4.6`. After reading about the `--backup` option for `supabase stop`, I decided to upgrade. 
Unfortunately, now I get an error that `public.ecr.aws/supabase/studio:0.22.08` does not exist

```
2022/12/13 17:22:25 Sent Header: Host [docker]
2022/12/13 17:22:25 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/13 17:22:25 Send Done
2022/12/13 17:22:25 Recv First Byte
2022/12/13 17:22:25 Sent Header: Host [docker]
2022/12/13 17:22:25 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/13 17:22:25 Sent Header: Content-Length [0]
2022/12/13 17:22:25 Sent Header: Content-Type [text/plain]
2022/12/13 17:22:26 Recv First Byte
⣷ Pulling from supabase/studio...

2022/12/13 17:22:53 Sent Header: Host [docker]
2022/12/13 17:22:53 Sent Header: User-Agent [Go-http-client/1.1]
Error: Error: No such image: public.ecr.aws/supabase/studio:0.22.08
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Had cli version `1.4.6`
2. Upgraded to latest: `1.24.0` in my case
3. Had supabase running locally, so ran `supabase stop --backup`
4. Now I can't restart the local database

## Expected behavior

`supabase start` should run after upgrading to cli version 1.24.0 and running `supabase stop --backup`

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of supabase-js: xxx
- Version of Node.js: xxx

## Additional context

- It would seem a regression with the cli, but anyway I could remedy this issue locally?

**Comment by sweatybridge** [comment]
Hello, could you try


```bash
docker pull public.ecr.aws/supabase/studio:0.22.08
```

Sometimes the local disk is full which prevents new image from downloaded. Unfortunately, our error message is not clear in this case.

**Comment by miguelespinoza** [comment]
Yesterday afternoon, I decided to wipe existing docker containers, images, and volumes. I thought maybe there was a big gap between the cli versions that it required a fresh start.

Now that I wiped the containers, it's stuck on:
```
Error: ERROR: extension "pg_graphql" must be installed in schema "graphql" (SQLSTATE 0A000)
At statement 12: --                                                                  
-- Name: pg_graphql; Type: EXTENSION; Schema: -; Owner: -           
--                                                                  
                                                                    
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "extensions"
```

My migrations scripts are pointing to schema "extensions", but it wants the extension installed on schema "graphql", I'm cautious of making changes to migration scripts after the fact. Is this a known breaking change of the cli?

**Comment by miguelespinoza** [comment]
I came across this discord question about the above issue I found
https://discord.com/channels/839993398554656828/1051886994160095313/1051886994160095313

Are there any repercussions from having to comment out references of graphql? Specifically when publishing changes to a production supabase instance

**Comment by sweatybridge** [comment]
Thanks for giving us more context of this issue. In this case, I would suggest replacing the `extensions` schema with `graphql`. For eg.

```sql
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
```

**Comment by sweatybridge** [comment]
> Is this a known breaking change of the cli?

This specific error seems new. The known breaking changes are detailed in [other issues](https://github.com/supabase/cli/issues/615). Typically the resolution is to comment those lines out as those entities are managed by pg_graphql extension.

If you have further doubts, please email support@supabase.io with your project ref so that I can help take a closer look.

**Comment by miguelespinoza** [comment]
cool, thanks. 
So, in the Discord thread, I mentioned I had to comment out more graphql related SQL statements. These specifically were mentioned in this [PR](https://github.com/supabase/cli/pull/589), that they're safe to comment. Is that still the case?

```
Error: ERROR: function graphql.get_built_schema_version() does not exist (SQLSTATE 42883)
At statement 144: --                                                                                               
-- Name: FUNCTION "get_built_schema_version"(); Type: ACL; Schema: graphql; Owner: supabase_admin
--                                                                                   
```

**Comment by sweatybridge** [comment]
```sql
Error: ERROR: function graphql.get_built_schema_version() does not exist (SQLSTATE 42883)
At statement 144: --                                                                                               
-- Name: FUNCTION "get_built_schema_version"(); Type: ACL; Schema: graphql; Owner: supabase_admin
--                                                                                   
```

Yup, those are still safe to comment out.

**Comment by miguelespinoza** [comment]
cool deal, thanks for following up @sweatybridge!

Looks like I'm all good to keep on working locally!
