### ISSUE TITLE
Error: Error running SQL: ERROR:  relation "public.profiles" does not exist

### ISSUE THREAD

**Issue by titogarrido** [supabase/cli#69]
# Bug report

## Describe the bug

I am not able to run `supabase start` without an error

## To Reproduce

1. Install supabase-cli
2. execute supabase init
3. execute supabase start
```
titog@intel-nuc:~/supabase-local$ supabase start
⣟ Applying migration 20211108185629_link.sql...

BEGIN
ALTER EVENT TRIGGER
ALTER PUBLICATION
Error: Error running SQL: ERROR:  relation "public.profiles" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

## Expected behavior

supabase should start a mirrored instance locally

## System information

- OS: Ubuntu 20.04 x86
- Version of supabase-cli: 0.10.5

**Comment by titogarrido** [comment]
I have removed this table from the "realtime" replication, deleted supabase folder and now when I try to run link again I am receiving:

`Error: supabase_migrations.schema_migrations table conflicts with the contents of `migrations` directory.`

**Comment by devneagu** [comment]
Hello,

Are you sure you created your profiles table using supabase from User Management Starter in the SQL Editor(Quick Start)? 

I've had the same issue, forgot to add the profiles table.

**Comment by soedirgo** [comment]
This seems to be the same issue as https://github.com/supabase/cli/issues/65.

I've updated the error messages in https://github.com/supabase/cli/commit/f4ece64daac6fcad8b63edf51c68424b032b4c4b - it should now say something more useful than "X conflicts with Y".
