### ISSUE TITLE
Invalid db.major_version 15 in config.toml when linking

### ISSUE THREAD

**Issue by steezeburger** [supabase/cli#698]
# Bug report

## Describe the bug

When trying to link a new remote project to a new local codebase, I get the following:
```
Finished supabase link.
Local config differs from linked project. Try updating supabase/config.toml
[db]
port = 54322
shadow_port = 54320
major_version = 15
```

I then update `config.toml` to have version 15, and then I get the following error when I rerun the `link` command:
```
Error: Failed reading config: Invalid db.major_version: 15.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Supabase remote project
2. Create a new Nextjs local repo
3. Try to link the Supabase remote project to your local repo
4. See warning about updating `config.toml`
5. Update `config.toml` to use version 15
6. Run the `link` command again

## Expected behavior

I've not successfully linked a project yet, so I'm not 100% sure of the intended behavior.

**Comment by izznatsir** [comment]
It also prevents `supabase start` command from running with the same error message.
