### ISSUE TITLE
db remote commit uses pg_dump v14 even when major_version = 15 is set

### ISSUE THREAD

**Issue by etherform** [supabase/cli#703]
# Bug report
## Describe the bug
Cli fails on command `supabase db remote commit` when remote postgres database version is 15

## To Reproduce

1. Create project at https://app.supabase.com
2. Link it with `supabase link`
3. Try to create initial migration with `supabase db remote commit ` 

At the time of writing you get:
```
pg_dump: error: server version: 15.1; pg_dump version: 14.5 (Debian 14.5-2.pgdg110+2)
pg_dump: error: aborting because of server version mismatch
Error running pg_dump on remote database: error running container
```

## Expected behavior

`db remote commit` command should probably pick correct pg image depending on which `major_version` is stated in config file.

## System information

- OS: Windows
- Version of supabase-cli: 1.26.3
- Version of node.js: 18.12.1

**Comment by soedirgo** [comment]
Hey there - let us know if upgrading fixes the issue!

**Comment by etherform** [comment]
@soedirgo everything is great now, thanks!
