### ISSUE TITLE
Operation not permitted error on yarn install command

### ISSUE THREAD

**Issue by dwozniak8** [supabase/cli#706]
# Bug report

## Describe the bug

There is error when try to install this package: 

```
yarn add v1.22.19
Downloading https://github.com/supabase/cli/releases/download/v1.26.5/supabase_1.26.5_windows_amd64.tar.gz
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: EPERM: operation not permitted, symlink '..\supabase\bin\supabase' -> 'C:\apps\cm\node_modules\.bin\supabase'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
```

## To Reproduce

1. run `yarn add --dev supabase` in project

## Expected behavior

Package shoud be installed

## System information

- OS: Windows 10
- Version of Node.js: v.14.18.0
- Version of Yarn: 1.22.19

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. Would you be open to using alternative installation methods on windows, like npm or scoop?

Those are known to work on windows.

**Comment by LordZardeck** [comment]
We are having the exact same issue when deploying to vercel, using build cache.

**Comment by sweatybridge** [comment]
I've released a fix for yarn on windows and added CI check for installation on all supported platforms. https://github.com/supabase/cli/actions/runs/3719923636
