### ISSUE TITLE
supabase start fails to download PG15 image

### ISSUE THREAD

**Issue by alexfigueiredo** [supabase/cli#707]
# Bug report

## Describe the bug

The command `supabase start` fails to download a docker image for `postgres@15.1.0.11`.

```
supabase start
Error: Error: No such image: public.ecr.aws/supabase/postgres:15.1.0.11
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a project at https://app.supabase.com
2. Link it with `supabase link`
2.1 This will throw an error saying the "Local config differs from linked project." Try updating supabase/config.toml
3. Update `db.major_version` from `14` to `15`
5. Run `supabase start`

## Expected behavior

The command creates the local environment.

## Screenshot

<img width="2672" alt="1" src="https://user-images.githubusercontent.com/944615/207976137-abfcf14f-48e7-40bb-9b9d-7a43f98b4ea9.png">

## System information

- OS: macOS
- Version of supabase-cli: 1.26.5
- Version of Node.js: v16.15.1

**Comment by sweatybridge** [comment]
Hello, as a sanity check, could you try

```bash
docker pull public.ecr.aws/supabase/postgres:15.1.0.11
```

Sometimes the local disk is full which prevents new image from being downloaded. Unfortunately, our error message is not clear in this case.

**Comment by alexfigueiredo** [comment]
Indeed, that was my issue: local disk full. Sorry for the noise.
