### ISSUE TITLE
Auto schema diff stuck - Creating shadow database

### ISSUE THREAD

**Issue by k-ane** [supabase/cli#714]
# Bug report

## Describe the bug

I was following the guide on [Managing Environments](https://supabase.com/docs/guides/resources/supabase-cli/managing-environments) and when I try to run the auto diff command `supabase db diff -f new_employee`, it hangs on `Creating shadow database...`.

## To Reproduce

Follow the guide on [Managing Environments](https://supabase.com/docs/guides/resources/supabase-cli/managing-environments#auto-schema-diff), try to complete the 'Auto schema diff' section. See the CLI get stuck.

I tried without an existing migration file and also with one after trying the 'Manual migration' section.

## Expected behavior

I would expect a new or updated migration file, or for the command to time out / error.

## System information

- OS: MacOS M1X
- Version of supabase CLI: v1.26.7
- Version of Node.js: v18.12.1

## Additional context

Running `supabase db diff --use-migra` did produce an output, but not with the `-f` flag.

**Comment by sweatybridge** [comment]
Have you tried with both flags? The following command works for me locally

```bash
supabase db diff --use-migra -f new_employee
```

We will probably switch the default diff tool to migra to make this clearer.

**Comment by sweatybridge** [comment]
I've updated the default pgadmin diff so that creating shadow container is no longer bugged.
