### ISSUE TITLE
Postgres v15 migration

### ISSUE THREAD

**Issue by johnshift** [supabase/cli#716]
# Bug report

## Describe the bug
New projects with postgres `v15` conflicts with `config.toml`. Previous versions were working correctly.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new supabase project (new projects use `postgres-15` instance).
2. Get server major_version by running `SHOW server_version` in remote instance.
3. Set db `major_version = 15` in `config.toml`. 

## Expected behavior

Migration should work as expected.

### v14 related images
![image](https://user-images.githubusercontent.com/89079900/208281690-1f08b0ae-8a44-4ac9-93ce-f5fa23b5d9a7.png)
![ci-invalid-major-14](https://user-images.githubusercontent.com/89079900/208281715-a0e5c61a-ddaa-4b11-aecd-e9d802814c88.png)

### v15 related images
![image](https://user-images.githubusercontent.com/89079900/208281725-4c0140d1-4781-4785-8e09-a7268497ab5e.png)
![ci-invalid-major-15](https://user-images.githubusercontent.com/89079900/208281740-77d90985-a62e-4b3b-9fb7-99fa42197a6a.png)
![image](https://user-images.githubusercontent.com/89079900/208281778-e3ae5b64-33fd-429f-9837-f699c7de9b5b.png)

### github-actions workflow:
![image](https://user-images.githubusercontent.com/89079900/208281617-6ff9928e-96f6-4374-b1e2-53059df9309c.png)

## System information

- OS: `ubuntu 22.04`
- Version of supabase-js: `"@supabase/supabase-js": "^2.2.0"`
- Version of Node.js: `v18.12.1`

**Comment by sweatybridge** [comment]
Hi, in your setup-cli action, you can change the `version` from 1.0.0 to latest cli 1.26.9 to resolve this issue.

**Comment by johnshift** [comment]
Hi @sweatybridge great catch! My bad. 
Thank you. Closing this now.

Awesome blazingly fast reply! 🔥 ⚡
