### ISSUE TITLE
Can't db diff or remote commit with pg_cron extension & scheduled jobs

### ISSUE THREAD

**Issue by drftls** [supabase/cli#723]
# Bug report

## Describe the bug

Cron jobs are scheduled on the remote db using the pg_cron extension so there seems to be some trouble syncing the local.

Working through the following error messages, I tried changing the cron.database_name setting in postgresql.conf as suggested in the error hint, but it produced an additional error and did not seem to resolve the original error. Hoping someone here can share some insight. 

Up to now, I've been developing on the live database, and will continue to do so. Local database would be preferable once we enter production, but if it's not an option, it's not the end of the world either.

_Errors_

`supabase db remote commit --debug` raises `"Error: error creating shadow database"`

`supabase db diff` raises the following:

``` bash
Error: Error starting shadow database: ERROR:  can only create extension in database postgres
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'supabase_shadow' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
```

``` bash
NOTICE:  database "supabase_shadow" does not exist, skipping
Error: Error starting shadow database: ERROR:  can only create extension in database postgres
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'supabase_shadow' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start new Supabase project
2. Enable pg_cron extension
3. Schedule a cron job
4. Try to execute remote commit or diff commands

## Expected behavior

Not sure what to have expected. Thought local DB would work but the cron jobs wouldn't fire if the Docker wasn't online. Don't need the cron jobs to run locally, I just wanted to test some changes to key tables before deleting anything on the live db.

## System information

- OS: Window with WSL2 and Docker Desktop
- `supabase -v`: 1.15.1
- Version of supabase-js: ^2.1.1
- Version of Node.js: v16.17.1

**Comment by sweatybridge** [comment]
Hello, I've addressed this issue in the latest release by creating the shadow database in a separate container.

Feel free to reach out if you run into other issues.
