### ISSUE TITLE
supabase generated backup fails for postgres 15

### ISSUE THREAD

**Issue by Gerschtli** [supabase/cli#726]
# Bug report

## Describe the bug

Starting an empty project with a backup fails when using postgres 15.

## To Reproduce

Execute these in an empty directory:

```sh
$ supabase --version
1.27.1

$ supabase init
Finished supabase init.

$ supabase start
Seeding data supabase/seed.sql...
Started supabase local development setup.

         API URL: http://localhost:54321
          DB URL: postgresql://postgres:postgres@localhost:54322/postgres
      Studio URL: http://localhost:54323
    Inbucket URL: http://localhost:54324
      JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
        anon key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

$ supabase stop --backup
Stopped supabase local development setup.

$ supabase start
Error: ERROR: schema "pgsodium" does not exist (SQLSTATE 3F000)
At statement 18: --
-- Name: pgsodium; Type: EXTENSION; Schema: -; Owner: -
--
CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium"
Try rerunning the command with --debug to troubleshoot the error.
```

`supabase/config.toml`: http://ix.io/4j6j/toml
`supabase/.branches/main/dump.sql`: http://ix.io/4j6k/SQL

## Expected behavior

Supabase containers should start without errors.

## System information

- OS: Linux (NixOS)
- Version of supabase-cli: 1.27.1

## Additional context

Works fine when setting `db.major_version` to `14` after `supabase init`.

`supabase/.branches/main/dump.sql` for pg14: http://ix.io/4j6k/SQL
Diff between dump.sql for pg14 and pg15: http://ix.io/4j6q/diff

**Comment by alpharahl** [comment]
+1 running into the same issue. Once you've gotten into this state I can't see an obvious way to reset the database as supabase db reset requires the containers to be running, but they fail to start

**Comment by Gerschtli** [comment]
@alpharahl As a temporary fix, just remove the `dump.sql` in `supabase/.branches/<branchname>`.

**Comment by lsarni** [comment]
I'm having the same error on version 1.29.6

```
Error: ERROR: schema "pgsodium" does not exist (SQLSTATE 3F000)
At statement 18: --                                                              
-- Name: pgsodium; Type: EXTENSION; Schema: -; Owner: -         
--                                                              
                                                                
CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium"
Try rerunning the command with --debug to troubleshoot the error.
```

<img width="680" alt="image" src="https://user-images.githubusercontent.com/15196342/216398979-c22feb99-2753-4245-b95c-5b8b5310084c.png">

As a workaround I can delete the `dump.sql` as suggested above, but I would like to be able to use it.
