### ISSUE TITLE
Error running supabase start with fresh project

### ISSUE THREAD

**Issue by milesingrams** [supabase/cli#73]
# Bug report

## Describe the bug

I really want to try this new CLI, however i seem to consistently run into an issue with `supabase start`.
I've created a new project, didnt change any settings, linked it using the CLI, but when running `supabase start` I get this error: `Error running SQL: ERROR:  extension "pgjwt" has no update path from version "0.1.0" to version "0.2.0"`, followed by many repeated: `ERROR:  current transaction is aborted, commands ignored until end of transaction block`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new supabase project
2. Use CLI to init and link
3. Run `supabase start`

## Screenshots

<img width="785" alt="Screen Shot 2021-11-16 at 6 45 56 PM" src="https://user-images.githubusercontent.com/4930881/142083946-946ea0c9-544b-45ed-960c-b72ef3df99c4.png">

## System information

- OS: Mac OSX 12.0.1

**Comment by soedirgo** [comment]
Hey Miles, can you try removing these SQL from the `..._link.sql` file?
- `ALTER EXTENSION`
- anything that involves the `auth` schema, e.g. `CREATE TABLE auth.identities`
- anything that involves the `extensions` schema, e.g. `ALTER FUNCTION extensions.try_cast_double`

In my case for a fresh project this left the `...link.sql` empty.

Sorry for the experience though, currently you need some interventions to use the CLI.

**Comment by milesingrams** [comment]
Thanks for the answer! I'll definitely give that a try!
Out of curiosity would this potentially cause my local container to act differently than the prod DB? Aka if there is an `ALTER FUNCTION extensions.try_cast_double` would not having that run locally in the `link.sql` mean I'm using a different version of that function and therefore could have different results? Perhaps there could be a solution where the core `engine` schemas (auth, storage, extensions) are diffed/patched separately with different rules than the non-core schemas (public, etc.)

**Comment by soedirgo** [comment]
> Perhaps there could be a solution where the core engine schemas (auth, storage, extensions) are diffed/patched separately

Yup, the approach I have in mind is to:
1. ignore objects managed by extensions
2. ignore `extensions`, `auth`, and other schemas managed by Supabase

I'll be doing these in the next release.

**Comment by soedirgo** [comment]
> ignore objects managed by extensions
> ignore extensions, auth, and other schemas managed by Supabase

The CLI does the above now, so closing this.
