### ISSUE TITLE
Unable to run`supabase init`

### ISSUE THREAD

**Issue by JamesLloydPartington** [supabase/cli#730]
# Bug report

## Describe the bug
When running `supabase init` I get the following error:
```
Error: Project already initialized. Remove supabase/config.toml to reinitialize.
Try rerunning the command with --debug to troubleshoot the error.
```

The `--debug` displays no extra info

## To Reproduce

```
temp-folder $ mkdir temp
temp-folder $ cd temp
temp (main) $ supabase init
Error: Project already initialized. Remove supabase/config.toml to reinitialize.
Try rerunning the command with --debug to troubleshoot the error.
temp (main) $ ls
temp (main) $
```

## Expected behavior

Initialise a new supabase project locally

## Screenshots

N/A

## System information

Mac M1

## Additional context

I do have supabase/config.toml in other directories, but I really do not want to delete them just to make a new project work. And I am sure I have been able to setup supabase locally at different locations before (not simultaneously obviously).

I have tried uninstalling and reinstalling supabase CLI, deleting docker containers, images and volumes which are used by Supabase.

**Comment by sweatybridge** [comment]
closing as not reproducible

**Comment by mintavenger** [comment]
Hi. I installed CLI version 1.33.0 and having the same issue:

temp-folder $ mkdir temp
temp-folder $ cd temp
temp-folder $ supabase -v
1.33.0
temp (main) $ supabase init
Error: Project already initialized. Remove supabase/config.toml to reinitialize.
Try rerunning the command with --debug to troubleshoot the error.
temp (main) $ ls
temp (main) $

**Comment by mintavenger** [comment]
Also tried with latest 1.34.2

$ supabase -v
1.34.2

**Comment by mintavenger** [comment]
Found the issue, a supabase directory was at $HOME/supabase. Once I removed that I was able to initialize within the project.
