### ISSUE TITLE
Error: exit status 1

### ISSUE THREAD

**Issue by scouech** [supabase/cli#735]
Hi, 

Tried to copy the `hello-world` function and deploy it, however it gives at random times the error below. 
I managed to deploy the function but then after the first deploy it becomes impossible to deploy it again. 

I tried via Replit, local and remote DO server. 
I get the same error. I thought it would be the project so I tried to create another project but I still get the same error.

Latest version of the CLI  (1.27.7) 
Maybe there is something really simple I didn't understand!

```
root@terminal:~# supabase functions deploy hello-world --project-ref xxxxx
Error: exit status 1
Try rerunning the command with --debug to troubleshoot the error.
root@terminal:~# supabase functions deploy hello-world --project-ref xxxx --debug
Error: exit status 1
```

**Comment by sweatybridge** [comment]
Could you provide us with more information to help reproduce?

- OS version: `uname -a`
- deno version: `~/.supabase/deno --version`

It appears from your logs that something errored either during `InstallOrUpgradeDeno` step or `CopyEszipScripts` step because the logs didn't contain the lines `Bundling <name>...`.

My best guess is incompatible deno version. Perhaps you can try `rm ~/.supabase/deno` to force redownload deno?

**Comment by scouech** [comment]
Thanks @sweatybridge 

Os version:
`Linux 649ce420198a 5.15.0-1025-gcp #32~20.04.2-Ubuntu SMP Tue Nov 29 08:31:04 UTC 2022 x86_64 GNU/Linux
`
Deno version:
```
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

I have forced the redownload of Deno. It works for the first deploy, but then it stops working:

```
~/EvergreenGenerousSearch$ supabase functions deploy hello-world --project-ref xxxx
Bundling hello-world
Deploying hello-world (script size: 20.99kB)
Deployed Function hello-world on project xxxx
You can inspect your deployment in the Dashboard: https://app.supabase.com/project/xxxx/functions/xxxx/details
```
```
~/EvergreenGenerousSearch$ supabase functions deploy hello-world --project-ref xxxx
Error: exit status 1
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by ZgodaRafal** [comment]
Same here :  
`➜  supabase git:(Init) ✗ npx supabase functions deploy xxx
Error: exit status 1
Try rerunning the command with --debug to troubleshoot the error.
➜  supabase git:(Init) ✗ npx supabase functions deploy --debug xxx
Error: exit status 1`

`"Ubuntu` 18.04.6 LTS"`

**Comment by sweatybridge** [comment]
I suspect this is a problem with mismatched deno version specific to Linux. Let me know if the latest CLI release works for you. I've also included more log statements in case it doesn't.

**Comment by scouech** [comment]
it seems to work! thank you!
