### ISSUE TITLE
Config to disable specific containers

### ISSUE THREAD

**Issue by WesleyYue** [supabase/cli#737]
# Feature request

## Is your feature request related to a problem? Please describe.

config.toml should allow you to disable containers entirely (like inbucket, studio, or auth). We use `supabase start` to run tests in CI and these containers take time and bandwidth to spin up, but we don't even use them in CI.

## Describe the solution you'd like

A flag to disable specific services from startup in config.toml

**Comment by sweatybridge** [comment]
Would the solutions implemented in #624 work for you? We currently support

```bash
supabase start -x inbucket,studio,gotrue
```

Or if you only want to start the db on CI

```bash
supabase db start
```

**Comment by WesleyYue** [comment]
Ah yes, thanks! I was on a slightly older version of the cli so didn't see the option. Hot off the press!

**Comment by sweatybridge** [comment]
If you are using GitHub Actions, another config that can speed up your CI is

```yaml
        env:
          SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
```

This switches CLI to use our GHCR mirror, which reduced our image download time by about 30s.

If you are on Travis CI, logging into AWS ECR via docker cli could also help as it removes the rate limit of pulling as anonymous user.
