### ISSUE TITLE
Supabase CLI - Docker Auth Config: Add OAuth Settings

### ISSUE THREAD

**Issue by dthyresson** [supabase/cli#739]
# Feature request

Easily configure Supabase with OAuth config environment settings to enable GitHub and other third-party auth in local development.

## Is your feature request related to a problem? Please describe.

While the docker-compose.yml included 

```
        GOTRUE_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
        GOTRUE_JWT_EXP: 3600
        GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
```

Did not immediately know what the envars would be needed to configure GitHub or other OAuth providers.

## Describe the solution you'd like

* Have the docker file include all possible settings as noted here: https://github.com/supabase/gotrue#external-authentication-providers

For each: `azure, bitbucket, github, gitlab, facebook, and google`

```
GOTRUE_EXTERNAL_GITHUB_ENABLED=true
GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=myappclientid
GOTRUE_EXTERNAL_GITHUB_SECRET=clientsecretvaluessssh
```

also may need redirect and urls:

```
EXTERNAL_X_ENABLED - bool

Whether this external provider is enabled or not

EXTERNAL_X_CLIENT_ID - string required

The OAuth2 Client ID registered with the external provider.

EXTERNAL_X_SECRET - string required

The OAuth2 Client Secret provided by the external provider when you registered.

EXTERNAL_X_REDIRECT_URI - string required

The URI a OAuth2 provider will redirect to with the code and state values.

EXTERNAL_X_URL - string
```

But for *all* providers, but perhaps commented out or all disables and envars empty.

* Include a cli option on `init` to declare a provider/list of providers to setup (but then how to you set up additional after one was setup?)

## Additional context

https://github.com/supabase/supabase/blob/766d3c0c9107fb553210dcc02880e2d6a9291fc3/docker/docker-compose.yml#L27

Seems like best option might be to include all by default, just not enabled in the docker-compose so can configure easily when/if needed in future.

**Comment by sweatybridge** [comment]
We are supporting oauth settings via config.toml now https://github.com/supabase/cli/blob/a30210717bdb1f3c9d3d5ce940d000971fc1a6da/internal/utils/templates/init_config.toml#L64
