### ISSUE TITLE
supabase db diff returns No changes found

### ISSUE THREAD

**Issue by abhay187** [supabase/cli#742]
# Bug report
supabase db diff returns No changes found
## Describe the bug
I am getting started with local development and started with example in documentation. After creating the employee table when I try to run `supabase db diff create_employees -f create_employees` response is `No changes found`

## To Reproduce
1. update the cli
2. use the documentation example to test
<img width="808" alt="Screenshot 2022-12-27 at 3 06 07 AM" src="https://user-images.githubusercontent.com/61496865/209584860-e5399500-1df8-4c85-9e2a-90fbd6fdb003.png">

## Expected behavior
migration file should be generated.

## Screenshots
<img width="1440" alt="Screenshot 2022-12-27 at 3 15 43 AM" src="https://user-images.githubusercontent.com/61496865/209585012-49b92cba-0734-40cf-8c71-48d717d943ab.png">

## System information

- OS: MacOS v13.1
- Browser (if applies) Firefox
- Supabase cli v.1.27.7

**Comment by sweatybridge** [comment]
Thanks for raising this issue. This was due to a misconfiguration of our diff tool. I've released new version that works as documented.

**Comment by abhay187** [comment]
Hi, @sweatybridge Happy to help. Upgraded my cli and it is working fine.
