### ISSUE TITLE
imgproxy image is pulled incorrectly when using docker hub as registry

### ISSUE THREAD

**Issue by profiluefter** [supabase/cli#743]
# Bug report

## Describe the bug

When setting `SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io` the imgproxy docker image is being pulled as `supabase/imgproxy:v1.0.4` which doesn't exist. According to the [docker-compose.yml in the main repository](https://github.com/supabase/supabase/blob/76e45cf4e8c344b060c6cdcae68af0236b3bbd33/docker/docker-compose.yml#L160) it should be pulled as `darthsim/imgproxy:v3.11`.

Maybe setting that variable isn't an officially supported use case, however it is the only way that our GitHub Action CI runs run without running into ratelimiting issues.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set `SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io` as environment variable
2. `supabase init`
3. `supabase up`

## Expected behavior

The expected image should also be present on docker hub as that platform has higher ratelimiting tolerances.

## Screenshots

```
Pulling images... (3/13)
Error response from daemon: pull access denied for supabase/imgproxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Retrying after 4s: supabase/imgproxy:v1.0.4
```

## System information

- OS: Ubuntu 22.04.1 LTS (GitHub Actions)
- Version of supabase CLI: 1.27.7

## Additional context

N/A

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. I will follow up with updating docker hub.

Meanwhile, a workaround is to use our GHCR mirror which has much higher rate limits when downloading from GitHub Action.

```bash
SUPABASE_INTERNAL_IMAGE_REGISTRY=ghcr.io
```

**Comment by profiluefter** [comment]
Didn't know there is a GHCR mirror! Sounds like a perfect fit for GitHub Actions, thanks!
