### ISSUE TITLE
Supabase db remote commit fail to detect enabled extensions

### ISSUE THREAD

**Issue by abhay187** [supabase/cli#745]
# Bug report
When I run `supabase db remote commit` migration file do not contain `create extension` query.

## Steps to reproduce
1. Enable some extension for example - `moddatetime` on the remote project.
2. Use the extension in a query on a remote project.
3. Run `supabase db remote commit` on local to create migration.
4. Run `supabase db reset` will through error.

## Screenshots
<img width="1090" alt="Screenshot 2022-12-27 at 7 35 09 PM" src="https://user-images.githubusercontent.com/61496865/209680872-1c6d9da1-5ecc-47e8-90cc-33e94af89807.png">

## System information

- OS: MacOS 13.1
- Browser: Firefox
- Supabase CLI - v1.27.8

**Comment by abhay187** [comment]
The current Fix is manually adding code in migration. For the above case, I added `create extension if not exists moddatetime schema extensions;` in remote_commit.sql

**Comment by sweatybridge** [comment]
Another workaround is to pass in the `extensions` schema explicitly via

```bash
supabase db remote commit --schema public,extensions
```

We will work on a fix to default to all schemas.
