### ISSUE TITLE
Enable Azure in GoTrue

### ISSUE THREAD

**Issue by solvemon** [supabase/cli#75]
In "MK1" of the supabase CLI (I have been using version 0.5 up until today), I manually passed in parameters to GoTrue via the docker-compose file. Specifically, flags to enable Azure, as I use this in local development and testing:

```version: '3.6'
services:
    ....
  auth:
    container_name: supabase-auth
    environment:
      .....
      GOTRUE_EXTERNAL_AZURE_ENABLED: 'true'
      GOTRUE_EXTERNAL_AZURE_CLIENT_ID: ************
      GOTRUE_EXTERNAL_AZURE_SECRET: ***********
      GOTRUE_EXTERNAL_AZURE_REDIRECT_URI: http://localhost:8000/auth/v1/callback
      GOTRUE_URI_ALLOW_LIST: http://localhost:8080
    depends_on:
      - db
      - mail
 ```

What would be the equivalent in MK2?

**Comment by soedirgo** [comment]
I haven't thought deeply about this, but the I think the ideal solution is to configure this directly in the OSS dashboard once I manage to integrate it into the CLI.

**Comment by soedirgo** [comment]
Closing this in favor of #80
