### ISSUE TITLE
Type generation does not handle optional parameters to functions

### ISSUE THREAD

**Issue by wwall3r** [supabase/cli#752]
# Bug report

## Describe the bug

Given a function with an optional parameter (has a default value in its PGSQL definition), `npx supabase gen types typescript` does not define that parameter as optional.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the following function and grant permissions to it: 
```pgsql
CREATE OR REPLACE FUNCTION public.create_board(
	p_game_id uuid,
	p_user_id uuid = auth.uid(),
	p_num_objectives integer = 24)
    RETURNS void
-- ... body doesn't matter for this excercise
```
2. `npx supabase gen types typescript`

## Expected behavior

The type definition should look something like this:

```typescript
Functions: {
  create_board: {
    Args: {
      p_game_id: string,
      p_user_id?: string, // should have the ? or possibly string | undefined
      p_num_objectives?: number, // same here
    }
    Returns: undefined
  }
}
```

## System information

- OS: Linux (PopOS 22.04)
- Browser (if applies) N/A
- Version of supabase-js: 2.2.2
- Version of Node.js: 18.12.0
- Version of CLI: 1.27.7

I suppose you could argue that this is a request for a new feature rather than a bug, but I'm not sure what the current expected behavior is.

**Comment by Davepar** [comment]
I created a PR for this: https://github.com/supabase/postgres-meta/pull/455

**Comment by bombillazo** [comment]
Any update on this?

**Comment by soedirgo** [comment]
Resolved in https://github.com/supabase/postgres-meta/pull/455
