### ISSUE TITLE
Failed reading config: Invalid db.major_version: 15.

### ISSUE THREAD

**Issue by gonta1026** [supabase/cli#756]
# Bug report
I try to use github actions to reflect the information in the remote project, but it fails.

## Describe the bug
> Failed reading config: Invalid db.major_version: 15.

## To Reproduce

1. git push
2. [my check github action](https://github.com/gonta1026/sample-supabase/actions)
3. See error

## Expected behavior

Successfully validate github action

### error
<img width="1028" alt="スクリーンショット 2023-01-03 14 49 05" src="https://user-images.githubusercontent.com/45672476/210305752-97a84fd3-1e46-4080-be53-d5628f1dc237.png">

### db version

<img width="513" alt="スクリーンショット 2023-01-03 14 54 25" src="https://user-images.githubusercontent.com/45672476/210306186-8bfb10fd-6976-4456-8c16-9222ae2e973a.png">

### my reference
https://github.com/supabase/supabase-action-example
https://www.youtube.com/watch?v=rOLyOsBR1Uc

**Comment by amorimdub** [comment]
I had the same issue.

I've just updated the version of the github action to latest:

```
      - uses: supabase/setup-cli@v1
        with:
          version: latest
```

**Comment by MartinTale** [comment]
Had to upgrade supabase cli with `brew upgrade` works like a charm afterwards ;)

**Comment by gonta1026** [comment]
Thank you all, I have successfully upgraded the supabase cli as described above.

commit : [fix: supabase/setup-cli@v1 version: latest](https://github.com/gonta1026/sample-supabase#:~:text=.github/workflows-,fix%3A%20supabase/setup%2Dcli%40v1%20version%3A%20latest,-6%20minutes%20ago)

**Comment by gonta1026** [comment]
Issue closed as resolved.

**Comment by lorenzopantano** [comment]
Stumbled upon this issue while running `supabase start` inside my project. Turns out that supabase-cli does not support postgres versions above 15, so if you're running into this issue with db.major_version 16 or 17, what worked for me is to delete the entire supabase folder inside my project and recreated it with `supabase init`.
