### ISSUE TITLE
Relation does not exist when seeding

### ISSUE THREAD

**Issue by thomasmol** [supabase/cli#758]
# Bug report

## Describe the bug

When starting the cli, I get an error when the seed.sql is executed:
```
{"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42P01","Message":"relation \"groups\" does not exist","Detail":"","Hint":"","Position":0,"InternalPosition":34,"InternalQuery":"done := NOT exists(SELECT 1 FROM groups WHERE code=new_code)","Where":"PL/pgSQL function public.generate_group_code() line 9 at assignment","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"parse_relation.c","Line":1381,"Routine":"parserOpenTable","UnknownFields":null}
2023/01/04 12:06:00 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2023/01/04 12:06:00 PG Send: {"Type":"Terminate"}
Error: ERROR: relation "groups" does not exist (SQLSTATE 42P01)
```

The part of the seed.sql that I think is causing a problem:
```sql
ALTER TABLE public.groups DISABLE TRIGGER ALL;
INSERT INTO public.groups (id, name) VALUES
('1f7fc984-c529-4bb6-b7d3-61074a75c55d', 'Group A'),
('15638106-481b-4da6-9ef4-ab1b3c60b8ef', 'Group B')
ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.groups ENABLE TRIGGER ALL;
```

An internal query is executed, as the error message states: ```sql done := NOT exists(SELECT 1 FROM groups WHERE code=new_code)```. I think it applying the schema name should fix this: ```public.groups```

## To Reproduce
1. Setup a local supabase environment.
2. Create a seed.sql
3. Have db trigger that is temporarily disabled in the seed.sql

## Expected behavior

The seed.sql to seed my db. 

## System information

- OS: [macOS 13]
- Version of supabase-cli: [v1.28.1]

**Comment by sweatybridge** [comment]
Could you try moving any alter table statements to a new migration? `seed.sql` only supports data operations like insert or truncate.

**Comment by sweatybridge** [comment]
It also means that in your case,  triggers are not disabled before insert into, which is causing an error.

Are you able to somehow rewrite your seed.sql to work with the trigger?
