### ISSUE TITLE
Pulling images... Error response from daemon: manifest unknown (v1.8.2)

### ISSUE THREAD

**Issue by maxkostow** [supabase/cli#759]
# Bug report

## Describe the bug

`cli@1.8.2` can no longer pull images from ECR and receives the error message

```
Error response from daemon: manifest unknown
```

I realize this is a very old version and likely using old images. The reason we have not updated is due to #146 (we have a script that creates users after `db reset` and at some point after `1.8.2` it started getting an error; I will open another issue with that issue)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. install cli@1.8.2
2. `supabase start`
3. See error

## Expected behavior

The images should continue to pull

## System information

- Github Actions
- Have not tried to reproduce locally

**Comment by maxkostow** [comment]
Ah perhaps this is due to https://github.com/supabase/setup-cli/pull/113

**Comment by sweatybridge** [comment]
Thanks for catching this issue. I've updated setup-cli action to use ghcr only on 1.28.0 and above.
