### ISSUE TITLE
503: name resolution failed in fresh project when creating user

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#76]
# Bug report

## Describe the bug

I'm getting 503 name resolution failed in fresh project when creating a new user

## To Reproduce

Init a project with default settings/ports

```bash
supabase init
```

Start the containers

```bash
supabase start
```

Create a new user

```bash
curl --request POST \
  --url http://localhost:8000/auth/v1/admin/user \
  --header 'APIKey: <serviceKey>' \
  --header 'Authorization: Bearer <serviceKey>' \
  --header 'Content-Type: application/json' \
  --data '{
	"email": "john@doe.com",
	"name": "John Doe"
}'
```

## Expected behavior

I'd expect code 200 and have a user created in the local database

## System information

- OS: macOS Monterey v12.0.1 - Apple M1 Pro
- Version of supabase-js: 1.28.1
- Version of Node.js: v16.13.0
- Version of supabase cli: 0.5.0

## Additional information

If you give me some pointers then I'd like to contribute

**Comment by mr-bjerre** [comment]
God - it is `http://localhost:8000/auth/v1/admin/users` and not `http://localhost:8000/auth/v1/admin/user`. Now I can't replicate 503 anymore though

**Comment by mr-bjerre** [comment]
I just realized it's because auth and storage containers might crash on start since database is not ready yet. It's working if you just start them again but it shouldn't crash on start of course.

**Comment by mr-bjerre** [comment]
Gosh !! I had two installations of `supabase` cli. This happened in v0.5.0

**Comment by Strajk** [comment]
As this is a first result when Googling "name resolution failed supabase", the solution for me was found [here](https://github.com/supabase/cli/issues/1281) 

```
npx supabase stop --no-backup
npx supabase start
```

**Comment by KnightOfNih** [comment]
While this may not be the issue for this post, I did run into the "name resolution failed" error when trying to create a user from the local development dashboard. I had to go into the config.toml file and under "[auth]" change "enabled" to true.

[auth]
enabled = true

This was for version 1.165.0

**Comment by galacticgibbon** [comment]
In my case I had disabled [api]

Must be

[api]
enabled = true
