### ISSUE TITLE
Auth container fails to initialize with CLI v1.28.1 and later

### ISSUE THREAD

**Issue by emilioschepis** [supabase/cli#760]
# Bug report

## Describe the bug

Upgrading the CLI version to v1.28.1 causes the auth container to continuously restart after failing to initialize.

The error message is: 
```json
{
  "level":"fatal",
  "msg":"running db migrations: error executing /usr/local/etc/gotrue/migrations/20221114143410_remove_parent_foreign_key_refresh_tokens.up.sql, sql: alter table only auth.refresh_tokens\n  drop constraint refresh_tokens_parent_fkey;\n: ERROR: constraint \"refresh_tokens_parent_fkey\" of relation \"refresh_tokens\" does not exist (SQLSTATE 42704)",
  "time":"2023-01-04T19:38:06Z"
}
```

Might be related to https://github.com/supabase/cli/commit/9cabaa8db4dfb7969c1080bfcdf5fb4367a67cb4 ?

Let me know if I can provide any additional info, thanks!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install latest CLI version from brew
2. Initialize a supabase project
3. Run `supabase start`

## Expected behavior

The `supabase_auth_<project>` container initializes correctly and serves requests.

## System information

- OS: macOS
- Version of Node.js: 18.12.1

**Comment by sweatybridge** [comment]
Thanks for reporting this bug. It was due to missing entries in auth migrations table that caused migrations to rerun. It should be fixed in 1.28.3.
