### ISSUE TITLE
Postgres extensions missing after update

### ISSUE THREAD

**Issue by KirioXX** [supabase/cli#766]
# Bug report

## Describe the bug

Updated today my CLI version and now pg_jsonschema is missing.

## To Reproduce

1. update CLI to the latest version (1.28.4)
2. start a development server
3. open the extensions page in supabase studio
4. search for pg_jsonschema

## Expected behaviour

The same extensions are available locally as hosted.

## System information

- OS: macOS
- Version of supabase-cli: 1.28.4

**Comment by sweatybridge** [comment]
Hey thanks for reporting this issue. Our upstream [postgres build](https://github.com/supabase/postgres/actions/workflows/dockerhub-release.yml) has been failing. I will update the cli image once that's fixed.
