### ISSUE TITLE
Make it possible to create ts seed scripts intead of just sql

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#77]
# Feature request

Currently when creating a new project with `supabase init` a `supabase` folder is created with `seed.sql`. I don't know if `seed.sql` can be used yet actually but it would be great if we could write seed scripts in typescript/javascript as well (or instead).

**Comment by soedirgo** [comment]
I saw this asked before: https://github.com/supabase/cli/issues/66. I think the most flexible is to just run a custom command.

**Comment by mr-bjerre** [comment]
That's a fair point. Might just have it as docs / cookbook
