### ISSUE TITLE
Can I pull production tables & data in localhost with the CLI?

### ISSUE THREAD

**Issue by gkatsanos** [supabase/cli#775]
People who're onboarded to supabase via the web UI (like myself) usually start with creating a project, and a table, via the UI. 
I created some dummy data as well so I can experiment with it before setting up anything locally.

Next, I initialized the supabase cli and to my understanding there's no 'shortcut' to pull this table and data just created locally. 

I assume one needs to manually dump and import this data.

Would be cool if `supabase` cli could do this.

**Comment by sweatybridge** [comment]
You can try the following command

```
supabase db diff --linked
```

**Comment by gkatsanos** [comment]
> You can try the following command
> 
> ```
> supabase db diff --linked -f my_table
> ```

for now I used `dbeaver` , it has an export to another table functionality. Short how-to:
1. use supabase start to start your local dev/db
2. create two connections with dbeaver, one in local and one in supabase remote ( you can find the JDBC url in your database settings)
![image](https://user-images.githubusercontent.com/1768834/211273462-3cf70833-7f57-458e-adcc-8cc5cea9b490.png)
![image](https://user-images.githubusercontent.com/1768834/211273111-a75c60fb-9dac-4d78-b722-06daa551d5cc.png)
4. go to 'export' sub-menu of your remote database table, pick the first option 
![image](https://user-images.githubusercontent.com/1768834/211272838-2bf84cb5-484c-4281-a36e-c4c743cf586f.png)
5. set your target container to be the local database
![image](https://user-images.githubusercontent.com/1768834/211272933-32f0f4f2-ce3d-4986-b2bf-eb7860ae2863.png)
