### ISSUE TITLE
supabase db push --dry-run doesn't correctly test migrations

### ISSUE THREAD

**Issue by yoont4** [supabase/cli#776]
# Bug report

## Describe the bug

Generally when a command uses the `dry-run` property, it will show the computed result of _if_ something is applied. But with `db push --dry-run`, it only shows what migration files haven't be pushed. I would expect it to validate if the migrations are valid without actually applying them, and output the same thing as a regular run.

This is **extremely** useful for running migration checks as part of CI, so pull requests can validate that any migrations in it will succeed before actually applying them. The recommended way to handle migrations across environments is to have an action that applies the migration _after_ the merge, but that can easily put the repo in a state where the code has the migration change in the target branch while the supabase project does not (because it failed).

Alternatively, maybe I am misinterpreting what `--dry-run` is for, and what I'm looking for is some `--test` flag. If that fits better, I would be very happy to use that flag 😄 

And even further as an alternative, if there was some way for the github action to cache the docker(?) image for `supabase start`, that would also work I think. Right now it takes 3-5 minutes for it to download every time, even though starting and applying it is maybe a couple seconds.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new migration `pnpm supabase migration new this_should_fail`
2. Put invalid SQL in it like `abcdef` or `alter table i_do_not_exist add column dummy text`
3. Run `pnpm supabase db push --dry-run`

## Expected behavior

I would expect it to output the same thing as `pnpm supabase db push` (other than the this will not be applied message):
```
Pushing migration 20230108110451_this_should_fail.sql...
Error: ERROR: syntax error at or near "abcdef" (SQLSTATE 42601)
At statement 0: abcdef
```

Instead, it prints this:

```
$ pnpm supabase db push --dry-run
DRY RUN: migrations will *not* be pushed to the database.
Would push migration 20230108110451_this_should_fail.sql...
```

Where it says "would push migration...", when in fact, it would **not** push that to the DB.

## System information

- OS: Windows
- Version of Node.js:18

**Comment by sweatybridge** [comment]
Hello, thanks for the suggestion. I agree it would be nice to perform this check with `--dry-run`. However, it's blocked on a few implementation details.

For one, CLI doesn't do any client side sql validation, so checking for syntax error would require actually sending that statement to a postgres server.

An alternative is to wrap the migration file in a transaction and rollback at the end of dry run. But since we support pushing multiple migration files in one command, rolling back would mean that subsequent migration files could fail.

The current recommendation is to run `db start` in your CI before `db push`. This command starts a postgres container locally and runs all migrations to ensure they are valid. In addition, you can also lint and unit test your schemas before pushing to remote project.

Putting them all together:

```bash
supabase db start
supabase db lint
supabase db test
supabase db push
```

Hope it helps.

**Comment by yoont4** [comment]
Thank you for the information, I did not know about the `db lint` command, will take a look at it.

One thing for my use case, I am primarily trying to speed up the testing in our CI pipeline, as we are using `supabase db start` to test PRs before allowing merges. But the issue is that it takes several minutes for the images to get downloaded, while the actual migrations take a few seconds to run. Across multiple projects and many rapid PRs, it starts to pull a lot of hours into our GitHub actions. Was just looking for ways to have it run faster for both cost and dev-experience.

I think we can easily adopt a workflow of getting that tested locally, but for regular code changes/PR feedback, it will still result in a new CI run each time. As an alternative, if there was some supabase configuration/utility that allowed the GitHub actions to cache the docker image for a faster run-time, that would be cool too 😄  

Curious for your final thoughts 🎩

**Comment by sweatybridge** [comment]
We looked into caching in a similar request here https://github.com/supabase/setup-cli/issues/88#issuecomment-1370519155

The best we can do right now is to exclude unnecessary containers from starting. Using setup-cli@v1 and `db start` should reduce your ci time to around 1 min.

**Comment by yoont4** [comment]
Thank you @sweatybridge, we are using `setup-cli@v1` as of right now and it is definitely better than no CI, so I appreciate the work being done there! We still see it running for a few minutes, but I will see if we have some configuration error on our part.

**Comment by sweatybridge** [comment]
@yoont4 just an update: we have further reduced the size of `supabase/postgres` image so it should start much faster on CI now (around [1m40s](https://github.com/supabase/setup-cli/actions/runs/4319609210/jobs/7538977572) for the full stack).
