### ISSUE TITLE
Gen Types with `--db-url` doesn't work with local, non-CLI DB

### ISSUE THREAD

**Issue by carderne** [supabase/cli#777]
# Bug report
## Describe the bug
I'm running Supabase locally with the [docker-compose config](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) (i.e. I never ran `supabase start`).
This doesn't work:
```bash
supabase gen types typescript --db-url postgresql://postgres:password@$localhost:54322/postgres
```
Because the script runs in a container, and therefore doesn't know what `localhost` means.
If I run it with `--debug`, I get `Error: connect ECONNREFUSED`.

## To Reproduce
1. `git clone git@github.com:supabase/supabase.git`
2. `cd supabase/docker`
3. `docker compose up`
4. `supabase gen types ...` but with the password from the `.env` in that repo

## Workaround
I'm doing the following:
```bash
DOCKER_HOST_IP=$(echo $(docker run --rm alpine nslookup host.docker.internal) | sed 's/.* //')
```
And then using that.

## Potential solution
In the script, in the Docker container, if `localhost` is passed as the HOST, you could run `nslookup host.docker.internal` for me to avoid this kludge... :)

## System information
- OS: macOS
- Version of CLI: 1.29.3

**Comment by carderne** [comment]
Problem mentioned previously here https://github.com/supabase/cli/issues/380#issuecomment-1297723638

**Comment by felixwochnick** [comment]
If you want to generate the typescript types of a local Docker environment, you can run the command in the container (default: supabase-meta) of the supabase/postgres-meta image:

`docker exec supabase-meta node /usr/src/app/bin/src/server/app.js gen types typescript --include-schemas public,auth,realtime,storage > supabase/types.ts`

**Comment by sinianzhiren** [comment]
> 如果你想生成本地Docker环境的typescript类型，可以在supabase/postgres-meta镜像的容器（默认：supabase-meta）中运行命令：
> 
> `docker exec supabase-meta node /usr/src/app/bin/src/server/app.js gen types typescript --include-schemas public,auth,realtime,storage > supabase/types.ts`

after run command, is a empty type.ts ?
