### ISSUE TITLE
cli logs remote database url when generating types

### ISSUE THREAD

**Issue by ff6347** [supabase/cli#780]
When using the types generator from the cli with the` --db-url` flag for example like this:

```bash
supabase gen types typescript --db-url postgresql://postgres:postgrss@localhost:54321/postgres
```

The cli logs the remote url. This could be considered harmful when used on ci servers.

https://github.com/supabase/cli/blob/f43145bfbde74f984ed15e578129ceb750dafd8f/internal/gen/types/typescript/typescript.go#L59

**Comment by sweatybridge** [comment]
Thanks for highlighting this issue. It is fixed in the latest release.
