### ISSUE TITLE
[Actions] github action publishes to npm before the releases are finished

### ISSUE THREAD

**Issue by kageurufu** [supabase/cli#783]
# Bug report

## Describe the bug

The Release action publishes a new package to npm before the Github release is completed. This leads to broken installs for a time period until the release is complete

## To Reproduce

1. During a release action, `npm install` the new supabase version
2. watch it fail

## Expected behavior

The npmjs release should happen after the github release is finished

**Comment by sweatybridge** [comment]
Thanks for reporting. Tagging another related issue https://github.com/supabase/setup-cli/issues/115

**Comment by probablykasper** [comment]
CI broken for the past hour because of this with the new v1.40 release
