### ISSUE TITLE
Flag to allow `supabase start` to return code 0 if another container is already running

### ISSUE THREAD

**Issue by WesleyYue** [supabase/cli#787]
# Feature request

## Is your feature request related to a problem? Please describe.

For various reasons, it's helpful to be able to be able to run `supabase start` and have it start the containers if there are no containers running, perform no-op and return success if containers are already running, and fail if it's failing for some other reason (cannot connect to docker daemon).

## Describe the solution you'd like

Either:
- Different return code if it's exited because containers are already running (instead of returning exit code 1)
- Flag to make the CLI return code 0 even if containers are already running

## Describe alternatives you've considered

- Running `supabase stop` every time before start. This is not a good solution for the case where we have a `yarn dev` command that spins up all the services, since if there is already a supabase instance, it might have some changes that the developer hasn't written to a permanent migration script yet and we don't want to just kill and delete all the changes.

**Comment by sweatybridge** [comment]
> start the containers if there are no containers running, perform no-op and return success if containers are already running, and fail if it's failing for some other reason

Thanks for the suggestion. Instead of adding a new flag, I will make this the default behaviour.
