### ISSUE TITLE
Fail to generate types from Supabase CLI

### ISSUE THREAD

**Issue by pybern** [supabase/cli#802]
# Bug report

## Describe the bug
Following the documentation [Generating types using Supabase CLI](https://supabase.com/docs/guides/api/generating-types), I am unable to find the correct version in the docs and I hit the `supabase start is not running` error when trying to generate types.

## To Reproduce

1. Go to [docs](https://supabase.com/docs/guides/api/generating-types)
3. Run `npm i supabase@">=1.8.1" --save-dev`
4. Run `npx supabase login`
5. Run `npx supabase gen types typescript --project-id "$PROJECT_ID" --schema public > types/supabase.ts`
6. **See error** ```Error: supabase start is not running.
Try rerunning the command with --debug to troubleshoot the error.```
7. Run `npx supabase start`
8. **See error** ```Error: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.       
  in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:48
  in github.com/supabase/cli/internal/start.Run:34
Try rerunning the command with --debug to troubleshoot the error.```

## Expected behavior

supabase.ts types are generated in defined folder

## System information

- OS: Windows
- Browser (if applies) Not applicable
- Version of supabase: 1.34.2

**Comment by sweatybridge** [comment]
`$PROJECT_ID` is an environment variable that you should replace with your own project id. It looks like this env var is evaluating to an empty string, which caused the CLI to generate against local database instead.

Can you set the env var `PROJECT_ID` and retry?

**Comment by pybern** [comment]
Thanks . Resolved. Will suggest edits to documents when I have the time.
