### ISSUE TITLE
supabase functions serve failing due to read-only volume mount

### ISSUE THREAD

**Issue by Benjamin-Dobell** [supabase/cli#806]
# Bug report

## Describe the bug

> Starting supabase/functions/generate-applicants-csv
> Serving supabase/functions/generate-applicants-csv
> Watcher Process started.
> Check file:///home/deno/functions/generate-applicants-csv/index.ts
> **error: Read-only file system (os error 30)**
> Watcher Process finished. Restarting on file change...

Seems to be related to download of imports.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new function locally with supabase CLI v1.34.5
2. Make `index.ts` content the following:
  ```ts
  import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
  serve(async req => {
    return new Response(JSON.stringify({}), { headers: { "Content-Type": "application/json "}});
  });
  ```
4. `pnpm exec supabase functions serve function-name`

If the above doesn't reproduce, try introduce an additional import e.g.

```ts
import { stringify } from "https://deno.land/std@0.168.0/encoding/csv.ts";
```

## Expected behavior

Server should start listening.

## System information

- OS: macOS
- supabase CLI: 1.34.5

## Additional context

If I execute the relay container manually with:

> docker run --name=supabase_deno_relay_prequel-portal --hostname=7f185be5ce49 --user=deno --env=JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long --env=DENO_ORIGIN=http://localhost:8000 --env=VERIFY_JWT=true --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=DENO_DIR=/deno-dir/ --env=DENO_INSTALL_ROOT=/usr/local --volume=/Users/ben/Development/Prequel/prequel-portal/supabase/functions:/home/deno/functions:z --volume=/Users/ben/Development/Prequel/prequel-portal/supabase/functions/import_map.json:/home/deno/import_map.json:z --network=supabase_network_prequel-portal --workdir=/app --expose=8081 --label='com.supabase.cli.project=prequel-portal' --label='com.docker.compose.project=prequel-portal' --runtime=runc --detach=true public.ecr.aws/supabase/deno-relay:v1.5.0 run --allow-read --allow-net --allow-env src/index.ts

i.e. make the volume mount read/write rather than read only. Then I proceed to `deno run` within the container manually, everything is as expected.

However, and here's where I'm admittedly a bit stumped, if I execute the container regularly again (`ro`) then subsequent builds using just the same imports are fine. That would seem to imply a cache somewhere, but I'm not seeing where that's configured.

**Comment by Benjamin-Dobell** [comment]
Okay. It seems the problem is that deno is attempting to write a `deno.lock` file to disk. If one already exists and is up to date, then it doesn't attempt to do so.

This explains the weird behavior I saw with follow up builds using the original read only container working just fine _until_ I proceed to introduce an additional dependency.

**Comment by whollacsek** [comment]
In my case I have a `deno.json` in the functions folder, deleting the file made it work again

**Comment by sweatybridge** [comment]
Thank you for reporting this issue. I've updated the CLI to use rw mount in the latest release.
