### ISSUE TITLE
npm install supabase not working (missing file or directory for node_modules/supabase/bin/supabase

### ISSUE THREAD

**Issue by spotvin42** [supabase/cli#807]
# Bug report

## Describe the bug

When installing the supabase npm package, it fails to install.

## To Reproduce

npm install supabase --save-dev

## Error Message

` ENOENT  ENOENT: no such file or directory, chmod '${project_folder}/node_modules/supabase/bin/supabase'`

## System information

- OS: [Windows]
- Version of Node.js: [18.13.00] - although also does it with v16

**Comment by sweatybridge** [comment]
Hello, could you also report the npm version for me to reproduce?

**Comment by brandongregoryscott** [comment]
I'm experiencing this issue when trying to install v1.34.5, and it seems to happen as far back as v1.27.0. I am able to install v1.26.10 fine, so it might be related to https://github.com/supabase/cli/commit/738b8ecf0ad76828452856a1c9078f62878230e9

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/Brandon/beets/node_modules/supabase/bin/supabase
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Brandon/beets/node_modules/supabase/bin/supabase'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Brandon/.npm/_logs/2023-01-29T02_17_12_376Z-debug.log
```

**Comment by sweatybridge** [comment]
@brandongregoryscott could you share the `npm --version` you are using? I think this shouldn't happen on v8+ but just want to confirm

**Comment by brandongregoryscott** [comment]
Ah, good catch - I'm using npm v7.24.2 right now. Seems to work on npm v8.

**Comment by sweatybridge** [comment]
Thank you for confirming. I will close this issue then.
