### ISSUE TITLE
Get "Error: conn busy" when running db remote set with 0.13.0

### ISSUE THREAD

**Issue by brettatoms** [supabase/cli#81]
# Bug report

When running `supabase db remote set <url>` it prints the following error:
```
Error: conn busy
```

## Describe the bug

See above.  

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. cd <existing project created with supabase 0.12.4>
2. Run `supabase start`
3. Run `supabase db remote set postgresql://...`
4. Should see error message

## Expected behavior

The local database should be linked to the remote database

## System information

- OS: macOS 
- Version of supabase-js: 1.28.2
- Version of Node.js: 14.16.0

**Comment by fponticelli** [comment]
I am experiencing the same behavior. Thank you for reporting.

**Comment by clouedoc** [comment]
I have the same problem, thanks for reporting too.

Version information:

```console
➜  opinionshift git:(feat-devcontainer) ✗ supabase --version
0.15.1
```

**Comment by soedirgo** [comment]
Thanks for reporting! Turns out this happens irrespective of which CLI version the project was initialized with. Let me know if the issue persists.
