### ISSUE TITLE
`supabase functions deploy foobar` doesn't work with `signal: abort trap`

### ISSUE THREAD

**Issue by t-east** [supabase/cli#815]
# Bug report

## Describe the bug
I can't deploy edge function to remote.
```
 supabase functions deploy foobar --debug
```
 But I can delete functions on remote from cli
```
supabase functions delete foobar
```
and, I can use any `supabase db` command

## Error Message
```
Version 1.28.0 is already installed
Bundling foobar
Error: Error bundling function: signal: abort trap
file:///src/import_map.json
file:///src/index.ts
...
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
```
## To Reproduce
1. uninstall supabase-cli 
```
brew uninstall supabase
```
2. reinstall cli
```
brew install supabase/tap/supabase
```
3. deploy exist function
```
supabase functions deploy foobar
```

## System information
- OS: [M1 macOS]
- Version of supabase-cli: [1.35.0]
- Version of deno: [1.30.0]
- Version of Node.js: [18.7.0]

Thank you

**Comment by yuzhanglong** [comment]
I have the same problem. How did you solve it?

**Comment by soedirgo** [comment]
@yuzhanglong can you try following the steps here? https://github.com/supabase/cli/issues/673#issuecomment-1341879953

**Comment by yuzhanglong** [comment]
> @yuzhanglong can you try following the steps here? [#673 (comment)](https://github.com/supabase/cli/issues/673#issuecomment-1341879953)

yes，it works！

thank you！
