### ISSUE TITLE
No output after entering access token for npx supabase login

### ISSUE THREAD

**Issue by ahmetkca** [supabase/cli#819]
# Bug report

## Describe the bug
I run the `npx supabase login` and enter the access token but it just hangs no output or anything then I terminate with `Ctrl+c`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: Ubuntu 20.04 on WSL2
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]
- supabase cli version: 1.35.0

**Comment by ahmetkca** [comment]
I think the problem is that there is no progress indicator so I thought it wasn't responding  and hang. I think a progress bar with what's going on would be nice to see when you run the command

**Comment by stan-dot** [comment]
I also am experiencing the problem. it's first time login using Supabase CLI

**Comment by karlo-supatrooper** [comment]
Hey @stan-dot ~ `npx supabase login` currently works on the latest version. Can you try updating your Supabase CLI to the latest version v1.38.6? Let me know if that works. Thanks.

**Comment by sweatybridge** [comment]
Thanks for reporting. This issue happens on WSL because CLI tries to store the access token in freedesktop secret service which doesn't exist on WSL. The temporary workaround is to specify your access token via environment variable. For example

```bash
SUPABASE_ACCESS_TOKEN=<token> supabase start
```

**Comment by wowczarczyk** [comment]
> Thanks for reporting. This issue happens on WSL because CLI tries to store the access token in freedesktop secret service which doesn't exist on WSL. The temporary workaround is to specify your access token via environment variable. For example
> 
> ```shell
> SUPABASE_ACCESS_TOKEN=<token> supabase start
> ```
> 
> If you are on native windows, macOS, or linux, please let me know as that would be something else.

No, that did not work, still hangs

**Comment by sweatybridge** [comment]
@wowczarczyk which command did you run exactly? Login is optional if you specify the access token env var. 

I will close this as won't fix to focus on the related ticket on `supabase link` command.

**Comment by seminull** [comment]
This makes supabase cli essentially unusable on wsl, unless you prefix calls that require the access token in this fashion.  I suppose the command hangs looking for this secret service, then falls back to just checking your env after several minutes? I'm sure that is presumptuous, but I spent a lot of time blaming my connection and in retrospect, I wish it just gave some message on why it took so long to ask for my project ref.  I have since written a bash script that just wraps my supabase calls with the token & project ref.
