### ISSUE TITLE
Error restoring main: branch was not dumped.

### ISSUE THREAD

**Issue by waynebloss** [supabase/cli#823]
# Bug report

After running `npx supabase start` I received the message `Error restoring main: branch was not dumped.`.

## Describe the bug

I am wondering if there's a bug due to the fact that my git repository has a `master` branch and not a `main` branch? The `supabase/.branches/_current_branch` was automatically set to `main`...

The error is occurring on a brand new project with no changes to the database.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. (Maybe optional?) Start a repo with default branch named `master`.
2. `npm add supabase --save-dev`
3. `npx supabase init`
4. `npx supabase stop`
5. (Maybe optional?) Move your `./supabase` folder somewhere else in the repo, like I did and then `cd to/parent-of` the `supabase` directory.
6. `npx supabase start`

## Expected behavior

No error and branch names match git repo.

## System information

- OS: Linux
- Browser: none
- Version of supabase-cli: ^1.34.5
- Version of Node.js: 16.18.0

## Additional context

I'm just curious about the cause. I don't think this error has prevented my from doing anything at this time and Supabase continued on to successfully run locally after this error. Thanks!

**Comment by waynebloss** [comment]
OK I didn't search the issue well enough. I see the answers here https://github.com/supabase/cli/issues/139#issuecomment-1016790536

**Comment by sweatybridge** [comment]
Apologies for the confusion. We addressed a similar issue in 1.35.0. Related to this PR https://github.com/supabase/cli/pull/820

The error logged is indeed misleading and shouldn't be printed.

**Comment by waynebloss** [comment]
@sweatybridge Thanks! I'll try it out.
