### ISSUE TITLE
Generated types has an array type for a database Function that returns a table

### ISSUE THREAD

**Issue by AlexDunmow** [supabase/cli#842]
# Bug report

Generated types for functions that return a table are erroneously an array type.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create PG Function that returns a table:

```sql
create or replace function blog_posts(post_author_username text)
    returns table
            (
                id                  bigint,
                created_by          uuid,
                created_by_username text
            )
as
$body$
select np.id,
       np.created_by,
       p.username created_by_username
FROM public.news_posts np
         inner join public.profiles p on np.created_by = p.id
where p.username = post_author_username;
$body$ language sql;
```

3. generate types: `supabase gen types typescript --local > ./src/types/database.types.ts`
4. query db:

```typescript
type ArrayElement<ArrayType extends readonly unknown[]> = ArrayType extends readonly (infer ElementType)[]
	? ElementType
	: never

export type NewsPost = ArrayElement<Database["public"]["Functions"]["blog_posts"]["Returns"]>

...

const [posts, setPosts] = useState<NewsPost[]>([])
useEffect(() => {

useEffect(() => {
	const fetchData = async () => {
		const { data, error } = await supabase.rpc("blog_posts", { post_author_username: username })
		setPosts(data || [])
	}

	// call the function
	fetchData().catch(console.error)
}, [])
```

5. Breaks because generated type is

```
blog_posts: {
   Args: { post_author_username: string }
      Returns: {
          id: number
          created_by: string
          created_by_username: string
        }[]
      }
   }
```

## Expected behavior

Generated type should not be an array type. Works fine if [] is deleted. 

## System information

- supabase --version: `1.34.5`
- Version of Node: `v18.13.0`

**Comment by soedirgo** [comment]
Hey @AlexDunmow, I think this is related to https://github.com/supabase/postgrest-js/pull/394. Can you try `npm update @supabase/postgrest-js` and see if that fixes it?

**Comment by TimoWilhelm** [comment]
Same issue here. I dont have a reference to `@supabase/postgrest-js` in my project. I guess we need to wait for a new version of the `supabase` npm package to be published?

**Comment by soedirgo** [comment]
Sorry, I should've been clearer: `@supabase/supabase-js` has `@supabase/postgrest-js` as a dependency - presumably you'd have an older version of `@supabase/postgrest-js` in your `package-lock.json`, and updating the package should fix it.

**Comment by soedirgo** [comment]
Resolved in https://github.com/supabase/postgrest-js/pull/394
