### ISSUE TITLE
Latest CLI versions not in sync with other Supabase releases

### ISSUE THREAD

**Issue by drewbietron** [supabase/cli#848]
With new releases of other repos such as Postgres and pg_graphql, the CLI isn't in sync with the lastest versions which makes local development challenging. 

I'm unable to have parody between environments and more importantly am not able to test new features from new releases in the packages that are installed via the CLI before shipping them to production. 

Not sure what the best solution would be, but maybe more options to the config.toml that could set explicit versions of the packages that are installed?

Thanks

**Comment by drewbietron** [comment]
Tried to push a change to `internal/utils/misc.go` to update the PG15 image to the latest version of supabase/postgres (15.1.0.37) but looks like permissions are set to not send any pull requests.

Lots of nice changes have gone into the postgres repo since the PG15 image thats currently pinned in this CLI and it would  great to be able to put all the great work to use!

Thanks

**Comment by soedirgo** [comment]
That's odd - we've received PRs recently so you should be able to open one. I'll create a PR to update the image.

As for syncing the local db image and the one on the platform: this is trickier to solve because there are a number of things to iron out (e.g. not all images used on the platform is available as a Docker image because of build failures etc.).

**Comment by soedirgo** [comment]
Actually, I just checked the linked pg_graphql issue and can confirm that the current latest CLI version uses pg_graphql 1.1.0. Is it not the case for you? Can you try resetting the local dev setup (`supabase stop && supabase start`)?

**Comment by drewbietron** [comment]
> Actually, I just checked the linked pg_graphql issue and can confirm that the current latest CLI version uses pg_graphql 1.1.0. Is it not the case for you? Can you try resetting the local dev setup (`supabase stop && supabase start`)?

I couldn't find a declared version of pg_graphql anywhere in the CLI repo.  1.1.0 of pg_graphql was merged into a release of supabase/postgres thats after the version pinned in main in the CLI.

**Comment by soedirgo** [comment]
The specific version of pg_graphql is tied to the `supabase/postgres` image version, which is `15.1.0.33` as you linked. `15.1.0.33` should have pg_graphql 1.1.0 installed: https://github.com/supabase/postgres/blob/57bb5bcbe3347601a9368472c7c703e7a48e2dcf/ansible/vars.yml#L101

**Comment by soedirgo** [comment]
I'll close this issue since the updated pg_graphql is on the latest CLI version - feel free to comment here if that isn't the case.
