### ISSUE TITLE
Error starting Docker Containers with CLI on MacOS

### ISSUE THREAD

**Issue by alew3** [supabase/cli#856]
# Bug report

## Describe the bug

When trying to start local docker containers with the the CLI command 
``supabase start``
 on the Mac I get the error, even though docker is running:

``Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:40 in github.com/supabase/cli/internal/start.Run:43 ``

I think this is happening because:

- Docker Desktop for Mac removed /var/run/docker.sock per 4.13.0 Release Notes: https://docs.docker.com/desktop/release-notes/#docker-desktop-4130 "By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead."
The workaround I found to get it working is to manually create the symlink:
``sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock``

System information
OS: MacOS Ventura 13.2
Supabase CLI: 1.10.2

**Comment by soedirgo** [comment]
Can you try upgrading Docker Desktop? I think this is the same issue as https://github.com/supabase/cli/issues/167#issuecomment-1288213488

Or you can set the `DOCKER_HOST` as noted in that thread.

**Comment by sweatybridge** [comment]
> Re-added the /var/run/docker.sock on Mac by default, to increase compatibility with tooling like tilt and docker-py.

This has also been addressed in newer docker desktop versions https://docs.docker.com/desktop/release-notes/#4140

I will close this as won't fix but let me know if you are still having problems after updating docker.
