### ISSUE TITLE
Error: Error response from daemon: No such image: supabase/studio:latest

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#86]
Now I'm excited about this new release but currently we get the following error when starting

> Error: Error response from daemon: No such image: supabase/studio:latest

Also: do we need to change anything due to [this update](https://github.com/supabase/supabase/releases/tag/0.20.11.30)?

**Comment by mr-bjerre** [comment]
I tried running `docker pull supabase/studio:latest` and then starting. That only works partially - studio exits...

```
❯ docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                   CREATED              STATUS                          PORTS                                                                  NAMES
ef3b843c8fcc   supabase/studio:latest                   "docker-entrypoint.s…"    About a minute ago   Exited (1) About a minute ago 
```

**Comment by soedirgo** [comment]
Hmm, seems to be because `supabase/studio` is arm64-only on Docker Hub. I'll disable this as a temporary fix, will enable once it's resolved.

**Comment by soedirgo** [comment]
This should now be fixed by https://github.com/supabase/cli/commit/59245bbb98cd9847075dbb8e455aad84de938152 and `linux/amd64` is also available on Docker Hub. Let me know if it works!

**Comment by ndhaniff** [comment]
It works on pop! OS 21. had to use `docker pull --platform linux/amd64 supabase/studio:latest `  then supabase start

**Comment by soedirgo** [comment]
Hmm you shouldn't need to `docker pull` manually though, the commit above fixes that. I'll keep this open in case it still doesn't work OOTB.

**Comment by mr-bjerre** [comment]
Working in ubuntu as well
