### ISSUE TITLE
Running supabase-cli docker env on a Hackintosh

### ISSUE THREAD

**Issue by iam4x** [supabase/cli#868]
# Bug report

## Describe the bug

My setup is:

(https://github.com/sergeycherepanov/homebrew-docker-virtualbox)

- custom docker-machine image
- running into virtualbox
- forwarding ports from docker to host using virtualbox

![image](https://user-images.githubusercontent.com/893837/219065075-4cb6c711-c0de-4b98-9081-1452e4c1cabe.png)

## To Reproduce

- run any supabase-cli commands that involve using `host-gateway`

## Expected behavior

- maybe have a config where we can override `host-gateway` to our value

## Screenshots

![image](https://user-images.githubusercontent.com/893837/219065506-4ff45038-6685-43c2-aab7-e01686f0e8a6.png)
![image](https://user-images.githubusercontent.com/893837/219065622-eb5ecddb-d3cc-4f0e-a114-57c33b8bba96.png)

## System information

- AMD Ryzen Hackintosh macOS BigSur
- using https://github.com/sergeycherepanov/homebrew-docker-virtualbox to run docker

**Comment by sweatybridge** [comment]
Could you try updating docker? The host-gateway is supported in 20.03 and above https://github.com/docker/cli/issues/2664

**Comment by sweatybridge** [comment]
Since we are not planning to support old versions of docker, I would close this issue as won't fix.
