### ISSUE TITLE
Serving multiple functions and calling supabase-js createClient causes error

### ISSUE THREAD

**Issue by grschafer** [supabase/cli#869]
# Bug report

## Describe the bug

Using the supabase-js `createClient` function in an edge function and serving it locally with the new "serve all edge functions" CLI command causes an error.

As a separate note, it seems that "serve all edge functions" removes the authorization header requirement. Perhaps this should be a separate bug report, let me know!

## To Reproduce

Set up a new project:

```
mkdir supabase-cli-playground2
cd supabase-cli-playground2
supabase init
supabase start
supabase functions new foo
```

Edit `supabase/functions/foo/index.ts` to have the following content:

```
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.8.0";

console.log("Hello from Functions!");

serve(async (req) => {
  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

  return new Response("ok");
});
```

Serve all functions:

```
supabase functions serve
```

In a separate terminal, curl the function and get a `502 Bad Gateway` response:

```
$ curl -v -X POST 'http://localhost:54321/functions/v1/foo'
*   Trying 127.0.0.1:54321...
* Connected to localhost (127.0.0.1) port 54321 (#0)
> POST /functions/v1/foo HTTP/1.1
> Host: localhost:54321
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Date: Thu, 16 Feb 2023 01:26:51 GMT
< Content-Type: application/json; charset=utf-8
< Connection: keep-alive
< Content-Length: 75
< X-Kong-Upstream-Latency: 39
< X-Kong-Proxy-Latency: 0
< Via: kong/2.8.1
< 
{
  "message":"An invalid response was received from the upstream server"
* Connection #0 to host localhost left intact
}

```

The `supabase functions serve` terminal shows the following:

```
worker thread panicked ReferenceError: _eventHandlers is not defined
    at get ([js_worker]: bootstrap.js:144:19)
    at Window.get [as onerror] (https://esm.sh/v106/es5-ext@0.10.62/esnext/global.js:11:19)
    at https://esm.sh/v106/es5-ext@0.10.62/esnext/global.js:46:35
```

If I instead specifically serve the foo function:

```
supabase functions serve foo
```

And make the curl request, then I get the expected 401 response with body `Missing authorization header`.

If I comment out the `createClient` call from `index.ts`, serve all edge functions, and make the curl request, then I get a 200 response with body `ok`, so it seems that serving all functions also removes the authorization header requirement.

## Expected behavior

I would expect edge functions to behave the same whether they're served via `supabase functions serve foo` or `supabase functions serve`.

## System information

- OS: Ubuntu 22.04
- Version of supabase-js: 2.8.0
- Version of supabase-cli: 1.38.2
  - edge-runtime:v1.0.9
  - kong:2.8.1
- Version of docker: 23.0.1

## Additional context

A separate thought: it'd be nice to see what's going on in the `edge-runtime` docker image and associated binary, similar to how you've open sourced dockerfiles and contents of other images used by the CLI.

**Comment by laktek** [comment]
@grschafer Can you try updating to Supabase CLI version 1.38.3? It should fix the above issue.

**Comment by grschafer** [comment]
@laktek That fixes the above issue, thank you! I've opened a separate bug report for the authentication issue (https://github.com/supabase/cli/issues/873), so it can be tracked separately from this issue.

**Comment by laktek** [comment]
@grschafer Thanks! yeah, we'll be fixing that next. Closing this issue.
