### ISSUE TITLE
`supabase start` fails when launched inside a container

### ISSUE THREAD

**Issue by clouedoc** [supabase/cli#87]
# Bug report

## Describe the bug

When running Supabase inside a Docker container with a docker-host-socket to container setup (container has access to the host's Docker socket), when running `supabase start`, Supabase tries to bind a volume from the host into another container.

```console
➜  opinionshift git:(feat-devcontainer) supabase start 
Error: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/workspace/opinionshift/supabase/.temp/userlist.txt" to rootfs at "/etc/pgbouncer/userlist.txt" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
➜  opinionshift git:(feat-devcontainer) 
```

## Reproduction

See [reproduction repository](https://github.com/clouedoc/supabase-docker-reproduction)

## System information

- OS: Docker container inside a Linux host

### Faulty code

https://github.com/supabase/cli/blob/59245bbb98cd9847075dbb8e455aad84de938152/internal/start/start.go#L716-L720

and

https://github.com/supabase/cli/blob/59245bbb98cd9847075dbb8e455aad84de938152/internal/start/start.go#L676-L683

## Possible solutions

- [ ] using volumes instead of filesystem binds (note: there might be networking issues too)
- [x] using Docker in Docker

## Checklist for PR creator

- [ ] removing filesystem bindings
- [ ] checking that sibling container-to-container communications work

**Comment by soedirgo** [comment]
Thanks for the report! Running in Docker isn't supported atm, but if it can work w/o too much hassle I have no problem with that.

**Comment by bajosiaa** [comment]
instead of docker from docker, I used docker in docker and it works.
![image](https://user-images.githubusercontent.com/48413508/144595689-ff1b8c95-ae93-456b-8257-54307a112fd5.png)

**Comment by clouedoc** [comment]
> instead of docker from docker, I used docker in docker and it works.
@bajosiaa thank you so much! I didn't think that VSCode's devcontainers supported this natively.

**Comment by roman-perroquet** [comment]
@turkerdev & @clouedoc  by any chance, have you tried docker-outside-docker and run supabase?

I get failed to connect to postgres: failed to connect to `host=127.0.0.1 user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)

and I wonder which config option to change to host.docker.internal in order for supabase start to properly.

Thanks

P.S. sorry for reviving an old bug :)
