### ISSUE TITLE
supabase start fails on running migrations for the first time

### ISSUE THREAD

**Issue by tmcw** [supabase/cli#870]
# Bug report

## Describe the bug

I'm trying to set up my project for the first time on localhost

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run `supabase start`

## Expected behavior

It successfully runs migrations

## Screenshots

The migration crashes with the following error, that looks internal to supabase and unrelated to my application

https://gist.github.com/tmcw/22f94a49ef3076afc1693ebdcaa2cdb2

## System information

- OS: macOS
- Version of supabase-cli: 1.38.2
- Version of Node.js: v18.12.1

**Comment by sweatybridge** [comment]
Thanks for reporting! This is probably due to mismatched postgres image version between hosted and local. The new CLI release should have resolved this issue.

Feel free to reopen if it is still happening.
