### ISSUE TITLE
Supabase link should have better UX when --project-ref isn't provided

### ISSUE THREAD

**Issue by tmcw** [supabase/cli#878]
# Bug report

## Describe the bug

You look for supabase commands:

```
val.town git:(main) ✗ supabase
Supabase CLI 1.38.5

Usage:
  supabase [command]

Local Development:
  db                   Manage local Postgres databases
  gen                  Run code generation tools
  init                 Initialize a local project
  link                 Link to a Supabase project
```

You run supabase link, and it asks for a database password:

```
val.town git:(main) ✗ supabase link
Enter your database password:
```

You provide that password, and you get this error:

```
Error: Invalid project ref format. Must be like `abcdefghijklmnopqrst`.
```

What's a project ref? Where is it specified? How is it invalid, and what's its current value? The answer is that you need to do:

```
supabase link --project-ref=xxx
```

There is no suggestion that you need to do this and the error message does not guide you.

## Expected behavior

If `--project-ref` is a required parameter, which it appears to be, there should be an error message showing that it's missing and saying to provide it as `--project-ref`, rather than an error about it being in the wrong format.

- Supabase CLI version 1.38.5

**Comment by sweatybridge** [comment]
Thank you for reporting this issue. It was introduced by a previous refactor which messed up the order of project-ref arg validation. I have addressed it in the linked PR.

**Comment by neuquen** [comment]
It is still not clear to me what the project-ref is supposed to contain.  Can that be clarified here and updated in the documentation?

**Comment by neuquen** [comment]
It is still not clear to me what the project-ref is supposed to contain. Can that be clarified here and updated in the documentation?

UPDATE: I found example usage [here](https://github.com/supabase/setup-cli#advanced-usage) which is great, but I still think the help text needs added clarification.

**Comment by Jonnotie** [comment]
I just ran into this issue as well

**Comment by kkukshtel** [comment]
I also missed this — the flag should be changed to project-id to match that it's the project ID, and more explicitly called out that it's just the string of letters in the project url on supabase (no idea if it's available elsewhere).

**Comment by landsman** [comment]
> I also missed this — the flag should be changed to project-id to match that it's the project ID, and more explicitly called out that it's just the string of letters in the project url on supabase (no idea if it's available elsewhere).

exactly

**Comment by sweatybridge** [comment]
In the beta release, we added an interactive prompt if project-ref flag is not specified when running supabase link.

**Comment by Carles11** [comment]
Yes, very unclear what is expected. This is how it worked for me:
1.- supabase link --project-ref xxxx (xxxx is the reference ID from supabase general Settings)
2.- "Enter your database password (or leave blank to skip):" (need to type it, copy/pasting it did not work)

**Comment by samsslee** [comment]
@Carles11 this is 100% what worked for me, thank you so much. Typing instead of copy/pasting did the trick!

**Comment by mattarderne** [comment]
2024 and if you're still confused, because of the following instruction (now baked into LLM assistant memory)

`supabase link --project-ref your-project-ref`

You're looking for Project ID
Project Settings > General settings > **Project ID**
