### ISSUE TITLE
Support installing via pnpm

### ISSUE THREAD

**Issue by vhpx** [supabase/cli#885]
# Bug report

## Describe the bug

Supabase CLI v1.38.7's postinstall script failed to run.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install supabase@1.38.7 via pnpm i
2. See error at postinstall step

## Expected behavior

It should install the package normally, upgrading from previous version or a clean installation does not fix this problem.

## Screenshots

![image](https://user-images.githubusercontent.com/81307469/220852356-c7a48f60-4cd3-4d2e-b5c2-4025c0b3e5aa.png)

## System information

- OS: Windows 11 22H2 (Build 22621.1265)
- supabase-js: v1.38.7
- node.js: v19.6.0
- pnpm cli: v7.27.1

**Comment by sumardi** [comment]
Same here. Running on macOS M1 pro.

```
npm ERR! code 1
npm ERR! path /Users/smd/Workspace/twodia-app/node_modules/supabase
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! Downloading https://github.com/supabase/cli/releases/download/v1.38.7/supabase_darwin_arm64.tar.gz
npm ERR! node:events:490
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: incorrect header check
npm ERR!     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
npm ERR! Emitted 'error' event on Gunzip instance at:
npm ERR!     at Gunzip.onerror (node:internal/streams/readable:785:14)
npm ERR!     at Gunzip.emit (node:events:512:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -3,
npm ERR!   code: 'Z_DATA_ERROR'
npm ERR! }
npm ERR! 
npm ERR! Node.js v19.6.0
```

**Comment by arpadgabor** [comment]
@sweatybridge getting a related error with a fresh install, Windows 11 in WSL2, Node 18 and 16, pnpm 7.28.0

```
WARN  Failed to create bin at /home/arpad/work/mvp/node_modules/.bin/supabase. The source file at /home/arpad/work/mvp/node_modules/supabase/bin/supabase does not exist.
```

And looking in node modules, it seems like the `postinstall` script was not executed as the `bin` folder is empty.

**Comment by sweatybridge** [comment]
I will try to reproduce with pnpm. In the mean time, are you able to use yarn or npm?

**Comment by arpadgabor** [comment]
I've managed to get it working with homebrew so it's not urgent. By the way, is the cli not usable if installed globally? Because I was getting weird issues even when installed globally or used directly with `npx` without installing in the repository

**Comment by sweatybridge** [comment]
The recommended way to install globally is via one of the supported system package managers.

> or used directly with npx without installing in the repository
Do you have the logs when running directly with npx?

**Comment by arpadgabor** [comment]
This was all I could get:
```
❯ npx supabase
Need to install the following packages:
  supabase@1.40.4
Ok to proceed? (y) 
sh: 1: supabase: not found
```
But it now works with homebrew 👍 

> The recommended way to install globally is via one of the supported system package managers.

Maybe it's useful to add a warning in the readme about this? I don't mind using another package manager, but as a CLI I kind of expect it to work even if installed globally.

**Comment by sweatybridge** [comment]
I managed to reproduce the warning on pnpm: https://github.com/supabase/cli/actions/runs/4312324665/jobs/7522749949

It's harmless ignore it as the postinstall succeeded anyway. Subsequent `npx supabase --version` successfully finds the binary in path.

**Comment by iwo9** [comment]
I've been trying to install supabase through npm for a while:
supabase@1.148.6
Ok to proceed? (y) y
npm http fetch GET 200 https://registry.npmjs.org/supabase 10ms (cache hit)
....
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 431ms
npm info run supabase@1.148.6 postinstall node_modules/supabase node scripts/postinstall.js
npm info run supabase@1.148.6 postinstall { code: 1, signal: null }    
npm verb exit 1
npm verb unfinished npm timer reify 1710324795538
npm verb unfinished npm timer reify:build 1710324796370
npm verb unfinished npm timer build 1710324796371
npm verb unfinished npm timer build:deps 1710324796371
npm verb unfinished npm timer build:run:postinstall 1710324796381      
npm verb unfinished npm timer build:run:postinstall:node_modules/supabase 1710324796382
npm verb code 1

and then it just ends. Idk why it isn't working

**Comment by reubendrummond** [comment]
Important to note here: do not run `pnpm install` with with `--ignore-scripts` flag.

**Comment by khakimme** [comment]
npx supabase init

sh: supabase: command not found

**Comment by michaelaflores** [comment]
Similar to @khakimio, I'm still observing that `npx supabase init` command fails. Noting it rather than only thumb up-ing because it's been 8 months so worth noting this is still an issue. The docs for [Generating Types](https://supabase.com/docs/guides/api/rest/generating-types) ask that this command be run, so it's unexpected.

**Comment by semiautomatix** [comment]
```bash
$ pnpm supabase init
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "supabase" not found

$ npx supabase
sh: 1: supabase: not found
```

Still a problem?

**Comment by semiautomatix** [comment]
```bash
 WARN  Failed to create bin at /node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/node_modules/.bin/supabase. ENOENT: no such file or directory, open '/node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/bin/supabase'
 WARN  Failed to create bin at /node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/node_modules/.bin/supabase. ENOENT: no such file or directory, open '/node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/bin/supabase'
 WARN  Failed to create bin at /node_modules/.bin/supabase. ENOENT: no such file or directory, open '/node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/bin/supabase'
 WARN  Failed to create bin at /node_modules/.bin/supabase. ENOENT: no such file or directory, open '/node_modules/supabase/bin/supabase'
```

**Comment by KilianSL** [comment]
This issue is still outstanding using pnpm v10.10.0 in a turborepo project. 

```
 WARN  Failed to create bin at /var/home/kilian/Repos/seo-bot/apps/web/node_modules/.bin/supabase. ENOENT: no such file or directory, open '/var/home/kilian/Repos/seo-bot/node_modules/.pnpm/supabase@2.22.6/node_modules/supabase/bin/supabase'
```

**Comment by inouetakuya** [comment]
Try `pnpm approve-builds`

- pnpm v10.8.1
- supabase v2.22.12

```
$ pnpm approve-builds
✔ Choose which packages to build (Press <space> to select, <a> to toggle all, <i> to invert selection) · supabase
✔ The next packages will now be built: supabase.
Do you approve? (y/N) · true
node_modules/.pnpm/supabase@2.22.12/node_modules/supabase: Running postinstall script, done in 1.9s
```

```
$ pnpm supabase --version
2.22.12
```

It works! :tada:

**Comment by obiscr** [comment]
Have same issue

https://github.com/supabase/cli/issues/885#issuecomment-2829399450

**Comment by gblikas** [comment]
> Try `pnpm approve-builds`
> 
> * pnpm v10.8.1
> * supabase v2.22.12
> 
> ```
> $ pnpm approve-builds
> ✔ Choose which packages to build (Press <space> to select, <a> to toggle all, <i> to invert selection) · supabase
> ✔ The next packages will now be built: supabase.
> Do you approve? (y/N) · true
> node_modules/.pnpm/supabase@2.22.12/node_modules/supabase: Running postinstall script, done in 1.9s
> ```
> 
> ```
> $ pnpm supabase --version
> 2.22.12
> ```
> 
> It works! 🎉

Does **not** work for me with 

```bash
$ pnpm --version
10.22.0
```

and 

```
    "supabase": "^2.58.5",
```

**Comment by sacsand** [comment]
This  worked for me! 

rm -rf node_modules/.pnpm/supabase* && pnpm remove supabase && pnpm add -D supabase

**Comment by kalenmike** [comment]
Confirming a combination of the last two resolved the issue for me.

#### Cleanup

```bash
rm -rf node_modules/.pnpm/supabase* # remove folder
pnpm remove supabase # remove from pnpm
```

#### Install

```bash
pnpm add -D supabase # install package as dev dependecy
pnpm approve-builds # allow the post install script to run
```

#### Validate

```bash
pnpm exec supabase --version # confirm installation
```
