### ISSUE TITLE
Type generation from dashboard or CLI results in error

### ISSUE THREAD

**Issue by Gravy59** [supabase/cli#887]
# Bug report

## Describe the bug

When I try to generate types from the supabase dashboard I get this inexplicable error. Unfortunately, since my instance of supabse is self hosted with docker, I can't use the cli to generate types instead.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an instance of supabase using the self hosting instructions
2. Add some dummy data/tables
3. Click on "API Docs"
4. Click on "introduction"
5. Click "Generate & Download Types"
6. Get an error wall

## Expected behavior

I expected to have types generated from my tables.

## Screenshots

![](https://cdn.discordapp.com/attachments/1078766959384068138/1078766959803510925/image.png)

## System information

- OS: MacOS
- Browser (if applies) Brave
- Version of supabase-js: 2.8.0
- Version of Node.js: 19.4.0

## Additional context

N/A

**Comment by soedirgo** [comment]
Hey @Gravy59, you can use `supabase gen types typescript --db-url` to generate types from your self-hosted database.

**Comment by Gravy59** [comment]
I'm unable to do that because I get a connection refused error.

`supabase gen types typescript --db-url "postgresql://postgres:your-super-secret-and-long-postgres-password@localhost:5432/postgres"` gives me an `ECONNREFUSED`. I haven't modified any base settings in supabase, and I've tried using `postgresql://` and `postgres://`.

**Comment by soedirgo** [comment]
Hmm, could be because the typegen itself is running from a container, so `localhost` doesn't resolve to the host. Can you try replacing `localhost` with `host.docker.internal`? (I'm assuming you use Docker Desktop.)

**Comment by Gravy59** [comment]
That solved the issue for me. Thanks!
