### ISSUE TITLE
init command hangs if no git repo initialized in folder

### ISSUE THREAD

**Issue by realfresh** [supabase/cli#89]
# Bug report

## Describe the bug

The init command hangs if no git repo initialized in folder

## To Reproduce

1. Create new folder
2. Run `supabase init`

## Expected behavior

Prompt the user that git must be initialized in the folder

## System information

- OS: Windows
- Version of supabase-js: 0.15.2
- Version of Node.js: 14.4

**Comment by soedirgo** [comment]
That's odd, this shows me:
```
❯ supabase init
Error: Cannot find Git root. Are you in a Git repository?
```

Most likely a path handling issue, but I don't have a Windows machine to test this.

**Comment by redraskal** [comment]
Can confirm this issue is present on Windows. Running `git init` solves the issue

**Comment by redraskal** [comment]
Working on a fix- will submit a PR shortly
