### ISSUE TITLE
v1.40 release failed

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#893]
The release CI failed for v1.40: https://github.com/supabase/cli/actions/runs/4289730620/jobs/7473058224

This caused v1.40 to be released with no binary, breaking every CI that uses [supabase/setup-cli](https://github.com/supabase/setup-cli) with `version: latest`

Related to #783

**Comment by sweatybridge** [comment]
Thanks for reporting. #783 should be fixed now

closing duplicate.
