### ISSUE TITLE
supabase db remote commit errors with Postgis

### ISSUE THREAD

**Issue by nickreese** [supabase/cli#894]
# Bug report

## Describe the bug

`supabase db remote commit` doesn't work.

Returns:

```
pg_dump: error: query failed: ERROR:  permission denied for table direction_lookup
pg_dump: detail: Query was: LOCK TABLE "tiger"."direction_lookup" IN ACCESS SHARE MODE
```

## To Reproduce

* Supabase instance.
* Install `postgis`
* Run the command.

## Expected behavior

It would write the schema.

## System information

- OS: macOS. Homebrew supabase.

**Comment by nickreese** [comment]
Thanks for the quick turn around. Just did `brew reinstall supabase` and it appears this has not been released.

**Comment by nickreese** [comment]
OK, currently on `1.40.1`.

1. `brew upgrade supabase`

```
supabase/tap/supabase 1.40.1 already installed
```

2. `supabase db remote commit`

```
Dumping schemas from remote database...
pg_dump: error: query failed: ERROR:  permission denied for table direction_lookup
pg_dump: detail: Query was: LOCK TABLE "tiger"."direction_lookup" IN ACCESS SHARE MODE
Error: Error running pg_dump on remote database: error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by sweatybridge** [comment]
Could you try `brew update` first before upgrade?

The tap seems to be updated successfully to v1.40.3 https://github.com/supabase/homebrew-tap

**Comment by nickreese** [comment]
1. `brew upgrade supabase`

```
==> Upgrading supabase/tap/supabase
  1.40.1 -> 1.40.3 
```

2. `supabase db remote commit`

```
Dumping schemas from remote database...
pg_dump: error: query failed: ERROR:  permission denied for table direction_lookup
pg_dump: detail: Query was: LOCK TABLE "tiger"."direction_lookup" IN ACCESS SHARE MODE
Error: Error running pg_dump on remote database: error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

3. `supabase -v`

```
1.40.3
```

**Comment by nickreese** [comment]
OK, thanks. I saw the same issues with the flags as well.

Any options to get local dev working? I'm working on a major new push and without local dev I'm going to be lost.

Advice here? I'm stuck.

**Comment by sweatybridge** [comment]
Could you email support@supabase.com with your project ref? We can apply this fix for you manually to unblock.

**Comment by sweatybridge** [comment]
We have completed the rollout to all existing projects. Could you let me know if `remote commit` is still stuck?

I will close this ticket as resolved but feel free to reopen.
