### ISSUE TITLE
CLI doesnt connect to the database via --db-url

### ISSUE THREAD

**Issue by vacavaca** [supabase/cli#903]
# Bug report

## Describe the bug

I'm running a self-hosted version of supabase. My postgres container exposes its port at 127.0.0.1:5433 but the CLI throws a "connection refused" error when I'm trying to generate types.

## To Reproduce

```bash
supabase gen types typescript --debug --db-url postgresql://postgres:12345@127.0.0.1:5433/postgres --schema public > database.types.ts

# ...
Error: connect ECONNREFUSED 127.0.0.1:5433
    at file:///usr/src/app/dist/server/app.js:67:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
# ...
```

To verify the postgres instance is reachable:

```bash
docker run --rm -it --network host postgres psql --host 127.0.0.1 -p 5433 -U postgre

Password for user postgres:
psql (15.1 (Debian 15.1-1.pgdg110+1), server 14.6 (Debian 14.6-1.pgdg110+1))
Type "help" for help.

postgres=> \dt
             List of relations
 Schema |  Name   | Type  |     Owner
--------+---------+-------+----------------
 public | profile | table | supabase_admin
 public | role    | table | supabase_admin
(2 rows)

postgres=>
```

## Expected behavior

CLI connects to the database and generates types

## System information

- OS: macOS Ventura 13.1
- Version of supabase-js: 1.41.1
- Version of Node.js: 18.14.1

---

I suspect the problem is related to docker networking.

**Comment by sweatybridge** [comment]
Hi @vacavaca, typegen runs within a docker container so you will need to replace 127.0.0.1 with docker.internal.host to reach your host network.

**Comment by vacavaca** [comment]
```
Error: Connection terminated due to connection timeout
    at file:///usr/src/app/dist/server/app.js:67:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Tryied "docker.internal.host", "172.21.0.2"

Here is my docker inspect for the database container, the networks section:

```json
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "567adfddb37a334ecde4838642015f6e1685c30835c4c0307071adb14cf2fa10",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5432/tcp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "5433"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/567adfddb37a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "local_app": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "supabase-db",
                        "db",
                        "1282b1c41494"
                    ],
                    "NetworkID": "bcc59753c37835bd844e3761dce191d32cee60fde27d865f5c075af4ff57c119",
                    "EndpointID": "eef01dcf3a80231100867b6ab6250b0fa079120f0929374c698f122951b5155c",
                    "Gateway": "172.21.0.1",
                    "IPAddress": "172.21.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:15:00:02",
                    "DriverOpts": null
                }
            }
        }
```

**Comment by vacavaca** [comment]
"host.docker.internal" works.

However, it was a bit surprising that a "CLI" application uses some arbitrary bridge network (the default docker bridge) and not the "host" network (lo). For example, when I run `psql` or `redis-cli` or some nodejs script, I expect it to reach every network endpoint that I can reach by running `curl` in the same terminal. But apparently, supabase-cli requires a very specific configuration to reach the database. Maybe it would be better to run all the containers in the "host" networking mode to make the CLI work more conventionally. What do you think?

**Comment by sweatybridge** [comment]
It's probably sufficient to run the one-off pgmeta container in host network only when `--db-url` flag is passed to typegen. That would solve for your use case of behaving similarly to psql client. 

I'm not sure if there's a strong use case for other containers to be on the host network too.

**Comment by vacavaca** [comment]
I agree, using the host networking only with `--db-url` would be enough.
