### ISSUE TITLE
Studio can't connect to default project

### ISSUE THREAD

**Issue by jeramiahgcoffey** [supabase/cli#904]
# Bug report

## Describe the bug

I am using the CLI to run a local instance for development. I am trying to access Studio but it cannot connect to the database.
Dev tools show a 404 response when reaching out to `http://localhost:54323/api/projects/default/api/rest`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1.  `yarn supabase init`
2.  `yarn supabase start`
3. Navigate to http://localhost:54323
4. Connection to default project unsuccessful, see 404 response in the console

## Expected behavior

Studio should connect to the project.

## System information

- OS: [Windows 11, Docker for WSL2]
- Version of supabase-js: [e.g. 1.41.1]
- Version of Node.js: [e.g. 18.13.0]

**Comment by arthur5005** [comment]
Experiencing exactly this, to the letter, except on:
- OS: [macOS Monterey 12.3]
- Docker [Desktop for Mac 20.10.23]
- Supabase cli: [1.41.1]
- Node: [19.7.0]

First time supabase user just want to get local development going for functions. Tried to change ports around, try on a fresh directory where I set everything back up and I re-linked and everything. 

Aside, if you try and access the parent url:
`http://localhost:54323/api/projects/default` 

it does respond with something seemingly meaningful.

```json
{"id":1,"ref":"default","name":"Default Project","organization_id":1,"cloud_provider":"localhost","status":"ACTIVE_HEALTHY","region":"local","inserted_at":"2021-08-02T06:40:40.646Z","connectionString":"","kpsVersion":"kps-v1.0.0","restUrl":"http://localhost:54321/rest/v1/"}
```

where as `http://localhost:54323/api/projects/default/api/rest` yields a 404

**Comment by schwindelig** [comment]
Looks like this has been introduced with `1.41.1`. Connecting fine with `1.41.0`

**Comment by arthur5005** [comment]
Amazing turnaround time. Thank you :)

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. I've reverted studio to last known good version CLI 1.41.3 (releasing in a few mins).

**Comment by jeramiahgcoffey** [comment]
Fantastic thank you very much!
