### ISSUE TITLE
The storage API is returning a 404

### ISSUE THREAD

**Issue by daver182** [supabase/cli#908]
# Bug report

## Describe the bug

The storage api is not working. I just installed the supabase-cli on a new MacBook and the storage is not working, I'm getting a 404 error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `supabase init`
2. `supabase start`
3. Go to buckets `http://localhost:54323/project/default/storage/buckets`
4. On the screen is a 404 error. On the toast, the whole 404 page is shown.
5. The call to `http://localhost:54323/api/storage/default/buckets` is returning a 404.

## Expected behavior

There should be a list of current buckets and the ability to create new ones.

## System information

- OS: macOS Ventura, v13.2.1
- Version of Node.js: v18.14.2

**Comment by mbashiq** [comment]
Hey there, I'm also facing the same issue that you have described.

Supabase cli v 1.41.6
Installed via brew
MacOs 13.1 (22C65)

**Comment by sweatybridge** [comment]
Thanks for reporting this bug. I've reverted studio image to a last known working version.
