### ISSUE TITLE
Not receiving MagicLink emails from local supabase instance

### ISSUE THREAD

**Issue by mclean25** [supabase/cli#93]
# Bug report

## Describe the bug

I'm running Supabase locally and trying to login the way I do in prod via MagicLink. The request goes through as a `200` and a row is added to the `auth.user` table, but no email is ever received. Also seems to be something weird going on with the `instance_id` but maybe that's because I can't fully login.

![image](https://user-images.githubusercontent.com/7105182/144764888-2269391f-6c01-4d85-9440-1b0b0aca8e7a.png)
![image](https://user-images.githubusercontent.com/7105182/144764962-9cfca80b-0c26-470d-ad2c-2791ec77beb6.png)

## To Reproduce

Run Supabase locally and attempt to login with MagicLink 

## Expected behavior

Receive email so you can login.

## System information

- OS: MacOS
```
├─ @supabase/gotrue-js@1.19.0
├─ @supabase/postgrest-js@0.34.1
├─ @supabase/realtime-js@1.2.1
├─ @supabase/storage-js@1.4.1
└─ @supabase/supabase-js@1.25.2
```

**Comment by soedirgo** [comment]
Can you try setting `ports.inbucket` to some random port in `supabase/config.json`? Custom SMTP is not possible for the CLI atm.

**Comment by mclean25** [comment]
Yes, it's the CLI. Sorry for opening in the wrong spot.

I don't have a `ports.inbucket`. This is what my `config.json` looks like:
```
{
  "projectId": "figure",
  "ports": {
    "api": 54321,
    "db": 54322,
    "studio": 54323
  },
  "dbVersion": "130003"
}
```

I didn't modify any of this. Is there supposed to be a `ports.inbucket` there?

**Comment by soedirgo** [comment]
It's optional, you can add it in `ports`. Sorry for the lack of docs on this one, will fix that soon 🙏

**Comment by mclean25** [comment]
I tried a couple random port numbers, `54324` and `3245` but neither worked. Still not receiving any email. When I changed the `config.json`, I re-ran `supabase start` and `yarn dev` both times, and it did list the `inbucket` port for me:

```
> supabase start                                                           2m 45s
Started local development setup.
API URL: http://localhost:54321
DB URL: postgresql://postgres:postgres@localhost:54322/postgres
Studio URL: http://localhost:54323
Inbucket URL: http://localhost:3245
anon key: ...
service_role key: ...
```

**Comment by soedirgo** [comment]
Does updating the CLI to v0.15.6 fix it? There was an issue with Postgres 14 that makes auth & storage nonfunctional.

On v0.15.6 I managed to receive the magic link:
<img width="2032" alt="Screen Shot 2021-12-10 at 12 01 02 AM" src="https://user-images.githubusercontent.com/31685197/145431664-3df1876e-8164-44f7-861f-d2bf3da1f5b8.png">

My config:
```json
{
  "projectId": "pls",
  "ports": {
    "api": 54321,
    "db": 54322,
    "studio": 54323,
    "inbucket": 54324
  },
  "dbVersion": "140001"
}
```

Btw, the email doesn't actually get sent to the recipient - it's a local dev server so we just want to see if the emails come through just right. The web interface on `Inbucket URL` does just that.

**Comment by mclean25** [comment]
Well, that makes a lot of sense. Shamefully, I expected the email to show up in my inbox but this makes much more sense now that I think about it. 

Things are working as intended!

**Comment by iAmWillShepherd** [comment]
I ran into this issue as well. I expected the link to be emitted to my CLI. It's not super clear from the getting started guide that you can test email, but I'm glad it's here.

**Comment by soedirgo** [comment]
Noted :+1:

To be clear this is on me that the docs fall short - will keep improving it in the coming weeks.

**Comment by joshdance** [comment]
I had this same issue, no magiclink getting emailed. 

Turns out I had the wrong Supabase URL in my .env file. Check that if you are not getting emails.

**Comment by joshdance** [comment]
@o1Suleyman get your own SMTP provider it makes it way easier than the heavily throttled one.

**Comment by o1Suleyman** [comment]
> @o1Suleyman get your own SMTP provider it makes it way easier than the heavily throttled one. 

I figured it out, I just needed to set send emails to true in config.toml
