### ISSUE TITLE
Can not commit local change to remote Supabase project

### ISSUE THREAD

**Issue by piggy0713** [supabase/cli#936]
# Bug report

## Describe the bug

I am encountering issues while deploying my local development to Supabase. I followed the instructions provided in the [documentation](https://supabase.com/docs/guides/cli/local-development#link-your-project).

When I tried to run ```supabase db remote commit```, I received the following error message: ```Error: Remote database is not set. Run supabase db remote set first```.

I then attempted to set the remote database using the command ```supabase db remote set postgresql://postgres:[password]@db.[projectid].supabase.co:5432/postgres```, but encountered another error: ```Error: Remote database Postgres version 15 is incompatible with db.major_version 14. If you are setting up a fresh Supabase CLI project, try changing db.major_version in supabase/config.toml to 15```.

After changing db.major_version to 15 and rerun the command, I encountered the error: ```Error: Failed reading config: Invalid db.major_version: 15```.

I find this to be a frustrating first-time experience with Supabase. Could you please assist me in resolving this issue?

## System information

- OS: macOS 12.6.3
- Hardware: Macbook m1
- Supabase CLI 0.31.2
- Version of Node.js:  16.18.1

**Comment by sweatybridge** [comment]
Hi @piggy0713, could you update CLI to the latest version and try again? ie. `brew upgrade supabase`

**Comment by sweatybridge** [comment]
In that case, you want to run `npm i --save-dev supabase` instead. Let me know if it works

**Comment by piggy0713** [comment]
I think my supabase is 1.42.7, I run the ```npm i ---savve-dev supabase```, but there is no update.

**Comment by sweatybridge** [comment]
I think you might have supabase installed both system wide and as dev package. Can you try `npx supabase db remote commit`? That would use the dev package installed via npm.

**Comment by piggy0713** [comment]
interesting, thank you for your help, I think that might be the problem; how do I delete the system-wide superbase

**Comment by sweatybridge** [comment]
> how do I delete the system-wide superbase

Depends on how you installed it, what's the output of `which supabase`?

If it's a npm global module, you can uninstall by `npm uninstall -g supabase`.
