### ISSUE TITLE
Error: service not healthy, when starting supabase for local development

### ISSUE THREAD

**Issue by mcandylab** [supabase/cli#937]
# Bug report

## Describe the bug

When starting ```supabase start``` I get an error ```Error: service not healthy: [supabase_rest_ploi]```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. ```npx supabase login```
2. ```npx supabase init```
3. ```npx supabase start```

## Expected behavior

I expect supabase to start and display the connection settings

## Screenshots

![img](https://i.imgur.com/Ksy7AY4.png)

## System information

- OS: Ubuntu Server 22.04
- Version of supabase-js: -
- Version of Node.js: v18.15.0
- Version of Supabase CLI: 1.42.7

## Additional context

docker running as root

**Comment by sweatybridge** [comment]
Hi @mcandylab how much memory do you have available on the VM? Smaller RAM could delay startup. I would probably suggest 4GB to be on the safe side.

If that's not possible, you can start with `--ignore-health-check` flag.

**Comment by mcandylab** [comment]
> Hi @mcandylab how much memory do you have available on the VM? Smaller RAM could delay startup. I would probably suggest 4GB to be on the safe side.
> 
> If that's not possible, you can start with `--ignore-health-check` flag.

The server has 32 GB of RAM and 12 physical cores. However, the problem still persists
