### ISSUE TITLE
Local Development: Renaming folder in studio not working

### ISSUE THREAD

**Issue by boptom** [supabase/cli#940]
# Bug report

## Describe the bug

When renaming a folder in local development using Studio an error occurs.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Init a project with `supabase init`
2. Start local dev with `supabase start`
3. Navigate to the Studio URL, buckets: `http://localhost:54323/project/default/storage/buckets`
4. Create a bucket
5. Create a folder
6. Rename the folder
7. "Failed to move" error appears. It refers to the file `.emptyFolderPlaceholder`

This seems to happen if the folder is empty, or if a nested folder is empty. Uploading a file to the folder allows renaming it successfully.

Note: This does not occur on production at app.supabase.com

## Expected behavior

Renaming the folder should rename the folder without errors.

## Screenshots

N/A

## System information

- OS: MacOS Ventura 13.2.1
- Browser: Chrome
- Version of supabase-js: N/A
- Version of Node.js: 18.0.0

## Additional context

N/A

**Comment by sweatybridge** [comment]
This has been fixed on latest version of CLI.
