### ISSUE TITLE
Large requests to edge functions are fully buffered, rather than streamed

### ISSUE THREAD

**Issue by grschafer** [supabase/cli#949]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using the CLI, large requests to an edge function appear to be completely buffered then delivered all at once, rather than being streamed to the edge function. This doesn't match the behavior in production (on supabase.com), which makes local development and testing more difficult.

I'm not sure what is the culprit ... maybe kong/nginx?

## To Reproduce

```
mkdir stream-to-edge-function
cd stream-to-edge-function
supabase init
supabase functions new hello-world
```

Replace the contents of `supabase/functions/hello-world/index.ts` with the following:

```
import { serve } from "https://deno.land/std@0.180.0/http/server.ts";

serve(async (req) => {
  const body = req.body!;

  let totalSize = 0;
  let numChunks = 0;
  for await (const chunk of body) {
    console.debug("got chunk", chunk.length);
    numChunks++;
    totalSize += chunk.length;
  }

  return new Response(JSON.stringify({ numChunks, totalSize }));
});
```

Test locally:

```
# In one terminal, run the below 2 commands
supabase start
supabase functions serve

# In another terminal, run the following:
# Make a 64 MiB file
fallocate -l 64M /tmp/64MiB.file
# Upload it to the function slowly (1 MB per second)
curl -L --limit-rate 1M -X POST http://localhost:54321/functions/v1/hello-world --upload-file /tmp/64MiB.file --output /dev/stdout

# Container logs seem quiet, other than kong which prints a line like the below when the request is first issued.
# To print the logs, run the command: `docker logs -n 10 -f supabase_kong_stream-to-edge-function`
2023/03/21 23:30:57 [warn] 1122#0: *6245 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000001, client: 172.22.0.1, server: kong, request: "POST /functions/v1/hello-world HTTP/1.1", host: "localhost:54321"

# The `supabase functions serve` won't show any output until the upload completes (after ~1 minute)
# at which point it prints 1000+ lines of "got chunk 65536" (the exact number varies).
```

Test in production:

```
supabase functions deploy hello-world --project-ref <YOUR-PROJECT-REF>

# In the supabase dashboard, I disabled "Enforce JWT Verification"

# Make the same request as before
curl -L --limit-rate 1M -X POST 'https://YOUR-PROJECT-REF.functions.supabase.co/hello-world' --upload-file /tmp/64MiB.file --output /dev/stdout

# In the supabase dashboard you can see the log messages in the
# edge function's Logs tab over the full duration of the curl command.
```

So, the takeaway is that something in between curl and the edge function is waiting for the full upload request to finish before passing the request to the edge function for processing and a response. I'm not sure what that something is. I haven't tested to see if uploads to storage-api are similarly buffered.

## Expected behavior

It would be ideal if the local development environment provided by the Supabase CLI matched the behavior in production more closely -- that is, large requests (such as file uploads) are available to edge functions as a stream while the request is in flight, rather than blocking/buffering the request until it is fully received before becoming available to edge functions.

I'm not too familiar with kong or nginx to know if they're the culprit and some configuration around streaming could be set that would fix this.

## System information

- OS: Ubuntu 22.04.2 LTS
- Supabase CLI: 1.44.0
- Docker: 23.0.1
- Docker image:
    - kong:2.8.1
    - edge-runtime:v1.1.1

## Additional context

As a workaround, I'll probably be using deno directly and manually injecting supabase variables, e.g.:

```
SUPABASE_URL=http://localhost:54321 SUPABASE_ANON_KEY=eyJh... deno run --allow-net=:8000 --allow-env hello-world/index.ts
```

and making requests from my frontend manually to deno (localhost:8000) rather than using supabase-js.

**Comment by laktek** [comment]
This could be buffering in Kong. I tried the example directly with the [Edge Runtime](https://github.com/supabase/edge-runtime) container it seems to emit the console.logs for the chunks.

**Comment by grschafer** [comment]
Good to know! So, perhaps this issue will be resolved with no extra effort whenever edge-runtime replaces kong (https://supabase.com/blog/edge-runtime-self-hosted-deno-functions#api-gateway-to-other-supabase-services).

**Comment by laktek** [comment]
Yes! Planning to do that soon. Until we do that, you can directly use Edge Runtime to test large payloads to functions.

Shall I close this issue for now?

**Comment by grschafer** [comment]
Works for me! 👍
