### ISSUE TITLE
Can't sign up after reset

### ISSUE THREAD

**Issue by YousefED** [supabase/cli#960]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to create a new user with supabase-js and the local dev environment in a unit test. Between test runs, I call `supabase db reset`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- `supabase db reset`
- `const { data, error } = await supabase.auth.signUp({
      email: "user1aaa@emailasdf.com",
      password: "password-1",
    });`

Sometimes this works, sometimes I get "error finding user"

output of Auth container:
```
{"component":"api","level":"info","method":"POST","msg":"request started","path":"/signup","referer":"","remote_addr":"172.25.0.1","time":"2023-03-25T03:11:37Z","timestamp":"2023-03-25T03:11:37Z"}

{"component":"api","error":"unable to find identity by email for duplicates: FATAL: terminating connection due to administrator command (SQLSTATE 57P01)","level":"error","method":"POST","msg":"500: Database error finding user","path":"/signup","referer":"","remote_addr":"172.25.0.1","time":"2023-03-25T03:11:37Z","timestamp":"2023-03-25T03:11:37Z"}

{"component":"api","duration":513792,"level":"info","method":"POST","msg":"request completed","path":"/signup","referer":"","remote_addr":"172.25.0.1","status":500,"time":"2023-03-25T03:11:37Z","timestamp":"2023-03-25T03:11:37Z"}
```

## Expected behavior

Sign up should work after a reset. Could it be that the auth server doesn't work well with db resets (e.g.: keeps some users in memory?)

## System information

- OS: macOS
- Version of supabase-js: 2.12.1

**Comment by YousefED** [comment]
Possibly related:

- https://github.com/supabase/cli/issues/146

**Comment by sweatybridge** [comment]
This should be resolved in latest release https://github.com/supabase/cli/pull/1060
