### ISSUE TITLE
Seeding with ~500,000 rows causes public.ecr.aws/supabase/postgres:15.1.0.54-rc0 crash

### ISSUE THREAD

**Issue by timothygorer** [supabase/cli#963]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I try to seed my local supabase instance with ~500,000 rows, the docker instance public.ecr.aws/supabase/postgres:15.1.0.54-rc0 crashes and goes into a boot loop. I also get the error message that the Database is not healthy. I've tried numerous times. I've also tried seeding with snaplet.dev. I usually have to do a supabase stop and supabase start to fix the unhealthy state. Today I had to delete all data from my Docker app after the crash occurred because when I tried supabase start I got the error "dial tcp [::1]:54322: connect: connection refused" even after restarting my laptop. I also gave docker 4 GB swap and 5GB RAM. Previously I had 1 GB swap and 5GB RAM.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. supabase start
2. supabase db reset (make sure seed.sql has hundreds of thousands of rows)

## Expected behavior

Expected my db to have 500,000 rows.

## System information

- Intel Macbook Pro, running MacOS 12.5.1 Monterey

## Additional context

Seems to work if I seed with a subset of the database.

**Comment by sweatybridge** [comment]
Hi @timothygorer, could you share with us the postgres logs when seeding fails? I'm unable to reproduce on CLI 1.50.8 with a seed.sql file containing 600k+ rows.

```bash
docker logs supabase_db_<project>
```

**Comment by sweatybridge** [comment]
We have improved the data seeding code in v1.68.6. Feel free to reopen if this issue still persists.

**Comment by timothygorer** [comment]
Thanks @sweatybridge
