### ISSUE TITLE
Allow supabase stop

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/cli#97]
# Feature request

## Is your feature request related to a problem? Please describe.

I often run `supabase start` and in VS Code terminal and then I close VS Code at some point. This leaves all the containers running in the background. So next time I do `supabase start` I get `Error: listen tcp4 :54321: bind: address already in use`.

## Describe the solution you'd like

Closing the terminal should stop the supabase containers gracefully (not sure if that's possible).

## Describe alternatives you've considered

Otherwise it would be sufficient with a `supabase stop` command to stop the current containers - problem is that this might save state into `supabase/.temp` and `supabase/.branches` even though the containers might come from a different project? 

## Additional context

Currently I manually stop the containers with the following command

```bash
docker stop $(docker ps -aq --filter "name=supabase") && docker rm $(docker ps -aq --filter "name=supabase") 
```

**Comment by bhvngt** [comment]
+1. 

It might be a good idea to `daemonize` `supabase start` cli process. That way it wont lock the terminal. With `supabase stop` one can stop all the containers.

**Comment by varna** [comment]
> +1.
> 
> It might be a good idea to `daemonize` `supabase start` cli process. That way it wont lock the terminal. With `supabase stop` one can stop all the containers.

`supabase stop` would be enough for me.

**Comment by steinroe** [comment]
+1

A nice addition to this request would be a command similar to firebase exec

> Run the script at scriptpath after starting emulators for the Firebase products configured in firebase.json. Emulator processes will automatically stop when the script has finished running.

**Comment by soedirgo** [comment]
`supabase stop` is available now, and `supabase start` is detached and warns if an existing setup on the same project is already started :+1:

**Comment by RobertB4** [comment]
Thanks for adding this feature! Is there anyway to stop the supabase server using the cli? `supabase stop` doesn't just shut down the servers, it also wipes/reset all the data from the db. Yet, if I don't use `supabase stop` the servers never stop running on my machines.

**Comment by soedirgo** [comment]
Related: #150 

The short term fix is to revert the old behavior (i.e. dump the db on `supabase stop`), but I'm currently rethinking the (scarcely documented) "branching" feature so that you dump the db on demand instead (as "snapshots").

I'm currently focused on other projects atm though, so if anyone is up for the fix, a PR would be appreciated!
