### ISSUE TITLE
`supabase db dump --data-only` → `permission denied for table hooks`

### ISSUE THREAD

**Issue by Strajk** [supabase/cli#973]
# Bug report

```bash
PG_CONNECTION_STRING="postgres://postgres:[my-main-password]db.abc123.supabase.co:5432/postgres"
supabase db dump --db-url $PG_CONNECTION_STRING -f schema.sql # works fine
supabase db dump --db-url $PG_CONNECTION_STRING --data-only -f data.sql # fails with error
```

Error
```
pg_dump: error: query failed: ERROR:  permission denied for table hooks
pg_dump: detail: Query was: LOCK TABLE "supabase_functions"."hooks" IN ACCESS SHARE MODE
```

Found related discussions (but without a proper solution IMO)
* https://discord.com/channels/839993398554656828/1086001421138276422/1086074301981151323
* https://github.com/supabase/supabase/issues/10982
* https://discord.com/channels/839993398554656828/1086001421138276422/1086033092000624711

My "hotfix": Found this [script](https://github.com/supabase/cli/blob/main/internal/db/dump/templates/dump_data.sh), added `"supabase_functions"."hooks"` to excluded tables, run manually → works fine for me

## System information

- OS: macOS
- Version of supabase-cli: 1.45.2
- Version of Node.js: 18
- Supabase project id: `gxkegsjkvwmcfdxvthle` -- feel free to admin-check, no sensitive/PII data there

**Comment by soedirgo** [comment]
Thanks for reporting this. Seems to be an issue with how we set up the permissions on your project - I've manually restored it, so the command should work fine now.

**Comment by benjamindonze** [comment]
@soedirgo I'm having the same issue how can this be fixed?

**Comment by soedirgo** [comment]
@benjamindonze can you file a ticket on https://supabase.com/dashboard/support/new?
