### ISSUE TITLE
Local LogFlare docs? 

### ISSUE THREAD

**Issue by evelant** [supabase/cli#982]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)
](https://supabase.com/docs/guides/platform/logs)

## Describe the problem

LogFlare tab was added to the local development environment (awesome!) but there is no documentation. Currently the tab doesn't work, it just fails to show any logs with `LOGFLARE_API_KEY env variables are not set`
 
## Describe the improvement

Local LogFlare usage should be documented

**Comment by sweatybridge** [comment]
We have added logflare setup docs to our local development guide: https://supabase.com/docs/guides/getting-started/local-development#enabling-local-logging
